### ISSUE TITLE
[Doc] Update information about system minimum requirements to install AppFlowy

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1002]
https://github.com/AppFlowy-IO/AppFlowy-Docs/blob/main/essential-documentation/install-appflowy/requirements.md

**Comment by literalEval** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by annieappflowy** [comment]
I assigned https://github.com/AppFlowy-IO/AppFlowy/issues/1120 to you. I'd recommend that you focus on one issue a time :D

**Comment by literalEval** [comment]
Since #1120 is a huge task in itself, I think it will be better if I contribute in small changes first so that I can get used to the code slowly, and finally will work on that issue. Does this sound good to you ?
If yes, then please tell what changes are need in the system requirements doc ?

**Comment by Indrajeet-S** [comment]
@literalEval 
we have to mention requirements of memory, processor, etc... right?

**Comment by Indrajeet-S** [comment]
@annieappflowy

**Comment by MayurSMahajan** [comment]
Is anybody assigned to this issue?

**Comment by Indrajeet-S** [comment]
> Is anybody assigned to this issue?

Nope!!

**Comment by Chirag8023** [comment]
I would like to work on this Issue ! Can I work on it ?
Please assign this issue to me.

**Comment by annieappflowy** [comment]
Thanks, Chirag. Assigned it to you

**Comment by Chirag8023** [comment]
@annieappflowy where to get the data of supported operating systems and the minimum requirements
