### ISSUE TITLE
[FR] Support Obsidian's URI ?

### ISSUE THREAD

**Issue by Connor-yang96** [AppFlowy-IO/AppFlowy#1021]
I want to use AppFlowy in Obsidian for replace markdown table.

So, need AppFlowy support [Obsidian's URI](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI), that can open obsidian's note. with [Text link Feature request](https://github.com/AppFlowy-IO/AppFlowy/issues/1020).

Maybe some obsidian's users need this feature. 

![image](https://user-images.githubusercontent.com/81000027/189485737-0e849c09-3ded-4df2-8d9e-de6bb2bab09e.png)

**Comment by richardshiue** [comment]
Hi @Connor-yang96, this is supported in the latest release, please try it out and tell us how it went!
