### ISSUE TITLE
[Bug] Linux 0.0.5 version doesn't work

### ISSUE THREAD

**Issue by LaBaude32** [AppFlowy-IO/AppFlowy#1022]
**Describe the bug**
I have download the 0.0.5 version but it's does not open on Debian 11. Nothing show up when I clic on the app_flowy icon.
I have tried to lunch it in CLI and I have this error : 
`./app_flowy: error while loading shared libraries: libkeybinder-3.0.so.0: cannot open shared object file: No such file or directory`

**Desktop (please complete the following information):**
 - OS: Debian 11 Gnome 38 Nvidia (driver 470)
 - Version 0.0.5

Thaks for your work and good luck !

**Comment by jonmseaman** [comment]
I had this issue on Ubuntu 22.04 as well. I fixed it by installing the libkeybinder package separately:

```
sudo apt install libkeybinder-3.0-0
```

**Comment by LaBaude32** [comment]
Thx it's work on Debian 11 too !
