### ISSUE TITLE
[Bug] Trim text on sidebar with Ellipsis

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1025]
**Describe the bug**
I'm trying to implement elided text on the sidebar of the application. Currently, I've only made that change on pages, usernames and sub-pages. "Trash" and "New page" do not seem to ever get clipped by the sidebar (in all the existing languages at my resolution), so I've ignored them for now. 

**To Reproduce**
1. Have a long username and/or page with very long names
2. Resize the sidebar to the minimum
3. The text goes on to the next line, or overflows. The second line is mostly visible, but the descenders get cut off. The third line is completely invisible

**Concerns**
1. Do you guys have a particular design in mind?
2. macOS has window control buttons in place of the appflowy logo. Does that decrease the minimum sidebar width?
3. I'm not sure how this translates to other device resolutions.

**Screenshots**
![elided-text](https://user-images.githubusercontent.com/71320345/189519595-6b7683be-0b68-4cf0-8972-ed90062e6a55.png)

**Desktop**
 - OS: Linux
 - main branch

**Comment by appflowy** [comment]
I think it's ok to show the ellipsis if the text out of bound.
