### ISSUE TITLE
[Bug] Need scrolling in Board Page

### ISSUE THREAD

**Issue by ChiragKr04** [AppFlowy-IO/AppFlowy#1027]
**Describe the bug**
In `Board` page we cannot scroll if screen width is smaller.

**To Reproduce**
1. Create new `Board` page.
2. Shrink the app width.
3. Now other cards are not visible.

**Expected behavior**
There should be scrolling behaviour, just like in `Grid` page.

**Screenshots**
Cannot scroll to see other cards.
![image](https://user-images.githubusercontent.com/62651867/189528008-4a32114b-c35d-46ae-89f9-f216708d9be5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - App version: Latest

**Comment by Dev-Owl** [comment]
If you wrap the `AppFlowyBoard` Widget in a `Scrollbar` Widget you get the requested scrollbar (you might want to set `thumbVisibility` to true to always show it). 
What doesn't work out of the box is dragging an item to the edge of the screen and scroll.

**Comment by annieappflowy** [comment]
Not working on Windows 11 pro
Maybe I haven't learnt how to trigger the horizontal scroll


https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/6e82591e-ee64-4e52-b951-d314a9fbeb6a

**Comment by Xazin** [comment]
We spoke shortly about it on discord before the PR was merged, but the horizontal scrollbar should always be visible, and it should fit the design.

The scrollbar should be created using `StyledScrollbar` see `appflowy_flutter\packages\flowy_infra_ui\lib\style_widget\scrolling\styled_scroll_bar.dart`.

The API for it includes the `autoHideScrollbar`, it defaults to `true`, in this case it should be `false`.

**Comment by annieappflowy** [comment]
Shift + mouse scroll works!
