### ISSUE TITLE
[Bug] Navigation keys paste text on Flowy Editor

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#1028]
**Describe the bug**
The keys 'Shift + End', 'Shift + Home', 'Home' & 'End'. Paste the last text node.
Instead of navigating or selecting text, it just pastes the last written text.

**To Reproduce**
1. Run Flowy Editor example
2. Type random text
3. Press the 'Home' or 'End' keys.

**Expected behavior**
The keys will paste the last text node from the previous line.

**Screenshots**

https://user-images.githubusercontent.com/42723553/189528571-64aa8e0b-a37e-4402-8b84-5907116a6398.mp4

**Desktop (please complete the following information):**
 - OS: Manjaro Xfce

**Comment by MayurSMahajan** [comment]
@rileyhawk1417 can we close this issue?
