### ISSUE TITLE
[Bug] Bullet list doesn't cancel when 'Enter' key is pressed twice

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#1029]
**Describe the bug**
When pressing the 'Enter' key twice the bullet list does not cancel.
Unlike with the quote feature it cancels when the user hits the 'Enter key twice.

**To Reproduce**
1. Run Flowy Editor
2. Type and set bullet list style
3. Press the enter key.

**Expected behavior**
The bullet list will still move with the cursor as the user presses the 'Enter' key.

**Screenshots**

https://user-images.githubusercontent.com/42723553/189528912-7215f0c9-9d2c-40de-8549-4f829deff2a4.mp4

**Desktop (please complete the following information):**
 - Manjaro Xfce

**Comment by Xazin** [comment]
@annieappflowy I believe we resolved this recently.


https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/4d6923ef-626c-4a54-8d77-10c1834ab19d

**Comment by annieappflowy** [comment]
Works perfectly!
