### ISSUE TITLE
[Bug] Flowy Editor can't handle large amount of text

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#1030]
**Describe the bug**
Flowy Editor lags when a large amount of text is loaded, or pasted into the editor.

**To Reproduce**
1. Run Flowy Editor
2. Copy and text from a large document then paste into the editor.
3. Scroll down to see responsiveness.

**Expected behavior**
Flowy Editor may feel slow and laggy, when navigating the text.

**Screenshots**

https://user-images.githubusercontent.com/42723553/189529223-d24ab63d-84bc-4a3d-aa4d-81ab969d4898.mp4

**Desktop (please complete the following information):**
 - OS: Manjaro Xfce

**Comment by fangykai** [comment]
I could see if I can get a Manjaro boot running and test this myself as I can't reproduce. How did you install appflowy? From source, the releases page, or from the documentation (not the source one.)

**Comment by annieappflowy** [comment]
> I could see if I can get a Manjaro boot running and test this myself as I can't reproduce. How did you install appflowy? From source, the releases page, or from the documentation (not the source one.)

I believe Sean installed the package via https://pub.dev/packages/appflowy_editor
This is our in-house editor built from the ground up by AppFlowy.
