### ISSUE TITLE
[Bug] Can't delete text or navigate with arrow keys

### ISSUE THREAD

**Issue by joaomarcospinho** [AppFlowy-IO/AppFlowy#1034]
**Describe the bug**
Can't delete any character written, and navigate with arrow keys.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.5.1

**Comment by apomalyn** [comment]
@joaomarcospinho can you tell us, which version of AppFlowy are you using?
Also on which type of page are you (doc, board, grid)? 
I'm also on MacOS and I can use the arrow keys to navigate, select text and delete the selected text.
