### ISSUE TITLE
Recently 0.5 version has been released. but default installation (for macos) guide installs 0.4 version 

### ISSUE THREAD

**Issue by revati** [AppFlowy-IO/AppFlowy#1042]
Title says it all. I yesterday downlaoded it and it is great (y) today noticed there is newer version released.

How on can update cask version? If id knew i could do it my self

https://formulae.brew.sh/cask/appflowy

**Comment by LucasXu0** [comment]
Hi, @revati. I have updated the latest version to Homebrew and set the automatic update. The newest GitHub release will be automatically synchronized to homebrew.

https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/appflowy.rb
