### ISSUE TITLE
[FR]  Reduce the time threshold after holding down on the header before the column reordering action is triggered

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1043]
**1~3 main use cases of the proposed feature**
I would like to reorder the columns in the grid. Currently, the same behavior can be achieved by renaming and then changing the property type, but that is quite burdensome. It would be nice to simply drag and drop the header row from one position to another. Additionally, the grid's primary column cannot be deleted or assigned to another column, which also impacts usability.

**what types of users can benefit from using your proposed feature**
Any users who wish to reorder the grid's column order at a later date.

**Comment by annieappflowy** [comment]
Hi @richardshiue , thanks for reporting the issue you encountered. If I understand your needs correctly, actually the columns can be reordered by dragging and dropping a column from one place to another. Please refer to the gif below:
![grid_reorder_columns](https://user-images.githubusercontent.com/12026239/190060277-dd1a793b-826c-45b8-baea-ca4ade941321.gif)
Let me know if this is not what you requested or any problems you have with dragging columns.

**Comment by richardshiue** [comment]
Interesting, perhaps it is a platform-specific issue. On linux, I cannot get that same behavior. If I understand this correctly, we are using left mouse click and hold, right? Or should another key be pressed while dragging?

**Comment by annieappflowy** [comment]
@richardshiue , reducing the threshold makes sense. I changed this issue to reflect the needs and include it into our short-term plan.

**Comment by richardshiue** [comment]
With v0.0.5.3, the column reordering action is now immediate after clicking on the header. We're all done here.
