### ISSUE TITLE
[Bug] Can't delete card on board

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#1047]
**Describe the bug**

Impossible to delete a card on board. 

**To Reproduce**
1. Go to any board
2. Click on a card tray menu
3. Click on delete in the tray menu
4. On the pop-up click 'OK'
5. See that nothing change.

**Expected behavior**

The pop-up menu should have two buttons:
- a red one: "Delete"
- another one: "Cancel" 
- OR/AND having a `x` to close the popup.

**Screenshots**

https://user-images.githubusercontent.com/22211097/190161160-ccb53334-93e1-42d2-b5ac-4d4a9d557a46.mov

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version: 0.0.5.1.1

**Additional context**
arch: x86_64
model: MacBookPro16,1
hostName: Darwin
osRelease: Version 12.5.1 (Build 21G83)
activeCPUs: 12
memorySize: 34359738368
cpuFrequency: 2600000000
computerName: C02FT12PMD6V
kernelVersion: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64

**Comment by Razer323** [comment]
Yes i'm also having this problem 


    OS: MacOS Monterey
    Version: 0.0.5.1

Additional context
arch: x86_64
model: MacBookPro 14 inch Base

**Comment by appflowy** [comment]
fix in #1073
