### ISSUE TITLE
[Bug] Dark theme makes highlighted text unreadable.

### ISSUE THREAD

**Issue by tuqueque** [AppFlowy-IO/AppFlowy#1048]
Hello. First of all, thank you for making this incredibly promising application. I really hope this project takes off. We need a proper Notion alternative and this one seems really well done.

My problem is with the dark theme setup. When I use it, highlighted text becomes unreadable...
![2022-09-14_12-06](https://user-images.githubusercontent.com/13471025/190207484-563eafd2-482f-40bf-abd7-84d327f0989f.png)

My suggestion: make the highlighting colors "semi transparent" inside the program (like 50%). So if the user sets a green highlight, it looks like a light-green with the white background of the bright theme of the application, generating good contrast with the black text... and that same semi-transparent green, looks like dark-green with the black backdround of the dark theme, making good contrast with the white text.

Thank you in advance!

**Comment by apomalyn** [comment]
Hi! Thank you for reporting this. 
We already have an issue for this #433, I suggest you close this one and add your comment on the other issue. Thank you!
