### ISSUE TITLE
[FR] How is the communication between Flutter and Rust frontend implemented?

### ISSUE THREAD

**Issue by fzyzcjy** [AppFlowy-IO/appflowy#105]
Hi thanks for this wonderful project that replaces notion! I am very curious how the communication between Flutter and Rust frontend is implemented? I have looked at the [source code](https://github.com/AppFlowy-IO/appflowy/blob/main/frontend/rust-lib/dart-ffi/src/protobuf/proto/ffi_response.proto) and it seems that it only encodes the whole request/response into an action and a byte-array payload.

Therefore, I wonder the code can be simplified using [flutter_rust_bridge](https://github.com/fzyzcjy/flutter_rust_bridge), a high-level memory-safe binding generator for Flutter/Dart <-> Rust. With that, just simply write down a Rust function declaration, and the Dart side is automatically generated with rich type support and safety.

(Disclaimer: I wrote that lib and used it in my 200kloc project in production environment)

**Comment by annieappflowy** [comment]
I'm glad that you asked :D
We had evaluated flutter_rust_bridge when we coded up the project. Unfortunately, it doesn't satisfy our needs. We're still open to this package though. If you'd like to discuss further, you can find me on Discord. We also welcome you to join our community!

**Comment by fzyzcjy** [comment]
@annieappflowy Hi thanks for your reply and interest! Appflowy sounds quite promising and wonderful. flutter_rust_bridge has evolved and new features have been added, and corner cases have been better recently. Its architecture is also quite easy to use and modify, and I always respond quickly to PRs. I will join discord.

**Comment by annieappflowy** [comment]
> I am in Discord now (as fzyzcjy). Where should I talk?

I'm adding you

**Comment by fzyzcjy** [comment]
I see

**Comment by fzyzcjy** [comment]
👀

**Comment by fzyzcjy** [comment]
@annieappflowy How is it going

**Comment by fzyzcjy** [comment]
@annieappflowy How is it going? flutter_rust_bridge is going to be even more powerful in the future (e.g. https://github.com/fzyzcjy/flutter_rust_bridge/issues/243), thus by migrating to flutter_rust_bridge, appflowy no longer needs to spend time reinventing the wheel.

**Comment by MikeWallaceDev** [comment]
It's interesting, might be something to look at in the future.
