### ISSUE TITLE
[Bug] Can't open the app after 0.0.5.1 update on MacOS

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#1056]
**Describe the bug**

After the update, if I try to open the application I'm stuck at a screen with: 
```
FolderEditor should be initialized after user login in.
```
Written, the `create a workspace` button doesn't do anything.

**To Reproduce**
1. Update the application to 0.0.5.1
2. Create a new board page
3. Close the application
4. Restart the application
5. See the error

**Expected behavior**

The application should start and load the workspace.

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Version 0.0.5.1

**Comment by wnemay** [comment]
I did something slightly similair to what is listed above.  I updated to 0.0.5, edited a note, created a board to check out the new feature, and the next day, updated to 0.0.5.1.  Immediately saw this error.

**Comment by appflowy** [comment]
I can reproduce it by downloading v0.0.4
1. create a doc
2. delete a doc

upgrade to v 0.0.5
1. create a doc
2. delete a doc

This issue will be fixed today.

**Comment by appflowy** [comment]
fix in #1073
