### ISSUE TITLE
[FR] Import markdown files

### ISSUE THREAD

**Issue by marcleonschulz** [AppFlowy-IO/AppFlowy#1058]
You can use existent markdown files and can edit them.

**Comment by annieappflowy** [comment]
<img width="1011" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/e99b3402-9cf4-4588-9c96-a8ed52a5df31">

**Comment by vichbb** [comment]
Why is it closed? I tried it, but can't I batch import the markdown file? @annieappflowy
