### ISSUE TITLE
[FR] Support markdown to italicize text

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1059]
To italicize text, add one asterisk or underscore before and after a word or phrase. To italicize the middle of a word for emphasis, add one asterisk without spaces around the letters.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/12026239/190624628-5e94fab9-8a97-4bad-9687-5db0d66c967f.png">

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by ankur12-1610** [comment]
I would like to work on this issue!

**Comment by annieappflowy** [comment]
Thanks! Assigned to you. The mentor on this issue is @LucasXu0 . If you have any questions, please feel free to reach him out on Discord.

**Comment by JRS296** [comment]
Hey @annieappflowy, can I try working on this?

**Comment by LucasXu0** [comment]
Hi, @JRS296. Sure. We have implemented `_abc_` to _abc_, but have not implemented the `*abc*` to _abc_ yet.

**Comment by JRS296** [comment]
Cool, getting to work right away

**Comment by Xazin** [comment]
@JRS296 Hey JRS, if you need help feel free to let me know. I have this on a commit if you want some reference.

**Comment by JRS296** [comment]
@Xazin Hey there, I've located the root of the issue, and am clear on how to go about it; However I am having trouble setting up the dev environment. I've opened up an issue for the same ( Issue #2045 ). Feel free to share your thoughts on the same, would be really helpful 👍

**Comment by Xazin** [comment]
This commit (https://github.com/Xazin/appflowy-editor/commit/bef6dafbd2d9bf20745b5e0581a85efb3b049754) for the italic shortcut.

I will try during next week to see if I can replicate it on my Windows machine, currently away from home with my MacOS laptop.

Cheers

**Comment by JRS296** [comment]
Hey @Xazin , managed to fix the dev environment, it was due to the AntiVirus interfering with the build. Has this Feature request been implemented with your recent commit? If so, I'll start work on something else 👍

**Comment by Xazin** [comment]
I haven't made the PR, but I can do that later today, if you want to complete it feel free to do so.

**Comment by Xazin** [comment]
Resolved by #2115

**Comment by annieappflowy** [comment]
_ works but * doesn't work
I'm using v0.1.2

**Comment by JRS296** [comment]
I'll have a look into it 👍

**Comment by Xazin** [comment]
> _ works but * doesn't work I'm using v0.1.2

This must be due to the fact that `appflowy_editor` was removed locally from the repo, and it now uses the AppFlowy Editor dependency instead.

**Comment by annieappflowy** [comment]
* * not working
