### ISSUE TITLE
[FR] Support markdown to bold text

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1060]
To bold text, add two asterisks or underscores before and after a word or phrase. To bold the middle of a word for emphasis, add two asterisks without spaces around the letters.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/12026239/190625731-2ace9bc6-69a9-4bcc-ad51-da2a52624d84.png">

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by tekdel** [comment]
Could you assign it to me?

**Comment by annieappflowy** [comment]
Hi @tekdel , thanks for offering the help. I just assigned it to you. If you need any help, please reach out to @LucasXu0 on [Discord](https://discord.gg/9Q2xaN37tV)

**Comment by literalEval** [comment]
Is this issue fixed ? Otherwise I can work on it.

**Comment by bumie-e** [comment]
Hi, has this issue been fixed?

**Comment by annieappflowy** [comment]
This has been completed.
