### ISSUE TITLE
[FR] Support markdown to create a blockquote

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1061]
To create a blockquote, add a > in front of a paragraph.

> Dorothy followed her through many of the beautiful rooms in her castle.

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by Lakshikuga** [comment]
Hi! Would like to work on this issue.

**Comment by annieappflowy** [comment]
Hi @Lakshikuga , thanks for offering the help. I assigned the issue to you. Your mentor is @LucasXu0  for this task. If you need help from him, please reach him out on [Discord](https://discord.gg/9Q2xaN37tV).

**Comment by LucasXu0** [comment]
Hi @Lakshikuga. How's the progress of this issue? Feel free to DM me on Discord if you need any help.

**Comment by abichinger** [comment]
Hello everyone, I would like to take over this issue, if @Lakshikuga is no longer working on it.

**Comment by annieappflowy** [comment]
Assigned @abichinger 
Thanks for offering the help. Your mentor for this issue is @LucasXu0 . You can reach out him for help on Discord.
