### ISSUE TITLE
[FR] Support markdown to strikethrough text

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1062]
Surrounding text with ~~ to strikethrough the text, e.g.~~strikethrough~~

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by alemoreau** [comment]
Hi ! I would like to work on this issue.
I've created a PR https://github.com/AppFlowy-IO/AppFlowy/pull/1209 inspired by https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
Thank you !

**Comment by Lakshikuga** [comment]
Hi! would like to work on this issue!

**Comment by annieappflowy** [comment]
@alemoreau great progress! Assigned the issue to you and @LucasXu0 will review your PR. Thank you!

**Comment by annieappflowy** [comment]
> Hi! would like to work on this issue!

@Lakshikuga , assigned https://github.com/AppFlowy-IO/AppFlowy/issues/1061 to you. Enjoy and have fun :D

**Comment by DestinedCodes** [comment]
@annieappflowy I don't know if this issue has been addressed, but I am interested. if it is closed, I would like to be assigned another case.

**Comment by Xazin** [comment]
Wasn't this already supported by `doubleTildeToStrikethrough`? See https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart#LL290-L294C5 and https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/packages/appflowy_editor/lib/src/service/internal_key_event_handlers/markdown_syntax_to_styled_text.dart#LL129-L189C3

**Comment by LucasXu0** [comment]
Yes, @Xazin. I closed it.
