### ISSUE TITLE
[FR] Support markdown to create a link

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1063]
To create a link, enclose the link text in brackets (e.g., [AppFlowy]) and then follow it immediately with the URL in parentheses (e.g., (https://www.appflowy.io)).

My favorite open-source project is [AppFlowy](https://www.appflowy.io).

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by citricacid2** [comment]
can you assign this one to me?

**Comment by annieappflowy** [comment]
> can you assign this one to me?

Thanks for offering the help. Just assigned it to you :D 
Your mentor is @LucasXu0 . Please feel free to reach him out on [Discord](https://discord.gg/9Q2xaN37tV) for help.

**Comment by zoli** [comment]
I think this issue is resolved.

**Comment by annieappflowy** [comment]
I'm not able to use markdown to create a link 
MacOS v0.1.2

**Comment by alan-roe** [comment]
I seems the code that brought support for this is no longer part of the codebase, perhaps it got lost when the editor was brought into it's own repo? Should this change happen in the editor repo?

**Comment by rileyhawk1417** [comment]
@alan-roe I think it should just be moved to appflowy-editor, since most of the markdown implementations are there

**Comment by jazima** [comment]
@annieappflowy could I be assigned to this issue, I would like to give it a try
