### ISSUE TITLE
[FR] Support markdown to link an image

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1064]
Linking Images
To add a link to an image, enclose the Markdown for the image in brackets, and then add the link in parentheses.

![profile_page_appflowy_hactoberfest](https://user-images.githubusercontent.com/12026239/190627544-748d85df-87ce-40a4-b096-3b98329c416e.jpg)

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by jedau** [comment]
If this issue is still available, I would love to get a crack at it.

**Comment by annieappflowy** [comment]
@jedau , thanks for offering the help. I assigned the issue to you. Your mentor is @LucasXu0 . If you need help, please reach out to him on[ Discord](https://discord.gg/9Q2xaN37tV).

**Comment by jedau** [comment]
Hey @annieappflowy clarification regarding the requirement. Do you need the image to automatically act as a hyperlink (i.e. `[![]()]()`), or is rendering an image via the `![]()` syntax enough for this?

**Comment by annieappflowy** [comment]
@jedau did you get verification from @LucasXu0

**Comment by jedau** [comment]
@annieappflowy Not yet. Messaged him regarding a different earlier issue I encountered but I haven't heard back.

**Comment by LucasXu0** [comment]
> clarification regarding the requirement. Do you need the image to automatically act as a hyperlink (i.e. `[![]()]()`), or is rendering an image via the `![]()` syntax enough for this?

Hi, @jedau. I think it is enough to implement the latter. Converting the syntax `![]()` to the image.
