### ISSUE TITLE
[FR] Support markdown to mark as code

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1065]
To denote a word or phrase as code, enclose it in backticks (`).

eg `Hello World`

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

**Comment by MrHeer** [comment]
Hi, Can I work it?

**Comment by LucasXu0** [comment]
Sure. I assigned this issue to you.

**Comment by MrHeer** [comment]
Should I consider [escaping-backticks](https://www.markdownguide.org/basic-syntax/#escaping-backticks)?

**Comment by MrHeer** [comment]
Again, this is only the implementation of inline code, not the code block, right?

**Comment by LucasXu0** [comment]
> Should I consider [escaping-backticks](https://www.markdownguide.org/basic-syntax/#escaping-backticks)?

Good insight. Yes, it would be even better to implement the [escaping-backticks](https://www.markdownguide.org/basic-syntax/#escaping-backticks) feature, although just implementing the inline code works too. We haven't implemented the code block yet, so we have to leave it for now.
