### ISSUE TITLE
[FR] Add Latex plugin to AppFlowy Editor

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1066]
Allow users to create beautiful equations with Latex in AppFlowy Editor

Students & researchers would benefit from this plugin

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/documentation/customizing.md#customize-a-component
* https://www.markdownguide.org/basic-syntax/

**Comment by glitchpop-frenzy** [comment]
Hey Annie, this issue seems interesting. Can you assign this to me?
Do I need to define a shortcut event for each LaTeX rule?

**Comment by LucasXu0** [comment]
Hi, @glitchpop-frenzy. I recently finished a simple version of the LateX plugin. You can help to improve it if you are interested.

The LateX plugin file locates in `appflowy/frontend/app_flowy/packages/appflowy_editor/example/lib/plugin/tex_block_node_widget.dart`

**Comment by aberardinelli** [comment]
> The LateX plugin file locates in...

Which branch? I don't see it in main. I would like to look at this to see if I can help.

**Comment by LucasXu0** [comment]
Hi, @aberardinelli. The file has been moved to the plugin directory. https://github.com/AppFlowy-IO/AppFlowy/tree/main/frontend/app_flowy/packages/appflowy_editor_plugins/lib/src/math_%20equation

**Comment by annieappflowy** [comment]
Are you still working on this issue? @glitchpop-frenzy

**Comment by glitchpop-frenzy** [comment]
nope, not right now.
