### ISSUE TITLE
[FR] Enable users to insert a numbered list via the toolbar

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1069]
**1~3 main use cases of the proposed feature**
As a user, I can insert a numbered list through AppFlowy's Editor's toolbar.

(Below image shows how to use the toolbar to format as a Quote)
<img width="388" alt="image" src="https://user-images.githubusercontent.com/12026239/190637129-14c80cd0-f4d0-4abd-9a3e-5b3b379e8cf7.png">

**Comment by MrHeer** [comment]
Can I take it?

**Comment by 1AMTEDDY** [comment]
Hi @annieappflowy is this issue still avaliable?

**Comment by LucasXu0** [comment]
Hey, @1AMTEDDY. Yes. I assigned it to you.

**Comment by 1AMTEDDY** [comment]
Thank you i will take it up

**Comment by Heccubernny** [comment]
Good day @LucasXu0, is there any bug or issue that I can be assigned to? I notice some of the good first issues have been assigned to some. While some issues have been fixed but haven't been closed

**Comment by 1AMTEDDY** [comment]
I am still working on this issue @Heccubernny

**Comment by Heccubernny** [comment]
Okay @1AMTEDDY

**Comment by LucasXu0** [comment]
Hey, @Heccubernny. You can refer to https://github.com/AppFlowy-IO/AppFlowy/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
