### ISSUE TITLE
[FR] Provide AppImage build

### ISSUE THREAD

**Issue by oofdog** [AppFlowy-IO/AppFlowy#107]
**1~3 main use cases of the proposed feature**
AppImage has distinguished itself from other distribution methods (snap, flatpak and all the package managers) as being the most convenient way to distribute Linux desktop applications.

**what types of users can benefit from using your proposed feature**
It enables Linux users to have the same easy experience as Mac/Windows users.

**Additional context**
Desktop applications are increasingly using AppImage to bundle and deploy their apps to Linux as it allows them to bundle shared libraries without having to go through dependency hell.

Thank you.

**Comment by annieappflowy** [comment]
Hi oofdog,

Thanks for letting us know. We'll consider it when AF is ready for application platforms.

Annie

**Comment by rodolf0** [comment]
Just wondering if there's any recent discussion about providing an AppImage for releases. It'd be super convenient for any linux distro users

**Comment by a-wallen** [comment]
@LucasXu0 reassigning because of Q3 OKRs

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/5d8a1c3e-4df1-4b8e-9a12-8cdc10e29135

Supported!
