### ISSUE TITLE
[FR] Translate into fr-FR

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1071]
French translation

Reference:
frontend/app_flowy/packages/appflowy_editor/documentation/translation.md

**Comment by ankur12-1610** [comment]
I would like to work on this issue ;)

**Comment by Defkon1** [comment]
Sorry, I just found out this issue; I pushed the fr_FR a few minutes ago

**Comment by ankur12-1610** [comment]
Do we have any other translation that needs to be covered?

**Comment by Defkon1** [comment]
For the editor: https://github.com/AppFlowy-IO/AppFlowy/tree/22d7ade18b8844ff879f692b6037b2348aa82090/frontend/app_flowy/packages/appflowy_editor/lib/l10n

**Comment by ankur12-1610** [comment]
@Defkon1 we don't have issues for them right?
Should I create or are you going to create the issues collectively for all the remaining translations?

**Comment by Defkon1** [comment]
I don't know what is the preferred way in this repo, I am a first time contributor here...

Probably you should create a new issue
