### ISSUE TITLE
[FR] Enhance Settings

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1072]
UI enhancement

(will add more details later)

**Comment by gaganyadav80** [comment]
Hi Annie, If provided with the design I can work on this. Please assign me and share the further details.

**Comment by annieappflowy** [comment]
Hey @gaganyadav80 , so glad to hear from you. Yes, we just sourced a designer to work on this. Will share details once it's finished. Thanks for offering the help!

**Comment by akshatakulkarni25** [comment]
hey @annieappflowy , if the issue is still open can i work on it

**Comment by annieappflowy** [comment]
The design is pending. Once it's done, I will assign it to you, @akshatakulkarni25 
Thanks for offering the help!

**Comment by Uday-kiran9147** [comment]
hey @annieappflowy, if the design is Ready I can work on this issue.
