### ISSUE TITLE
[Bug] release typo

### ISSUE THREAD

**Issue by Yaminyam** [AppFlowy-IO/AppFlowy#1074]
**Describe the bug**
The bugfix title of the release should be in h2, but it is in h3.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31057849/190708384-07b8605a-5b94-416b-a446-b6afdffaf5e8.png)

**Desktop (please complete the following information):**

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by annieappflowy** [comment]
Thanks @Yaminyam , I fixed it.
