### ISSUE TITLE
Looking for experienced devs who'd like to give us feedback on our tech design article

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#109]
We're drafting a doc about AppFlowy's tech design (Part I). This article is mainly for hackers and developers who are interested in the tech design of AppFlowy. It serves as a starting point for the community to exchange ideas and grow knowledge together.  The topics it will cover:

- AppFlowy’s DDD design
- Strategies of adopting Flutter to support multiple platforms
- What roles does Rust play in the project
- A step-by-step example guiding you through the codebase

We're looking for experienced developers who would like to help us review and provide feedback before publishing it. 
Please sign up here if you're interested: https://tally.so/r/mZvQBm

**Comment by Luckey-Elijah** [comment]
I've been quietly watching this project and it's progress. Certainly interested in contributing and supporting it!

**Comment by annieappflowy** [comment]
@Luckey-Elijah thank you for the support! I'll shoot you an email once the article is ready for review.

**Comment by Poly-Pixel** [comment]
@annieappflowy I think that this issue can be closed now that the article has been published.
