### ISSUE TITLE
[Doc] Update the troubleshooting page

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1096]
Update this FAQ [page](https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/troubleshooting-when-installing-appflowy) to include frequently asked questions related to the installation / environment setup. 

Sources for Q&A:

-  [Closed issues ](https://github.com/AppFlowy-IO/AppFlowy/issues?q=is%3Aissue+is%3Aclosed)
- [Open issues tagged with documentation](https://github.com/AppFlowy-IO/AppFlowy/labels/documentation)
-  Resolved questions on [Discussions](https://github.com/AppFlowy-IO/AppFlowy/discussions)
-  [Discord channels](https://discord.gg/9Q2xaN37tV)

**Comment by VividhPandey003** [comment]
Hey @annieappflowy 👋, I am beginner to Open Source and was looking forward to contribute to this repository by resolving this issue. Could you please explain me once again, what needs to be done.

**Comment by annieappflowy** [comment]
Hi @VividhPandey003 , there were questions asked by people about setting up the environment on different systems to have AppFlowy up running on their devices. The goal here is to compile a list of FAQs and add it to the troubleshooting page. Please let me know if it's not clear or you have any questions.

**Comment by VividhPandey003** [comment]
@annieappflowy So what needs to be done is compile all the questions asked regarding setting up the enviornment along with the solution and add it to the troubleshooting page.

I'll try doing it. I suggest you to not assign it to me right now. Rather if I'm able to and if nobody is assigned till that time, I'll inform you first and then submit a PR.😊

**Comment by annieappflowy** [comment]
@VividhPandey003 all the questions with verified answers!
PR to this repo please: https://github.com/AppFlowy-IO/AppFlowy-Docs
If you have more questions, let me know!

**Comment by VividhPandey003** [comment]
@annieappflowy Should I directly refer to [Discussions](https://github.com/AppFlowy-IO/AppFlowy/discussions) for the questions and answers

**Comment by annieappflowy** [comment]
here is a list of places where you are supposed to mine FAQ:
- [Closed issues](https://github.com/AppFlowy-IO/AppFlowy/issues?q=is%3Aissue+is%3Aclosed)
- [Open issues tagged with documentation](https://github.com/AppFlowy-IO/AppFlowy/labels/documentation)
- Resolved questions on [Discussions](https://github.com/AppFlowy-IO/AppFlowy/discussions)
- [Discord channels](https://discord.gg/9Q2xaN37tV)

**Comment by kaggrwal** [comment]
@annieappflowy I have raised a PR, can you please review it and merge it ?
