### ISSUE TITLE
Thank you and suggestion to be on Telegram

### ISSUE THREAD

**Issue by wooley2** [AppFlowy-IO/AppFlowy#1106]
Hi,

For people like me who are not on Discord, would you consider a telegram channel?

Maybe you have checked it out, if not, here are some links
https://core.telegram.org/techfaq
@github_repos https://t.me/s/github_repos
https://github.com/telegramdesktop/tdesktop

Press Jun 2022
Telegram became one of the top-5 downloaded apps worldwide in 2022 and now has over 700 million monthly active users.  This growth is solely from personal recommendations – Telegram has never paid to advertise its apps.

**Comment by annieappflowy** [comment]
Hi @wooley2 , can you point me to a few great communities that are run on Telegram? I'd like to feel the vibe and evaluate Telegram as an alternative option to Discord. Thank you!

**Comment by ftp27** [comment]
I'm currently managing the [@github_repos](https://t.me/s/github_repos) channel. You have a truly impressive project here. If you're interested, I can feature it on the channel. Just send me a message with what you would like to post.

**Comment by annieappflowy** [comment]
Thank you @ftp27 
I just joined your awesome channel. Will reach out soon!
