### ISSUE TITLE
[Test]: Improve Code Coverage for infra files

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1112]
### Description

Create more tests to cover files under the "infra" folder
An example to learn how to create a test:
https://github.com/AppFlowy-IO/AppFlowy/discussions/1107

### Impact

Code Coverage metric helps in determining the performance and quality aspects of any software. 
Help us ensure AppFlowy's quality!

**Comment by DiFronzo** [comment]
Hi, @annieappflowy. I would like to work on this task. I can create test(s) for covering the file ["html-converter.dart"](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/lib/src/infra/html_converter.dart). Can you create a new issue for this spesific file and assign it to me?

**Comment by annieappflowy** [comment]
Thanks @DiFronzo ! Please create a separate issue on this topic including your work scope. I’ll then assign the issue to you. If you need quick help for this task, please reach out to @LucasXu0 on Discord.

**Comment by JRS296** [comment]
Hey there @annieappflowy, can I work on this issue?

**Comment by annieappflowy** [comment]
Since you are assigned to another issue, let's leave this for someone else.

> Hey there @annieappflowy, can I work on this issue?

**Comment by lalitkumawat1m** [comment]
hey @annieappflowy,
You are doing great work. I want to contribute to this project. Could you please assign this issue to me?
