### ISSUE TITLE
[Test]: Improve Code Coverage for operation files

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1116]
### Description

Create more tests to cover files under the "operation" folder
An example to learn how to create a test:
https://github.com/AppFlowy-IO/AppFlowy/discussions/1107

### Impact

Code Coverage metric helps in determining the performance and quality aspects of any software.
Help us ensure AppFlowy's quality!

**Comment by enzoftware** [comment]
Hi, @annieappflowy can I take this one?

**Comment by annieappflowy** [comment]
Sure @enzoftware , thanks for offering the help. Please create a separate issue for this task and include your scope in the issue.
