### ISSUE TITLE
[Test]: Improve Code Coverage for service files

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1117]
### Description

Create more tests to cover files under the "service" folder
An example to learn how to create a test:
https://github.com/AppFlowy-IO/AppFlowy/discussions/1107

### Impact

Code Coverage metric helps in determining the performance and quality aspects of any software.
Help us ensure AppFlowy's quality!

**Comment by rileyhawk1417** [comment]
Hi Annie can I try and take this issue?

**Comment by lalitkumawat1m** [comment]
hey @annieappflowy,
You are doing great work. I want to contribute to this project. Could you please assign this issue to me?

**Comment by LucasXu0** [comment]
> hey @annieappflowy, You are doing great work. I want to contribute to this project. Could you please assign this issue to me?

Hi, @lalitkumawat1m. Would you like to try another related task, such as adding integration tests?
