### ISSUE TITLE
[Test]: Improve Code Coverage for extensions files

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1118]
### Description

Create more tests to cover files under the "extensions" folder
An example to learn how to create a test:
https://github.com/AppFlowy-IO/AppFlowy/discussions/1107

### Impact

Code Coverage metric helps in determining the performance and quality aspects of any software.
Help us ensure AppFlowy's quality!

**Comment by enzoftware** [comment]
Hi @annieappflowy, can I take this one? Cheers

**Comment by annieappflowy** [comment]
@enzoftware , thanks for claiming this task. Please create a separate issue for this task. I will label your issue accordingly!

**Comment by ayushanand308** [comment]
@annieappflowy  Can you assign me this issue to complete my eligibility for github octernship program for AppFlowy?

**Comment by LucasXu0** [comment]
Hey, @ayushanand308. I assigned it to you. By the way, you can also improve the code coverage for any file not only for the extension files.
