### ISSUE TITLE
[Test]: Improve Code Coverage for render files

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1119]
### Description

Create more tests to cover files under the "render" folder
An example to learn how to create a test:
https://github.com/AppFlowy-IO/AppFlowy/discussions/1107

### Impact

Code Coverage metric helps in determining the performance and quality aspects of any software.
Help us ensure AppFlowy's quality!

**Comment by rileyhawk1417** [comment]
Hi @annieappflowy can I try and tackle this one?

**Comment by annieappflowy** [comment]
Thanks, @rileyhawk1417 . Assigned it to you

**Comment by rileyhawk1417** [comment]
Most tests were solved in this PR #1006
