### ISSUE TITLE
[Test]: Improve Code Coverage for document files

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1120]
### Description

Create more tests to cover files under the "document" folder
An example to learn how to create a test:
https://github.com/AppFlowy-IO/AppFlowy/discussions/1107

### Impact

Code Coverage metric helps in determining the performance and quality aspects of any software.
Help us ensure AppFlowy's quality!

**Comment by literalEval** [comment]
I would like to work on this issue.

**Comment by annieappflowy** [comment]
Hi @literalEval , thanks for offering the help. I assigned this issue to you.

**Comment by annieappflowy** [comment]
You mentor is @LucasXu0 . If you need help from him, please reach him out on [Discord](https://discord.gg/9Q2xaN37tV).

**Comment by annieappflowy** [comment]
Hi @literalEval , please create a separate issue for this task. I will label it accordingly. Thanks!

**Comment by literalEval** [comment]
Okay. Sure. Can you please clarify which "document files" are being talked about here ? I am a bit confused.

**Comment by rileyhawk1417** [comment]
@literalEval check the  folder under packages/appflowy_editor/src/document

**Comment by literalEval** [comment]
Okay. Sure.

**Comment by GouravShDev** [comment]
I would like to work on this if no one is working on it. 
Just wanna make sure that the document files which was mentioned are the one stored under : "frontend/appflowy_flutter/packages/appflowy_editor/lib/src/core/document"

**Comment by annieappflowy** [comment]
@GouravShDev , I assigned it to you. Your mentor is @LucasXu0 . Please reach out to him on Discord for guidance. Happy coding!
