### ISSUE TITLE
[Bug]: Help pop-up window looks weird

### ISSUE THREAD

**Issue by dadyarri** [AppFlowy-IO/AppFlowy#1126]
### Bug Description

1. In the dark mode shadow highlights the window
2. In russian locale Debug Info button can't fit in the window
3. Debug Info button have an unsupported icon
4. Version in the window doesn't match with actual version

### How to Reproduce

Open a help pop-up using button in bottom-right corner

### Expected Behavior

...

### Operating System

Arco Linux

### AppFlowy Version(s)

main branch

### Screenshots

![image](https://user-images.githubusercontent.com/51821039/191685593-a633adc6-cc08-433a-b4eb-1d27dcb7e8c3.png)

**Comment by appflowy** [comment]
@dadyarri This bug was fixed in #1155. It will be released in v0.0.5.3
