### ISSUE TITLE
[Bug]: No hard limit on maximum length of options in single/multi-select properties

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1128]
### Bug Description

Title says all. Currently, I can write an essay in the text field and set it as an option. It would be a lot better imo if there were a limit to how long the option name can be. The exact number of this limit, however, deserves more discussion.

### How to Reproduce

1. Open up a grid with a single or multi-select property.
2. Type a lot of text into the text field and press enter
3. Observe that the option is created

### Expected Behavior

The long input should not be allowed.

### Operating System

Linux

### AppFlowy Version(s)

0.0.5.2

### Screenshots

![image](https://user-images.githubusercontent.com/71320345/191734775-0716f4bd-aa6f-4df3-8541-c3f19d263411.png)

**Comment by annieappflowy** [comment]
Can this be a good issue for newcomers? @appflowy

**Comment by appflowy** [comment]
> Can this be a good issue for newcomers? @appflowy

Sure

**Comment by vortixhead** [comment]
Hi! 👋 
I would like to contribute to this one, is it available?

**Comment by annieappflowy** [comment]
@vortixhead Thanks for offering the help. I just assigned the issue to you. If you need help with this task, you can reach out to @appflowy Nathan on Discord.
