### ISSUE TITLE
[FR] Is there a Chinese community 

### ISSUE THREAD

**Issue by impactCn** [AppFlowy-IO/AppFlowy#113]
Hi community, 

I really want to use rust and flutter to help with development.

I want to ask if there is a Chinese community to assign tasks or add new features.

**Comment by annieappflowy** [comment]
Hi impactCn,

Thanks for your interest. We don't have one at this moment. Since we are a team of two, we don't have any buffer to run localized communities. You might want to try Google Translator which I think can do the magic.

Annie

**Comment by impactCn** [comment]
Or a community like slack and WeChat?

**Comment by impactCn** [comment]
> Or a community like slack and WeChat?

Of course, I can also receive tasks from issue.

**Comment by impactCn** [comment]
> Or a community like slack and WeChat?

Of course, I can also receive tasks from issue.

**Comment by annieappflowy** [comment]
> Or a community like slack and WeChat?

We have a Discord server (English) : https://discord.gg/9Q2xaN37tV
and there is a channel called #pr-wanted where we post suggested issues for newcomers :D
