### ISSUE TITLE
[FR]: Move Boards/Docs

### ISSUE THREAD

**Issue by andercard0** [AppFlowy-IO/AppFlowy#1134]
### Description

I would like to request if feasible to implement the ability to move boards/docs between the pages as shown in the video below at the moment is not possible!

![Move pages](https://user-images.githubusercontent.com/43047877/191850042-07db0e71-854a-40d6-b367-626cf3744433.gif)

### Impact

Well, not a big of deal to be honest but in the mentioned example above gif, I've created a board 'Nihongo' (Japanese) with my stuff there and below another board 'DevQuest' which is not related to the Japanese language at all 😆 so, due to this mistake of mine, a simple move board would be in handy because this way I would not have to create each of my To Dos All over again! 

In this case is kinda of simple, but imagine if i have rather a bunch of these below...

![image](https://user-images.githubusercontent.com/43047877/191850673-d9013e3f-2c36-4574-a03c-9eab66b5fa00.png)

### Additional Context

None!

**Comment by Xazin** [comment]
I'm not quite sure how to achieve this without rewriting largely how reorderable is used.

It's a bit of a complex implementation to have one Reorderable still function for two kinds of lists.

Currently, we have the "title" of a section, which is collapsible and has the action with it, this would have to be refactored such that it, and its children, would all be 1 list.

```
[
  MenuItem(label: "Nihongo", type: "header", children: [1, 2],),
  MenuItem(label: "Nihongo", type: "app", app: app),
  MenuItem(label: "DevQuest", type: "app", app: app),
  MenuItem(label: "Desenvolvimento", type: "header", children: [],),
]
```
There is a lot of work involved in enabling this basically.

I wonder if anyone else has better ideas on how to achieve this. I have not worked with Reorderable in Flutter that much before.

**Comment by zoli** [comment]
> I'm not quite sure how to achieve this without rewriting largely how reorderable is used.

Some weeks ago when I saw this issue I thought maybe instead of reorderable, this feature could get done using appflowy board. But I'm not sure (didn't get into it) how much appflowy board is customizable to use in this case.

**Comment by Xazin** [comment]
This is in the sidebar navigation, which is built using a
ReorderableListView and the children of it contains ReorderableColumn.

To achieve this you'd need to have the children be able to move outside of
the ReorderableColumn.

This could be achieved by either a custom implementation, or rewriting it
to only use one Reorderable type, and then group its children by eg. A
type. Such that you could drag both a "category" and an "app".

tor. 6. apr. 2023 20.02 skrev Mohammad Zolfaghari ***@***.***

**Comment by zoli** [comment]
I know what it its. Still the functionality of the UI part isn't similar to appflowy board? Look at each group as page and each card as file (board/document/etc). In appflowy board UI its possible to move a card between groups so if it be possible to reuse appflowy board UI component in the sidebar it could resolve the UI part of reordering pages and moving file (card) between pages (board group).

**Comment by Xazin** [comment]
> I know what it is. Still the functionality of the UI part isn't similar to appflowy board? Look at each group as page and each card as file (board/document/etc). In appflowy board UI its possible to move a card between groups so if it be possible to reuse appflowy board UI component in the sidebar it could resolve the UI part of reordering pages and moving file (card) between pages (board group).

The Sidebar is written in Dart, while the board if I'm not mistaken, is a React Component, using the `Draggable` from the `react-beautiful-dnd` package. 

I mean, it's not that it can't be done, but I'm not sure if it's a good idea to change the sidebar to a react component.

I guess the decision would ultimately be on the team.

**Comment by Xazin** [comment]
Actually, I was looking at the Reorderable package we use, when I have some more time I will look at it, but it seems it should be possible without too much refactoring.

**Comment by annieappflowy** [comment]
Hi @andercard0 , we have supported your requests:
1. Add subpages and easily nest / un-nest by drag and drop
2. Move board cards from one stack to another by drag and drop
Please give it a try with the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases) and let us know your feedback.

**Comment by andercard0** [comment]
> Hi @andercard0 , we have supported your requests:
> 1. Add subpages and easily nest / un-nest by drag and drop
> 2. Move board cards from one stack to another by drag and drop
> Please give it a try with the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases) and let us know your feedback.

Hi. 

Thank you for all of you guys! 

Will use for sure intensively this feature and if anything go wrong I will let you know.

**Comment by zoli** [comment]
I thought this issue was about moving pages between two different sections. The descriptions doesn't say that but the preview is an attempt to move a page from one section to another.
