### ISSUE TITLE
[Bug]: Some issues/bugs

### ISSUE THREAD

**Issue by andercard0** [AppFlowy-IO/AppFlowy#1135]
### Bug Description

Hi, Not sure if this was already reported (and yes I've tried to look into it before raise this) but I could not find similar issue here. 

I'll list all of my issues until now and make a quick video to illustrate them better.

1 Duplicate Board isn't being duplicated;

2 Program keeps enforcing me to use in my native language even if I choose English for example after restart it;

3 Board created only duplicates correctly if, there is nothing selected, how do I select that (check the video) I do not know 🤣 the itens in the header of the boards has gone, I can't see if, they're "To Do" "Doing" "Done" etc.

4 After select anything my notes got erased, believe me I had a bunch of it more than showned in the video srsly : ( 

5 Font-size not being scaled/unscaled while in trash(page)

### How to Reproduce

1. Create a board > fill it with ToDos, Doing etc.. then try to duplicate, if, they are checked (and I really don't know how I did it)it will be duplicated but with blank content as show in the video below

![Duplicate issue](https://user-images.githubusercontent.com/43047877/191875184-46d9d352-0667-4a55-aeba-b35705828d41.gif)

2. Chosse any other language rather yours (native) then close the app and open again, it will return to the latter one. i guess AppFlowy is checking for the OS configure language and enforcing it instead of let us choose any other and keep it as we want instead.

Here, it is in English but app keept Brazilian Portuguese as choose language
![image](https://user-images.githubusercontent.com/43047877/191876900-f12961b0-7778-402b-9a00-afa74fdd1c64.png)

3. and 4. they are kinda linked I guess take a look in the video below, soon as I hit: Properties > Description > Text (it got checked forever) erasing my other/old notes... I mean, my older notes reapeared but the check item won't let me see the header anymore so, I've lost all my notes. If there was a way to export the DB notes that would be great deal too. 

![Can't uncheck all my other notes are gone](https://user-images.githubusercontent.com/43047877/191876165-36f12a00-04f1-41b2-be19-db9a885cef32.gif)

5. at the right side (apagar tudo) "delete all" is squished, haven't tested in other languages though.
![image](https://user-images.githubusercontent.com/43047877/192035817-761f5be0-7c45-4b96-b4fa-fb86e672cb4c.png)

### Expected Behavior

I don't know.. not sure if I'm doing something wrong here sorry... if I'm please let me know.

Hope you guys can fix those issues soon! The application idea is fantastic.

### Operating System

Windows 10 - 21h2

### AppFlowy Version(s)

latest 1.0.0.

### Screenshots

Video above

### Additional Context

No need.

**Comment by annieappflowy** [comment]
@andercard0 huge thanks!
I'll start handling the issues listed here over this weekend. Will follow up soon

**Comment by appflowy** [comment]
2 and 5 were already fixed in main branch. Will release in version 0.0.5.3

**Comment by appflowy** [comment]
@andercard0 I tried to reproduce the 3,4 issue, but I can reproduce how to lost the data.

**Comment by andercard0** [comment]
> @andercard0 I tried to reproduce the 3,4 issue, but I can reproduce how to lost the data.

🤔 hm well. the moment I seen my other notes were gone was when that ✔️ appears.

This one is too tricky to reproduce indeed 😆 

![image](https://user-images.githubusercontent.com/43047877/192102177-57f75b02-c9ee-4706-a1aa-b95e23e175e5.png)

**Comment by andercard0** [comment]
> 2 and 5 were already fixed in main branch. Will release in version 0.0.5.3

woah, already ? 
you're fast 👍🏽 Thank you so much all of you guys!!

**Comment by appflowy** [comment]
> 

No problem. I am still working on other issues.
I will let you know if we publish a new release version. Probably next week.
