### ISSUE TITLE
[FR]: Rename/add columns into a board

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#1145]
### Description

As a user, I would like to control the name and number of columns I have on a board so I'm able to use it for everything I want (e.g. kanban: To Do, In progress, Blocked, Review, Done)

### Impact

All of the users.

**Comment by annieappflowy** [comment]
Hi @apomalyn , can you elaborate on how you want to control the name and number of columns? Thanks!

**Comment by annieappflowy** [comment]
1. Enable users to directly rename a stack by clicking on the stack name and editing the name
2. Enable users to hide/unhide a stack

**Comment by annieappflowy** [comment]
<img width="654" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/87aa3190-712e-4a33-9a97-f2e578768198">
