### ISSUE TITLE
[Bug]: Deseriaze delta error!

### ISSUE THREAD

**Issue by qqke** [AppFlowy-IO/AppFlowy#1148]
### Bug Description

<img width="422" alt="image" src="https://user-images.githubusercontent.com/23273672/192083607-750189e1-fc59-49ac-be10-f7ceac36404b.png">

### How to Reproduce

Saved japanese characters  ,cannot open again! 

### Expected Behavior

How to find the original data

### Operating System

windows 11

### AppFlowy Version(s)

0.5.2 beta

**Comment by appflowy** [comment]
Hi, @qqke please try the latest release version. You could DM me if the problem still exists.
