### ISSUE TITLE
Support AppFlowy Editor on the Web platform

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1149]

**Comment by jaydeepmehta15** [comment]
Is it complete ?

**Comment by 304442** [comment]
?

**Comment by LucasXu0** [comment]
@jaydeepmehta15 @304442 Yes. The appflowy_editor supports the web platform. FYI, we only verify the editor's behavior that builds with `canvaskit`, but not with `HTML`.

**ScreenShot**
<img width="1624" alt="Screenshot 2022-12-08 at 09 46 42" src="https://user-images.githubusercontent.com/11863087/206336484-76aa39e3-a486-473c-b6a1-01a7a08827b4.png">

**Comment by 304442** [comment]
So I can run appflowy web app using docker-compose for the frontend?

**Comment by LucasXu0** [comment]
@304442 What we are talking about is not the same thing. AppFlowy does not support the web platform yet, and [appflowy_editor](https://pub.dev/packages/appflowy_editor) is the built-in editor component we are using in AppFlowy, which supports the web platform.

**Comment by arsen-z** [comment]
@LucasXu0 Are there any plans for web platform support for AppFlowy?

**Comment by annieappflowy** [comment]
Yes, @arsen-z , we're working on the web app
