### ISSUE TITLE
[Bug]: Few pixels near the edge of grid cells behave abnormally

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1151]
### Bug Description

With the exception of Text, Number and URL properties, clicking on the few pixels just near the edges of the cells doesn't trigger the popover that will be used to edit the cell.

Additionally, the I-beam cursor effect only appears for Text and Number properties when hovering over the inner rectangle within the cell.

### How to Reproduce

1. Click near the edges of a grid cell that should hold a date
2. Observe that nothing happens

1. Hover over a Text field
2. Move the cursor towards the edges and observe that the I-beam disappears

### Expected Behavior

The clicks/hover events should be propagated as long as the cursor is within the cells.

### Operating System

Linux

### AppFlowy Version(s)

v0.0.5.2

**Comment by ChiragKr04** [comment]
Can reproduce on `Windows 11` too. I'll work on this.
