### ISSUE TITLE
[FR]: Create more Rust starter issues for AppFlowy's contributors

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1164]
### Description

We'd like to offer real-world practices to AppFlowy's contributors who are interested in learning Rust and developing relevant skills. At the moment, most of our open issues for newcomers are Flutter issues. Please create more Rust starter issues.

### Impact

Contributors who are learning Rust or want to build up their development skills through real world opportunities.

**Comment by TieWay59** [comment]
Is there already a doc or blog post related to the rust back-end? I think it would be nice if we newcomers can read it before asking too much. 

(sorry if you have already posted it somewhere else.)
