### ISSUE TITLE
[Test]: Unit tests that cover other Enum NumberFormat

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1171]
Cover other enum types in NumberFormat. For the moment, only `Number`, `USD`, `Yen`, `Yuan`, and `EUR` get covered.
```rust
  for format in NumberFormat::iter() {
    type_option.format = format;
    match format {
        NumberFormat::Num => {
            assert_number(&type_option, "18443", "18443", &field_type, &field_rev);
        }
        NumberFormat::USD => {
            assert_number(&type_option, "18443", "$18,443", &field_type, &field_rev);
        }
        NumberFormat::Yen => {
            assert_number(&type_option, "18443", "¥18,443", &field_type, &field_rev);
        }
        NumberFormat::Yuan => {
            assert_number(&type_option, "18443", "CN¥18,443", &field_type, &field_rev);
        }
        NumberFormat::EUR => {
            assert_number(&type_option, "18443", "€18.443", &field_type, &field_rev);
        }
        _ => {}
    }
}
```

Check out the [number_type_option_format_number_test](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/number_type_option/number_tests.rs) and 
[number_type_option_format_str_test](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/number_type_option/number_tests.rs) function for more information.

**Comment by ZZITE** [comment]
I see there is another issue #1170 that looks the same, Is there any difference?

I’m interested in this project and I'm just starting to learn rust, can i work it?

**Comment by appflowy** [comment]
> I see there is another issue #1170 that looks the same, Is there any difference?
> 
> I’m interested in this project and I'm just starting to learn rust, can i work it?

#1170 is duplicated. 

Sure, I assign it to you.
