### ISSUE TITLE
[FR]: Integrate thiserror and anyhow

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1172]
AppFlowy uses custom defined error type that will be eventually converted to `FlowyError`. Try to Integrate [thiserror](https://docs.rs/thiserror/latest/thiserror/) and [anyhow](https://docs.rs/anyhow/latest/anyhow/) into one of the crates located in [rust-lib](https://github.com/AppFlowy-IO/AppFlowy/tree/main/frontend/rust-lib) to make it easier to handle errors.

 `FlowyError` is annotated with `ProtoBuf` macro, which means it can be deserialized/serialized via protobuf. For the moment,  `FlowyError` is propagated to the Dart side.

**Comment by VoidCupboard** [comment]
I would like to work on this issue 😄

**Comment by annieappflowy** [comment]
Hi @VoidCupboard , thanks for offering the help. Your mentor is @appflowy . If you need help, you can contact him on [Discord](https://discord.gg/9Q2xaN37tV).

**Comment by inigoiparragirre** [comment]
Hi, I would like to know if this issue is ongoing. I can take a look. Thank you @annieappflowy

**Comment by annieappflowy** [comment]
Hi @VoidCupboard , how's the progress on this issue? 
If you are no longer working on it, we can let @inigoiparragirre take a look.
