### ISSUE TITLE
[FR]: Support Group by Date in Kanban Board

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1174]
Support Group by Date in Kanban Board. 

Currently, AppFowy doesn't support grouping by the Date property, as shown below. 
![Image](https://user-images.githubusercontent.com/86001920/192415152-94d79e21-add8-40a4-a1be-3d6dff8e12ba.gif)

An example (see below) the dates are grouped by Month. Implement support grouping the records in Kanban board by the date property.

![Image](https://user-images.githubusercontent.com/86001920/192416901-d274205f-7214-426e-b319-7f093de188b5.png)

**Comment by AmoleR** [comment]
I'd love to help with this. This would just be making a new controller for date (and changing the grayed-out version of Date to a selectable version). Am I missing anything?

**Comment by itsparser** [comment]
@AmoleR  are you working on this, i will like to help on this

**Comment by annieappflowy** [comment]
Sorry for missing your question @AmoleR . 
This is not a straightforward task to be honest. Since it's been months, maybe we can let @itsparser give it a try!
Let me know if there is anything else that interests you: https://github.com/orgs/AppFlowy-IO/projects/5/views/4
We'll assign you a mentor this time in case you need quick help!

**Comment by annieappflowy** [comment]
Assigned it to @itsparser. Your mentor is @appflowy  for this task. You can DM him on Discord for help.
You also have a friend who's working on a similar task at the moment: https://github.com/AppFlowy-IO/AppFlowy/issues/1175#issuecomment-1369366348

**Comment by itsparser** [comment]
thanks for the Connection, will go through the code and will update back

**Comment by annieappflowy** [comment]
Hello @itsparser , are you still working on this issue? Do you need help?

**Comment by zoli** [comment]
I would like to take on this if @itsparser is no longer interested.

**Comment by annieappflowy** [comment]
Assigned. Thanks @zoli for offering the help!

**Comment by zoli** [comment]
About this, I would like to suggest having multiple group options:
- By Day
- By Month
- By Week Number

**Comment by zoli** [comment]
> About this, I would like to suggest having multiple group options:

After reading `DateGroupConfigurationRevision` I see that you already had this in mind. But I don't get `DateCondition::Relative` meaning. What's that supposed to mean, grouping date by what?

**Comment by zoli** [comment]
> > About this, I would like to suggest having multiple group options:
> 
> After reading `DateGroupConfigurationRevision` I see that you already had this in mind. But I don't get `DateCondition::Relative` meaning. What's that supposed to mean, grouping date by what?

From what I found `Relative` means "Tomorrow", "Next 7 days", "Next 30 days" and other next months.
