### ISSUE TITLE
[FR]: Support Group by the URL property in Kanban Board

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1175]

**Comment by appflowy** [comment]
Support group by URL in Kanban board.

Currently, AppFowy didn't support grouping by URL property, as shown below.

![group_by_url](https://user-images.githubusercontent.com/86001920/192419291-1b950daa-ee88-4799-bbe9-a1786fa1a2ff.gif)

**Comment by zoli** [comment]
Hi,
I would like to take on this.

**Comment by annieappflowy** [comment]
Thanks for claiming the issue @zoli 
Assigned it to you. Your mentor is @appflowy  for this task. You can DM him on Discord for help.
