### ISSUE TITLE
[Test] Implement unit test in Rust when switching from other property types to Text property type.

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1177]
Implement the unit test when switching to Text property from other property types but still need to display the cell content.

**Comment by ENsu** [comment]
@annieappflowy Can I tackle this one?

**Comment by ENsu** [comment]
Can I take this one?

**Comment by annieappflowy** [comment]
@ENsu , I assigned it to you. Happy coding!

**Comment by 0xkelvin** [comment]
hello @ENsu 
i also working on this, so maybe we can pair together

cc @annieappflowy @appflowy

**Comment by annieappflowy** [comment]
Oh sorry, I didn't know that @0xkelvin was working on it. 
Yes, collaboration sounds fun! 
@ENsu would it be ok to partner with @0xkelvin to finish this task?

**Comment by 0xkelvin** [comment]
hello @ENsu 
please connect over Discord, my id : 0xqwert#2911

**Comment by 0xkelvin** [comment]
hello @ENsu how is it going, do you need any help from me
