### ISSUE TITLE
[FR] Support switching from Single-select property type to Multi-select property type and vice versa

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1178]
Display the option after switching from a single select property type to a multi-select property type and vice versa

For the moment, the cell is blank after switching from single select to multi-select

![Image](https://user-images.githubusercontent.com/86001920/192450171-fe40395d-516f-4f1d-88fa-a9a2154cef00.gif)

**Comment by arshidhaar** [comment]
Hi

**Comment by aminmarashi** [comment]
I'm working on this one...

**Comment by annieappflowy** [comment]
Thanks! Assigned it to you. Your mentor is @appflowy . If you have any questions, please feel free to reach out to Nathan on [Discord](https://discord.gg/9Q2xaN37tV).

**Comment by aminmarashi** [comment]
I think it's a good time for me to give up on this issue. I couldn't find the time to work on it and the source-code is too alien for me to make it a simple change. So please consider this issue unassigned again.

**Comment by ENsu** [comment]
@annieappflowy Can you assign this task to me? I have discussed with @appflowy.
I think I can finish the whole feature first (this task), then finish the [one](https://github.com/AppFlowy-IO/AppFlowy/issues/1181) that runs the unit test.

**Comment by annieappflowy** [comment]
Awesome! Just assigned it to you. Have fun learning Rust :D

**Comment by ENsu** [comment]
@appflowy Could you please check to see if this work has been completed as a result of this merge?
https://github.com/AppFlowy-IO/AppFlowy/pull/1493

**Comment by appflowy** [comment]
> 

#1493 handles the single-select to multi-select. You could create a new PR that supports multi-select to single-select.

**Comment by ENsu** [comment]
Hi @appflowy I believe it already works in both directions. Could you please double-check this one?

**Comment by appflowy** [comment]
> Hi @appflowy I believe it already works in both directions. Could you please double-check this one?

Sorry, I forgot to tell you I already tested it. 
Yep, it works.
