### ISSUE TITLE
[FR] Support switching from Checkbox property type to Single/Multi-select property type

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1179]
Create a new tag named `Yes` if the checkbox is in check status when switching from checkbox property type to single/multi-select.
Need to know Flutter and Rust

![Image](https://user-images.githubusercontent.com/86001920/192449266-5c576a4c-6c11-4a67-be4c-fa44f3c56a74.gif)

**Comment by MrHeer** [comment]
I very much hope that I can come to challenge this task.

**Comment by annieappflowy** [comment]
Let me know when you are ready to start working on this. I'll then assign this issue to you @MrHeer

**Comment by MrHeer** [comment]
Yes, I'm ready!

**Comment by annieappflowy** [comment]
Awesome @MrHeer , if you need help or have questions, please ask @appflowy on Discord. Have fun and enjoy!
