### ISSUE TITLE
[Bug] GitHub misspelled

### ISSUE THREAD

**Issue by factotvm** [AppFlowy-IO/appflowy#118]
**Describe the bug**

On the ApPFlOwY web site, you do not spell GitHub correctly. They have a capital "G" and a capital "H" and while we can argue about whether that makes sense or not, it's their name and they're very consistent about spelling it the way they'd like it to be written.

**To Reproduce**
1. Visit https://www.appflowy.io/
2. Search using your browser's mechanism for "git"
3. Notice all instances are spelled "Github" (consistent, at least)

**Expected behavior**
Spell the name of the service you're using correctly

**Screenshots**

<img width="342" alt="image" src="https://user-images.githubusercontent.com/38792/144694758-818fbdc8-659f-42f9-9c7f-0612384d2e3c.png">

<img width="128" alt="image" src="https://user-images.githubusercontent.com/38792/144694763-8be3319f-6991-4c58-8615-9a5a0bb7a0da.png">

<img width="195" alt="image" src="https://user-images.githubusercontent.com/38792/144694775-736c6231-b351-477c-82de-50751ff07cb5.png">

**Additional context**

This is a bit tongue-in-cheek, but I do believe attention to detail is important and I hope you feel the same.

**Comment by annieappflowy** [comment]
Hi factotvm,

Thank you for your feedback. I see your point, and I will update the UX text on the website.

Annie

**Comment by annieappflowy** [comment]
Updated it. Closing this issue. Thanks
