### ISSUE TITLE
[Test] Implement unit test in rust when switching from a Single-select to a Multi-select property type

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1181]

**Comment by TomerPacific** [comment]
Hi @appflowy , I'd like to help out. Seeing as this will be my first contribution here, anything I should know in advance (apart from the contributing file)?

**Comment by appflowy** [comment]
Hi, @TomerPacific. There are resources you can take a look

* [Commit message guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/code-submission-guidelines)
* [Some concepts about the grid](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/architecture/frontend/grid) 

I am writing new documentation about Type switching. I will let you know after I finish it.

**Comment by TomerPacific** [comment]
@appflowy  - Thanks. I'll check those out and post back here if I have any more questions/clarifications.

**Comment by appflowy** [comment]
@TomerPacific I added some documentation. Check out the transform method of the  [TypeOptionBuilder](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_option_builder.rs) trait. You can handle the logic during the `transform` when switching from/to a different type.

Both MultiSelectTypeOptionBuilder and  SingleSelectTypeOptionBuilder implement the  `TypeOptionBuidler` trait. FYI, there are some unit tests written in [multi_select_type_option.rs](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/multi_select_type_option.rs) and [single_select_type_option.rs](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/single_select_type_option.rs)

1. [MultiSelectTypeOptionBuilder](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/multi_select_type_option.rs)
2. [SingleSelectTypeOptionBuilder](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/selection_type_option/single_select_type_option.rs)

**Comment by TomerPacific** [comment]
@appflowy  - Currently stuck with a local development issue (discussed at the discord channel). Might be worthwhile to assign this to someone else.
I'll update if I can overcome this issue.

**Comment by annieappflowy** [comment]
@TomerPacific 
reposting here in case other Windows devs can help:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/12026239/196380816-9843d78e-9582-47ae-889f-3b5afe177358.png">

**Comment by ENsu** [comment]
@annieappflowy @appflowy If this is acceptable, I would like to try this one.

**Comment by annieappflowy** [comment]
Yes! I think this is a good place to start practicing Rust. I've assigned the issue to you. If you need help, please don't hesitate to reach out on Discord.

**Comment by ENsu** [comment]
Hello, @appflowy . I tried the `main` branch version.

Currently, switching from SingleSelectType to MultiSelectType (or vice versa) removes the data from the frontend.

Is this something I should be concerned about, or is it a separate issue? (I am happy to deal with it; I just want to be certain.)

**Comment by ENsu** [comment]
@appflowy Could you please check to see if this work has been completed as a result of this merge? I've added the relative features as well as the unit test.
https://github.com/AppFlowy-IO/AppFlowy/pull/1493

**Comment by appflowy** [comment]
> @appflowy Could you please check to see if this work has been completed as a result of this merge? I've added the relative features as well as the unit test. #1493

Yes, it is.
