### ISSUE TITLE
[Test] Implement unit test in rust when switching from a Multi-select property type to a Text property type

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1183]

**Comment by 0xkelvin** [comment]
hello can i take this @annieappflowy @appflowy

**Comment by annieappflowy** [comment]
Thanks @0xkelvin for taking this issue. Just assigned it to you.
In case you need help, please reach out @appflowy on Discord

**Comment by 0xkelvin** [comment]
it done and merged #1585
