### ISSUE TITLE
[Bug]: Extra spacing in multiselect cell

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1186]
### Bug Description

When I select 2 or more options in a multi-select grid cell, the cell wraps to a second line even though there is more than enough to fit everything in the first row.

### How to Reproduce

1. Go to a grid with a multi-select property
2. Select 2 options when that should fit in the first row
3. Observe that there is extra spacing

### Expected Behavior

The tags should fit on the same row

### Operating System

Linux

### AppFlowy Version(s)

v0.0.5.2

### Screenshots

https://user-images.githubusercontent.com/71320345/192566299-f9b28dfb-3db1-4d80-b88b-1e58c974a637.mp4

**Comment by annieappflowy** [comment]
Is it an easy fix? Can this be an newcomer friendly issue? @appflowy

**Comment by sahej-dev** [comment]
I would like to be assigned this issue, if no else has started working on this. I am newcomer.

**Comment by codezuma** [comment]
@sahej-dev  are you still working on this issue.

**Comment by sahej-dev** [comment]
@codezuma Yes I am.
