### ISSUE TITLE
[China.] If I can, I'd like to translate the Chinese version

### ISSUE THREAD

**Issue by ghost** [AppFlowy-IO/AppFlowy#119]
很喜欢这个项目，我希望有中文版本，我不懂英文，但是我可以用翻译软件来协助翻译；目前这个项目还是刚开发，从开始就出现多语言版本，后面开发会更加全面和省心省心！

**Comment by annieappflowy** [comment]
Thanks for the kind words. Sure. Please follow https://github.com/AppFlowy-IO/appflowy/issues/117 
Once we have i18n set up, I'll post you on the progress. 

Annie

**Comment by fhmohen** [comment]
Because many excellent markdown note taking projects have no Chinese version, many compatriots have given up. I hope such an excellent project can be known and accepted by more Chinese people.

**Comment by annieappflowy** [comment]
Understood. Thanks for your inputs!

**Comment by C1oud555** [comment]
Chinese user too. It will be much easier to recommend this excellent project to my friends if Chinese is supported

**Comment by annieappflowy** [comment]
We support simplified and traditional Chinese
