### ISSUE TITLE
[FR]: Auto-detect link in AppFlowy Editor

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1190]
### Description

Paste a link starting with https or www into AppFlowy Editor. Then it's auto-formatted as URL and clickable
<img width="716" alt="image" src="https://user-images.githubusercontent.com/12026239/192686005-c5022fa1-267d-46f0-aaac-ed5b4db86d66.png">

### Impact

Users who write links in pages

**Comment by MrHeer** [comment]
Can we fetch the URL, and parse the `title` from the HTML?

**Comment by MrHeer** [comment]
Can I take it?

**Comment by Rocketchat23** [comment]
No you can't

**Comment by annieappflowy** [comment]
Hi @MrHeer , thanks for offering the help! I assigned it to you. This one is not an easy fix to be honest, but great practice for sure. If you have any questions, please feel free to reach out to @LucasXu0

**Comment by MrHeer** [comment]
@annieappflowy Hi, This feature seems to be completed by #851

**Comment by annieappflowy** [comment]
Thanks @MrHeer , great work :D
