### ISSUE TITLE
[Bug]: New note/tag bug

### ISSUE THREAD

**Issue by andercard0** [AppFlowy-IO/AppFlowy#1193]
### Bug Description

Hi all, here I go again reporting a new bug hope you don't mind :) 

Some things are better explained in videos rather with texts, so take a look

![Deleted](https://user-images.githubusercontent.com/43047877/192893364-6831392e-d30d-495e-a315-559ece4cd39e.gif)

2. can't select the text it moves the entire tag.

![selection](https://user-images.githubusercontent.com/43047877/193024901-f8307799-ca70-4ba1-9e39-a518f98f3c0d.gif)

### How to Reproduce

Steps to reproduce it (issue 1)

- Create a new label/tag (never know how name this) sorry...
- Name it as normal;
- Move it into NoStatus page;
- Delete it > it will not delete aparently.

Steps to reproduce (issue 2)
- click in the pencil to edit the tag
- try to select text

Text is only selecteable if use a shortcut **Ctrl + a** instead

Even if you check the trash there will nothing in there but if you do close the application and reopen again the deleted item is now gone.

### Expected Behavior

When I decide to delete, show me that I deleted it! : ) 

### Operating System

Windows 10 - 21h2

### AppFlowy Version(s)

v0.0.5.3

### Screenshots

Gif attached above

### Additional Context

No needed.

Thanks!

**Comment by annieappflowy** [comment]
@andercard0 , thanks! We don't mind at all getting bug reports. Please share them when you find any!

**Comment by appflowy** [comment]
@andercard0 Thank you for reporting this issue. It had been fixed in PR #1241.
