### ISSUE TITLE
[Bug]: Padding Issue on ActionItems

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1206]
### Bug Description

This seems to be a regression from 0.0.5.3. Some ActionItems are no longer sized correctly. The one case that works as intended (from my observations at least) is the bottom-right info button with the question mark.

### How to Reproduce

1. Click on the share button in a doc page, or
2. Open the context menu on an app in the sidebar, or
3. Open the context menu on a page in the sidebar,
4. Observe that the padding is off when hovering over it

### Expected Behavior

The hover effect should stretch to the right edge.

### Operating System

Linux

### AppFlowy Version(s)

v0.0.5.3

### Screenshots

![Screenshot_20221002_200126](https://user-images.githubusercontent.com/71320345/193452909-238c0ab2-96cc-47d9-ac39-4ce1a445de39.png)

![Screenshot_20221002_195817](https://user-images.githubusercontent.com/71320345/193452893-31e56671-e490-4907-b40c-0362a1d09706.png)

![Screenshot_20221002_200359](https://user-images.githubusercontent.com/71320345/193453035-4f1dbc6b-c49f-419e-be47-a18fcc058c24.png)

**Comment by annieappflowy** [comment]
could be bugs introduced by the overlay package
@appflowy , please check

**Comment by appflowy** [comment]
Hi, @richardshiue this issue was fixed in #1250.
