### ISSUE TITLE
[Test]: Improve Code Coverage for extensions files

### ISSUE THREAD

**Issue by enzoftware** [AppFlowy-IO/AppFlowy#1221]
### Description

- Improve code coverage
- Improve codebase

### Impact

Improve confidence while doing changes on the `extensions` package

### Additional Context

Coming from #1118 

_No response_

**Comment by enzoftware** [comment]
@annieappflowy here is the new issue

**Comment by annieappflowy** [comment]
@enzoftware , thanks! Assigned to you

**Comment by enzoftware** [comment]
Hi @annieappflowy, can I reach out to someone to ask some questions about the scope of the PR. Or just drop them here?

**Comment by annieappflowy** [comment]
You can either drop your questions here or ask @LucasXu0 on [Discord](https://discord.gg/9Q2xaN37tV). He will be your mentor on this task. Thanks!
