### ISSUE TITLE
[Bug]: Scrolling in multi-select edit text fields

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1223]
### Bug Description

The selected tags show up at the start of the search field as shown below. However, the only way to scroll through them is by using the touchpad horizontal scroll (no mouse scrolling and horizontal mouse scroll is very rare, and vertical scroll for touchpad doesn't work either). We can also explore adding mouse drag to scroll through the selected tags.

I am also of the view that there are too many ways of conveying the selected options (the cell itself, the search field and the list view). While I think that on mobile the cell would probably not be visible when editing the cell, on desktop 3 is too many imo.

### How to Reproduce

1. Open a grid cell with multi-select property
2. Select multiple tags or a few tags with long option names
3. Observe that the only way to scroll through the tags is via a horizontal mouse swipe

### Expected Behavior

The tags should be easily scrollable

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

v0.0.5.3

### Screenshots

![image](https://user-images.githubusercontent.com/71320345/193819901-f1286be0-b2a9-456b-8f5a-a5bc4b504190.png)

**Comment by ChiragKr04** [comment]
I'm able to produce this on `Windows 11`. I'll work on this.
