### ISSUE TITLE
[Test]: Improve Code Coverage for infra/html-converter

### ISSUE THREAD

**Issue by DiFronzo** [AppFlowy-IO/AppFlowy#1227]
Create tests for covering the code found in the file [html-converter.dart](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/lib/src/infra/html_converter.dart). Connected to issue #1112.

**Comment by annieappflowy** [comment]
@DiFronzo , have you checked out this example on how to add tests? https://github.com/AppFlowy-IO/AppFlowy/discussions/1107
Let us know if you need more hints to complete this task.
