### ISSUE TITLE
[Bug]: Scrollbar Design

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1230]
### Bug Description

Scrollbars in some appflowy pages could use some improvement:
- Kanban doesn't have one at all (the only way is through horizontal touchpad scroll) #1027
- The one in grid looks okay, but there is some mis-alignment (bottom right corner) and I think the scroll bar should protrude above the header row?
- The one in the trash page is a bit thinner than the one in grid

### How to Reproduce

1. Go to a grid
2. add some rows and columns
3. scroll and observer results

1. Go to a kanban board with more groupings than can be fitted on the page
2. scroll horizontally and see that there is no scrollbar

### Expected Behavior

Scrollbars looking snazzy

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

v0.0.5.3

### Screenshots

![image](https://user-images.githubusercontent.com/71320345/194101118-331ce18b-2ba4-4c6f-982e-e3c2c8952017.png)

**Comment by SmartAree** [comment]
Can I work on this?

**Comment by annieappflowy** [comment]
Sure. Thanks for offering the help! Just assigned the issue to you

**Comment by SmartAree** [comment]
Thanks and pleasure!

**Comment by appflowy** [comment]
Hi @SmartAree, you can DM me on Discord if you have any questions.

**Comment by SmartAree** [comment]
Yeah sure
