### ISSUE TITLE
[FR] Allow to indent checklist items

### ISSUE THREAD

**Issue by gianpaj** [AppFlowy-IO/AppFlowy#124]
**1~3 main use cases of the proposed feature**
As a user, I want to have multiple checkbox items indented:
eg.
```
- user
  - name
  - email
```

![image](https://user-images.githubusercontent.com/899175/144843017-b6e511fa-48ba-4c48-91d4-b7949fc6999f.png)

Also:
- use `Tab` key to quickly indent
- `shift`+`Tab` to un-indent

**Comment by annieappflowy** [comment]
Thank you @gianpaj for proposing the feature.
This is a known enhancement but has not been prioritized. Also, it depends on https://github.com/AppFlowy-IO/appflowy/projects/2#card-74049343
