### ISSUE TITLE
Automatically publish the AppFlowy app to Flathub in the release job.

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1247]
Original PR:

https://github.com/AppFlowy-IO/AppFlowy/pull/208

**Comment by Ayush1325** [comment]
I think it is important first to clarify what integrating flatpak into AppFlowy build process means. Most applications in flathub (Eg: [zola](https://github.com/flathub/org.getzola.zola)) do not do any building in the base repository.

**Comment by LucasXu0** [comment]
Hi, @Ayush1325. Actually, we want to integrate the action of publishing the AppFlowy app to Flathub in the release job.
