### ISSUE TITLE
[FR] Support windows platform in ci.yaml

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1248]
### Description

Currently `ci.yaml` is not supported for the Windows platform, while `release.yml` is supported for all desktop platforms.

### Impact

Avoid unintended errors on windows.

### Additional Context

 Theoretically, we only need to migrate the logic of `release.yaml`

**Comment by LucasXu0** [comment]
**ci.yaml**
<img width="561" alt="ci.yaml" src="https://user-images.githubusercontent.com/11863087/194684426-8f09825a-ed87-40fa-bcd9-362e49e95d5b.png">

**release.yml**
<img width="843" alt="release.yml" src="https://user-images.githubusercontent.com/11863087/194684449-c36816fd-ac33-4c1d-8027-bdb58c681bc9.png">

**Comment by Ishanned** [comment]
@LucasXu0 do we need to include `windows-latest` in the os list of ci.yaml?

**Comment by Ishanned** [comment]
I would like to work on this issue. Can you assign this to me?
