### ISSUE TITLE
[FR] Prevent keeping the previous style when formatting text through markdown syntax.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1249]
### Description

Prevent keeping the previous style when formatting text through markdown syntax.

For example : 
1. input `**ABC**`
2. `**ABC**` will become **ABC**
3. input some text, like `EFG`, after **ABC** and the new inputting text should not be bold
4. **ABC**EFG

### Impact

This will enhance the user experience for Markdown users.

**Comment by codezuma** [comment]
@LucasXu0  are you working on this issue.

**Comment by LucasXu0** [comment]
No. Do you want to give it a try?

**Comment by codezuma** [comment]
Thinking of that. But i dont have any experience in flutter

**Comment by codezuma** [comment]
Can you help me with it? Looks like you have been contributing for a while in this now

**Comment by LucasXu0** [comment]
It's a bit difficult for a without flutter experience developer. Maybe you can try the other issues tagged with a `good first issue for devs` label. 😊

**Comment by codezuma** [comment]
Yeah sure
