### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [AppFlowy-IO/appflowy#125]
Hello!

I manage awesome flutter list on github and would like to invite you to add AppFlowy.

https://github.com/Solido/awesome-flutter

Thank you for this excellent tool.

Cheers,
Robert

**Comment by annieappflowy** [comment]
Hi Robert,

Thank you so much for inviting us. The list you created can be of great help for Flutter learners.

I just flicked through the list, and I think we can add AppFlowy to "Flutter Apps"? Please let  me know which location it's the most appropriate.
![image](https://user-images.githubusercontent.com/12026239/144846268-5a9504a5-bad3-4693-affb-9bbbad2a751f.png)

**Comment by Solido** [comment]
Premium is what define AppFlowy, please add it there ;)

**Comment by annieappflowy** [comment]
Cool! Thanks for promoting us ;)

**Comment by annieappflowy** [comment]
@Solido  https://github.com/Solido/awesome-flutter/pull/880

**Comment by Solido** [comment]
Welcome aboard!

Have you heard about Synology Nas company? 
They produce a range of products for individuals as well as enterprise on advanced hardware.
I already manage all my services like that.
Looks like perfect fit for AppFlowy!
They also have a package manager for full installation and update.
Maybe you can consider it as an eventual opportunity.

Cheers!
Robert
