### ISSUE TITLE
[Test]: Improve Code Coverage for operation files 

### ISSUE THREAD

**Issue by enzoftware** [AppFlowy-IO/AppFlowy#1254]
### Description

Create more tests to cover files under the "operation" folder

### Impact

Increase code coverage for the editor package

### Additional Context

Related to #1116

**Comment by enzoftware** [comment]
Hi, I was working on this one and then updated my branch with the latest and realized that the `operation` folder was removed on this [PR ](https://github.com/AppFlowy-IO/AppFlowy/pull/1259). @LucasXu0 is this folder moved to another location? How can I move forward on this one?

**Comment by LucasXu0** [comment]
> Hi, I was working on this one and then updated my branch with the latest and realized that the `operation` folder was removed on this [PR ](https://github.com/AppFlowy-IO/AppFlowy/pull/1259). @LucasXu0 is this folder moved to another location? How can I move forward on this one?

Hi. I moved the operation file to the new directory. `lib/src/core/transform`
