### ISSUE TITLE
[Bug]: Better color selection for new options in single/multi-select properties

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1255]
### Bug Description

Currently, the color for new tags can often overlap, especially after a previous option is deleted.

### How to Reproduce

1. Go to a multi-select property
2. Create 3 option and remember the colors for each 
3. Delete the second option
4. Create a new option
5. Observe that the new option's color overlaps

### Expected Behavior

The new option's color isn't the same as an existing option's

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

v0.0.5.3

### Screenshots

https://user-images.githubusercontent.com/71320345/194760832-899c854b-8c04-4d94-b90f-ce36e9f563c5.mp4

**Comment by annieappflowy** [comment]
Can this be a good issue for contributors? @appflowy
