### ISSUE TITLE
[Bug] Linux binary: Exec format error

### ISSUE THREAD

**Issue by starsareintherose** [AppFlowy-IO/appflowy#126]
**Describe the bug**
I install binary and lib and data into the dest dir and exec the binary. All the files are from https://github.com/AppFlowy-IO/appflowy/releases/download/0.0.2/AppFlowy-Linux-arm64.zip

**To Reproduce**
```
bash: /usr/bin/appflowy: cannot execute binary file: Exec format error
```

**Expected behavior**
can run

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser Chromium
 - Version 96.0.4664.45

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by glitsj16** [comment]
The Linux release you used explicitly refers to `arm64`. Your OS is most likely using a different architecture (like `x86_64`), which would explain the error message. Run `uname -m` to check this.

On a side-note, the same goes for the [AUR package](https://aur.archlinux.org/packages/appflowy-bin/). The PKGBUILD refers to the `x86_64` [arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=appflowy-bin#n9) yet tries to use a `arm64` [source](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=appflowy-bin#n14) file. That will never work.

**Comment by Gausoft** [comment]
So how to solve this issue?

**Comment by annieappflowy** [comment]
> So how to solve this issue?

Hi Gausoft,

You would have to clone the source and build it on your machine.

Annie

**Comment by starsareintherose** [comment]
Sorry, I condisering it as amd

**Comment by starsareintherose** [comment]
But actually, it is not possible to compile under ArchLinux, the packages used does not exit.

**Comment by Gausoft** [comment]
> > So how to solve this issue?
> 
> Hi Gausoft,
> 
> You would have to clone the source and build it on your machine.
> 
> Annie

Sorry I'am unable to build it on my linux os

**Comment by annieappflowy** [comment]
> > > So how to solve this issue?
> > 
> > 
> > Hi Gausoft,
> > You would have to clone the source and build it on your machine.
> > Annie
> 
> Sorry I'am unable to build it on my linux os

What error did you get? Would you mind sharing it?

**Comment by irfanbacker** [comment]
> But actually, it is not possible to compile under ArchLinux, the packages used does not exit.

Have you tried following the [linux build instructions](https://github.com/AppFlowy-IO/appflowy/blob/main/doc/BUILD_ON_LINUX.md)? Other users were able to compile on ArchLinux.

**Comment by starsareintherose** [comment]
```
#Maintainer Guoyi Zhang <GuoyiZhang at malacology dot net>

pkgname=appflowy
_pkg=AppFlowy
pkgver=2021.12.8
pkgrel=1
pkgdesc="an open-source alternative to Notion"
arch=('x86_64')
url="https://www.appflowy.io/"
license=('AGPL')
depends=('curl' 'sqlite3' 'openssl' 'clang' 'cmake' 'ninja' 'flutter' 'gtk3' 'rustup')
provides=('appflowy')
conflicts=('appflowy-bin' 'appflowy-git')
source=("git+https://github.com/AppFlowy-IO/appflowy.git")
sha256sums=('SKIP')
prepare(){
	cd $srcdir/$pkgname
#cp backend/configuration/base.example.yaml backend/configuration/base.yaml
#	cp backend/configuration/.env.example backend/configuration/.env
}
build(){
#	source $HOME/.cargo/env
	sudo rustup toolchain install nightly
	sudo rustup default nightly
	
	echo "export PATH=\$PATH:"`pwd`"/bin" >> ~/.profile
	export PATH="$PATH:`pwd`/bin"
	flutter channel dev
	flutter config --enable-linux-desktop

	cd appflowy/frontend
	cargo install --force cargo-make
	cargo install --force duckscript_cli

	cargo make -p production-linux-x86 appflowy-linux
}
package(){
 install	
}
```
The instructions are not so wise to explain.

**Comment by MikeWallaceDev** [comment]
@starsareintherose @Gausoft Please look at the newest version of [The Linux build instructions](https://github.com/AppFlowy-IO/appflowy/blob/main/doc/BUILD_ON_LINUX.md). These instructions have been tested on Ubuntu and Manjaro(Arch). I built AppFlowy on Arch myself, so I garantee that it works :)

@annieappflowy Can you please close this issue?
