### ISSUE TITLE
[FR / Bug] Markdown, Reciprocal Link, and Cell Merge

### ISSUE THREAD

**Issue by Angel0726** [AppFlowy-IO/AppFlowy#127]
**1~3 main use cases of the proposed feature**
Ex: 
1. export markdown&html。i want to use appflowy for blog
2. reciprocal link
3. merge table cell

**what types of users can benefit from using your proposed feature**
i want ro use it as hexo editor. what'more 
I want the same experience as notion

**Additional context**

**Comment by annieappflowy** [comment]
@Angel0726 have you tried our simple markdown export? Just click "Share" -> "Markdown" -> (Ctrl + V) onto your blog page?
<img width="223" alt="Screen Shot 2021-12-08 at 2 24 50 PM" src="https://user-images.githubusercontent.com/12026239/145159185-53ae86e5-3f71-4fe0-83d4-9473265b1279.png">

**Comment by Angel0726** [comment]
thank you。i have more question, will appflowy develop into notion? use database, build blogs?

**Comment by Angel0726** [comment]
> @Angel0726 have you tried our simple markdown export? Just click "Share" -> "Markdown" -> (Ctrl + V) onto your blog page? <img alt="Screen Shot 2021-12-08 at 2 24 50 PM" width="223" src="https://user-images.githubusercontent.com/12026239/145159185-53ae86e5-3f71-4fe0-83d4-9473265b1279.png">

Share" -> "Markdown"-> (Ctrl + V) onto your blog page? it does not work

**Comment by SekiBetu** [comment]
> > @Angel0726 have you tried our simple markdown export? Just click "Share" -> "Markdown" -> (Ctrl + V) onto your blog page? <img alt="Screen Shot 2021-12-08 at 2 24 50 PM" width="223" src="https://user-images.githubusercontent.com/12026239/145159185-53ae86e5-3f71-4fe0-83d4-9473265b1279.png">
> 
> Share" -> "Markdown"-> (Ctrl + V) onto your blog page? it does not work

+1  not working on windows 11

**Comment by MikeWallaceDev** [comment]
@annieappflowy I can look into why the export button is not working.

**Comment by annieappflowy** [comment]
> @annieappflowy I can look into why the export button is not working.

Sure. That would be awesome. Thank you!

**Comment by annieappflowy** [comment]
@MikeWallaceDev hey Mike, any update on this?

**Comment by sunny7dusk** [comment]
I've just tried testing for this bug. The feature is working as intended. After clicking on Share -> Markdown, I can just CTRL+V at any text editor for the markdown code.

**Comment by MikeWallaceDev** [comment]
Yeah, I fix this a while back. But I think there was a duplicate issue that I closed.
