### ISSUE TITLE
[FR]: editor shortcuts like ctrl+backspace, home, end, etc

### ISSUE THREAD

**Issue by FarisHijazi** [AppFlowy-IO/AppFlowy#1270]
### Description

many editor shortcuts are missing, basic ones that you'd expect to find even in notepad.

The behavior I'm looking for is very standard, you can try it in any textbox in any browser or text editor

- home, end should navigate to the beginning and end of the line
- ctrl+home, ctrl+end should navigate to the very top of the page and very bottom of the page
- ctrl+backspace, ctrl+delete should delete the next/prev word
- shift+down, shift+up should highlight the line bellow/above respectively, currently you have to press it twice then it would highlight the entire block, not what we're expecting

### Impact

more intuitive and better editing experience

I only used appflowy for a few seconds and I encountered this issue of not having these hotkeys, please add them, many power users will be expecting them

**Comment by LucasXu0** [comment]
Hi, @FarisHijazi. Thanks for your suggestion. Actually, we are developing a new editor that supports customizing shortcuts. 

We have implemented the following shortcuts.
* Home
* End
* Shift + Arrow keys + (Control / Command)

About the shortcuts, like Control/Command + Home/End or Backspace/Delete, we will implement them soon.

**Comment by annieappflowy** [comment]
Can the remaining shortcuts be good Hacktoberfest issues? @LucasXu0

**Comment by annieappflowy** [comment]
Hi @MayurSMahajan , please verify if all the shortcuts suggested by @FarisHijazi have been supports.

**Comment by MayurSMahajan** [comment]
The following shortcuts mentioned by @FarisHijazi are implemented:

- [x] `Home` and `End` keys to navigate to the start and end of a line.
- [x] `Ctrl+Home` and `Ctrl+End` navigate to the very top of the page and very bottom of the page.
- [x] `ctrl+backspace` deletes the previous word.
- [x] `shift+down`, `shift+up` should highlight the line below/above respectively

The following shortcut is not implemented yet:

- [ ] `ctrl+delete` to delete the next word.

**Comment by MayurSMahajan** [comment]
> The following shortcuts mentioned by @FarisHijazi are implemented:
> 
>     * [x]  `Home` and `End` keys to navigate to the start and end of a line.
> 
>     * [x]  `Ctrl+Home` and `Ctrl+End` navigate to the very top of the page and very bottom of the page.
> 
>     * [x]  `ctrl+backspace` deletes the previous word.
> 
>     * [x]  `shift+down`, `shift+up` should highlight the line below/above respectively
> 
> 
> The following shortcut is not implemented yet:
> 
>     * [ ]  `ctrl+delete` to delete the next word.

With `ctrl+delete` completed, we now support all the shortcuts specified in this issue.
