### ISSUE TITLE
[Bug]: App keeps corrupting documents

### ISSUE THREAD

**Issue by VincentKnightTesting** [AppFlowy-IO/AppFlowy#1276]
### Bug Description

Whenever I close the app and reopen it, it shoves my changes at the bottom which messes with previous inserted styling.
Example: I have:
I: United States

1. bluh bluh bluh loreum ipsum
2. balh bluh
3. foobar

after reopening it will be
I:

1. 
2. 
3. 
United Statesbluh bluh bluh loreum ipsum
balh bluh
foobar

### How to Reproduce

Write text with empty number lists and quotes, close app, and then add text in empty slots and then restart app.

### Expected Behavior

I expect the text to be left how I left it

### Operating System

Mac Montary 12.5.1

### AppFlowy Version(s)

0.0.5.3

### Additional Context

I can provide logs if needed

**Comment by annieappflowy** [comment]
Is this resolved at v0.0.6?

**Comment by VincentKnightTesting** [comment]
omg best way to hear about an update, I'll try it out

**Comment by VincentKnightTesting** [comment]
from what I can see, so far it's good!

**Comment by annieappflowy** [comment]
Thanks @VincentKnightTesting for confirming. I'm closing this issue. You can reopen it if you can reproduce. Looking forward to getting more feedback from you.
