### ISSUE TITLE
[FR] Zoom level settings

### ISSUE THREAD

**Issue by TieWay59** [AppFlowy-IO/AppFlowy#128]
**1~3 main use cases of the proposed feature**
Just as in windows browsers, people press `ctrl +` and `ctrl -` to adjust the scale of the whole layout of the view. 
Many text editors have this feature, such as vs code.

**what types of users can benefit from using your proposed feature**
This can help when working on a different kind of screen device.
It's like a piece of `a11y` thing. Personally, I prefer everything a bit larger than current defaults.

**Additional context**
Looking forward to a stronger list of shortcut keys.

**Comment by annieappflowy** [comment]
If we offer you a few font size choices, would that meet your needs?

**Comment by TieWay59** [comment]
@annieappflowy sure, more choices will help a lot !

**Comment by v3ss0n** [comment]
Unable to use on 4k and high DPI , cannot even zoom.

**Comment by zoli** [comment]
How is this different from #1638?

**Comment by annieappflowy** [comment]
@zoli , #1638 is a duplicate of this issue.

**Comment by Twilightssuperb** [comment]
How about to increasing the priority of this issue?
