### ISSUE TITLE
[Bug] 300ms delay on buttons in titlebar

### ISSUE THREAD

**Issue by cbenhagen** [AppFlowy-IO/AppFlowy#1290]
### Bug Description

When clicking on the "close side bar" or "Share" button in the title bar there is a 300ms delay before the button reacts. This feels as if the app is very slow.

This is due to the underlying the `onDoubleTap` handler of the `GestureDetector` in `MoveWindowDetector` waiting for a potential second tap before defering the tap handling to its child. 

### How to Reproduce

Click on a button in the titlebar.

### Expected Behavior

The button should react immediately.

### Operating System

macOS

### AppFlowy Version(s)

main branch on commit cbd84dfaa

**Comment by ChiragKr04** [comment]
It might look slow. But it is a part of appflowy UX. Making it react instantly will make it snappy with no animation. I might be wrong but @annieappflowy can suggest.

**Comment by cbenhagen** [comment]
Maybe I should have been clearer. I didn't mean to ommit the animation. This issue is about not having a 300ms delay before the animation starts.

The `GestureDetector` responsible for this 300ms delay is only used under macOS so it seems pretty clear that the delay is is not intentional:
https://github.com/AppFlowy-IO/AppFlowy/blob/7b53b2c523e43aeaedfa71956e69ee377213b88b/frontend/app_flowy/lib/core/frameless_window.dart#L43-L51

**Comment by annieappflowy** [comment]
@cbenhagen @ChiragKr04  thanks. I can reproduce on macOS. I agree that it reacts slower than it should be.

**Comment by annieappflowy** [comment]
@LucasXu0 , can you evaluate if this is a good issue for Hacktoberfest?

**Comment by LucasXu0** [comment]
OK. The main reason for this issue is that the two gestures are in conflict. I think using `Listener` instead of `GestureDetector` is a way to fix this issue. Maybe there is a better way, but I don't find yet.

**Comment by LucasXu0** [comment]
<img width="728" alt="" src="https://user-images.githubusercontent.com/11863087/196095443-f68a5e18-a165-422c-b94b-873c35b3be10.png">

**Comment by LucasXu0** [comment]
```
class RoundedTextButton extends StatelessWidget {
  // ...
  @override
  Widget build(BuildContext context) {
    // ...
        child: SizedBox.expand(
          child: Listener(
            onPointerDown: (event) => onPressed?.call(),
            onPointerSignal: (event) {
              // do nothing, just to prevent to call the parent's actions
            },
            child: Center(
              child: Text(
                title ?? '',
                style: TextStyle(color: textColor, fontSize: fontSize),
              ),
            ),
          ),
          // TextButton(
          //   onPressed: onPressed,
          //   child: Text(
          //     title ?? '',
          //     style: TextStyle(color: textColor, fontSize: fontSize),
          //   ),
          // ),
   // ...
  }
}
```

**Comment by AdiAr11** [comment]
Hi, I've successfully built the app for mac. @LucasXu0 could you please guide me a little? Is the issue because of GestureDetector in frameless_window.dart which you shared?

**Comment by AdiAr11** [comment]
> class RoundedTextButton extends StatelessWidget {
>   // ...
>   @override
>   Widget build(BuildContext context) {
>     // ...
>         child: SizedBox.expand(
>           child: Listener(
>             onPointerDown: (event) => onPressed?.call(),
>             onPointerSignal: (event) {
>               // do nothing, just to prevent to call the parent's actions
>             },
>             child: Center(
>               child: Text(
>                 title ?? '',
>                 style: TextStyle(color: textColor, fontSize: fontSize),
>               ),
>             ),
>           ),
>           // TextButton(
>           //   onPressed: onPressed,
>           //   child: Text(
>           //     title ?? '',
>           //     style: TextStyle(color: textColor, fontSize: fontSize),
>           //   ),
>           // ),
>    // ...
>   }
> }

What should I look for in this file?

**Comment by LucasXu0** [comment]
Hi, @AdiAr11. The file locates in `frontend/app_flowy/packages/flowy_infra_ui/lib/widget/rounded_button.dart`. The share button has to delay its response because of the `GestureDetector` in `frameless_window.dart`.

**Comment by AdiAr11** [comment]
Oh, Okay. I'll try to fix this. Thank you!

**Comment by cbenhagen** [comment]
You might also want to wrap your `Listener` in `GestureDetector` with an empty `onDoubleTap` handler so that double clicking your new button will not maximize the window.

**Comment by AdiAr11** [comment]
@cbenhagen Sure, thank you!

**Comment by annieappflowy** [comment]
@AdiAr11 , any progress update on this issue? Let us know if you need help. Thanks!

**Comment by AdiAr11** [comment]
@annieappflowy sorry, im out of town. I'll be back in 2 days. 
I had some doubts though, I'll ask them when i get back.

**Comment by annieappflowy** [comment]
Any update / progress on this issue? @AdiAr11

**Comment by AdiAr11** [comment]
Yes, sorry for late reply. I tried the above approach and it was still the same. I researched and I saw that there is a delay because of a potential second tap.

**Comment by annieappflowy** [comment]
Thanks for the update.
@LucasXu0 can provide you with more guidance.
