### ISSUE TITLE
[Bug] Disable unexpected logs to the console in the release mode.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1292]
### Bug Description

I found some logs are outputted to the console when I used AppFlowy installed by flatpak.

### How to Reproduce

* install the AppFlowy through flatpak or run the app in the terminal directly.

### Expected Behavior

Only useful information should be printed out to the console.

### Operating System

Ubuntu 22.04

### AppFlowy Version(s)

0.0.5.3

### Screenshots

<img width="609" alt="" src="https://user-images.githubusercontent.com/11863087/196078540-9222d7c8-891e-484b-9f69-6a863dad8124.png">

**Comment by appflowy** [comment]
Fixed
