### ISSUE TITLE
[Bug] Grid: Incomplete display of the property names

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1296]
### Bug Description

<img width="548" alt="" src="https://user-images.githubusercontent.com/11863087/196113010-2e00dd47-7bea-42f2-97e4-3cfc4ba7ff05.png">

As the screenshot shows, only the `Name` is displayed on the field but I have typed `Name ABCDEFG`

### How to Reproduce

typing long text in the grid property field.

### Expected Behavior

It will be better to show `Name ABCDE...` than `Name` only.

### Operating System

Ubuntu 22.04

### AppFlowy Version(s)

0.0.5.3

**Comment by alemoreau** [comment]
Hi @LucasXu0 !
Can I work on this ?

**Comment by LucasXu0** [comment]
Hi, @alemoreau. Sure, I assigned it to you.
