### ISSUE TITLE
[Bug] Can't open the inline link in the Grid on Ubuntu

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1297]
### Bug Description

![image](https://user-images.githubusercontent.com/11863087/196115141-4e2780d2-56df-454b-887d-12deb1dae415.png)

There is no effect when double-clicking the link.

### How to Reproduce

* Change the filed type to Link
* Enter the link
* Double-click it

### Expected Behavior

Open the link successfully

### Operating System

Ubuntu 22.04

### AppFlowy Version(s)

0.0.5.3

**Comment by LucasXu0** [comment]
Hi, @Chirag8023. The code locates in `frontend/app_flowy/lib/plugins/grid/presentation/widgets/cell/url_cell/url_cell.dart`.

![image](https://user-images.githubusercontent.com/11863087/196850791-697f9fe0-a85c-44ed-943d-31cf36d0ccde.png)

By the way, I can only reproduce it on 0.0.5.3 but not in the `main` branch.

**Comment by Chirag8023** [comment]
I thought this is an easy one but this issue is harder than I thought !
Can you help me on what changes to make?

**Comment by annieappflowy** [comment]
Any update on this issue? @LucasXu0
