### ISSUE TITLE
[Bug] Grid: Incomplete placeholder for the Name field.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1298]
### Bug Description

<img width="907" alt="" src="https://user-images.githubusercontent.com/11863087/196116179-b560bc2c-34a6-4d6f-a8cd-4221ae6b2ddd.png">

### How to Reproduce

* Create a grid
* Select a field under the name property
* Click the `Open as a page` button

### Expected Behavior

The placeholder shows completely.

### Operating System

macOS 12.6

### AppFlowy Version(s)

0.0.5.3

**Comment by ChiragKr04** [comment]
I can reproduce it on `Windows 11`. I'll work on this.

**Comment by LucasXu0** [comment]
Sure! I assigned it to you.
