### ISSUE TITLE
[Bug] Board: the text on the card is not displayed completely

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1299]
### Bug Description

 [Screencast from 17-10-22 14:41:00.webm](https://user-images.githubusercontent.com/11863087/196118118-72d5052a-50ed-4f9f-9fad-24fa5b592ace.webm)

Only the `card 2` text has been displayed after I typed the `card 2\ncard 5`.

### How to Reproduce

* Create a board
* Select a card 
* Input something and tap the Enter key

### Expected Behavior

All text will be displayed on the card.

### Operating System

Ubuntu 22.04

### AppFlowy Version(s)

0.0.5.3

**Comment by agent515** [comment]
I would like to give this a go. Is the issue present only on Ubuntu or all the platforms?

**Comment by LucasXu0** [comment]
Hi, @agent515. I only reproduced this issue on Ubuntu. It works fine on macOS.

**Comment by agent515** [comment]
Hi, @LucasXu0 . I'm unassigning myself from this issue because I'm not able to take enough time out to work on the issue. Sorry about that. 🙏 

My best wishes for the project.

**Comment by not-shoyo** [comment]
Hi @LucasXu0 , I tried to recreate the bug you mentioned, however it doesn't look like its an issue anymore. Could you please update the video you provided for the bug if it still persists? The text explanation is a little tough to follow.

**Comment by LucasXu0** [comment]
Hey, @not-shoyo @glunkad. This issue has been fixed. Let me close it.
