### ISSUE TITLE
[Question] Any plans for a Docker image?

### ISSUE THREAD

**Issue by sfkpmr** [AppFlowy-IO/appflowy#13]
I see .dockerignore, but no Dockerfile. Would love to see one!

**Comment by stemount** [comment]
@sfkpmr what do you propose the use of Docker for? (building? hosting flutter as a pwa or something - not a flutter expert)

**Comment by nicolasdanelon** [comment]
@sfkpmr maybe I don't want to install Rust on my machine, maybe I just want to download the docker images and run the app on my local environment without installing any dependency... 
also docker containers can be used to deploy the app faster on tons of boxes.
if some developer is using M1 and doesn't have a dependency or is just running Linux docker will have all dependencies already built in, configured and ready to run.
Docker is a must

**Comment by appflowy** [comment]
@sfkpmr  The docker file is used to deploy the AppFlowy backend on the local host.

**Comment by franciscoafonsoo** [comment]
Would you guys be open to a Pull Request for a docker-compose and some Dockerfiles ? 

I was thinking that it would help local development in the wild to have a docker-compose that launches the db, the backend and the frontend (never dockerized a flutter app but should be possible).

**Comment by PabloCastellano** [comment]
Yes, please! The Rust+Flutter stack isn't that common nowadays and having to spend more than 1 hour (my case so far) for installing all the Rust and Flutter dependencies, plus compiling... is discouraging, unless you have been waiting for a Notion open source clone for years!

With Docker it would be super easy and fast to just fetch AppFlowy and run it

**Comment by iamaravindim** [comment]
Please DO create the Docker Image we are interested in hosting in on our servers.

**Comment by huangxinping** [comment]
Please DO create the Docker Image we are also VERY interested.

It has taken more than 3 hours to install all dependencies so far without success.

**Comment by annieappflowy** [comment]
> Would you guys be open to a Pull Request for a docker-compose and some Dockerfiles ?
> 
> I was thinking that it would help local development in the wild to have a docker-compose that launches the db, the backend and the frontend (never dockerized a flutter app but should be possible).
> 
> Edit: i'm checking the database scripts. The idea would be to simplify this logic so that random developers can launch the project in a very simple and straight forward way

We're definitely open to PRs. To understand this better, do you want a docker backend or both the backend and the frontend?

**Comment by annieappflowy** [comment]
> Yes, please! The Rust+Flutter stack isn't that common nowadays and having to spend more than 1 hour (my case so far) for installing all the Rust and Flutter dependencies, plus compiling... is discouraging, unless you have been waiting for a Notion open source clone for years!
> 
> With Docker it would be super easy and fast to just fetch AppFlowy and run it

Love how you put this all together - I can feel your pain now :(
Let's just keep discussing this topic in this thread until we land on a nice solution :D

**Comment by sfkpmr** [comment]
@annieappflowy An image for both would be awesome!

**Comment by annieappflowy** [comment]
> Please DO create the Docker Image we are also VERY interested.
> 
> It has taken more than 3 hours to install all dependencies so far without success.

Please join our Discord channel, and I believe some pro hackers can help you out there

**Comment by appflowy** [comment]
@franciscoafonsoo  It seems possible to docker the flutter desktop application.
https://hub.docker.com/r/openpriv/flutter-desktop

I use docker to host the AppFlowy backend on my laptop to develop the AppFlowy backend server. But did set up the Dockerfile.

**Comment by appflowy** [comment]
Guys, PRs for this are welcomed :D

**Comment by akimolll** [comment]
Yes, docker is very needed to run it

**Comment by franciscoafonsoo** [comment]
> @franciscoafonsoo It seems possible to docker the flutter desktop application. https://hub.docker.com/r/openpriv/flutter-desktop
> 
> I use docker to host the backend on my laptop to develop the frontend, but I didn't set up the Dockerfile.

I will then join discord and discuss some things !

**Comment by franciscoafonsoo** [comment]
So i will start with something very simple:

- docker-compose definition for the backend and the database. something like this

```yaml
version: "3.8"

services:
  backend:
    image: appflowy-backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 8080:8080

  database:
    image: postgres:14.1-bullseye
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: flowy
      DB_PORT: 5433

    ports:
      - 5433:5433
```

I am reading the db scripts to understand what needs to be done. But should look something like that. After having that done, it's a matter of exploring flutter docker and connecting it.

**Comment by esturniolo** [comment]
+1 for this

**Comment by appflowy** [comment]
@franciscoafonsoo  Wow, it seems ok to me. Have you tried it?

* The existing Dockerfile does not work anymore.

**Comment by Hawkinzzz** [comment]
another +1 for this!! a docker container would make it that much easier to set up and run on any server

**Comment by adamzhoul** [comment]
+1 

little idea,  let's volume data to the local.
so we can easily back up.
or, users can volume path to apple iCloud path, so data can sync between the company and home easily.

**Comment by pramadito** [comment]
+1 

i would love to develop full stack with docker

**Comment by juangburgos** [comment]
+1

**Comment by Poly-Pixel** [comment]
+1
Is there a PR in progress for this?

**Comment by tborychowski** [comment]
There's a whole community of [/r/selfhosted](https://www.reddit.com/r/selfhosted/) who would love to take this for a spin! :-D

**Comment by Hawkinzzz** [comment]
Yeah we would be keen to do a video on this if we could get a working docker container running on the unraid platform (we can add the template on your behalf if needed) - https://youtube.com/c/IBRACORP

**Comment by felipefideli** [comment]
+1

**Comment by armin771** [comment]
> Yeah we would be keen to do a video on this if we could get a working docker container running on the unraid platform (we can add the template on your behalf if needed) - https://youtube.com/c/IBRACORP

That would be fantastic. Would love to get it running on my end under unraid.

**Comment by 0xN0x** [comment]
+1

**Comment by lirc572** [comment]
I think it would be more useful to be able to also run the flutter desktop app itself in a docker container during development and display the GUI on the host machine, because it will allow us to use flutter's hot reload for development.

[This link](http://wiki.ros.org/docker/Tutorials/GUI) is a good reference on how to run GUI apps in a container. Not sure if it will be easy to apply it to the flutter desktop toolchain though.

A web (PWA) version would of course be much easier to run/develop with docker.

**Comment by appflowy** [comment]
The backend docker image is ready. Run 
`make docker_image`

![image](https://user-images.githubusercontent.com/86001920/144740064-ff2c4539-a139-4bf6-afe6-4c65c6bc6f33.png)

![image](https://user-images.githubusercontent.com/86001920/144740228-95f5e90c-996f-44cb-b4c6-d1c9f63151d7.png)


I couldn't find the method to run the GUI desktop application build with flutter in Docker. I'm working on the frontend part that enables communication with the backend. Let me know if I'm on the right track to meet your needs.

**Comment by irfanbacker** [comment]
> I couldn't find the method to run the GUI desktop application build with flutter in Docker, but I'll keep trying. I'm working on the frontend part that enables communication with the backend. Let me know if I'm on the right track to meet your needs.

I don't think there is a straightforward way to do it. Users might have to do some external setup to get GUI applications working on docker. Besides, i don't think there is a usecase here. Users could easily use the release zips to run the frontend. If its for easier building, maybe a docker image with mounted folder could be used and the build could be output in the folder.

**Comment by antoineozenne** [comment]
I think a docker-compose to launch all the stack (back, front, db) would be great to promote the application. Today, I wanted to test the application on Ubuntu, but there is no "one-command test". In addition, Rust and Flutter are still fairly new, and not everyone is perfectly comfortable with these technologies. While a docker-compose...

**Comment by MikeWallaceDev** [comment]
This thread needs a conclusion. There seems to be bits and pieces, but no clear outcome. Can someone write up a blogpost/wiki that explains what our docker containers can do, how to install them, and how to use them? If a PR is needed, let's get that done too. Then we can close this issue.

Who would like to take the lead on this?

@nicolasdanelon @appflowy @franciscoafonsoo @annieappflowy @adamzhoul @lirc572 @antoineozenne

**Comment by armin771** [comment]
Would it be possible to make the Docker available on DockerHub? Then it would be easy to set up AppFlowy on Unraid.

**Comment by MikeWallaceDev** [comment]
Hello,
A Docker file was created and documented by @rushic24, thanks!

You can find install information [here](https://github.com/AppFlowy-IO/appflowy/wiki/Installing-with-Docker).

**Comment by JoyceBabu** [comment]
> Hello, A Docker file was created and documented by @rushic24, thanks!
> 
> You can find install information [here](https://github.com/AppFlowy-IO/appflowy/wiki/Installing-with-Docker).

The wiki link is redirecting to the GitHub project home page. Is this no longer supported?
