### ISSUE TITLE
[FR] Right button mouse support

### ISSUE THREAD

**Issue by Miradin** [AppFlowy-IO/AppFlowy#1300]
### Description

On right mouse button click show standard menu with options:
* copy
* paste
* delete

Maybe, additionally:
* clear formatting
* all capital
* all lowercase

### Impact

At this moment, there are no actions on right button click and standard behavior is expected.

### Additional Context

Please, add Editor tag.

**Comment by LucasXu0** [comment]
Hi, @Miradin. Thanks for your suggestions. I implemented a simple context menu, like this

<img width="790" alt="" src="https://user-images.githubusercontent.com/11863087/196368979-297f607f-82fe-48f6-8fa2-65d2a9a90c5c.png">

Does this meet your needs?

**Comment by Miradin** [comment]
Hello Lukas, that looks good! Thank you.
Have you thought about extended functionality? Maybe, not now, but in some future releases?

**Comment by LucasXu0** [comment]
Yup. We will implement the additional functionality.
