### ISSUE TITLE
[Bug] Could not drag the board on Ubuntu

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1301]
### Bug Description

It's no effect when dragging the board card on Ubuntu

### How to Reproduce

* Create a board
* Drag the card

### Expected Behavior

The board card can be dragged normally

### Operating System

Ubuntu 22.04

### AppFlowy Version(s)

0.0.5.3

**Comment by polypixeldev** [comment]
I am trying to drag the cards on the board and I do not see any issues. I am on the latest main branch (5a30f46b85f5bf0cb2ae508f97b223a1e401ec80) and Ubuntu 22.04.

**Comment by annieappflowy** [comment]
Cannot reproduce anymore. Should have been fixed already
