### ISSUE TITLE
[FR] Support .deb package for Linux

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1303]
### Description

It's a normal installation way on Linux. Please integrate the `.deb` installation way on the release page.

### Impact

The Linux user will be easier to install AppFlowy.

### Additional Context

https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html
https://pub.dev/packages/flutter_to_debian

**Comment by ramanverma2k** [comment]
Hi!
I can work on this issue. Can you please assign it to me?

**Comment by annieappflowy** [comment]
Hi #ramanverma2k , thanks! Just assigned it to you

**Comment by ramanverma2k** [comment]
Thank you very much!

I'll get on it ASAP.

**Comment by ramanverma2k** [comment]
Hi,

I need some advice regarding the implementation of package generation.
While it would be quite faster & painless to make deb package using ```flutter_to_debian```, I don't think that it's would be the right kind of approach as depending on a third party package for a single purpose would be quite meaningless.

I was thinking of extending the linux script defined in flutter.toml to generate deb package after ```flutter build``` process is finished.

**Comment by LucasXu0** [comment]
Hi, @ramanverma2k. I read the documentation(https://pub.dev/packages/flutter_to_debian), and don't think we need to depend on `flutte_to_debain` directly. We can integrate the `flutter_to _debian` into the CI stage.

**Comment by annieappflowy** [comment]
Is this issue resolved? @ramanverma2k

**Comment by ramanverma2k** [comment]
> Is this issue resolved? @ramanverma2k 

Yes, it was merged in [#1303](https://github.com/AppFlowy-IO/AppFlowy/pull/1386)

**Comment by annieappflowy** [comment]
thanks @ramanverma2k for confirming. I'm closing this comment.
FYI, we're preparing for our first-ever mentorship program. If you are interested, please kindly check out a [survey](https://github.com/AppFlowy-IO/AppFlowy/issues/1427)
