### ISSUE TITLE
[FR] Support .exe setup for Windows

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1305]
### Description

It's a normal installation way on Windows. Please integrate the `.exe` setup installation way on the release page.

### Impact

The Windows user will be easier to install AppFlowy

### Additional Context

https://retroportalstudio.medium.com/creating-exe-executable-file-for-flutter-desktop-apps-windows-ea7c338465e

**Comment by siddhesh-coder** [comment]
assign me this issue

**Comment by ramanverma2k** [comment]
@siddhesh-coder Are you still working on this issue or is it available for taking?

**Comment by LucasXu0** [comment]
Hi, @ramanverma2k. I don't think @siddhesh-coder is still working on this issue. Would you want to take this issue?

**Comment by ramanverma2k** [comment]
Hi, @LucasXu0. Yes, I would like to work on this issue.

**Comment by LucasXu0** [comment]
I assigned it to you. Please let me know whether or not you need help.

**Comment by ramanverma2k** [comment]
@LucasXu0 Can you please check the installer & test it?

[AppFlowy-test-1305-windows-x86_64.exe](https://github.com/ramanverma2k/AppFlowy/releases/download/refs%2Fheads%2Ftest-1305/AppFlowy-test-1305-windows-x86_64.exe)

**Comment by LucasXu0** [comment]
@ramanverma2k I installed the .exe package on my windows 11 computer. And it works fine.
