### ISSUE TITLE
[Bug] DatePicker cannot go further in the past than July (for now)

### ISSUE THREAD

**Issue by Kaijiro** [AppFlowy-IO/AppFlowy#1307]
### Bug Description

I am fiddling with the grid and actually the DatePicker is kinda ... stuck : I can't go earlier than July 2022 and further than January 2023. 
I correspond to the actual semester, maybe it's a "widget" misconfiguration ?

### How to Reproduce

Create a Grid page, add a Date column.
Add a row then try to select the 1st of January 2022.

### Expected Behavior

I should be able to select any date I want.

### Operating System

MacOS BigSur 11.6.2

### AppFlowy Version(s)

0.0.5.3 (1)

**Comment by richardshiue** [comment]
Can confirm. The current calendar specifically only allows you to go 3 months forward or backward in time. Perhaps it was causing performance problems in the past, I'm not sure. But this definitely needs improvement

**Comment by annieappflowy** [comment]
Is this planned in v0.0.7? @appflowy

**Comment by annieappflowy** [comment]
Fixed already
