### ISSUE TITLE
[FR]suporrt graphviz、mermaid、drawio、mindmap

### ISSUE THREAD

**Issue by Angel0726** [AppFlowy-IO/appflowy#131]
support graphviz、mermaid、mindmap、echarts、drawio
**1~3 main use cases of the proposed feature**
1. graphviz: It is the software often used in data structure. It can plot tree and graph. i often use it to describe data structure in leetcode
![image](https://user-images.githubusercontent.com/32816780/145536463-b0b72222-8a79-4416-8fd9-481b06e9bbcd.png)
2. mermaid: as we know many markdown editor support it
![image](https://user-images.githubusercontent.com/32816780/145536914-04a32b67-598c-4f19-aa87-90dc94ad5fdc.png)
3. mindmap: it syntax of mind mapping
![image](https://user-images.githubusercontent.com/32816780/145536083-27aba255-2fea-4ddc-a667-1b350a5d84e4.png)
4. echarts: It is a syntax for diagrams that provides an interactive experience
[image](https://user-images.githubusercontent.com/32816780/145546606-4ae0cffd-ff4e-4abc-8e6d-092f3bf8dc52.png)
![image](https://user-images.githubusercontent.com/32816780/145572348-65ff90c4-8ab8-40f5-8f45-6ecbfe303020.png)
5. drawio: Open source drawing software, programmers often use it to make frame diagrams
![image](https://user-images.githubusercontent.com/32816780/145537088-7fdf19e3-253a-4929-a1d6-82a22f4c500d.png)

**what types of users can benefit from using your proposed feature**
Ex: It practitioners include teachers, students, programmers and product managers
**Additional context**
you can experience graphviz、mermaid、mindmap、echart in [siyuan note](https://b3log.org/siyuan/)  or [vditor](https://github.com/Vanessa219/vditor/blob/master/demo/markdown/zh_CN.md)
[drawio](https://app.diagrams.net/) is a open source software, it can export .png(Usually Png will have one more prefix drawio) picture, and edit .png picture。 what's more, we can use markdown to import  .png picture which genered by drawio. **what i want， Drawio is integrated into AppFlow, or AppFlow can specify drawio to open Png picture**。

**Comment by annieappflowy** [comment]
> support graphviz、mermaid、drawio、mindmap

Hi @Angel0726 

Could you please follow the template provided for proposing a feature? We would need to know more context in order to understand your request.

Thanks,
Annie

**Comment by Angel0726** [comment]
> > support graphviz、mermaid、drawio、mindmap
> 
> Hi @Angel0726
> 
> Could you please follow the template provided for proposing a feature? We would need to know more context in order to understand your request.
> 
> Thanks, Annie

[siyuan note](https://b3log.org/siyuan/)  it is  Similar with you,  what's more itsupport  graphviz、mermaid、mindmap, 
1. mindmap
![image](https://user-images.githubusercontent.com/32816780/145536083-27aba255-2fea-4ddc-a667-1b350a5d84e4.png)
2. graphviz  is open source graph visualization software. it can plot tree and graph
![image](https://user-images.githubusercontent.com/32816780/145536463-b0b72222-8a79-4416-8fd9-481b06e9bbcd.png)
3. mermaid 
![image](https://user-images.githubusercontent.com/32816780/145536914-04a32b67-598c-4f19-aa87-90dc94ad5fdc.png)
4. [drawio](https://app.diagrams.net/) is a open source software, it can export png picture, and edit drawio.png picture
![image](https://user-images.githubusercontent.com/32816780/145537088-7fdf19e3-253a-4929-a1d6-82a22f4c500d.png)

**Comment by Angel0726** [comment]
> > support graphviz、mermaid、drawio、mindmap
> 
> Hi @Angel0726 
> 
> Could you please follow the template provided for proposing a feature? We would need to know more context in order to understand your request.
> 
> Thanks,
> Annie

i have followed the template

**Comment by MikeWallaceDev** [comment]
@Angel0726 When creating a FR or a big report, please include one feature per FR. We use these to delegate tasks and I'm sure you understand we can't assign everything at once. In this case these features might be assigned to 4 different developers. Can you please separate these into separate requests? Thank you :-)

**Comment by Angel0726** [comment]
> @Angel0726 When creating a FR or a big report, please include one feature per FR. We use these to delegate tasks and I'm sure you understand we can't assign everything at once. In this case these features might be assigned to 4 different developers. Can you please separate these into separate requests? Thank you :-)

Yes, i have done
