### ISSUE TITLE
[FR] Local Sync for data backup

### ISSUE THREAD

**Issue by VenomSupreme** [AppFlowy-IO/AppFlowy#1310]
### Description

We can sync our data to a folder, backing up all our data locally.

In case of a crash, reinstall when all our data gets lost, we should be able to link the folder in appflowy and it'll sync all our data back.

Option to set the time for data sync, like every 5minutes, every day, every time app starts etc.

### Impact

Backup for all our data, always a good thing.  

Import/export is great, but sync increases productivity as we don't have to worry about import/export everytime we make a change in our notes.

**Comment by ziyziyziy888** [comment]
Remote Sync is also useful.

**Comment by heyakyra** [comment]
> Remote Sync is also useful.

Looks like server sync (see https://github.com/AppFlowy-IO/AppFlowy/issues/246 and https://github.com/AppFlowy-IO/AppFlowy/issues/714) is expected in v0.1.4 in Q2 of this year according to the roadmap https://github.com/AppFlowy-IO/AppFlowy/discussions/1715#discussioncomment-5315703

**Comment by smit-io** [comment]
> @VenomSupreme , [v0.0.9.1 (the latest release)](https://github.com/AppFlowy-IO/AppFlowy/releases) seems to fulfil your needs, enabling users to define where to store their data and create separate folders to better manage it. If you can give it a try and let us know your feedback, that would be very much appreciated. <img alt="Screenshot_20230202_055947" width="602" src="https://user-images.githubusercontent.com/12026239/216294099-13bfdc60-5ed9-4714-9861-c4afad3ea4d2.png"> ![image](https://user-images.githubusercontent.com/12026239/216294244-cb5f9a61-5bc3-4960-8704-da95a9f466e8.png)

I don't see the second option in the latest version V 0.3.x ?
