### ISSUE TITLE
[Bug] undo Quote doesn't work

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1325]
### Bug Description

I marked some text as code and formatted as Quote then I can't undo Quote via clicking on the Quote icon. 
Same as I inserted a Quote block through '/' 

### How to Reproduce

<img width="512" alt="image" src="https://user-images.githubusercontent.com/12026239/197158189-2bd0ea9b-ae05-4fcb-b0fd-553854af6e98.png">

### Expected Behavior

I can undo the Quote format by clicking on the Quote icon again 

### Operating System

macOS

### AppFlowy Version(s)

integrate_appflowy_editor

**Comment by alemoreau** [comment]
Hi ! I took the liberty of trying to fix this issue in this PR. https://github.com/AppFlowy-IO/AppFlowy/pull/1353 :innocent: 
I'm open to any feedback.

**Comment by LucasXu0** [comment]
> Hi ! I took the liberty of trying to fix this issue in this PR. #1353 😇 I'm open to any feedback.

Thanks. I merged it and added some tests.
