### ISSUE TITLE
[FR] handle failed to upload an image

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1327]
### Bug Description

if the image is not successfully inserted, the system should tell the user by showing an error msg

### How to Reproduce

use slash to insert an image

### Expected Behavior

show an error msg telling users what to do

### Operating System

macOS

### AppFlowy Version(s)

integrate_appflowy_editor

**Comment by annieappflowy** [comment]
If I use www.appflowy.io to upload, it does nothing without an error message. I'm using v0.2.5

**Comment by Xazin** [comment]
For URL Images, we can create a regex pattern to match only supported filetypes, eg. `gif, png, jpg, ico` etc.

I don't believe we have this as of yet, I could be wrong.
