### ISSUE TITLE
[FR] Support tab to indent checkbox

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1328]
### Description

Support using 'Tab' to indent a checkbox line so we can use it to represent a subtask 
Currently, the bulleted list supports indentation
<img width="148" alt="image" src="https://user-images.githubusercontent.com/12026239/197162996-8e805a13-8cdf-40f8-9da4-35e5b13280f1.png">

### Impact

Users who use checkboxes to track tasks and need multi-level checkboxes

**Comment by annieappflowy** [comment]
Hi @mymyxtran , welcome! Thanks for offering the help. Assigned you to this task. 
Your mentor is @LucasXu0 for completing this issue. If you need help or guidance, please reach out us on Discord.

**Comment by MayurSMahajan** [comment]
This issue is solved with this PR: #1847
