### ISSUE TITLE
[Bug] Copy paste doesn't work properly

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1330]
### Bug Description

<img width="273" alt="image" src="https://user-images.githubusercontent.com/12026239/197165236-d0d2b347-d6fb-48dc-94aa-11b3dc68237a.png">

### How to Reproduce

Copy multiple lines by using command + A and command + C
Paste by using command + V
You will see it's reversed

### Expected Behavior

Pasted text should look the same as copied text

### Operating System

macOS

### AppFlowy Version(s)

integrate_appflowy_editor

**Comment by LucasXu0** [comment]
It was fixed in https://github.com/AppFlowy-IO/AppFlowy/issues/1330.
