### ISSUE TITLE
[FR] Support markdown rendering, compilation and export for easier switching from Notion to AppFlowy

### ISSUE THREAD

**Issue by ARGF0RCE** [AppFlowy-IO/AppFlowy#1332]
### Description

The app does not autorender markdown, as a result no compiler for markdown, and I don't see any option for Exporting it as markdown or pdf. The video recording below shows the same. I understand that the goal is to not completely replicate Notion but I think adding autorender features for markdown would be a huge plus for the app. Otherwise I face only a few bugs which I think the community is doing its best to fix it including myself.

https://user-images.githubusercontent.com/86123710/197176462-522af039-0cc6-4403-9959-a60d93eccf39.mp4

I think that I can work on this feature. If you can provide me some kind of roadmap on what features to be included and what limitations would be there to make such a feature, that would be of great help. Although I am new to open source, I am not new to flutter. I will be glad to make my first contribution to this app which I think is a very good initiative.

Long Live OpenSource!

### Impact

This feature can provide ease of typing and note-taking management without using the mouse for formatting your text. This will be a huge plus for the app as many developers that use any Documentation API or note-taking API are generally based on Markdown such as mkdocs, jekyll, etc., even Notion. As this is an opensource project, I think aiming for the opensource developers would be beneficial in faster growth of the app as they will use the app to prerender their documentation and give help in contributing to the opensource.

Long Live OpenSource!

**Comment by ARGF0RCE** [comment]
I think that I can work on this feature. If you can provide me some kind of roadmap on what features to be included and what limitations would be there to make such a feature, that would be of great help. Although I am new to open source, I am not new to flutter, dart, a little bit of rust, python, devops, machine learning, tensorflow, robotics. I will be glad to make my first contribution to this app which I think is a very good initiative.

**Comment by annieappflowy** [comment]
Hi @ARGF0RCE , [v0.0.6](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.0.6) is out. It includes a major upgrade to the editor experience. We now support basic Markdown syntax! 
That said, there are advanced Markdown syntax we have not supported yet. If you are interested in working on this topic, you can pick one that's not supported. Here is an[ example](https://github.com/AppFlowy-IO/AppFlowy/discussions/1100) you can follow. It should be quite straightforward if you know Flutter.

**Comment by annieappflowy** [comment]
Here is a list of markdown we support: https://appflowy.gitbook.io/docs/essential-documentation/markdown
We also support export as .md
Please give it a try using the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases)
