### ISSUE TITLE
[FR] Bulleted list to support shift + tab to outdent 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1334]
### Description

Now I can press 'Tab' to indent a bullet item but cannot use shift+tab to outdent

### Impact

Shortcut users who use bulleted lists to organize information

**Comment by annieappflowy** [comment]
Is this going to be included in the upcoming release?
I'm not able to outdent on the main branch

**Comment by annieappflowy** [comment]
- [ ] update documentation

**Comment by MayurSMahajan** [comment]
AppFlowy is using the editor version: ^0.1.5, this feature is included in Editor release ^0.1.9.

**Comment by MayurSMahajan** [comment]
The documentation seems to be updated and the feature is working with the latest main branch. So I am closing this issue as completed now.
