### ISSUE TITLE
[Enhancement] A hyperlink for LICENSE.md in the README file

### ISSUE THREAD

**Issue by AnirudhDaya** [AppFlowy-IO/AppFlowy#1335]
Hello maintainers,
I would like to propose an addition/improvement to the existing license section of your [README](https://github.com/AppFlowy-IO/AppFlowy/blob/main/README.md#license) file.
It's a hyperlink to your LICENSE.md, so it's currently like this:  `LICENSE.md` and I would like to change it into a hyperlink like this [`LICENSE.md`](https://github.com/AppFlowy-IO/AppFlowy/blob/main/LICENSE), which would be helpful while exploring your humble repository, especially for the new contributors. 
If you feel like this is a helpful addition, please do tell me if I can proceed with this issue and submit a PR for the same.

**Comment by annieappflowy** [comment]
Hi @AnirudhDaya , thanks for your suggestions. Is this fixed?

**Comment by AnirudhDaya** [comment]
Hi @annieappflowy, somebody already did fix this issue recently

**Comment by annieappflowy** [comment]
Thanks @AnirudhDaya , closing this one. Please don't hesitate to submit more feature requests and bug reports
