### ISSUE TITLE
[FR] Tooltip design

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1338]
### Description

The appflowy design doc has the following design when hovering over the toolbar in the flowy editor

![image](https://user-images.githubusercontent.com/71320345/197372569-6519e470-785f-48d1-a550-40477338040d.png)

Is this the desired tooltip style that will be used throughout the application? If so, I'd love to see it get implemented. There is an issue to consider though: the shortcut key's text color is a slightly muted color which I'm not sure how it should fit in with the above design.

![image](https://user-images.githubusercontent.com/71320345/197372686-b6108c18-4017-4ea9-a8c3-67a1f40a49a6.png)

### Impact

Users will be seeing a tooltip style native to Appflowy instead of the default one offered by material design

**Comment by LucasXu0** [comment]
Thanks for the suggestion. Since the `AppFlowy Editor` project doesn't depend on `AppFlowy` when it is created, the style of the tooltip is not considered. I will update it to adapt to the AppFlowy theme style.

**Comment by aaronang** [comment]
I believe this issue has been resolved?

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7579804/7c819608-89a6-4279-a491-f8627d7d74ff)

Something I noticed is that the "Close side bar" tooltip is left-aligned, while the text formatting tooltip texts are center-aligned. Is there a design standard for AppFlowy regarding tooltip text alignment?

**Comment by annieappflowy** [comment]
<img width="162" alt="image" src="https://github.com/user-attachments/assets/0fac1cb6-c9f8-4534-a974-ccec2552851c">
<img width="149" alt="image" src="https://github.com/user-attachments/assets/e19a2d70-f516-4324-aec6-a992ee314240">
