### ISSUE TITLE
[Bug] Flowy Hover Effect Disappearing on Hover when it triggers a Popover

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1345]
### Bug Description

Title says all. Opening an issue here in case I forget about this.

### How to Reproduce

1. Go to a grid cell header
2. Click edit property
3. Hover over the type option
4. Observe that the hover effect disappears until you move the mouse out of the rectangle and then back in again, after which it will show for a split second and disappear once again.

### Expected Behavior

The hover effect should persist

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

v0.0.5.3

### Screenshots

https://user-images.githubusercontent.com/71320345/197409772-3e8ac900-f4d6-4f76-9661-f702f3b0f883.mp4

**Comment by Eakam1007** [comment]
Hi, I would like to work on this
