### ISSUE TITLE
[FR] update readme

### ISSUE THREAD

**Issue by saimaheshtaduri** [AppFlowy-IO/AppFlowy#1349]
### Description

The issue link in readme isn't appropriate.

### Impact

This change helps users raise issues easily. 

change from 
If you'd like to propose a feature, submit an issue [here](https://github.com/AppFlowy-IO/appflowy/issues).
to : 
If you'd like to propose a feature, submit a feature request [here](https://github.com/AppFlowy-IO/AppFlowy/issues/new?assignees=&labels=&template=feature_request.yaml&title=%5BFR%5D+)
If you'd like to report a bug, submit bug report [here](https://github.com/AppFlowy-IO/AppFlowy/issues/new?assignees=&labels=&template=bug_report.yaml&title=%5BBug%5D+)

**Comment by saimaheshtaduri** [comment]
@appflowy

**Comment by Smartmind12** [comment]
@saimaheshtaduri I would like to work on this issue and rectify the changes!

**Comment by saimaheshtaduri** [comment]
@Smartmind12 even Iam waiting for their approval.
