### ISSUE TITLE
[Bug] Pages

### ISSUE THREAD

**Issue by andercard0** [AppFlowy-IO/AppFlowy#1350]
### Bug Description

As soon as I opened my notes after update I realize that there is a new page with 'NoStatus' label on it, so far so good it was just a matter of move this new page to the end..but.. I moved it and soon as i reopen the app it return to its starting point. as shown below.

![MovePage](https://user-images.githubusercontent.com/43047877/197591611-5eb38462-8242-40f0-9428-32a99158f987.gif)

### How to Reproduce

- Open the app
- Move the new page 
- Close the application
- Reopen the application, page returns to its starting point.

### Expected Behavior

Make changes in my stuff permanet.

### Operating System

Windows 10

### AppFlowy Version(s)

V0.0.6

**Comment by annieappflowy** [comment]
@andercard0 , we fixed this
