### ISSUE TITLE
[Bug] Invalid (Dark) Theming of Editor Menu's 

### ISSUE THREAD

**Issue by rshchekotov** [AppFlowy-IO/AppFlowy#1351]
### Bug Description

There are several menu's where the theming is off in Dark Mode, which either simply looks off or even makes the menus unreadable.

Examples would be:
- Barely readable "Right-Click in Editor > [Cut; Copy; Paste] Context Menu" on Hover
- Not readable Link/URL Editor: White-on-White (likely simply unfinished)
- Perhaps unintended thick white border around the before mentioned Cut-Copy-Paste menu (?)

There might be some more bugs of this kind in submenus, that I haven't yet discovered.

(I'm aware that this is not a major bug and is likely something that's work in progress anyways, especially seeing that this project is in quite a beta-status just yet or at least, so I'd guess from the version number v0.0.x)

### How to Reproduce

1. Turn on Dark Mode
2. Create a new Page
3. Write some text
  - Select text and add a hyperlink to the text (White font on white background)
  - Right-Click anywhere within the editor of the created page and observe the thick white border and the hover-effect on the context items

### Expected Behavior

Correct Dark Theming (?)

### Operating System

Windows 11

### AppFlowy Version(s)

v0.0.6

### Screenshots

<img width="291" alt="image" src="https://user-images.githubusercontent.com/82679380/197608556-9638b64d-99c8-4003-b0a9-a5110de0fd55.png">
<img width="138" alt="image" src="https://user-images.githubusercontent.com/82679380/197608623-da49c341-e3fb-409e-abd0-c5dcf803de48.png">
<img width="155" alt="image" src="https://user-images.githubusercontent.com/82679380/197608659-fe1accbf-28ae-4137-9e7e-a30b50fda5e0.png">

**Comment by LucasXu0** [comment]
Hi, @rshchekotov. I have resolved this issue.

**Link Menu**
<img width="694" alt="Screen Shot 2022-10-26 at 14 42 26" src="https://user-images.githubusercontent.com/11863087/197956185-0237f65f-87ac-45d3-b3f3-8f31eac374db.png">

**Context Menu**
<img width="694" alt="Screen Shot 2022-10-26 at 14 42 26" src="https://user-images.githubusercontent.com/11863087/197956361-f84e8428-cd7a-4fb3-bb70-29a9b4c0826c.png">

**Image Menu**
 <img width="720" alt="Screen Shot 2022-10-26 at 14 42 03" src="https://user-images.githubusercontent.com/11863087/197956584-0d242c85-88c5-4c1e-b437-08a9004d1005.png">
