### ISSUE TITLE
[Bug] IME preview results do not disappear after typing

### ISSUE THREAD

**Issue by novload** [AppFlowy-IO/AppFlowy#1352]
### Bug Description

1. When I type Chinese, IME preview results do not disappear after typing.
2. The characters are in the wrong position when typing multiple times.

### How to Reproduce

Windows11, Microsoft Pinyin IME, type Chinese in editor.

### Expected Behavior

The preview should disappear after typing

### Operating System

Windows11 22621.674

### AppFlowy Version(s)

0.0.6

### Screenshots

App Flowy:

https://user-images.githubusercontent.com/9421929/197629721-9636a2fc-8ea3-4748-8fa2-ff0506d2e8d1.mp4

Notepad:

https://user-images.githubusercontent.com/9421929/197629744-4371a421-418e-41be-bd00-e2306d13c0a3.mp4

**Comment by LucasXu0** [comment]
Hi, @novload. We will try to adapt the IME for Windows and Linux.

**Comment by annieappflowy** [comment]
Fixed
