### ISSUE TITLE
[FR] Absence of a Pull Request template

### ISSUE THREAD

**Issue by Smartmind12** [AppFlowy-IO/AppFlowy#1358]
### Description

Currently there is an absence of a Pull request template beacue of which the pull request created by contributors are not streamlined and difficult to connect an issue (if not mentioned by the user).

### Impact

For all users who want to contribute to the project via pull request merging and issue solving.

### Additional Context

Kindly assign this issue to me so that i can make a PR for the same! (Hacktoberfest 2022)

**Comment by Xazin** [comment]
@a-wallen We can close this as a result of the PR template you added.
