### ISSUE TITLE
[Bug] Deleting a document page leaves the content area black after deleting permanently.

### ISSUE THREAD

**Issue by branhillsdesign** [AppFlowy-IO/AppFlowy#136]
**Describe the bug**
Deleting a document page leaves the content area black after deleting permanently.

**To Reproduce**
1. Click on ':' to bring up document menu in the side navigation.
2. Click on '🗑 Delete'
3. Click on 'Delete Permanently' in the banner that appears in the content frame.
4. Content area is left black until a different document is selected.

**Expected behavior**
The expected behavior is to show content from a nearby document that currently exists.

**Screenshots**
![image](https://user-images.githubusercontent.com/51428934/145703394-3e78c5ab-818a-4e3c-9432-88901e223a3b.png)
![image](https://user-images.githubusercontent.com/51428934/145703417-4732f9ee-da9f-4ba3-8c8f-7aae3214d5bc.png)
![image](https://user-images.githubusercontent.com/51428934/145703419-cb182be7-e6da-4593-895a-3a1bb9639ee2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop Application

**Comment by annieappflowy** [comment]
Thanks Bran. This is a known issue, which is not prioritized at the moment.

**Comment by annieappflowy** [comment]
Need to know Rust

**Comment by MikeWallaceDev** [comment]
I'm going to look into this now.  Please assign me and then delete this comment.  Thank you.

**Comment by annieappflowy** [comment]
assigned to @MikeWallaceDev

**Comment by Grubba27** [comment]
![Captura de Tela 2022-01-18 às 22 08 21](https://user-images.githubusercontent.com/70247653/150044476-c792c4eb-93ed-4b65-bbf9-3d10dff77885.png)
This happens also on macOS, there is any place i should e looking for to deal with this issue ? I know a little of rust perhaps i can help :)

**Comment by MikeWallaceDev** [comment]
@Grubba27, Nathan is currently working on that code, so we can't really go into it right now.
