### ISSUE TITLE
[Bug] Wrong app version in help and support popup

### ISSUE THREAD

**Issue by LaBaude32** [AppFlowy-IO/AppFlowy#1365]
### Bug Description

As we can see in the image the version displayed is : 1.0.0.1.

### How to Reproduce

Open the AppFlowy, click on the ? icon (help and support) on the bottom right corner.

### Expected Behavior

Display the right version number : 0.0.6

### Operating System

Debian 11

### AppFlowy Version(s)

0.0.6

### Screenshots

![image](https://user-images.githubusercontent.com/42806696/197825647-753b082c-1a27-4007-873a-3adaf0fa9371.png)

**Comment by annieappflowy** [comment]
Thanks @LaBaude32 , we need to upgrade Flutter to 3.3 to fix this issue .
