### ISSUE TITLE
[FR] Ability to drag sub-pages between sections

### ISSUE THREAD

**Issue by MarkJThomas** [AppFlowy-IO/AppFlowy#1372]
### Description

Right now I can't move a sub-page between sections, so if I think a sub-page is better suited elsewhere I have to re-do it in the new section. 

### Impact

This is something I feel people would benefit from, who are as organised as me and always moving things around and re-imagining how the sections should look.

**Comment by LucasXu0** [comment]
Related PR: https://github.com/AppFlowy-IO/AppFlowy/pull/3083

We will release it in the next version.

Here's the preview.

<img width="1316" alt="Screenshot 2023-07-31 at 20 11 44" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/3ae6ba21-89a9-4fe8-be6c-a2f80fbe7361">

**Comment by Harmon758** [comment]
This is in v0.2.8 now.
