### ISSUE TITLE
[FR] Integration between kanban boards, table items and pages

### ISSUE THREAD

**Issue by mizzyc** [AppFlowy-IO/AppFlowy#1378]
### Description

It'd be nice to have a integration between de kanban board cards and the rest of my pages and tables on Flowy.
I think it'd work just like in Notion, by letting me create roll-up fields in the kanban to sync between the tables.
Also, a way to change the kanban to other views, like a table view, would be awesome!

### Impact

To be honestly, that's pretty much the only thing that keeps me from moving all my workflow directly to Flowy.
I think it'd be game changer for choosing Flowy instead of Notion or other softwares.

**Comment by annieappflowy** [comment]
Hi @mizzyc , thanks for your feedback. Integrating Kanban Board and Gird into pages is planned to release at v0.0.9
We look forward to getting more feedback from you when it's shipped :D

**Comment by LucasXu0** [comment]
#1759
#1675

We have integrated the Board and Grid into the Document page and will release them at v0.1.0.
