### ISSUE TITLE
[Bug] High CPU on macOS

### ISSUE THREAD

**Issue by Thearas** [AppFlowy-IO/appflowy#138]
**Describe the bug**
The CPU usage of AppFlowy is always greater than 100:

**To Reproduce**
1. `brew install appflowy` and run
2. Create a page and write something
3. Wait a few minutes and do nothing, the CPU usage is still high (greater than 100)

**Screenshots**
![image](https://user-images.githubusercontent.com/44015907/145770188-d35ec39f-2a93-47e6-9ab9-c1ec093c7f60.png)

**Desktop (please complete the following information):**
 - OS: macOS M1
 ```
Darwin ThearasdeMacBook-Pro-13.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64
```
 - Browser: chrome
 - Version: 96.0.4664.93

**Comment by Thearas** [comment]
![image](https://user-images.githubusercontent.com/44015907/145774701-e0d36771-f809-42cf-85a7-74fd82322d1d.png)

```sh
xctrace record --template 'Time Profiler' --time-limit 10s --attach AppFlowy
```

**Comment by MikeWallaceDev** [comment]
I would just like to add that this doesn't happen on Linux. At least not with the details shared here. I page, let it sit there for 40 minutes and there was no cpu problem.

**Comment by Thearas** [comment]
It is reproducing steadily on my mac. Maybe I'm missing something, or maybe the problem is related to my local data?

**Comment by appflowy** [comment]
@Thearas  I try to reproduce this bug but fail. Would you mind showing me what you type in the document or any steps to reproduce this?
![image](https://user-images.githubusercontent.com/86001920/147934224-09b92070-a020-4e88-8a2d-0f64bafa9dab.png)

**Comment by Thearas** [comment]
> @Thearas I try to reproduce this bug but fail. Would you mind showing me what you type in the document or any steps to reproduce this? 

I reproduce this bug successfully by:
***Enter some some long Chinese sentences with Sogou Pinyin***😂
![image](https://user-images.githubusercontent.com/44015907/148346657-ccb8e344-8bd3-42d9-8e83-63e46fc4eee2.png)

Non-reproducible when typing English.

**Comment by appflowy** [comment]
Thanks, the problem has been solved!

**Comment by rebron1900** [comment]
@appflowy When will the next version be released?

**Comment by appflowy** [comment]
> @appflowy When will the next version be released?

Will be published at the end of this month.
