### ISSUE TITLE
[Bug] Grid URL property's edit button

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1385]
### Bug Description

In a grid with a URL property, hovering in any other field in the same row triggers the edit button to show up in the URL cell.

### How to Reproduce

1. Go to a grid with a URL property
2. Hover over a row, on a property apart from the URL property
3. Observe that the editor URL button appears

### Expected Behavior

The button should only show when the user hovers over the exact cell, not the row in general

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

v0.0.6

### Screenshots

![image](https://user-images.githubusercontent.com/71320345/198276005-74a620f0-bf9c-454f-ab36-5b3af7754de3.png)

**Comment by Onyedikareal** [comment]
Hi @richardshiue, I will like to work on this. Please can you assign this to me?

**Comment by richardshiue** [comment]
Hello @Onyedikareal, thanks for offering to help on this! I'm not a maintainer so I can't do that for you, sorry. Ping @annieappflowy

**Comment by Onyedikareal** [comment]
Alright, thanks @richardshiue. 
Hi @annieappflowy, please can you assign this to me.

**Comment by richardshiue** [comment]
> Hi @Onyedikareal , thanks for offering the help. I just assigned the issue to you. @richardshiue , I've added you to our org as a collaborator. Going forward, you will be able to manage issues for AppFlowy. You should receive an invite from GitHub to accept your new role! ![image](https://user-images.githubusercontent.com/12026239/200281294-9dd7fe53-39d4-473a-9858-b59f247339dd.png)

Thanks, that'd be an honor

**Comment by Onyedikareal** [comment]
> Hi @Onyedikareal , thanks for offering the help. I just assigned the issue to you. @richardshiue , I've added you to our org as a collaborator. Going forward, you will be able to manage issues for AppFlowy. You should receive an invite from GitHub to accept your new role! ![image](https://user-images.githubusercontent.com/12026239/200281294-9dd7fe53-39d4-473a-9858-b59f247339dd.png)

Thanks

**Comment by richardshiue** [comment]
Hey there @Onyedikareal, do you have any update on this?

**Comment by Onyedikareal** [comment]
Hi @richardshiue , thanks for asking. Unfortunately I'm hooked here. Will appreciate it if someone can assist me on this.

**Comment by Onyedikareal** [comment]
Hi @richardshiue , thanks for asking. Unfortunately I'm hooked here. Will appreciate it if someone can assist me on this.

**Comment by richardshiue** [comment]
Okay I'll look into it and let you know if I find something

**Comment by richardshiue** [comment]
Sorry I took so long to get back to you. The problem is that we want the primary cells (aka non-deletable title field) to show the open as page accessory just by hovering over it or any other cell in the row. See `app_flowy/lib/plugins/grid/presentation/widgets/cell/cell_container.dart`

![image](https://user-images.githubusercontent.com/71320345/211156478-29f7dff0-8fc4-4ccf-8ea4-42e0eaf5b395.png)

the onEnter stores the state of the hover event. So when a row is hovered, the cell also "gets hovered" in effect. The problem is that it's not happening only to the primary cells but the URL ones as well. So here, we should remove the update clause and replace the `ChangeNotifierProxy` with `ChangeNotifierProvider<_CellContainerNotifier>`. You can also remove `rowStateNotifier` field as well. 

With this change primary cells won't have the previous behavior. To bring it back, we need to pass the `isPrimary` flag into `CellContainer` (I'll let you figure out from where) and then into `_GridCellEnterRegion`. Then, change out the Selector for a Selector2 with the selector clause being

```
return Selector2<RegionStateNotifier, _CellContainerNotifier, bool>(
  selector: (context, regionNotifier, cellNotifier) => !cellNotifier.isFocus && (cellNotifier.onEnter || regionNotifier.onEnter && isPrimary),
...
```

I think the selector is pretty self-explanatory. If you have another way fix it, feel free to submit a PR, but I think that's the gist of it. If you have further questions, please don't hesitate to reach out to me on Discord

**Comment by richardshiue** [comment]
@Onyedikareal gentle ping :)

**Comment by Onyedikareal** [comment]
@richardshiue Thanks for the gentle ping ;-) . I'm just seeing your first response.  Will apply your suggestion and see if that fixes the problem. 
Thanks so much.

**Comment by onyicodes** [comment]
@richardshiue Thanks so much for the help. I've sorted this issue out with your guide.

**Comment by richardshiue** [comment]
That's awesome! Hoping to see your PR soon
