### ISSUE TITLE
[Bug] a bug when typing Chinese pinyin

### ISSUE THREAD

**Issue by guchengxi1994** [AppFlowy-IO/AppFlowy#1404]
### Bug Description

when typing pinyin , the title keep the pinyin string when typing is done.

### How to Reproduce

see Screenshots

### Expected Behavior

Only the Chinese string reserved.

### Operating System

windows

### AppFlowy Version(s)

release v0.0.6.2

### Screenshots

![20221031](https://user-images.githubusercontent.com/33513462/198946597-656a34f7-9d4f-4bcd-b1e9-bd15b886879b.gif)

**Comment by annieappflowy** [comment]
Thanks for reporting. This is a known issue for Flutter.

**Comment by ziyziyziy888** [comment]
Same problem.
