### ISSUE TITLE
[Bug] No focus border on date cells

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1414]
### Bug Description

Title says all.

### How to Reproduce

1. Go to a grid with a date property
2. Click on a cell under the date property
3. Observe that there is no focus border

### Expected Behavior

Cell should have a bright blue focus border

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

v0.0.6

### Screenshots

![image](https://user-images.githubusercontent.com/71320345/199764075-dd1eb8c4-69a3-41d5-9484-a1c8e9c1995f.png)

**Comment by Eakam1007** [comment]
Hi, I would like to work on this

**Comment by richardshiue** [comment]
@Eakam1007 Sure, thanks for helping! I've assigned it to you. Don't hesitate to reach out to the AF team on Discord if you need help.
