### ISSUE TITLE
[Bug] Appflowy don't work with unicode font

### ISSUE THREAD

**Issue by chiconcota** [AppFlowy-IO/AppFlowy#1415]
### Bug Description

I using the Vietnamese language. When I'm Typing the letter, this letter disapper

### How to Reproduce

you can download unikey app and set unicode then you type the Vietnamese language like Thành or Việt you will see.

### Expected Behavior

I want this app can display "thành" or "việt". Not "thnh" or "vit" 

### Operating System

win 10

### AppFlowy Version(s)

0.0.6

**Comment by annieappflowy** [comment]
Thanks for reporting. This is a known issue for Flutter.

**Comment by LucasXu0** [comment]
Hi, @chiconcota. We are using `Poppins` as the built-in font. It doesn't support Unicode characters. https://github.com/itfoundry/Poppins/issues/25

We plan to add a new feature to support switching the font.

**Comment by annieappflowy** [comment]
Set the font to default in Settings -> Workspace -> Workspace font
