### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dominiksledzik** [AppFlowy-IO/AppFlowy#1416]
### Bug Description

On the taskbar the name of the application shows as "A new Flutter project."

### How to Reproduce

Right-click AppFlowy app on Taskbar.

### Expected Behavior

Displaying the name of the app, not the placeholder text.

### Operating System

Windows 11

### AppFlowy Version(s)

0.0.6.2

### Screenshots

![image](https://user-images.githubusercontent.com/57485073/200118007-1632e444-12d3-4031-91e3-2608cbbca822.png)

**Comment by annieappflowy** [comment]
Fixed
