### ISSUE TITLE
[Survey] AppFlowy's Pilot Mentorship Program 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1427]
In preparation for launching AppFlowy's Pilot Mentorship Program, we would like to collect your input to make the program successful and enjoyable.  Please kindly take 5mins to fill in this form to let us know your thoughts: [survey](https://tally.so/r/3Eqlyl) 🙏 💜

**Comment by MayurSMahajan** [comment]
@annieappflowy can this be closed now?

**Comment by annieappflowy** [comment]
I think so. Thanks for sending a reminder :D
