### ISSUE TITLE
[Bug] AppFlowy's website link on Flathub

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1430]
### Bug Description

I don't know if I should put this here or over at the Flathub's repository, but clicking on the website button on Flathub currently shows the following message, which is kinda concerning.

![image](https://user-images.githubusercontent.com/71320345/201008884-cea6b4be-6742-4a98-ac40-39983c9151f7.png)

### How to Reproduce

1. Go to the appflowy page on flathub
2. Scroll down and click "Website"
3. Observe that it doesn't redirect to AppFlowy's website

### Expected Behavior

I should see AF's website

### Operating System

any

### AppFlowy Version(s)

N/A

**Comment by LucasXu0** [comment]
Hi, @richardshiue. Thanks for the reminder. I just checked and updated the certificate. It will take effect after about 72 hours.

**Comment by richardshiue** [comment]
Okay awesome! Thank you so much

**Comment by richardshiue** [comment]
Hello @LucasXu0! The issue seems to be persisting from what I can tell, could please you check again?

**Comment by LucasXu0** [comment]
Hi @richardshiue. @annieappflowy has sent an email to the server provider. We are waiting for their reply.

**Comment by richardshiue** [comment]
The issue has been fixed. Closing as completed! Thanks @annieappflowy @LucasXu0
