### ISSUE TITLE
[Bug]  NetworkType null safety issue

### ISSUE THREAD

**Issue by Onyedikareal** [AppFlowy-IO/AppFlowy#1434]
### Bug Description

Connectivity result for vpn not implemented resulting to NetworkType returning null for the case where Connectivity result is vpn

### How to Reproduce

Steps to reproduce
* follow the contribution guideline on how to clone the repo to your local machine
* follow the steps to setup your development environment
* building your code will result to null safety issues relating to the NetworkType type in the file AppFlowy/frontend/app_flowy/lib/core/network_monitor.dart
* If you observe properly you will see that the case for `ConnectivityResult.vpn` was not implemented

### Expected Behavior

I expect NetworkType to return a well defined NetworkType or NetworkType.UnknownNetworkType for where NetworkType is not defined.
This will elimate the null safety issues.

### Operating System

Windows

### AppFlowy Version(s)

v0.0.6

### Screenshots

![image](https://user-images.githubusercontent.com/25469676/201101776-7ef0f905-88aa-4ae7-99aa-0c83513cdf43.png)

**Comment by richardshiue** [comment]
With #1435 merged, I believe this issue has been fixed. Closing as completed
