### ISSUE TITLE
[FR]  Support local image import

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#1436]
### Description

The feature will allow the user to import images from their computer.

### Impact

The user can take advantage of using local images if they don't wish to use network images.

### Additional Context

A separate copy of the image will be placed in the applications directory

**Comment by annieappflowy** [comment]
Thanks @Xazin for your feedback. We'll keep it in mind when designing this feature.

**Comment by bmcgonag** [comment]
I agree, I'd like to have a local image option since AppFlowy runs locally, seems odd to force me to upload an image to a server just to add a url for it to load from.
