### ISSUE TITLE
[FR] Resize image on editor

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#1439]
### Description

Currently when a image is attached in Flowy Editor. It comes in full size, which takes up note real estate and ends up being a long document.
Bringing this feature will shrink the images automatically when placed, and leave more space for the user to work. Should they choose to enlarge the image there will be a mechanism that allows it.

### Impact

Users can attach multiple images and not worry about screen real estate being used up. The minimal images can be viewed in full size with a single click.

**Comment by andhikalfariz** [comment]
Hello sir, may I take this issue?

**Comment by annieappflowy** [comment]
Sure! Thanks for offering the help. Just assigned to you
If you need help, you can reach out @LucasXu0

**Comment by rileyhawk1417** [comment]
Hi @andhikalfariz looking forward to working with you :)

**Comment by rileyhawk1417** [comment]
Hi @andhikalfariz any update on this issue?

**Comment by Xazin** [comment]
This has since been implemented :+1: Will close it
