### ISSUE TITLE
[Bug] CapsLock cannot switch language

### ISSUE THREAD

**Issue by ChenTaHung** [AppFlowy-IO/AppFlowy#1443]
### Bug Description

mac version : Ventura 13.0
appflowy version 0.0.6.2
`CapsLock` button cannot switch language between english and Chinese(bopomofo)
![image](https://user-images.githubusercontent.com/49839507/201465397-80f5992f-9900-45d0-bfc9-9ac673c31b6d.png)
 But `ctrl+space` works finely.

### How to Reproduce

create a new Doc, press `CapsLock` and the language is not changed.

### Expected Behavior

Language shows on the top of the screen will change when pressing CapsLock. But the language sign does not change and the typing language didn't switched as well.
![image](https://user-images.githubusercontent.com/49839507/201465505-b0fe4626-ca2c-41e1-859c-ae10e1584079.png) `<->` ![image](https://user-images.githubusercontent.com/49839507/201465511-147c067f-e1f3-4980-90e7-680d344e0b27.png)

### Operating System

MacOS Ventura 13.0

### AppFlowy Version(s)

0.0.6.2

**Comment by annieappflowy** [comment]
I tried on my mac. It works.
Please reopen if you still have the same issue.
