### ISSUE TITLE
[Bug] Website certificate invalid

### ISSUE THREAD

**Issue by TimJentzsch** [AppFlowy-IO/AppFlowy#1445]
### Bug Description

I get a security alert when trying to open <https://appflowy.io/> in a web browser, warning that a secure connection to the website could not be established.

### How to Reproduce

Open <https://appflowy.io/> in either Firefox or Chromium.

### Expected Behavior

I can access <https://appflowy.io/> without getting a security warning.

### Operating System

Linux (Pop!_OS)

### AppFlowy Version(s)

N/A

### Screenshots

Firefox:
![Warning: Potential Security Risk Ahead. Firefox detected a potential security threat and did not continue to appflowy.io. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.](https://user-images.githubusercontent.com/13908946/201472755-93fb8d5a-d36e-4b25-bb00-6bfffb7d9241.png)

Chromium:
![Your connection is not private. Attackers might be trying to steal your information from appflowy.io (for example, passwords, messages, or credit cards). `NET::ERR_CERT_COMMON_NAME_INVALID`](https://user-images.githubusercontent.com/13908946/201472778-cbf7644e-f729-4274-b672-3169162bbc71.png)

**Comment by richardshiue** [comment]
duplicate of #1430

**Comment by richardshiue** [comment]
The issue has been fixed. Closing as completed!
