### ISSUE TITLE
[FR] Create a menu item in the "?" that generates the required system info for a Bug report

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/appflowy#145]
**1~3 main use cases of the proposed feature**
As a developer it would be benificial to me to receive accurate information about the user's system
As a user it would help me to be able to just click a button a retrieve all the information that the dev requires.
As a user I sometimes don't know exactly what information the dev needs, or how to retrieve it.

**what types of users can benefit from using your proposed feature**
All AF devs and user's who need to create an issue report.

**Additional context**
I did not validate it, but there is a package for this : [Device Info Plus](https://pub.dev/packages/device_info_plus)

**Comment by Poly-Pixel** [comment]
Should it copy the debug info to the clipboard?

**Comment by MikeWallaceDev** [comment]
I was thinking about this and... Maybe you could send the information directly into a GitHub issue? (new clue if there's an API for that.)
Else, yeah, for now copying to the clipboard and popping a up a toast sounds like the way to go.

**Comment by Poly-Pixel** [comment]
Popping up a toast?
