### ISSUE TITLE
[FR] Create a new yellow theme for AppFlowy

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#1475]
### Need to Implement New Themes

- [x] Create a mechanism to select from multiple theme options
- [x] Create a new all-colored theme that utilizes all the colors in AppFlowy's logo.

We need to implement new themes for AppFlowy. We should offer a wide range of themes to the user to choose from, so that they can improve their experience with our application. One such theme i suggest we should implement is a yellow + red theme. 

This is my suggested theme:

![image](https://user-images.githubusercontent.com/47064215/203481648-147ff8f3-92f9-431c-b8ea-fd0e29d247e7.png)

### Impact

Every type of user can benefit from this feature. Having more themes to choose from offers a sense of customization to the user. This power of customization improves the overall user experience.

**Comment by MayurSMahajan** [comment]
@annieappflowy could you assign this one to me

**Comment by annieappflowy** [comment]
Thanks @MayurSMahajan . Just assigned it to you!

**Comment by MayurSMahajan** [comment]
Annie I am thinking of changing the theme selection option in settings to a listview, so that user can select from multiple themes. Right now there is only one toggle, so rather than that we will have a listview with all the themes.

![image](https://user-images.githubusercontent.com/47064215/204203634-4a27ffa4-8908-4dca-836c-640eeccffebe.png)


Do you think I should create a new issue for that or should I include it in this issue?

**Comment by annieappflowy** [comment]
Sounds good to me! You can include it in this issue with some descriptions.
