### ISSUE TITLE
[FR] Create a new purple dark theme

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#1476]
### Description

Need to Implement New Themes

We need to implement new themes for AppFlowy. We should offer a wide range of themes to the user to choose from, so that they can improve their experience with our application. One such theme i suggest we should implement is a red + purple theme.

This is my suggested theme:

![image](https://user-images.githubusercontent.com/47064215/203482535-914080b0-9865-4bb2-808e-0c5052e8533a.png)

### Impact

Every type of user can benefit from this feature. Having more themes to choose from offers a sense of customization to the user. This power of customization improves the overall user experience.

**Comment by annieappflowy** [comment]
Are you working on the implementation? If not, we can add a help-wanted label to get a contributor to work on this.

**Comment by MayurSMahajan** [comment]
I am working on them yes
