### ISSUE TITLE
[FR] wee need arabic support....please

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#148]
wee need arabic support....please

_Originally posted by @ahmedsamyalafifi123 in https://github.com/AppFlowy-IO/appflowy/discussions/4#discussioncomment-1800954_

**Comment by MikeWallaceDev** [comment]
@ahmedsamyalafifi123 please use this issue #148 to discuss Arabic language. Can you please delete your comment in the other thread. Thank you.

Yes, I'm aware that Arabic is RTL. We can start with the text, and go from there.

Also, I believe I saw some French in your text, maybe that would be an option?

**Comment by annieappflowy** [comment]
There are other languages than Arabic adopting [R2L](https://en.wikipedia.org/wiki/Right-to-left_script) language systems

**Comment by zoli** [comment]
> There are other languages than Arabic adopting [R2L](https://en.wikipedia.org/wiki/Right-to-left_script) language systems

Yes, I know so is it not the case that resolving #39 will resolve this to? So this is duplicate of #39.

**Comment by xximj** [comment]
Is there any plans to this?

**Comment by annieappflowy** [comment]
Hi @xximj , yes, it will come as a community plugin. I'll update you when I find folks who want to build it for the community.

**Comment by annieappflowy** [comment]
@xximj , RTL is supported

**Comment by xximj** [comment]
Great news! 👏🏼
Much appreciated, thanks a lot.
