### ISSUE TITLE
[Bug] AZERTY keyboard: the key combination Shift+":" to type the symbol "/" doesn't open the menu

### ISSUE THREAD

**Issue by guill-lege** [AppFlowy-IO/AppFlowy#1480]
### Bug Description

When using a Belgian AZERTY keyboard, typing on Shift+":" (combination to type "/") doesn't open the menu

### How to Reproduce

In a new page, while using a French Belgian keyboard, use the combination Shift+":" to type the symbol "/"

### Expected Behavior

The expected behavior is for the combination Shift+":"to open the menu when using a Belgian AZERTY keyboard

### Operating System

Windows 10

### AppFlowy Version(s)

0.0.6.2

### Screenshots

![image](https://user-images.githubusercontent.com/72153383/203761202-bab2d661-fa6e-499d-81bf-4fbf88e29ca8.png)

**Comment by annieappflowy** [comment]
Related to https://github.com/AppFlowy-IO/AppFlowy/issues/1413

**Comment by LucasXu0** [comment]
Hi, @guill-lege. This bug has been fixed in 0.0.7.
