### ISSUE TITLE
[Bug] Can't build the app with latest Rust version 1.65

### ISSUE THREAD

**Issue by SumanKisku** [AppFlowy-IO/AppFlowy#1484]
### Bug Description

So, while trying to building the app with the latest version of Rustup I couldn't able to build the app. I needed to downgrade the version of Rustup to 1.64 o able to build the app successfully. `rustup default 1.64` command worked to downgrade the version rustup. And the build was successful.

### How to Reproduce

`rustup default 1.65` use this command to update to the rustup 1.65(currently the latest version) and this will give some this kind of error "`-Csplit-debuginfo=unpacked` is unstable on this platform".

### Expected Behavior

App should be build with one go.

### Operating System

Windows 10, 22H2

### AppFlowy Version(s)

v0.0.6.2

**Comment by appflowy** [comment]
Thank you for reporting this. @SumanKisku. This issue was already fixed in main branch.
