### ISSUE TITLE
[Bug]  字体粗细不一

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#1488]
### Bug Description

字体粗细不一

### How to Reproduce

设置语言为中文，外观内的字体

### Expected Behavior

该字体应该是保持一致的粗细

### Operating System

Windows 10

### AppFlowy Version(s)

AppFlowy v0.0.6.2

### Screenshots

截图
![image](https://user-images.githubusercontent.com/45089051/204104710-cc1cb5e4-3325-4e08-9e27-d2088646ea9f.png)

### Additional Context

期待版本的迭代得以修复。对于一些小bug和改进的意见，提出几点
1、 增加全局字体大小的调整，默认的确实太小了。
2、 中文输入存在问题，暂时不能使用中文输入。
3、 快速输入时，输入的数据会跑到光标的右边。
4、 表格不能单行上下移动

AppFlowy是一个很好的产品，我很喜欢，期待提出的建议能够采纳以及bug被早日修复，谢谢！

**Comment by LucasXu0** [comment]
Blocked by https://github.com/flutter/flutter/issues/103811.

**Comment by LucasXu0** [comment]
> ![image](https://user-images.githubusercontent.com/45089051/205072943-a09529b8-ddaf-4814-b87e-433304f2e359.png) Chinese input method overflows to the right of the cursor

Thanks for reporting. It's a known issue.  https://github.com/AppFlowy-IO/AppFlowy/issues/1517

**Comment by August936** [comment]
还是没有修复

**Comment by annieappflowy** [comment]
Please go to Settings -> Workspace -> Workspace font -> System
<img width="289" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/bc6dc12d-15a2-495a-a002-9b832798fe9e">

**Comment by JustLikeCheese** [comment]
并没有得到解决，修改工作区字体为系统后，还是原来的样子。我通过 [#3350](https://github.com/AppFlowy-IO/AppFlowy/issues/3350) 提供的方法修改了工作区字体，但是 AppFlowy 的界面字体还是粗细不一。我的操作系统是 Windows 10，AppFlowy 版本为最新的 v0.7.4。
![github-appflowy-image3.png](https://pic2.imge.cc/2024/11/23/6741458354bc2.png)

**Comment by ItsFated** [comment]
AppFlowy用了Google Fonts，可以先用 Noto Sans SC （思源黑体），就不会有中文字体粗细不一，大小不一的问题了。这估计是Flutter的问题。参考：https://github.com/flutter/flutter/issues/103811#issuecomment-3013804785
