### ISSUE TITLE
[Bug] AppFlowy is crashed after creating the second new page

### ISSUE THREAD

**Issue by 0xkelvin** [AppFlowy-IO/AppFlowy#1505]
### Bug Description

AppFlowy is crashed after creating the second new page

### How to Reproduce

click on below button to create a new page : 
<img width="130" alt="image" src="https://user-images.githubusercontent.com/56182747/204553662-9e7bcd39-251d-4616-b20b-6ecb8e94ac37.png">

it is ok for the first page, but the crashing will happen if try to create another new page

### Expected Behavior

can create many many pages

### Operating System

MacOS M1

### AppFlowy Version(s)

latest

### Screenshots

![image](https://user-images.githubusercontent.com/56182747/204553488-d179f08c-c388-49a8-aa66-bebffe7f4990.png)

**Comment by LucasXu0** [comment]
Hi, @0xkelvin. Could you provide more detailed steps? I tested it on my M1 MacBook. Nothing goes wrong.

**Comment by 0xkelvin** [comment]
Hi @LucasXu0 

I was followed below document to setup and build on my M1: 
https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos

below is the video i just recorded :

https://user-images.githubusercontent.com/56182747/204717001-644d196b-f7a4-44b2-b852-7cbd99409f14.mov

**Comment by LucasXu0** [comment]
Can you provide the result of running the following command line?

```shell
flutter doctor
rustc --version
```

**Comment by 0xkelvin** [comment]
below is the version of rust and result of flutter doctor:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/56182747/204723573-9d296035-7665-49a5-9fcc-8871deba9b3c.png">

**Comment by LucasXu0** [comment]
Got it. We only verified the behavior of AppFlowy under rust 'stable-2022-04-07' and flutter '3.0.5'. So it's better to switch to the version mentioned above and please try it again.

**Comment by 0xkelvin** [comment]
i see, thanks for information

**Comment by annieappflowy** [comment]
Is this solved? @0xkelvin

**Comment by 0xkelvin** [comment]
> Is this solved? @0xkelvin

yes i does, let me close this issue. thanks a lot
