### ISSUE TITLE
[Bug] Grid note broken after upgrade from 0.0.7 to 0.0.8

### ISSUE THREAD

**Issue by Dialga** [AppFlowy-IO/AppFlowy#1514]
### Bug Description

![image](https://user-images.githubusercontent.com/5157928/204792873-db735aa2-6329-4d05-8d73-291b74ca8eae.png)

msg oterror incompatiblelength msg expected 83, but received 0.

Error message is also unselectable so I couldn't copy and paste it here.

### How to Reproduce

Upgrade from 0.0.7 to 0.0.8

### Expected Behavior

Grid note works as before

### Operating System

Arch Linux x64

### AppFlowy Version(s)

v0.0.8

### Screenshots

![image](https://user-images.githubusercontent.com/5157928/204792873-db735aa2-6329-4d05-8d73-291b74ca8eae.png)

**Comment by appflowy** [comment]
@Dialga Thank you for reporting this. Would you mind sharing your local data file with me for debugging? If yes, please DM me in Discord.

**Comment by Dialga** [comment]
Have sent it to you

**Comment by appflowy** [comment]
> Have sent it to you

Thank you!
