### ISSUE TITLE
[Bug] Microsoft Chinese input method inputs duplicately

### ISSUE THREAD

**Issue by Learces** [AppFlowy-IO/AppFlowy#1517]
### Bug Description

When I type Chinese, the letters repeat in the editor.

### How to Reproduce

use microsoft chinese input method inputs anthing word

### Expected Behavior

don‘t repeat

### Operating System

Windows 11

### AppFlowy Version(s)

AppFlowy-0.0.8-windows-x86_64.exe

### Screenshots

![image](https://user-images.githubusercontent.com/94371988/204979002-8c03ecf9-d058-4965-bdc5-db1444d6a457.png)

**Comment by LucasXu0** [comment]
Hi, @Learces. It's a known issue. I have reported this bug to Flutter. https://github.com/flutter/flutter/issues/113909#issuecomment-1311478223

**Comment by annieappflowy** [comment]
Fixed
Please give it a try with the latest [release ](https://github.com/AppFlowy-IO/AppFlowy/releases)

**Comment by XUTENGHAO** [comment]
Not solved, still existed
