### ISSUE TITLE
[Bug] Card shown status not updating on moving around

### ISSUE THREAD

**Issue by zoli** [AppFlowy-IO/AppFlowy#1524]
### Bug Description

What is shown as card status in kanban board doesn't get updated after moving the card to another status with cursor. If you change the page to another and come back it gets updated.

### How to Reproduce

1. Create new board
2. Click on Card 2 and view its status you will see that its To Do.
3. Move Card 2 with cursor to No Status section
4. Click on Card 2 and view its status you will see that its still showing To Do.

### Expected Behavior

The card shown status should get updated to empty status or whatever status that the section which the card has been moved to.

### Operating System

Arch Linux

### AppFlowy Version(s)

0.0.8

### Screenshots

https://user-images.githubusercontent.com/3286303/205444210-e5b03e6c-fc3a-45f5-b9b3-db4114646c25.mp4

**Comment by appflowy** [comment]
@zoli Thank you for your video! This bug was fixed and the [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/1536) will be merged into main branch later.
