### ISSUE TITLE
[FR] Implementation for switching from a Multi-select property type to a Text property type

### ISSUE THREAD

**Issue by 0xkelvin** [AppFlowy-IO/AppFlowy#1532]
### Description

The implementation for switching from a Multi-select property type to a Text property type is needed before writing the unit test which mentioned in #1183

### Impact

to be cater for #1183

### Additional Context

please just assign to me

**Comment by annieappflowy** [comment]
Thanks, @0xkelvin . Assigned

**Comment by 0xkelvin** [comment]
hello @annieappflowy, @appflowy 

Just for confirmation.
when switching from Multi-select type to Text property type, the values in the cell should be clear/remove/empty ?

do i understand correctly ?

**Comment by 0xkelvin** [comment]
Hello @annieappflowy @appflowy 
Does this requirement also apply the same for "Single-select to Text property" type ?

**Comment by appflowy** [comment]
Yes, it does. The test should be updated.

**Comment by 0xkelvin** [comment]
let me create another issue for that, to avoid forget it later on

**Comment by 0xkelvin** [comment]
hello @annieappflowy 
after discussion with @appflowy , we realised that it was the miss-understanding. 
this feature implemented in the method "decode_cell_data" 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/56182747/208613701-c2ef13b9-a17c-4b75-9fff-b8d33e2cf6bc.png">

And the behaviours are correct, so just need to write the unit test (#1585 )

so i will close this thread.
