### ISSUE TITLE
[FR] Settings Page

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#154]
**1~3 main use cases of the proposed feature**
- The user can adjust settings such as themes and color tints for the app.
- In the event the app may be buggy the user can clear the cache and restart it.
- Having a settings page now allows us to work on it separately and bind user actions.

**what types of users can benefit from using your proposed feature**
The user can choose the color of their choice and fix minor issues with the app on their own

**Comment by annieappflowy** [comment]
Done
