### ISSUE TITLE
[Bug] Switching grid cell type removes focus border

### ISSUE THREAD

**Issue by Eakam1007** [AppFlowy-IO/AppFlowy#1543]
### Bug Description

Grid Cells except for `Date` and `Checkbox` types show a focus border when they are being edited. 
However, if the cell type is changed to something else and changed back, the focus border no longer shows for existing cells until the app is restarted or the page is switched. It still shows for any new cells that are added later.

### How to Reproduce

1. Edit a grid cell with any type other than `Date` and `Checkbox`
2. Observe that a blue focus border appears
3. Change cell type to something else, and change it back
4. Edit the cell again
5. Observe that there is no focus border
6. Add a new row to the grid and edit the new cell
7. Observe that there is a focus border on the new cell
8. Switch to a different page and switch back (or restart the app)
9. Edit the cells again
10. Observe that there is a focus border

### Expected Behavior

The focus border should show after changing the type (provided the type shows a focus border normally)

### Operating System

Windows 11

### AppFlowy Version(s)

v0.0.8

### Screenshots

https://user-images.githubusercontent.com/67077705/205950385-8427f393-8750-4b20-9b80-299d651903fe.mp4

**Comment by annieappflowy** [comment]
Hi @Eakam1007 , thanks a lot for reporting this issue with a lot of details.
Are you working on fixing this issue? I suppose there is a PR related to it. If yes, please don't forget to link your PR to this issue. Thanks, again, for the contributions!

**Comment by Eakam1007** [comment]
Hey sorry, I won't be able to work on it. I found this while working on #1469

**Comment by annieappflowy** [comment]
Oh sorry, I got it wrong. Thanks for reporting this bug! I mark it as a help-wanted issue so that someone else can claim it.
