### ISSUE TITLE
[FR] IOS and Android support

### ISSUE THREAD

**Issue by antime** [AppFlowy-IO/AppFlowy#1547]
### Description

Android and IOS app support

### Impact

all users

**Comment by Cosmopal** [comment]
Is this open for public contribution? I'd like to contribute to this feature.

**Comment by annieappflowy** [comment]
I believe there are many areas you can contribute to the mobile versions.
@LucasXu0 will create a few first-time friendly issues on mobile

**Comment by gianpaj** [comment]
duplicate of  https://github.com/AppFlowy-IO/appflowy-editor/issues/68 ?

**Comment by annieappflowy** [comment]
It has overlap but not exactly the same. appflowy_editor is a subset of AppFlowy. We'll support mobile for appflowy_editor first and then AppFlowy.

**Comment by annieappflowy** [comment]
AppFlowy Mobile is available to download from https://appflowy.io/download#ios-and-android
