### ISSUE TITLE
[Bug] Build error on macos

### ISSUE THREAD

**Issue by XiangQingW** [AppFlowy-IO/AppFlowy#1558]
### Bug Description

packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:38:17: Error: Field '_defaultInstance' should be initialized because its type 'ViewPB' doesn't allow null.
 - 'ViewPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static ViewPB _defaultInstance;
                ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:92:25: Error: Field '_defaultInstance' should be initialized because its type 'RepeatedViewPB' doesn't allow null.
 - 'RepeatedViewPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static RepeatedViewPB _defaultInstance;
                        ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:113:27: Error: Field '_defaultInstance' should be initialized because its type 'RepeatedViewIdPB' doesn't allow null.
 - 'RepeatedViewIdPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static RepeatedViewIdPB _defaultInstance;
                          ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:150:30: Error: Field '_defaultInstance' should be initialized because its type 'CreateViewPayloadPB' doesn't allow null.
 - 'CreateViewPayloadPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static CreateViewPayloadPB _defaultInstance;
                             ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:207:19: Error: Field '_defaultInstance' should be initialized because its type 'ViewIdPB' doesn't allow null.
 - 'ViewIdPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static ViewIdPB _defaultInstance;
                  ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:242:24: Error: Field '_defaultInstance' should be initialized because its type 'DeletedViewPB' doesn't allow null.
 - 'DeletedViewPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static DeletedViewPB _defaultInstance;
                       ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:307:30: Error: Field '_defaultInstance' should be initialized because its type 'UpdateViewPayloadPB' doesn't allow null.
 - 'UpdateViewPayloadPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static UpdateViewPayloadPB _defaultInstance;
                             ^^^^^^^^^^^^^^^^
packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart:358:34: Error: Field '_defaultInstance' should be initialized because its type 'MoveFolderItemPayloadPB' doesn't allow null.
 - 'MoveFolderItemPayloadPB' is from 'package:flowy_sdk/protobuf/flowy-folder/view.pb.dart' ('packages/flowy_sdk/lib/protobuf/flowy-folder/view.pb.dart').
  static MoveFolderItemPayloadPB _defaultInstance;

### How to Reproduce

Run `cargo make --profile production-mac-x86_64 appflowy` on the terminal.

### Expected Behavior

Build success

### Operating System

macos

### AppFlowy Version(s)

main branch

### Screenshots

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/7948384/206698355-0f02bb7e-5712-4989-a621-03ad2edd3994.png">

**Comment by LucasXu0** [comment]
Hi, @XiangQingW. What version of Flutter do you use?

**Comment by XiangQingW** [comment]
@LucasXu0 Flutter is the latest version. After I upgrade dart-gen-protoc, the issue was gone. Thank you.
