### ISSUE TITLE
[Bug] Scaling error 4k monitor Linux

### ISSUE THREAD

**Issue by Borgesbr** [AppFlowy-IO/AppFlowy#1559]
### Bug Description

scaling error when switching to more than 100% on 4K monitor

### How to Reproduce

1. open settings

2. Browse display settings

3. change scale to more than 100%

### Expected Behavior

I expected the user interface to adapt to the larger scale, as well as other software

### Operating System

Pop OS, Linux Mint Xfce, Manjaro Genome

### AppFlowy Version(s)

0.0.8.1 and previous

### Screenshots

![Screenshot from 2022-12-09 13-38-28](https://user-images.githubusercontent.com/120200595/206749630-272aac0a-6ab9-4c27-afc4-a1f5cee05543.png)

![Screenshot from 2022-12-09 13-38-48](https://user-images.githubusercontent.com/120200595/206749672-ce14d3ed-eade-4b13-aa2e-d7a8b2e7207c.png)

### Additional Context

I'm happy for the software, congratulations on everyone's work.

**Comment by yushuhuang** [comment]
Tried on Ubuntu, the problem is X window related, Wayland scales fine.

**Comment by fangykai** [comment]
If I recall this was also reproducible on Zorin OS 16.1.

**Comment by C-Peiter** [comment]
Same thing happening on Kubuntu 22.04 with X11.

**Comment by annieappflowy** [comment]
Hi guys,

This should be fixed in https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.0
Please give it a try!

Thanks
