### ISSUE TITLE
[Bug] Flatpak not functioning

### ISSUE THREAD

**Issue by memoryfile** [AppFlowy-IO/AppFlowy#1561]
### Bug Description

Appflowy's Flatpak won't launch because of a glibc error.

### How to Reproduce

Install Appflowy via flatpak

Enter `flatpak run io.appflowy.AppFlowy` in a terminal

Receive `app_flowy: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by app_flowy)`

### Expected Behavior

Appflowy launches.

### Operating System

Fedora Silverblue 37

### AppFlowy Version(s)

0.0.7 (the flatpak hasn't been updated)

**Comment by memoryfile** [comment]
Problem seems to have resolved itself on my end (would love to get an updated flatpak version though! by the way, liking Appflowy a lot; thanks to the Appflowy team for all that you do!)

**Comment by LucasXu0** [comment]
Hi, @memoryfile. Thanks for updating. A contributor helped us to update the built-in `org.freedesktop.Platform`. https://github.com/flathub/io.appflowy.AppFlowy/issues/8
