### ISSUE TITLE
[FR] Clear value for date fields in grid/kanban

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1574]
### Description

Most fields in the database allow you to clear the value, such as clearing out the text in a text field, or by deselecting all of the options. In date fields, however, the user is only permitted to change the date after setting it, or delete the entire row and recreate it.

### Impact

Users wishing to clear the date field in their grid/kanban will be able to do so.

**Comment by annieappflowy** [comment]
TODO: Add a 'Clear' function for Date to allow users to clear the value entered into a Date cell

**Comment by richardshiue** [comment]
Hey @hdjdoxDev, thanks for offering to help on this. I've assigned the issue to you, hope to see your PR soon! If you have questions about the implementation, feel free to reach out to nathan on Discord.

**Comment by hdjdoxDev** [comment]
Hello @richardshiue Given that this would be my first contribution I will need some guidance, are you sure I can ask Nathan?

**Comment by hdjdoxDev** [comment]
I've started getting my hands dirty with the code. Unfortunately I couldn't completely solve the issue because I'm not so familiar with the architecture and bloc in particular. 
 - [x] added method clearValue to DateCellBloc (?)
 - [x] added DateCellAccessory following PrimaryCellAccessory (need tooltips)
 - [x] overridden accessoryBuilder of GridDateCell to return DateCellAccessory
 - [x] some code style changes (not sure if they are welcome)
 - [ ] retrieve bloc instance in GridDateCell
 - [ ] solve a bug I found on show/hide behaviour of GridCellAccessory

**Comment by richardshiue** [comment]
Hey there @hdjdoxDev, glad to see progress. Do you think the accessory or an item in the menu would be better? I personally think that accessory would be too easy mis-click.

![image](https://user-images.githubusercontent.com/71320345/212242219-c598eeb4-e3b1-4668-a67b-555ccd7f1549.png)

**Comment by annieappflowy** [comment]
Hi @hdjdoxDev , you can seek help from @appflowy and @richardshiue on Discord. Happy coding and good luck!

**Comment by hdjdoxDev** [comment]
Hi @richardshiue, I changed as you suggested but I still have some trouble following the bloc logic. 
Now the button actually deselects the date in the Cal bloc but it does'n clear the value once the editor is deselected in the Cell bloc. My guess is that there is some null-safe logic that prevents changes but I still couldn't track it.

**Comment by richardshiue** [comment]
Hello @hdjdoxDev, from what I can see in your code, you are following the right bloc, but the event that you're firing is what is used by the backend to send information to the Flutter side and since the date isn't cleared in the backend, the date gets restored to the UI. It'd be better if you added a new `DateCalEvent` similar to  `setTime` and handle that instead. As for clearing the date value in the backend, I'm not sure whether it's better right now to simply set it as zero (January 1, 1970) and use the existing selectDay/setTime functions or make it accept null values and access it via a specialized clearDate. @appflowy

**Comment by richardshiue** [comment]
Hey there @hdjdoxDev, have you been able to make some progress on this?

**Comment by hdjdoxDev** [comment]
Hi @richardshiue, I'm sorry I left you hanging, I was hoping to be assigned a mentor to help me catch up with some technical gaps.

I saw your edits to the last comment, it's is not so clear to me how to proceed after adding the `const factory DateCalEvent.resetTime() = _ResetTime;` line. Right now I'm looking into the freezed package and the app_flowy docs. 

I don't know how much of a rush you have to get this issue solved, but with me it will take some time given my inexperience and small availability at the moment.  Please consider reassigning this issue given the situation, either way I would be happy to keep exploring it till I get to the solution.

**Comment by richardshiue** [comment]
Hey there @hdjdoxDev, I encourage you to keep trying. That's a good start, the next step is to handle it. Please feel free to reach me on Discord at Stormcheetah#4271

**Comment by hdjdoxDev** [comment]
Hello @richardshiue, I am sorry to say that I will be unable to keep following this issue at the moment. I hope to come back and really help in the future. Thank you for your time and the encouragement!

**Comment by richardshiue** [comment]
Hey there @hdjdoxDev, thanks for the update, and for trying to tackle this feature! Of course, I look forward to you coming back some time, I'm sure there will be other issues that you can work on.

**Comment by dejvizelo** [comment]
I would like to work on this

**Comment by dejvizelo** [comment]
> As for clearing the date value in the backend, you can simply set it to none and use the existing selectDay/setTime functions.

@richardshiue I'm new to the project and would appreciate a bit of help on this. Can you elaborate a bit more on what you said above? Right now I can't seem to figure out how to set the date value to none, and I don't understand why or how we need to use the existing selectDay/setTiem functions.

**Comment by richardshiue** [comment]
Hey there @dejvizelo, thanks for taking a jab at this. You can follow the following steps to do the backend:

1. Create an event in `rust-lib/flowy-database2/src/event_map.rs` named `ClearDateCell` and specify the handler `clear_date_cell_handler`
2. Implement the `clear_date_cell_handler` in `rust-lib/flowy-database2/src/event_handlers.rs`
3. This should call a new `clear_date_cell` function in `rust-lib/flowy-database2/src/services/database/database_editor.rs`. You can refer to `update_cell_with_changeset`.
4. This should then call a new function `clear_date_cell` that is a method of `DateTypeOption`, in it the `Option<i64>` timestamp will be turned into `None`. You can refer to the `ApplyChangeset` trait implementation for `DateTypeOption`

On the frontend, you're right, I don't think we need to use the selectDay or setTime functions anymore. In `date_cal_bloc`, you'd have to dispatch that this new `ClearDateCell` event and handle it (preferably in a helper function). Good luck and let me know if you need more help!

**Comment by annieappflowy** [comment]
Hi @dejvizelo , would you like to continue to work on this issue?

**Comment by dejvizelo** [comment]
Hi @annieappflowy, I'm still working on this but work has stalled a bit at the moment because I am not very familiar with Rust. I'm still keeping contact with @richardshiue to try to find a good implementation for it. Sorry that it's taking so long

**Comment by annieappflowy** [comment]
Thanks @dejvizelo for the update. Keep going!

**Comment by dejvizelo** [comment]
@annieappflowy PR is now ready
