### ISSUE TITLE
button description 

### ISSUE THREAD

**Issue by yaggit** [AppFlowy-IO/AppFlowy#1575]
### Bug Description

Greetings,
I don't know whether it is happening with all users or just me but after turning on dark mode while hovering over the button, the description text is not visible properly.
I tried both modes i.e. system preference dark mode and dark mode from AppFlowy application.

![image](https://user-images.githubusercontent.com/72143254/207878029-2413e476-2be6-43e2-8c6c-ddc5a39b6a40.png)
![image](https://user-images.githubusercontent.com/72143254/207878217-c9680de5-ef54-4b0f-97f0-cbfc3875db42.png)
![image](https://user-images.githubusercontent.com/72143254/207878507-6717f18f-5fb4-4974-8882-a80a3e560946.png)

### How to Reproduce

Since I am unfamiliar with the code I can not make a decision.
Although if there is a property for hover-popup, it should be changed, like background color or fade or opaqueness or any other thing.

### Expected Behavior

Clear visible text in dark mode over hovering.

### Operating System

Windows

### AppFlowy Version(s)

0.0.8.1

### Screenshots

![image](https://user-images.githubusercontent.com/72143254/207878029-2413e476-2be6-43e2-8c6c-ddc5a39b6a40.png)
![image](https://user-images.githubusercontent.com/72143254/207878217-c9680de5-ef54-4b0f-97f0-cbfc3875db42.png)
![image](https://user-images.githubusercontent.com/72143254/207878507-6717f18f-5fb4-4974-8882-a80a3e560946.png)

**Comment by vuzzer** [comment]
Hi, this problem is solved.

**Comment by annieappflowy** [comment]
Thanks for updating the progress!
Yes, please meet AppFlowy's official dark mode in [v0.1.3](https://github.com/AppFlowy-IO/AppFlowy/releases)

**Comment by yaggit** [comment]
Thanks for solving the problem.
