### ISSUE TITLE
[Bug] Error at login

### ISSUE THREAD

**Issue by KaTOxDev** [AppFlowy-IO/AppFlowy#1576]
### Bug Description

![image](https://user-images.githubusercontent.com/98159417/207976765-0e8a7a1f-5b72-433a-8d22-30796670495a.png)

### How to Reproduce

after installing the app , it work fine but when i restart the app , nothing work

### Expected Behavior

![image](https://user-images.githubusercontent.com/98159417/207977324-a9cfe2bf-5227-464b-b4ee-84dd66d8668e.png)

### Operating System

windows 11

### AppFlowy Version(s)

0.0.8.1

**Comment by appflowy** [comment]
@KaTOxDev Thank you for reporting this. Did you upgrade from 0.0.7 to 0.0.8.1?

**Comment by KaTOxDev** [comment]
No i just install 0.0.8.1 for the first time

**Comment by appflowy** [comment]
> No i just install 0.0.8.1 for the first time

Got it. I can reproduce it in my Windows. Will keep trying to find out why.

**Comment by KaTOxDev** [comment]
ok thanks , i hope you fix it , i prefer to use appflow its free , offline and fast

**Comment by appflowy** [comment]
> ok thanks , i hope you fix it , i prefer to use appflow its free , offline and fast

Would you mind building AppFlowy from the main branch? Or you can download the latest version that supports creating a new folder to store your data.

**Comment by KaTOxDev** [comment]
> > ok thanks , i hope you fix it , i prefer to use appflow its free , offline and fast
> 
> Would you mind building AppFlowy from the main branch? Or you can download the latest version that supports creating a new folder to store your data.

I install the latest version i got the same problem

**Comment by annieappflowy** [comment]
@KaTOxDev glad to hear it is partially solved.
Maybe you can try out our new feature 'Files‘ in Settings:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/12026239/209418558-73ba7e3d-d6ba-4e8a-8a35-659b77e4d40b.png">

You can use it to open another folder which can be your previous "flowy" folder. Please let me know if it works or not!

Thanks!

**Comment by KaTOxDev** [comment]
when i make some change and reopen the appflowy i get the same error .
and i try to change the folder to my previous "flowy" folder i got the same error .
