### ISSUE TITLE
[Bug] No app icon on Linux

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/appflowy#158]
**Describe the bug**
The application does not correctly show an icon in the app bar.

**To Reproduce**
1. Launch the application
2. The application bar shows the default application icon

**Expected behavior**
The AppFlowy icon should appear in the app bar

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/146266357-3612f520-27aa-4df1-9547-b7eafb35cfdf.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version 0.0.2

**Additional context**
I believe the correct way to fix this is to create a .desktop file.

**Comment by MikeWallaceDev** [comment]
I have created a appflowy.desktop file which is located in /frontend/app_flowy/linux. This file is now included within the release archive file.

However, although the app does appear in the menu, and the icon does appear correctly in the menu, the icon does not appear in the taskbar, app switcher, or app title bar.  I can not find a solution for this.

If would be really good if someone could do some research on this because my google-fu is weak on this one.

**Comment by moltinginstar** [comment]
This should do the trick (tested on Ubuntu 21.10):

1. Copy `flowy_logo.svg` to `/usr/share/icons` (or `/usr/share/icons/hicolor/scalable/apps` as suggested in the [icon theme spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#:~:text=So%2C%20you%27re%20an,specific%20desktop%20environment.))
2. Move `appflowy.desktop` to `/usr/share/applications`
3. In `appflowy.desktop`, set `Icons=flowy_logo.svg` (full path not needed) and `Exec=<*absolute* path to executable>` (e.g., `Exec=/opt/appflowy/app_flowy`)
4. Rename `appflowy.desktop` to `app_flowy.desktop` to match the name of the executable

**Comment by MikeWallaceDev** [comment]
Hi @moltinginstar thanks for that!  Unfortunately, I have done all your steps exactly, and they do not fix the problem of not having the icon appear in the taskbar, or on the application window.

**In the taskbar :** 
![image](https://user-images.githubusercontent.com/5375835/148277644-73ab6b91-290c-4d6a-8596-3d9ba57a6bca.png)

**On the application window:** 
![image](https://user-images.githubusercontent.com/5375835/148277810-4a2135ba-7d6e-452f-b589-0cfbab826bf0.png)

**Comment by moltinginstar** [comment]
I see. I’m not very familiar with Xfce but after some Googling I found [this](https://askubuntu.com/a/1268919).

Could you try renaming `flowy_logo.svg` to `app_flowy.svg` and let me know if it works? Thanks.

**Comment by MikeWallaceDev** [comment]
I renamed the .svg, it did not work
I then changed the icon value in the .desktop file (you didn't tell me to do that), it did not work
I then removed the .svg extension in the .desktop file, it did not work.

Thanks for looking at this!

**Comment by moltinginstar** [comment]
Strange. I wonder if that custom icon theme could be to blame. Really sorry to bug you again, but can you also try copying the `svg` and the `.desktop` file to `~/.local/share/icons` and `~/.local/share/applications` (respectively) and rebooting the computer? If it still doesn’t work, I’ll install Kubuntu on my laptop first thing tomorrow and try to get to the bottom of this. I’ve been following the project for a while now and I’d love to contribute in any way I can :)

**Comment by MikeWallaceDev** [comment]
You're not bugging me. I'm the one who created the .desktop file and procedure! I added this issue because I couldn't get those two things to work.

Unfortunately, I can't try that now as I have to go to work.

Just for clarification : I'm on xfce, not kde.  So you should look at xubuntu if you want the same environment.

Thanks again!  :)

**Comment by moltinginstar** [comment]
Just installed Xubuntu 20.04.3 on a live USB but couldn't reproduce the issue no matter what I tried. If the SVG has a different name from the executable, it doesn't show up in the taskbar and app window, as in your case. However, renaming it instantly fixes the problem for me.

Different name (`flowy_icon.svg`):
![Different names](https://user-images.githubusercontent.com/62135712/148506728-39c67c1d-7bcc-46c3-b2e8-7dedb3c0ce29.png)

Same name (`app_flowy.svg`):
![Same name](https://user-images.githubusercontent.com/62135712/148506722-b22e7b35-1c8d-4243-a82b-a99b46c5ed07.png)

At this point, I have no idea what could be causing it. Has anyone else run into the same problem?

**Comment by MikeWallaceDev** [comment]
Maybe my system is corrupted. I tried many things...

**Comment by MikeWallaceDev** [comment]
@moltinginstar I GOT IT!!!
I cleaned up my system as much as possible and redid everything, and it worked!
This ->  (or /usr/share/icons/hicolor/scalable/apps as suggested in the icon theme spec) did not work. It only works (for me) in /usr/share/icons

I kind of wish that I didn't have to tell people to put stuff in their /usr dirs, but hey, it works.

I'm going to update the installation guide and mark this as resolved. Thanks!

**Comment by moltinginstar** [comment]
That’s great to hear!

By the way, the same directories in `~/.local` should also work. Be sure to give that a try if you don’t like the idea of users messing with system directories. Ideally, all this “dirty work” should be done by the installer, but since we don’t have one for Linux yet, copying the files manually is the next best thing...

**Comment by MikeWallaceDev** [comment]
Yep, I had already tried them when you wrote that :D  And indeed, they worked.  Like I said, I had all kinds of crap installed (app_flowy.desktop files in different directories, with different names, the icon in different places, with different names...)

The system was probably picking up an old .desktop file with incorrect information.

It all works now, and is checked-in.

However (again), I can't create a new release file (the tar), we're way too far from 0.0.2 for me to just name it 0.0.2, and I have to wait for Nathan to create an official 0.0.3.  Once that is done I will update everything.
