### ISSUE TITLE
[FR] Nested Folders

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#1581]
### Description

It would be nice if appflowy had a nested folder system for notes. 
Can be useful to group specific notes together.
For example:
Parent Folder:
    - File 1
    - File 2
    - File 3
    - File 4
    Child Folder:
        - File 1
        - File 2
        - File 3
        - File 4

### Impact

This can help users keep their notes organised in folders and separated from unrelated notes.

**Comment by reggermont** [comment]
Surprised nobody reacted on this one. This is the only thing that is stopping me from using AppFlowy

Well, this and https://github.com/AppFlowy-IO/AppFlowy/issues/1372

**Comment by ameerPillsbee** [comment]
why is this still not addressed. this is the must have feature !!

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/3083

**Comment by annieappflowy** [comment]
Now you can add pages inside pages and rearrange by drag and drop. Please give it a try using the [latest release](https://github.com/AppFlowy-IO/AppFlowy/releases) and let us know if you have any questions or feedback.
Thanks, @reggermont @ameerPillsbee
