### ISSUE TITLE
[FR] Linux / cross-os build?

### ISSUE THREAD

**Issue by chris-aeviator** [AppFlowy-IO/appflowy#16]
Since you are using Flutter will it make sense for you to release a cross-os build? Can I build the project myself on linux?

**Comment by rayrrr** [comment]
+1. GitHub Actions may be the solution. From https://github.com/features/actions :

> Linux, macOS, Windows, ARM, and containers
> Hosted runners for every major OS make it easy to build and test all your projects. Run directly on a VM or inside a container. Use your own VMs, in the cloud or on-prem, with self-hosted runners.

**Comment by appflowy** [comment]
@chris-aeviator  @rayrrr  Thanks, I will set up the Github actions as soon as I finish the windows release.

**Comment by pdckxd** [comment]
Linux x86_64 #34

**Comment by berard** [comment]
Could we also have a universal Mac build (for ARM and x86)?
