### ISSUE TITLE
Can't build docker image?

### ISSUE THREAD

**Issue by julianbrennum** [AppFlowy-IO/AppFlowy#1600]
Hi! 

I need some help to build the latest docker image.

When I follow the guide to build the latest docker image I get this error message: 

```
 => CANCELED [builder  2/17] RUN pacman -Syy                                                  0.4s
 => ERROR [stage-1 2/9] RUN pacman -Syy &&     pacman -Syu --needed --noconfirm xdg-user-dir  0.3s
------
 > [stage-1 2/9] RUN pacman -Syy &&     pacman -Syu --needed --noconfirm xdg-user-dirs &&     pacman -Scc --noconfirm:
#0 0.233 exec /bin/sh: exec format error
------
failed to solve: executor failed running [/bin/sh -c pacman -Syy &&     pacman -Syu --needed --noconfirm xdg-user-dirs &&     pacman -Scc --noconfirm]: exit code: 1
```

**This happens when I try to run the following code:**
`docker compose build --build-arg uid=$(id -u) --build-arg gid=$(id -g)`

**My system is running:**
Docker version: 20.10.22
Docker compose version: 2.14.1
Ubuntu 22.04.1 LTS

**Comment by julianbrennum** [comment]
I also tried to deploy it with **Portainer (Compose file)** but I got this error message: 

`failed to deploy a stack: time="2023-01-03T16:11:49Z" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string." app Pulling app Error failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2376524704/Dockerfile: no such file or directory`

Then I tried to install it via **Portainer (Repository)** but then I got this: 

`failed to deploy a stack: time="2023-01-03T16:13:32Z" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string." app Pulling app Error failed to solve: executor failed running [/bin/sh -c pacman -Syy]: exit code: 1`

Has anyone encountered this before?

**Comment by annieappflowy** [comment]
Please try out https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy

**Comment by Tataukee** [comment]
> I also tried to deploy it with **Portainer (Compose file)** but I got this error message:
> 
> `failed to deploy a stack: time="2023-01-03T16:11:49Z" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string." app Pulling app Error failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2376524704/Dockerfile: no such file or directory`
> 
> Then I tried to install it via **Portainer (Repository)** but then I got this:
> 
> `failed to deploy a stack: time="2023-01-03T16:13:32Z" level=warning msg="The \"DISPLAY\" variable is not set. Defaulting to a blank string." app Pulling app Error failed to solve: executor failed running [/bin/sh -c pacman -Syy]: exit code: 1`
> 
> Has anyone encountered this before?
@julianbrennum Have you managed to deploy AppFlowy through portainer ? i have currently the same issue like you did .. just discovered the app..
