### ISSUE TITLE
App stopped working after rebooting on Windows 10[Bug] 

### ISSUE THREAD

**Issue by ferreira-fp** [AppFlowy-IO/AppFlowy#1604]
### Bug Description

App stopped working after rebooting the pc, was working fine yesterday
![image](https://user-images.githubusercontent.com/121294924/209332829-c6a95927-795b-408c-a00d-aac72d493d6e.png)

### How to Reproduce

Install the app on Windows 10, reboot the pc, try to open

### Expected Behavior

Display my notes

### Operating System

Windows 10

### AppFlowy Version(s)

0.0.9

### Screenshots

![image](https://user-images.githubusercontent.com/121294924/209332943-9f738bfa-2440-420f-8a7d-83b13b76cf7c.png)

**Comment by LucasXu0** [comment]
Hi, @ferreira-fp. Did you try to customize the folder path or just open the app directly?

**Comment by ferreira-fp** [comment]
Just open th app
