### ISSUE TITLE
[FR] Cell switching from text to check

### ISSUE THREAD

**Issue by 0xkelvin** [AppFlowy-IO/AppFlowy#1614]
### Bug Description

https://user-images.githubusercontent.com/56182747/209751240-4430d7e1-8aa1-4d25-a404-7a269d1a46b6.mov

### How to Reproduce

create the text type field, then fill Yes or No in the cell, then switch to Check-box type

### Expected Behavior

i guess : 
if the cell's content is Yes or yes, it will display checked when switch to check-box type
if the cell's content is No or no or another text, it will display un-checked when switch to check-box type

### Operating System

MacOS M1

### AppFlowy Version(s)

latest

**Comment by 0xkelvin** [comment]
@appflowy @annieappflowy

**Comment by 0xkelvin** [comment]
after trying Notion, below is expected behaviour : 

- if the cell's content is Yes or yes, it will display checked when switch to check-box type
- if the cell's content is No or no or another text, it will display un-checked when switch to check-box type

cc: @appflowy

**Comment by 0xkelvin** [comment]
i working on this one, please assign to me @appflowy @annieappflowy

**Comment by annieappflowy** [comment]
Good catch! Assigned
