### ISSUE TITLE
[Bug] Document may disappear when you click near a ducument's MORE options

### ISSUE THREAD

**Issue by MoveCloudROY** [AppFlowy-IO/AppFlowy#1617]
### Bug Description

When you click multiple times near the red arrow in the first picture, this document may disappear, and then leave a black shadow on the left side as the second picture (I did it many times so you can see many shadows in different locations).
If you want the document to reappear, you need to tap the other document.

### How to Reproduce

1. Create some documents to test
2. Click repeatedly on one of the document's MORE option positions until it disappears, you may need to click faster or click many times.

### Expected Behavior

Only the option to turn on/off more occurs, without making document items undisplayed and without creating strange shadows.

### Operating System

Manjaro Linux

### AppFlowy Version(s)

0.0.9

### Screenshots

![image](https://user-images.githubusercontent.com/32302164/209864567-3978d0ec-299c-4ab3-aaa1-100d60adc4f7.png)
![image](https://user-images.githubusercontent.com/32302164/209864885-dac00a96-4118-455b-99f3-ed35efb0913a.png)

### Additional Context

OS: Manjaro Linux x86_64 
Host: Dell G15 5511 
Kernel: 6.1.1-1-MANJARO 
Resolution: 1920x1080 
DE: Plasma 5.26.4 
WM: KWin 
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
Memory: 10359MiB / 15744MiB

**Comment by MoveCloudROY** [comment]
I find that actually clicking anywhere on a document item seems to trigger the problem

**Comment by richardshiue** [comment]
Can you try launching the application in a terminal and see if there are error messages when this happens? I can't seem to reproduce your behavior from my end.

**Comment by MoveCloudROY** [comment]
no error messages when this happens, but when you try to delete some ducuments, it will throw error
```
Dec 29 15:21:25.449 ERROR ThreadId(20) {"error":"3: \"\\\"Can't find view with id 4aEO955Ut7\\\"\""}
{"msg":"flowy_folder::services::view::controller","error":"3: \"\\\"Can't find view with id 4aEO955Ut7\\\"\""}
Serialize FlowyError: FlowyError { code: 3, msg: "\"\\\"Can't find view with id 4aEO955Ut7\\\"\"" } to event response

```

**Comment by polypixeldev** [comment]
I also am not able to reproduce this behavior on my end (on Ubuntu 22.04 w/ GNOME). I will try it with Manjaro on a VM to see if I reproduce there.

**Comment by polypixeldev** [comment]
I am unable to reproduce on my Manjaro VM

**Comment by MoveCloudROY** [comment]
I suspect that there is a problem with the way I build from source. I started by building directly from main, now I switch to release 0.0.9 commit https://github.com/AppFlowy-IO/AppFlowy/commit/9a387b275f7850a00fb29ff3a9e0cb1f1049bb9d, although the problem is not solved, but I get more error messages
```
╰─❯ ./frontend/app_flowy/product/0.0.9/linux/Release/AppFlowy/app_flowy 

** (app_flowy:49009): CRITICAL **: 20:41:00.821: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置
** (app_flowy:49009): CRITICAL **: 20:41:00.822: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置
** (app_flowy:49009): CRITICAL **: 20:41:00.823: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置
** (app_flowy:49009): CRITICAL **: 20:41:00.823: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置
** (app_flowy:49009): CRITICAL **: 20:41:00.824: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: 未找到请求的设置
flutter: Bad state: Too many elements
flutter: #0      _GrowableList.single (dart:core-patch/growable_array.dart:354)
flutter: #1      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:109)
flutter: #2      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:115)
flutter: #3      _ReorderableFlexContentState._scrollTo (package:reorderables/src/widgets/reorderable_flex.dart:381)
flutter: #4      _ReorderableFlexContentState._wrap.<anonymous closure>.<anonymous closure> (package:reorderables/src/widgets/reorderable_flex.dart:741)
flutter: #5      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart:752)
flutter: #6      _DragAvatar.updateDrag.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:915)
flutter: #7      ListMixin.firstWhere (dart:collection/list.dart:161)
flutter: #8      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:909)
flutter: #9      new _DragAvatar (package:flutter/src/widgets/drag_target.dart:835)
flutter: #10     _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:556)
flutter: #11     MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:299)
flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253)
flutter: #13     MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:299)
flutter: #14     MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:289)
flutter: #15     _VerticalPointerState.accepted (package:flutter/src/gestures/multidrag.dart:467)
flutter: #16     MultiDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/multidrag.dart:289)
flutter: #17     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:278)
flutter: #18     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:235)
flutter: #19     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53)
flutter: #20     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:82)
flutter: #21     _ImmediatePointerState.checkForResolutionAfterMove (package:flutter/src/gestures/multidrag.dart:347)
flutter: #22     MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:102)
flutter: #23     MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:262)
flutter: #24     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
flutter: #25     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
flutter: #26     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617)
flutter: #27     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
flutter: #28     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
flutter: #29     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460)
flutter: #30     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440)
flutter: #31     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337)
flutter: #32     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395)
flutter: #33     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357)
flutter: #34     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314)
flutter: #35     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295)
flutter: #36     _invoke1 (dart:ui/hooks.dart:167)
flutter: #37     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341)
flutter: #38     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)

(app_flowy:49009): GLib-GObject-WARNING **: 20:41:13.377: ../glib/gobject/gsignal.c:2772: instance '0x56507ce0f1b0' has no handler with id '120'

```

**Comment by MoveCloudROY** [comment]
This is how I built it and the .zshrc file 
[The link](https://gist.github.com/MoveCloudROY/9527b4ac3bf5d756a8c69ea6bf15c239)

**Comment by richardshiue** [comment]
Got it. Can you verify that your Flutter version is 3.0.5? This is the version that AppFlowy is built and tested against.

**Comment by MoveCloudROY** [comment]
> Got it. Can you verify that your Flutter version is 3.0.5? This is the version that AppFlowy is built and tested against.
Unfortunately, my Flutter version is 3.3.10. I will try to use 3.0.5 latter.

**Comment by MoveCloudROY** [comment]
Thank you, it works correctly now!
But I think we need to update the documentation. Maybe because of my fault, I didn't see the requirements related to Flutter version in the documentation

**Comment by richardshiue** [comment]
Hey there @MoveCloudROY! Recently, the AppFlowy's Flutter version was updated to 3.3.9, meaning that this is a relevant issue if it's still reproducible with this version. I've added a commit that addressed an issue similar to yours but I'm not exactly sure if it will solve yours. If you have time, could you pull the latest changes from main and see if it's still reproducible?

**Comment by annieappflowy** [comment]
@MoveCloudROY , could you confirm if this issue still exists?
