### ISSUE TITLE
[FR] Improvement dark mode nicer

### ISSUE THREAD

**Issue by 0xkelvin** [AppFlowy-IO/AppFlowy#1618]
### Description

<img width="991" alt="image" src="https://user-images.githubusercontent.com/56182747/209972593-a535dd35-a0aa-4945-9373-30ba83ca0cb2.png">
dark mode on macos look not so nice

### Impact

user experience on mac book

**Comment by polypixeldev** [comment]
Can you please elaborate? What parts of the app in dark mode do not look good? Do you have any suggestions as to how to improve the look?
