### ISSUE TITLE
[FR] Support Shift + Option + Left/Right Arrow

### ISSUE THREAD

**Issue by Kaijiro** [AppFlowy-IO/AppFlowy#1624]
### Bug Description

On MacOS, I usually select one or many words with the combination "Shift + Option + Left/Right Arrow". This is a basic text manipulation.
Nothing happens when I use this key combination on AppFlowy.

### How to Reproduce

Write many characters / words and try to select them using only your keyboard.

### Expected Behavior

The words should be highlighted by the selection

### Operating System

MacOs

### AppFlowy Version(s)

0.0.8 (1)

**Comment by LucasXu0** [comment]
Hi, @Kaijiro. Thanks for your suggestion. I implemented the shortcuts for shift+option+arrow left/right in this [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/1648) and will release it in the next version.

**Comment by emmggi** [comment]
Can we perhaps have it select one word instead all until the end/beginning when we do CTRL+SHIFT+ARROW LEFT/RIGHT?
Selection all the way to the end/beginning could be done using SHIFT+HOME/END.
