### ISSUE TITLE
[Bug] Resizing window when table-view is opened re-opens grid infinitely in the backend

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1628]
### Bug Description

Title basically says all. The terminal is flooded with this message:

```
{"msg":"[⛳ OPEN_GRID - START]","line":95,"file":"flowy-grid/src/manager.rs"}
{"msg":"[⛳ OPEN_GRID - END]","line":95,"file":"flowy-grid/src/manager.rs","elapsed_milliseconds":0}
```

- Does not happen for kanban
- Does not happen on v0.0.6.2 and earlier

### How to Reproduce

1. Open a database in table-view
2. Resize the window
3. Observe that there is a flood of messages resembling the lines below.

### Expected Behavior

The terminal shouldn't be flooded with these messages. And if it's causing performance problems, that shouldn't happen either.

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

0.0.7 and later

**Comment by appflowy** [comment]
Thanks for reporting this. I check the code again and I think it's ok because resizing the windows won't cause the grid close. So the instance will be reused when `open_grid` get called.

 ```dart
Future<Either<Unit, FlowyError>> closeGrid() {
    final request = ViewIdPB(value: gridId);
    return FolderEventCloseView(request).send();
  }
```

**Comment by richardshiue** [comment]
Ok thanks, was good to make sure. Closing as non-issue.
