### ISSUE TITLE
[FR] Docker Image support needed

### ISSUE THREAD

**Issue by rushic24** [AppFlowy-IO/appflowy#163]
Compiling differently for every Linux is painful. Lets add a docker image to run everywhere.

**Comment by annieappflowy** [comment]
Hi @rushic24 , this is WIP. I'll keep you posted when it's ready!

**Comment by rushic24** [comment]
Hi @annieappflowy, I just created this issue to link with PR 😅. 
https://github.com/AppFlowy-IO/appflowy/pull/164 The dockerfile is ready.

**Comment by spothound** [comment]
I think this could be closed with https://github.com/AppFlowy-IO/appflowy/pull/164

**Comment by MikeWallaceDev** [comment]
Thanks @spothound !
