### ISSUE TITLE
[FR] Updating test grid data to cover fully the switching from "text" to "checkbox" type

### ISSUE THREAD

**Issue by 0xkelvin** [AppFlowy-IO/AppFlowy#1635]
### Description

the current mock test data in make_test_grid() function is not enough to cover below cases, when user switching from text type to checkbox type

<img width="400" alt="image" src="https://user-images.githubusercontent.com/56182747/210211675-a01833c5-6cbf-412d-8142-01b7d011d232.png">

we need to fix another test cases as well when we expand mock test data. 

### Impact
#1632
another test cases will be failed
testing coverage

### Additional Context

please assign to me cc @appflowy @annieappflowy

**Comment by annieappflowy** [comment]
Assigned!

**Comment by 0xkelvin** [comment]
apart is : #1639
