### ISSUE TITLE
[FR] Support command + / -

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1638]
### Description

The large sized font option is excellent. I would like to suggest a function like "Ctrl" + "+" and "Ctrl" + scrolling then the UI would zoom in including all text, just like obsidian. 
https://github.com/AppFlowy-IO/AppFlowy/discussions/665

### Impact

Users who want to adjust the font size to meet their needs

**Comment by richardshiue** [comment]
I second this. Just making sure, this would zoom the entire app, not just the editor right?

**Comment by annieappflowy** [comment]
Supporting zooming in / out the entire app not just the main editor. Thanks for clarifying!

**Comment by Erik0806** [comment]
Pressing Ctrl + scrolling should have the same effect

**Comment by henri9813** [comment]
Hello,

The shortcuts should be:

- CTRL + / - for windows
- CMD + / - For macOS :)

Thanks !

**Comment by md-weber** [comment]
There seems to be a small issue on macOS (M2): German Keyboard layout. I can zoom out, but not in anymore.

**Comment by henri9813** [comment]
Hello,

Sorry but I have an Averty keyboard

Neither CMD + = ( for zoom in ) nor CMD + - ( for zoom out ) works.

**Comment by Xazin** [comment]
I made a small flutter app so we could see what Flutter is interpreting your keystrokes as.

If some of you could please run this app https://dartpad.dev/?id=03d24ac601bc2311e18bc220dc542e17 and then follow this video to record your keystrokes related to zoom, it might shed some light on what is going wrong.

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/5703107c-2dfb-4ade-8889-e07d9537032b

Notice if you want to show what your combined keystrokes is, eg. `CTRL + -`, you should hold `CTRL` down before pressing on `record` followed by your desired secondary key. That is what I do in the last example, where I hold Shift and press on 0, which logically means `=` on my keyboard.

**Comment by md-weber** [comment]
@Xazin Thanks for sharing that example. My result is "Meta left | '+'". It did not work with both keys together to record, because my browser zoomed in.

**Comment by Xazin** [comment]
> @Xazin Thanks for sharing that example. It did not work with both keys together to record, because my browser zoomed in.
> 
> ![image](https://private-user-images.githubusercontent.com/8026644/335823116-9375bf50-f8ec-463b-9f18-1f5e4481858e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzA5NDksIm5iZiI6MTcxNzI3MDY0OSwicGF0aCI6Ii84MDI2NjQ0LzMzNTgyMzExNi05Mzc1YmY1MC1mOGVjLTQ2M2ItOWYxOC0xZjVlNDQ4MTg1OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMTkzNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ1MjU5NjAyNmE5NjZiMzE0ZWQ2ZjhjNTNlNWI5Y2QwZmIwOTEzMzViMDhmYmRhYWQ5MjNmYzIzNjMzYThiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bYJ-BRxLQYyzwYPSjwc2Z_hYLqcDmlg1CTN8X7Cg1bE)
> 
> I also tested it with an English keyboard layout and used Meta left + = and it zoomed in. Sadly on a German Keyboard layout you have the problem that the '=' sign is a combination of Shift + 0 = '='. Therefore it cannot be recognized.
> 
> I would recommend adding support to change the keybindings in the settings.

Thanks for sharing, I'll try to squeeze in the change to support changing the keybindings for application-wide hotkeys in the next release :pray:

**Comment by md-weber** [comment]
Thanks @Xazin, I would also look into, but still have the issue with Architecture problems. Maybe if you have a minute it would be great if you have a minute to read my message in discord :), maybe you have an idea.

**Comment by annieappflowy** [comment]
Consider this feature is supported.
I created another issue to track @md-weber reported bugs #5601
