### ISSUE TITLE
[FR] Convert quill delta to appflowy document

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1649]
### Description

Convert quill delta to appflowy document.

### Impact

The user who wants to transfer their quill delta to appflowy document will benefit

**Comment by annieappflowy** [comment]
Status?

**Comment by LucasXu0** [comment]
The PR has been merged and released in v0.0.9.

Here's the guide. https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/documentation/importing.md
