### ISSUE TITLE
[FR] Cover image

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1657]
### Description

Support adding a cover image to a page

### Impact

All users who want to decorate their page with a image

**Comment by Xazin** [comment]
We have this on AppFlowy, I guess this can be closed?

**Comment by annieappflowy** [comment]
https://user-images.githubusercontent.com/12026239/231755507-96dbba2f-53f4-465a-b715-ff89b00422c6.mov
