### ISSUE TITLE
[FR] Page icon

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1658]
### Description

Allow the user to add a page icon to the top of a page 
<img width="303" alt="image" src="https://user-images.githubusercontent.com/12026239/210785106-82650788-e32c-4a88-b6fa-56973aa07b74.png">

### Impact

Users who need more visual clues to identify a page

**Comment by Draise14** [comment]
Yeah, this will be nice, specially in the navigation panel or outliner.

**Comment by Xazin** [comment]
This seems to be implemented on the `develop` branch already, not sure if it's on `main` as well.

One thing to notice though, is that without a cover, the icon is still pushed quite far down the page, leaving a huge gap at the top of the document. Might be something to address.

**Comment by annieappflowy** [comment]
<img width="729" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/e884245c-b622-4d51-98d8-66fc62e6abde">

Consider this issue done. I created a new issue for the navigation panel and design polish https://github.com/AppFlowy-IO/AppFlowy/issues/2784
