### ISSUE TITLE
[FR] Support Callout Block

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1661]
### Description

Allow the user to add a callout block to a page.
The callout block should support changing background color and default editing options such as inserting headings and databases.

### Impact

Users who need visual clues to divide a page into different sections.

**Comment by abichinger** [comment]
@annieappflowy I would like to work on this.

**Comment by annieappflowy** [comment]
Thanks @abichinger for claiming the issue. I assigned it to you.

**Comment by annieappflowy** [comment]
Completed
<img width="923" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/a159533b-4649-4008-8c02-0a81be7321ad">
