### ISSUE TITLE
[FR] Support Relation To

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1664]
### Description

Allow the user to link one database to another 

### Impact

Sophisticated database users

**Comment by rollingtatoo** [comment]
I personally can't fully make the switch from Notion until this feature is available! I would give a hand would i know Rust... Will keep an eye on its progress, thanks for your awesome work!

**Comment by justin-pierce** [comment]
Same. My workflows depend heavily on databases being able to dynamically reference each other.

**Comment by rollingtatoo** [comment]
I might be willing to give a hand with this feature and likely others in the future, but i will first need self-learn Rust and Flutter. Are there other techs i would need to familiarize myself with to implement this specific feature?

**Comment by annieappflowy** [comment]
Thanks @rollingtatoo  for your interest in contributing to AppFlowy!
This feature might be too challenging for you at the moment. I'd recommend that you start with beginner [friendly issues](https://github.com/orgs/AppFlowy-IO/projects/5/views/4).

**Comment by annieappflowy** [comment]
How appflowy deal with databases. I cannot create correlation between two databases. Which is a basically the number 1 reason Notion is so powerful.

**Comment by annieappflowy** [comment]
Hello, I am new to AppFlowy and just discovering it. Is it possible to create a relationship from a column on my table to a column in another table?

**Comment by ciseur68** [comment]
Hello,
This feature was initially planned for the v2.4, then 2.6, 3.1, 3.6 and finally unplanned.
Have you any idea if the feature will be added, and when it would be ?
Thanks

**Comment by annieappflowy** [comment]
Thanks @ciseur68 for following us!
We plan to support relation to by the end of Q1 2024 🥹
I totally get it that relation to is an essential feature for power users.
It was initially assigned to @appflowy 
then he has been busy building AppFlowy Cloud. The rest of the team is working on AppFlowy Mobile at the moment.

**Comment by bogerssja** [comment]
@annieappflowy just curious if Q1 2024 is still the plan. Don't see it showing up on the roadmap in the next 2 versions.

**Comment by Xazin** [comment]
> @annieappflowy just curious if Q1 2024 is still the plan. Don't see it showing up on the roadmap in the next 2 versions.

It's actually in our immediate plans, and is currently under development, if you have any questions or suggestions, feel free to let us know.

CC @richardshiue

**Comment by bogerssja** [comment]
No specific requests. Would like to connect two databases so team 1 and team 2 can have their own db and it all rolls up to one orher db, with a different schema. If you have UX related challenges remaining, I'm happy to help.

**Comment by zliebersbach** [comment]
Hi Q1 is about to end, just wondering when we can expect this feature??

**Comment by annieappflowy** [comment]
We supported "Relation" in the latest release ([v0.5.3](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.3)). 
There will be a few more iterations on this feature in the near term. You're welcome to submit new feature requests related to this feature. Closing this issue for now.

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/b3be7c91-d76f-414f-b4a7-6b8236cdffc8

**Comment by xonel** [comment]
[  [FR] Advanced option - Support Relation To #5257 ](https://github.com/AppFlowy-IO/AppFlowy/issues/5257#issue-2278519207)
