### ISSUE TITLE
[FR] Support scientific notation and decimal separator in numbered type cell.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1665]
### Description

1. convert 1.2.3 into 1.2
2. convert 10e9 into 10000000000.

### Impact

none

**Comment by 0xkelvin** [comment]
thanks i will work on this

**Comment by 0xkelvin** [comment]
@LucasXu0 could you please help review and testing again in your side 
PR : https://github.com/AppFlowy-IO/AppFlowy/pull/1688
