### ISSUE TITLE
[FR] Support the Date Created property

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1668]
### Description

Allow users to use an automatically updated field to indicate when a row was created

### Impact

Database users

**Comment by zoli** [comment]
If I'm getting this and existing code correctly implementing this and #1669 feature requires some changes in rust part right?

Maybe `created_at` on row entity? What about `updated_at`? It should be on field entity and calculate the latest as for row's `updated_at`?

**Comment by annieappflowy** [comment]
Hi @zoli , it requires some coding in Rust. Please let me know if you are interested in working on it. This feature is planned to release this quarter.

**Comment by zoli** [comment]
> Hi @zoli , it requires some coding in Rust. Please let me know if you are interested in working on it. This feature is planned to release this quarter.

Sure, I would like to work on this (specially because of Rust part :D) but probably after getting at least some parts of table plugin merged. I'm working on that currently. I don't know if that is OK or not (regarding to the release timeline).

**Comment by zoli** [comment]
@annieappflowy, I would like to take on this issue.
Just to make the issue clear. There should be a `created_at` property which should get created automatically right? and they can hide it if they want.

**Comment by annieappflowy** [comment]
Yes, it's a property type that the user can add to their database. When a new row is created, this property's value is auto-filled.
If they choose to hide this column, then it won't be displayed.

**Comment by zoli** [comment]
Now that develop is merged to main branch, I think this issue can get closed.
