### ISSUE TITLE
[FR] Improve darkmode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1671]
### Description

This is a parent issue for making improvements on the dark mode theme. 
Related issues are listed below:
- https://github.com/AppFlowy-IO/AppFlowy/issues/433
- https://github.com/AppFlowy-IO/AppFlowy/issues/399
- https://github.com/AppFlowy-IO/AppFlowy/issues/336
- https://github.com/AppFlowy-IO/AppFlowy/issues/1807
- https://github.com/AppFlowy-IO/AppFlowy/issues/875

### Impact

Darkmode users

**Comment by hyj1204** [comment]
I'd love to help with it.
