### ISSUE TITLE
[FR] Auto-hide sidebar when re-sizing the window

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1674]
### Description

It would be nice if the sidebar can automatically hide when the window shrinks to the point that the sidebar becomes floating.

### Impact

Users who resize their AppFlowy window to a small size

**Comment by onyicodes** [comment]
Hi @richardshiue can you provide more details on this. An image showing the current state will be helpful. 
Thanks

**Comment by richardshiue** [comment]
@onyicodes Sure. This is the current behavior. It'd be better if the sidebar could automatically hide when the window becomes small enough. 

https://user-images.githubusercontent.com/71320345/213331256-376f1d31-1eb1-48fb-b1a2-bf6415e48b58.mp4

**Comment by onyicodes** [comment]
Okay thanks. I have a clear picture of what is required now. Please can you assign this to me?

**Comment by onyicodes** [comment]
@richardshiue  Which would be better?
The sidebar closes when the window is small enough and  reappears when the window is expanded beyond a certain extent or it does not reappear automatically but waits for user to tap on open sidebar icon again?

**Comment by richardshiue** [comment]
> Please can you assign this to me?

Sure! I've assigned it to you. Thank you for helping with this.

> @richardshiue Which would be better? 

Ideally, this is the UX I'm accustomed to. If the sidebar was hidden when the window was still large enough, then the latter. If the sidebar was shown, then the former. You can absolutely just choose one for now and alter the behavior later on.

**Comment by onyicodes** [comment]
> > Please can you assign this to me?
> 
> Sure! I've assigned it to you. Thank you for helping with this.
> 
> > @richardshiue Which would be better?
> 
> Ideally, this is the UX I'm accustomed to. If the sidebar was hidden when the window was still large enough (before shrinking the window), then the latter. If the sidebar was shown, then the former. You can absolutely just choose one for now and alter the behavior later on.

Alright. Thanks

**Comment by huang12zheng** [comment]
Compact	Width < 600	
Medium	600 < width < 840
Expanded	Width > 840
Could be a possible reference value?
@onyicodes

**Comment by AmanNegi** [comment]
Hey @onyicodes, are you working on this issue?

**Comment by onyicodes** [comment]
Hi @AmanNegi yeah I'm still working on it.

**Comment by AmanNegi** [comment]
Great! 💚

**Comment by annieappflowy** [comment]
Let us know if you need help!

**Comment by DestinedCodes** [comment]
@onyicodes have you worked on this, I would be glad to help

**Comment by onyicodes** [comment]
Yeah @DestinedCodes I'm making some good progress. Thanks for asking

**Comment by Shreesh09** [comment]
I would like to work on this issue

**Comment by annieappflowy** [comment]
Completed
