### ISSUE TITLE
[FR] Propagate dart log to rust and save to disk

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1677]
### Description

Currently, the dart log doesn't save to disk. It needs to propagate the [log](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/flowy_sdk/lib/log.dart) to the backend. For example, we can create a new c API in [dart-ffi ](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/dart-ffi/src/lib.rs).  Then call it from the dart code through [ffi.dart](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/flowy_sdk/lib/ffi.dart)

![image](https://user-images.githubusercontent.com/86001920/211128360-2e2e29a3-8a36-432c-97cf-adcd3a873742.png)

### Impact

None

**Comment by 0xkelvin** [comment]
i willing take this one

**Comment by 0xkelvin** [comment]
could you please check again the hyperlink, i am not able to access: 

- log : https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/flowy_sdk/lib/log.dart
- ffi.dart: https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/flowy_sdk/lib/ffi.dart

cc: @annieappflowy @appflowy
