### ISSUE TITLE
[Bug] Editor toolbar glitch

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1681]
### Bug Description

Sometimes the toolbar will have a glitch and show all the options as selected. See recording below

### How to Reproduce

Reproducible based on the difference in block width.

I am holding down the left mouse button from the bottom line and then dragging as shown in the recording below

### Expected Behavior

This shouldn't happen

### Operating System

Fedora Linux 36

### AppFlowy Version(s)

0.0.9

### Screenshots

https://user-images.githubusercontent.com/71320345/211159258-1d52b0fc-2160-496a-9bca-70f28ae000a2.mp4

**Comment by annieappflowy** [comment]
Hi @richardshiue , are you still running into this issue?

**Comment by richardshiue** [comment]
Hi @annieappflowy, yes, still reproducible on main and v0.2.5

**Comment by annieappflowy** [comment]
reproducible on v0.3.9.1

**Comment by richardshiue** [comment]
Reproducible on v0.5.3

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/23bcdce1-f244-4e9a-943e-6d83f743fdfb)
