### ISSUE TITLE
[FR] Simplify URL field UX

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1685]
### Description

At the moment, clicking on a URL cell, on the edit accessory or the field in an overlay opens up a popup textfield to the bottom. It would be a lot simpler to place the textfield directly in that space like the text or number fields.

### Impact

Users who place links in the database.

**Comment by hyj1204** [comment]
I hope the editing URL can be easy as editing a text cell.  The edit button for the URL cell looks redundant if we can edit the URL directly.

Here is the preview for current interaction in URL cell which looks a litter bit buggy. 

https://user-images.githubusercontent.com/14248245/230477256-c48378db-dcf9-4b17-8a32-0259020c4f40.mov
