### ISSUE TITLE
[Bug] Failed to start Flutter renderer: No available configurations for the given RGBA pixel format

### ISSUE THREAD

**Issue by jbobbylopez** [AppFlowy-IO/AppFlowy#1689]
### Bug Description

Please note, I believe this issue was previously reported both in https://github.com/flet-dev/flet/issues/166 and in https://github.com/AppFlowy-IO/AppFlowy/issues/418
However in those issues there was no response/follow-up, and so the issue was closed before it could be resolved.

My best guess right now is that this issue affects all users who are trying to run Appflowy on any Ubuntu-based OS distribution - and possibly other Linux distributions as well.

I've tried installing Appflowy in two ways (Docker and "Building the docker image") as described in this document:
https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker

### How to Reproduce

Both methods have failed with the same error as follows:

```
 $ sudo docker-compose up
Creating volume "podman-appflowy_appflowy-data" with default driver
Creating podman-appflowy_app_1 ... done
Attaching to podman-appflowy_app_1
app_1  | 
app_1  | ** (app_flowy:1): WARNING **: 00:58:08.309: Failed to start Flutter renderer: No available configurations for the given RGBA pixel format
```
At that point, the docker container is still running, and the "app_flowy" client window starts on the desktop, but nothing is rendered to window.

### Expected Behavior

Expected behaviour is that Appflowy client would load correctly.

### Operating System

Ubuntu 22.04.1 LTS

### AppFlowy Version(s)

v0.0.9

### Screenshots

![appflowy-flutter-RGBA-issue](https://user-images.githubusercontent.com/447140/211233231-7dce6785-cd64-48e2-9cbb-60a2147732fe.png)

### Additional Context

Let me know if there is any other info I can provide to help investigate, thanks.

**Comment by luisheres** [comment]
Hi, any news on this bug? I get the same thing.

**Comment by tensmyo** [comment]
Hi, Exactly same issue. it will be great helpful if you can share any progress

**Comment by lpinilla** [comment]
same issue, it worked the first time I used it and after `apt dist-upgrade` it broke

**Comment by LucasXu0** [comment]
Hi there! There's a workaround worth trying: before running the application, execute this command: export LIBGL_ALWAYS_SOFTWARE=1.

it comes from https://github.com/flutter/flutter/issues/106941
