### ISSUE TITLE
[FR] Unit test for num scientific notation

### ISSUE THREAD

**Issue by 0xkelvin** [AppFlowy-IO/AppFlowy#1691]
### Description

Unit test for num scientific notation

### Impact

numer type optioin

**Comment by annieappflowy** [comment]
@0xkelvin , what's the latest progress on this? Done?

**Comment by 0xkelvin** [comment]
> @0xkelvin , what's the latest progress on this? Done?

oh done, but haven't commit yet, let me review again

**Comment by annieappflowy** [comment]
Hi @0xkelvin , have you completed this issue?
