### ISSUE TITLE
[FR] Separate checklists for separate blocks, and other checklist features. 

### ISSUE THREAD

**Issue by Toxteer** [AppFlowy-IO/AppFlowy#1692]
At this time, it is not possible to have separate checklists for blocks. For instance, if I want to track progress through a checklist, but I don't want all the blocks to have the same checklist. You should still be able to have "global" checklist that show up on every block if thats what the user wants.

![BLOCK](https://user-images.githubusercontent.com/59182487/211563070-7998a483-e37d-48b2-8e86-496a15c6519e.png)

Additonally, to make checklists more usable:
- Adding color options

> Like the picture above

- Adding a distance if more than one checklist is used.

> How it looks right now:

![SPACE](https://user-images.githubusercontent.com/59182487/211562994-44dbb6aa-71b0-44ca-b47b-36793cf9653b.png)

- Adding the abbility to display the items in the checklist in a list format on the block. 

> One example

![LIST](https://user-images.githubusercontent.com/59182487/211564211-e0113539-8e20-4d54-870f-ed152ac31e56.png)

**Comment by Jmsi18** [comment]
Hi, good that this improvement is already considered...it will help a lot to all AppFlowy users.

**Comment by annieappflowy** [comment]
This feature is scheduled to start the development this month

**Comment by annieappflowy** [comment]
<img width="473" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/d87e9f99-f2c6-4886-adab-afa497e2ddbd">
<img width="540" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/00dbd028-6e2a-4f3c-9844-298d0d1da217">
Fixed!
Please give it a try @Jmsi18 @Toxteer using the [latest](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.2.0) release
