### ISSUE TITLE
[FR] Reorder grid items

### ISSUE THREAD

**Issue by TrevorGKann** [AppFlowy-IO/AppFlowy#1697]
### Description

You can drag and drop items between sections in the board menu, it would be nice to be able to reorder items in the grid as well. Also being able to sort by different column values like priority or date. 

### Impact

anyone who uses the grid would be benefited by this feature.

**Comment by annieappflowy** [comment]
Hi @TrevorGKann , thanks for providing us with your valuable feedback. We actually support reordering columns in Grid (see the attached). Is this what you meant? 
![ezgif-1-d51756bd77](https://user-images.githubusercontent.com/12026239/211970496-81cf70a9-3294-468b-b575-0ad0de1a22dc.gif)

Reordering rows is not supported yet.
Sorting will be supported in the upcoming v0.0.9.1.

**Comment by TrevorGKann** [comment]
Thank you for the reply. I meant to re-order rows. I should have been more specific. 

I didn't see it in the roadmap, but I probably didn't look close enough.

**Comment by annieappflowy** [comment]
We supported reordering rows in the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases)

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7cbf14ca-8fdf-40e9-a1a7-59649f28de7d
