### ISSUE TITLE
[Bug] Cannot undo reverting to Markdown

### ISSUE THREAD

**Issue by Erik0806** [AppFlowy-IO/AppFlowy#1703]
### Bug Description

When writing e.g variable names for planning, the text is turned italic automatically. In this context this is unwanted. In other programs it is possible to convert this change by pressing Ctrl + Z. This however doesn't work for AppFlowy.

### How to Reproduce

1. Write '\_test\_'
2. The text will be replaced by '_test_'
3. Press Ctrl + Z
4. The text will be completely removed

### Expected Behavior

Text will be converted back to '\_test\_'

### Operating System

Linux (but is irrelevant for this)

### AppFlowy Version(s)

0.0.9

**Comment by Xazin** [comment]
This has been implemented ina previous version, will close for now :+1:
