### ISSUE TITLE
[Bug] User name and icon get reset when sidebar is closed

### ISSUE THREAD

**Issue by 1gni5** [AppFlowy-IO/AppFlowy#1713]
### Bug Description

When editing the name and/or the icon of the user, then collapsing and expanding the sidebar the name and the icon get reset.
> The way to collapse/expand the sidebar, keyboard shortcut or mouse click has no influence on the bug.

### How to Reproduce

1. Change the user name and icon
2. Collapse the sidebar
3. Expand the sidebar

### Expected Behavior

The user name and icon should be kept even if the sidebar is collapsed.

### Operating System

MacOS Ventura 13.1

### AppFlowy Version(s)

0.0.9.1 (1)

**Comment by annieappflowy** [comment]
Fixed
