### ISSUE TITLE
[Bug] lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:115:7: Error: 'SelectOptionPB' isn't a type. 

### ISSUE THREAD

**Issue by lucasjinreal** [AppFlowy-IO/AppFlowy#1725]
### Bug Description

lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:115:7: Error: 'SelectOptionPB' isn't a type.
      SelectOptionPB option) = _SelectOption;
      ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:117:7: Error: 'SelectOptionPB' isn't a type.
      SelectOptionPB option) = _UnSelectOption;
      ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:119:12: Error: 'SelectOptionPB' isn't a type.
      List<SelectOptionPB> options) = _DidReceiveOptions;
           ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:127:19: Error: 'SelectOptionPB' isn't a type.
    required List<SelectOptionPB> options,
                  ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:144:9: Error: 'SelectOptionPB' isn't a type.
  final SelectOptionPB optionPB;
        ^^^^^^^^^^^^^^
Unhandled exception:
Null check operator used on a null value

### How to Reproduce

lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:115:7: Error: 'SelectOptionPB' isn't a type.
      SelectOptionPB option) = _SelectOption;
      ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:117:7: Error: 'SelectOptionPB' isn't a type.
      SelectOptionPB option) = _UnSelectOption;
      ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:119:12: Error: 'SelectOptionPB' isn't a type.
      List<SelectOptionPB> options) = _DidReceiveOptions;
           ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:127:19: Error: 'SelectOptionPB' isn't a type.
    required List<SelectOptionPB> options,
                  ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:144:9: Error: 'SelectOptionPB' isn't a type.
  final SelectOptionPB optionPB;
        ^^^^^^^^^^^^^^
Unhandled exception:
Null check operator used on a null value

### Expected Behavior

lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:115:7: Error: 'SelectOptionPB' isn't a type.
      SelectOptionPB option) = _SelectOption;
      ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:117:7: Error: 'SelectOptionPB' isn't a type.
      SelectOptionPB option) = _UnSelectOption;
      ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:119:12: Error: 'SelectOptionPB' isn't a type.
      List<SelectOptionPB> options) = _DidReceiveOptions;
           ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:127:19: Error: 'SelectOptionPB' isn't a type.
    required List<SelectOptionPB> options,
                  ^^^^^^^^^^^^^^
lib/plugins/grid/application/filter/select_option_filter_list_bloc.dart:144:9: Error: 'SelectOptionPB' isn't a type.
  final SelectOptionPB optionPB;
        ^^^^^^^^^^^^^^
Unhandled exception:
Null check operator used on a null value

### Operating System

macos

### AppFlowy Version(s)

master

### Screenshots

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/21303438/213331047-22508c1d-4d96-46eb-9885-a55872f79118.png">

### Additional Context

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by appflowy** [comment]
It seems like your local development env was not set up correctly. Did you follow the instructions in https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos?

**Comment by minhnn94** [comment]
@appflowy  I still it. 
line 164, column 25 of .: Expected to find ','.
    ╷
164 │ as List<SelectOptionPB> options, List<SelectOptionPB>,
    │                         ^^^^^^^
    ╵
line 185, column 39 of .: Expected to find ';'.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                       ^^^^
    ╵
line 185, column 43 of .: Expected a class member.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                           ^
    ╵
line 185, column 44 of .: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                            ^^^^^^^^^^^^^^
    ╵
line 185, column 44 of .: Expected to find ';'.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                            ^^^^^^^^^^^^^^
    ╵
line 185, column 58 of .: Operator declarations must be preceded by the keyword 'operator'.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                                          ^
    ╵
line 185, column 58 of .: Methods must have an explicit list of parameters.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                                          ^
    ╵
line 185, column 60 of .: A function body must be provided.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                                            ^^^^^^^^^^^^^^^^
    ╵
line 185, column 60 of .: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
    ╷
185 │  final  List<SelectOptionPB> options, List<SelectOptionPB> _selectedOptions;
    │                                                            ^^^^^^^^^^^^^^^^
    ╵
line 186, column 41 of .: Expected to find ';'.
    ╷
186 │ @override List<SelectOptionPB> options, List<SelectOptionPB> get selectedOptions {
 My device the same with topic. But I can not run App. I wonder how to get SelectOPtionPB and Where?
 Please help me

**Comment by annieappflowy** [comment]
Since the codebase has been changed a lot since Jan 19, I'm closing this issue.
