### ISSUE TITLE
[FR] AppFlowy Kanban board UI

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1728]
### Description

Implement the Kanban Board of AppFlowy

<img width="684" alt="image" src="https://user-images.githubusercontent.com/86001920/213378250-731ae16a-51de-4882-87dc-b040da4a62aa.png">

 In addition, these have been implemented in Flutter, you can refer to the [implementation](https://github.com/AppFlowy-IO/AppFlowy/tree/main/frontend/app_flowy/lib/plugins/board) inside to organize your code or you can download the release [AppFlowy](https://github.com/AppFlowy-IO/AppFlowy/releases) to experience the interaction.

Prerequisites:

Follow this [guide](https://www.notion.so/appflowy/Development-6eb9015951834853b394fc360c07a673) to see AppFlowy design principle and set up your development environment

### UI Sub Tasks

- [x] Make `/kanban` route
- [x] Heading and subheading UI with icon
- [x] Grid, Board and Group by text UI with icon 
- [x] Group by dropdown UI 
- [x] Search component UI
- [x] Setting up the kanban board with todo, In progress, complete, and new block columns UI
- [x] Column header component UI
- [ ] Columns header component more option icon with dropdown UI along with search component
- [x] Column footer component UI
- [x] Card component UI
- [x] Card image UI
- [x] Card heading and date UI
- [ ] Card more option icon with dropdown UI along with search component
- [ ] Card tags/chips UI
- [ ] Card multi tags/chips dropdown UI
- [ ] Card progress bar UI along with percentage
- [ ] Card user image and name heading UI

### APIS Integration Sub Tasks

- [ ] Implement Grid view
- [ ] Implement Board view (Design missing)
- [ ] Implement Group by dropdown functionality
- [ ] Implement search functionality ie by name etc
- [ ] Update the status label, color and count in columns header
- [ ] Implement search functionality in column header dropdown
- [ ] Implement status label in in column header dropdown
- [ ] Implement status color in in column header dropdown
- [ ] Implement delete functionality in column header dropdown
- [ ] Implement hide column functionality in column header dropdown
- [ ] Implement add new functionality on click of plus icon in column header dropdown(tbd)
- [ ] Implement add new block functionality
- [ ] Show dynamically card title and date
- [ ] Assign multiple tags/chips functionality on card
- [ ] Implement progress bar functionality with percentage on card
- [ ] Show dynamically user image and name on card
- [ ] Implement search functionality in card dropdown
- [ ] Implement copy link functionality in card dropdown
- [ ] Implement duplicate functionality in card dropdown
- [ ] Implement delete functionality in card dropdown
- [ ] Text dropdown in card (tbd)
- [ ] Implement card drag functionality
- [ ] Implement add new functionality in column footer

# Required
1. Use **React-TS** to build the UI and follow the [react design principles](https://reactjs.org/docs/design-principles.html)
2. Lint: https://github.com/prettier/prettier - [https://prettier.io/docs/en/editors.html](https://prettier.io/docs/en/editors.html)
3. i18n:  https://github.com/i18next/react-i18next
4. State manager:  https://github.com/reduxjs/react-redux
5. unit test: https://github.com/testing-library/react-testing-library
6. UI should support the Theme
7. Follow the [DDD](https://www.notion.so/AppFlowy-React-c858a3f1bde04f88b75686192f6c8e6e) design principle

Resources :

1.  [AppFlowy Figma](https://www.figma.com/file/X1R9i5HAFtJSNIKOPPW7yK/AppFlowy-%5BUI%5D%5BMaster%5D?node-id=0%3A1&t=CR4OidJ8GnzNuUrD-1)
2. [AppFlowy release version](https://github.com/AppFlowy-IO/AppFlowy/releases)
3. [About AppFlowy Tauri](https://www.notion.so/About-749332384d1b45cd9ec67c61dda82ffe)

### Impact

None

**Comment by umairrazam** [comment]
hi
