### ISSUE TITLE
[FR] Support to CTRL + ALT + Q

### ISSUE THREAD

**Issue by diegogit03** [AppFlowy-IO/AppFlowy#1739]
### Description

Hi! i have a keyboard without "/". for type this character i use CTRL + ALT + Q and the AppFlowy not see element list. I suppose that in code listen "/" key no "/" character.

Sorry if not undestand my english, i am brazilian :D

### Impact

People with keyboard without "/" will could use the flowy.

### Additional Context

none other than this

**Comment by MayurSMahajan** [comment]
Hi, this issue fits right into my mentorship project, so I would like to be assigned for this issue.

**Comment by MayurSMahajan** [comment]
Hey @diegogit03! Hope you are well. I wanted to know if it is a common practice for Brazilian users to use Ctrl+Alt+Q for adding the '/' character. 

Also in the near future, we are going to implement a feature called Customize Shortcuts, where you will be able to define your own shortcuts for any tasks that we support.

**Comment by MayurSMahajan** [comment]
Hey @diegogit03! you can now simply customize the slash menu with your desired key combination.

**Comment by annieappflowy** [comment]
@MayurSMahajan , I'd suggest we create a user guide for how to customize shortcuts

**Comment by annieappflowy** [comment]
Hi @diegogit03 , you can now use the slash command if you pull the latest code or wait for the next release (v0.1.2).
Similar issue: https://github.com/AppFlowy-IO/AppFlowy/issues/2098

**Comment by MayurSMahajan** [comment]
@annieappflowy absolutely, even better I have created a 1 minute video, where I am customizing shortcuts. I will include it with the written steps in our docs

**Comment by MayurSMahajan** [comment]
Since introducing `CharacterShortcutEvent` for the Slash command, users who don't use `/`  key but some other key combination to insert the slash symbol will also be able to see the Selection Menu appear.
