### ISSUE TITLE
[FR] Consider Flatpak release via Flathub / Flathub-Beta

### ISSUE THREAD

**Issue by bayazidbh** [AppFlowy-IO/AppFlowy#175]
**1~3 main use cases of the proposed feature**
Use for most Linux distros. While AppImage and Snap are valid ways of universal package distribution on Linux, Flatpak seems to be the one that is more embraced by distributions that aren't mainline Ubuntu (although Ubuntu users can very easily add Flatpak as source, and it is more embraced by Ubuntu-based distro) and Arch-based (AUR).

This is especially true with OS with immutable root filesystem, such as Endless OS, Fedora Silverblue/Kinoite, and soon SteamOS 3.0.

Using Flatpak would be a good way of distributing them for most platforms, especially given that they are usually integrated with the distribution's GUI Software Centers. 

**what types of users can benefit from using your proposed feature**
Linux users in most distributions (Ubuntu users can also easily add Flatpak source).

**Additional context**
Consider using Flathub-Beta while the project is still in early development.

**Comment by Ayush1325** [comment]
I have created flatpak manifest and other required files. They can be found [here](https://github.com/Ayush1325/flathub/tree/appflowy). I am able to install and run it on my local system. It would be great if someone else already familiar with the application can also test it out since this is my first time using AppFlowy.

**Comment by MikeWallaceDev** [comment]
@Ayush1325 Thank you very much for that!  
So these files will create an installable flatpack?  I've never built one...
You should create a PR, linked to this issue. However, place the files in the following directory : 
appflowy/frontend/scripts/flatpack-buildfiles

From there, we can test out the files, and maybe add the flatpack to our release process.

**Comment by CodeCubeNeo** [comment]
Any progress on rhis?

**Comment by Ayush1325** [comment]
> Any progress on rhis?

Well, last I checked, the flatpak I created worked fine. It can be submitted directly to flathub but someone probably needs to become a maintainer or something to make sure it works fine.

**Comment by CodeCubeNeo** [comment]
Now we just have to find one. Could somebody from the devs (maybe the one who publishes the win binaries) be that? How do we ask them?

**Comment by annieappflowy** [comment]
Since this is a highly requested issue, we decide to work on it. I will come back to this thread when it's done. Thanks all.

**Comment by MichaelTunnell** [comment]
> Since this is a highly requested issue, we decide to work on it. I will come back to this thread when it's done. Thanks all.

I came here to request Flatpak support and to see it already planned to be done is Awesome! 😎👍

**Comment by vincentdchan** [comment]
I am starting to build the Flathub package. It's on the way. ✈️

**Comment by andreysaksonov** [comment]
@vincentdchan will bleeding edge version be available through flatpak-beta

**Comment by annieappflowy** [comment]
Hi all, @LucasXu0 will take over this issue to work on in this quarter.

**Comment by FriedrichGaming** [comment]
https://flathub.org/apps/details/io.appflowy.AppFlowy

**Comment by LucasXu0** [comment]
Hi, All. We have released the latest AppFlowy on Flathub.

```
flatpak install flathub io.appflowy.AppFlowy
flatpak run io.appflowy.AppFlowy
```

**Comment by yodatak** [comment]
I update the flatpak to 0.0.0.8 and add a autodependcy checker 
https://github.com/flathub/io.appflowy.AppFlowy/pull/6
