### ISSUE TITLE
[FR] Create a separate repo for appflowy_editor

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1758]
### Description

This is a subtask of https://github.com/AppFlowy-IO/AppFlowy/issues/1718

- [x] On Feb 1st, go over contributors who have not given consent and start rewriting their code in an environment that has no access to the original contributions and document the environment
- [x] On Feb 5th, separate appflowy_editor from AppFlowy in a new repo under https://github.com/AppFlowy-IO
- [x] Dual license appflowy_editor under AGPL 3.0 and MPL 2.0
- [x] Set up CLA assistant
- [x] Change the license on pub.dev

The same for appflowy_board

### Impact

appflowy_editor / appflowy_board users

**Comment by LucasXu0** [comment]
- [ ] migrate the CI related to the editor to https://github.com/AppFlowy-IO/appflowy-editor, and remove them from the main repo.
- [ ] update the minimum supported Flutter version of the editor to 3.7.0.
- [ ] update the minimum supported Flutter version of the main repo to 3.7.0.
- [ ] release editor v0.1.1
- [ ] config Github actions for the editor repo, like, codecov, release_notes.

**Comment by annieappflowy** [comment]
@LucasXu0  is this task all done?
