### ISSUE TITLE
[Bug] Numbered list

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1761]
### Bug Description

No line between numbered list items is allowed 

<img width="166" alt="image" src="https://user-images.githubusercontent.com/12026239/215458336-5a310057-bdd7-442f-ac1b-10036fb8a365.png">

### How to Reproduce

1. Create three numbered list items
2. Try to add an empty line between 1. and 2.
3. The numbers shown are not incremental from 1 to 3

### Expected Behavior

Like Google Docs, I can add empty lines in between a numbered list
<img width="99" alt="image" src="https://user-images.githubusercontent.com/12026239/215459139-d2410b11-210b-4054-b0b9-9e5fabbff9f2.png">

### Operating System

Windows 10

### AppFlowy Version(s)

0.0.9.1

**Comment by LucasXu0** [comment]
It's by design. If we press the enter between numbered lists, the below part will re-sort from 1.

Please take a look at this video if you'd like to insert an empty line between the incremental numbered list.

https://user-images.githubusercontent.com/11863087/215662798-01d549ba-e657-4e15-bf0a-617d1e217103.mov

Or using shift+enter to add a new line at the same node.

**Comment by richardshiue** [comment]
I didn't know about shift+enter, maybe that's what Annie wants as well. In google docs, the shift+enter to add a new line in the same node is a single enter, and a subsequent enter will trigger AppFlowy's usual enter behavior that splits the number list into two.

**Comment by annieappflowy** [comment]
Ok I see. I didn't figure out the trick.
I suppose Shift + enter should be added to our shortcuts guide (which doesn't exist yet)

**Comment by MayurSMahajan** [comment]
Okay, so we just want to add documentation for the shift+enter, in our shortcuts guide(which I will be happy to make), right? Or am I missing something? I did not understand what Richard meant.

**Comment by annieappflowy** [comment]
Based on my understanding, what Richard means is that in Google Docs both ways (shift+enter or enter+backspace) can achieve adding lines between numbered item without breaking the existing number order. AppFlowy only supports shift+enter at the moment.

I think we should write documentation to list out all the shortcuts we support. In addition, we can add an entry to the "?" list at the bottom right of the editing area to direct users to view the shortcut guide.

**Comment by MayurSMahajan** [comment]
Okay understood! Thanks.

**Comment by MayurSMahajan** [comment]
So the objective of the PR solving this issue will facilitate the redirection of the user to a documentation page that enlists all the existing predefined shortcuts. This link can be accessed by clicking on the "?" button 
![image](https://user-images.githubusercontent.com/47064215/216049565-8f45d890-75a7-48f6-9edf-532b828091a5.png)
I can get this done, but this seems a perfect choice for a "good first issue" for any newcomers. If no one claims it I will work on it.

**Comment by AmanNegi** [comment]
Hey there can I work on this?

**Comment by MayurSMahajan** [comment]
Hey @AmanNegi! Go ahead, you can start working on this.

**Comment by AmanNegi** [comment]
Hey there, do we already have a list of Shortcuts listed somewhere? If not are we supposed to create a Flutter Page or a `SHORTCUTS.md` in the GitHub Repository?

**Comment by annieappflowy** [comment]
Hi @AmanNegi , we should create a documentation page to list the shortcuts we support and build a link in the app so people can be directed to that page. 

Just created a page for you to fill good stuff in: https://github.com/AppFlowy-IO/AppFlowy-Docs/blob/main/essential-documentation/shortcuts.md
You can work on it and submit a PR for review.
Meanwhile, you can also work on adding a link to "?"

**Comment by MayurSMahajan** [comment]
Hey @AmanNegi, you can find the list of existing shortcuts here.
`AppFlowy\frontend\app_flowy\packages\appflowy_editor\lib\src\service\shortcut_event\built_in_shortcut_events.dart`

**Comment by AmanNegi** [comment]
Thanks, 😊 @MayurSMahajan That helps a lot!

**Comment by AmanNegi** [comment]
Hey there, I had a question. If I add some text, do I need to add translation in each language?

``` json
  "questionBubble": {
    "shortcuts": "Shortcuts", 
    "whatsNew": "What's new?", 
    "help": "Help & Support",
    "debug": {
      "name": "Debug Info",
      "success": "Copied debug info to clipboard!",
      "fail": "Unable to copy debug info to clipboard"
    }
  }
```
> Added `"shortcuts": "Shortcuts"` above in `en.json`.

**Comment by MayurSMahajan** [comment]
No just English is fine, if you **want** to add a translation for any other language, you can create a new PR for that.

**Comment by AmanNegi** [comment]
Okay great :)
