### ISSUE TITLE
[FR] Support shortcuts for checking on/off a checkbox

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1762]
### Description

As described in the title, I would like to use keyboard shortcuts to check off a checkbox and uncheck it.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/12026239/215460912-29d13128-7554-420e-9044-844f70227079.png">

### Impact

Users who want to quickly check off or uncheck a checkbox

**Comment by MayurSMahajan** [comment]
Working on it!
