### ISSUE TITLE
[FR] Web App interface for hosting

### ISSUE THREAD

**Issue by iamaravindim** [AppFlowy-IO/appflowy#177]
**Use cases of the proposed feature**
Is it possible for a web interface to be made available for AppFlowy so that we can host it completely on a server as a Webapp and access it through the browser?

**what types of users can benefit from using your proposed feature**
This would help people to work on thing online as a team.

**Comment by nguillaumin** [comment]
Duplicate of #89 ?

**Comment by MikeWallaceDev** [comment]
Duplicate of #89
