### ISSUE TITLE
[FR] Import local MD file or project

### ISSUE THREAD

**Issue by Sun-Glove** [AppFlowy-IO/AppFlowy#1773]
### Description

Actually, I choose to write document in Markdown editor and then comb the document relationships with Obsidian.
But AppFlowy cant import/export conveniently. 
It's like I found an error somewhere while combing and needed to go to AppFlowy and re-modify and export it instead of opening the document directly with AppFlowy
I hope someday, we can intuitively see that your documents are in your own store.
Thanks

### Impact

People like me who need to work with documentation across applications frequently.

**Comment by annieappflowy** [comment]
Thanks for sharing your needs.
Can you elaborate on how you sync files across different platforms? Do you want to sync by file or in batch or by vault?
Also, under what scenarios do you want to use AppFlowy to edit files from Obsidian or other markdown editors?

**Comment by Sun-Glove** [comment]
> Thanks for sharing your needs. Can you elaborate on how you sync files across different platforms? Do you want to sync by file or in batch or by vault? Also, under what scenarios do you want to use AppFlowy to edit files from Obsidian or other markdown editors?

About sync:
I am using two options right now. One through cloud, and the other set up locally. Buy they all sync by vault directly.
1.This is to back up my notes. First I created a private repo on github and configured git bash locally. It's then automatically uploaded to my repo via Obsidian Git---a Obsidian's plugin.
2.This is for editing my files using two different software. I will just create a vault. Have two pieces of software share this vault. 

The other question:
In fact, Appflowy is always my first editor, but this is not so convenient when errors are found after exporting.
You may know,Obsidian has always had one flaw. It is not very good at "what you see is what you get", it relies on a lot of plugins. So I will choose a more intuitive and consier editor like AppFlowy to complete edit file. Put them in charge of different functions.

**Comment by annieappflowy** [comment]
Thanks for the explanation, super valuable to us.
My follow-up questions:
1. Do you create one vault for one project or you tend to have a main vault to include all your files?
2. How often do you switch from one vault to another?

**Comment by Sun-Glove** [comment]
> Thanks for the explanation, super valuable to us. My follow-up questions:
> 
> 1. Do you create one vault for one project or you tend to have a main vault to include all your files?
> 2. How often do you switch from one vault to another?

1. I prefer to creare a vault where I can store my subproject.
2. When I finish learning a piece of knowledge(very large). But not very often ..... about half a year
