### ISSUE TITLE
[FR] title plugin for AppFlowy and AppFlowy Editor

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1774]
### Description

While developing the Grid and Board plugins, I found an issue. If inserting a Grid or Board at the first position, we can't continue to add text before it. So I assume that we need to make sure the node at the first position must be a TextNode.

Normally, for the text node at the first position, it should be a title.

### Impact

improve the user experience for writing.

### Additional Context

* make sure that the node at the first position is TextNode.
* In AppFlowy, this node must be a title, and can't be inserted in places other than the first position.
* The style of the title should be fixed. Disable the selection menu or the toolbar when selecting the title node.
* ~~The title of the document should be synced with its name~~.
* https://www.figma.com/file/HxyVjpgGpGPlag6IBJemnR/AppFlowy-Dark?node-id=862%3A436890&t=RVvst46sss6HG8z3-0

**Comment by rizwan3395** [comment]
Grid Plugin

<img width="973" alt="Screenshot 2023-02-06 at 4 20 15 AM" src="https://user-images.githubusercontent.com/47111784/216851719-5f22a8d4-b047-4474-be01-0091bdf961d4.png">

**Comment by rizwan3395** [comment]
will document name of Grid or Board  could be the title ?

**Comment by LucasXu0** [comment]
> @LucasXu0 will document name of Grid or Board could be the title ?

I don't get your point. What's the meaning of the document name of Grid or Board.

**Comment by rizwan3395** [comment]
I mean the page name.

**Comment by rizwan3395** [comment]
is there any limit for text on top. e.g heading only

**Comment by rileyhawk1417** [comment]
I am interested in trying this can i take a look at it?

**Comment by rileyhawk1417** [comment]
Am interested in this can I take a look at it?

**Comment by annieappflowy** [comment]
Assigned! @rileyhawk1417 , thanks ❤️
