### ISSUE TITLE
[FR] The text formatting toolbar should appear after the selection

### ISSUE THREAD

**Issue by Sun-Glove** [AppFlowy-IO/AppFlowy#1778]
### Description

https://user-images.githubusercontent.com/63444399/216002391-54caa119-52ec-41e5-a0cb-37cd866f76d5.mp4

You can see. The text formatting toolbar appears during the selection. This will block the information below.

 So I think the text formatting toolbar should appear after the selection

### Impact

Most users.

**Comment by annieappflowy** [comment]
I don't see it blocking text below. Can you try to add a new line of words below and try highlight the first line again?
<img width="392" alt="image" src="https://user-images.githubusercontent.com/12026239/216014410-ce168e0c-2d52-4bfd-9d6d-5af06c87451e.png">

**Comment by Sun-Glove** [comment]
> I don't see it blocking text below. Can you try to add a new line of words below and try highlight the first line again?
> <img width="392" alt="image" src="https://user-images.githubusercontent.com/12026239/216014410-ce168e0c-2d52-4bfd-9d6d-5af06c87451e.png">
> 

Thank you very much for your opinion.
After testing, I found that there was no such problem, which was my negligence. 
But, Software like Office always has an edit box after it is selected, so the operation mode and impression may be more comfortable.

**Comment by annieappflowy** [comment]
I agree. The timing to trigger the toolbar needs improvements. Let me make it a to-do in our project.

**Comment by annieappflowy** [comment]
This is done. @Sun-Glove , you can test it in the upcoming release v0.1.1
Thanks for your feedback. Look forward to getting more suggestions from you.
