### ISSUE TITLE
[Bug] malicious software warning on install

### ISSUE THREAD

**Issue by stefnestor** [AppFlowy-IO/appflowy#18]
Just heard about & love this project! Installation bug: 

On macOS Big Sur (v11.5.2), AppFlowy (v0.0.2) gives opening error requiring _Security & Privacy_ override to bypass as warning:

```
“AppFlowy 2” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
Firefox downloaded this file today at 9:56 AM from github.com.
```

Appears next-step bug to https://github.com/AppFlowy-IO/appflowy/issues/6. 

1. Download most recent release [0.0.2 zip](https://github.com/AppFlowy-IO/appflowy/releases/tag/0.0.2)
2. Unzip & click "AppFlowy" file, receive error
3. Open _Security & Privacy_ click to "open anyway"
4. AppFlowy now successfully loads & will w/o error on subsequent open attempts

<details><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/26751266/142032873-2d1d548f-6c62-45e4-bebb-fd2f479cdb21.png)

![image](https://user-images.githubusercontent.com/26751266/142033735-2e1412fe-7ef8-4e7a-ba98-e1e78586bd83.png)

</details>

**Comment by nicolasdanelon** [comment]
open the app from Finder and not form launchpad and you will be just fine

**Comment by mychidarko** [comment]
- Open your system settings and click on security and privacy
![image](https://user-images.githubusercontent.com/26604242/142066017-3f0f3d09-affd-4ce9-b28a-7b35b4395b35.png)

- Go to the general tab
![image](https://user-images.githubusercontent.com/26604242/142066233-48e49e06-c814-4c6a-95ae-bcf1c5ac6f96.png)

- You should see something like this, click on open anyway
![image](https://user-images.githubusercontent.com/26604242/142066465-9df552d3-331d-4204-bfaf-46f72b1693d4.png)

- On these popups, click on open
![image](https://user-images.githubusercontent.com/26604242/142066576-5008145a-3764-4cbe-b360-aa804b952945.png)

**Comment by annieappflowy** [comment]
thank you for asking and answering the question ❤️ 
we haven't paid to Apple so that's why, but we'll get one so this won't happen as long as we feel ready to serve end users.
