### ISSUE TITLE
[Bug] [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by dyrnq** [AppFlowy-IO/appflowy#180]
**Describe the bug**
run ./app_flowy on debian 11 report exception and  the interface is blank

```bash
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/appflowy/lib/libdart_ffi.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:19)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:23)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/init_sdk.dart:23)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/init_sdk.dart:19)
#9      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#10     AppLauncher.launch (package:app_flowy/startup/launcher.dart:36)
<asynchronous suspension>
``` 

**To Reproduce**
1. curl -O -fssL https://github.com/AppFlowy-IO/appflowy/releases/download/0.0.2/AppFlowy-linux-x86.tar.gz
2. mkdir /opt/appflowy && cd /opt/appflowy
3. tar -xvf AppFlowy-linux-x86.tar.gz
4. run `./app_flowy`

**Screenshots**
![Screenshot from 2021-12-19 15-05-03](https://user-images.githubusercontent.com/68039577/146666833-5089eece-2e09-4197-bd55-9aced179e707.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Browser: chrome
 - Version: Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**
None

**Comment by PabloCastellano** [comment]
I've hit the same issue. Looks like libdart_ffi requires `glibc >= 2.32` while this version is not available in some common linux distributions yet. In my case I'm using Linux Mint 20.1.

```
$ ldd /opt/AppFlowy/lib/libdart_ffi.so
/opt/AppFlowy/lib/libdart_ffi.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/AppFlowy/lib/libdart_ffi.so)
/opt/AppFlowy/lib/libdart_ffi.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/AppFlowy/lib/libdart_ffi.so)
	linux-vdso.so.1 (0x00007ffdb04ae000)
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fca0c063000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fca0bd8d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fca0bd72000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca0bd4f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fca0bc00000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca0bbfa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca0ba06000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fca0cb18000)
```

For the record, glibc 2.33 is available on Debian testing and Ubuntu 21.04:

```
$ rmadison libc6
 libc6 | 2.19-0ubuntu6    | trusty          | amd64, arm64, armhf, i386, powerpc, ppc64el
 libc6 | 2.19-0ubuntu6.15 | trusty-security | amd64, arm64, armhf, i386, powerpc, ppc64el
 libc6 | 2.19-0ubuntu6.15 | trusty-updates  | amd64, arm64, armhf, i386, powerpc, ppc64el
 libc6 | 2.23-0ubuntu3    | xenial          | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
 libc6 | 2.23-0ubuntu11.3 | xenial-security | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
 libc6 | 2.23-0ubuntu11.3 | xenial-updates  | amd64, arm64, armhf, i386, powerpc, ppc64el, s390x
 libc6 | 2.27-3ubuntu1    | bionic          | amd64, arm64, armhf, i386, ppc64el, s390x
 libc6 | 2.27-3ubuntu1.2  | bionic-security | amd64, arm64, armhf, i386, ppc64el, s390x
 libc6 | 2.27-3ubuntu1.4  | bionic-updates  | amd64, arm64, armhf, i386, ppc64el, s390x
 libc6 | 2.31-0ubuntu9    | focal           | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x
 libc6 | 2.31-0ubuntu9.2  | focal-updates   | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x
 libc6 | 2.31-0ubuntu9.4  | focal-proposed  | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x
 libc6 | 2.33-0ubuntu5    | hirsute         | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x
 libc6 | 2.34-0ubuntu3    | impish          | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x
 libc6 | 2.34-0ubuntu3    | jammy           | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x
```

```
$ rmadison libc6 -u debian
libc6      | 2.19-18+deb8u10     | oldoldoldstable     | amd64, armel, armhf, i386
libc6      | 2.24-11+deb9u4      | oldoldstable        | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
libc6      | 2.28-10             | oldstable           | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
libc6      | 2.31-13+deb11u2     | stable              | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
libc6      | 2.33-1              | testing             | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
libc6      | 2.33-1              | unstable            | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
libc6      | 2.34-0experimental1 | buildd-experimental | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
libc6      | 2.34-0experimental1 | experimental        | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
```

**Comment by MikeWallaceDev** [comment]
Thank you @dyrnq for reporting this, and you @PabloCastellano for reporting all of that information!
I will add a note in the installation page. There's not much we can really do at this point.

**Comment by valmormn** [comment]
Same problem here on Ubuntu! 💩

**Comment by MikeWallaceDev** [comment]
@valmormn which version of Ubuntu?

**Comment by zicklag** [comment]
I'm getting the same issue on Pop!_OS ( Ubuntu ) 20.04 LTS.

Is it possible we could reduce the required glibc version to the older version, or otherwise bundle glibc 2.32 in the `lib` folder with the distribution?

**Comment by changchichung** [comment]
same issue in ubuntu 22.04

**Comment by valmormn** [comment]
> @valmormn which version of Ubuntu?

Ubuntu 20.04 LTS

**Comment by GoodM4ven** [comment]
I did this on Ubuntu 22.04.

- When I first launched the Linux built app, got the blank window.
- Ran the app through the terminal: `~/Downloads/AppFlowy/app_flowy` and saw the `libssl` whatever not being found.
- Then ran `ldd ~/Downloads/AppFlowy/lib/libdart_ffi.so` which was first read to reach the error and shown the missing 2 library links, which Ubuntu has new versions of:
  ```bash
  libssl.so.1.1 => not found
  libcrypto.so.1.1 => not found
  ```
- So now I needed to see if the exact versions are available somewhere, and ran `sudo find / -name "libssl*"`, which had found that that `torguard` app has them in its `lib` directory!
- I also understood that `LD_LIBRARY_PATH` variable is used to find those libraries and initially echoing it has an empty result!
- So I first tried to run the app counting those libraries in `LD_LIBRARY_PATH="/opt/torguard/lib" ~/Downloads/AppFlowy/app_flowy` and it worked!
- Now I copied them the 2 libraries to `/usr/local/lib`, then touched 2 conf files for them like so:
  - `sudo nano /etc/ld.so.conf.d/libcrypto.so.1.1.conf` with only `/usr/local/lib` inside.
  - `sudo nano /etc/ld.so.conf.d/libssl.so.1.1.conf` with only `/usr/local/lib` inside.
- Now just had to `export LD_LIBRARY_PATH="/usr/local/lib`, I guess, then run `sudo ldconfig` to save it all! 😋

Credits: dave1 and HeadOnFire (from Laravel community)
