### ISSUE TITLE
[Bug] the data property including time default time 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1800]
### Bug Description

<img width="270" alt="image" src="https://user-images.githubusercontent.com/12026239/216755433-f4b6dfa8-5a56-440f-99ac-f9b4e4acfdf8.png">

After toggling on "Include time", the time field is prefilled a time as a placeholder.
If the user doesn't enter the edit mode to update it, I feel it should just auto-fill time with this placeholder time rather than not updating the time?

As seen in the screenshot, if I don't edit the time field and close the menu instead, the property value should show Feb 07, 2023 13:00 rather than Feb 07, 2023. This is because I already toggled on "Include time" even though I have not edited the time field.

### How to Reproduce

As described in the bug description

### Expected Behavior

As described in the bug description

### Operating System

Windows 10

### AppFlowy Version(s)

main branch

**Comment by richardshiue** [comment]
Gentle ping @annieappflowy

**Comment by annieappflowy** [comment]
I'd prefer to set the current time when includeTime is toggled and the user doesn't enter the edit mode to change it. Well, this is just my preference as a user.
