### ISSUE TITLE
[FR] Enable users to add a new property through Settings in Kanban Board

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1801]
### Description

<img width="735" alt="image" src="https://user-images.githubusercontent.com/12026239/216757783-921f172b-5fce-4b4e-badd-c391581389aa.png">
<img width="202" alt="image" src="https://user-images.githubusercontent.com/12026239/216757938-508c8473-a631-4fae-b481-9c9d10277dc1.png">

At the moment, I can add a new property through viewing a card details.
I'd like to have an option to manage properties through the Settings in Kanban Board
For example, I can add a new property by going to the Settings and clicking on Properties where I can see an option "+ New Property"

### Impact

Kanban board users who manage properties through Settings

**Comment by squidrye** [comment]
Hi @annieappflowy , I would love to take on this issue if it's still open.

https://user-images.githubusercontent.com/84044317/226199043-5027d14d-79a8-47f9-9201-4281c878d635.mp4

Would this be desired effect?

**Comment by annieappflowy** [comment]
Hi @squidrye , if you have implemented this issue, please submit a PR and give up another one that was also assigned to you!
Thank you for offering the help!

**Comment by squidrye** [comment]
I'll be working on the assigned issue @annieappflowy, will leave this one for other people.
