### ISSUE TITLE
[Bug] Math Equation would be null.

### ISSUE THREAD

**Issue by huang12zheng** [AppFlowy-IO/AppFlowy#1802]
### Bug Description

Left (Left(docId: KAqvylhRb-
snapshot: {"document":{"type":"editor","children":[{"type":"text","delta":[{"insert":"fdgfd"}]},{"type":"math_equation","attributes":{"math_equation":null}},{"type":"text","delta":[{"insert":"fdsaf"}]},{"type":"text","delta":[{"insert":"fdsaf"}]},{"type":"text","delta":[{"insert":"aa"}]},{"type":"math_equation","attributes":{"math_equation":"E"}},{"type":"text","delta":[{"insert":"dfaf"}]},{"type":"math_equation","attributes":{"math_equation":"E"}},{"type":"text"}]}}
))

### How to Reproduce

https://user-images.githubusercontent.com/28038074/216769677-f23afaa1-a6e7-487a-9814-8ca33c77ded4.mp4

### Expected Behavior

{"type":"math_equation","attributes":{"math_equation":null}} 
to be 
{"type":"math_equation","attributes":{"math_equation":""}}

---
or no render error

### Operating System

Darwin13.1（version 22C65）

### AppFlowy Version(s)

1.0.0+1

### Additional Context

PS: I don't know what flutter and rust do when modifying values. Maybe write_snapshot and document_rev_table, and then pull the data out of it. But I spent a lot of time trying to figure it out.
Because of FFI, I can't debug directly, which is a little sad

**Comment by LucasXu0** [comment]
Hi, @huang12zheng. Thanks for reporting.

You can debug the Rust code by executing `AF-desktop: Debug Rust`.
<img width="232" alt="Screenshot 2023-02-05 at 16 38 33" src="https://user-images.githubusercontent.com/11863087/216809564-4467cfc3-ecbd-41e1-8a0d-353b854814f7.png">

**Comment by annieappflowy** [comment]
Is this resolved? @huang12zheng

**Comment by huang12zheng** [comment]
@annieappflowy the problem of this issue is relation to #1806

On the development tips, LucasXu0 tells the method, I don't know how to try.

**Comment by LucasXu0** [comment]
Here're the steps.

1. Get the process id of AppFlowy
2. Executing the `AF-desktop: Debug Rust` task.
3. Input the process id.
4. Set a breakpoint to debug the code.
