### ISSUE TITLE
[Bug]  Help & Support Icon text not clear in the Dark mode

### ISSUE THREAD

**Issue by mayura-alahakoon** [AppFlowy-IO/AppFlowy#1807]
### Bug Description

![Screenshot from 2023-02-06 05-10-47](https://user-images.githubusercontent.com/48531182/216852594-bf366763-9c60-4519-9d55-228423776177.png)

in light mode, this one better but when dark mode, it's display like this,
![Screenshot from 2023-02-06 05-04-42](https://user-images.githubusercontent.com/48531182/216852664-0396fbd2-439d-4d87-bc7e-16ae2f842b97.png)

### How to Reproduce

I think this is a small bug. We can change font color or reduce background color. I suppose

### Expected Behavior

In the dark mode,  that Help & Support text should be more clear.

### Operating System

Pop!_OS 22.04 LTS x86_64

### AppFlowy Version(s)

app_flowy 1.0.0.1

### Screenshots

![Screenshot from 2023-02-06 05-10-47](https://user-images.githubusercontent.com/48531182/216852859-b724dd5d-4eed-4a74-8724-9f1cda1038e9.png)  <<<----- Light Mode

![Screenshot from 2023-02-06 05-04-42](https://user-images.githubusercontent.com/48531182/216852878-afd6b748-0669-4ef7-9290-33d7494928ed.png) <<<------ Dark mode

**Comment by annieappflowy** [comment]
Part of https://github.com/AppFlowy-IO/AppFlowy/issues/1671

**Comment by mayura-alahakoon** [comment]
Ok I'll check that
