### ISSUE TITLE
[FR] About Sync

### ISSUE THREAD

**Issue by huabin** [AppFlowy-IO/appflowy#181]
**1~3 main use cases of the proposed feature**
I checked appflowy [roadmap](https://trello.com/c/7ymtyfQd/1-sync) on trello.com, and I would like to ask what way it will be implemented? Will it use a third-party  storage drive like Google drive, or will appflowy have a built-in sync service, or will it allow users to set up a hosting of their own?

**what types of users can benefit from using your proposed feature**
Everyone who uses appflowy

**Additional context**
I would prefer users could use self-hosting.

Thank you.

**Comment by huabin** [comment]
BTW, could you please move roadmap from Trello to GitHub, thank you.

**Comment by MikeWallaceDev** [comment]
Hello @huabin ! Thank you for your interest in AppFlowy, we're happy to see you here :)
Unfortunately this is not a feature request, it's a question. Can you please move this to the [Discussions](https://github.com/AppFlowy-IO/appflowy/discussions) section?  I'd do it for you but then I would own the question, not you.

I'm closing this as it's not an issue.

**Comment by huabin** [comment]
Got it. 
Thx.
