### ISSUE TITLE
[Bug] No PrimaryScrollController widget ancestor could be found

### ISSUE THREAD

**Issue by keanallen** [AppFlowy-IO/AppFlowy#1815]
### Bug Description

When I **re-order** or **long press** any board, it will display an error on the active board saying:

```
No PrimaryScrollController widget ancestor could be found starting from the
context that was passed to PrimaryScrollController.of().
This can happen because you are using a widget that looks for a
PrimaryScrollController ancestor, but no such ancestor exists.
```

### How to Reproduce

Build an app with appflowy on windows desktop, and long press or drag one board to another.

### Expected Behavior

It should drag without displaying error

### Operating System

Windows 11 x64

### AppFlowy Version(s)

0.0.9

### Screenshots

![image](https://user-images.githubusercontent.com/45480782/217157524-59b440d0-061a-46ac-9392-69477afdf7be.png)

### Additional Context

```
Flutter 3.7.0 • channel stable
```

**Comment by appflowy** [comment]
@keanallen Thank you for reporting this. I will fix it

**Comment by richardshiue** [comment]
This issue no longer exists. Please use the latest commit rev on the appflowy board package
