### ISSUE TITLE
[FR] Hide "No Status" Stack on Kanban Board

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1821]
### Description

"I don't plan on utilising the No Status block 
I'm a bit of a perfectionist when it comes to organising things like to do lists so I'd rather not have something like that there, if I'm not going to use it. I would hide it completely"

### Impact

Kanban Board Users

### Additional Context

Can this be a good first-timer issue? @appflowy

**Comment by zoli** [comment]
Isn't better to have a show property on groups in Fron-eend side so the user can hide any group which she/he wants?

**Comment by annieappflowy** [comment]
@zoli , I guess it's a good direction to solve this.

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/1733

**Comment by annieappflowy** [comment]
Scope:
- [ ] The ability to hide the No Status / No Select stack
- [ ] Show the number of cards under No select
- [ ] Can display the list of no status cards in a dropdown list like how No Date in the calendar view works
- [ ] Click on an item to trigger the card detail page

**Comment by annieappflowy** [comment]
<img width="480" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7089f10b-f925-4b5c-b4a8-dbfb75d444bb">
<img width="313" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/182e7620-fc7a-4ec4-9830-1a709f81e207">
