### ISSUE TITLE
[FR] Enable users to directly delete a stack on Kanban Board 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1822]
### Description

Users can delete a stack more easily without going into the group-by column to delete the value
<img width="267" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/0cad8799-cb1a-4e1b-94df-3530b3c7c05a">
<img width="418" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/a88f3d45-adc0-4e8a-88bc-835adffe499c">

### Impact

Kanban Board Users

**Comment by annieappflowy** [comment]
Can this be a good first-timer issue? @appflowy

**Comment by olaitanade** [comment]
Hi @annieappflowy , can i be assigned this issue?

**Comment by richardshiue** [comment]
Hi @olaitanade this issue is already being tackled and should be in the next release. Please look for another issue and we'd be happy to assign it to you.

**Comment by olaitanade** [comment]
Thank you, I'd do just that. Cheers
