### ISSUE TITLE
[FR] Improve editing and navigating shortcuts with CTRL

### ISSUE THREAD

**Issue by cb0s** [AppFlowy-IO/AppFlowy#1825]
### Description

While testing this tool for the first time, the first thing I noticed is that I cannot delete entire words by pressing CTRL + Backspace which seems to be the standard shortcut for this feature. Although being a simple request I have to say that this is an important feature for me for example and I suppose there are numerous other possible users out there who might enjoy this being implemented. 😄
Similarly, I cannot select entire words by pressing CTRL and the arrow keys. Instead it works more like HOME/POS1 or END. There might be similar navigation and editing flows, but those were these most noticable for a "new user" (or tester).

I know this tool is still in the incubator state/full development, but I wanted to share my first experiences with you to hopefully be able to enhance this cool project!

### Impact

Imo, this would improve the workflow by alot. Many times, deleting words or partial sentences and jumping back to add a missing comma, are very important features.

Although, as stated above, being a simple feature, I fear that exactly those are the ones, which make this tool (at least for me) at this stage still unpractical for daily use.

### Additional Context

I tested this in AppFlowly in v0.0.9.1 on Windows 10. I hope, I didnt miss an issue proposing a similar feature...

EDIT: I just saw #75 , however, this only proposes CTRL + Backspace. I think multiple word selection would be the next step.

**Comment by LucasXu0** [comment]
Thanks for reporting. Hey, @MayurSMahajan, Can you implement these shortcut keys together?

**Comment by MayurSMahajan** [comment]
Sure! Working on it.

**Comment by LucasXu0** [comment]
Hi, @cb0s. 

CTRL + Arrow Keys are to make the cursor jump to the beginning or the end.
CTRL + ALT(OPTION) + Arrow Keys are to select a word.
