### ISSUE TITLE
[FR] Navigate through Grid items

### ISSUE THREAD

**Issue by Ascarbek** [AppFlowy-IO/AppFlowy#1829]
### Description

Grid item values can be modified by clicking on them. When user clicks away or presses Esc key the "selected" border should stay on but the input element should be replaced by other element (span, div). In this state user should be able to select other grid items (navigate) using up, down, left, right arrow buttons. Pressing Spacebar or Enter key should change to "value editing" mode.

### Impact

frontend development of appflowy_tauri

**Comment by mikiastilahun** [comment]
@appflowy Can you confirm the requirements in this card are accurate? 

Thanks,

**Comment by appflowy** [comment]
> @appflowy Can you confirm the requirements in this card are accurate?
> 
> Thanks,

Yep. It's correct.
