### ISSUE TITLE
[FR] supports file upload

### ISSUE THREAD

**Issue by xiamaocheng** [AppFlowy-IO/AppFlowy#1830]
### Description

supports file upload to AppFlowy

### Impact

adjust classic style

**Comment by annieappflowy** [comment]
Thanks for submitting a feature request!
I'd need a little bit more details about your needs. 
Do you want to upload files to a document page? Or to a Grid or Kanban Board?

**Comment by MrZang101** [comment]
Hello, would be nice to implement it exemple in the kanban or Board we want to make a section name "invoice" so we want to upload the file there.

**Comment by oppZ** [comment]
uploading files to a document page would be nice too

**Comment by digisomni** [comment]
This has a good opportunity to beat out Nextcloud as a whole-org suite if file upload and permissioned sharing is also well handled.

**Comment by dasinking** [comment]
I support this feature request. Appflowy looks really good, but the kanbas board is no use for me, as long as I'm unable to attach any files to the notes.

For example: I want to create a board for every university course I take and attach PDF files to notes, which I have to read and work through.

In the meantime I'll use Planka, but longterm Appflowy seems more capable and complete. Thank you very much for developing :)

**Comment by pintom** [comment]
Is there any update on this, and would any assistance be useful? Thank you

**Comment by Xazin** [comment]
> Is there any update on this, and would any assistance be useful? Thank you

Hey, thanks for your interest, we will support file upload in database at latest in version 0.6.9.

We already have file upload in documents. 🙏

**Comment by annieappflowy** [comment]
Supported

https://github.com/user-attachments/assets/6ec01a12-f6de-4e5a-a1ca-14d953724aa5
