### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by saegl5** [AppFlowy-IO/AppFlowy#1856]
### Bug Description

Opened a board, but received an error: \
msg: "OTError { code: IncompatibleLength, msg: \"Expected: 1, but received: 0 \" }"

### How to Reproduce

Open a board

### Expected Behavior

Board opens

### Operating System

macOS 13.2

### AppFlowy Version(s)

0.1.0.1

### Additional Context

My board contained blocks with lots of text

**Comment by saegl5** [comment]
I tried duplicating the board, but nothing happens. \
I also tried deleting and restoring the board, but the error persists. \
Now, I do back up the data file frequently, however I don't know how to properly restore such a file.
Altogether, I am in limbo~~~

**Comment by saegl5** [comment]
update: I *was* able to restore an older version of the board from an older backup of the data directory
at least to me, this isn't a solution, but it *is* better than nothing

a potential solution could have been if the feature, "Restore corrupt data from snapshots," introduced in [v0.0.9.1](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.0.9.1) worked for me, given that I use v0.1.0.1 \
...perhaps the feature is not as seamless as I expected it to be?

a potential fallback solution---thinking ahead now---could be not to have to quit the application for macs to be able to backup the data directory in time machine

**Comment by annieappflowy** [comment]
@saegl5 , thanks so much for all the hard work and feedback. We'll incorporate your input to see how this solution can be improved.
