### ISSUE TITLE
[Bug]  AppFlowy installed via flatpak miss required dependencies

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1860]
### Bug Description

<img width="565" alt="Screenshot 2023-02-15 at 14 09 12" src="https://user-images.githubusercontent.com/11863087/218946629-2a0f5e36-1541-422f-bfae-01be05b1d241.png">

### How to Reproduce

Install AppFlowy via flatpak.

### Expected Behavior

anything should be fine.

### Operating System

Fedora

### AppFlowy Version(s)

0.1.0

**Comment by Mo-Sense** [comment]
Same for me, but on KDE Neon 5.27.  Except I believe the AppFlowy version is 0.0.9, not 0.1.0.  Flatpak version 1.12.7.
```
AppFlowy - Open Source Notion Alternative

          ID: io.appflowy.AppFlowy
         Ref: app/io.appflowy.AppFlowy/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.9
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 55.9?MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: df5e19d9bbfc49b666700edeb08529bc8064abce328cd6bdcee9b35db5241baf
      Parent: 8ba086e2858f2cc5bfd6bcfb3cf1fb955e1c15b886462edffcd24b77b80a3c73
     Subject: chore: release 0.1.0 (d29322bc)
        Date: 2023-02-13 02:10:46 +0000
```

**Comment by justresisting** [comment]
I am running Solus Budgie. Downloaded AppFlowy sometime last year and finally got around to trying it out and get the following errors when running it via Flatpak.  

flatpak run io.appflowy.AppFlowy
Gtk-Message: 03:22:43.281: Failed to load module "appmenu-gtk-module"
Gtk-Message: 03:22:43.281: Failed to load module "appmenu-gtk-module"
Gtk-Message: 03:22:43.281: Failed to load module "appmenu-gtk-module"
Gtk-Message: 03:22:43.356: Failed to load module "canberra-gtk-module"
Gtk-Message: 03:22:43.357: Failed to load module "canberra-gtk-module"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_stream_port (package:appflowy_backend/ffi.dart)
#5      set_stream_port (package:appflowy_backend/ffi.dart)
#6      FlowySDK.init (package:appflowy_backend/appflowy_backend.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:24)
<asynchronous suspension>
#8      AppLauncher.launch (package:app_flowy/startup/startup.dart:124)
<asynchronous suspension>
#9      FlowyRunner.run (package:app_flowy/startup/startup.dart:64)
<asynchronous suspension>
#10     main (package:app_flowy/main.dart:25)
<asynchronous suspension>

**Comment by LucasXu0** [comment]
Hey, @justresisting. I think @rileyhawk1417 has fixed it. Can you try reinstalling it via flatpak?

**Comment by justresisting** [comment]
> Hey, @justresisting. I think @rileyhawk1417 has fixed it. Can you try reinstalling it via flatpak?

It's fixed.

**Comment by LucasXu0** [comment]
Great. I will close this issue.
