### ISSUE TITLE
[FR] The mouse swipes too slowly

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#1861]
### Description

The mouse swipes too slowly，
Hope to improve

### Impact

1.0

**Comment by LucasXu0** [comment]
Hey, @enomothem. 

> The mouse swipes too slowly.
Do you mean that dragging the window is slow, or resizing it is slow?

**Comment by enomothem** [comment]
Swipe up and down the page
I'm referring to the wheel in the middle of the mouse

**Comment by LucasXu0** [comment]
> I'm referring to the wheel in the middle of the mouse

Got it.
