### ISSUE TITLE
[FR] Different Users

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [AppFlowy-IO/AppFlowy#1874]
### Description

A simple way of having different users could benefit teams working on appflowy out there. The main uses would be when you want someone to be tagged for example, so that they see a document. Lets admit you work with appflowy as a team. You can synchronize your documents already (for example with a synology device or any other cloud syncing technology), and you would like a user to be notified you're tagging them. Without doing something too intricate, you could simply have a little notification/bell icon, that contains the places where you've been tagged and that you haven't tagged as read. This would work with usernames, but might need a UserID refactoring part, where you have a "static" user ID and name list or something, to know which users you can tag; list that would be shared with the documents across all users. 

### Impact

This alone would benefit teams that work together with appflowy, and need a communication flow that goes back and forth easily.

**Comment by Jabe64** [comment]
Yes it would be awesome to be able to comment different projects like Monday.com does.

And we could also imagine other collaborative communication tools, for example to be able to create a new page type (on top of the classic Document/Grid/Board/Calendar etc) called "chat channel" or "Comments" and inside of it messages will appear with usernames and time of post and it will allow AppFlowy to replace Slack 🤯

**Comment by annieappflowy** [comment]
#3899  comments planned in Q3
We supported team collaboration
