### ISSUE TITLE
[FR] rewrite some part of appflowy editor

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1881]
### Description

Since we move the appflowy_eidtor from appflowy as an individual repo, we remove the codes that their developer didn't sign the document.

The removed codes include:
* ~~support markdown link feature, like converting `[AppFlowy](appflowy.io)` to [AppFlowy](appflowy.io)~~
* ~~add numbered list entry to the slash menu.~~
* ~~support markdown image feature.~~
* remove the slash keyword `/` when clicking the slash menu item.
* double asterisks or underscores to bold text.

### Impact

It's a necessary task before releasing the new appflowy editor.

**Comment by hyj1204** [comment]
Hi Lucas,
Could you assign it to me? Thanks

**Comment by LucasXu0** [comment]
Okay.

**Comment by hyj1204** [comment]
Code has been merged
