### ISSUE TITLE
[Bug] AppFlowy Editor Upgrade to 3.7.x

### ISSUE THREAD

**Issue by jenishkumar88** [AppFlowy-IO/AppFlowy#1883]
### Bug Description

Please update new version compatible with newer flutter version 3.7.3 or later 

### How to Reproduce

i have one flutter-flow project that used flutter version 3.7.3 (was using 3.3.4 perviously )

i am using app_flowy editor as custom widget in my flutter-flow project 

but now i can not run project due to version conflict

so please update flutter version because i can not downgrade flutter version in flutterflow 

### Expected Behavior

i have one flutter-flow project that used flutter version 3.7.3 (was using 3.3.4 perviously )

i am using app_flowy editor as custom widget in my flutter-flow project 

but now i can not run project due to version conflict

so please update flutter version because i can not downgrade flutter version in flutterflow 

### Operating System

Flutter

### AppFlowy Version(s)

0.0.9

**Comment by rileyhawk1417** [comment]
@jenishkumar88 currently it's not possible to upgrade it to flutter 3.7 there are other dependencies that will break if the flutter version is at 3.7

**Comment by jenishkumar88** [comment]
@rileyhawk1417 okay is there any way i could fix this issue ?

**Comment by annieappflowy** [comment]
@LucasXu0 , please review this request

**Comment by jenishkumar88** [comment]
@rileyhawk1417 

i can not downgrade flutter version in flutterflow
so my whole project is struck due to this

**Comment by literalEval** [comment]
@annieappflowy can we migrate our project to flutter 3.7 ? I can perform the migration.

**Comment by jenishkumar88** [comment]
@annieappflowy @literalEval @factotvm @rileyhawk1417 
it would be great if you can migrate to flutter 3.7

**Comment by literalEval** [comment]
Please assign this to me. I can do the migration.

**Comment by jenishkumar88** [comment]
@annieappflowy @rileyhawk1417 @factotvm 
can you please assign this issue to @literalEval please

**Comment by LucasXu0** [comment]
Hey, @literalEval. I assigned it to you. We also need to update the flutter version of the main project(appflowy) not only the flutter version of the appflowy editor.

**Comment by literalEval** [comment]
Sure.

**Comment by LucasXu0** [comment]
@literalEval @Akshay-akkay  By the way, there's a related PR. https://github.com/AppFlowy-IO/AppFlowy/pull/1895.

**Comment by jenishkumar88** [comment]
@LucasXu0 @annieappflowy @rileyhawk1417 @literalEval 
Any update 
when i can expect new version ?
Sorry to keep disturbing but my whole project is stopped due to this 
i hope you can understand

**Comment by literalEval** [comment]
Will try to finish before this weekend. Sorry, was busy in exams.

**Comment by LucasXu0** [comment]
@jenishkumar88. I can create a new branch for updating appflowy_editor to 3.7.x. After that, you can depend on it using git.

**Comment by LucasXu0** [comment]
Hey, @jenishkumar88. Here's the lastest version for Flutter 3.7.5.

```
  appflowy_editor:
    git:
      url: https://github.com/AppFlowy-IO/AppFlowy.git
      ref: 6bbef2310a94431a0811f7040403ce73e46bb2f4
      path: frontend/appflowy_flutter/packages/appflowy_editor
```

**Comment by jenishkumar88** [comment]
Okay let me checkout it

In Flutterflow i can not use library that has defined git path 
i have to use versioning system for this 

[Screenshot 2023-03-06 at 12 52 23 PM](https://user-images.githubusercontent.com/35342916/223044264-8fc8a6d3-d5a8-4272-8e43-546fdd464df3.png)

**Comment by LucasXu0** [comment]
@jenishkumar88. Okay. How about trying this one? 0.1.0

**Comment by jenishkumar88** [comment]
@LucasXu0 @annieappflowy @rileyhawk1417 @literalEval 
it worked 
Thanks you all made my day
