### ISSUE TITLE
[FR] More flexible date parsing

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#1887]
### Description

Currently, a placeholder is required to instruct users to input time values in a very specific way (12 hour or 24 hour, with strict spacing). It would be better if the time string were better parsed, ordered in complexity:

- leading, trailing, multiple spaces/tabs (`          6:00  am  ` -> 06:00)
- am, pm with and without period, capitalized or not (am, a.m., AM, A.M.)
- missing spaces or colons (`6 00` -> 06:00, `6:00pm`)
- a single number to specify an hour (`6` -> 06:00, `17` -> 17:00, `6 pm` -> 18:00)
- ISO-8601
- words (noon, midnight, eight, six o'clock, half past one, twelve fifty-five)

### Impact

Users who enter dates in databases

**Comment by Shreesh09** [comment]
can I work on this?
