### ISSUE TITLE
[FR] Sucessfully to build workable version for windows (Rust target: x86_64-pc-windows-msvc), request to contribute

### ISSUE THREAD

**Issue by pdckxd** [AppFlowy-IO/appflowy#19]
**1~3 main use cases of the proposed feature**
Can I issue pull request to support x86_64-pc-windows-msvc target for rust-lib?

**what types of users can benefit from using your proposed feature**
n/a

**Additional context**
n/a

![image](https://user-images.githubusercontent.com/1890394/142132615-72681d21-ad3d-4d25-a6ed-f8fae3c54c38.png)

**Comment by annieappflowy** [comment]
100% 
You rock!!!!

**Comment by appflowy** [comment]
@pdckxd Wow, amazing! Open new PR, please!

**Comment by pdckxd** [comment]
Sure, I will file PR later today after work.

**Comment by pdckxd** [comment]
hi @appflowy, can you help to review?

PS:  didn't get enough time to verify on MacOS.

**Comment by pdckxd** [comment]
Thanks appflowy. Closing this issus
