### ISSUE TITLE
[FR] Fonts Settings

### ISSUE THREAD

**Issue by dxps** [AppFlowy-IO/AppFlowy#190]
**Use Cases of the proposed feature**
As a writer, I want to be able to use my preferred fonts for both normal and monospaced (inline code or code blocks), including their sizes.

**What types of users can benefit from using your proposed feature**
People with specific preferences, maybe slightly OCD driven ones like myself :yum: 

**Additional Context**
At the time of this writing, this is how ver. 0.0.2 looks like on Pop!_OS (Ubuntu based) ver. 21.10 distro.
It looks quite good for such an initial release.
It seems that Ubuntu font is being used for both regular and monospaced formats, although the monospaced format should use a monospaced font, and the size of it should be increased.

![image](https://user-images.githubusercontent.com/14140226/147054040-6eb9c66f-e90a-4f78-9309-3a7c0a8386ce.png)

Thank you for doing and sharing this! :pray: 
Just discovered this morning and planning to contribute since it's using two of my favorite programming languages and frameworks. :blush:

**Comment by annieappflowy** [comment]
Hi @dxps , now you can choose any Google Font in AppFlowy using the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases).
You'd also be surprised about how much improvement we've made since v0.0.2

**Comment by dxps** [comment]
Thanks, Annie! :pray: 
I'll give it a try again.

All the best with the app!
