### ISSUE TITLE
[Question] Built for teams ?

### ISSUE THREAD

**Issue by apcloic** [AppFlowy-IO/AppFlowy#1903]
### Bug Description

Hi,

On the website, AppFlowy claims to be "built for teams" but afaik it works as a single user / desktop app with no server component.
Did I miss something ?
How could I work with / collaborate my other teammates ?
Regards,

### How to Reproduce

try to work with teammates

### Expected Behavior

"share with" button, add user or something like this.

### Operating System

Windows 10

### AppFlowy Version(s)

latest

### Additional Context

How to work with Appflowy as a team ?

**Comment by MayurSMahajan** [comment]
CC: @annieappflowy

**Comment by annieappflowy** [comment]
Hi @apcloic , thanks for checking out AppFlowy. We are working towards supporting multi-users collaboration. The development is scheduled to start in Q3. You can also take a look at our roadmap to see what we are up to: https://github.com/AppFlowy-IO/AppFlowy/discussions/1715
Please let me know if you have more follow-up questions or feedback.
