### ISSUE TITLE
[Bug] Blank (white) page on startup

### ISSUE THREAD

**Issue by Dieterbe** [AppFlowy-IO/AppFlowy#1909]
### Bug Description

Hi, i built appflowy from scratch on arch linux using the [aur package](https://aur.archlinux.org/packages/appflowy-git)
Upon startup, i just get a white page, seems similar to #65 

### How to Reproduce

build from source and run it

### Expected Behavior

i see more than just blank

### Operating System

Arch linux

### AppFlowy Version(s)

i've been seeing this with main branch today, but also 10 days ago

### Screenshots

![image](https://user-images.githubusercontent.com/20774/222366734-5c207453-04e7-4f5b-ac38-06b8687b9afd.png)

**Comment by annieappflowy** [comment]
Hi @Dieterbe , plz take a look at this doc: https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux
Search libssl

**Comment by Dieterbe** [comment]
Hi Annie,
so that doc mentions this error:
```
Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory.
```
I do not see this error at runtime (or is this supposed to be a build-time error? my build seems to have completed successfully, maybe i missed such a message during build, but i imagine a failure like this would break a build)
and also, i do seem to have the required ssl library installed:
```
/usr/lib/libssl.so
/usr/lib/libssl.so.1.1
/usr/lib/libssl.so.3
/usr/lib/libssl3.so
/usr/lib/openssl-1.1/libssl.so
/usr/lib/openssl-1.1/pkgconfig/libssl.pc
/usr/lib/pkgconfig/libssl.pc
~ ❯❯❯ pacman -Qs libssl
local/openssl 3.0.8-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
local/openssl-1.1 1.1.1.t-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
```

**Comment by LucasXu0** [comment]
Hey, @Dieterbe. Are there no errors complaining at runtime? I only know that AppFlowy will run into a blank page if the libssl is missing.

> Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory.

By the way, this is a runtime error.

**Comment by MithicSpirit** [comment]
@Dieterbe can you try to run `ldd -v /opt/appflowy-git/lib/libdart_ffi.so` and send the output here (ideally [spoilered](https://stackoverflow.com/questions/32814161/how-to-make-spoiler-text-in-github-wiki-pages) to prevent spam, or in a pastebin)? It should provide info on the necessary shared libraries.

**Comment by Dieterbe** [comment]
First of all, thanks to all of you for being so helpful, really appreciate it.
I confirm that there are no runtime errors or output of any kind when running the program,
until I close the window. At that point I do see this (may be a separate issue)
```
(appflowy_flutter:38317): GLib-GObject-WARNING **: 09:46:39.312: ../glib/gobject/gsignal.c:2772: instance '0x5565aced11b0' has no handler with id '104'
[1]    38317 segmentation fault (core dumped)  appflowy_flutter
```

Output of the ldd command (and `ls -l` while we're at it) is here:
<details>
~ ❯❯❯ ldd -v /opt/appflowy-git/lib/libdart_ffi.so
ldd: warning: you do not have execution permission for `/opt/appflowy-git/lib/libdart_ffi.so'
	linux-vdso.so.1 (0x00007ffe5f5c9000)
	libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f4ee7d60000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f4ee7800000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f4ee93ac000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f4ee7c78000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f4ee7619000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f4ee93f4000)

	Version information:
	/opt/appflowy-git/lib/libdart_ffi.so:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libcrypto.so.3 (OPENSSL_3.0.0) => /usr/lib/libcrypto.so.3
		libssl.so.3 (OPENSSL_3.0.0) => /usr/lib/libssl.so.3
		libgcc_s.so.1 (GCC_4.2.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.9) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.18) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.28) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libssl.so.3:
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libcrypto.so.3 (OPENSSL_3.0.3) => /usr/lib/libcrypto.so.3
		libcrypto.so.3 (OPENSSL_3.0.0) => /usr/lib/libcrypto.so.3
	/usr/lib/libcrypto.so.3:
		libc.so.6 (GLIBC_2.15) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.16) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libgcc_s.so.1:
		libc.so.6 (GLIBC_2.35) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_ABI_DT_RELR) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.35) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.34) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
~ ❯❯❯ ls -l /opt/appflowy-git/lib/libdart_ffi.so
-rw-r--r-- 1 root root 22455160 Mar  2 14:19 /opt/appflowy-git/lib/libdart_ffi.so
</details>

**Comment by Anvith00** [comment]
Greetings @Dieterbe , are you perhaps missing the keybinder-3 dependency?
If yes, you would have to install keybinder-3 in your distribution. Please try:
```bash
sudo pacman -S libkeybinder3-0
```

**Comment by MithicSpirit** [comment]
I get the same GLib warning on my machine (where appflowy works fine), so that's not the issue I think. 

As for libkeybinder it is already a dependency of the AUR package, so it should already be installed (also, on Arch, the package is named `libkeybinder3` instead of `libkeybinder3-0`).

@Dieterbe are you on X.org or Wayland?

**Comment by MithicSpirit** [comment]
Did some testing around in a Docker container and found out that the issue is a missing `xdg-user-dirs` dependency (had to compare with the `appflowy-bin` package to find out, so kudos to them). I've added this now, so @Dieterbe, if you could please try rebuilding now (or just installing that dependency manually) and seeing if it works, that would be appreciated.

**Comment by lariane-guerra** [comment]
I have a similar problem.  I want to use the AppFlowy, i installed with POPos store, but i had a blank white screen on startup. 

Can one help me?

**Comment by lariane-guerra** [comment]
> Hi @Dieterbe , plz take a look at this doc: https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux Search libssl

I try to install the libssl, but it dosent help for me

**Comment by Dieterbe** [comment]
@Anvith00 I have libkeybinder3 installed (but not libkeybinder2)
```
~ ❯❯❯ pacman -Ss libkeybinder
extra/libkeybinder3 0.3.2-4 [installed]
    A library for registering global keyboard shortcuts
community/libkeybinder2 0.3.1-4
    Library for registering global keyboard shortcuts
```

I tried installing libkeybinder2 as well, but that did not fix the issue.

@MithicSpirit I run X.org (xorg-server 21.1.7), and your fix of installing xdg-user-dirs fixed it!! thank you !

**Comment by MithicSpirit** [comment]
> I have a similar problem. I want to use the AppFlowy, i installed with POPos store, but i had a blank white screen on startup.

@lariane-guerra try launching it from the terminal and look to see if there is any output. If there is any please post it here. Also, make sure that the binary `xdg-user-dir` exists on your system.

---

> So, we now have 2 options, I think:
A) change this issue into "appflowy does not gracefully handle absense of xdg-user-dirs, it should show an error or something"
B) there is no issue here, since everything works if the build instructions are followed.

If option A is easy to implement (which I suspect it is—just hardcode default directories relative to `$HOME` if `xdg-user-dirs` is not found) then I think that it would be the best solution. Otherwise, I think that a warning similar to the ssl one should be added to the instructions stating that the `xdg-user-dir` executable is necessary (and mentioning the corresponding package on each relevant distro).

**Comment by lariane-guerra** [comment]
> > I have a similar problem. I want to use the AppFlowy, i installed with POPos store, but i had a blank white screen on startup.
> 
> @lariane-guerra try launching it from the terminal and look to see if there is any output. If there is any please post it here. Also, make sure that the executable `xdg-user-dir` is in your `$PATH`.
> 
> > So, we now have 2 options, I think:
> > A) change this issue into "appflowy does not gracefully handle absense of xdg-user-dirs, it should show an error or something"
> > B) there is no issue here, since everything works if the build instructions are followed.
> 
> If option A is easy to implement (which I suspect it is—just hardcode default directories relative to `$HOME` if `xdg-user-dirs` is not found) then I think that it would be the best solution. Otherwise, I think that a warning similar to the ssl one should be added to the instructions stating that the `xdg-user-dir` executable is necessary (and mentioning the corresponding package on each relevant distro).

@MithicSpirit can you help me with this? I'm a new user in linux. I really dont know how can i open by terminal

**Comment by lariane-guerra** [comment]
> > I have a similar problem. I want to use the AppFlowy, i installed with POPos store, but i had a blank white screen on startup.
> 
> @lariane-guerra try launching it from the terminal and look to see if there is any output. If there is any please post it here. Also, make sure that the executable `xdg-user-dir` is in your `$PATH`.
> 
> > So, we now have 2 options, I think:
> > A) change this issue into "appflowy does not gracefully handle absense of xdg-user-dirs, it should show an error or something"
> > B) there is no issue here, since everything works if the build instructions are followed.
> 
> If option A is easy to implement (which I suspect it is—just hardcode default directories relative to `$HOME` if `xdg-user-dirs` is not found) then I think that it would be the best solution. Otherwise, I think that a warning similar to the ssl one should be added to the instructions stating that the `xdg-user-dir` executable is necessary (and mentioning the corresponding package on each relevant distro).

HIiiii, i remove the trash files, and re-install the app, now its working.

**Comment by Anvith00** [comment]
@lariane-guerra I'm not sure what steps you might have followed to install AppFlowy. What I do know is that the AppFlowy you initially installed from Pop!_Shop was a flatpak release, which is outdated by a version.

Can you let us know how you installed AppFlowy the second time?

**Comment by chenxuan520** [comment]
I opened it by unzipping the archive. The version is the latest, and there is a blank screen. The command line error is:Unhandled Exception:Invalid argument(s):Failed to load dynamic library 'libdart_ffi.so':libssl.so.1.1:cannot open shared object file:No such file or directory.      My operating system is linuxmint 21. I found that the missing dynamic libraries are all in the lib directory, but I don't want to add them to the system lib directory. Is there any other way to solve this problem

> @lariane-guerra I'm not exactly sure what steps you might have followed to install AppFlowy the second time. What I do know is that the AppFlowy you initially installed from Pop!_Shop was a flatpak release, which is outdated by a version, and has a blank screen since it cannot access openssl 1.1.1 in the sandbox.
> 
> Can you let us know how you installed AppFlowy the second time?
> 
> Was it by installing using a .deb installer, or, did you download and extract the tarball binaries?

**Comment by Anvith00** [comment]
@chenxuan520 You will require installing openssl1.1.1. You can do that on apt using:
```bash
 sudo apt install libssl1.1
```
If `libssl1.1` isn't present in your distributions package manager repository, do this instead:
```bash
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
```

**Comment by LucasXu0** [comment]
@czakuma Related to https://github.com/AppFlowy-IO/AppFlowy/issues/566#issuecomment-1479966477.

**Comment by Moilleadoir** [comment]
So is the flatpak unofficial/unsupported then?

**Comment by annieappflowy** [comment]
We officially support flatpak @Moilleadoir 
Will take a look into the issue

**Comment by annieappflowy** [comment]
Let us know if you still encounter the issue

**Comment by Zukureneno** [comment]
> Let us know if you still encounter the issue

This issue is still present on Flatpak

```
flatpak run io.appflowy.AppFlowy
Gtk-Message: 15:38:11.804: Failed to load module "xapp-gtk3-module"

** (AppFlowy:2): WARNING **: 15:38:36.891: atk-bridge: get_device_events_reply: unknown signature
```

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/60487234/1a656a8d-9c37-4e96-a9f5-e80f6aa30d00)
