### ISSUE TITLE
[FR] Add more info for ubuntu

### ISSUE THREAD

**Issue by PeterlitsZo** [AppFlowy-IO/AppFlowy#191]
I have the same problem of #180. But I solve it. I hope the `README.md` could add a link to this page for someone hits the same question.

WARNING: It may increase the instability of the system !!!

I append [ubuntu 21.04 source.list](https://askubuntu.com/questions/1340397/how-does-sources-list-for-hirsute-hippo-21-04-looks-like/1340401#1340401)'s content to `/etc/apt/source.list`, and then upgrade `libc6`.

``` shell
# Append the ubuntu 20.04's source.list to its tail.
$ sudo vim /etc/apt/source.list
$ sudo apt upgrade libc6
```

Now it works.

**Comment by Smartmind12** [comment]
@MikeWallaceDev Can i take this issue up and document it on readme for better usability??

**Comment by Smartmind12** [comment]
> Hi @Smartmind12 , thanks for offering the help. You can add this info to our [troubleshooting page](https://github.com/AppFlowy-IO/AppFlowy-Docs/blob/main/essential-documentation/install-appflowy/installation-methods/troubleshooting-when-installing-appflowy.md).

@annieappflowy Done with the needful changes kindly review...Thanks!
