### ISSUE TITLE
[Bug] Dev Scripts cause flutter version reset

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#1912]
## Issue

When we setup our environment using the `install_dev_env` files, it causes the Flutter Version to reset to the latest stable one. This behavior should be improved as we are using the specific version `v3.3.10` and any other version would cause error in the building process. 

## Caused By
I was able to narrow down the cause of error as the following lines in the `install_dev_env` files:
``` sh
# Enable the flutter stable channel
printMessage "Setting up Flutter"
flutter channel stable
```

## Solutions
>  Simply, comment these lines and prompt the user to have the specific version at end. As anyone following the [gitbook](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup) would have the right version installed. Also we are assuming here that the, `flutter` is added to path and is thus installed, so it makes sense to remove this line.

### How to Reproduce

On your system install `flutter v3.3.10`, and then run the scripts provided under `install_dev_env` and then check your flutter version.

### Expected Behavior

Do not modify pre-existing flutter version.

### Operating System

Ubuntu 20.04.5 LTS

### AppFlowy Version(s)

1.0.0.1

**Comment by AmanNegi** [comment]
Let me know, if I am right on this. And I would love to comment those lines 🤣

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. Yes. It's right. You can submit a PR to replace them with a new command to switch to v3.3.10 version.

**Comment by AmanNegi** [comment]
Hey @LucasXu0 as there are no further reports of this issue, I will be closing this issue.
