### ISSUE TITLE
[FR] Need of Board Improvements

### ISSUE THREAD

**Issue by Checkerface230** [AppFlowy-IO/AppFlowy#1917]
### Description

- [x] Addition of a scroll button if the board is too many. 
- [ ] Addition of other types of Big card. 
- [ ] Addition of Color to the  cards inside of the Big Cards. 
- [x] Addition of Starting Date and End date for the cards.

### Impact

To make the other boards much more viewable. To create different type of cards from the board beside No Status, To do, Doing , Done.  To make the board aesthetically pleasing. To know the real status of the card.

**Comment by MayurSMahajan** [comment]
Hey @Checkerface230, thank you for creating this issue, I also feel we should implement a scroll bar on the board's page. There is a way to add a start date and end date on the cards. 
For eg:
![image](https://user-images.githubusercontent.com/47064215/222940310-e30fe92a-0389-4fbd-80a8-f2462f772dfe.png)

Steps: 
1. Click the card.
2. Select New Column
3. Enter 'start date' as new column heading and select date as the data type.
4. Then click on the value of the column to pick a date from our date picker.
5. The selected date will appear on the card as described above.

**Comment by MayurSMahajan** [comment]
Hey @Checkerface230, thank you for creating this issue, I also feel we should implement a scroll bar on the board's page. There is a way to add a start date and end date on the cards. 
For eg:
![image](https://user-images.githubusercontent.com/47064215/222940310-e30fe92a-0389-4fbd-80a8-f2462f772dfe.png)

Steps: 
1. Click the card.
2. Select New Column
3. Enter 'start date' as new column heading and select date as the data type.
4. Then click on the value of the column to pick a date from our date picker.
5. The selected date will appear on the card as described above.
