### ISSUE TITLE
[FR] will you add whiteboard like affine

### ISSUE THREAD

**Issue by Angel0726** [AppFlowy-IO/AppFlowy#1918]
### Description

Affine is the next-generation collaborative knowledge base for professionals. all pages come with whiteboard . you can try it with url https://app.affine.pro/

### Impact

maybe everyone works with pen

**Comment by annieappflowy** [comment]
It's not on our roadmap at the moment.

**Comment by annieappflowy** [comment]
@andsofine , no, not in our one year plan at least

**Comment by smartynov** [comment]
Duplicate of #53

**Comment by Jose-jme** [comment]
and now?
