### ISSUE TITLE
[FR] Improvement for cover plugin

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1928]
### Description

Emoji support:
- Support adding an emoji icon at the cover plugin
- User can delete and replace the emoji icon by tapping the icon
- Add an add icon button to the cover plugin

Image from URL:
- Support adding images from the URL to the cover plugin
- When the user taps add image button the dialog shows up
- Dialog will have a TextField to add enter URL, a confirm button to add the image to the app gallery and a cancel button to close the dialog
- Show a loader while the image is being fetched and display the image inside the dialog when the image is fetched successfully
- Show an error message if fetch fails
- Support showing network images on the cover even when the device is offline

### Impact

For the user who wants to insert an emoji on the cover or insert a network image as a cover.

**Comment by rileyhawk1417** [comment]
@LucasXu0 so the network image will be cached in the data folder?

**Comment by LucasXu0** [comment]
@rileyhawk1417 Yes. The network image will be cached, but still not decide which folder should be used.

**Comment by rizwan3395** [comment]
@LucasXu0 I have started working on it, Please assign this ticket to me.
