### ISSUE TITLE
[Bug] Build flowy-error Fail

### ISSUE THREAD

**Issue by B635** [AppFlowy-IO/AppFlowy#1956]
### Bug Description

When I build the rust-lib in fronted, the flowy-error can't build,the result are as follows and shows:failed to run custom build command for `flowy-error v0.1.0 

failed to run custom build command for `flowy-error v0.1.0 (/Users/b635/Downloads/git_warehouse/AppFlowy/fronted/rust-lib/flowy-error)`

Caused by:
  process didn't exit successfully: `/Users/b635/Downloads/git_warehouse/AppFlowy/fronted/rust-lib/target/debug/build/flowy-error-6b248bcf31766459/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', flowy-codegen/src/protobuf_file/ast.rs:77:46
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

### How to Reproduce

<img width="519" alt="Screenshot 2023-03-10 at 23 31 32" src="https://user-images.githubusercontent.com/60867549/224357002-dab7238b-acf4-4a42-b222-b870e3beb01c.png">

### Expected Behavior

build successfully in flowy-error

### Operating System

MacOs

### AppFlowy Version(s)

the least version

**Comment by B635** [comment]
When I delete the build.rs in flowy-error. It builds successfully, But why build.rs will build fail

**Comment by appflowy** [comment]
@B635 Please check this out.https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup. I think maybe you need to switch to rust 1.65.

**Comment by B635** [comment]
@appflowy The toolchain.toml has set the rust 1.65, but it still can't build

**Comment by B635** [comment]
<img width="827" alt="Screenshot 2023-03-12 at 14 09 35" src="https://user-images.githubusercontent.com/60867549/224527609-36eb9129-65bd-4f7c-b485-f0b23ce59b04.png">

**Comment by a-wallen** [comment]
I ran into the same issue with flowy-error failing to build. It was resolved after I switched to the appropriate rust and flutter version.

**Comment by B635** [comment]
After I restart the project, it was resolved
