### ISSUE TITLE
[Bug] Data gets duplicated when starting the application

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/appflowy#196]
**Describe the bug**
The app appends a new "Welcome to AppFlowy" block every time it opens. 

**To Reproduce**
1. Open the app.
2. Go to the "read me" document
3. Scroll the document and count how many time you see the "Welcome to AppFlowy" Block.
4. Close the app
5. Reopen the app
6. Go to the "read me" document
7. Scroll and count the Welcome blocks, there will be one more than previously.

**Expected behavior**
Data should not change between close and open

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/147278157-ada06f7a-8f68-497b-9c0b-dca151b97380.png)

**Desktop (please complete the following information):**
 - OS: Linux, Manjaro
 - Browser: N/A
 - Version: 0.0.2

**Additional context**
N/A

**Comment by rileyhawk1417** [comment]
Any Idea what the cause could be?

**Comment by appflowy** [comment]
Issue fixed. Will be submitted later.

The reason for the data corruption is the document data was written even if the data already exists in the local disk. Which causes duplicate data issues.
