### ISSUE TITLE
[Bug] UI inconsistency

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1968]
### Bug Description

This "Cancel" button receives a special treatment by having a shortcut clue on the UI itself

### How to Reproduce

Use the Summarize feature

### Expected Behavior

Shouldn't include "ESC"
UIs should be consistent across the app

### Operating System

Windows 10

### AppFlowy Version(s)

main branch

### Screenshots

<img width="169" alt="image" src="https://user-images.githubusercontent.com/12026239/224523232-f6f3d12a-7b63-4c55-a234-93fdd9470baa.png">

**Comment by MayurSMahajan** [comment]
So we just want to remove the ESC word as a suggestion there, that button should only show Cancel. Does this seem to be a perfect candidate for a good first issue?

**Comment by LucasXu0** [comment]
Yes. It's a good first issue. However, I have to fix it now. We plan to release a new version in the next few days.

**Comment by LucasXu0** [comment]
<img width="929" alt="Screenshot 2023-03-14 at 16 28 22" src="https://user-images.githubusercontent.com/11863087/224940957-c50ba129-be6e-47de-972f-ec2d4ef5b2c4.png">
