### ISSUE TITLE
[Bug] Should the toolbar menu go along with where I see the cursor?

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1974]
### Bug Description

<img width="410" alt="image" src="https://user-images.githubusercontent.com/12026239/224529579-b3dab41f-232e-4aa1-b45b-152db32f777b.png">

The toolbar is still at the beginning of this long paragraph (see attached) so I can't see it until I scroll up to the beginning after I finish highlighting.

### How to Reproduce

Highlight long text

### Expected Behavior

I can easily access the toolbar menu

### Operating System

Windows 10

### AppFlowy Version(s)

main branch

**Comment by Xazin** [comment]
I think it's fine not for it to follow the cursor, but it would make sense if the context menu never goes out of bounds (eg. if you scroll down, then it would always stick at the top of the window.
