### ISSUE TITLE
[FR] Set a height limit for the AI prompt window where it displays the results

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1975]
### Description

As described, the height of the prompt window should have a limit 
Otherwise, when it returns something lengthy, it hurts the viewing experience because you can't easily view other text areas outside this prompt window.

### Impact

Users who use AI services.

**Comment by LucasXu0** [comment]
I didn't set a fixed height for the AI prompt window now because the scroll gesture inside it will conflict with the editor's scroll gesture.
