### ISSUE TITLE
[FR] Shortcuts link

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1977]
### Description

Clicking on "Shortcuts" is better directed to [this](https://appflowy.gitbook.io/docs/essential-documentation/shortcuts), where it is user friendlier
<img width="135" alt="image" src="https://user-images.githubusercontent.com/12026239/224530660-1e31d1a0-73b1-4814-9c54-ac92620399ef.png">

### Impact

Users who check the manual

**Comment by MayurSMahajan** [comment]
Working on it!
