### ISSUE TITLE
[Bug] Theflowy-user can't build

### ISSUE THREAD

**Issue by B635** [AppFlowy-IO/AppFlowy#1978]
### Bug Description

`?` couldn't convert the error to `flowy_error::FlowyError`
  --> flowy-user/src/handlers/user_handler.rs:55:44
   |
55 |     let s = serde_json::to_string(&setting)?;
   |                                            ^ the trait `From<serde_json::Error>` is not implemented for `flowy_error::FlowyError`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following other types implement trait `From<T>`:

### How to Reproduce

.

### Expected Behavior

But I find this in flowy-error, So why It can't build?
<img width="773" alt="Screenshot 2023-03-12 at 17 54 58" src="https://user-images.githubusercontent.com/60867549/224537293-406d2ada-68cd-4de2-be0d-e5d3ea31b506.png">

### Operating System

MacOs

### AppFlowy Version(s)

the least version

**Comment by LucasXu0** [comment]
Hey, @B635. Which version of Rust do you use?

**Comment by B635** [comment]
Hey, @LucasXu0 The rust version is 1.65

**Comment by B635** [comment]
<img width="622" alt="Screenshot 2023-03-14 at 12 32 55" src="https://user-images.githubusercontent.com/60867549/224893947-70d8bbc9-6ffe-4ded-befe-c3d5f9957cce.png">

**Comment by LucasXu0** [comment]
@B635 It seems that you're using Android Studio or another IDE. We build AppFlowy on VSCode mostly.

**Comment by B635** [comment]
Ye, that I use idea to build this project. But I think that it will works whether use either IDE

**Comment by B635** [comment]
@LucasXu0

**Comment by B635** [comment]
Gays, it's amazing.I can build it today without doing anything
