### ISSUE TITLE
[FR] Ctrl, shift or alt + backspace deletes a whole word at a time 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1985]
### Description

As described in the title

### Impact

Users who use a shortcut to delete a word

**Comment by MayurSMahajan** [comment]
Hello @annieappflowy! Actually pressing ctrl + backspace already deletes a word. This issue (#75 ) is already completed with this PR: #1845 . Maybe on some users' keyboards, it might not work because of different international keyboard layouts.

**Comment by Erik0806** [comment]
Doesn't work on a German keyboard

**Comment by annieappflowy** [comment]
The user who reported this issue is on a Norwegian keyboard

**Comment by richardshiue** [comment]
I'm not sure what's the norm on macOS but I've only been able to delete a whole word at a time in other text fields or text editing software (browser, office, etc) with Ctrl+Backspace, not shift+backspace or alt+backspace.

And to add to this, I hope the usability of the handler can be improved. When Ctrl+Backspace is triggered while there are multiple spaces and tabs after a word like `an apple           |`, should still be able to delete the word. That is, the previous text turns into `an |`

**Comment by MayurSMahajan** [comment]
> And to add to this, I hope the usability of the handler can be improved. When Ctrl+Backspace is triggered while there are multiple spaces and tabs after a word like `an apple |`, should still be able to delete the word. That is, the previous text turns into `an |`

I will see what I can do about it.

**Comment by iBobik** [comment]
It should by default follow OS conventions. So on macOS alt+backpace for word.

**Comment by Xazin** [comment]
There is this PR on the Editor repo (https://github.com/AppFlowy-IO/appflowy-editor/pull/32)

What it does is it makes `cmd + backspace` delete to beginning of sentence on MacOS, and `alt + backspace` on Windows. And makes it so `cmd + backspace` on Windows deletes word, on MacOS word deletion is `alt (option) + backspace`.

**Comment by Xazin** [comment]
@annieappflowy This can be closed as done :+1:
