### ISSUE TITLE
[FR] Windows 10 Native App Bar Does Not Respond To System Set Theme

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#1995]
### Description

The native menu bar on Windows 10 does not respond to user settings in the Windows system preferences.

![image](https://user-images.githubusercontent.com/44445638/225185322-8159fe63-5fcc-441f-b136-9acf30f9cf1f.png)

![image](https://user-images.githubusercontent.com/44445638/225185374-ec3a6bf3-1db9-46cf-be0f-1aa8bd282a4d.png)

### Impact

I could live without this.

### Additional Context

https://pub.dev/packages/bitsdojo_window

**Comment by a-wallen** [comment]
I think that it should suffice to make the app bar color the same color as the left navigation bar (using bitsdojo_window)

**Comment by GouravShDev** [comment]
I would like to work on this issue.

**Comment by annieappflowy** [comment]
Thanks. Assigned

**Comment by Danik1601** [comment]
Exactly the same thing on Linux.

Fedora 38 Beta, GNOME 44:
![image_2023-04-12_12-18-43](https://user-images.githubusercontent.com/17238959/231413382-a91e59a8-679f-41a8-8d71-28ef8bf19153.png)

**Comment by SaifEl-Deen** [comment]
Any updates on this? At least make it follow the current Windows color like other apps until it gets its own code to follow the app's color scheme?

**Comment by Xazin** [comment]
> Any updates on this? At least make it follow the current Windows color like other apps until it gets its own code to follow the app's color scheme?

I'll take a look at this. :+1:

**Comment by istanb84** [comment]
Hi, any updates on this?
I've searched related issues and found #2169 , it seems the feature has already been finished but never merged.
Not sure what is going on.

**Comment by Xazin** [comment]
> Hi, any updates on this? I've searched related issues and found #2169 , it seems the feature has already been finished but never merged. Not sure what is going on.

It was never completely finished.

To be more specific, it should only be implemented for Linux and MacOS, also, it should be possible to theme the windows bar, so that it always matches the window.
