### ISSUE TITLE
[FR] Importing data from Notion

### ISSUE THREAD

**Issue by immortaly007** [AppFlowy-IO/AppFlowy#20]
**1~3 main use cases of the proposed feature**
As a (former) notion user, I want to import my Notion into AppFlowy. So that I can take control of my already existing data.

What I believe is required for this feature to work well:

- All pages/subpages and data tables from Notion should be copied to/imported into AppFlowy
- The formatting is consistent between Notion and AppFlowy.
- Internal links (e.g. between pages) should work, and now direct to the correct location in AppFlowy.
- There should be a warning if some parts of the Notion can't be imported, which clearly states which pages are effected. This way, users can either copy those pages manually, or decide to abonden them. 

**what types of users can benefit from using your proposed feature**
(Former) Notion users.

**Comment by tomByrer** [comment]
If Appflowy has an API or a easy to access DB, then a simple API bridge should suffice as MVP.

Is Appflowy designed to be 100% API compatable?

**Comment by rabble** [comment]
I'd be happy with any import at all.

**Comment by dsinghvi** [comment]
Does AppFlowy publish an OpenAPI spec?

**Comment by Angel0726** [comment]
> If Appflowy has an API or a easy to access DB, then a simple API bridge should suffice as MVP.
> 
> Is Appflowy designed to be 100% API compatable?

i have the same questions, did anyone slove it

**Comment by acherkashin** [comment]
I would like to have ability to migrate from notion to appflowy

**Comment by HsunGong** [comment]
Put an eye here

**Comment by annieappflowy** [comment]
Working on it
https://github.com/AppFlowy-IO/AppFlowy/issues/2706

**Comment by thienguen** [comment]
Looking forward to it, the moment it comes out I will try right away

**Comment by aposseadesse** [comment]
Keeping an eye on this feature...

**Comment by travel-subsidize0stature-resident** [comment]
Looking great, also keeping tabs!

**Comment by annieappflowy** [comment]
@MarArMar , the import feature is released thru https://appflowy.io/compare/notion-vs-appflowy 
v0.7.2 will include this feature, which allows you to import without going to the web page.

**Comment by mensog** [comment]
There is a problem with importing via HTML and Markdown

I am attaching the cleaned application logs when attempting to import:
[log.2025-09-18.redacted.txt](https://github.com/user-attachments/files/22406633/log.2025-09-18.redacted.txt)
[log.sync.2025-09-18-10.redacted.txt](https://github.com/user-attachments/files/22406635/log.sync.2025-09-18-10.redacted.txt)
[log.sync.2025-09-18-11.redacted.txt](https://github.com/user-attachments/files/22406634/log.sync.2025-09-18-11.redacted.txt)
