### ISSUE TITLE
[Bug] Deleting a referenced board results in a permanent CircularProgressIndicator.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2001]
### Bug Description

If you add a referenced board to a page and delete the board, the page will have a permanent circular progress indicator.

### How to Reproduce

1. Create a new board.
2. Reference the board inside of a page.
3. Delete the board that you created earlier.
4. Close the app.
5. Open the app.
6. Open the page where you added the referenced board. There will be a circular progress indicator that you cannot remove.

### Expected Behavior

The referenced board should not show.

### Operating System

Windows 10

### AppFlowy Version(s)

main

### Screenshots

![image](https://user-images.githubusercontent.com/44445638/225464314-768c7693-81b8-4df0-a6d8-c421279b9508.png)

**Comment by DestinedCodes** [comment]
I have reproduced this, and would like this task to be assigned to me.

**Comment by DestinedCodes** [comment]
just checked and the bug doesn't only exist with boards but with grids as well

**Comment by a-wallen** [comment]
@DestinedCodes, thank you!

**Comment by DestinedCodes** [comment]
I just began working on it. I'll keep this space posted on my progress. I am applying for octernship, so an issue with the label "good first issue for devs" would be great.😊😊😊

**Comment by a-wallen** [comment]
I suspect the answer is in `built_in_page_widget.dart`

```dart
  @override
  Widget build(BuildContext context) {
    return FutureBuilder<dartz.Either<ViewPB, FlowyError>>(
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          final board = snapshot.data?.getLeftOrNull<ViewPB>();
          if (board != null) {
            return _build(context, board);
          }
        }
        return const Center(
          child: CircularProgressIndicator(),
        );
      },
      future: AppBackendService().getView(appID, gridID),
    );
  }

```

**Comment by DestinedCodes** [comment]
I have fixed the bug. please review😊. It was interesting working on this, but it wasn't really easy to build the app on my laptop. (I had to do more debugging on my laptop than I had to fix the code 😂)

**Comment by annieappflowy** [comment]
Fixed
