### ISSUE TITLE
[FR] selection menu with a single list style

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2006]
### Description

- [ ] implement a new selection menu with a single list style.
- [ ] the new selection menu should be fixed height, which also can be customized.
- [ ] the selection menu item should be sorted by group.
- [ ] users can search or filter the showing selection menu item by typing keywords.
- [ ] users can click on the item to select an item.
- [ ] users can also select an item by the arrow keys and the enter key.
- [ ] developers can customize the icon, name, and tooltips for a selection menu item.
- [ ] developers can customize a new group for the items or insert a new item into an existing group.

### Impact

* When AppFlowy is displayed on a small size window, the current selection menu will be blocked.
* Developers can customize the selection item group.

**Comment by jessicamrbr** [comment]
suggestion:

![Image](https://github.com/AppFlowy-IO/AppFlowy/assets/18180548/4c0fc6ba-6a9e-45ce-a35d-ec67fdd0a93f)
