### ISSUE TITLE
[Bug] the hover effect of Text in the slash menu doesn't disappear when selecting other options

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2010]
### Bug Description

![image](https://user-images.githubusercontent.com/12026239/225848096-ff151a37-0028-414f-979d-8201a6d9651a.png)

### How to Reproduce

Type / and then hover on an option other than Text

### Expected Behavior

Only one option a time has the hover effect 

### Operating System

MacOS

### AppFlowy Version(s)

release/0.1.1

**Comment by richardshiue** [comment]
This is the design in the figma. The currently-selected item has a lighter blue shade, while the hovered item is slightly darker. However, I noticed a different design with the blue checkmark instead of a color fill in the grid.

**Comment by slorop41314** [comment]
Hi @annieappflowy is this still an issue to be work on?

If so, just to confirm should it look like this? Hovered on 'Bulleted list'. 
Will need the Color value for **hover state** if this expected.

<img width="851" alt="Screenshot 2023-06-29 at 16 12 30" src="https://github.com/AppFlowy-IO/AppFlowy/assets/52713279/cbcad76d-a623-4940-8c8f-69ad1748c0f6">
