### ISSUE TITLE
[FR] Support regenerating AI results

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2012]
### Description

If I'm not satisfied with what AI generates based on my input, I can regenerate a result

### Impact

Users who use OpenAI Writer and Summarize

**Comment by annieappflowy** [comment]
+ improve writing

**Comment by rizwan3395** [comment]
@annieappflowy I have started working on it. Please assign this task to me

**Comment by a-wallen** [comment]
@rizwan3395 I reverted the PR that would've closed this issue. Please take a look at https://github.com/AppFlowy-IO/AppFlowy/pull/2642 for more information.
