### ISSUE TITLE
[FR] giving visual hint of dropdown menu in language selection

### ISSUE THREAD

**Issue by Sudhanva-Nadiger** [AppFlowy-IO/AppFlowy#2015]
### Description

![image](https://user-images.githubusercontent.com/93595710/225942820-85f1400a-59f9-4a32-9d51-06099fc89c4f.png)

- As we can see from this that we could not find that after clicking on "English" button it will open a menu list
- We can give a visual hint by providing Icons.show_more and Icons.show_less accordingly.

### Impact

- User can easily find out 

### Additional Context

- OS: windows 10

**Comment by DarkFalc0n** [comment]
I can help to implement this feature, please assign this to me @a-wallen.

**Comment by Sudhanva-Nadiger** [comment]
I am working on this !

**Comment by Sudhanva-Nadiger** [comment]
@appflowy shall I make PR for this ? I have made the changes ! Thanks.

**Comment by LucasXu0** [comment]
Hey, @Sudhanva-Nadiger. Yes. You can submit the PR.

**Comment by SharmaDhruv2511** [comment]
is this issue currently open?? I want to contribute to it..

**Comment by jumainahkhan** [comment]
@Sudhanva-Nadiger I would like to work on this issue. Can you assign it to me?

**Comment by Sudhanva-Nadiger** [comment]
Its alredy done guys! we can close this issue
