### ISSUE TITLE
[Bug] Tooltip text color is not coherent with dark theme, reduces readability. 

### ISSUE THREAD

**Issue by DarkFalc0n** [AppFlowy-IO/AppFlowy#2016]
### Bug Description

Tooltip text color stays white even in the dark theme, this results in reduced readability as the tooltip background is also white(ish).

### How to Reproduce

Turn the settings to: 
Settings > Appearance > Theme Mode > Dark Mode

Then hover over any action button in the UI to reveal the tooltip.
![image](https://user-images.githubusercontent.com/59203815/225959276-eab55d2b-c114-4f71-abba-b62cfbc51892.png)

### Expected Behavior

The tooltip text should change to a darker color upon switching themes.

### Operating System

Windows

### AppFlowy Version(s)

0.1.0

### Screenshots

![image](https://user-images.githubusercontent.com/59203815/225959571-9cde3300-6567-4c81-9b7a-314e2dadba9c.png)

**Comment by DestinedCodes** [comment]
I have been able to reproduce this issue and would like to work on it. Can you assign it to me? Thank you!!!

**Comment by a-wallen** [comment]
@DestinedCodes, you got it!

**Comment by hyj1204** [comment]
Hi guys, 
I have been working on the dark mode improvement recently and this tooltip text should be changed after it. 
@DestinedCodes  Is it okay to unsign you for this PR? 
Related to issue #1671 and PR #1987

**Comment by hyj1204** [comment]
This issue has been solved. Please check the linked PR for detail.
