### ISSUE TITLE
[Bug] Unable to scroll/access all the menu-items of slash menu when app-window size is smaller

### ISSUE THREAD

**Issue by Samiksha-Garg** [AppFlowy-IO/AppFlowy#2019]
### Bug Description

On small window sizes, the width of the slash menu becomes is greater and the menu overflows the right boundary. With no horizontal scroll available, the user is unable to interact with all the menu items in such case.

### How to Reproduce

Steps to reproduce the behaviour:
1) Make the app-window size as small as possible (or smaller than the expected dimensions of the slash menu)
2) Type "/" to invoke the slash menu command.

### Expected Behavior

It would be better if user could just scroll over the overflowing items.

### Operating System

MacOS (arm64)

### AppFlowy Version(s)

0.1.0

### Screenshots

<img width="814" alt="Screenshot 2023-03-19 at 9 44 13 AM" src="https://user-images.githubusercontent.com/79906086/226153762-81afee99-aa64-4794-9065-5b3486ddc0e4.png">

In the screenshot attached I am unable to access/see callout menu item.

**Comment by Samiksha-Garg** [comment]
Hello! I have found a fix around this small bug! Can I take this up?

**Comment by LucasXu0** [comment]
Hey, @Samiksha-Garg. Sure. How do you plan to fix it?

**Comment by Samiksha-Garg** [comment]
Hey @LucasXu0, So the selection menu is wrapped inside a positioned widget, and in order to make it horizontally scrollable it was necessary to have both left and right position arguments in place. Right position argument was missing so added that, and wrapped the child in single child scrolling widget. Selection menu scrolls only in case of overflow, otherwise it takes as much as width as required. I will raise a PR for it soon.

**Comment by richardshiue** [comment]
Hey there @Samiksha-Garg, could the items be re-arranged in less columns instead of it becoming scrollable in that situation? I think it would look better.
