### ISSUE TITLE
The non-abstract class '_AppFlowyInputState' is missing implementations for these members

### ISSUE THREAD

**Issue by 1AMTEDDY** [AppFlowy-IO/AppFlowy#2021]
### Bug Description

I was trying to build the application for LInux and i came across this error

```ERROR: packages/appflowy_editor/lib/src/service/input_service.dart:60:7: Error: The non-abstract class '_AppFlowyInputState' is missing implementations for these members:
ERROR:  - TextInputClient.didChangeInputControl
ERROR:  - TextInputClient.performSelector
ERROR: Try to either
ERROR:  - provide an implementation,
ERROR:  - inherit an implementation from a superclass or mixin,
ERROR:  - mark the class as abstract, or
ERROR:  - provide a 'noSuchMethod' implementation.
ERROR: class _AppFlowyInputState extends State<AppFlowyInput>
ERROR:       ^^^^^^^^^^^^^^^^^^^
ERROR: ../../../snap/flutter/common/flutter/packages/flutter/lib/src/services/text_input.dart:1163:8: Context: 'TextInputClient.didChangeInputControl' is defined here.
ERROR:   void didChangeInputControl(TextInputControl? oldControl, TextInputControl? newControl) {}
ERROR:        ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../snap/flutter/common/flutter/packages/flutter/lib/src/services/text_input.dart:1184:8: Context: 'TextInputClient.performSelector' is defined here.
ERROR:   void performSelector(String selectorName) {}
ERROR:        ^^^^^^^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
```
![teslim@teslim-HP-255-G7-Notebook-PC:~-AppFlowy-frontend_001](https://user-images.githubusercontent.com/103382847/226173673-844b5526-cf85-433c-9759-8046dc09b2b0.png)

### How to Reproduce

Follow the instruction in documentation on builiding for Linux. Link to that [here](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux).

Attempt to build the command
```
cargo make --profile production-linux-x86_64 appflowy 
```

### Expected Behavior

Build should be successful and no errors should be displayed on the logs

### Operating System

Linux

### AppFlowy Version(s)

Main

### Screenshots

![teslim@teslim-HP-255-G7-Notebook-PC:~-AppFlowy-frontend_001](https://user-images.githubusercontent.com/103382847/226174122-c435e83f-4c1e-478a-a7fb-492239fdc31d.png)

**Comment by LucasXu0** [comment]
Hey, @1AMTEDDY. We're using Flutter 3.3.10 now. Here's the docs. https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup
