### ISSUE TITLE
[FR] Add a new option Markdown to the help menu

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2026]
### Description

<img width="282" alt="image" src="https://user-images.githubusercontent.com/12026239/226232906-2f8feafa-494a-4d48-aabc-1b08ed79dd10.png">

Add a new option in the help menu by clicking on the '?' icon at the bottom right of the application
After clicking on the "Markdown" option, the user should be directed to a markdown guide.
The guide should be added to the [documentation](https://appflowy.gitbook.io/docs/essential-documentation/readme) as a separate page similar to [this](https://appflowy.gitbook.io/docs/essential-documentation/shortcuts)
The guide should explain all the markdown syntax supported by AppFlowy.

### Impact

Markdown users

### Additional Context

You need to ask @annieappflowy to create a separate documentation page for you on GitBook.

**Comment by Yogesh01000100** [comment]
Hi, I would like to work on this issue.

**Comment by JRS296** [comment]
Hey @annieappflowy, can I be assigned this issue as part of the requirement to complete the octernship application?

**Comment by Om-Gujarathi** [comment]
I would like to work on this!

**Comment by LucasXu0** [comment]
Hey, @Om-Gujarathi. I assigned it to you.

**Comment by Om-Gujarathi** [comment]
![Appflowy SS](https://user-images.githubusercontent.com/98649066/227538041-1a44f19b-b0d7-45b2-9f4c-046e6078b349.png)

Could you please confirm if this is what you were looking for @annieappflowy, @LucasXu0 ? 
Also, if possible, could you provide me with the a separate documentation page where the users would be redirected. I would greatly appreciate it.

**Comment by annieappflowy** [comment]
Hi @Om-Gujarathi , it looks great!
Could you send me a direct msg on [Discord](https://discord.com/invite/9Q2xaN37tV) with your email address? I'll invite you to be an editor of our documentation pages.

**Comment by Om-Gujarathi** [comment]
Sounds Great..Done!👍
