### ISSUE TITLE
[Bug] Slash menu responds to multiple key commands.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2030]
### Bug Description

https://user-images.githubusercontent.com/44445638/226263547-1511b257-2836-41a6-bdbb-77a140fa0d01.mp4

The video shows that the slash menu responds to the tab and arrow keys. The user should be able to control the slash menu simultaneously with the tab and arrow keys.   

### How to Reproduce

Type `/` in a document. Move the selection using the arrow keys, then press tab.

### Expected Behavior

The tab key should move the currently highlighted selection to the right by one. You can move to the first element in the next row if the selection is at the button furthest to the right. Using the arrow keys, the selection should move in the direction specified by the arrow key.

### Operating System

Windows 10

### AppFlowy Version(s)

main

**Comment by a-wallen** [comment]
We could also disable focus for the slash menu.

**Comment by squidrye** [comment]
Hi @a-wallen, I have been trying to implement this and I believe I am very close to achieve it can you assign it to me, I have been looking for issues to provide my first contribution.

**Comment by annieappflowy** [comment]
Thanks @squidrye for offering the help. Assigned it to you
