### ISSUE TITLE
[FR] Auto save the change to the workspace name

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2033]
### Description

![image](https://user-images.githubusercontent.com/12026239/226283788-81398ebe-4132-43de-9981-92db4fd415c6.png)
<img width="440" alt="image" src="https://user-images.githubusercontent.com/12026239/226283874-a09c758a-a9df-47fa-8ada-50c7c538ad4e.png">

Auto-save the change without needing to press Enter
For example, after changing the name from Me to Annie, I just close up the Settings by clicking on the gray area outside the Settings window. The name should be changed to Annie in this case

### Impact

Users who change their workspace name

**Comment by DestinedCodes** [comment]
I'd be glad to work on this. I can do it.

**Comment by DestinedCodes** [comment]
Can I begin working on this issue?

**Comment by annieappflowy** [comment]
Yes, I assigned it to you!
