### ISSUE TITLE
[Bug] Dragging a board column always takes it to the right-most section

### ISSUE THREAD

**Issue by bijaykumarpun** [AppFlowy-IO/AppFlowy#2036]
### Bug Description

In a board, different columns can be dragged to reposition them. However, when a column is dragged to any position, it is always automatically placed on the rightmost section.

### How to Reproduce

Step 1: Add a new `Board` page
Step 2: Drag a column to a different position

The dragged column will always be positioned on the rightmost section.

### Expected Behavior

The dragged column stays on the new position

### Operating System

MacOS Ventura 13.0.0

### AppFlowy Version(s)

1.0.0 (1)

### Screenshots

https://user-images.githubusercontent.com/13991373/226330517-0215cdfe-3060-4173-bbe2-360e872b4a29.mov

### Additional Context

Did not try reproducing this on any other device/OS.

**Comment by annieappflowy** [comment]
I can reproduce it on Windows 11

**Comment by annieappflowy** [comment]
Should be fixed
