### ISSUE TITLE
[FR] Create a shortcut to trigger the emojis selection menu

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2038]
### Description

At the moment, we can use the slash command to insert an emoji. It would be nice to have it triggered by keyboard shortcuts.

### Impact

Users who like using shortcuts to insert emojis.

### Additional Context

Past related work can be found in the repo

**Comment by not-shoyo** [comment]
Hi @annieappflowy . I hope I am right in understanding that we require a keyboard shortcut to open up the emoji picker. In which case I would like to be assigned this issue to work on.

**Comment by a-wallen** [comment]
Assigned @not-shoyo, you can request my review on your PR when it is ready 👍

**Comment by nurmukhametdaniyar** [comment]
@a-wallen Created a PR for the emoji selection menu shortcut, looking forward to your review.

Note: There is no access to SelectionMenuService, so I took the approach from the SelectionMenuService that uses EditorState to determine the offset of the selection menu.

**Comment by lalitkumawat1m** [comment]
hey @annieappflowy,
You are doing great work. I want to contribute to this project. Could you please assign this issue to me?

**Comment by rituraj2000** [comment]
@annieappflowy If this is still open could you please assign it to me ?
