### ISSUE TITLE
[FR] AI - Improve writing

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2039]
### Description

1. select a range of continuous text.
2. click the 💡 icon on the toolbar.
3. select the action `improve writing`.
4. call the OpenAI service to improve the selected text writing.

<img width="229" alt="Screenshot 2023-03-20 at 21 24 28" src="https://user-images.githubusercontent.com/11863087/226353228-a7bd23cc-4f95-410f-bb59-dfd8726c6f91.png">

### Impact

The users who want to improve the selected text writing.

### Additional Context

* refer to `smart_edit_action.dart`
* https://platform.openai.com/examples

**Comment by annieappflowy** [comment]
Assigned! Thanks for offering the help ❤️

**Comment by alceil** [comment]
Thanks @annieappflowy

**Comment by annieappflowy** [comment]
Your mentor is @LucasXu0 for this issue. Please feel free to seek help on Discord.

**Comment by alceil** [comment]
Sure @annieappflowy Currently im facing some issue while trying to run the project locally.

**Comment by alceil** [comment]
I have raised a pr can you please have a look @LucasXu0 @annieappflowy
