### ISSUE TITLE
[FR] Partially Checked / Indeterminate Checkboxes

### ISSUE THREAD

**Issue by AlexanderWillner** [AppFlowy-IO/AppFlowy#204]
**1~3 main use cases of the proposed feature**
I suggest to support partially checked / indeterminate checkboxes. A good feature request with examples and implementation details are given at https://gitlab.com/gitlab-org/gitlab/-/issues/229189.

**what types of users can benefit from using your proposed feature**
Anyone who thinks task completion is not just binary.

**Additional context**

Input:
```markdown
- [x] Item 1
- [-] Item 2
- [ ] Item 3
```

Output:
<img width="66" alt="image" src="https://user-images.githubusercontent.com/307605/146460820-3c16d3e7-e379-44ac-9c3b-544b63210999.png">

**Comment by annieappflowy** [comment]
Thanks, Alex. This will be considered as a community plug-in block.
