### ISSUE TITLE
[Bug] Exception is being thrown when attempting to switch the user icon

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#2042]
### Bug Description

It appears that an exception is being thrown when attempting to switch the user icon. 

### How to Reproduce

To switch the user icon
![image](https://user-images.githubusercontent.com/14248245/226407657-60db9165-c3c6-464c-b227-7ee40fc9e0e5.png)

### Expected Behavior

No exception should be thrown.

### Operating System

macOS 13.0

### AppFlowy Version(s)

0.1.1

### Screenshots

**Exception Message**
![image](https://user-images.githubusercontent.com/14248245/226407524-e2f9563d-0c77-4310-93a5-3e780f85c3f2.png)

**Comment by JazzGlobal** [comment]
I can take a crack at this. Can you assign this to me?

**Comment by JazzGlobal** [comment]
This isn't throwing an exception for me. Is it reproducible with a clean build?

**Comment by hyj1204** [comment]
@JazzGlobal 
I just tested again. The exception is gone in the current main branch. I am gonna close this issue. 
Thanks for you help.
