### ISSUE TITLE
[Bug] Exception is being thrown when switching to date type property of a card

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#2043]
### Bug Description

After I typed some value in the number type property, an exception occurred when I tried to change it to a date type property.

### How to Reproduce

1. Add a board and a new card.
2. Add `num` type property to the card and input some number like $123.
3. Change `num` type property to `date` type, the exception will occur.

![image](https://user-images.githubusercontent.com/14248245/226414969-a599a990-95e2-4052-8e5e-3ea70f7dd8f9.png)

### Expected Behavior

No exception should be thrown.

### Operating System

macOS 13.0

### AppFlowy Version(s)

0.1.1

### Screenshots

**Exception Message**
![image](https://user-images.githubusercontent.com/14248245/226414849-36148968-701c-45ab-af6f-911c8f51a600.png)

**Comment by JazzGlobal** [comment]
This also isn't not occurring for me. Wonder if it's due to me being on Windows and not Mac.

**Comment by hyj1204** [comment]
@JazzGlobal 
I tested again. This issue is also gone in the updated main branch. Sorry for that. It may be fixed with other issues together and forgot to link these. I will close this issue.

**Comment by JazzGlobal** [comment]
> @JazzGlobal I tested again. This issue is also gone in the updated main branch. Sorry for that. It may be fixed with other issues together and forgot to link these. I will close this issue.

Not a problem! I wonder if there's a test associated with this now.
