### ISSUE TITLE
[Bug] hint text misplaced

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#2044]
### Bug Description

The hint text should be 'Sort by' not 'Filter by' under the sort feature.

### How to Reproduce

1. Add a grid page
2. Click the 'sort'  button located in the top-right corner.
![image](https://user-images.githubusercontent.com/14248245/226419872-bbe6e221-9bea-4bec-b4fe-436bd4903257.png)

### Expected Behavior

Show 'Sort by' in the hint text

### Operating System

macOS 13.0

### AppFlowy Version(s)

0.1.1

**Comment by DestinedCodes** [comment]
This looks absolutely easy, I'd be glad to take this

**Comment by DestinedCodes** [comment]
@hyj1204 I just made a Pull request #2050 which should be a fix for the typo
