### ISSUE TITLE
[FR] Translation for multiple languages 

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#2048]
### Description

As Appflowy has expanded over time, we have found that several parts of our app are missing translations. If you are a bilingual, we would greatly appreciate your help in translating our app and making it accessible to more people in their native language.

Here are some steps you can take as a first-time contributor:

1. Create a new [issue](https://github.com/AppFlowy-IO/AppFlowy/issues) on our GitHub repository using the Feature Request template. Please state which language you would like to work on, and we will assign the task to you.

2. Fork our repository and create a new branch in your repository to work on. Check this [link](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions) for instructions on [how to install and contribute](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions).

3. Modify/Add a key-value JSON file for the language you are translating in the `frontend/app_flowy/assets/translations/ folder`. Please refer to the `en.json` file for the format and keys. For more details on translating AppFlowy, please refer to this [guidelines](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/translation).

4. Follow the [submission rules](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/code-submission-guidelines) to [submit your PR](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request) and link the issue you created in step 1.

### Impact

We encourage more people to use and explore our app. Additionally, it can help you discover all the features and functionalities that it offers.

**Comment by GouravShDev** [comment]
I would suggest to use chatgpt for translation. Just copy small part of json file in chatgpt and translate.  And made few changes if required. I tried translating using this trick in another project it worked great.

**Comment by annieappflowy** [comment]
Thanks @hyj1204 for creating this FR.
A to-do on my list is to explore translation platforms we can use to make translation tasks easier and more accessible to global translators.

**Comment by prashant235913** [comment]
There are many softwares for translation:_
here are the names of some good translation apps:

    Google Translate
    Microsoft Translator
    iTranslate
    Translate Now
    Papago
    DeepL
    Translate All
    TripLingo
    Translate Voice
    Language Translator
    
    I am thinking about picking this translation thing

**Comment by ahsanahmad4654** [comment]
Hey @hyj1204, What languages are missing in which you want the AppFlowy to be in future.

**Comment by hyj1204** [comment]
> Hey @hyj1204, What languages are missing in which you want the AppFlowy to be in future.

We welcome all new languages. You can choose your preferred language and start working. 

All the language file we support now is under the folder  `AppFlowy/frontend/resources/translations/`, however, except en.json, other language files may not be fully translated. For example, they don't have "Search emoji" since it was recently added in `en.json`. We would appreciate any improvement to our current language, as well as any new language.
