### ISSUE TITLE
[FR] Improve the tooltip for toolbar item

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2053]
### Description

<img width="635" alt="Screenshot 2023-03-21 at 09 48 27" src="https://user-images.githubusercontent.com/11863087/226501002-eedb7439-39bf-4a15-b232-f8d4b210d73e.png">

At the moment, the tooltip for the toolbar item doesn't contain the description of its connected shortcut. Like, we can trigger the selected text as `Bold` using `cmd / ctrl + B`. We want to show this event in its tooltip. For example:
```
Bold
⌘ + B // For macOS 
CTRL + B // For Windows
```

### Impact

Users who don't know the built-in shortcut.

### Additional Context

Please refer to those files.

* `document_page.dart`.
* `built_in_shortcut_events.dart`.

**Comment by Samiksha-Garg** [comment]
Hey @LucasXu0, can I work on this issue? Although I am not quite sure about how to go about it, the simplest way would be editing the tooltipsMessage for each item with a shortcut (in toolbar_item.dart), something like :
` tooltipsMessage: AppFlowyEditorLocalizations.current.bold +
        "\n" +
        (Platform.isMacOS ? "⌘ + B" : "CTRL + B"),`
If this is good, then we are good to go, or maybe you can point in the right direction.

P.S. `Platform.isMacOS ? "⌘ + B" : "CTRL + B"` could be fetched from a class tho, it would make the code more readable in my opinion.

**Comment by LucasXu0** [comment]
> P.S. Platform.isMacOS ? "⌘ + B" : "CTRL + B" could be fetched from a class tho, it would make the code more readable in my opinion.

Yes, it's a good idea. However, as I know, we can't fetch this tooltip from any class for now. Because the shortcut event registration is separate from the toolbar item registration. So I think we can hardcode the tooltip for the toolbar item temporarily. Once this PR has been merged, then we can get the connection between them. https://github.com/AppFlowy-IO/AppFlowy/pull/2112
