### ISSUE TITLE
[FR] Delete block and update prev block

### ISSUE THREAD

**Issue by qinluhe** [AppFlowy-IO/AppFlowy#2054]
### Description

1. Listen for backspace in TextBlock and delete the block where the cursor is located
2. Append the currently deleted content to the end of the previous block(The criteria for the previous block are: father or previous brother, depending on whether the current block is the first child of its father)
3. Confirm local data update and send op(Check the log to see if the log is printed)
Like insert block
<img width="500" alt="image" src="https://user-images.githubusercontent.com/108015703/226500971-3ddd19c6-9819-4109-9b58-e529b07a9d94.png">
You will see the op log with type  `delete` and `update` 

### Impact

Users who use the tauri of the Appflowy

### Additional Context

Preparation: https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/tauri-setup

Use React + TypeScript

Please add comments if you have any questions, thank you

**Comment by ArslanYM** [comment]
Can i start working on this?

**Comment by qinluhe** [comment]
> 

I am sorry because this task has been completed, now the branch main has the latest code.I will add some new issues in the future. 😊
If you are interested in other functions of the react version editor, please let me know, thank you for your attention and message. 
Express my apologies again. 😞

**Comment by qinluhe** [comment]
> Can i start working on this?

I am sorry because this task has been completed, now the branch main has the latest code, I will add some new issues in the future. 
If you are interested in other functions of the react version editor, please let me know, thank you for your attention and message. 😊
Express my apologies again 😞
