### ISSUE TITLE
[FR] Improve the cover plugin. Only show the change cover button and delete button when it's hovering.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2055]
### Description

<img width="1013" alt="Screenshot 2023-03-21 at 09 55 08" src="https://user-images.githubusercontent.com/11863087/226501628-edff52c1-9cff-42bf-bd2f-fb778420eb62.png">

At the moment, the change cover button and the delete button always show above the cover widget. We want to hide them when the cover isn't hovering.

### Impact

Make the document looks tidier.

### Additional Context

Please refer to:

* `cover_node_widget.dart`

**Comment by hmncube** [comment]
@LucasXu0 I would like to work on this issue

**Comment by LucasXu0** [comment]
OK, @hmncube. I assigned it to you.

**Comment by hmncube** [comment]
@LucasXu0 do we want to show the buttons after hovering on the whole cover image or on a particular space near the button location?
