### ISSUE TITLE
[Bug] The buttons should hide after setting a cover image

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2058]
### Bug Description

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/12026239/226513868-4db6a5a4-61d2-4409-a409-d15a06777541.png">

### How to Reproduce

Choose a color cover image

### Expected Behavior

The buttons `Change Cover` and `Trash` should hide

### Operating System

MacOS

### AppFlowy Version(s)

release/0.1.1

**Comment by AmanNegi** [comment]
Hey there I would love to work on this issue.

**Comment by annieappflowy** [comment]
Thanks @AmanNegi  for offering the help. I've assigned this issue to you.

**Comment by LucasXu0** [comment]
Hi @AmanNegi. This bug should be fixed in https://github.com/AppFlowy-IO/AppFlowy/pull/2145, but there is a minor UI bug, so it has not been merged yet.

**Comment by AmanNegi** [comment]
Okay I'll keep an eye on that as well. 🙂

**Comment by annieappflowy** [comment]
Still showing up in v0.1.3
