### ISSUE TITLE
[FR] Insert below should highlight the summary

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2059]
### Description

<img width="892" alt="image" src="https://user-images.githubusercontent.com/12026239/226514284-0b00b539-7da1-4503-95ef-77b2224e9952.png">

After summarizing the selected text area, I chose the option `Insert below`
The summary was inserted but I had hard time to locate it as the selected text was in the middle of a long article.
Ideally, we should auto highlight the summary using the cursor for the user

### Impact

Users who use the summarize feature

**Comment by squidrye** [comment]
@annieappflowy can I work on this?

**Comment by annieappflowy** [comment]
Sure. Thanks for offering the help!
If you need help or guidance, please reach out @LucasXu0
