### ISSUE TITLE
[FR] Allow users to select a language in the quick start page

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2069]
### Description

<img width="807" alt="image" src="https://user-images.githubusercontent.com/12026239/226617876-4ed5db5a-7e1d-45cf-8284-fee6ca6f590a.png">

Users can switch to another language (or maybe ideally it matches their system language automatically.

### Impact

All the users

**Comment by Om-Gujarathi** [comment]
I would like to work on this!
Also, if you could guide me on where to place the selector on the welcome page, as I'm not entirely sure if the placement I've chosen is optimal.

<img width="863" alt="Alternative" src="https://user-images.githubusercontent.com/98649066/227716425-1abac652-29f7-45dd-807f-87adb3c8a6b7.png">

**Comment by annieappflowy** [comment]
Thanks for offering the help. @Om-Gujarathi , your design looks good to me.
Adding @hyj1204 for a second opinion.

**Comment by annieappflowy** [comment]
I'd prefer to let `Quick Start` be the focus

**Comment by Xazin** [comment]
> After considering the feedback I received, I'm open to any design that you think would work best for the welcome page. However, I personally believe that the language selector should be placed in the bottom half of the page, just like @annieappflowy @Xazin said. To continue with the center alignment of the welcome page as @hyj1204 said, this design might work:
> 
> <img alt="AppFlowy WP" width="949" src="https://user-images.githubusercontent.com/98649066/228305093-21168290-ee46-4fcb-8293-864daa06d8e5.png">
> 
> Please let me know what you think, I'm open to any other suggestions.

Do you have a link to the original design of the screen? Or can you link me to the figma file of your version if not (or both) :pray:

**Comment by Om-Gujarathi** [comment]
> > After considering the feedback I received, I'm open to any design that you think would work best for the welcome page. However, I personally believe that the language selector should be placed in the bottom half of the page, just like @annieappflowy @Xazin said. To continue with the center alignment of the welcome page as @hyj1204 said, this design might work:
> > 
> > <img alt="AppFlowy WP" width="949" src="https://user-images.githubusercontent.com/98649066/228305093-21168290-ee46-4fcb-8293-864daa06d8e5.png">
> > 
> > Please let me know what you think, I'm open to any other suggestions.
> 
> Do you have a link to the original design of the screen? Or can you link me to the figma file of your version if not (or both) :pray:
> 
> Edit: Just noticed you work directly in the code, but maybe you have a link to the original none the less?

Unfortunately, I do not have any links to the original design or a Figma file of my version. I work directly in the code, so I don't have access to those files.

**Comment by Om-Gujarathi** [comment]
Actually my work on adding the language selector feature is completed, but everything was working perfectly until I pulled the latest code. 
<img width="950" alt="WelcomePage" src="https://user-images.githubusercontent.com/98649066/229573567-0a5620ea-6601-4e7d-95ee-a736c13d65b8.png">

Specifically, the welcome text and language selector menu that I added are not clearly visible.
I would appreciate any suggestions or advice that you can offer on how to fix this.

**Comment by Xazin** [comment]
> Actually my work on adding the language selector feature is completed, but everything was working perfectly until I pulled the latest code. <img alt="WelcomePage" width="950" src="https://user-images.githubusercontent.com/98649066/229573567-0a5620ea-6601-4e7d-95ee-a736c13d65b8.png">
> 
> Specifically, the welcome text and language selector menu that I added are not clearly visible. I would appreciate any suggestions or advice that you can offer on how to fix this.

Can you link me to your branch? I'd like to take a look

**Comment by hyj1204** [comment]
@Om-Gujarathi @Xazin 
I believe the issue come from the background color didn't get updated in the dark mode. I just fixed it in the [commit](https://github.com/AppFlowy-IO/AppFlowy/pull/2160/commits/a4966c2a9263713bb9568463698bd053e8db24bd) with my latest PR #2160

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/2188

**Comment by annieappflowy** [comment]
![Image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/958f9e5b-96fe-44a6-b8b5-2a1eb9b8d75b)
