### ISSUE TITLE
[Bug] Issues with the dark theme

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#207]
**Describe the bug**
Some elements are invisible when using the dark theme

**To Reproduce**
1. Use the dark theme

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/147884923-bef0f055-9818-4917-a91e-9318a2455c3c.png)
![image](https://user-images.githubusercontent.com/5375835/147884928-18d209af-7078-419e-b43c-0d8f6a96a2b1.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser N/A
 - Version 0.0.2

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]
None.

**Comment by apomalyn** [comment]
Closing this because the bug doesn't exists anymore (see screenshot)

<img width="62" alt="Screen Shot 2022-07-19 at 13 46 44" src="https://user-images.githubusercontent.com/22211097/179815839-38ddc56f-7331-411a-b2f1-a008aa36e2dc.png">
