### ISSUE TITLE
[Bug] Keyboard word-for-word text navigation not working

### ISSUE THREAD

**Issue by rlndkhlr** [AppFlowy-IO/AppFlowy#2071]
### Bug Description

Navigating from word to word using the keyboard's option and arrow keys does not work, the text cursor does not move.

### How to Reproduce

On macOS, open/create a document with a few sentences. When trying to use the option ( ⌥ ) key and left/right arrows to jump between or select single words, the cursor does not move.

### Expected Behavior

⌥ + left/right arrows: jump with cursor from word to word (❌)
⇧ + ⌥ + left/right arrows: select single words (❌)
⌘ + left/right arrows: jump from cursor position to line beginning or end (✅)
⇧ + ⌘ + left/right arrows: select from cursor position to line beginning or end (✅)

### Operating System

macOS Ventura 13.1

### AppFlowy Version(s)

Version 0.1.0 (1) & Version 0.1.1 (1)

**Comment by LucasXu0** [comment]
Hey, @rlndkhlr. I tested the `⇧ + ⌥ + left/right arrows: select single words` on my macOS. It works fine.

**Comment by rlndkhlr** [comment]
Thanks for testing. Tested it again, also on a different machine (and with the latest version) and it works here, too. Must have been a user error in this case, sorry about that.

Unfortunately, the `⌥ + left/right arrows: jump from word to word` still does not work. 😔

**Comment by Xazin** [comment]
> Thanks for testing. Tested it again, also on a different machine (and with the latest version) and it works here, too. Must have been a user error in this case, sorry about that.
> 
> Unfortunately, the `⌥ + left/right arrows: jump from word to word` still does not work. 😔

I've made a PR for this on the editor, it was indeed missing.

**Comment by annieappflowy** [comment]
Confirm it works on Windows
I also updated the shortcuts [guide](https://appflowy.gitbook.io/docs/essential-documentation/shortcuts)

**Comment by rlndkhlr** [comment]
Thanks all for fixing. :)
