### ISSUE TITLE
[FR] Don't run the CI tests related to Flutter if the developers only modify the code in appflowy_tauri.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2073]
### Description

As the title shows, the developers don't want to waste time on the Flutter CI if they only modify the code in appflowy_tauri, like ts, js, and so on.

### Impact

It will save time for the developers.

### Additional Context

Please refer to 

* `./github/flutter_ci.yaml`

**Comment by btertoolen** [comment]
Hey, can I work on this? @LucasXu0

**Comment by annieappflowy** [comment]
Thanks @btertoolen for offering the help. Assigned
