### ISSUE TITLE
[BUG] the version in the bubble icon `?` always shows 1.0.0 in Windows.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2074]
### Description

It will be better to show the real version in the bubble icon `?`.

<img width="186" alt="Screenshot 2023-03-22 at 10 59 31" src="https://user-images.githubusercontent.com/11863087/226791232-3a4cfab1-a14b-4021-95b4-d6fa6f2f8f0a.png">

### Impact

The users who want to know the app version.

**Comment by AmanNegi** [comment]
I would love to work on this issue. However, I didn't get what needs to be done. We currently show the version in the Help Menu.
![image](https://user-images.githubusercontent.com/37607224/226977055-3c86fa4d-e05d-46e0-8b17-a212dc113bb7.png)

**Comment by a-wallen** [comment]
@AmanNegi the current version is `v0.1.1` [(see this post on our Discord)](https://discordapp.com/channels/903549834160635914/924237714625290260/1088085092632637510). The version of the app can be found in `appflowy_flutter/pubspec.yaml`. Although the current version in the `pubspec.yaml` is incorrect, you can change it. We can incorporate [`package_info_plus` to read the version during runtime](https://stackoverflow.com/questions/53672171/how-to-get-build-and-version-number-of-flutter-app) and display the version in the menu. 

cc @annieappflowy to confirm that this is the correct app version.
cc @LucasXu0 to confirm that this is what you mean.

**Comment by annieappflowy** [comment]
Yes, this latest release is v0.1.1

**Comment by AmanNegi** [comment]
Okay I'll work on this 🤗✨

**Comment by Om-Gujarathi** [comment]
> @AmanNegi the current version is `v0.1.1` [(see this post on our Discord)](https://discordapp.com/channels/903549834160635914/924237714625290260/1088085092632637510). The version of the app can be found in `appflowy_flutter/pubspec.yaml`. Although the current version in the `pubspec.yaml` is incorrect, you can change it. We can incorporate [`package_info_plus` to read the version during runtime](https://stackoverflow.com/questions/53672171/how-to-get-build-and-version-number-of-flutter-app) and display the version in the menu.
> 
> cc @annieappflowy to confirm that this is the correct app version. cc @LucasXu0 to confirm that this is what you mean.

So now do we just have to update the version number in ```pubspec.yaml``` as the ```pakage_info_plus``` pakage is already implemented right?

**Comment by AmanNegi** [comment]
Yes we simply need to do this, also I am working on this. :smile: :sparkles:

**Comment by AmanNegi** [comment]
@LucasXu0 So far as I can see we simply need to update the `pubspec.yaml` version and that would fix the problem. Because we are already using the `package_info_plus` and all the code is in place already, just like @Om-Gujarathi said.

**Comment by AmanNegi** [comment]
Hey @annieappflowy, Is there something to be done on this issue?

**Comment by annieappflowy** [comment]
I suppose this is fixed? @LucasXu0 
<img width="129" alt="image" src="https://user-images.githubusercontent.com/12026239/228787239-f0d33d30-ba26-4110-b49d-5973900e0b09.png">
