### ISSUE TITLE
[FR] Support deleting the cover image inside Images

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2076]
### Description

* Add a `delete` button for each image.
* Add a `clear all` button on the top-right corner.

<img width="537" alt="Screenshot 2023-03-22 at 14 06 53" src="https://user-images.githubusercontent.com/11863087/226816766-f1fa2087-1d3a-4158-b0f7-d02d9d6aeee8.png">

### Impact

Users who want to delete the uploaded image.

**Comment by GouravShDev** [comment]
I would like to work on this issue

**Comment by annieappflowy** [comment]
Assigned to you. Thank you for offering the help.

**Comment by GouravShDev** [comment]
I created ui for it.
is it looking fine or some changes requires? 
 
![image](https://user-images.githubusercontent.com/74348508/227722067-6d3a6f4a-5277-4468-97bb-15b857e981fb.png)

**Comment by Xazin** [comment]
> I created ui for it. is it looking fine or some changes requires?
> 
> ![image](https://user-images.githubusercontent.com/74348508/227722223-7ff415f6-61f7-44dc-ad4d-1df710cd7604.png)

I think it looks great, I would have maybe used the Trash icon to clarify even more what the button does. (Just my two cents)

**Comment by GouravShDev** [comment]
> > I created ui for it. is it looking fine or some changes requires?
> > 
> > ![image](https://user-images.githubusercontent.com/74348508/227722223-7ff415f6-61f7-44dc-ad4d-1df710cd7604.png)
> 
> I think it looks great, I would have maybe used the Trash icon to clarify even more what the button does. (Just my two cents)

I'll replace cross icon with trash icon. Thanks for the suggestion.

**Comment by annieappflowy** [comment]
@hyj1204 might be able to offer help!

**Comment by hyj1204** [comment]
I made some design for the hover effect here https://github.com/AppFlowy-IO/AppFlowy/pull/2111#issuecomment-1485599614
