### ISSUE TITLE
[Bug] Double Asterisk to Bold Text doesn't work

### ISSUE THREAD

**Issue by Om-Gujarathi** [AppFlowy-IO/AppFlowy#2080]
### Bug Description

Double Asterisk to Bold doesn't work.

### How to Reproduce

Open/Create a document. When trying to bold text using \*\*TEXT_TO_BOLD** , it doesn't become bold. 

### Expected Behavior

The text between two asterisk should become bold.

### Operating System

Windows 11

### AppFlowy Version(s)

Version 0.1.1 (1)

### Screenshots

https://user-images.githubusercontent.com/98649066/226951914-d2f14eac-7cd2-4a67-92be-5bff275868b5.mp4

**Comment by Om-Gujarathi** [comment]
I would like to work on this issue.


https://user-images.githubusercontent.com/98649066/226952426-3f24328b-71f5-4aed-a79f-16037a4b8547.mp4

**Comment by Xazin** [comment]
I will presume that all these "markdown" formatters, aka. keyboard commands that insert text and expect to be handled correctly, will suffer from the keyboard layout issue until we have a solution for text commands.

**Comment by LucasXu0** [comment]
I re-think your previous suggestion, adding a text command for `input_service`. And here's my idea, we can both support key event commands, like `shift+slash`, `shift+enter`, and support character commands, like `/`, `*`.

<img width="1343" alt="Screenshot 2023-03-24 at 10 06 53" src="https://user-images.githubusercontent.com/11863087/227406228-7cf06f50-ce37-4450-9b83-100c2d6b4f98.png">

As the above screenshot shows, the `onKey` callback also returns the character. So, I think can extend this function to support different keyboard types.

**Comment by skkirtonia** [comment]
In my case, I needed to leave one empty line before a new header section after <p> </p> in the previous section. Not having an empty line removes all formatting in the next section.
