### ISSUE TITLE
[FR] Don't show "Referenced Board" or "Referenced Grid" as an option in the slash menu if there are none.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2081]
### Description

If there are no boards or grids in the current app, don't show "Referenced Board" or "Referenced Grid" as an option in the slash menu.

### Impact

Minimal

**Comment by annieappflowy** [comment]
I feel neutral about this solution to handle the no boards or grids case because I see the benefits of exposing these options even though there doesn't exist one to reference

**Comment by Xazin** [comment]
Maybe have an option to create one in the small context menu (where you can select a reference)
