### ISSUE TITLE
[FR] Title of referenced board does not change in document if name is edited in the workspace sidebar.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2082]
### Description

https://user-images.githubusercontent.com/44445638/227062156-f679050a-faed-4acf-8a2a-f609743e3d2a.mp4

The document widget needs to be reloaded entirely for the title of a referenced board to be updated.

### Impact

Minor fidelity impact.

**Comment by Xazin** [comment]
This issue persists not only for Board, but also for grid. (Any referenced Page - same logic)
