### ISSUE TITLE
[FR] Color selection for text and highlights using HEX/RGB values

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2090]
### Description

 Color selection for text, highlighting and wherever it can be applied to; by providing its HEX/RGB values. Because, in Notion there are a very limited no. of colors for it, and even out of them, certain colors really don't look/feel good in dark mode. Also, sometimes it's about individual preferences. So, I feel it would be really good if we let the user color of his/her choice, from the complete spectrum available. 

### Impact

Users who need more color choices

**Comment by Mukund-Tandon** [comment]
Can I work on this issue?
