### ISSUE TITLE
[Bug] Duplicated Grids are synced after closing AppFlowy

### ISSUE THREAD

**Issue by Lumerina** [AppFlowy-IO/AppFlowy#2095]
### Bug Description

Grids which are Duplicated are synced together upon closing AppFlowy, the latest grid you edited will affect the rest of the grids in the same category if duplicated

### How to Reproduce

1. Duplicate Grids in the same category
2. Make changes to one of those grids
3. Close AppFlowy
4. Check the Grids

### Expected Behavior

Each Grid should be different from each other

### Operating System

Windows 11

### AppFlowy Version(s)

0.1.1

### Screenshots

https://user-images.githubusercontent.com/107034053/227239261-d453363c-623a-40e8-91f8-c7e979509e37.mp4

**Comment by annieappflowy** [comment]
is this a newly introduced bug? @a-wallen @appflowy

**Comment by annieappflowy** [comment]
is this a newly introduced bug? @a-wallen @appflowy

**Comment by annieappflowy** [comment]
Hi @Lumerina , this issue has been fixed in[ the latest release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.2)
Thanks for reporting this bug. Hope to get more feedback from you ❤️
