### ISSUE TITLE
[Bug] Selection Menu doesn't show

### ISSUE THREAD

**Issue by jujpenabe** [AppFlowy-IO/AppFlowy#2098]
### Bug Description

When pressed the shortcut `/` to display the multiple utilities nothing happens.

### How to Reproduce

Build the project from source in Ubuntu 22.0 successfully.

Open the app.

Press `/` in any page.

Nothing happens, just the character `/` is printed in the editor.

### Expected Behavior

Is expected to display a selection menu (with all the tools, included the AI writer) when `/` is pressed

### Operating System

Lubuntu 22.04

### AppFlowy Version(s)

0.1.1

**Comment by Xazin** [comment]
This should have been resolved with #2101 - If you can test on newest version (main branch), we can close this.

**Comment by jujpenabe** [comment]
I've tested with the newest version, and it works perfect, it shows the selection menu as expected.
