### ISSUE TITLE
[Bug] Text overflows if OS text scale is larger than 100%

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2105]
### Bug Description

Buttons and text overflows the parent widget when the text scale is set to larger than 100% by the operating system.

### How to Reproduce

Windows 11, go to Settings > Accessibility > Text Size, set the scale larger than 100%. 

### Expected Behavior

Text does not overflow.

### Operating System

Windows 11

### AppFlowy Version(s)

main

### Screenshots

![image](https://user-images.githubusercontent.com/44445638/227631784-05e4fcbe-7391-4167-93a6-75c5f82f5e36.png)

**Comment by Xazin** [comment]
I'll work on this :+1:

**Comment by a-wallen** [comment]
Thank you!
