### ISSUE TITLE
Malicious executable or false positive?

### ISSUE THREAD

**Issue by victorsalit** [AppFlowy-IO/AppFlowy#2113]
Hi, 

I tried to install the last release (0.1.1), however the microsoft defender blocked the install of the AppFlowy_0.1.1_windows-x86_64.exe and on virustotal one vendor flagged the executable as malicious [see here](https://www.virustotal.com/gui/file/223dc9eff5af3c0d8f8aff79d5b5496147535ccb5ba9d4a3a0f1a1f529c92376) 
Please have a look.

Kind regards,
Victor
![AppFlowy MS Defender](https://user-images.githubusercontent.com/10028616/227799217-47657e56-e926-411e-a17a-fae396f7d41f.png)
![AppFlowy Virustotal](https://user-images.githubusercontent.com/10028616/227799239-202f222a-4823-4794-8168-add6f64cb74c.png)

**Comment by annieappflowy** [comment]
Hi @victorsalit , please click on `Run anyway` to proceed.
You see this warning because we have not purchased a developer license.

**Comment by gpytel** [comment]
Hey @annieappflowy , is it the same for Mac? I installed with no problems on Mac, Apple M1, macOS Ventura; but when I try to open, I get an error that "Apple cannot check the app..."

<img width="289" alt="Screenshot 2023-06-29 at 18 11 13" src="https://github.com/AppFlowy-IO/AppFlowy/assets/28045418/21067069-4f0d-41f0-99fa-3efa111d8aaf">

Coincidentally, I also installed on Mac Intel, macOS BigSur, and I was able to open with no problems :-)

If yes - please advise how to open it, I'm afraid I haven't had such case before...

Thank you!
