### ISSUE TITLE
[Bug] Snackbar theming

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#2127]
### Bug Description

It looks like we don't currently have a design for snackbars, and this reflects in the application when using Snackbars.

Mostly we have been using it to show errors, which have been hard to come by, but as we implement more snackbars as in eg. #2114 - we need to realign the Snackbar and it's theming.

Currently it looks bad on all themes, due to being disregarded previously.

### How to Reproduce

1. Open `Settings`
2. Go to `Files` tab
3. Double tap on the path / current files location
4. See the snackbar

### Expected Behavior

A common design for snackbars, and for it to be included when theming is being made

### Operating System

All

### AppFlowy Version(s)

0.1.1

### Screenshots

![image](https://user-images.githubusercontent.com/42929161/228172574-c8eb1da8-24b2-4e9d-89f5-cf6e681fd972.png)

**Comment by a-wallen** [comment]
It doesn't look like any of the Figma designs include specifications for a snackbar. I'm going to write a theme that's similar to the button theme.
