### ISSUE TITLE
Divider inserted on line with text does not go to the next line

### ISSUE THREAD

**Issue by DestinedCodes** [AppFlowy-IO/AppFlowy#2137]
### Bug Description

When inserting a divider in a line that already contains text, the cursor does not go to the next line. Instead, it remains on the same line. This bug only occurs when inserting a divider on a line with existing text, but works fine when the divider is inserted on an empty line.

### How to Reproduce

- Open AppFlowy
- Create a new Document
- Type some text on the line
- Insert a divider (/divider) on the same line as the existing text
- Observe that the cursor does not move to the following line

### Expected Behavior

When inserting a divider on a line with text, the cursor should move to the next line, just as it does when inserting a divider on an empty line.

### Operating System

Windows 11, Ubuntu 22.04

### AppFlowy Version(s)

0.1.2

**Comment by DestinedCodes** [comment]
can this issue be assigned to me?

**Comment by ankursharma7982** [comment]
Hi Annie Wang, This is Ankur from UpWork. 
I would love to work on this issue, kindly assign it to me.

**Comment by annieappflowy** [comment]
I believe GitStart is working on the fix: https://github.com/AppFlowy-IO/AppFlowy/pull/2561

**Comment by gitstart** [comment]
> I believe GitStart is working on the fix: #2561

Yes @annieappflowy we are waiting on this [task](https://github.com/AppFlowy-IO/AppFlowy/pull/2612) currently, and after that we will wrap this ticket also.
