### ISSUE TITLE
[Bug] Widget exception when expanding an empty section

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#2138]
### Bug Description

Widget exception when expanding an empty section

https://user-images.githubusercontent.com/14248245/228570618-997c07ca-3d71-418c-be3c-480a3bc2fc7c.mov

### How to Reproduce

1. Click the 'New page'  button in the left-bottom corner.
2. Enter a section name
3. Click the section name to expand it

### Expected Behavior

No exceptions occur.  

### Operating System

macOS

### AppFlowy Version(s)

0.1.1

### Screenshots

![image](https://user-images.githubusercontent.com/14248245/228562769-e44dd856-ce90-41a4-ab83-93c4364e27c5.png)

**Comment by DestinedCodes** [comment]
I am unable to  reproduce this on Ubuntu 22.04 Appflowy version 0.1.2, (maybe a screen record would guide better)

**Comment by DestinedCodes** [comment]
Since I still am unable to reproduce this, I am unable to take this issue. Maybe a different OS (I use Ubuntu 22.04) or this has been fixed in Appflowy 0.1.2

**Comment by DestinedCodes** [comment]
[Screencast from 29-03-2023 15:33:18.webm](https://user-images.githubusercontent.com/84413505/228573008-ea16adb7-e440-413d-ab20-e9b8bd47e82f.webm)

**Comment by Xazin** [comment]
Could also not reproduce on Windows 10

**Comment by hyj1204** [comment]
@Xazin @DestinedCodes 
I've just rebased the branch I was working on to the latest main and the Exception is gone. I guess someone might fix it recently. My apologies for the disruption for it. I really appreciate your feedback.
