### ISSUE TITLE
[Bug] Referenced Board/Referenced Grid cannot be inserted using slash menu "/referenced"

### ISSUE THREAD

**Issue by DestinedCodes** [AppFlowy-IO/AppFlowy#2139]
### Bug Description

When trying to insert a Referenced Board or Referenced Grid using the slash menu command "/referenced", the referenced board or grid menu option does not appear. However, if the slash menu command "/board" or "/grid" is used, the referenced board or grid can be inserted with no issue. 

### How to Reproduce

- Open AppFlowy
- Create a new document
- Type "/referenced" in the list item
- Observe that the referenced board or grid menu option does not appear. 

### Expected Behavior

The slash menu command "/referenced" should work when trying to insert a Referenced Board or Referenced Grid, just as it does when using the slash menu commands "/board" or "/grid".

### Operating System

Windows 11, Ubuntu 22.04

### AppFlowy Version(s)

0.1.2

**Comment by DestinedCodes** [comment]
I would like to offer to fix this issue myself if that is possible. Please let me know if this is an issue worth fixing and if I can be assigned to work on it. Thank you.

**Comment by Xazin** [comment]
> I would like to offer to fix this issue myself if that is possible. Please let me know if this is an issue worth fixing and if I can be assigned to work on it. Thank you.

I'm pretty sure no one will mind if you make a PR for this before being assigned, feel free to.

**Comment by DestinedCodes** [comment]
Thanks a lot. I have always waited to be assigned before making Pr's 🙃
