### ISSUE TITLE
[Bug] Divider shortcut (---) does not work on lines with existing text

### ISSUE THREAD

**Issue by DestinedCodes** [AppFlowy-IO/AppFlowy#2140]
### Bug Description

The divider shortcut (---) does not work when trying to insert a divider on a line that already contains some text. This bug only occurs on lines with existing text but works fine when the divider shortcut is used on an empty line.

### How to Reproduce

- Open AppFlowy
- Create a new document
- Type some text on the line
- Try to insert a divider using the shortcut (---) on the line with the existing text
- Observe that the divider is not inserted.

### Expected Behavior

The divider shortcut (---) should work when trying to insert a divider on a line with existing text, just as it does when used on an empty line.

### Operating System

Windows 11, Ubuntu 22.04

### AppFlowy Version(s)

0.1.2

**Comment by DestinedCodes** [comment]
I'd love to work on this.

**Comment by hmncube** [comment]
@annieappflowy Can you assign me this task?
