### ISSUE TITLE
[FR] The hover text for the setting icon isn't visible

### ISSUE THREAD

**Issue by vivekmahindrakar** [AppFlowy-IO/AppFlowy#2146]
### Description

![fr1-appflowy](https://user-images.githubusercontent.com/57032732/228842262-dbed3828-4267-4ed1-bd10-f813fab4f331.PNG)

**Comment by hyj1204** [comment]
Thank you for bringing this issue to our attention. We have recently made updates to our code to support dark mode better. Specifically, we have updated the generic areas/widgets such as the sidebar, top bar, question bubble, and tooltip #2099 . We are currently working on updating the remaining page areas, including the editor, grid, board, and calendar, to a better dark mode.

Please feel free to fetch the latest code in [main](https://github.com/AppFlowy-IO/AppFlowy/tree/main) branch and check out these updates. If you encounter any issues or have any further feedback, please do not hesitate to report them to us. We value your input and appreciate your help in improving AppFlowy.
