### ISSUE TITLE
[FR] Translate into Chinese(Traditional)

### ISSUE THREAD

**Issue by rhybs** [AppFlowy-IO/AppFlowy#2153]
### Description

Add more translations in Chinese(Traditional).

### Impact

For Chinese(Traditional) users.

**Comment by taylormao** [comment]
你下载的那个appflowy能直接使用？需要安装什么依赖环境么？

**Comment by rhybs** [comment]
> 你下载的那个appflowy能直接使用？需要安装什么依赖环境么？

ref: [environement setup doc](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup)
