### ISSUE TITLE
[Bug] The system cannot find the file specified after deleting selected cover image

### ISSUE THREAD

**Issue by GouravShDev** [AppFlowy-IO/AppFlowy#2173]
### Bug Description

After deleting the selected image of a document cover will cause the following exception:
 (OS Error: The system cannot find the file specified, errno = 2)

### How to Reproduce

- Add a document cover image
- delete that image through the change cover popup
- restart the app

### Expected Behavior

It should revert back to default no cover image

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.2

### Screenshots

![image](https://user-images.githubusercontent.com/74348508/229584182-e4c21547-47b3-4415-a0c4-1271c80fd78d.png)

![image](https://user-images.githubusercontent.com/74348508/229584135-1820f15b-cb4c-4d61-b61a-8edf3856de71.png)

### Additional Context

https://github.com/AppFlowy-IO/AppFlowy/pull/2111#issuecomment-1493578791

**Comment by GouravShDev** [comment]
I would like to work on this fix. As my PR caused it 😅.

**Comment by annieappflowy** [comment]
@GouravShDev , I commented on the previous PR. I think it's better to go back to the default no image cover state after deleting the current cover image.

**Comment by GouravShDev** [comment]
I need suggestion for the possible solution to this issue. 
I was thinking to just check for the cover image before creating image widget for that and if it doesn't exists then remove from the database and return empty sizedbox.
But this doesn't update the current document unless app restarts. Should I go with this approach?

**Comment by hyj1204** [comment]
In my opinion, the ideal solution would be to display a pop-up dialog when a user attempts to delete an image that is currently in use. It can be "This image is currently used in the cover, it will be removed from cover after it is deleted. Do you want to delete it and remove it from the cover? "  Yes/No
If the user chooses to proceed, the image should be deleted, and the cover should be updated with a refresh animation(that weird animation could make sense here) to indicate the change. It could be a new feature/improvement to do in a new PR. 

For now, it would be best to focus on fixing the error first. I think your first approach is suitable for this situation, and it won't cause any disruptive changes for users when they delete an image that's currently in use.

What do you think? @GouravShDev @annieappflowy

**Comment by GouravShDev** [comment]
Definitely agree with you @hyj1204 . I can try adding popup for deleting selected cover image and loading animation but that might take some time. If that first approach is feasible I can create PR for it. And might work on improvement later on.

I found another issue with updating current document cover after deleting selected cover image.

Let's say a image is used as cover for different documents and user deletes that cover image I might be able to update current document but I don't know how can I update all other documents which are using that cover image  without app restart.

**Comment by hyj1204** [comment]
@GouravShDev 
That's a really good point. I agree that it can be difficult to keep track of all the pages linked to an image that is going to be deleted. One solution I could think of it is to separate the cover image used on the page from the cover image used in the gallery. This could be achieved by making a copy of the image each time it is applied and saving it with the page it belongs to. By this way, if the user deletes the image in the gallery, it will not affect anything in the pages until the user chooses to delete it. However, this may cause a lot of cover images to be stored with the pages, I am not sure if it is a good solution to solve this problem at this point. 

Another feasible solution I could come up with is to follow the way I suggest before, pop up a dialog, then deleting the cover for current page only, and leave the other pages with deleted cover until user restart the app. After restarting the app, any non-existent cover images will disappear(become Sizedbox).

Let me know what you thought about it.

**Comment by GouravShDev** [comment]
@hyj1204 I am going with the approach of showing popup to user and updating current document . Other documents will update when widget get rebuild. I have created Alert dialog ui for it. I'm working on its functionality rn. 
Can you suggest if the UI for the dialog is right?

![image](https://user-images.githubusercontent.com/74348508/230729311-9d933391-b8f4-465c-a14d-0ba74aeac3cc.png)

**Comment by LucasXu0** [comment]
Hey, @GouravShDev. We should add a backup logic for deleting images. If we can't load the image successfully, we have two options: either clear the status of the cover or show the built-in image.

**Comment by GouravShDev** [comment]
@LucasXu0 I have added backup logic in my PR.
But what about alert dialog for deleting image which is current selected ? Should I keep it or remove it? As it difficult to check if image is used in any document cover.

**Comment by LucasXu0** [comment]
> Should I keep it or remove it? As it difficult to check if image is used in any document cover.

I suggest that we only show the toast if the user deletes the image that's currently being used in the document. @hyj1204 What do you think?

**Comment by hyj1204** [comment]
@LucasXu0 
Yes, I think it is my previous suggestion too. The dialog will pop up only when user intent to delete the cover which is in using in current page. If the image is not used in current page or used in other pages, the dialog won't pop up and the image will be delete immediately.

@GouravShDev 
You can use the dialog you already built. I may modify it later after you code is merged because I gonna refactor all the `StyledDialog` (maybe with other predefined widgets) later as a independent PR.
