### ISSUE TITLE
[Bug] Grids not loading after version update (msg: NotFound)

### ISSUE THREAD

**Issue by StartAGarden** [AppFlowy-IO/AppFlowy#2174]
### Bug Description

After updating from 0.1.0 to 0.1.2 my old grids don't load anymore. Instead I see the text "msg: NotFound". The title still shows.

### How to Reproduce

- previous version: 0.1.0 on Windows.
- updated to 0.1.2 via the provided Winows .exe file
- opened Appflowy
- since my data is not in the default folder, I selected the folder where my data is in
- my text files show up properly but all grids only show the title and, instead of the grid, only the error message

### Expected Behavior

All my old grids are shown properly.

### Operating System

Windows

### AppFlowy Version(s)

0.1.2

### Screenshots

![grafik](https://user-images.githubusercontent.com/114412683/229610198-0e2ac38d-b426-4281-84b9-9a47962c1e49.png)

**Comment by appflowy** [comment]
Hi @StartAGarden Would you mind send me the data folder? Or you can DM me in discord if you have any questions.

**Comment by Dialga** [comment]
I also have this issue, see #2166.

**Comment by a-wallen** [comment]
@Dialga do you mind sharing a workspace folder with us? I was unable to reproduce this by creating a new grid in 0.1.1 and opening the workspace in 0.1.2.

**Comment by Dialga** [comment]
Have sent you my db.

**Comment by StartAGarden** [comment]
Really sorry for the late reply, I sent @annieappflowy the data for this issue and the other issue I opened. Both are still there, even in the newest version.
