### ISSUE TITLE
[Bug] Multiple covers can be added to one page (random number, too?)

### ISSUE THREAD

**Issue by StartAGarden** [AppFlowy-IO/AppFlowy#2175]
### Bug Description

After updating from 0.1.0 to 0.1.2, I can add multiple covers in some of my old files. The numbers seem random, some are only one, then I have one file where I have 4 add-cover-buttons and one with even 8...?

### How to Reproduce

Not sure if there is a way to reproduce it, for me it appeared on "old" simple documents with text, after I updated from 0.1.0 to 0.1.2.

### Expected Behavior

Only 1 cover can be added per page and therefore only one button shows up.

### Operating System

Windows

### AppFlowy Version(s)

0.1.2

### Screenshots

![grafik](https://user-images.githubusercontent.com/114412683/229612502-430ec4cd-dd7e-46ef-853d-63c822053f65.png)
![grafik](https://user-images.githubusercontent.com/114412683/229612568-a7f3262f-99b3-4742-a09e-3ab08fb3cebc.png)
![grafik](https://user-images.githubusercontent.com/114412683/229612611-41b7dc03-2b73-41d7-a2b9-3483645729ac.png)
![grafik](https://user-images.githubusercontent.com/114412683/229612688-327dc36f-f660-42c1-8b16-b4e8bd23aca5.png)
![grafik](https://user-images.githubusercontent.com/114412683/229612729-577149ce-8b93-4ff9-a9f3-2140d86a92f0.png)

### Additional Context

Regarding the screenshots: First 3 are the example with the 4 buttons (screenshots only of 3), the last 2 are the file with the 8 buttons, screenshots show 2 buttons plus an existing cover)

_No response_

**Comment by a-wallen** [comment]
@StartAGarden do you mind sharing a workspace folder with us so that we can reproduce this?

**Comment by annieappflowy** [comment]
I cannot reproduce using v0.1.3
@StartAGarden do you still encounter the issue?

**Comment by StartAGarden** [comment]
@annieappflowy I am so sorry for the late reply, I sent you the folder since it is still the same with the newest version....
