### ISSUE TITLE
[Bug] When Screen Size is Small Kanban Board is not Horzontally Scrollable

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/AppFlowy#2177]
### Bug Description

[Screencast from 04-04-23 03:35:48 PM IST.webm](https://user-images.githubusercontent.com/71614009/229759403-e928479f-3292-4c74-b92a-a6eee377bca3.webm)

As Shown in the video If screen size becomes small the We are not able to scroll to view the left side Group

### How to Reproduce

Just creat a normal board and decrease screen width

### Expected Behavior

We should be able to scroll To left

### Operating System

Linux (Fedora Workstation 35)

### AppFlowy Version(s)

0.1.2

**Comment by Xazin** [comment]
Relates to #1917 I believe

**Comment by Mukund-Tandon** [comment]
Yes , Just saw it , Should I close this issue?

**Comment by Xazin** [comment]
> > Relates to #1917 I believe
> 
> Yes, Just Saw it , Should I close this issue?

Maybe not, let's see what the team says, I would assume since this is more specific, it might be easier to implement just this one feature compared to a "bunch" as in 1917.

**Comment by hyj1204** [comment]
We have the scrollbar in the gird view page but it doesn't exist in the board view page yet. 

https://user-images.githubusercontent.com/14248245/229947069-dfda55d5-69b8-4f3b-a923-b4e0912617aa.mov


### Anyone can help implement the same type of scrollbar in the Kanban board view page?

Here are some files maybe helpful to check to build this feature.
Grid page:
`AppFlowy/frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart`

Current scroll bar widgets:
`package:flowy_infra_ui/style_widget/scrolling/styled_scroll_bar.dart`

**Comment by Mukund-Tandon** [comment]
Can I work on this issue?

**Comment by AmanNegi** [comment]
I have noticed that when we use trackpad to scroll, it does scroll. However when we use mouse to scroll, it does not work.

**Comment by LucasXu0** [comment]
@Mukund-Tandon Sure. I assigned it to you. 

> I have noticed that when we use trackpad to scroll, it does scroll. However when we use mouse to scroll, it does not work.

Thanks @AmanNegi for reminding. I think there's a missing listener for mouse gesture.

**Comment by annieappflowy** [comment]
Are you working on this? @Mukund-Tandon 
If not, I'll assign it to another person.

**Comment by ankursharma7982** [comment]
Hello Annie, This is Ankur from UpWork,
Kindly assign it to me.

**Comment by Mukund-Tandon** [comment]
> Are you working on this? @Mukund-Tandon If not, I'll assign it to another person.

I am currently not working on this.

**Comment by annieappflowy** [comment]
@Xazin , I suppose this was fixed already?

**Comment by Xazin** [comment]
> @Xazin , I suppose this was fixed already?

Yes, it's completed.
