### ISSUE TITLE
[Bug] Settings Button or kanban board not clearly visible in dark mode and light theme

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/AppFlowy#2186]
### Bug Description

[Screencast from 04-04-23 08:11:08 PM IST.webm](https://user-images.githubusercontent.com/71614009/229829130-153c2e24-de1b-44cb-bcd0-5a97595dc012.webm)

The black color of setting text merges with the dark background which makes it little difficult to spot

### How to Reproduce

It appears on kanban board page

### Expected Behavior

The color of setting button should be differentiated from the background

### Operating System

Linux (Fedora Workstation 35)

### AppFlowy Version(s)

0.1.2

**Comment by hyj1204** [comment]
@Mukund-Tandon 
Thanks for bringing this issue. I am actively working on upgrading the dark mode feature and addressing the issue you reported. The issue will be solved once it is finished. I will keep you updated.

**Comment by Mukund-Tandon** [comment]
> @Mukund-Tandon Thanks for bringing this issue. I am actively working on upgrading the dark mode feature and addressing the issue you reported. The issue will be solved once it is finished. I will keep you updated.

I was able to come up with a solution to this issue . The final results were -

[Screencast from 04-04-23 08:17:41 PM IST.webm](https://user-images.githubusercontent.com/71614009/229859087-325ecfe7-da70-4163-bf97-21b0cc0811cd.webm)

Should I raise a PR or leave it?

**Comment by hyj1204** [comment]
You can leave it since I will change it with other improvements in the board view page. Thanks anyway.
