### ISSUE TITLE
[Bug] Failed to run AppFlowy_0.1.2_windows-x86_64.exe on Windows

### ISSUE THREAD

**Issue by njouanin** [AppFlowy-IO/AppFlowy#2187]
### Bug Description

When starting AppFlowy_0.1.2_windows-x86_64.exe, Windows complains with "Microsoft Defender SmartScreen" preventing from starting the application due to unrecognized application (unknwown editor).

### How to Reproduce

run AppFlowy_0.1.2_windows-x86_64.exe on Windows 10 with security restrictions (sorry, no windows specialist)

### Expected Behavior

AppFlowy_0.1.2_windows-x86_64.exe should run without security error

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.2

### Screenshots

![2023-04-04 17_33_46-](https://user-images.githubusercontent.com/728898/229843555-35c4ca27-d774-40d5-b78a-d2120e49982b.png)

**Comment by JRS296** [comment]
Hey there @njouanin , I encountered the same issue as I had not turned on the **Developer Mode** for my Windows Machine. You can try referring to these two links to solve the same.
- Developer Mode: https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
- Handling the Caution Message: https://www.itsupportguides.com/knowledge-base/windows-10/windows-defender-smartscreen-prevented-an-unrecognized-app-error/

**Comment by njouanin** [comment]
Thanks for the tips. Unfortunatelly, access to these settings is disabled beacuse of security settings setup by administrator which I can't change.

**Comment by LoganTann** [comment]
The executable version also requires administrator access ! Is it really needed ?
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/28659185/60b05f3c-c8a3-49dc-b06d-c12f11cd78eb)
