### ISSUE TITLE
[Bug] Workspace folder location in settings menu does not use consistent path separators.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2195]
### Bug Description

Under Settings > Files. 

The list tile that shows the location of the current AppFlowy workspace has inconsistent path separators on Windows (shows `/` and `\` in the same path).

### How to Reproduce

I don't know how to reproduce it, but this fix is easy. The `SettingsLocationCubit` from `settings_location_cubit.dart` has the following `path` getter on `:24` that parses the file system path.

```dart
  String? get path {
    if (Platform.isMacOS) {
      // remove the prefix `/Volumes/*`
      return _path?.replaceFirst(RegExp(r'^/Volumes/[^/]+'), '');
    }
   /*
   if Platform.isWindows, replace all instances of '/' with '\'
   */
    return _path;
  }
```

### Expected Behavior

AppFlowy should show the path with `\` separators instead of '/' separators on Windows.

### Operating System

Windows 10

### AppFlowy Version(s)

main

### Screenshots

![image](https://user-images.githubusercontent.com/44445638/229987907-85c7c41a-0759-4917-ab81-122018cb88f4.png)

**Comment by hmncube** [comment]
@a-wallen I would like to work on this issue
