### ISSUE TITLE
[FR] Handle invalid URLs when formatting text as a link

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2199]
### Description

On the link edition/creation dialog you can type anything and it's still accepted, it should only accept URL (from web URL to system (I don't know how they are called) URL like mailto, call, etc.)

In the link editing menu, we should let the user know "Type a valid URL to link"

### Impact

Users who format text as links

**Comment by GouravShDev** [comment]
I would like to work on this issue.

**Comment by rwt-2001** [comment]
@GouravShDev would you let me work on this issue?

**Comment by GouravShDev** [comment]
@rwt-2001 sure.

**Comment by annieappflowy** [comment]
Thanks @GouravShDev. I think there are other interesting issues to take :D
Assigned it to @rwt-2001

**Comment by Xazin** [comment]
The PR linked to this does not change any behavior inside the link menu, are we sure this is completed?

**Comment by Chandan-CV** [comment]
@annieappflowy @Xazin, if no one working on this, can I take it up? :smiley:

**Comment by Chandan-CV** [comment]
@annieappflowy Can you assign me this issue?

**Comment by annieappflowy** [comment]
Sorry for the late response. Are you still keen to work on it? @Chandan-CV

**Comment by AdiAr11** [comment]
Hi @annieappflowy , can i work on this? Also what all changes are required? Like should i change the title from 'Add your link' to 'Type a valid URL to link' and change the functionality by first checking if the link is valid before clicking entering or either of the two?
Thank you!
<img width="894" alt="Screenshot 2023-07-16 at 3 13 13 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/54585121/4a8b0087-55be-4298-8e9c-3cf57eb0274c">

**Comment by annieappflowy** [comment]
Hi @AdiAr11 , are you available to work on this?

**Comment by AdiAr11** [comment]
@annieappflowy Yes, I am available!

**Comment by AdiAr11** [comment]
@annieappflowy I think the following PR fixes this issue.
[https://github.com/AppFlowy-IO/appflowy-editor/pull/324#issuecomment-1643923192](https://github.com/AppFlowy-IO/appflowy-editor/pull/324#issuecomment-1643923192)
