### ISSUE TITLE
[FR] Minimum system requirement to build AppFlowy is required

### ISSUE THREAD

**Issue by FlyingWedgeDefence** [AppFlowy-IO/AppFlowy#2207]
### Description

Minimum system requirement to build AppFlowy is required. today the readme does not tell me the minimum requirements to build from scratch and this causes issues in being able to understand if i can run this app on my hardware or not. additionally information on the kind of cpu architecture supported would be generally helpful.

### Impact

- Decreased activation energy needed to retain new users

**Comment by LucasXu0** [comment]
Hi, @FlyingWedgeDefence. I believe this [document](https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/requirements) is what you're looking for. Please let me know if I misunderstood.
