### ISSUE TITLE
[Task] Fix all warnings in the code

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#221]

**Comment by gabrielztk** [comment]
Hi, I found some clippy warnings for rust
Should I fix them?

**Comment by appflowy** [comment]
> Hi, I found some clippy warnings for rust Should I fix them?

Sure! You could submit a PR to fix them. By the way, you can DM me if you need helps.

**Comment by appflowy** [comment]
Close this task.  Please create a new PR If you find any warnings.
