### ISSUE TITLE
[FR] Text to image generator

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2215]
### Description

Integrate [Stability AI](https://stability.ai/) services into AppFlowy to allow users to generate [images from text](https://platform.stability.ai/rest-api#tag/v1generation/operation/textToImage)

This should be an editor plugin and also can be triggered via /image and adding a cover image.

### Impact

Users who express ideas visually or use beautiful images to decorate their pages

**Comment by GouravShDev** [comment]
I would like to work on this one.

**Comment by LucasXu0** [comment]
Thanks, @GouravShDev. Assigned it to you. We can discuss more details about this FR if you need any help or clarification.

**Comment by GouravShDev** [comment]
@LucasXu0 Should I take reference from OpenAI Writer for implementing this feature? I think both features are somewhat similar.

**Comment by annieappflowy** [comment]
<img width="480" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ffb1375e-bfee-49e3-a310-52a64ec593e9">

We can simply add an option in the `/image `menu to provide this text-to-image generator

**Comment by rizwan3395** [comment]
This sounds interesting. I would like to work on this feature

**Comment by LucasXu0** [comment]
@rizwan3395 I'm currently working on implementing the local image upload feature, and I believe I am the most suitable person to handle the integration of this feature as well.

So, please find another feature instead.

**Comment by annieappflowy** [comment]
Released in v0.3.5
