### ISSUE TITLE
[FR] Code block copy button on hover

### ISSUE THREAD

**Issue by ghzgod** [AppFlowy-IO/AppFlowy#2217]
### Description

Could we get a copy button when we hover over a code block? Thank you

### Impact

Developers

**Comment by JRS296** [comment]
Hey @ghzgod, are you referring to a copy button on a left click over a component, or just over code blocks?

**Comment by hmncube** [comment]
@annieappflowy @ghzgod Is this the possible solution you have in mind?

https://github.com/AppFlowy-IO/AppFlowy/assets/2725300/26dd7856-1575-452a-9a42-a9296ba89253

**Comment by ghzgod** [comment]
> @annieappflowy @ghzgod Is this the possible solution you have in mind?
> 
>  possible.sln.mov

Yes this exactly!

**Comment by hmncube** [comment]
> Hi guys, thanks for your contribution. In our design mockups, the interactions on the code block look like this: <img alt="image" width="272" src="https://user-images.githubusercontent.com/12026239/237614268-913a866d-843f-4a32-a9d1-c968f675bbd1.png">

@annieappflowy Instead of duplicate the text will be `copy` right?

**Comment by annieappflowy** [comment]
Thanks @ghzgod for confirming!

Will consider your suggestions. Thanks, @hmncube

**Comment by annieappflowy** [comment]
FYI: your request is supported. Please give it a try with the [latest release](https://github.com/AppFlowy-IO/AppFlowy/releases).
