### ISSUE TITLE
[Bug] Build in Xcode fail

### ISSUE THREAD

**Issue by B635** [AppFlowy-IO/AppFlowy#2222]
### Bug Description

Choose the Runner.xcworkspace in Macos folder by Xcode.And build it but it show build fail like follow.
<img width="263" alt="Screenshot 2023-04-09 at 14 15 05" src="https://user-images.githubusercontent.com/60867549/230757698-39eef1b0-bd7b-4bf2-90d4-167149845f6d.png">

### How to Reproduce

I'm not usually use Xcode, So if it is that something doesn't setting cause,or I should have any other operation to run this.

### Expected Behavior

I want to know how to fix this.

### Operating System

MacOs

### AppFlowy Version(s)

the least version

**Comment by LucasXu0** [comment]
For running and debugging the project, we primarily use VSCode. If you need help getting start, here's the guide. https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos.

By the way, if you are able to successfully build the project in VSCode, you should also be able to build it successfully in Xcode.

**Comment by B635** [comment]
Ye, it shows not found dart_ffi, so does it mean that the rust cargo"dart_ffi" didn't build? @LucasXu0

**Comment by B635** [comment]
@LucasXu0  sorry I just see it now

**Comment by B635** [comment]
<img width="524" alt="Screenshot 2023-04-18 at 20 07 30" src="https://user-images.githubusercontent.com/60867549/232772438-26f9470f-eae5-49b7-a246-86aef2623ce2.png">

**Comment by B635** [comment]
I now use vscode, but it still build like this. But how can I get the app on my mac, can you give me some method @LucasXu0
