### ISSUE TITLE
[FR] Add the rules to analysis_options.yaml based on AppFlowy Flutter Style Guide

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2225]
### Description

We should add rules to `analysis_options.ymal`, located in `frontend/analysis_options.yaml`, based on [AppFlowy Flutter Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)

- [x] #2226
- [x] #2228

### Impact

This will help format the code and reduce the time required for code reviewing.

#### Reference
* https://dart-lang.github.io/linter/lints/index.html
* https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides

**Please DO NOT close this issue**. We will keep this issue open to continue discussing which rules should be added.

**Comment by literalEval** [comment]
I would like to work on this issue @annieappflowy @LucasXu0 
Please assign this to me :)

**Comment by literalEval** [comment]
@LucasXu0 I plan to add each option in a separate PR. Is that fine?

**Comment by a-wallen** [comment]
@LucasXu0 let's add one to document all public classes, methods, etc.

**Comment by LucasXu0** [comment]
> @LucasXu0 let's add one to document all public classes, methods, etc.

This one? https://dart.dev/tools/linter-rules/public_member_api_docs

**Comment by a-wallen** [comment]
Yes, that's the one. I wonder if there's a way that it will only apply to the PR diff rather than the whole repo.

**Comment by LucasXu0** [comment]
It seems that there's no way to apply only to the diff.

**Comment by a-wallen** [comment]
734 members to document, so maybe it's best that we leave this off for now. cc @annieappflowy adding this lint will significantly help the documentation of the codebase.

**Comment by literalEval** [comment]
@LucasXu0 

1. If we use the Dart Linter directly, it is possible to check single/list of file(s). Maybe clone the linter repo during CI and run the tool ? Caching the repo will reduce the runtime in future.
2. We can add ignore directive on top of each file in the repo, and just check if the file with a diff has the ignore directive or not. If it has, the PR check fails. If it doesn't have, the linter will do it's job anyway.

Though these alternatives will have the problem that even if the contributor changes a single line in the file, they will need to write documentation for the whole file.

**Comment by LucasXu0** [comment]
I prefer to request that both us and the contributors write documentation during code reviews for now. Perhaps we can focus on documenting all the public functions or classes in the future. In my opinion, it is not a priority for this quarter.
