### ISSUE TITLE
[FR] add prefer_final_fields, prefer_final_in_for_each, prefer_final_locals, prefer_final_parameters to analysis_options.yaml

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2228]
https://github.com/AppFlowy-IO/AppFlowy/pull/2219/files#diff-821d01a41fc10f7b1d262ae67e55c3c7592a44b0692999b99207dfaaac1dce66R291

* adding the above rules to analysis_options.yaml.
* formatting the exsittng code in the same PR.

**Comment by yatendra2001** [comment]
Hey @LucasXu0 , I would like to work on this issue, can you assign it to me?

**Comment by LucasXu0** [comment]
Sure, @yatendra2001.

**Comment by yatendra2001** [comment]
@LucasXu0 I need to create a new PR right?

**Comment by yatendra2001** [comment]
@LucasXu0 Opened a PR for this issue at #2708

**Comment by yatendra2001** [comment]
Okay, I need to fix the formatting of the code in this PR as well right?

so it passes the flutter analyzer?

**Comment by yatendra2001** [comment]
Do you know an automated way to achieve that? 
There are more than 5k+ lines and manually adding the final to each parameter doesn't seem feasible.

**Comment by LucasXu0** [comment]
Yep. You should format the code as well. You can use `dart fix --apply` for most cases.
