### ISSUE TITLE
[FR] Search v0.1

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2232]
### Description

Allow users to search in the workspace using natural language queries
A `Search` button can be found on the left panel
It can also be triggered via a shortcut cmd/ctrl + P

When you open the search window, you'll see a list of pages under Recent Pages. These are all pages from your workspace that you've visited lately.

Show the previous search query under Recent Searches in the search window.

### Impact

All users who retrieve information through searching with keywords or asking questions

**Comment by SaifEl-Deen** [comment]
May I ask why this FR is delayed to v0.2.6?

**Comment by Xazin** [comment]
> May I ask why this FR is delayed to v0.2.6?

It's complex to implement, and it is made up of multiple parts that need to come together. Backend design & implementation, UIUX design, and Frontend implementation.

I think v0.2.6 is the goal, but for this to actually be worth it to implement, there are other features that should be prioritized first.

**Comment by akaihola** [comment]
Why `Ctrl-P`? Isn't that the shortcut for printing a hard-copy by convention almost on all applications and all platforms?

**Comment by annieappflowy** [comment]
So what's the most common shortcut for triggering the search command?

**Comment by Xazin** [comment]
CTRL+K is the most common command for opening up a Command Palette, it's also the most common command for inserting a link if an editor is focused.

CTRL+F is the most common command for document search.

CTRL+Shift+F is the most common command for full workspace search.

**Comment by Xazin** [comment]
> Currently, I am working on a Find and Replace handler in the editor (this feature allows users to search within a document), I am using Ctrl+F and Ctrl+H for them. So we should use Ctrl+Shift+F for implementing this feature. 

Can you hit me up on discord about this. We might need to consider some things when implementing the built-in document search for the editor.

**Comment by Mojicode** [comment]
delay again...

**Comment by pickanameforlove** [comment]
waiting

**Comment by mauxdev** [comment]
It's a important feature. I think, without this AppFlowy cannot use with many notes.

**Comment by SimDav888** [comment]
Thanks a lot to the team. the lack of this function is this only reason why i still use notion ...

**Comment by Hexara7777** [comment]
@SimDav888 +1, can't believe that such an extremely important feature is not implemented yet,  I wonder how appflowy team prioritize their development efforts.

**Comment by SimDav888** [comment]
> @SimDav888 +1, can't believe that such an extremely important feature is not implemented yet,  I wonder how appflowy team prioritize their development efforts. 

Come on... dev is hard. I can imagine they had other priorities. For instance, the app looks very good and has a ios and android version. It s already a great achievement.  All dev thanks you for the good work please don t give up on us little users

**Comment by louisjg** [comment]
I just installed appflowy a few minutes ago and thought it was cool until I tried to search for something.  Search is basic expected functionality for notes and such.  TBH, I was shocked it's not here yet.

Please consider adding this basic functionality ASAP.

**Comment by FlorinZai** [comment]
Just installed this app a few minutes ago like louisjg says. I created a few notes and wanted to search but the functionality is missing. Can't replace notion without this basic feature

**Comment by thewh1teagle** [comment]
Can't use AppFlowy currenly without this feature. I write many notes... and navigate between

**Comment by mkrzych** [comment]
Hey, just wanted to highlight the priority of this feature. The ability to search through the notes is my main blocker to migrate from iOS/Mac notes.... The search needs to be robust and ideally should be integrated with Mac/iOS search.

**Comment by dandv** [comment]
@annieappflowy can you please provide a brief summary of how this feature works? Neither <kbd>Ctrl+P</kbd> nor <kbd>Ctrl+K</kbd> do anything in 0.7.6 on Linux/KDE, and this issue comes up in searches before any docs that might reveal the non-standard hotkey for workspace-wide search.
