### ISSUE TITLE
[Bug] Referencing grids trigger new grids automatically created

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2235]
### Bug Description

![Xnip2023-04-11_14-11-22](https://user-images.githubusercontent.com/12026239/231071802-d2b4126e-09e4-4dd4-918a-d85acc61b472.jpg)

The same issue appeared for referencing Kanban Boards

### How to Reproduce

1. Create a grid `GridA` and add a few records.
2. Create a new document
3. Insert a referenced grid to `GridA`
4. Insert another referenced grid to `GridA` in the same document

### Expected Behavior

Inserting referenced grids should **not** auto duplicate grids and show up in the left panel as standalone pages

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by annieappflowy** [comment]
So I manually delete the auto-created view from the left panel, then the referenced one in the document disappears and shows a loading icon 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/12026239/231148655-cd8a64fa-309d-4056-a0ff-575910f466f6.png">

**Comment by a-wallen** [comment]
I think that your issue with the loading indicator is related to [this issue](https://github.com/AppFlowy-IO/AppFlowy/issues/2001).

**Comment by a-wallen** [comment]
We're deciding not to show `View of` in the left navigation bar.

**Comment by annieappflowy** [comment]
Will improve when working on switching between views
