### ISSUE TITLE
[FR] Insert files into documents

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2237]
### Description

Allow users to insert files into documents via drag-and-drop and the slash menu
Users can view an inserted PDF in AppFlowy
Files can be chosen to save under a specified subpath
Support basic operations: rename, delete, and duplicate
There will be more features related to files.

### Impact

Users who retrieve information from the files and manage them in AppFlowy

**Comment by icearith** [comment]
files may be an important information of docs. Apple Notes has this feature, which I often attach related files in notes.

**Comment by annieappflowy** [comment]
Will include this feature in v0.6.7
