### ISSUE TITLE
[Bug] Duplicating a calendar then I'm not able to add an event

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2240]
### Bug Description

I duplicate a calendar in the left panel
I'm not able to add an entry to my duplicated calendar. And the data is not duplicated.

### How to Reproduce

Create a calendar and add a few entries
Duplicate it

### Expected Behavior

All the data should be copied to the duplicated calendar.
I'm able to add new things to the duplicated calendar and the data won't sync back to the original calendar.

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by richardshiue** [comment]
Hello @annieappflowy, are you still able to reproduce this on latest main? If so, could you give me more detailed steps to reproduce?

**Comment by appflowy** [comment]
> Hello @annieappflowy, are you still able to reproduce this on latest main? If so, could you give me more detailed steps to reproduce?

Already fixed in 0.1.3
