### ISSUE TITLE
[FR] shift + tab to unindent

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2243]
### Description

I'd like to use shift+ tab to unindent a checkbox
<img width="221" alt="image" src="https://user-images.githubusercontent.com/12026239/231144022-01cbaa32-78e2-46e5-8b7d-51c95be9aa02.png">

### Impact

Users who use lists to organize information

**Comment by ShadowWalker98** [comment]
Can I try this?

**Comment by Xazin** [comment]
> Can I try this? I am new to Rust but I would like to give this a go if that is okay with you?

I believe this is already done, or close to done.

There should be a PR on the editor repository that sovles this if I remember correctly.

**Comment by literalEval** [comment]
Is this done?

**Comment by MayurSMahajan** [comment]
Yes, it is already implemented in Editor version: 0.1.9 by this [PR](https://github.com/AppFlowy-IO/appflowy-editor/pull/63), soon the AppFlowy main branch will also have it included.

**Comment by annieappflowy** [comment]
It works on release/v0.1.3
Thank you all!
