### ISSUE TITLE
[Bug] The hover state in dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2246]
### Bug Description

<img width="846" alt="image" src="https://user-images.githubusercontent.com/12026239/231150254-e3fd8cf2-69a3-426d-8eea-178747c480dd.png">

The `x` hover state is not in a contrast color as depicted in the design spec

### How to Reproduce

Create a Kanban Board
Open a card
Hover on `x` in the top right corner

### Expected Behavior

The same effect like hovering on the property has

<img width="221" alt="image" src="https://user-images.githubusercontent.com/12026239/231151094-b285019e-73e0-408f-bc03-23ff2aaabe31.png">

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by hyj1204** [comment]
It has been updated.
<img width="146" alt="image" src="https://user-images.githubusercontent.com/14248245/232052756-54380b2b-4ae2-4e06-8d24-5b0149efe73b.png">
