### ISSUE TITLE
[Bug] (app_flowy:1): Gtk-WARNING **: cannot open display: :0

### ISSUE THREAD

**Issue by leeyaal** [AppFlowy-IO/AppFlowy#2250]
### Bug Description

I was trying to run appflowy in docker-compose, but there is no configuration for successful running. I always got the error like in the header. That is how my docker-compose looks like on a screen
I use the image from Dockerfile:

FROM appflowy: main

also I was trying to add 

CMD ["xhost +"]

did not work

Are there any solutions?

### How to Reproduce

correct docker-compose configuration, in docs docker-compose example did not work for me as well

### Expected Behavior

Successfful docker-compose running

### Operating System

Linux

### AppFlowy Version(s)

main(latest)

### Screenshots

![image](https://user-images.githubusercontent.com/90761484/231397243-1d4d25ff-aca5-4d93-a580-1d58cf537f67.png)

**Comment by DrAmygdala** [comment]
I have this issue as well and, while I don't have the knowledge to truly look into it, I think it has to do with using Wayland. For reference, I'm using Ubuntu 22.04 and Wayland. To quote from the docs
> Note: Appflowy inside docker needs access to your X server.

https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker

**Comment by annieappflowy** [comment]
@leeyaal @DrAmygdala would you like to try out our latest self-hosting solution? https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy
