### ISSUE TITLE
[FR] Code block, font, database feedback

### ISSUE THREAD

**Issue by xiwwqk** [AppFlowy-IO/AppFlowy#2255]
### Description

现在的功能已经足用，但还有很多地方可以尽善尽美。
譬如字体方面，希望可以在字体上可以有其他选择，或者至少将简体中文的字体换成宋体......谢谢。
另外在新建文档和表格的使用上，ui不够丝滑，希望有更加流畅的效果。

### Impact

所有用户

**Comment by LucasXu0** [comment]
Hi, @xiwwqk. Thank you for reporting. We will support customizing fonts. Could you clarify what you mean by "the UI not smooth"? Can you point out specific instances where you experienced this issue?

**Comment by xiwwqk** [comment]
非常感谢您的快速回复。
“用户界面不流畅”是一些带有主观印象的诸多细节问题。个人看法有如下：
1. 总页面展开收缩键的动画效果略长，给我的第一印象比较臃肿，且，收缩时向下的小三角形会多次让我误认为它是展开的。因为我在同类软件中，多见的时三角横向为收缩，竖向为展开。
2. 在打开新页面，设置，他的动画效果如同收缩见一样略显冗长，希望有更加干净利落的表现。
3. 在表格选择属性时，属性与其他的隐藏拷贝按钮应该可以在同一个界面中，不必在多余的进入属性列表内选择。
另外时我刚刚发现的bug。
我的电脑上安装了三个输入法，分别是微软的win11输入法，搜狗输入法，华宇输入法。当我输入中文时：
搜狗输入法输入正常。
华宇输入法会卡在两字符位置，输入内容永远在第二个字符上，其他内容会被挤出到后面，导致输入内容紊乱。
win11输入法输入时，他会将拼音当作内容输入。
我将设置语言调换为其他语言也无效，同样的输入我在edge浏览器开启翻译功能是见过。
一下是分别用搜狗，华宇，win11，三种输入法输入得到的结果。
期待您的下次回复。


![image](https://user-images.githubusercontent.com/125173715/231638359-a1e78ae6-4fee-4004-9cd0-a2dba844d83f.png)

**Comment by LucasXu0** [comment]
We will review your feedback. Regarding the Chinese input method, there is a known issue which can be found at https://github.com/AppFlowy-IO/AppFlowy/issues/1756.

**Comment by cidxb** [comment]
> 非常感谢您的快速回复。 “用户界面不流畅”是一些带有主观印象的诸多细节问题。个人看法有如下：
> 
> 1. 总页面展开收缩键的动画效果略长，给我的第一印象比较臃肿，且，收缩时向下的小三角形会多次让我误认为它是展开的。因为我在同类软件中，多见的时三角横向为收缩，竖向为展开。
> 2. 在打开新页面，设置，他的动画效果如同收缩见一样略显冗长，希望有更加干净利落的表现。
> 3. 在表格选择属性时，属性与其他的隐藏拷贝按钮应该可以在同一个界面中，不必在多余的进入属性列表内选择。
>    另外时我刚刚发现的bug。
>    我的电脑上安装了三个输入法，分别是微软的win11输入法，搜狗输入法，华宇输入法。当我输入中文时：
>    搜狗输入法输入正常。
>    华宇输入法会卡在两字符位置，输入内容永远在第二个字符上，其他内容会被挤出到后面，导致输入内容紊乱。
>    win11输入法输入时，他会将拼音当作内容输入。
>    我将设置语言调换为其他语言也无效，同样的输入我在edge浏览器开启翻译功能是见过。
>    一下是分别用搜狗，华宇，win11，三种输入法输入得到的结果。
>    期待您的下次回复。
> 
> ![image](https://user-images.githubusercontent.com/125173715/231638359-a1e78ae6-4fee-4004-9cd0-a2dba844d83f.png)

Same issue happened to me

**Comment by annieappflowy** [comment]
Issue 1 & 2 & Chinese input were resolved
