### ISSUE TITLE
[Bug] App logo contrast issue in Dark Mode

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#2259]
### Bug Description

When we switch to dark mode, the logo towards the top left becomes hard to view. Reason being the Black Text in the `Logo` image.

### How to Reproduce

Run AppFlowy and switch to Dark Mode.

### Expected Behavior

When user switches to dark mode, we should use a different logo with white text, that should make it easy viewable and readable.

### Operating System

Ubuntu

### AppFlowy Version(s)

0.1.2

### Screenshots

![Screenshot from 2023-04-14 08-44-43](https://user-images.githubusercontent.com/37607224/231932649-f930f95d-5f73-470b-a88a-91769021610e.png)

**Comment by AmanNegi** [comment]
I would love to work on this issue. We have the code in place but there is some issue with the implementation.

**Comment by annieappflowy** [comment]
![Asset 16](https://user-images.githubusercontent.com/12026239/231949042-891ae568-70ae-4b1c-a723-f32c00738745.svg)
Hi @AmanNegi , thanks for offering the help. Here is the logo asset you can consider using in the dark mode. I'm not sure if the logo name in white would work though.

**Comment by AmanNegi** [comment]
Actually we do have an SVG asset with white text already. Also the code is in place it just doesn't seem to listen to the theme change. I'll fix that part.

**Comment by AmanNegi** [comment]
> ![Asset 16](https://user-images.githubusercontent.com/12026239/231949042-891ae568-70ae-4b1c-a723-f32c00738745.svg) 

Hey @annieappflowy, the new asset you provided works as expected. Seems like the old `SVG` had some problem. Should I perhaps delete the old one and rename the new one as the old one?

**Comment by annieappflowy** [comment]
Please go ahead. Thank you!

**Comment by AmanNegi** [comment]
I did that now it's working as expected! Can you please check the PR

**Comment by AmanNegi** [comment]
Works as expected now, closing this issue.
