### ISSUE TITLE
[Task] Standardize all labels in the documentation

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#226]
This is really an ongoing task that should be done by all of us, all the time. I believe that we should add a Glossary for our terms.

**Comment by annieappflowy** [comment]
https://appflowy.gitbook.io/docs/essential-documentation/get-started/glossary
I created a page for terminology

**Comment by MikeWallaceDev** [comment]
That is in the "Get Started" section, I consider that for users. Which is great, I think that there should be a glossary there.

However, I meant for the code. There are terms that are not easy to grasp. What we can do is create a page, and then the coders (starting with me!) can write words that we don't understand, and then Nathan can fill in the blanks.
