### ISSUE TITLE
[Bug] Pressing enter to unindent the checkbox

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2275]
### Bug Description

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/12026239/232485714-d8580c1a-1b1a-4a61-bc6e-42717a3f2210.png">

### How to Reproduce

Insert a checkbox and write some stuff
Press `Enter` to auto-insert another checkbox
Press `Tab` to indent the checkbox
Press `Enter` 

### Expected Behavior

It should unindent the checkbox
In addition, if I press `Enter` again, it should go back to the beginning position of the current line.

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by Xazin** [comment]
I can resolve this, albeit will fix it on the editor repo. :+1:

**Comment by annieappflowy** [comment]
Thanks @Xazin . That was quick! Great work 👍
