### ISSUE TITLE
[FR] Select the entire bulleted list item vs the text 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2278]
### Description

If I copy a bulleted list item and paste it somewhere else, the bullet comes with the text.
Currently, I don't have an option to just copy and paste the text inside a bulleted list item.
I'd like to have both options available.

The same for the checkbox list, the numbered list, the code block, and other block types.

### Impact

All users

**Comment by Xazin** [comment]
Maybe an option to paste unformatted (rather than with formatting)?

**Comment by annieappflowy** [comment]
cmd + shift + v -> without the bulleted list format
