### ISSUE TITLE
[FR] Turn into a checkbox item

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2279]
### Description

I cannot turn a selected line of text into a checkbox item

### Impact

Checkbox users who need more flexibility of writing to-do items

**Comment by Xazin** [comment]
With the `/checkbox` command?

**Comment by annieappflowy** [comment]
I guess there should be an action menu for the user to choose such option when some text is selected
<img width="110" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/0beec152-ccba-4b9e-9445-17560882c8d8">
