### ISSUE TITLE
[Bug] the numbered list alignment

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2281]
### Bug Description

<img width="160" alt="image" src="https://user-images.githubusercontent.com/12026239/232491159-15a8514c-92bb-4691-9499-759ffc966f33.png">

### How to Reproduce

insert a numbered list and create a few items

### Expected Behavior

the numbers should be aligned

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by Xazin** [comment]
In reality, this could be an issue with the font rather than the UI rendering. I'd have to double check using eg. Photoshop or Figma with the correct font, but I have a hunch that it's the font itself causing the issue.
