### ISSUE TITLE
[Bug] The emoji select menu shrinks when close to the bottom

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2284]
### Bug Description

<img width="492" alt="image" src="https://user-images.githubusercontent.com/12026239/232493406-12f482f7-f630-43c8-aa1b-53c251251d08.png">

### How to Reproduce

Insert a callout block close to the bottom of the text area.
Click on the icon in the callout block

### Expected Behavior

The emoji menu is not compromised 

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by annieappflowy** [comment]
Even though the callout block is not close to the bottom, the emoji menu looks weird.

**Comment by BijayKumarPun** [comment]
I've successfully reproduced this, and I'm investigating further.

**Comment by BijayKumarPun** [comment]
Hi @annieappflowy, I'd like to work on this; can assign me this issue please?

**Comment by annieappflowy** [comment]
Sure. Thanks for offering the help!
