### ISSUE TITLE
[Bug] The callout block color palette

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2285]
### Bug Description

<img width="229" alt="image" src="https://user-images.githubusercontent.com/12026239/232494392-f5088b7f-5a8e-46c5-9480-4807fc7f6c82.png">

Color names are strange

### How to Reproduce

Insert a callout block
Pick another color through the top right icon in the callout block

### Expected Behavior

Color names are user friendly and accessible

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by AmanNegi** [comment]
Hey there, I would like to work on this. If I am right we are supposed to just change the names to user-friendly names right?
