### ISSUE TITLE
[Bug] Strange Issue with copying list from ChatGPT 

### ISSUE THREAD

**Issue by Akif-Vohra** [AppFlowy-IO/AppFlowy#2288]
### Bug Description

Unable to copy a list from ChatGPT to AppFlowy editor.

### How to Reproduce

1. Go to ChatGPT and enter prompt give me a random list. It creates something like this.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/8165978/232855448-44bdcad5-4125-41d3-b478-60f56d214ac9.png">

2. Highlight the list and try to paste it in AppFlowy.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/8165978/232855560-37f0e6cc-45ea-44e4-afa4-852345fe7634.png">

3. It shows following.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/8165978/232855625-4ba97a99-bb8e-4c7f-b71b-a9e57624f0c4.png">

As you can see it skips the actual content of list. I am able to copy the content in microsoft word or any other editor, so it does not seem to be an issue with my system's clipboard or copy function.

### Expected Behavior

It should copy a list, preferably in a proper list format.

### Operating System

MacOS 13.2.1

### AppFlowy Version(s)

Version 0.1.2 (0.1.2)

### Screenshots

I included them in steps to reproduce. 

### Additional Context

I am able to copy other kinds of texts from ChatGPT. 

Could it be related an issue with copying markdown?

**Comment by annieappflowy** [comment]
HTML copy & paste

**Comment by annieappflowy** [comment]
Hi @Akif-Vohra , this issue was fixed in the latest release ([v0.3.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.3.0))
Please give it a try!
