### ISSUE TITLE
[Bug] Build in Vscode Error 

### ISSUE THREAD

**Issue by B635** [AppFlowy-IO/AppFlowy#2290]
### Bug Description

Use AF clean+build all, then the application is always loading
<img width="801" alt="Screenshot 2023-04-19 at 16 15 14" src="https://user-images.githubusercontent.com/60867549/233012443-87d46ddb-e096-4d6e-8c28-f72f904e364d.png">
And the Vscode shows 
![image](https://user-images.githubusercontent.com/60867549/233012787-f2c3ebe8-0ee7-4290-b2ce-6077db283608.png)

### How to Reproduce

click the AF clean+build all, then it will shows

### Expected Behavior

show the welcome page

### Operating System

MacOs

### AppFlowy Version(s)

0.0.9

**Comment by literalEval** [comment]
in which directory was your VSCode open ?
