### ISSUE TITLE
[Bug] The editing toolbar in dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2292]
### Bug Description

<img width="589" alt="image" src="https://user-images.githubusercontent.com/12026239/233059820-47d06abc-2618-4a6a-95f7-051274f86095.png">

### How to Reproduce

Write something
Select the text to trigger the formatting menu
Hover on an option

### Expected Behavior

<img width="452" alt="image" src="https://user-images.githubusercontent.com/12026239/233059931-05c03e68-45e9-42b6-b906-4d1cbe9031e3.png">

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by hyj1204** [comment]
@annieappflowy 
I changed the background color of all tooltips to white style. The original design had a high contrast blue color for both the hover color/button (clickable) and the tooltip (non-clickable), which could be confusing for users. To address this, I opted for a neutral color that indicates that the tooltip is a non-clickable component.
