### ISSUE TITLE
[FR] Handle incorrect image url

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2294]
### Description

I should not be allowed to upload an image via an incorrect url
<img width="367" alt="image" src="https://user-images.githubusercontent.com/12026239/233061897-e878ff8f-3b93-422e-ac88-4a97b1737d65.png">

### Impact

Users who insert images using URLs

**Comment by AdiAr11** [comment]
Hi, does this issue still need to be fixed? I can work on it if its still need to be fixed. Thank you

**Comment by LucasXu0** [comment]
@AdiAr11 yes. Assigned it to you.

**Comment by AdiAr11** [comment]
@LucasXu0 Thank you !!

**Comment by LucasXu0** [comment]
@AdiAr11. Your approach sounds good to me. The code is located in `image_upload_widget.dart`, and you should submit the PR to this [repo](https://github.com/AppFlowy-IO/appflowy-editor).

**Comment by AdiAr11** [comment]
@LucasXu0  @annieappflowy Created a PR in this mentioned [repo](https://github.com/AppFlowy-IO/appflowy-editor) :)

**Comment by annieappflowy** [comment]
Did you manage to get it merged, @AdiAr11 ?

**Comment by AdiAr11** [comment]
@annieappflowy yes, that pr has been merged.

**Comment by annieappflowy** [comment]
@AdiAr11 , I can see that it would show "invalid image" after pressing "Enter"
Ideally, it should stay in the upload panel while showing "invalid image link". This way I can fix the image link right away.

**Comment by AdiAr11** [comment]
@annieappflowy sorry, I somehow missed your last comment. 
https://github.com/AppFlowy-IO/appflowy-editor/pull/324
In this PR, the popup stays while showing "Incorrect link".

**Comment by annieappflowy** [comment]
todo: handle it in the menu without clicking the button
<img width="522" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/91288a64-be12-498f-ad12-3fe71f3563b2">
