### ISSUE TITLE
[Bug] The icon picker for the workspace name dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2297]
### Bug Description

<img width="411" alt="image" src="https://user-images.githubusercontent.com/12026239/233064594-c58c0a4f-b3e3-4e9d-96fc-eefe9ead6aba.png">

There isn't a hover state when hovering on an icon
Doesn't look as polished as other components in the dark mode

### How to Reproduce

Go to Settings
Go to User
Switch to use another icon

### Expected Behavior

Hovering on an icon has a hover state
The menu looks better

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by hyj1204** [comment]
@akarsh-jain-790 
I think the background color should be `cardColor` from the Theme and hover effect you can refer `secondaryContainer` or `tertiaryContainer` to see which one is better.
