### ISSUE TITLE
[Docs] Add Windows compiling/build guide

### ISSUE THREAD

**Issue by TomGalla11** [AppFlowy-IO/appflowy#23]
Currently, the GitHub Readme file only contains instructions on how to build on macOS. But no steps on how to build on Windows 10.

**Comment by appflowy** [comment]
Hi @TomGalla11, please refer to this: https://github.com/AppFlowy-IO/appflowy/blob/main/doc/BUILD_ON_WNIDOWS.md

**Comment by Lloyd-Jackman-UKPL** [comment]
This link goes to a 404. Should it?

**Comment by annieappflowy** [comment]
Can you try this: https://github.com/AppFlowy-IO/appflowy/blob/main/doc/BUILD_ON_WINDOWS.md

**Comment by Lloyd-Jackman-UKPL** [comment]
Perfect, that works!

Sent from ProtonMail mobile

-------- Original Message --------
