### ISSUE TITLE
[Bug] Property Date in dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2301]
### Bug Description

<img width="583" alt="image" src="https://user-images.githubusercontent.com/12026239/233323969-c6056525-43ec-4053-9b58-336dc406aad0.png">

### How to Reproduce

Add a Date column to a table-view database
Click on the Date header

### Expected Behavior

<img width="522" alt="image" src="https://user-images.githubusercontent.com/12026239/233324198-6e2808d9-5cc7-4ef1-97f9-15aac5f5de7e.png">
 The same effect as the other two options have 

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by annieappflowy** [comment]
The property type menu has the same issue:
Current:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/12026239/233324968-454c11cf-5de1-4211-9128-e6a0480a5b8f.png">

Design spec:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/12026239/233324829-46d80ff1-c531-4127-a144-de28771db192.png">

**Comment by annieappflowy** [comment]
I'm not sure if the current implementation is the latest design though

**Comment by richardshiue** [comment]
Hmm, I actually kinda like the new subtle grey hover color. I also like the recent move to a light-grey hover in light mode in favor of the old light-blue. But that's just my opinion though, the most important thing is that it's consistent throughout the application, whichever way this goes.
