### ISSUE TITLE
[Bug] Date format

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2303]
### Bug Description

<img width="145" alt="image" src="https://user-images.githubusercontent.com/12026239/233326532-24349676-99cd-4198-ab16-98ae2819801b.png">

Should there be a space betwee `,` and `2023`

### How to Reproduce

Add a Date column
Use this Date format: Month day, Year

### Expected Behavior

Month Day, Year

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by vuzzer** [comment]
Hey there, I would love to work on this issue.

**Comment by annieappflowy** [comment]
Thanks, @vuzzer . Assigned.
