### ISSUE TITLE
[FR] Create a shortcut for switching between dark mode and light mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2304]
### Description

`cmd` + `shift` + L to switch between dark mode and light mode

### Impact

Users who switch between dark mode and light mode by shortcuts

**Comment by aiden77mori** [comment]
I want to contribute to your project by implementing shortcut

**Comment by annieappflowy** [comment]
Awesome! Thanks for offering the help. Assigned

**Comment by annieappflowy** [comment]
Are you still working on this? @aiden77mori

**Comment by aiden77mori** [comment]
Sorry.
I had a big problem for a while.
So I couldn't do it.
Sorry again.

**Comment by annieappflowy** [comment]
No worries.

**Comment by MayurSMahajan** [comment]
Yes, I would like to!

**Comment by MayurSMahajan** [comment]
Yes, I would like to!
