### ISSUE TITLE
[FR] = + > then ⇒

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2309]
### Description

Enable users to type `=` + `>` to insert ⇒

### Impact

Shortcut users

**Comment by rimildeyjsr** [comment]
@annieappflowy - Hey, can i work on this?

**Comment by annieappflowy** [comment]
Sure! Thanks @rimildeyjsr for offering the help!
Your mentor is @LucasXu0 for completing this task. Please feel free to reach out on [Discord](https://discord.gg/9Q2xaN37tV)

**Comment by rimildeyjsr** [comment]
@annieappflowy - yes i am!

**Comment by rimildeyjsr** [comment]
@LucasXu0 - I have reached out to you on discord regarding a few doubts

**Comment by annieappflowy** [comment]
Are you still working on this issue, @rimildeyjsr ?

**Comment by rimildeyjsr** [comment]
@annieappflowy - I couldn't get the setup to work and I had reached out regarding a few doubts, but could not proceed beyond it!

**Comment by MayurSMahajan** [comment]
Hey @rimildeyjsr, can you tell us more about what doubts you have?

**Comment by Gen1us1100** [comment]
hey @annieappflowy I am new to open source and I want to try to fix this issue, can you tell me what would be a good starting point? my question is where can I actually find the shortcut key bindings and their handler functions? Thanks in advance! 🙌

**Comment by MayurSMahajan** [comment]
Hey @Gen1us1100! Thanks for showing interest in this. The shortcut bindings and their handlers are in the AppFlowy Editor Repository. So currently we have two types of shortcuts: 
1. Character Shortcuts
2. Command Shortcuts

This issue can be solved by creating a new Character shortcut. So in the AppFlowy Editor repo, you can look up shortcuts here: https://github.com/AppFlowy-IO/appflowy-editor/tree/main/lib/src/editor/editor_component/service/shortcuts

**Comment by rituraj2000** [comment]
@MayurSMahajan  @annieappflowy Could you please assign this issue to me ? I am new to open source and would love to make this the starting point of my opensource journey

**Comment by MayurSMahajan** [comment]
This is an open issue since @Gen1us1100 did not ask to be assigned. But I am not going to assign it, because they might have begun working, so whoever submits a PR will be assigned. Fair enough? @rituraj2000 @Gen1us1100

**Comment by Gen1us1100** [comment]
Yes @MayurSMahajan I have setup the env and was able to build the project and I'm working on the function I'll submit the PR as soon as I'm finished
