### ISSUE TITLE
[Task] Design a branching strategy

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#231]
There are several examples named in the document.
* Git Flow
* Github Flow
* GitLab Flow
* One Flow

**Comment by Xazin** [comment]
With our way of working currently, and our release flow, we do not currently have a need for a branching strategy.

I'll close this for now until we have a need for a dedicated strategy.

When in doubt, use Git or GitHub Flow (compatible)
