### ISSUE TITLE
[FR] Command palette

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2315]
### Description

Enable a shortcut to open up the command palette where users can look up shortcuts or click on one to perform the shortcut on behalf of users
Further support using natural languages to perform a series of commands on behalf of users. For example, I can command it to format the selected text in heading 3, red, and italics. This can be expanded beyond performing a series of shortcuts.

### Impact

All users

**Comment by Xazin** [comment]
The below is merely my thoughts.

The command palette should be generalized to support at least:
- Search and trigger commands (Shortcuts basically)
- Search for and go to apps (Distinct between different types of apps)

I see there is a specific focus on AI in the issue description, would it not be enough to simply have an option directly the same as eg. "fix spelling", that when selected will fix spelling of the selected.

Maybe it would be good to have some kind of document describing this feature with a few wireframes (not full-fledged designs). I imagine being able to allow for commands that aren't shortcuts, eg. share document, export/import document, new page/database/grid, etc.
