### ISSUE TITLE
[FR] Android application

### ISSUE THREAD

**Issue by allytiago** [AppFlowy-IO/AppFlowy#2318]
### Description

The application uses native android languages, flutter.

 Currently, Android has similar apps that are very limited, such as Notion, which has keyboard shortcut and responsiveness limitations.

 As previously mentioned, AppFlowy is already written in a native android language and if an android application is added, it may have native support for Samsung DeX, an interface that turns the android mobile environment into a desktop environment.

### Impact

AppFlowy was what android users needed and it is very sought after, since we commonly have limitations not related to the system, but related to the software that does not bring the full version to the environment.

 Most likely, when bringing an android version, several users will use it and suggest more improvements.  The community will grow and if it is well optimized, the Samsung DeX community will share the tool on their portals so that more users have the knowledge.

**Comment by annieappflowy** [comment]
Thanks @allytiago for sharing your insight. Mobile support is working in progress. You can see what we're up to here: https://github.com/AppFlowy-IO/appflowy-editor/issues/68

We'll take your input into consideration when supporting Android.

**Comment by annieappflowy** [comment]
Hi @allytiago , AppFlowy Android is available to download from https://appflowy.io/download#ios-and-android
Let me know how you like it.
