### ISSUE TITLE
[FR] Copy action on Code Block

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#2321]
### Description

It would be nice to have the option to copy a code block with an action besides the trash icon.

<details>
  <summary>Poorly drawn expected location of action</summary>

![image](https://user-images.githubusercontent.com/42929161/233799951-1ce1b8fe-5fe3-40d6-8504-44fd23fa18a9.png)

</details>

### Impact

More controls for the code block, ease usage of code sharing

**Comment by Chandan-CV** [comment]
Can I work on this issue?

**Comment by annieappflowy** [comment]
<img width="270" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/6e279f86-bb14-4988-9643-699d49406fb3">
