### ISSUE TITLE
[Bug] Link Dialog is partially invisible at the bottom of the page

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#2322]
### Bug Description

Currently opening the link dialog at the bottom of the page, results in the link dialog being only partially visible. 

### How to Reproduce

1. Open a document in AppFlowy
2. Put enough text or content in the document to reach the bottom of the page.
3. Now press Ctrl/Cmd + k or Select Open Link from the menu to insert a Link Dialog.

Observe how the link dialog is out of view plane, and since scrolling is disabled, there is no way to use the link dialog.

### Expected Behavior

The link dialog should appear in the view plane. The entire Link dialog should be visible.

### Operating System

Windows 11

### AppFlowy Version(s)

0.1.3 main

### Screenshots

![image](https://user-images.githubusercontent.com/47064215/233822779-2c0bc43c-3409-4f94-ab8d-de9967a19254.png)

### Additional Context

To fix this, the position of the document should be considered when assigning the offset values to the link dialog.

**Comment by annieappflowy** [comment]
Fixed in v0.2.1
