### ISSUE TITLE
[FR] Create a shortcut to bulk open selected links in a document

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2323]
### Description

This plugin allows users to easily open all selected links in edit mode, simplifying the editing process for multiple links at once. With this plugin, users no longer have to manually open each link in edit mode, saving time and increasing efficiency. Simply select the links and let the plugin do the rest.

### Impact

Document users

**Comment by Xazin** [comment]
Do we know what shortcut we want to do this? Contextual menu option, keyboard shortcut, or something entirely different?

It should be quite easy to implement the functionality itself.

**Comment by annieappflowy** [comment]
I suppose keyboard shortcuts would be most convenient for the user.

**Comment by lalitkumawat1m** [comment]
You are doing great work. I want to contribute to this project. Could you please assign this issue to me?

**Comment by annieappflowy** [comment]
Hi @lalitkumawat1m , are you still keen to work on this issue?

**Comment by Tony-MK** [comment]
Hey @annieappflowy. If @lalitkumawat1m is not ready to work on this issue, could you assign it to me?

**Comment by annieappflowy** [comment]
Sure. Assigned! Thanks, @Tony-MK

**Comment by Tony-MK** [comment]
Hey @annieappflowy, I would like to start working on this issue but I have a couple of questions. Hence, Can you recommend for me a mentor to guide me through this issue?

**Comment by annieappflowy** [comment]
You can ask @MayurSMahajan for help

**Comment by MayurSMahajan** [comment]
Hey @Tony-MK! I am here to help, hit me on discord if you need, here is a similar issue that allows for opening a selected link: https://github.com/AppFlowy-IO/appflowy-editor/pull/373

**Comment by Xazin** [comment]
I think it would be best to simply modify the method on the editor to something like this:
```
  final nodes = editorState.getNodesInSelection(selection);
  final linkNodes = nodes.where((n) => n.attributes[BuiltInAttributeKey.href != null);
// The above is pseudo code - you get the gist
  for (final node in linkNodes) {
    final link = // grab href
    safeLaunchUrl(linkText);
  }
```
The above code was written from my phone, take it with a pinch of salt.

**Comment by MayurSMahajan** [comment]
Perfect! You wrote that on your phone🤯

**Comment by Tony-MK** [comment]
@annieappflowy, @Xazin and @MayurSMahajan. Thanks for the help but I was curious on the outcome of the PR will be.

1) Which combination on keys should I use? I am think for using `alt` + `shift` + `enter` because opening a link is `alt` + `enter`.

2) When the shortcut is used, what should happpen? 
	a) Open all the links in a document or highlighted section of the document?

	b) Just incase the document more than 20 or 50 links. I should I create a component, like the emoji plugin, which lists all the available links. Then the user can unselect unwanted links and open the rest of the links.

**Comment by Tony-MK** [comment]
> Hey @Tony-MK! I am here to help, hit me on discord if you need, here is a similar issue that allows for opening a selected link: [AppFlowy-IO/appflowy-editor#373](https://github.com/AppFlowy-IO/appflowy-editor/pull/373)

Thanks @MayurSMahajan. Really helped me

**Comment by MayurSMahajan** [comment]
Hey @Tony-MK! 
1. Using `alt+shift+enter` sounds good.
2. For now, I think just open the links in the browser.

cc: @annieappflowy @Xazin

**Comment by Tony-MK** [comment]
Thanks @MayurSMahajan. I will make a pull request ASAP.

**Comment by annieappflowy** [comment]
Hi @Tony-MK , it this issue completed?

**Comment by Tony-MK** [comment]
Hi @annieappflowy, the PR was successfully merged around two months ago. Hence, I believe it can be closed.

**Comment by annieappflowy** [comment]
Well done!

**Comment by Tony-MK** [comment]
Thank you @annieappflowy
