### ISSUE TITLE
[FR] Markdown bold and nested italics

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2324]
### Description

`**Bold text and _nested italic_ text**`
**Bold text and _nested italic_ text**

### Impact

Markdown users

**Comment by btertoolen** [comment]
Hi, can I work on this?

**Comment by annieappflowy** [comment]
Thanks for offering the help! Assigned

**Comment by rileyhawk1417** [comment]
@annieappflowy The PR seems to have been merged. This issue can be closed right?

**Comment by annieappflowy** [comment]
Thanks @rileyhawk1417 
Confirmed that it works now!
