### ISSUE TITLE
[FR] Markdown bold and italic text

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2325]
### Description

`***Bold and italic text***`
***Bold and italic text***

### Impact

Markdown users

**Comment by Xazin** [comment]
I guess this actually works now, albeit the UX is kind of lacking. Also considering if you wanted to do this on an empty line, adding 3 `***` inserts a divider.

**Comment by annieappflowy** [comment]
Consider it's supported for now
