### ISSUE TITLE
[FR] Markdown divider

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2332]
### Description

You can use ***, ---, or ___ on its own line to add a horizontal bar.

- [ ] https://github.com/AppFlowy-IO/AppFlowy/issues/2372
- [x] https://github.com/AppFlowy-IO/AppFlowy/issues/2371

### Impact

Markdown users

**Comment by glunkad** [comment]
Hey @annieappflowy , I would like to contribute to the issue.

**Comment by glunkad** [comment]
Yes will do.

**Comment by a-wallen** [comment]
@annieappflowy, can we also make this an umbrella issue? For example, create a new issue for implementing '***' and '___' separately.

**Comment by annieappflowy** [comment]
> @annieappflowy, can we also make this an umbrella issue? For example, create a new issue for implementing '***' and '___' separately.

Sounds good to me

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/2372
https://github.com/AppFlowy-IO/AppFlowy/issues/2371
cc: @glunkad

**Comment by annieappflowy** [comment]
Hi @glunkad , can this get done by Friday? Hope we can release it in the upcoming v0.1.5.
