### ISSUE TITLE
[Bug] Release for `unknown-linux-gnu` target packaged twice?

### ISSUE THREAD

**Issue by adrian5** [AppFlowy-IO/AppFlowy#2340]
### Bug Description

It appears the `AppFlowy_x86_64-unknown-linux-gnu_ubuntu-{…}.tar.gz` archive contains a duplicate of the binary package. You can quickly see this by comparing its size to the Debian package. Probably some oversight in the CI rules.

### How to Reproduce

Check out the [0.1.2 release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.2) assets.

### Expected Behavior

The archive contains the binary release without additional copies.

### Operating System

Linux

### AppFlowy Version(s)

0.1.2

**Comment by LucasXu0** [comment]
@adrian5 There is a duplicate zip file inside the release package. Thank you for the reminder.
