### ISSUE TITLE
[FR] Remove the CI job based on Ubuntu 18.04 

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2341]
### Description

The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22
* https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
* https://github.com/AppFlowy-IO/AppFlowy/actions/runs/4784145803/jobs/8505268705

The release job based on Ubuntu 18.04 is no longer functional, and we should remove it.

### Impact

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by BijayKumarPun** [comment]
Investigating on this...

**Comment by LucasXu0** [comment]
@BijayKumarPun Are you working it?

**Comment by BijayKumarPun** [comment]
Hi @LucasXu0, yes! Can assign me this already.
