### ISSUE TITLE
[Bug] Integration tests often fail

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#2346]
### Bug Description

The empty document and typing `/grid` to create a new grid integration test often fails during GitHub pull CI checks, even though the pr didn't have such changes and the error cannot be reproduced manually outside of testing.

```
Tests on a workspace with only an empty document /grid shortcut creates a new grid and view of the grid (failed)

  The following TestFailure was thrown running a test:
  Expected: at least 2 matching nodes in the widget tree
    Actual: _WidgetTypeFinder:<zero widgets with type "SelectionMenuItemWidget" (ignoring offstage
  widgets)>
     Which: means none were found but some were expected
```

### How to Reproduce

Make a flutter-related pr and observe that the integration test fails. 

### Expected Behavior

The test shouldn't fail so often.

### Operating System

CI ubuntu-latest

### AppFlowy Version(s)

0.1.3

**Comment by a-wallen** [comment]
Thanks for opening this issue. We are still recovering from the upgrade to flutter 3.7.5, which disabled OpenGL support and caused our integration tests on macOS to fail. We are now running the integration tests on Linux, but I think some race condition causes this issue to happen while all the tests in CI are running.

Aside, `macos (build)` also flakes. That needs to be addressed after this is addressed too.

**Comment by a-wallen** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/2622 fixes hard failure in CI for `open_ai_smart_menu_test`

**Comment by a-wallen** [comment]
It looks like https://github.com/AppFlowy-IO/AppFlowy/pull/2621 is solving the broken tests in `Flutter-CI` for Windows. The next step is solving the errors with `pumpAndSettle` awaiting for an infinite amount of time because of the circular progress indicator.
