### ISSUE TITLE
[Bug] The Numbers column doesn't support negative numbers

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2354]
### Bug Description

When I enter -20, it displays 20

### How to Reproduce

Create a table-view database
Add a Numbers column
Enter -20

### Expected Behavior

Negative numbers can be properly displayed

### Operating System

Windows 10

### AppFlowy Version(s)

v0.1.3

**Comment by 0xkelvin** [comment]
i think this issue related to my implementation on Rust part, so let me take it

**Comment by VenomSupreme** [comment]
Here's a small vid for better understanding of the issue. 
I'm pressing ENTER key after entering the numbers.


https://user-images.githubusercontent.com/69515491/235305725-8300cff8-44f0-422a-b909-afd38f44ff02.mp4
