### ISSUE TITLE
[Bug] URL Image style in dark mode

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#2362]
### Bug Description

URL Image placeholder looks invisible in dark mode

https://user-images.githubusercontent.com/14248245/234624950-38e4abcf-2897-4a2a-b3ab-eabb2c9d6e2b.mov

I think this issue also relates to issue https://github.com/AppFlowy-IO/AppFlowy/issues/2294. We need to find a solution to handle all the invalid image address. 

### How to Reproduce

1. Insert a image
2. Leave the address empty and click 'Upload'

### Expected Behavior

A visible place holder or a better solution to handle the invalid image address. 

### Operating System

macOS 13.0

### AppFlowy Version(s)

v0.1.3

**Comment by nurmukhametdaniyar** [comment]
Solved the issue in https://github.com/AppFlowy-IO/appflowy-editor/pull/119

@a-wallen @hyj1204  looking forward to your review

**Comment by hyj1204** [comment]
@nurmukhametdaniyar The grey color looks fine for both light and dark modes.  I feel it would be better to use the color from  ThemeData, like a divider color or something like that. Since the code has been merged and it works, I am gonna close this issue.

**Comment by hyj1204** [comment]
@nurmukhametdaniyar Got it,  that's good for now. Actually, the editor is undergoing some refactoring now, this type of color value could be customized in the future.
