### ISSUE TITLE
[Bug] Cannot edit select options from the edit property menu from the headers

### ISSUE THREAD

**Issue by BraianPita** [AppFlowy-IO/AppFlowy#2363]
### Bug Description

When I try to edit my select values on a grid from the column header edit menu, it wont allow me to do so

### How to Reproduce

(In dark mode) 
1) Create a new Grid
2) Create a new property of type 'select'
3) Create a few Options
4) Click on the option after it is created and try to edit it by clicking the two dots at the end of the select option

### Expected Behavior

I should be allowed to edit select options (name, color) from the header menu instead of only being able to do so from the field when adding a new entry.

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.2

### Screenshots

![image](https://user-images.githubusercontent.com/54162188/234711002-1ab7d090-5c3b-4a70-8487-f0cae88d98ae.png)

### Additional Context

I am new to Appflowy, so this might already be in the roadmap, but I could not find any mention of it in the open issues.

**Comment by annieappflowy** [comment]
Please follow the attached video to edit a select option:

https://user-images.githubusercontent.com/12026239/234792004-d9205b54-92c7-40c1-92a6-1455c299a57a.mov

I run into your issue the other day but cannot reproduce it in [v0.1.3](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.3) Maybe give it a try using the latest release?
