### ISSUE TITLE
[Bug] Board: error opening already created board: OTError IncompatibleLength

### ISSUE THREAD

**Issue by ljsalvatierra** [AppFlowy-IO/AppFlowy#2364]
### Bug Description

Already created board does not display.

### How to Reproduce

Don't know, yesterday worked, Just created a board page for a To Do list.

### Expected Behavior

Open the board page correctly.

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.3

### Screenshots

![image](https://user-images.githubusercontent.com/5963328/234758357-477067e6-5c1e-448f-9658-0e45e301f2fa.png)

**Comment by annieappflowy** [comment]
Cannot reproduce in v0.2.1
