### ISSUE TITLE
[FR] Callout block design polish

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2366]
### Description

<img width="888" alt="image" src="https://user-images.githubusercontent.com/12026239/234820618-4bc5239f-c715-4bc9-9b11-097f4de6af29.png">

- [ ] The hover effect on the emoji icon
- [ ] The position of the first line relative to the emoji icon
- [ ] The color palette doesn't work well in the dark mode

### Impact

Callout block users

**Comment by a-wallen** [comment]
@annieappflowy it might be helpful to make this an umbrella issue. 
![image](https://user-images.githubusercontent.com/44445638/235002115-f5392a62-e479-4e41-a14e-46512ad00b20.png)
You can convert the check boxes to individual issues and provide more context. When all tasks are completed, then we can close this.

**Comment by annieappflowy** [comment]
That's pretty cool. I didn't know we could convert a checkbox item into an issue via a button :D
I created it for a designer so one issue is ok for her. 
It's a good idea to break it down into smaller tasks for newcomers to take. I'll create individual issues for developers once we have a design spec.
