### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by superiums** [AppFlowy-IO/AppFlowy#2367]
### Bug Description

when choose browser exist notes or create new one, after click browser (choose path)
it reports:
```
Apr 27 21:35:18.671 ERROR ThreadId(22) {"message":"Uncaught platform error"}
{"msg":"Uncaught platform error"}
```

### How to Reproduce

maybe related to os ?

### Expected Behavior

file choose dialog to be shown.

### Operating System

void linux

### AppFlowy Version(s)

0.1.3

### Additional Context

it's easier to add an text box to define path of notes, instead of choose by file chooser.

**Comment by a-wallen** [comment]
duplicate https://github.com/AppFlowy-IO/AppFlowy/issues/2368
