### ISSUE TITLE
[FR] Markdown divider implement ___

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2372]
### Description

You can use  ___ on its own line to add a horizontal bar.

### Impact

Markdown users

**Comment by AmanNegi** [comment]
Hey there, I would like to work on this. If I'm right this is similar to our Octernship task right?

**Comment by annieappflowy** [comment]
This is to implement a markdown syntax 
@AmanNegi , would you like to give it a try?

**Comment by AmanNegi** [comment]
I would like to but I didn't get what you exactly meant by implementing a markdown syntax. If something similar is already implemented could you please redirect me?

**Comment by annieappflowy** [comment]
The Markdown guidebook: https://appflowy.gitbook.io/docs/essential-documentation/markdown
An example illustrating how to implement: https://github.com/AppFlowy-IO/AppFlowy/discussions/1100

**Comment by AmanNegi** [comment]
Yeah this is similar to the Octernship task... I can surely work on this

**Comment by annieappflowy** [comment]
Sounds good! Thank you 🙏

**Comment by AmanNegi** [comment]
Hey there, sorry I was busy so this issue went inactive. I just now started looking at this issue, however I just noticed that `---` has been previously implemented to add divider but it doesn't work currently. Also, I wanted to ask that the `appflowy_editor` was previously released separately, so is this issue still relevant here?

**Comment by Xazin** [comment]
> Hey there, sorry I was busy so this issue went inactive. I just now started looking at this issue, however I just noticed that `---` has been previously implemented to add divider but it doesn't work currently. Also, I wanted to ask that the `appflowy_editor` was previously released separately, so is this issue still relevant here?

It should be implemented in the appflowy_editor repository.

**Comment by AmanNegi** [comment]
Okay, so we are supposed to make the changes in the editor repo. Sorry for the delay, now that it's clear I will work on this immediately. ✨

**Comment by annieappflowy** [comment]
@AmanNegi , are you still working on this?

**Comment by AmanNegi** [comment]
Yep now I am working on this, was waiting for the merging of `develop` and `main` branch.

**Comment by Xazin** [comment]
> Yep now I am working on this, was waiting for the merging of `develop` and `main` branch.

See for reference https://github.com/AppFlowy-IO/appflowy-editor/pull/118
All you need to do is add a Shortcut for `_` that triggers the insertDividerHandler.

On editor repo.

**Comment by AmanNegi** [comment]
Thanks for the reference @Xazin. Perhaps should I move this issue in the `editor_repo`?

**Comment by Xazin** [comment]
> Thanks for the reference @Xazin. Perhaps should I move this issue in the `editor_repo`?

No need, it's fine, we can still link to this issue from the PR.

**Comment by AmanNegi** [comment]
Okay great! :smiley_cat:
