### ISSUE TITLE
[FR] Enable users to edit without opening up the event

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2383]
### Description

Instead of clicking on the event to edit, I'd like to edit the event title, for example, directly on the calendar

### Impact

Calendar users

**Comment by richardshiue** [comment]
I'm worried that the day boxes in the calendar will be too cramped to make the text editing area usable enough. Are we sure we want this?

**Comment by annieappflowy** [comment]
Would it be easier for a user to make a quick change if we allow them to edit the event title directly? You can try this out on a Board card. 

I agree that allowing every property to be editable on the calendar view may introduce more hassle than a convenience.

**Comment by annieappflowy** [comment]
Here is a screenshot of how a record can be quickly updated without expanding it in Airtable:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/12026239/235851250-099764c8-da02-4db3-a103-953a19bcccaf.png">
