### ISSUE TITLE
[Bug] The + button on a calendar doesn't have a good contrast in dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2385]
### Bug Description

<img width="156" alt="image" src="https://user-images.githubusercontent.com/12026239/235155468-8cc29b94-e850-4569-b18a-8087ca44db08.png">

### How to Reproduce

Turn on dark mode
Create a calendar
Hover on a `+`

### Expected Behavior

Good contrast 
More polished look

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by richardshiue** [comment]
Hello @annieappflowy! I've addressed this in #2353 and added some screencaps in the comments, but there is still that dilemma between the light grey and the contrasting blue colors. That's the reason I'm not marking this issue as solvable by it yet.

![image](https://user-images.githubusercontent.com/71320345/235170544-604f2f79-0447-424a-a843-6adc6db8b8a0.png)
