### ISSUE TITLE
[Question] Virus scan of .exe results

### ISSUE THREAD

**Issue by link-leocorde** [AppFlowy-IO/AppFlowy#2389]
### Bug Description

I uploaded [AppFlowy_0.1.3_windows-x86_64.exe on virustotal.com](https://www.virustotal.com/gui/file/16921d7e665b2f275809140f2e75d9b21b3551ee62b330a4855c467b13bdef25) and there were some findings. I was hoping you could give me assurance before I install this on a Windows machine.

### How to Reproduce

Scan the file again on virustotal.com

### Expected Behavior

No results

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.3

**Comment by annieappflowy** [comment]
Can you add a screenshot of the messages you got?

**Comment by link-leocorde** [comment]
In [the link I posted above](https://www.virustotal.com/gui/file/16921d7e665b2f275809140f2e75d9b21b3551ee62b330a4855c467b13bdef25), you can see there are audit findings.
