### ISSUE TITLE
[FR] Esc to exit the link editing mode without saving the input

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2393]
### Description

I can press ESC to exit the link editing mode without saving the entered text if any.
I can press ESC again to close up the link menu.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/12026239/235340520-e296da6d-13ec-48ce-8251-213f687a9728.png">

### Impact

Shortcut users

**Comment by Narcos101** [comment]
Can you please assign me this issue?

**Comment by annieappflowy** [comment]
Assigned. Thanks @Narcos101 for offering the help.

**Comment by Narcos101** [comment]
@annieappflowy Can you assign me a mentor?

**Comment by annieappflowy** [comment]
Please contact @a-wallen if you need help or guidance.

**Comment by a-wallen** [comment]
My discord is a-wallen#0603

**Comment by annieappflowy** [comment]
@Narcos101 , can this get done by Friday? Hope it can be included in the upcoming release (v0.1.5)

**Comment by glunkad** [comment]
@annieappflowy Is the issue available to work on?

**Comment by annieappflowy** [comment]
Yes, I think so. Would you like to work on it, @glunkad ?

**Comment by vincenzoursano** [comment]
@annieappflowy this task should be solved, see https://github.com/AppFlowy-IO/appflowy-editor/pull/124

**Comment by glunkad** [comment]
Hey @annieappflowy , sorry I wont be able to work on the issue.

**Comment by annieappflowy** [comment]
Fixed
