### ISSUE TITLE
[Bug] Infinite loop when editing row

### ISSUE THREAD

**Issue by qinluhe** [AppFlowy-IO/AppFlowy#2400]
### Bug Description

When editing a row, adding an attribute, and setting its type to `Number`, it causes an infinite loop, and the console prints infinitely

### How to Reproduce

1. New Grid/Board  and open console
2. Click an empty row and open the row card
3. Click `grid.field.newColumn`
4. Change the new attribute to Number,  it causes an infinite loop, and the console prints infinitely

### How to open console

1. Right click on the inspect element

### Expected Behavior

Set to what type should not loop infinitely

### Operating System

macos

### AppFlowy Version(s)

develop branch

**Comment by Ascarbek** [comment]
I couldn't reproduce the error, maybe it was fixed by backend changes
