### ISSUE TITLE
[Bug] The view update error when clicking `New` in the board view

### ISSUE THREAD

**Issue by qinluhe** [AppFlowy-IO/AppFlowy#2401]
### Bug Description

Duplicate card on view update when clicking `New` in board view

### How to Reproduce

1. New Board
2. Click `New` 
3. 65 cards will be added

### Expected Behavior

Clicking `New` once should only add a card

### Operating System

macos

### AppFlowy Version(s)

develop branch

### Screenshots

https://user-images.githubusercontent.com/108015703/235395238-6439b25f-55b3-4a28-8460-463f4319bc30.mov

**Comment by Ascarbek** [comment]
this bug is related to backend events not firing correctly
