### ISSUE TITLE
[Bug] "light" shows up in the theme option list

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2402]
### Bug Description

<img width="583" alt="image" src="https://user-images.githubusercontent.com/12026239/235406700-f8930ff3-6c4e-40a7-8a51-2411f2395034.png">

### How to Reproduce

It was on the dark mode. Then I switched to the light mode.

### Expected Behavior

We only have "Default", "Lavender", and "Dandelion"
"light" shouldn't appear in the theme list

### Operating System

Windows 10

### AppFlowy Version(s)

main branch

**Comment by BijayKumarPun** [comment]
Hi @annieappflowy, I'd like to work on this please - can assign me.

**Comment by a-wallen** [comment]
Thanks @BijayKumarPun! You've been assigned.
