### ISSUE TITLE
[Bug] The Numbers property value shown on the calendar 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2410]
### Bug Description

<img width="108" alt="image" src="https://user-images.githubusercontent.com/12026239/235422519-01b96c82-2b18-449c-95f5-8fbeb6e0512e.png">

The font size for the Numbers property value seems a bit larger than the rest, making the look less polished

### How to Reproduce

Create an event
Add a Numbers property
Give it a number

### Expected Behavior

More polished 

### Operating System

Windows 10

### AppFlowy Version(s)

main branch

**Comment by a-wallen** [comment]
Thanks @akarsh-jain-790 you've been assigned!

**Comment by annieappflowy** [comment]
Thanks @akarsh-jain-790 for offering the help!
I'd like to let you know that we need to include this bug fix in the upcoming release (v0.1.4).
Would it be ok for you to submit a PR by May 4th? If you feel a bit rush, I can help you find another issue to work on.

**Comment by akarsh-jain-790** [comment]
@annieappflowy Sure, I'd be happy to submit a PR for this bug fix by May 4th.
