### ISSUE TITLE
[FR] Hovering on an event card

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2417]
### Description

When hovering on an event card, there should be a hover effect indicating the card is being hovered on
<img width="169" alt="image" src="https://user-images.githubusercontent.com/12026239/235588148-50c94a8f-e0f7-43b3-a1bf-83eb1818999d.png">

### Impact

Calendar users

**Comment by richardshiue** [comment]
I'd like to implement this using FlowyHover, but I don't like how it overrides the Theme for the children. I'll look into it.

![image](https://user-images.githubusercontent.com/71320345/235637481-0f063524-d4a7-4a3a-a2f0-fc6096785c6a.png)

**Comment by richardshiue** [comment]
Hello @hyj1204, do you happen to know of a way to use FlowyHover in the widget only and not apply the Theme to child Overlays?

**Comment by richardshiue** [comment]
> Hi @richardshiue, I was digging into it and found there have two GestureDetectors placed within the event card area, I think that's the reason why we got weird text color changes. You can set a fixed text color in the widget if you don't want it changes when it hovers, like here ![image](https://user-images.githubusercontent.com/14248245/237178987-b138bb154-4603-4b8b-84be-5e96eb4d473b.png) Excuse me hijack this issue :)

Alrighty then, thanks so much!
