### ISSUE TITLE
[Bug] Vertical alignment

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2420]
### Bug Description

<img width="763" alt="image" src="https://user-images.githubusercontent.com/12026239/235607694-602d3d66-8a64-4d79-9665-11c873c25ae1.png">

Not sure if it's just me
The icons in the row detail page are not left aligned

### How to Reproduce

Create a calendar view
Create an event
Open up the event card

### Expected Behavior

Icons are vertically left aligned?

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by annieappflowy** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/12026239/235608408-c2c3f539-e95c-4050-b8bc-c548097ec37d.png">

The same issue for property names

**Comment by richardshiue** [comment]
The icons are slightly off, seemingly because of their different sizes. As for the property names, I just tested by using a high-tech plastic ruler against my screen. I think it's an optical illusion

**Comment by richardshiue** [comment]
Update: The svg sizes are all 16x16, but how they're actually drawn in that 16x16 picture varies. @annieappflowy this could use the `needs-design` and `help-wanted` labels!
