### ISSUE TITLE
[Task] Create an iOS version of the application

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#243]

**Comment by ihgann** [comment]
If it means anything, Notion syncing with my iPhone is hands-down the primary reason I would have to stick with it over AppFlowy. I use Notion on my phone for GTD task capture and quick note capture, so getting iOS support would probably be the killer feature of AppFlowy to get me to switch over fully.

**Comment by niftylettuce** [comment]
Can I sponsor this somehow?

**Comment by ZJsheep** [comment]
I am also interested... Actually I am desperately wanting it for my iPad.

**Comment by rabble** [comment]
I'd love to see this.

**Comment by KoStard** [comment]
What are the main blockers for this to happen? Without this, I won't be able to move to AppFlowy, even though it looks very promising :/

**Comment by annieappflowy** [comment]
@glowingkitty @KoStard you can build Android and iOS using the current codebase. A community member has successfully built an Android package using our codebase - it's quite straightforward! The thing is you can't just copy the desktop's UX to mobile as it wouldn't give the user the best mobile experience right?

**Comment by ghzgod** [comment]
> We're working on the mobile design!
> The spoiler:
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/12026239/208807395-9bc6940c-3461-42be-bcbd-982ee7518512.png">

How is it coming along?

**Comment by ThinkSalat** [comment]
Please allow swiping a line/block to change indentation. It's such a major QOL improvement. Also mobile support should be a no brainer on any note taking/pkm application.

**Comment by LucasXu0** [comment]
@ghzgod We will start developing it in Apr.

**Comment by LucasXu0** [comment]
> swiping a line/block to change indentation

Hey, @ThinkSalat. I'm not sure I understand. For example, if we swipe the line 'World' below 'Hello', it becomes indented with a sub-bullet like this:

**Before**
* Hello
* World


**After**
* Hello
  * World

Is that what you mean?

**Comment by Avalarion** [comment]
@LucasXu0 do you need beta testers?

**Comment by rjorgenson-ns** [comment]
any updates on this? really wanting to get into using this but mobile access is pretty much a requirement for me

**Comment by LucasXu0** [comment]
@rjorgenson-ns still wip. Here're some previews.

<img width="596" alt="Screenshot 2023-12-18 at 16 30 41" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/f16b6b7e-94e5-42f4-ac69-e4e755a836fc">
<img width="596" alt="Screenshot 2023-12-18 at 16 30 14" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/b7f23185-aa25-4b33-8630-ff61d44c5fd8">
<img width="596" alt="Screenshot 2023-12-18 at 16 30 12" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/41ee1d49-9913-47d2-8022-bed0fe42fa34">

**Comment by natedwhite** [comment]
Is there an iPad version planned?

**Comment by annieappflowy** [comment]
@natedwhite , we've not received enough requests to prioritize it. Please feel free to submit a feature request

**Comment by mcmxcdev** [comment]
Why was this closed? There is no iOS release available yet afaik, so the requirements of this ticket are not fulfilled yet.

**Comment by annieappflowy** [comment]
It's on the test flight. We've started sending out invites.
@mcmxcdev , please sign up [here](https://tally.so/r/mYaP1B)
