### ISSUE TITLE
[FR] Support `Checkbox` and `CheckList` in Cell

### ISSUE THREAD

**Issue by qinluhe** [AppFlowy-IO/AppFlowy#2431]
### Description

- [ ] Support `Checkbox`
- [ ] Support `CheckList`
- [ ] Support Grid and Board

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/108015703/235658304-6b062c0f-da81-42e5-bcaf-f6f9c41c623c.png">

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/108015703/235658520-fe4495e6-26c3-4d0e-a9ba-93ef4c4b94a1.png">

### Impact

User who use Tauri

### Additional Context

UI Design
https://www.figma.com/file/X1R9i5HAFtJSNIKOPPW7yK/AppFlowy-%5BUI%5D%5BMaster%5D?type=design&node-id=0-1&t=ugrwABn5OzzdsiEl-0

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/1692
The current implementation for Checklist in Flutter needs to change. Please refer to the issue I linked.

**Comment by appflowy** [comment]
The checklist was reimplemented. Each cell can has its own options. check out this PR #2653

**Comment by fangwufeng-v** [comment]
got it
