### ISSUE TITLE
[Bug] Sorting numbers column done incorrectly as text

### ISSUE THREAD

**Issue by ljsalvatierra** [AppFlowy-IO/AppFlowy#2438]
### Bug Description

If you sort a `Numbers` column, it sortes as text. Also, i cannot undone the sorting, stays with the last order even when i remove the sort fields.

### How to Reproduce

Create a grid with multiple a `numbers` column and sort, ascending or descending.

### Expected Behavior

1,2,3,4,...

instead of

1, 10, ...

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.3

### Screenshots

![image](https://user-images.githubusercontent.com/5963328/235838265-04429d5c-af62-41d9-a44f-edbad1ef279c.png)

**Comment by annieappflowy** [comment]
Hi @ljsalvatierra , thanks for reporting. We fixed it in v0.1.4.
You can download the latest release from [here](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.4). Look forward to getting more feedback from you.

**Comment by ljsalvatierra** [comment]
Hi @annieappflowy 

Thanks for the update :) unfortunately it doesn't work in this version either.

![image](https://user-images.githubusercontent.com/5963328/236608695-90f6b603-6bcd-4c6e-9972-d89ae998b365.png)

![image](https://user-images.githubusercontent.com/5963328/236608736-fda8a416-4853-43a7-b6b3-286e2a7cb235.png)

**Comment by annieappflowy** [comment]
Oops my bad. Sorry :( Reopen this issue

**Comment by ljsalvatierra** [comment]
> Oops my bad. Sorry :( Reopen this issue

No problem at all! Thank you for your time!

**Comment by appflowy** [comment]
Hi @ljsalvatierra. Already fixed, will release a new version for this.
Ascending:
<img width="969" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86001920/27c30200-0236-462c-b81f-a57a98ff546d">

Descending
<img width="956" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86001920/69c71b67-b4d1-45cb-9374-70aa8797b684">

**Comment by ljsalvatierra** [comment]
> Hi @ljsalvatierra. Already fixed, will release a new version for this. Ascending: <img alt="image" width="969" src="https://user-images.githubusercontent.com/86001920/243282123-27c30200-0236-462c-b81f-a57a98ff546d.png">
> 
> Descending <img alt="image" width="956" src="https://user-images.githubusercontent.com/86001920/243282312-69c71b67-b4d1-45cb-9374-70aa8797b684.png">

awesome, thank you!
