### ISSUE TITLE
[Bug] Highlight default background

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2451]
### Bug Description

If I highlight in purple, there is no way to go back plain

### How to Reproduce

Highlight text in purple

### Expected Behavior

There should be an option for me to undo highlight in any color

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by annieappflowy** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/12026239/236114961-2ce2ddee-539f-44f3-a48f-ed475689f431.png">

When choosing this default background option, the highlight color is changed to blue, although it should've undone any highlight color.

**Comment by vuzzer** [comment]
Hey @annieappflowy, could you assign it to me.

**Comment by annieappflowy** [comment]
Assigned! Thank you

**Comment by vuzzer** [comment]
Hey @annieappflowy, if `default background` option is to remove the background color, it would be better to rename this option to `remove background`. What do you think about it ?

**Comment by annieappflowy** [comment]
@vuzzer , "clear background" or "none"?

**Comment by annieappflowy** [comment]
Hi @vuzzer , can this be done by Friday? Hope this bug can be fixed by Friday in the upcoming release (v0.1.5)

**Comment by vuzzer** [comment]
Hey @annieappflowy, of course, it will be done before Friday.

**Comment by richardshiue** [comment]
My two cents:

- I thought that the default background color depends on the theme, in this case it's blue.
- The current way to de-highlight (if that's a word) text is to click on the button again. However, there is a bug where if a color other than the default were selected, it would first clear the custom color (and use the default), and then a subsequent selection and click will de-highlight the default highlight color. 

    ![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/a9969b60-5c33-446a-ae12-bf409638d52e)

- It definitely would be better if I can also deselect color by clicking on it (e.g. if it's highlighted purple, I can click on purple and it will be de-highlighted).

**Comment by vuzzer** [comment]
I have difficulties to detect in the code base the part dedicated to the menu that appears when you select a text. I don't think I can solve this Friday.However, I am actively working on this problem. Any help is welcome. @annieappflowy  @richardshiue 


> Hey @annieappflowy, of course, it will be done before Friday.

I have difficulties to detect in the code base the part dedicated to the menu that appears when you select a text. I don't think I can solve this Friday.However, I am actively working on this problem. Any help is welcome. @annieappflowy  @richardshiue

**Comment by vuzzer** [comment]
> Hey @annieappflowy, of course, it will be done before Friday.

I have difficulties to detect in the code base the part dedicated to the menu that appears when you select a text. I don't think I can solve this Friday.However, I am actively working on this problem. Any help is welcome. @annieappflowy @richardshiue

**Comment by vuzzer** [comment]
> My two cents:
> 
> * I thought that the default background color depends on the theme, in this case it's blue.
> * The current way to de-highlight (if that's a word) text is to click on the button again. However, there is a bug where if a color other than the default were selected, it would first clear the custom color (and use the default), and then a subsequent selection and click will de-highlight the default highlight color.
>   ![image](https://user-images.githubusercontent.com/71320345/237297785-a9969b60-5c33-446a-ae12-bf409638d52e.png)
> * It definitely would be better if I can also deselect color by clicking on it (e.g. if it's highlighted purple, I can click on purple and it will be de-highlighted).

I have found this problem as well @richardshiue. I have difficulties to detect in the code base the part dedicated to the menu that appears when you select a text.

**Comment by Xazin** [comment]
This is an issue with the software design. Text background and highlight are two separate things, thus causing this weird behavior, whilst they should either be the same feature, or there should be noticeably different behavior.

**Comment by vuzzer** [comment]
of course, although I have activated **Select widget mode**, to determine the toolbar that appears when you underline the text, it detects every time this widget `AppFlowyEditor`.

**Comment by annieappflowy** [comment]
Thanks @vuzzer for letting us know. I moved this issue to v0.2

**Comment by LucasXu0** [comment]
Hey, @vuzzer. You can take a look in the appflowy_editor mobile branch. we have removed the highlight item and separated the text color and the background color into two items.

**Comment by vuzzer** [comment]
> Hey, @vuzzer. You can take a look in the appflowy_editor `mobile` branch. we have removed the highlight item and separated the text color and the background color into two items.

Hey @LucasXu0, Thank you very much, I am looking into it.
