### ISSUE TITLE
[Bug] Nested checkmark list is missing in markdown

### ISSUE THREAD

**Issue by c4lliope** [AppFlowy-IO/AppFlowy#2452]
### Bug Description

Here is a sample document:

![image](https://user-images.githubusercontent.com/30454698/235923664-138be789-637d-4e3f-8a13-f07fc2c13b78.png)

Here is the rendered markdown from the "Share" menu:

```markdown
# Welcome to AppFlowy!
## Here are the basics
- [ ] Click anywhere and just start typing.
- [ ] Highlight any text, and use the editing menu to _style_ **your** <u>writing</u> `however` you ~~like.~~
- [ ] Type `/` followed by `/bullet` or `/num` to create a list.
- [x] Click `+ New Page `button at the bottom of your sidebar to add a new page.
- [ ] Click `+` next to any page title in the sidebar to quickly add a new subpage, `Document`, `Grid`, or `Kanban Board`.
```

You can see the indented checkmark line is missing in the export.

### How to Reproduce

* [ ] Make a checkmark list
  * [ ] indent a sub-checkmark
* [ ] Share as markdown

### Expected Behavior

All checkmarks should be recorded with the necessary indentation.

### Operating System

Linux

### AppFlowy Version(s)

0.1.3

**Comment by Xazin** [comment]
It should be mentioned that the same occurs to bulleted lists.

Indented entries are missing from the exported markdown.

**Comment by Amartya-Mahato** [comment]
seems like the problem is in appflowy_editor 0.1.9

**Comment by saru2020** [comment]
[this](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/lib/src/plugins/markdown/encoder/parser/text_node_parser.dart) is where the issue lies, the `text_node_parser` isn't considering `indentation`
