### ISSUE TITLE
[Bug] Run appyflowy in docker,but it not work: cannot open display: :0

### ISSUE THREAD

**Issue by walker83** [AppFlowy-IO/AppFlowy#2458]
### Bug Description

xhost +
docker run --rm   -v $HOME/.Xauthority:/root/.Xauthority:rw   -v /tmp/.X11-unix:/tmp/.X11-unix   -v /dev/dri:/dev/dri   -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket   -v appflowy-data:/home/appflowy   -e DISPLAY=${DISPLAY}   appflowyio/appflowy_client:main

(app_flowy:1): Gtk-WARNING **: 01:27:57.247: cannot open display: :0

### How to Reproduce

Add the --network=host parameter to the Docker container to use the host's network. This will allow the Docker container to access the host's X server.

docker run --rm --network=host -v $HOME/.Xauthority:/root/.Xauthority:rw -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/dri:/dev/dri -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket -v appflowy-data:/home/appflowy -e DISPLAY=${DISPLAY} appflowyio/appflowy_client:main

### Expected Behavior

Now it works

### Operating System

Ubuntu 22

### AppFlowy Version(s)

main

**Comment by annieappflowy** [comment]
Docker is not officially supported by us. We'll start working on it once our web version is released.

**Comment by walker83** [comment]
Thanks a lot. 
I add the param 
**--network=host**

and it works

**Comment by annieappflowy** [comment]
Thanks @walker83 
Adding your findings to our troubleshooting page as a reference to help other folks :D

**Comment by annieappflowy** [comment]
https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/troubleshooting
