### ISSUE TITLE
[Bug] Unable to update the property name

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2467]
### Bug Description

<img width="249" alt="image" src="https://user-images.githubusercontent.com/12026239/236611153-911437d6-5373-454f-8f9d-126b47b61bac.png">

### How to Reproduce

Add a new column
Edit its name

### Expected Behavior

I can update column names

### Operating System

Windows 11

### AppFlowy Version(s)

v0.1.4

**Comment by annieappflowy** [comment]
Wont let me change the property type

**Comment by SaifEl-Deen** [comment]
This only occurs when trying to edit a property within a mentioned kanban with the /Referenced Board or /Create New Board.
