### ISSUE TITLE
[Bug] Add cover in Dandelion

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2469]
### Bug Description

https://user-images.githubusercontent.com/12026239/236622141-e23820f9-ea8b-46d0-9acb-cf1750e68c48.mp4

### How to Reproduce

Go to Settings
Choose Dandelion Theme
Create a new document
Add a cover

### Expected Behavior

Cover button only appears in one place
Cover page is properly placed

### Operating System

Windows 11

### AppFlowy Version(s)

v0.1.4

**Comment by annieappflowy** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/12026239/236623082-55373e69-ef06-4b46-8208-0b799bd0aadf.png">


Similar issues using the light mode

**Comment by rizwan3395** [comment]
Hi @annieappflowy, I followed the steps to reproduce but I couldn't reproduce it on my end. Is there anything I am missing out?

https://user-images.githubusercontent.com/47111784/236689234-c3de4507-414c-448b-a816-2b7bf61c84b3.mp4
