### ISSUE TITLE
[Bug] Rearrange columns

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2470]
### Bug Description

Dragging a column to another place doesn't work sometimes

https://user-images.githubusercontent.com/12026239/236666527-986a93a8-5dbe-4d73-b4b4-ca0156e3ae8d.mp4

### How to Reproduce

Long press a column to place it in between another two columns

### Expected Behavior

I can rearrange properties by long pressing a column and placing it in another location

### Operating System

Windows 11

### AppFlowy Version(s)

v0.1.4

**Comment by yumin2002** [comment]
I am not able to replicate the bug with v0.1.5 on macos Monterey. I am not sure if this issue is only related to windows or v0.1.4. Could you double check if the same issue presists in the latest version?
