### ISSUE TITLE
[Bug] Open row as a page

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2473]
### Bug Description

<img width="777" alt="image" src="https://user-images.githubusercontent.com/12026239/236737336-b1465e07-76f2-4848-b1ab-9ebc3869e2eb.png">

![Xnip2023-05-08_12-58-19](https://user-images.githubusercontent.com/12026239/236737739-e1c83d8b-42de-4642-a27a-44a199345b63.jpg)

### How to Reproduce

Create a grid
Open row as a page

### Expected Behavior

The first property shows up when opening up a row

### Operating System

MacOS

### AppFlowy Version(s)

v0.1.4

**Comment by richardshiue** [comment]
This is related to #2460, I made whichever field is the "primary" field at the top and instantly editable. In the first screenshot, it seems like the "Done" is the primary field.
