### ISSUE TITLE
[FR] add duplicate to :: that appears to the left of each row on hover

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2474]
### Description

Duplicating a row is available via open row as a page.
Add this action to the `::` menu that appears on hover to the left of each row.
<img width="524" alt="image" src="https://user-images.githubusercontent.com/12026239/236740996-a59bef60-8cdb-446f-b651-e7154b8ae4a5.png">

### Impact

Table-view database users can quickly perform a duplicate action on a row

**Comment by rizwan3395** [comment]
@annieappflowy Can you assign this task to me, if no one else is working on it.
