### ISSUE TITLE
[Bug] Displaying 'Bahasa' instead of 'Bahasa Indonesia' when referring to the Indonesian language

### ISSUE THREAD

**Issue by Catyousha** [AppFlowy-IO/AppFlowy#2477]
### Bug Description

Since 'Bahasa' means 'Language', mention Indonesian language as just 'Bahasa' is as odd as referring 'the English language' as just 'Language'. 

### How to Reproduce

Simply go to Setting > Language

### Expected Behavior

When navigating to the Settings menu to switch languages, the string in dropdown display shows 'Bahasa Indonesia' instead of just 'Bahasa'.

### Operating System

Windows 11

### AppFlowy Version(s)

v0.1.4

### Screenshots

![image](https://user-images.githubusercontent.com/20609509/236786732-b24c58de-57a7-4f4e-bb73-33e79a0e93b3.png)

**Comment by BijayKumarPun** [comment]
Hi @annieappflowy, could you please assign me this task?

**Comment by annieappflowy** [comment]
Thanks @BijayKumarPun  for offering the help. Assigned.
