### ISSUE TITLE
[Bug] Cursor left word delete shortcut

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2496]
### Bug Description

Cursor left word delete ( CMD + DELETE) doesn't work as intended
It deletes the entire sentence.

### How to Reproduce

Write a sentence include more than two words.
cmd + delete

### Expected Behavior

It deletes cursor left word

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by Xazin** [comment]
Are you sure this is not as intended? CMD + BACKSPACE on MacOS defaults to deleting a sentence, whereas OPTION + BACKSPACE deletes a word on MacOS.

Currently it's implemented like the default behavior.

**Comment by annieappflowy** [comment]
I was referring to our shortcuts [guidebook](https://appflowy.gitbook.io/docs/essential-documentation/shortcuts)
We should update the guide instead

**Comment by Xazin** [comment]
I will update it, and double check that all shortcuts are currently on the same keybindings as described. :+1:
