### ISSUE TITLE
[FR] Show Calculate Option on last row of the Grid

### ISSUE THREAD

**Issue by yusufmalikul** [AppFlowy-IO/AppFlowy#2499]
### Description

The grid page is great. Thanks for building this!

I want to request a feature that shows some calculations (sum, average, max, min, etc) below the grid.

### Impact

People that need quick calculations to summary their data will benefit from this.
Screenshot from my Notion page:

<img width="832" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/15918537/a5e15b9a-b48d-4817-82ab-ed55d6d9177e">

**Comment by tomlevisse** [comment]
Yeah, it would be great !

**Comment by annieappflowy** [comment]
Supported
<img width="426" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/55087d8c-989f-4033-a142-11a282a35174">
