### ISSUE TITLE
[FR] Auto markdown formatting

### ISSUE THREAD

**Issue by Calcium3d** [AppFlowy-IO/AppFlowy#25]
**1~3 main use cases of the proposed feature**
Writing in markdown, will automatically convert that into the proposed element. For example, if I type a # with a space, it should auto convert that into a heading 1 instead of showing the hash, basically what happens if I click the button on the bottom toolbar instead

**Additional context**
![image](https://user-images.githubusercontent.com/56835743/142386648-90bda60e-63b9-4658-a069-96780e062eba.png)
currently, this is what happens when I try to type in markdown (up), I would like it to be this (down), 
![image](https://user-images.githubusercontent.com/56835743/142387037-74ed7e42-5aa5-4957-a118-0b68b85c9f3a.png)

**Comment by Zenyet** [comment]
agree.

**Comment by MeJackie** [comment]
agree

**Comment by Lloyd-Jackman-UKPL** [comment]
This is basically a Typora kind of interface, right? If so, agree but would argue there should be an option to view the raw markdown, or the rendered view.

**Comment by notd5a-alt** [comment]
Definetely agree to that. I type better in the raw markdown mode.

**Comment by Dernbu** [comment]
I'd like to suggest that markdown is good and all, but **may not be the way to go**. I think there are lots of benefits with markdown, but it simply isn't the solution to everything. I think one good example is the excel-style tables/databases in Notion (which is personally the selling point for me for the app), to have things like custom sorts, custom filters and all. I mean, it's definitely not impossible to implement with markdown, but I feel that using markdown in such an early stage of development boxes the app out of having certain features. Maybe a better approach will be to have markdown as an optional plugin, or to support things like cells (e..g Jupyter notebooks), also as an optional plugin.

**Comment by Lloyd-Jackman-UKPL** [comment]
That's a really interesting and important point. When you use Typora, you can see it clearly takes a "code block" approach in Source Code Mode, looking very familiar to me as a Jupyter user. I certainly wouldn't see any conflict with treating these blocks as of different types, but would only note that Jupyter limits your designs to a degree by not supporting more complex kinds of formatting, such as columns or tiles. Imagining a a page as a set of dynamically sized tiles that could be snapped into place, each having a type (markdown, board, table etc.) could be very powerful and visually appealing.

Lloyd Jackman

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Poly-Pixel** [comment]
I like Lloyd-Jackman-UKPL's idea:
> Imagining a a page as a set of dynamically sized tiles that could be snapped into place, each having a type (markdown, board, table etc.) could be very powerful and visually appealing.

It would be nice if pages would operate on a plugin-based system, where each plugin defines one or more tiles that can be used in the page. Some plugins could be included in the app by default (like Markdown), while others could be installed through the plugin marketplace. The plugins would likely have their own settings so that things like raw/rendered view could be managed. I know that the AF team has a plugin system in mind, although I'm not sure how it's planned to be implemented at the moment. Any thoughts?

**Comment by annieappflowy** [comment]
Thanks a lot for sharing your inputs. 

@Poly-Pixel your points totally make sense to me. I like it to be customized by having a plugin marketplace where users can download and install things that they prefer. Following this logic, Markdown can be a pre-installed plug-in which can be uninstalled by the user, so basically it's optional.

In terms of the tech design, @LucasXu0 will share more on this thread

**Comment by annieappflowy** [comment]
I also second to @Lloyd-Jackman-UKPL 's idea

**Comment by annieappflowy** [comment]
Hello folks on this thread,

Markdown is supported. Please refer to our Markdown guide in terms of how to use it and what it's available: https://appflowy.gitbook.io/docs/essential-documentation/markdown

Look forward to getting your feedback on this feature.

**Comment by annieappflowy** [comment]
Here is the link to download our latest release: https://github.com/AppFlowy-IO/AppFlowy/releases
