### ISSUE TITLE
[Bug] Does not save the configuration

### ISSUE THREAD

**Issue by avenfenix** [AppFlowy-IO/AppFlowy#2500]
### Bug Description

When I change settings and re open the app settings are reset. 

### How to Reproduce

Settings like theme or language

### Expected Behavior

It should save and restore the previous state.

### Operating System

Windows

### AppFlowy Version(s)

0.1.4

**Comment by yumin2002** [comment]
Can I try to work on this issue? Thanks!

**Comment by annieappflowy** [comment]
Assigned. Thank you, @yumin2002

**Comment by yumin2002** [comment]
On my end, settings like themes are preserved while language is not. The code seems correct for me (appflowy_flutter/lib/startup/tasks/app_widget.dart:InitAppWidgetTask::initialize). I think what this function does is basically get the appearance settings and create the application widget based on it. After the application widget is created, we localize and run the app.
Here is the documentation link for easy_localization package: https://pub.dev/packages/easy_localization.

As a newcomer, I am not very familiar with the project, I wonder when the exising user notes gets imported to the app(specifically which of the four startup tasks)?  Can anyone share a little bit on that?

**Comment by yumin2002** [comment]
@annieappflowy Can I have a mentor? I might need some guidance to understand the architecture while I am going through the codebase. Thanks!

**Comment by annieappflowy** [comment]
Hi @yumin2002 , your mentor is @LucasXu0 . You can reach him on Discord.
