### ISSUE TITLE
[Bug] Documentation outdated page link

### ISSUE THREAD

**Issue by tomlevisse** [AppFlowy-IO/AppFlowy#2505]
### Bug Description

On the official documentation in the link, link is no more available

https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/how-tos/how-to-create-a-plugin-for-appflowy-editor

The link url may have changed by thise one now -> [https://github.com/AppFlowy-IO/appflowy-editor/blob/main/documentation/customizing.md](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/documentation/customizing.md)

### How to Reproduce

- Go to page [How to Create a Plugin for AppFlowy Editor](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/how-tos/how-to-create-a-plugin-for-appflowy-editor)
- Clink on the link
- 404 Response

### Expected Behavior

Page shall redirect to an existing link

### Operating System

None

### AppFlowy Version(s)

v1.0.4

**Comment by ArslanYM** [comment]
Would love to fix this ASAP.

**Comment by annieappflowy** [comment]
I can assign this issue to you, @ArslanYM , if you'd like to take a stab.

**Comment by ArslanYM** [comment]
Sure thing > I can assign this issue to you, @ArslanYM , if you'd like to take a stab.

**Comment by ArslanYM** [comment]
@annieappflowy These changes need to made in the appFlowy-docs repo right?

**Comment by annieappflowy** [comment]
Yes
