### ISSUE TITLE
[Bug] Calendar properties are not translated correctly in French

### ISSUE THREAD

**Issue by tomlevisse** [AppFlowy-IO/AppFlowy#2513]
### Bug Description

The calendar properties are not translated in french, as showed in screenshots

### How to Reproduce

1. Go to a calendar view
-> There date counter which is not translated correctly in french
3. Click on "Paramètres" 
4. Then you see Layout which is not translated
5. Click on "Layout"
6. Layout proposals are not translated

### Expected Behavior

In case AppFlowy is set in French, you shall have a correct translation to interact with it.

Proposed translation:

Layout -> Disposition 
No date(0) -> Aucune date or Aucun Evènement
Layout calendar by -> mise en page du calendrier par
Start week on -> Premier jour de la semaine

### Operating System

Windows 10

### AppFlowy Version(s)

V0.1.5

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/46441884/d9ff2356-3cad-44de-b2a4-57687acd5c2e)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/46441884/b8871c3c-91c7-411e-a7ea-d96783bf9f50)

**Comment by Pranav2612000** [comment]
Hey 
I'll like to work on this.

**Comment by annieappflowy** [comment]
Assigned @tomlevisse 
Thanks @Pranav2612000 and @tomlevisse both for offering the help

**Comment by annieappflowy** [comment]
<img width="227" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/59499505-4ad1-457c-8edc-eec321d25f27">
