### ISSUE TITLE
[Bug] Renaming a new property in a referenced grid is not saved and immediately closes the renaming box on following try

### ISSUE THREAD

**Issue by SaifEl-Deen** [AppFlowy-IO/AppFlowy#2519]
### Bug Description

Right after creating a new property in a referenced grid, the box for renaming appears, typing anything then pressing enter won't save the change.
In addition to that, when I try to edit the name, it gets closed as soon as I type any letter.

### How to Reproduce

1. Create a document
2. Mention/reference a grid
3. Add a new property
4. Try to name/rename it, it wi

### Expected Behavior

To be able to name/rename a newly created property in a referenced grid.

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.5

### Screenshots

![Animation](https://github.com/AppFlowy-IO/AppFlowy/assets/130001839/1230c7db-2902-41a4-bd8c-008edec2df53)

### Additional Context

If you create a new property then switch to another document/kanban/grid whatever, then switch back to the document where you had referenced that grid, you can now name/rename the property normally

**Comment by annieappflowy** [comment]
Can you give it a try using the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases)?
