### ISSUE TITLE
[Bug] Strange behaviour when re-ordering files

### ISSUE THREAD

**Issue by SaifEl-Deen** [AppFlowy-IO/AppFlowy#2520]
### Bug Description

When I drag and drop a file in the left menu, the file gets dropped in a random position instead

### How to Reproduce

1. Create some files
2. Required: Some of the files are duplicated? (i.e View of Untitled)
3. Try to drag and drop random files

### Expected Behavior

To drop the file where the cursor is

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.5

### Screenshots

![Animation](https://github.com/AppFlowy-IO/AppFlowy/assets/130001839/8ed79f06-41b4-4238-a934-73f451aa5d70)

**Comment by Xazin** [comment]
I wasn't able to reproduce on MacOS on `main:d44de62b9051c7af79d227b8b6ffe437791b29e7`.
