### ISSUE TITLE
Calendar - Not the right day [Bug] 

### ISSUE THREAD

**Issue by TugdualDek** [AppFlowy-IO/AppFlowy#2522]
### Bug Description

Today's calendar date is not the right one

### How to Reproduce

Create a new calendar on AppFlowy

### Expected Behavior

Today's date should be correct according to the user's timezone and not according to a single defined timezone (I don't know if this is the problem but it is a guess)

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.4

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/35851118/c8fca7f0-3ea4-4ecd-9167-25cb76c35963)

**Comment by SaifEl-Deen** [comment]
You forgot to add a title for the issue 🙏

**Comment by TugdualDek** [comment]
> You forgot to add a title for the issue 🙏

Oups, i completely forgot, sorry...

**Comment by richardshiue** [comment]
Hey there @TugdualDek, just to clarify your problem, is it that the day of week not corresponding to the date, i.e. le 13 mai being vendredi instead of samedi? If so, I'd advise you to download 0.1.5 and see if it's correct there.

**Comment by TugdualDek** [comment]
Hello @richardshiue ,

Thank you for your message.
It is exactly the problem. I tried your solution, and it is now correct ! 

Thank you very much, and sorry for the inconvenience !

Thank you for all the work you are doing !
