### ISSUE TITLE
[Bug] cannot get out of callout block when added at the end of the document

### ISSUE THREAD

**Issue by Chandan-CV** [AppFlowy-IO/AppFlowy#2527]
### Bug Description

When a callout block is added at the end of the document, there is no way to get out and ahead of it. 

### How to Reproduce

1. open appflowy
2. create a new document
3. press enter till you go to the last line of the document
4. add the callout block
5. now there is no way to get the cursor ahead of this block

### Expected Behavior

adds 3 to 4 lines after the callout block to allow us to get out of it

### Operating System

Ubuntu

### AppFlowy Version(s)

0.1.4

### Screenshots

[Screencast from 14-05-23 11:50:19 AM IST.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/c31886f1-312d-4ca5-a5c9-716c38d0404a)

**Comment by Chandan-CV** [comment]
@annieappflowy Can I work on this issue?

**Comment by annieappflowy** [comment]
Thanks! Assigned.
You might need to submit a PR to https://github.com/AppFlowy-IO/appflowy-editor
cc: @LucasXu0

**Comment by LucasXu0** [comment]
Hey, @Chandan-CV. I have fixed this issue in [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/2536)

https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/9771aafd-a440-4229-9fa3-3503c06c3df7

For now, 
1. `enter` equals to move the cursor to the next line.
2. `enter + shift` equals to insert a new line at the callout block.

**Comment by Chandan-CV** [comment]
That is soo cool! I am excited to use the new editor :)

Should I close this issue?
