### ISSUE TITLE
[Bug] Grid does not update when deleting all sorts

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#2534]
### Bug Description

When you have 1 sort option enabled, and you "Delete Sort" (More specifically it runs Delete all sorts in the background), then the grid does not update, the rows stay sorted.

### How to Reproduce

- Create Grid
- Add rows
- Add sort (eg. Checkbox)
- See Grid being sorted
- Click on the Sort Chip to open popover menu
- Click on "Delete sort"
- Grid does not go back to original

### Expected Behavior

- Create Grid
- Add rows
- Add sort (eg. Checkbox)
- See Grid being sorted
- Click on the Sort Chip to open popover menu
- Click on "Delete sort"
- Grid resets to original order

### Operating System

MacOS

### AppFlowy Version(s)

main

### Screenshots

Before sorting:
<img width="522" alt="Screenshot 2023-05-14 at 21 44 42" src="https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/4e0f42db-6de4-493f-ad40-adb69c3bdae4">

After removing sort on `Done`:
<img width="511" alt="Screenshot 2023-05-14 at 21 44 24" src="https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/c10e545b-4176-4d49-9feb-0a1075e5f59f">

**Comment by appflowy** [comment]
Already fixed in develop branch.
