### ISSUE TITLE
[FR] support customizing the user avatar

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2535]
It is for the initial avatar color when the account is created and the user's name is entered. Later, we can add picking the color. Or how do you see it working?

_Originally posted by @nurmukhametdaniyar in https://github.com/AppFlowy-IO/AppFlowy/pull/2529#discussion_r1193492612_
            

For now, the background color for the avatar name is random. It will be better to provide some color options for the users to choice their prefer color.

**Comment by nurmukhametdaniyar** [comment]
Would like to take this issue

**Comment by nurmukhametdaniyar** [comment]
Or should we add uploading a user avatar instead of a color picker? But I think currently that type of upload is not supported. What do you think @LucasXu0 ?

**Comment by tomlevisse** [comment]
@nurmukhametdaniyar Would love to add a picture to personalize even more !

**Comment by LucasXu0** [comment]
@nurmukhametdaniyar the picture upload feature is not yet supported in the main branch. I suggest you start working on the UI part of the logic first. I will inform you once the picture upload feature is ready. Alternatively, you can save the avatar locally and migrate it to the cloud service later.

Also,I prefer using user avatars instead of background colors.

**Comment by nurmukhametdaniyar** [comment]
@LucasXu0 Completely agree that avatars are better than color pickers. I guess we can close this issue and open a new one. Or can you edit the name and description of it?

**Comment by LucasXu0** [comment]
Sure. I will rename it.

**Comment by annieappflowy** [comment]
<img width="72" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ab400e36-f787-433b-8bb3-673837a0e840">

Consider this issue done
