### ISSUE TITLE
[Bug] Renaming Page causes weird behavior in Menu

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#2539]
### Bug Description

When you have a page, and delete apps inside it, then rename the page, the deleted apps show up again. Then when renaming an app, the trashed apps are removed again.

This behavior persists between restarts of the application.

### How to Reproduce

1. Create a Page
2. Add apps (Document, Grid, Board, etc.)
3. Delete a couple of them
4. Rename the **parent page**
5. Deleted apps show up in menu again
6. Restart and repeat from step 4 to see persistence of the bug

### Expected Behavior

1. Create a Page
2. Add apps (Document, Grid, Board, etc.)
3. Delete a couple of them
4. Rename the **parent page**
5. Nothing changes in the menu/children of the page

### Operating System

MacOS

### AppFlowy Version(s)

main

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/b1edd013-27c3-4861-be97-afcb801100b7

**Comment by appflowy** [comment]
@Xazin Already fixed in the latest develop branch.
