### ISSUE TITLE
[Bug] Cannot run on Macbook M1 chip

### ISSUE THREAD

**Issue by JZMinilab** [AppFlowy-IO/AppFlowy#255]
**Describe the bug**
Cannot run on Macbook M1 chip

**To Reproduce**
brew install appflowy
Click application/appflowy

**Expected behavior**
Main windows shows up

**Screenshots**
Nothing shows, no process named appflowy in the activity monitor.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.1
 - Browser, both chrome and safari are installed
 - Version, chrome 97.0; Safari 15.2

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]
 
```
Running "flutter pub get" in flutter_tools...                      17.6s
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    en-CN)
    • Flutter version 2.8.1 at /opt/homebrew/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71
```

**Comment by Roms1383** [comment]
Looking at flutter doctor diagnosis, you have to follow its instructions and install:
- XCode
- Android Studio
Android toolchain is usually provided by installing Android Studio (SDK manager) AFAIR.

You might have additional issues related to the fact that M1 chip has a different architecture (`aarch64-apple-darwin` instead of `x86_64-apple-darwin` for older generations), but you should fix these first.

**Comment by JZMinilab** [comment]
Thanks for your reply but I'm confused. If I rebuild from scratch then encounter the issue, it is definitely the problem of uninstalling developing tools. However, I installed the app via brew install, how can an app depend on development tools?

**Comment by Roms1383** [comment]
`brew install` indeed should handle this on your behalf, my bad I thought you were also looking to build on your machine.

**Comment by niftylettuce** [comment]
Works for me, on Monterey

**Comment by JZMinilab** [comment]
@niftylettuce Can you show `flutter doctor -v` ?

**Comment by niftylettuce** [comment]
I don't have `flutter` installed, I installed via `brew`.

```sh
❯ flutter doctor -v
zsh: command not found: flutter
```

**Comment by JZMinilab** [comment]
Aha, I can open the app after `brew install rust`.

**Comment by MikeWallaceDev** [comment]
Hello @JZMinilab , glad to see that you got AF to run.  Maybe you can help out with the documentation so that other people won't have this problem in the future?

Admittedly, you would be the first to help with the new gitbook system, so we'll work through this together :)

Else, let us know how we can improve the documentation. All good :)

**Comment by JasonKing66** [comment]
First installation failed on M1 Mac using BREW. Tried
`brew upgrade`
`brew install flutter`
`brew install rust`
Try to make sure my development tools are all updated and I have both flutter and rust. It worked. As owner of this issue mentioned, maybe only `brew install rust` is enough. Need somebody else with a fresh M1 Mac to validate. 
<img width="1092" alt="Screen Shot 2022-01-31 at 2 43 29 PM" src="https://user-images.githubusercontent.com/15242765/151896279-c50f10e5-75d5-45c8-b719-f8c7e6fe8ce7.png">

**Comment by appflowy** [comment]
@JasonKing66 Thank you! I have updated the documentation on [Building on MacOS.](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos)
