### ISSUE TITLE
[FR] Spreadsheet data importer

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2557]
### Description

 Is there an api with which I could automatically add content? I have spreadsheet with some numbers and a text for every day (kind of a diary) which I would like to move to AppFlowy. But I would like to automatically (with a script) migrate the content from the spreadsheet to AppFlowy.

### Impact

People who want to migrate data into AppFlowy

**Comment by AndreasAZiegler** [comment]
In my case, I would like to migrate the content of an existing spreadsheet. It's sort of a diary with one row per day. I have columns with numerical values, e.g., how my day was (1-10), columns with text, e.g., what kind of sport I did or some comments. But in general, I believe it would be nice to be able to add any kind of content which AppFlowy supports via an api. This way, all sorts of migration (In my case from Joplin and Spreadsheets to AppFlowly) could be realized with some, e.g. Python scripts.

**Comment by Xazin** [comment]
A CSV import/export feature would be handy, and is probably one of the easiest to implement for a database/grid/spreadsheet.

**Comment by AndreasAZiegler** [comment]
I agree, a csv import feature would be a good first step.

**Comment by appflowy** [comment]
> @annieappflowy I can try to implement it, doesn't seem to be tricky

I think we can use the https://docs.rs/csv/latest/csv/ crate to do this.

**Comment by annieappflowy** [comment]
Currently supporting import .csv files
<img width="1883" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7772eded-1a74-429f-bfe5-7cd893014927">
