### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nurmukhametdaniyar** [AppFlowy-IO/AppFlowy#2559]
### Bug Description

The icons of the menu are not visible

### How to Reproduce

1. Open the editor
2. Type /

### Expected Behavior

Icons should be clearly visible

### Operating System

MacOS

### AppFlowy Version(s)

Latest develop branch

### Screenshots

<img width="912" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/28860230/100057c5-1a26-497e-9dd2-421818e2b0cd">

**Comment by annieappflowy** [comment]
Fixed
