### ISSUE TITLE
[FR] Collaborative edition

### ISSUE THREAD

**Issue by mibinn** [AppFlowy-IO/appflowy#256]
**use case**
As a user, i want to write documents simultaneously with other users, watching in real time their modification, so that we can't collaborate efficiently.

**what types of users can benefit from using your proposed feature**
Project managers, engineer, ... Anyone working with teammate, especially those working from home.

**Additional context**
A common scenario is when 2 collegues, from their home, have a meeting with a third person, a client, and want to take notes of the meeting. Collaborative writing allow each other to complete the report, correct mistakes, style the text,... All of these in real time. Moreover, if screen sharing is involved, the client can see the progress of the reporting.

Atlassian Confluence had a good answer to this.

**Comment by MikeWallaceDev** [comment]
Thank you very much @mibinn for such a well written feature request. This is in our roadmap and there is no need to track this here. You will be seeing this feature in the future. Thank you for using AppFlowy!

**Comment by matbgn** [comment]
Maybe for those, like me, who were searching where it is even tracked, it's here: https://github.com/AppFlowy-IO/AppFlowy/issues/714

Unfortunately, with no milestone and no planning ATTW. Hope it will change soon.

**Comment by annieappflowy** [comment]
Hi @matbgn , thanks for checking out the project. Here is our 6-month roadmap till the end of 2022: [link](https://github.com/AppFlowy-IO/AppFlowy/discussions/565). As you can see, supporting online collaboration is not included.  However, we are laying foundations for supporting collaboration, so it's definitely on our radar. We'll publish a new roadmap approaching the end of this year and add more details to https://github.com/AppFlowy-IO/AppFlowy/issues/714 when it's planned to start.

**Comment by matbgn** [comment]
Seems promising! Thanks for the feedback

**Comment by smartynov** [comment]
Why are those commits referencing this issue? it seems they have nothing to do with it.

And anyway, is there an open issue regarding realtime team editing? This is probably the only thing that holds us from switching to AppFlowy

**Comment by khorshuheng** [comment]
AppFlowy already support real-time editing for quite some time. This issue is outdated.

**Comment by smartynov** [comment]
Thank you @khorshuheng. I experienced some huge lags and problems with collaborative editing (like some blocks getting out of sync for different users), thus I thought that it's not supported. I will file a separate bug report when will be able to clearly reproduce it.
