### ISSUE TITLE
[Bug] Translation issue

### ISSUE THREAD

**Issue by yumin2002** [AppFlowy-IO/AppFlowy#2565]
### Bug Description

Some Chinese translation missing in setting and help and support. 

### How to Reproduce

Start AppFlowy and click setting icon, some texts in appearance, files, and user are not translated. Some text in help and support are not translated. The content of the icon that changes font size is also not translated.

### Expected Behavior

Expected to be translated.

### Operating System

macos Monterey

### AppFlowy Version(s)

v0.1.5

### Screenshots

<img width="773" alt="Screen Shot 2023-05-18 at 22 48 44" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/d5064405-99ea-4ee4-9294-bbf0cd295f5d">
<img width="761" alt="Screen Shot 2023-05-18 at 22 48 51" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/6338866e-b7eb-4910-95f1-4e9c69a0fb21">
<img width="769" alt="Screen Shot 2023-05-18 at 22 48 59" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/8755fc89-d4c1-4690-8e73-10756e9a1ad4">
<img width="286" alt="Screen Shot 2023-05-18 at 22 50 17" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/5cdfbf27-7564-4460-ae83-6528860854e2">
<img width="169" alt="Screen Shot 2023-05-18 at 22 53 32" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/d76803db-8e53-41b6-bfd9-ead543b3cc7a">

**Comment by yumin2002** [comment]
I am a native speaker of Chinese, I can help with simplified Chinese translation. Can anyone assign this issue to me? Thanks!

**Comment by annieappflowy** [comment]
@hyj1204 can guide you to translate AppFlowy 
Thanks for offering the help!
