### ISSUE TITLE
[Bug] Animation drop frames

### ISSUE THREAD

**Issue by yumin2002** [AppFlowy-IO/AppFlowy#2568]
### Bug Description

While scrolling rapidly, the app animation drops frames, resulting in a choppy transition. The animation appears laggy and visually inconsistent. Many other animations have the same issue.

### How to Reproduce

Open the app, create a page and add more content, then scroll rapidly up and down.

### Expected Behavior

It should have a smooth transition. 

### Operating System

macos Monterey

### AppFlowy Version(s)

v0.1.5

**Comment by Xazin** [comment]
I assume this relates to or is a duplicate of https://github.com/AppFlowy-IO/appflowy-editor/issues/29

**Comment by yumin2002** [comment]
Since this is a duplicate issue, I will close this issue for now.
