### ISSUE TITLE
[Bug] Unable to view the image picker at the bottom of the screen. The dialog box extends beyond the screen.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2571]
### Bug Description

In document type after, writing in whole page at the end of the page using / select image option and the image dialog is not showing properly.

### How to Reproduce

- In document type write down whole page. 
- At the end of the screen page by using “/“ select image option. 

### Expected Behavior

- It should come in the screen area.

### Operating System

macOS Ventura 

### AppFlowy Version(s)

0.1.5

### Screenshots

![appflowy](https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/77867892-2804-4b76-92a7-c5bbc18d4c15)

**Comment by MayurSMahajan** [comment]
@ChiragPaneliya Thank you for creating an issue!

**Comment by ChiragPaneliya** [comment]
@annieappflowy can you please assign this task to me.
