### ISSUE TITLE
[Bug] Unable to switch to AR language. App Crashes when changed to AR language.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2581]
### Bug Description

from setting change language to AR language at that time it shows blank screen with error message.

**"Unable to load asset: "assets/translations/ar-AR.json"**

### How to Reproduce

- Open App.
- Go to Setting and select Language option and change language to AR language.

### Expected Behavior

It should translate whole app with AR language.

### Operating System

macOS Ventura 13.3.1 (a) macOS Ventura

### AppFlowy Version(s)

0.1.5

### Screenshots

![Screen Recording 2023-05-22 at 11 14 23 AM](https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/02ea3f0b-a0e3-4c96-8374-127a38155b2a)

**Comment by yumin2002** [comment]
Can I work on this issue?

**Comment by ChiragPaneliya** [comment]
I'm working on it.

**Comment by yumin2002** [comment]
btw you can try the following changes. I clicked on it and I did not know how to get my window back to work so I have to fix it on my own and it seems to work: 
<img width="603" alt="Screen Shot 2023-05-22 at 02 35 44" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/91a51e8d-19a4-4afc-a263-e08798b9b4b3">

<img width="597" alt="Screen Shot 2023-05-22 at 02 36 05" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/dd2f7473-22ce-4dad-985f-87e2163e8ef9">
