### ISSUE TITLE
[Bug] Capitalize the first letters

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2587]
### Bug Description

<img width="95" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/52606b17-9de2-4474-9350-66c7102e3314">
<img width="100" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/2e9ad97b-c0fe-4242-b04d-c2b6fb5d4a95">

### How to Reproduce

Trigger the format bar
Hover on an icon to view the hint

### Expected Behavior

Text color
Highlight color

Bulleted list
Numbered list

### Operating System

MacOS

### AppFlowy Version(s)

Develop

**Comment by akarsh-jain-790** [comment]
@annieappflowy I would like to work on this.
