### ISSUE TITLE
[Bug] Board horizontal scroll bar

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2595]
### Bug Description

<img width="1781" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/9be9c420-35ae-480a-a0b9-437964acf4eb">

### How to Reproduce

Cannot scroll horizontally when stacks take up more than my current app screen size

### Expected Behavior

I can scroll to view the rest part of my Kanban

### Operating System

MacOS

### AppFlowy Version(s)

Develop

**Comment by a-wallen** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/f8ab2d03-cd57-41be-b210-139f75ec856d
