### ISSUE TITLE
[Bug] Cannot add a date property to Kanban

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2597]
### Bug Description

Unable to add a Date to kanban

### How to Reproduce

Create a Kanban
Open up a card to add a new Date property

### Expected Behavior

I can add a Date to my Kanban

### Operating System

MacOS

### AppFlowy Version(s)

Develop

**Comment by annieappflowy** [comment]
Actually it just doesn't show up on cards, although it's not hidden
<img width="548" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/fe623a84-70ff-4bc6-940a-27cbead02d1b">

**Comment by richardshiue** [comment]
Normally, the date will only show when one is entered. Are you expecting to see a placeholder?
