### ISSUE TITLE
[Bug] Numbers doesn't support .5

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2598]
### Bug Description

.5 --> interpreted as 5 in a Numbers property

### How to Reproduce

Add a Numbers column
Enter .5 for a cell under the column

### Expected Behavior

Should be recognized as 0.5

### Operating System

MacOS

### AppFlowy Version(s)

Develop

**Comment by younes-io** [comment]
Same for Windows 11
