### ISSUE TITLE
[FR] Universal build for M1 support?

### ISSUE THREAD

**Issue by FallenChromium** [AppFlowy-IO/AppFlowy#26]
Hi there! I loved the design of the app ♥️
One of the problems I've encountered is that it runs under Rosetta 2 on my laptop, which is undesirable, mainly because smoothness suffers and so does the battery life. Is there any way to compile Rust+Dart app into a Universal app?

**Comment by appflowy** [comment]
@FallenChromium Absolutely yes, but the size of the application will be larger. I can build one for M1. Please let me know how you think about it.

**Comment by FallenChromium** [comment]
It's absolutely fine to have 2 releases for each architecture (like most utils on Homebrew do, anyway), so I think it's a viable solution.

That said, it's always a compromise. I can see Universal App being easier to distribute but more painful to build (especially in an automated fashion). Separating targets and release products can also be a pain in the back, especially when other arches and\or platforms will join (win_x64, win_arm64, linux_x64, linux_arm64, you probably already imagined that giant GitHub Releases file list 🤣)

**Comment by pdckxd** [comment]
Seems flutter doesn't support build application for native Apple M1 chip. Below wiki page shows that M1 can run X86_64 application through Rosetta2 at this moment. So you will see Intel arch in "Activity Monitor"

https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon

> Compiled Intel macOS binaries work on Apple Silicon without change thanks to the Rosetta 2 translation environment, which converts x86_64 instructions to ARM64 equivalents.
> We also plan to offer support for compilation directly to ARM64, as well as universal binaries that combine x86_64 and ARM64 assets. Issue 60113 is the umbrella bug tracking this work.

**Comment by ioiioo** [comment]
I have the same appeal, I hope I can have M1 version applications.

**Comment by lvelvee** [comment]
kindly support native arm arch pls

**Comment by WATERMELOUN3** [comment]
Is there any news about native ARM build support ?
In the documentation in Building on MacOS -> Building in release mode, there is arm64 command, but it still doesn't work.

**Comment by Lewiscowles1986** [comment]
It seems Flutter recently released apple silicon support. I hope it's generic ARM64 so I can run on M1 Studio as well as low-end devices like the raspberry pi.

Links:
- https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon
- https://github.com/flutter/flutter/issues/60113
- https://github.com/flutter/flutter/issues/87508

**Comment by Lewiscowles1986** [comment]
If there are tests or it's a matter of configuring a build, I'm in BST London, and happy to take the time to use my hardware to build an M1 and host while the github process for building is worked out.

**Comment by SuperBo** [comment]
Hi @Lewiscowles1986 , can you share the build with us :D

**Comment by Lewiscowles1986** [comment]
It didn’t build and it seems I e not kept a log of why, or what the errors were

**Comment by Tienisto** [comment]
Shouldn't `flutter build macos` build an universal build by default? I am maintainer of [LocalSend](https://github.com/localsend/localsend) and I did not do anything to ensure M1 support.

Maybe an ARM based computer is needed though...

**Comment by Lewiscowles1986** [comment]
It's not the same commands @Tienisto (I think due to the Rust and other commands); but it looks like https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos has cli options for arm64; so I guess for me; this was all I wanted.

**Comment by Lewiscowles1986** [comment]
This has led to https://github.com/flutter/flutter/issues/130308 on a new mac I don't want to use appleId for, but it feels like that is a me problem.

**Comment by vncloudsco** [comment]
Are there any updates for this?

**Comment by LucasXu0** [comment]
We have provided the universal package for the M series chip from version 0.3.0.

**Comment by vncloudsco** [comment]
@LucasXu0 
We do not see that we still have not been installed on ARM, even the built -in docker is not shown.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/41409442/bd646223-962f-4492-9fea-a99d775bbed4)

**Comment by vncloudsco** [comment]
releases page only x86_64 support @LucasXu0 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/41409442/0836afb4-57e7-498c-8964-2c4a25edfc09)
