### ISSUE TITLE
[FR] Add hints to the No Date menu

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2600]
### Description

<img width="279" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/9e1d5ead-5cfa-431c-ab25-8b28ab11a6d2">

Tell users why the events show up in the menu

### Impact

Calendar users

**Comment by yumin2002** [comment]
I can think of two designs. Maybe wa can add sth like the info button similar to the image below and put it on the left side of "No Date".
<img width="56" alt="Screen Shot 2023-05-23 at 03 51 17" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/f6d86005-731b-40c3-8124-b425f84fd8ff">
When the user click on it, we display some hint.
Another design is like give user some brief hint when the mouse hover on "no date".
