### ISSUE TITLE
[FR] Enter icon in add field.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2605]
### Description

When user new field suggest them with enter button icon.
so user can understand by enter button they can add new field.
![Screenshot](https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/bfab9a64-b398-413c-9d19-3a75f65172af)

### Impact

Easy to understand how to add new field.

**Comment by ChiragPaneliya** [comment]
@annieappflowy can you please assign this task to me.

**Comment by annieappflowy** [comment]
Assigned.
