### ISSUE TITLE
[Bug] Theme not translated, text cannot be found in en.json

### ISSUE THREAD

**Issue by yumin2002** [AppFlowy-IO/AppFlowy#2609]
### Bug Description

The text of the theme is not translated, and the text "Lavender", "Dandelion", and "Default" cannot be found in en.json. So it is hard to add translation.

### How to Reproduce

Go to setting-language-change the language setting to ”简体中文“, then go to setting-appearance-“主题”. You may notice that the names of the themes are not translated.

### Expected Behavior

translated.

### Operating System

macos Monterey

### AppFlowy Version(s)

v0.1.5

### Screenshots

<img width="780" alt="Screen Shot 2023-05-23 at 17 48 55" src="https://github.com/AppFlowy-IO/AppFlowy/assets/94658575/7fd81068-b28f-437e-a532-3d601afb27ca">

### Additional Context

The bug remains after adding the latest simplified Chinese translation, which will be a change expected to be merged sometimes soon: https://github.com/AppFlowy-IO/AppFlowy/pull/2585.

**Comment by LucasXu0** [comment]
Hey, @yumin2002. I believe only the word 'Default' needs to be translated; the others should be used in their original names.

**Comment by annieappflowy** [comment]
<img width="192" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/b7b34a31-9cd4-4699-81ac-4aba9879b9cc">
