### ISSUE TITLE
[Bug] Calendar scroll

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2618]
### Bug Description

the whole white area on right margin could be used for scrolling instead of a small thin scroll bar, it'll make it faster and less annoying to navigate..

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/71d079c4-f7a5-47c4-9018-9694d9c5f048)

### How to Reproduce

Create a calendar
Trigger the vertical scroll

### Expected Behavior

can we move the Calendar scroll more to right so it doesn't overlap with weekend's scroll and easier to navigate

### Operating System

macOS

### AppFlowy Version(s)

v0.1.5

**Comment by richardshiue** [comment]
Unfortunately the calendar view packages doesn't seem to expose a scroll controller setting for us to specify, so it'd be kinda difficult to implement this. If the overlapping scrollbar is a serious issue, we would have to remove the scrollbar altogether.
