### ISSUE TITLE
[FR] Adding support for HINDI (Translations) language

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2626]
### Description

**By Adding Hindi Language Support User will be able to understand app more conveniently.**

### Impact

**Easy to understand for those who doesn’t speak English.**

**Comment by MayurSMahajan** [comment]
To solve this issue, one can first take a look here to get a better understanding: [Adding new Language Translation](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/translation#steps-to-add-new-language)

**Comment by ChiragPaneliya** [comment]
@annieappflowy can you please assign this task to me.

**Comment by amansh-tty** [comment]
@annieappflowy can you please assign the PR to me

**Comment by pawan-cpu** [comment]
Hi @annieappflowy, i am an experienced Hindi Translator,I have contributed to some of the projects Team everest by translating their content in hindi, could you please assign this  to me

**Comment by annieappflowy** [comment]
@pawan-cpu , there is a pending PR on this issue. I think you can continue to work on it.

**Comment by pawan-cpu** [comment]
Thanks Annie and AppFlowy-IO/AppFlowy for providing me the Opportunity to
contribute.
Thanks & Regards
 Pawan ***@***.***

**Comment by MayurSMahajan** [comment]
Hey @pawan-cpu! Are you still working on this?

**Comment by pawan-cpu** [comment]
Yes, I will complete it soon.I am working to ensure high quality I ensured.

**Comment by LucasXu0** [comment]
FYI, @pawan-cpu. Here's a translation tool that may help. https://inlang.com/marketplace/app.inlang.cli

<img width="802" alt="Screenshot 2023-09-13 at 15 03 55" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/10e1bf82-374d-4800-a567-d314f69583d8">

**Comment by duckcommit** [comment]
If this issue is not solved yet, I can take it up since I have already solved similar issues. @annieappflowy @LucasXu0  @MayurSMahajan

**Comment by MayurSMahajan** [comment]
Hey @duckcommit apparently @pawan-cpu is working on this, but since this is a translation issue, go ahead and submit a PR, then @pawan-cpu can review and maybe improve your changes.

**Comment by CrazyRikin** [comment]
> Hey @duckcommit apparently @pawan-cpu is working on this, but since this is a translation issue, go ahead and submit a PR, then @pawan-cpu can maybe improve your changes whenever they choose to submit their PR.

hey @MayurSMahajan if you allow me i can also submit a pr ? i can submit a pr quickly.

**Comment by MayurSMahajan** [comment]
Hey @CrazyRikin! Thanks, you can submit a PR if you want. As I said since this is a translation issue we can accept multiple PRs for this.
