### ISSUE TITLE
[Bug] Adding a callout on a page and then deleting the callout crashes the page and it goes grey

### ISSUE THREAD

**Issue by JellyBean-2298** [AppFlowy-IO/AppFlowy#2632]
### Bug Description

Adding a callout on a page and then deleting the callout crashes the page and it goes grey

### How to Reproduce

Make a new page
I added a cover colour and a title
use / to get a callout
Delete the callout using the delete callout button
Go on to a different page
Go back to the page you made and its grey
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/78557785/9c471b1c-3ea3-40a8-9722-3605caa22b26)

### Expected Behavior

Expected the page to no be grey and still be able to type on it 

### Operating System

Windows

### AppFlowy Version(s)

0.1.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/78557785/f193934d-4ba3-4b26-acec-7a16b7d5a695)
Making the new page and then creating a callout and then deleting it, makes the page go grey
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/78557785/b50665c1-8b75-416c-9347-f3394b7ccbb4)

**Comment by annieappflowy** [comment]
Could you please try out the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.5)?

**Comment by annieappflowy** [comment]
Unable to reproduce
