### ISSUE TITLE
[Bug] New grid row button is out of place

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#2633]
### Bug Description

The new row button looks out of place. There is a weird amount of blank space between the last row of the grid and the new row button.

### How to Reproduce

Open up a grid and scroll

### Expected Behavior

It should either be attached to the bottom of the row list, or just above the "Count" bar.

### Operating System

Fedora 38

### AppFlowy Version(s)

latest develop

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/5dbbc749-d8ed-4c94-8316-0785a0909ad2

**Comment by appflowy** [comment]
This is caused by using the SliverFillRemaining. 

> SliverFillRemaining: It sizes its child to fill the remaining space in the viewport. Typically, this is used for a flexible space where you don't have a specific size in mind. It can be quite useful for content that should take up the remaining available space on the screen.

It works fine if we use the SliverAnimatedList. But it does not support moving the row.

**Comment by Xazin** [comment]
I'll take a look at this, we don't need to use SliverFillRemaining, so if that's the primary issue we can refactor that part.
