### ISSUE TITLE
[Bug] Visual bug in divider between main editor area and top area 

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#2634]
### Bug Description

See screenshot below

### How to Reproduce

Open AppFlowy.

### Expected Behavior

The divider should stretch from end to end

### Operating System

Fedora Linux 38

### AppFlowy Version(s)

latest develop

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/f0a662c5-d6b8-4fb8-a5e2-35866ca6bbd9)

**Comment by annieappflowy** [comment]
Same on Windows 11
