### ISSUE TITLE
[Bug] Flutter Version Issue in Install Dev Env Scripts

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#2647]
### Bug Description

Currently we are supporting, Flutter version `v3.7.9` for development however in scripts we are still using `v3.7.5`. 

### How to Reproduce

Upgrade your flutter version to 3.7.9 and you will be switched to `3.7.5` after executing `install_dev_env` scripts.

### Expected Behavior

It should upgrade to `3.7.9` instead of `3.7.5`.

### Operating System

Ubuntu

### AppFlowy Version(s)

1.0.0

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. We have updated the Flutter to 3.10.1 on the develop branch.

**Comment by AmanNegi** [comment]
Perhaps I should upgrade it to `3.10.1` in the scripts?

**Comment by Xazin** [comment]
> Perhaps I should upgrade it to `3.10.1` in the scripts?
> 
> 

It's already done on develop as well.

**Comment by AmanNegi** [comment]
Okay that's great! Just as a doubt, are we supposed to branch from develop branch to work on feature now?

**Comment by AmanNegi** [comment]
This issue is already resolved in `develop` branch as mentioned above.
