### ISSUE TITLE
[Bug] Ui is not updating in board.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2650]
### Bug Description

When user duplicate the card, at that time card list is not updating instantly.
When user change window and come again to same card list it's changing.
![Screen-Recording-2023-05-29-at-4 24 22-PM](https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/2bfd241a-fca7-41d6-82b8-bd007ac1b71c)

### How to Reproduce

Open board type document and duplicate any card.  

### Expected Behavior

Card list should Update instantly.

### Operating System

MacOS Ventura

### AppFlowy Version(s)

0.1.5

**Comment by appflowy** [comment]
Thank you for reporting this. already fixed in #2639.
