### ISSUE TITLE
[Bug] After deleting property UI not updating

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2651]
### Bug Description

In card type when i delete property ui is not updating instantly, need to go back and when we come again at that time it's updates.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/f6d40290-8ac6-4deb-a913-1841008d68cf

### How to Reproduce

Open board and add value in card.
Try to delete property.

### Expected Behavior

property deletion ui should change instantly.

### Operating System

MacOS Ventura

### AppFlowy Version(s)

0.1.5

**Comment by annieappflowy** [comment]
cannot reproduce in the develop branch on WIndows 11

**Comment by ChiragPaneliya** [comment]
This issue is not generating again.
So I'm closing this issue. @annieappflowy
