### ISSUE TITLE
[Bug] edit url icon not working properly in url property.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2652]
### Bug Description

On tap of url edit icon it's not working properly. url is now only editing through on side click of that property.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/a11b1ca4-3c8c-429f-b452-efb55aed81d8

### How to Reproduce

Enter in url property and try to edit it url with edit icon.

### Expected Behavior

Edit icon button should work properly.

### Operating System

MacOS Ventura

### AppFlowy Version(s)

0.1.5

**Comment by annieappflowy** [comment]
I can reproduce on Windows

**Comment by appflowy** [comment]
#2523 already fix this issue. Support directly editing the url now.
