### ISSUE TITLE
[Bug] Editor feels sluggish when applying a text or highlight color

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2659]
### Bug Description

As described in the title

### How to Reproduce

Highlight text to trigger the format toolbar
Click "Text color"
Choose a color
When it applies, feel sluggish with a discernable delay

### Expected Behavior

No perceptible delay

### Operating System

Windows 11

### AppFlowy Version(s)

develop

**Comment by annieappflowy** [comment]
Feeling the same using v0.2.1 on macOS

**Comment by richardshiue** [comment]
Closing as completed
