### ISSUE TITLE
[Bug] Cannot change the background color of a callout

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2660]
### Bug Description

<img width="1632" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/516a5713-7661-4a33-8732-d0207a67b962">

### How to Reproduce

Insert a Callout block
Try to change its background color

### Expected Behavior

I can change the background color

### Operating System

Windows 11

### AppFlowy Version(s)

develop

**Comment by akarsh-jain-790** [comment]
@annieappflowy I would like to work on this issue.
