### ISSUE TITLE
[Bug] Document cover color not changing.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2673]
### Bug Description

After adding cover in document, cover color is not changing. All color shows as white color.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/6609ee11-9350-4cf9-9c79-d7fafad568b9

### How to Reproduce

Add new document and add cover on that document. And try to change color of cover.

### Expected Behavior

Cover colors should show different colors.

### Operating System

MacOS Ventura

### AppFlowy Version(s)

0.1.5

**Comment by annieappflowy** [comment]
Unable to reproduce in 0.1.6 on MacOS

**Comment by ChiragPaneliya** [comment]
@annieappflowy I'm also not able to reproduce in 0.1.6. Looks fixed. So I'm closing it.
