### ISSUE TITLE
[Bug] Check Box Overflow when scrolling

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2675]
### Bug Description

When we scroll the section on list in calendar data it scroll through the ui.

### How to Reproduce

Add new Calendar Document.
Add New Property with Some Check Box List and scroll.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/5477bc83-9eba-4386-97e2-984172b2f09c

### Expected Behavior

it should not scroll with overflow instead scroll with it's own available position.

### Operating System

MacOS Ventura

### AppFlowy Version(s)

0.1.6

**Comment by appflowy** [comment]
Already fixed in v0.2.0
