### ISSUE TITLE
[Bug] Refrence board and grid delete after issue. 

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2679]
### Bug Description

In doucment when user add new grid or board , or give refrence of grid or board but user when user delete it. There is showing continuously circular indicator on it.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/2d637af9-a640-4b9b-8356-a5e65b212482

### How to Reproduce

Open document add new or give refrence of board or grid. 
after that detele that board or grid.

### Expected Behavior

It show error message like "data not found or parent grid is deleted" isnted of continuously circular indicator on it.

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.6

**Comment by LucasXu0** [comment]
Fixed in develop.
