### ISSUE TITLE
[Bug] Language change

### ISSUE THREAD

**Issue by andercard0** [AppFlowy-IO/AppFlowy#2680]
### Bug Description

While trying to change the language of the application, it is not changed. being applied always in the system language instead.
Ex: My OS is in Portuguese any changed languaged after close the application, it returns to Portuguese. 

### How to Reproduce

Open the aplication > change language > close the app > it will return to OS's language instead. 

### Expected Behavior

Expected behaviour is while changing the app language it comply with it instead to follow my windows's.

### Operating System

Windows 

### AppFlowy Version(s)

0.1.6

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/43047877/f55e2b57-c4b5-4c52-8d4e-68b458da00b8)

Here after close and reopen the app:

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/43047877/a71e4576-2c96-4a45-a3fa-a6e2cc225a00)

**Comment by LucasXu0** [comment]
resolve in v0.2.0

**Comment by andercard0** [comment]
> Resolved in v0.2.0

Nope it is not just updated and same thing is still happening.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/43047877/e7522594-04c8-4204-a938-eb0e2424419f)

**Comment by andercard0** [comment]
[Update] working good now on version v0.2.3
Just give it a try now.
Thank you!

**Comment by annieappflowy** [comment]
Thanks for letting us know! Look forward to getting more feedback from you.
