### ISSUE TITLE
[Bug] When Deleting Last DOC it's not deleting.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2684]
### Bug Description

When you delete all doc from side panel but last doc is not deleting and still shows there.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/a78f0b38-d8c9-4f3d-8f01-9fe9969453ad

### How to Reproduce

1. Make Some Doc.
2. Add Some Content to it.
3. Delete doc one by one.

### Expected Behavior

When we delete all doc including last doc then doc panel should be empty with some image animation or message like (Make New Doc)

### Operating System

Windows 10

### AppFlowy Version(s)

develop

**Comment by appflowy** [comment]
It is a bug. It should show a delete banner on top of the document.

**Comment by annieappflowy** [comment]
Fixed
