### ISSUE TITLE
[Bug] Unwanted Behaviour When Create New Grid from Document.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2686]
### Bug Description

When we create new grid using  / in document it shows two document with same grid on left side.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/4405af93-9526-4ca1-8c84-fc8b91e24953

### How to Reproduce

1. Create New Document.
2. add Ceate a new Grid using /

### Expected Behavior

On Creation of new grid only new document needs to generate with grid instead of two document

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.6

**Comment by annieappflowy** [comment]
Fixed in v0.2
