### ISSUE TITLE
[FR] Outline Plugin for AppFlowy 

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#2688]
### Description

Adding the outline block to the document will automatically generate a list of anchor links to the headings within the document.

## Expected Outcome:
- Insert an outline via the slash '/' command
- Convert highlighted lines into an outline
- The content of the outline will be generated automatically based on the document
- Click on the content of the outline will take users directly to the corresponding heading
- Different levels of headings are indented differently. For example, H1 will have no indentation, while H2 will be indented once, and so on.

### Impact

Users who write lengthy documents and want a table of contents at the starting of the page so that they can easily navigate throughout the page.

**Comment by AmanNegi** [comment]
@LucasXu0 Could you please assign this issue to me, also please let me know what more details do I need to specify here. :smile:

**Comment by LucasXu0** [comment]
> Convert highlighted lines into an outline

I suppose we should convert the paragraph with heading style into an outline. For example,

# heading 1
...
## heading 2
...

the outline plugin should be 

[heading 1]()
[heading 2]()

and them should can clickable and link to the position of the heading.
