### ISSUE TITLE
[Bug] Please remove Https:// prefix if already added.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2690]
### Bug Description

When we add New task with url porperty in board document and clicked on url icon which opens url to browser it's adding https:// prefix to url even if there is already https:// prefix available.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/0715388f-2625-4df8-a415-be92ce604589

### How to Reproduce

1. Create New Board Document.
2. Create Task and Add It's property as url and add your url with https:// prefix.
3. Click on Url icon which is available right side of url property.

### Expected Behavior

if url already contains https:// prefix then don't add (https://) instad of just open url.

### Operating System

Windows 10

### AppFlowy Version(s)

develop

**Comment by annieappflowy** [comment]
I've assigned this issue to you, @ChiragPaneliya
