### ISSUE TITLE
[Bug] Add cover image using url issue

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2715]
### Bug Description

- When user add cover image using url , it's every time showing invalid image url. 

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/584104ba-9a9b-49e0-8159-42fe8fcd8c51

### How to Reproduce

- Add cover image in document.
- Try to add cover image using URL.

### Expected Behavior

Image also add with URL.

### Operating System

macOS monterey 12.6

### AppFlowy Version(s)

0.1.6

**Comment by LucasXu0** [comment]
@ChiragPaneliya can you post the image url here?

**Comment by ChiragPaneliya** [comment]
Yes @LucasXu0 ,
I tried many url's but currently I have this three image url.
1) https://t4.ftcdn.net/jpg/05/36/78/91/360_F_536789107_s0yn1EE4jcS8KiffDcqAUJqzB9KpQFSL.jpg
2) https://t4.ftcdn.net/jpg/04/95/28/65/360_F_495286577_rpsT2Shmr6g81hOhGXALhxWOfx1vOQBa.jpg
3) https://www.shutterstock.com/image-vector/vector-banner-design-circuit-board-260nw-1233925105.jpg
