### ISSUE TITLE
[Bug] Need horizontal scroll in document referenced board.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2717]
### Bug Description

- When user add board with reference in document, board is not scrolling horizontally.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/75e7c653-f3a5-4e78-9f97-9228a636ae10

### How to Reproduce

- add reference board in document
- in that board add multiple tags.

### Expected Behavior

Board should scroll horizontally

### Operating System

macOS monterey 12.6

### AppFlowy Version(s)

0.1.6

**Comment by annieappflowy** [comment]
Likely related: https://github.com/AppFlowy-IO/AppFlowy/issues/2595

**Comment by a-wallen** [comment]
This works for me now, but I need help finding out if a PR introduced the change.
