### ISSUE TITLE
[Bug] In document reference grid is not updating instantly

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2721]
### Bug Description

When user add reference grid at that time when user change or add new property of grid it’s not updating instantly in that document.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/a99b9f53-0e59-4abb-a420-8cc994459f77

### How to Reproduce

- Add reference grid in document try to change properties of that grid.

### Expected Behavior

Properties should work accordingly as user has selected.

### Operating System

macOS monterey 12.6

### AppFlowy Version(s)

0.1.6

**Comment by annieappflowy** [comment]
Fixed in v0.2.1

**Comment by ChiragPaneliya** [comment]
Please stop Email

**Comment by annieappflowy** [comment]
Please unsubscribe, @ChiragPaneliya 
I can't control
