### ISSUE TITLE
[Bug] Weird Preview when we add multiple checklist in board.

### ISSUE THREAD

**Issue by ChiragPaneliya** [AppFlowy-IO/AppFlowy#2729]
### Bug Description

When we create new board and add multiple property as checklist then in preview section it shows as very weird ui.

https://github.com/AppFlowy-IO/AppFlowy/assets/51508126/41c70fc1-3a27-4f35-8bf2-ac3f0cab820b

### How to Reproduce

Create New Board Add New Data.
Select 2 or 3 Check list from property section.
Go Back to preview section.

### Expected Behavior

In Preview section please add some level of margin to checklist preview.

### Operating System

Windows 10

### AppFlowy Version(s)

develop

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/2746
