### ISSUE TITLE
[Bug] Opening Links with `https://` don't work

### ISSUE THREAD

**Issue by VenomSupreme** [AppFlowy-IO/AppFlowy#2735]
### Bug Description

When opening a link, if the link has `https://` before it, it will remove the `:  `and link won't work anymore

### How to Reproduce

Change Property to URL
Paste a link with `https://` for eg (https://github.com/AppFlowy-IO)
Click on Go to link icon

### Expected Behavior

Link should work fine without any issues

### Operating System

WIN 10

### AppFlowy Version(s)

0.1.6

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/69515491/cb578b09-b804-4380-8167-5848674397cd

**Comment by ChiragPaneliya** [comment]
#2690 fixed in develop branch.

**Comment by annieappflowy** [comment]
fixed in the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.2.0)
