### ISSUE TITLE
[Bug] Docker Documentation is not right

### ISSUE THREAD

**Issue by Njima1572** [AppFlowy-IO/appflowy#274]
**Describe the bug**
Just cloned the repo and cannot find `docker-compose.yml` / `Dockerfile` in `docs/docker-buildfiles` in main branch as documented in https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker

**Additional context**
- #198 moved the docker related files in different directory, so the documentation needs to be updated

**Comment by MikeWallaceDev** [comment]
Thank you for your report @Njima1572 :)  In the future, for documentation related bugs, please use the issue tracker in the [Documentation repo](https://github.com/AppFlowy-IO/docs)

Fixed with change 54

**Comment by Njima1572** [comment]
Sorry, I could not find the documentation repo when I was doing this. Will be aware of it for next time :)
