### ISSUE TITLE
[Bug] UX flow of picking a photo from local and using it as a cover

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2771]
### Bug Description

The current UX flow is confusing

### How to Reproduce

Pick a photo from local to use a cover

### Expected Behavior

Better UX

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.1

**Comment by rizwan3395** [comment]
Hi @annieappflowy It seems interested to me. If no one is working please it to me.

**Comment by Brikkinus** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/67888185/1d5fe389-3bbd-4a6e-acaa-c920aa3c6d4e


Hi, @annieappflowy

I started a design a few months ago, but then got caught up in other stuff. Although the concept isn't complete, I wanted to share it.

let me know if this concept is interesting!

**Comment by annieappflowy** [comment]
Hi @Brikkinus , thanks so much for working on the concept. I love the side by side design and how convenient it is to add a cover image from the local.
