### ISSUE TITLE
[Bug] Importing document using text and  markdown treats codeblock in markdown as plain text

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/AppFlowy#2781]
### Bug Description

When importing a document using the text and markdown option the code block which is supported in AppFlowy is treated like regular text . Like shown below-
<img width="636" alt="Screenshot 2023-06-12 at 11 56 31 AM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/3a11621f-8b3c-46ea-8008-482480da5424">

### How to Reproduce

Import from a markdown file that has a code block 

### Expected Behavior

Should display a code block like - 
<img width="741" alt="Screenshot 2023-06-12 at 12 10 46 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/5a43ba12-d4bb-4080-ad01-3ca43d1ca878">

### Operating System

MacOs

### AppFlowy Version(s)

0.2.1

**Comment by Mukund-Tandon** [comment]
@LucasXu0, Could you please assign this issue to me.

**Comment by annieappflowy** [comment]
Assigned
