### ISSUE TITLE
can't see old version appflowy's files [Bug] 

### ISSUE THREAD

**Issue by TugdualDek** [AppFlowy-IO/AppFlowy#2788]
### Bug Description

I have installed the new version of appflowy. It hasn't deleted my old data, but it can't open them either.

### How to Reproduce

go from version 0.1.6 to 0.2.1

### Expected Behavior

See my pages from v0.1.6 on v0.2.1

### Operating System

windows 10

### AppFlowy Version(s)

0.2.1

**Comment by annieappflowy** [comment]
Please follow these two videos to export data from v0.1.6 and import into v0.2.1
and let me know if you need more help

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/50b7bfba-5b4e-4f20-824f-eb888c335b66


https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/29336dfa-006a-4a60-beb4-d63e90542b64
