### ISSUE TITLE
[FR] ability to change appflowy's font for notes

### ISSUE THREAD

**Issue by liyaowhen** [AppFlowy-IO/AppFlowy#2795]
### Description

To make a note aesthetic, you need to use different fonts. And I think that sometimes, the built-in app flowy font looks ugly in some cases, if only I could use a better font... In notion, you are given 3 different font options, to make app flowy even better, you add an option to add your own fonts to the mix 😄.

### Impact

It will help users create better notes, and also it will make app flowy more on par with Notion.

**Comment by annieappflowy** [comment]
Thanks for your input. What fonts would you like to use?

**Comment by liyaowhen** [comment]
google fonts since they are also open source, and they have good variety.

**Comment by liyaowhen** [comment]
there is a package called google fonts for flutter that can give access to all google fonts via internet. but because appflowy is supposed to be offline, you can have a fallback font based on the type of font it is {display, sans-serif, serif ...}. or you could do it like notion and have 3 options [sans-serif, serif and mono]. I am not an expert on programming in flutter, but this might not be viable because the fonts are stored in a yaml file, accessed thru compilation.

**Comment by a-wallen** [comment]
@annieappflowy since I was working on dynamic themes, I'd be happy to look at this.

**Comment by annieappflowy** [comment]
Thanks, @a-wallen ! Assigned
