### ISSUE TITLE
[FR] bump version 0.2.2

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2800]
### New Features
- Added support for embedding a document in the database's row detail page
- Added support for inserting an emoji in the database's row detail page

### Other Updates
- Added language selector on the welcome page
- Added support for importing multiple markdown files all at once

### Impact

Bump version 0.2.2

**Comment by appflowy** [comment]
1.  Support inserting emoji in row detail page.
2. fix some bugs
