### ISSUE TITLE
[Bug] import md nested bulleted list

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2809]
### Bug Description

Doesn't work well if the md file contains multi-level bulleted lists
This is the imported result
<img width="670" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ce28b2e2-e099-44e8-835c-cda13ab4d7c5">

This is the original:
<img width="518" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/993c057f-34d8-4906-9533-ff7e19305675">

### How to Reproduce

Export a md file containing a multi-level bulleted list
Import it into AppFlowy

### Expected Behavior

* like this
   * like this

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.1

**Comment by JessicaJHee** [comment]
@annieappflowy I would like to work on this! If you have any ideas on what files I should be looking at please point me in the right direction :)
