### ISSUE TITLE
[FR] Kanban - Don't cut off checklist items at ~22 characters

### ISSUE THREAD

**Issue by jaggujajamensan** [AppFlowy-IO/AppFlowy#2810]
### Description

Currently checklist items are cut off at around 22 characters, and don't show the entire string of the checklist item

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/136453208/5dc49cf3-b6b5-423a-9b31-a4b9524efd32)

They also don't show the list unless you click the progress bar, which adds another click when opening up a card, and is something I think should be shown by default, similar to Trello.

I suggest trying to match the use case of Trello Kanbans more, by showing more of the checklist item string when the checklist is clicked.

### Impact

This will let users write more than 22 characters in their checklist, showing the full description of the task they inserted. Currently you have to be very mindful to only write a few characters in this checklist.

### Additional Context
Running latest release on Windows 10.

**Comment by annieappflowy** [comment]
character limit is removed
<img width="617" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/4ad27867-574a-48d2-b733-61be73968898">
