### ISSUE TITLE
[FR] Kanban - Allow re-ordering card properties

### ISSUE THREAD

**Issue by jaggujajamensan** [AppFlowy-IO/AppFlowy#2811]
### Description

I accidentally clicked the "hide" button on my kanban cards' due date, removing the property entirely from all my cards (don't really get the purpose of that button). Now when trying to re-add a date, it's inserted at the bottom, as such:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/136453208/db6b571e-b007-4b58-a7e1-0a28e32dddc8)

There's currently no way to put that date at the top again, unless I delete and re-add every other property.

### Impact

This would punish users less for not having planned their entire card structure beforehand, and allow additions that don't go to the bottom.

### Additional Context
Running latest release on Windows 10.

**Comment by annieappflowy** [comment]
Thanks for your feedback! Will support re-ordering properties in Kanban.
There is a workaround at the moment. Go to Settings at the top right of your Kanban --> Click Layout ---> Grid
You can reorder properties in Grid and then switch back to Kanban
<img width="192" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/1c77ff5d-3a57-490a-ad41-8a46f36b50a6">

I tried to reproduce your issue with "Hide" but I am not quite sure about it. 


<img width="156" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/acc2d9a5-ed82-401c-b8b9-2e91849acfeb">

<img width="496" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/f7112333-c95d-43e8-a6c6-90aeaa0758b8">

Can you please elaborate on how you think Hide should work?

**Comment by jaggujajamensan** [comment]
Thanks for the quick response, and for informing me about the grid workaround!

And the only issue with _Hide_ was just that I hadn't seen the visibility markers in the properties menu, sorry 😅
That's mostly my fault, but I was a bit unsure of what the property menu represented, maybe it would be slightly clearer if the "Properties" button was renamed to "Card properties"?

**Comment by jaggujajamensan** [comment]
Hints like that would be perfect! The feature is pretty intuitive once you understand it, so I think a few hints like that would be enough to make new users understand more easily

**Comment by Xazin** [comment]
For now, I've made it possible to reorder properties from the settings menu by dragging.

Until we have the block action in the card menu, this should be sufficient.

See preview in #2989

**Comment by richardshiue** [comment]
We now offer two ways of reordering card properties across 3 database view layouts: from the row detail page and from the settings menu. I consider this resolved
