### ISSUE TITLE
[FR] Kanban - Don't show card's text property contents on the board

### ISSUE THREAD

**Issue by jaggujajamensan** [AppFlowy-IO/AppFlowy#2812]
### Description

As demonstrated here:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/136453208/c68053c4-eb5e-4f52-9d53-a7305c4a6608)

Text properties are impractical for storing details about a card, because its contents are shown directly on the card on the board. This makes it very difficult to store medium to large amounts of text, without heavily cluttering the kanban board, making it impractical to use Cards to store information about the task.

### Impact

This prevents users from storing information about a task inside a card, which is a use case commonly used by me and the teams I've worked with in the past, and one that many others might expect as storing details about tasks is something Trello (Popular kanban alternative) seems to be designed around.

If this were resolved, then checklists could be used in lieu of the checklist item, because of the issue described in #2810, but because of this issue there's currently no way to keep any larger-than-tiny amount of extra text/info inside a card, without making the board a cluttered mess.

### Additional Context
Running latest release on Windows 10.

**Comment by annieappflowy** [comment]
Hi @jaggujajamensan , have you tried to write long text in the text area right below the properties? Would that resolve your issue?
<img width="491" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/6b978be0-7c01-4e54-a298-74aadb40f5de">
