### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nan95270** [AppFlowy-IO/AppFlowy#2814]
### Bug Description

Board
When I check again, I get this error

msg:"\"Deserialize operations to database_model::block_rev::DatabaseBlockRevision failed：trailing characters at line 1 column 2528 \""

### How to Reproduce

I didn't find the reason

### Expected Behavior

what do i need,
to restore content here

### Operating System

Windows10

### AppFlowy Version(s)

0.1.6

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/127379471/152220b2-315b-44af-bdb6-68f33dcf5f7a)

**Comment by annieappflowy** [comment]
Helped the user recover on June 17th
