### ISSUE TITLE
[FR] Target URI

### ISSUE THREAD

**Issue by finey-dev** [AppFlowy-IO/AppFlowy#2815]
### Bug Description

Target of URI hasn't been generated: 'package:appflowy_backend/protobuf/dart-ffi/ffi_response.pb.dart'.
Try running the generator that will generate the file referenced by the URI.dart[uri_has_not_been_generated](https://dart.dev/diagnostics/uri_has_not_been_generated)
package:appflowy_backend/protobuf/dart-ffi/ffi_response.pb.dart

### How to Reproduce

flutter pub get

### Expected Behavior

Target URI Existing

### Operating System

Windows 

### AppFlowy Version(s)

0.0.1

**Comment by annieappflowy** [comment]
Related: https://github.com/AppFlowy-IO/AppFlowy/issues/1021

**Comment by Xazin** [comment]
Enable dart protoc plugin, and then run the clean and rebuild all.

You need to enable the protoc plugin everytime you change Fkutter version.

**Comment by garv-shah** [comment]
once the protoc plugin is installed, how would one rebuild all for `appflowy_backend`?

**Comment by garv-shah** [comment]
ah, sorry, I was using IntelliJ where the option would not come up. I opened the project in VSCode and it was all fixed 👍
