### ISSUE TITLE
[Bug] HOME & END buttons don't work

### ISSUE THREAD

**Issue by jaggujajamensan** [AppFlowy-IO/AppFlowy#2817]
### Bug Description

HOME & END keys aren't supported at all.

### How to Reproduce

When putting the text cursor on a line with text in a document, and hitting the HOME or END keys, the text cursor isn't moved.

### Expected Behavior

The expected behavior is for the text cursor to be moved to the beginning or end of that line

### Operating System

Windows 10

### AppFlowy Version(s)

Latest release as of this issue

### Additional Context

The home & end keys are used frequently by many programmers, and are a natural and expected part of writing text to me.

**Comment by MayurSMahajan** [comment]
@jaggujajamensan In the latest release home and end keys are used for moving to the top and end of the page respectively, however as you rightly pointed out, this is not the default behaviour on Windows machine. I will soon submit a PR regarding the same.

**Comment by jaggujajamensan** [comment]
Glad to hear it 😄

**Comment by MayurSMahajan** [comment]
The Home and End keys now navigate to the start and the end of the line respectively on Windows and Linux.
