### ISSUE TITLE
[Bug] click twice to select an option

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2832]
### Bug Description

When I select an entry within the Kanban board and then the priority property (select), I have to click twice on an option until it is applied (only for the first time). (As if the first click activates the options window and then the second click selects the option.) 

### How to Reproduce

Add a select property to a Kanban board
Add an option
Add another card
Select the option in the select property

### Expected Behavior

Click once to select an option

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.2

**Comment by vedant-pandey** [comment]
I want to work on this
