### ISSUE TITLE
[FR] Add Duplicate to the card action menu

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2833]
### Description

To duplicate a canbanboard item it would be handy if I didn't have to open it first, but could select it from the context menu (:), where I can also delete it so far.
<img width="261" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/fed71bee-3921-4218-bf46-4d641b49956b">

### Impact

Kanban users

**Comment by vedant-pandey** [comment]
I want to work on this
