### ISSUE TITLE
[Bug] the order of cards doesn't save after restarting the application

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2835]
### Bug Description

After I changed the order of the items in the canbanboard and restart Appflowy, the old order is displayed again

### How to Reproduce

Reorder cards under the same stack
Close AppFlowy and restart

### Expected Behavior

The order is saved

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.2

**Comment by rizwan3395** [comment]
Hi @annieappflowy, It seems interested to me, I wanna take this task. Please assign me.

**Comment by rizwan3395** [comment]
@annieappflowy any update on this task?

**Comment by Xazin** [comment]
> @annieappflowy any update on this task?

Hey Rizwan, I've assigned you. Feel free to let us know if you have any questions.

**Comment by rizwan3395** [comment]
Thank You @Xazin. Sure will let you know.

**Comment by appflowy** [comment]
Hey @rizwan3395 Sorry. This task is assigned to Alex.

**Comment by rizwan3395** [comment]
Hey @appflowy I have already started and near to complete it till Monday. I already gave time on it.

**Comment by rizwan3395** [comment]
# More Findings on issue #2835

## [Bug] the order of cards doesn't save after restarting the application

- [Appflowy](https://github.com/AppFlowy-IO/AppFlowy)

## Project

- [x] [Appflowy](https://github.com/AppFlowy-IO/AppFlowy)
- [x] [Appflowy-board](https://github.com/AppFlowy-IO/appflowy-board)

## Summary

- To create this issue faster we can we can just switch windows for the left side menu.
  - I am attaching a video to share how to reproduce the issue much faster.
[Video](https://github.com/AppFlowy-IO/AppFlowy/assets/47111784/d5e4197b-24e7-48e8-88b2-430f91c2db42)

- I also discovered few more issues while investigating this one.
  - When placing row in any other group, Prefilled with some existing rows, the row is added always to group[groupid].rows.last
<img width="929" alt="Screenshot 2023-07-22 at 5 09 37 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/47111784/e349e11c-9251-4a37-bbcc-6155010de907">

  - When placing row in any other group, Prefilled with some existing rows, the assigned index is is flaky.
  - When assigning a row to the last of same group, i.e. moving any row to the latest in group, debug-log gives Warning: for index out of bounds.
<img width="389" alt="Screenshot 2023-07-22 at 5 09 58 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/47111784/5d411755-5659-42b9-9327-f9ca5112cf8d">

@appflowy I would need some more time with this, anyways i am attaching few more useful insights on this, maybe @a-wallen would use this info and get it solved ... 🙂

**Comment by a-wallen** [comment]
> # More Findings on issue #2835
> ## [Bug] the order of cards doesn't save after restarting the application
> * [Appflowy](https://github.com/AppFlowy-IO/AppFlowy)
> 
> ## Project
> * [x]  [Appflowy](https://github.com/AppFlowy-IO/AppFlowy)
> * [x]  [Appflowy-board](https://github.com/AppFlowy-IO/appflowy-board)
> 
> ## Summary
> * To create this issue faster we can we can just switch windows for the left side menu.
>   
>   * I am attaching a video to share how to reproduce the issue much faster.
>     [Video](https://github.com/AppFlowy-IO/AppFlowy/assets/47111784/d5e4197b-24e7-48e8-88b2-430f91c2db42)
> * I also discovered few more issues while investigating this one.
>   
>   * When placing row in any other group, Prefilled with some existing rows, the row is added always to group[groupid].rows.last
> 
> <img alt="Screenshot 2023-07-22 at 5 09 37 PM" width="929" src="https://user-images.githubusercontent.com/47111784/255336529-e349e11c-9251-4a37-bbcc-6155010de907.png">
> * When placing row in any other group, Prefilled with some existing rows, the assigned index is is flaky.
> * When assigning a row to the last of same group, i.e. moving any row to the latest in group, debug-log gives Warning: for index out of bounds.
> 
> <img alt="Screenshot 2023-07-22 at 5 09 58 PM" width="389" src="https://user-images.githubusercontent.com/47111784/255336454-5d411755-5659-42b9-9327-f9ca5112cf8d.png">
> @appflowy I would need some more time with this, anyways i am attaching few more useful insights on this, maybe @a-wallen would use this info and get it solved ... 🙂

@rizwan3395 do you have an open PR that I can take a look at?

**Comment by annieappflowy** [comment]
@a-wallen , FYI: this is not a bug but a feature to build
