### ISSUE TITLE
[FR] Make essential editor shortcuts like CTRL+Arrow and HOME/END act as expected in Windows, or configurable

### ISSUE THREAD

**Issue by jaggujajamensan** [AppFlowy-IO/AppFlowy#2838]
### Description

Windows has a standard way of handling editor shortcuts like ctrl+arrow and home/end, that is unified in almost every text editor out there, in Windows but also in browsers, and websites like GitHub's text editor. When typing even in this text-box I can use these shortcuts.

**Expected behavior**:
`Home` -> Start of current line
`End` -> End of current line
`ctrl`+`left` -> One word to the left
`ctrl`+`right` -> One word to the right

**Actual behavior:**
`Home` -> Nothing
`End` -> Nothing
`ctrl`+`left` -> Start of current line (what `home` normally does)
`ctrl`+`right` -> End of current line (what `end` normally does)

I can see why this change could be useful and preferred, but as AppFlowy is imagined as an alternative to Notion, something that seems to appeal to power-users, these keys should at least be configurable in the settings, so that people can choose to use the key-bindings they're used to.

### Impact

This ends up being jarring to anyone used to editing text on Windows, who uses these shortcuts.

**Comment by annieappflowy** [comment]
Thanks @jaggujajamensan for the feedback. Much appreciated it.
We're enabling users to [customize shortcuts](https://github.com/AppFlowy-IO/AppFlowy/pull/2112/files/59fa5e0ebc8c9e3600dd657eb498958106311316..8bfe4047b3dac20a0387736128d8b07f38c455d8). It is scheduled to release in v0.2.3 (the upcoming one)

**Comment by annieappflowy** [comment]
> I would say that Home and End keys are universal way of navigating text on almost every platform and should be usable without customization... although customization in general is much appreciated :)

Thanks for your feedback. We're working on Home and End keys https://github.com/AppFlowy-IO/AppFlowy/issues/2817
It's done actually. Will include the change in the upcoming release.

**Comment by MayurSMahajan** [comment]
We have achieved the required functionality for Home and End keys, soon I will submit a PR that will update the ctrl+arrow keys.

**Comment by MayurSMahajan** [comment]
From release 0.2.7 onwards the expected behavior on windows and linux is supported.
