### ISSUE TITLE
[Bug] slash menu keyword

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2844]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/4c430630-37d8-40b6-8e60-8841aca3d9b3

### How to Reproduce

Follow the video

### Expected Behavior

the callout option shows up

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.2

**Comment by johansutrisno** [comment]
Hi @annieappflowy , I am newcomers and I was able to reproduce this issue and here is a screenshot of what I did, does it meet the requirements?
and I fixed this issue in the appflowy-editor package, can I fix it from there?

Thank you


https://github.com/AppFlowy-IO/AppFlowy/assets/22239637/f5c50186-f97f-4362-91d2-17b282ff1be5

**Comment by LucasXu0** [comment]
@johansutrisno It looks good. You can submit a PR to the appflowy-editor repo.

**Comment by johansutrisno** [comment]
Hi @LucasXu0 , I have submitted the PR, please review it, thanks
[https://github.com/AppFlowy-IO/appflowy-editor/pull/268](#268)

**Comment by annieappflowy** [comment]
Fixed
