### ISSUE TITLE
[FR] Hover turns a hand icon

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2850]
### Description

<img width="158" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/1a544ae4-be9e-4db8-becd-9d42446d224b">

Hovering on an action menu shows a hand icon
<img width="101" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/828544dc-6fa9-4d58-82be-c7cd8a11faff">

### Impact

All users

**Comment by annieappflowy** [comment]
<img width="78" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/0625afbd-a17b-46fc-837c-3f3123c47c0c">

Hovering on the page icon doesn't show a hand pointer

**Comment by richardshiue** [comment]
> Hi @richardshiue , could you help add the hover effect for the side action menu of the editor? ![image](https://user-images.githubusercontent.com/12026239/252287136-6726ab2d-5e8b-4131-95d8-b97eeeb5c406.png)

Absolutely

**Comment by LucasXu0** [comment]
Both the action menu and the icon menu show the ✋🏻 when hovered over. Close as completed.

**Comment by annieappflowy** [comment]
Not on Windows 11 v0.2.7 
<img width="72" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ca0e5681-6033-450d-b0f3-af12e38fa0dc">

**Comment by richardshiue** [comment]
Oh this is reproducible on windows, got it. There seems to be an upstream issue https://github.com/flutter/flutter/issues/99323 . According to it, the windows win32 api doesn't have a grab cursor, maybe we can use the click or move instead? If not, we'll have to do a custom cursor with png files.

https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/152017a0-a192-4e60-9317-2c56dc669b3a/d5450k9-7e210ff8-ee75-4e95-b04c-2907abd86135.png

**Comment by Xazin** [comment]
> Oh this is reproducible on windows, got it. There seems to be an upstream issue [flutter/flutter#99323](https://github.com/flutter/flutter/issues/99323) . According to it, the windows win32 api doesn't have a grab cursor, maybe we can use the click or move instead? If not, we'll have to do a custom cursor with png files.
> 
> https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/152017a0-a192-4e60-9317-2c56dc669b3a/d5450k9-7e210ff8-ee75-4e95-b04c-2907abd86135.png

I believe using the click cursor on Windows is the best option for now. :+1:
