### ISSUE TITLE
[Bug] indent not cancel out after pressing backspace

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2851]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ad532758-be24-4e55-bcf7-fdac6182861d

### How to Reproduce

1. At an empty line, press Tab
2. write something
3. press Enter
4. write something
5. press Enter
6. press Backspace

### Expected Behavior

After pressing backspace, the cursor should go back to the beginning of the current line rather than go to the end of the previous line

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.2

**Comment by Xazin** [comment]
Seems to have been resolved, can you double check @annieappflowy ?

**Comment by annieappflowy** [comment]
Confirmed it was fixed
