### ISSUE TITLE
[FR] Support for multiple systems using the same Appflowy

### ISSUE THREAD

**Issue by JeffGuldblum** [AppFlowy-IO/AppFlowy#2859]
### Description

Hi!

I started using Appflowy since last week and its been working great.

However I would like to see a feature which would allow me to open the same Appflowy file on a different computer. I understand it would be hard to would allow them to work at the same time. But my request is to use the same Appflowy file at different times (like how KeePass works). This is because I use a different system at home then when I am on the road.

Cheers!

(Sorry if this already a feature and I didnt see it, I scoured the docs but couldn't find anything)

### Impact

Users with multiple systems.

**Comment by annieappflowy** [comment]
You can try one drive. It works great for me.
Google Drive would run into some weird lock issues.

**Comment by annieappflowy** [comment]
We're working on cloud solutions, which will enable you to sync data across devices including mobile.

**Comment by JeffGuldblum** [comment]
I tried using onedrive by using the same folder one both devices. But then I am probably selecting the wrong folder. How do I import a whole appyflow from another computer?

**Comment by JeffGuldblum** [comment]
Sorry I accidentally closed the Issue!

**Comment by annieappflowy** [comment]
The folder should be the parent folder of cache and kv
<img width="167" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8458a41c-fdfb-44e6-9746-d52844c5674f">

Let me know if you need more help

**Comment by JeffGuldblum** [comment]
I tried using that folder, but I might have found the problem. On both my systems it didn't create a kv file. I also looked if it was in the default install location(Appdata) but there also wasn't a kv file.

![afbeelding](https://github.com/AppFlowy-IO/AppFlowy/assets/79310818/b8b2ec96-d9d3-4b4f-ae05-96fcd635b99e)
This is what my parentfolder lookslike (I crossed to the main folder as I thought it might contained personal information)

**Comment by appflowy** [comment]
> I tried using that folder, but I might have found the problem. On both my systems it didn't create a kv file. I also looked if it was in the default install location(Appdata) but there also wasn't a kv file.
> 
> ![afbeelding](https://user-images.githubusercontent.com/79310818/247500430-b8b2ec96-d9d3-4b4f-ae05-96fcd635b99e.png) This is what my parentfolder lookslike (I crossed to the main folder as I thought it might contained personal information)

Have you tried opening the folder that contains cache.db, AppFlowy-client.log.2023006-21, and the xxx?"

**Comment by JeffGuldblum** [comment]
Yes, it didnt work previously but I just tried and somehow it did work. I can't check on my other device yet, but it looks like it was a problem on my part. Sorry for the trouble.

If I have a problem on the other device ill contact you again, thankyou so much for the for now! :)
🥇 = Support

p.s. Mayby it didn't work cause I selected the folder on first start-up and not via the settings?

**Comment by annieappflowy** [comment]
No problem. We're here to help you! Just let us know 😄

**Comment by emmggi** [comment]
Maybe Syncthing could be helpful. I think the DB should be closed whenever it's synced.

**Comment by annieappflowy** [comment]
@JeffGuldblum , please try out AppFlowy Mobile and Cloud
Download the mobile app from https://appflowy.io/download#ios-and-android
Be sure to read [this guide](https://docs.appflowy.io/docs/guides/sync-desktop-and-mobile) before logging into mobile
