### ISSUE TITLE
[Bug] Referencing Calendar doesn't work

### ISSUE THREAD

**Issue by VenomSupreme** [AppFlowy-IO/AppFlowy#2881]
### Bug Description

When referencing a calendar in a Document, the calendar shown is empty, but when changed to grid, it shows all the data of calendar in grid layout.

### How to Reproduce

Create a document
Reference a calendar

### Expected Behavior

It should reference calendar properly 

### Operating System

WIN 10

### AppFlowy Version(s)

v0.2.3

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/69515491/669d8974-509f-4460-b22d-8858e5cb5672

**Comment by appflowy** [comment]
hi @VenomSupreme. Please check the top right corner; there's an indicator for all the rows missing a date.

**Comment by annieappflowy** [comment]
Resolved via Discord
