### ISSUE TITLE
[FR] Images in Details page of a row in grid

### ISSUE THREAD

**Issue by VenomSupreme** [AppFlowy-IO/AppFlowy#2884]
### Description

Being able to put screenshots/images in the details page of a row in grid

### Impact

People who need to put screenshots as a reference in their grid. 

I have to put screenshots everyday in grid and currently I'm using links for screenshots, so whenever I want to see the screenshot I open the link. It works but having to open a link everytime you want to see an image and it redirecting to browser is a lil annoying and affects the productivity since now I've to keep appflowy and my browser windows side by side to see if what I've written in grid is matching with the screenshot.

So having the ablity to just put screenshot in details page will make it easier to do all this.

**Comment by annieappflowy** [comment]
Hi @VenomSupreme , thanks for your feedback. I'd like to better understand your need.

Are you intended to put images in a property / column or in the editing area where you can access the slash menu?

**Comment by ld892012** [comment]
> Are you intended to put images in a property / column or in the editing area where you can access the slash menu?

This kind of feature can be useful for me ^^

**Comment by EvenTopland** [comment]
I need this too! Very useful for shotlists in a video production

**Comment by annieappflowy** [comment]
<img width="811" alt="image" src="https://github.com/user-attachments/assets/e2ada1de-1bce-4570-8e71-5b31ca6b6fe5">
<img width="997" alt="image" src="https://github.com/user-attachments/assets/7f8377c4-17e5-4e29-98c4-440ac7d9edb2">

Supported
