### ISSUE TITLE
[Bug] Support for the following shortcuts

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#2888]
### Bug Description

The following shortcuts are not supported in the latest AppFlowy version.

- [x] Cut using Ctrl/Cmd + X
- [x] Delete using Delete
- [x] Shift+Home to select till the start of the line in Windows
- [x] Shift+End to select till the end of the line in Windows.
- [x] Ctrl+Y for a Redo in Windows.

### How to Reproduce

To reproduce:
1. Open the AppFlowy app
2. Try using the specified shortcuts
3. Observe that nothing happens

### Expected Behavior

The shortcuts should work.

### Operating System

Windows 11

### AppFlowy Version(s)

0.2.3

**Comment by alihassan143** [comment]
> ### Bug Description
> The following shortcuts are not supported in the latest AppFlowy version.
> 
> * [ ]  Cut using Ctrl/Cmd + X
> * [x]  Delete using Delete
> * [x]  Shift+Home to select till the start of the line in Windows
> * [x]  Shift+End to select till the end of the line in Windows.
> * [x]  Ctrl+Y for a Redo in Windows.
> 
> ### How to Reproduce
> To reproduce:
> 
> 1. Open the AppFlowy app
> 2. Try using the specified shortcuts
> 3. Observe that nothing happens
> 
> ### Expected Behavior
> The shortcuts should work.
> 
> ### Operating System
> Windows 11
> 
> ### AppFlowy Version(s)
> 0.2.3
> 
> ### Screenshots
> _No response_
> 
> ### Additional Context
> _No response_

cut command added in [#240](https://github.com/AppFlowy-IO/appflowy-editor/pull/240)
