### ISSUE TITLE
[Bug] inline calendar date duplication

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2891]
### Bug Description

issue 1 : so everytime a "new calender" or a "referenced calender" is created, it adds a new "date" property

### How to Reproduce

Create a calendar and add a few events
Reference it in a document
There is a duplicated Date field created, which is not intended

### Expected Behavior

Don't create extra Date properties 

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.3

**Comment by vedant-pandey** [comment]
Can I take this issue?
