### ISSUE TITLE
[Bug] Import markdown underline

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2893]
### Bug Description

When I save a page as markdown in version 0.2.4-portable (W11, 22H2) and then import it again, the formatting "underline" is shown as tag (see picture). The formatting "H1", "H2" and "italic" is displayed correctly.

### How to Reproduce

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/3f5624ca-579e-405c-a23d-5b9983936ccc)

### Expected Behavior

Should detect the underline markdown properly when importing

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.4

**Comment by vedant-pandey** [comment]
Hi I was able to reproduce this issue, can I work on this?

**Comment by annieappflowy** [comment]
If you can submit a PR by the end of Wednesday, yes
Otherwise, we prefer to fix it asap

**Comment by vedant-pandey** [comment]
Sure, makes sense, will try to raise pr before wednesday

**Comment by annieappflowy** [comment]
Thank you. Assigned

**Comment by vedant-pandey** [comment]
Hi @annieappflowy i found the root cause to be coming from missing parser in appflowy editor. I have added my changes for the same [in this PR](https://github.com/AppFlowy-IO/appflowy-editor/pull/256)
