### ISSUE TITLE
[Bug] Can not input text

### ISSUE THREAD

**Issue by aa1ss2** [AppFlowy-IO/AppFlowy#2894]
### Bug Description

Chinese input methods for computers cannot be used normally, and there will be character echo.

### How to Reproduce

Enter any Chinese characters 
example

input 测试
display 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79680252/3c3c5be6-13ce-435a-bb03-da55055b0578)

### Expected Behavior

fixed

### Operating System

windows 11

### AppFlowy Version(s)

0.2.4

**Comment by annieappflowy** [comment]
duplicate of https://github.com/AppFlowy-IO/AppFlowy/issues/1404
