### ISSUE TITLE
[FR] Changes language names to their respective languages

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/appflowy#290]
**1~3 main use cases of the proposed feature**
Ex: As a non English speaker, I want to able to change the language of the app to my preferred language. However, the languages in the application are currently written in English.

**what types of users can benefit from using your proposed feature**
Non English speakers who want to change the language of the application

**Additional context**
When going into the settings to change the language setting, the user is presented with language names in English. This makes it difficult for a non English speaker to find their language.

**To Reproduce**
1. Click on the 'gear' icon to go into settings
2. Click on the 'Language' menu option. (This has an icon, so it's not that bad if you don't understand English)
3. A menu appears with all the languages in English.

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/151711705-d10e523d-f618-4bf4-b0f6-75e1ac4e8495.png)

**Comment by bolshoytoster** [comment]
@MikeWallaceDev I've opened a [pull request](https://github.com/AppFlowy-IO/appflowy/pull/293).
