### ISSUE TITLE
[FR] The application remembers being maximized

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#2904]
### Description

Currently, Appflowy is capable of remembering the window's last size upon startup. However, if it was maximized, the newly-opened application would open in the largest size, but as a floating window. It would be nice if it could remember being maximized, or as a floating window with a smaller size.

### Impact

Users who open AppFlowy as a maximized window.

**Comment by annieappflowy** [comment]
reopen window position is changed and some areas are outside the screen
