### ISSUE TITLE
[FR] Image Copy

### ISSUE THREAD

**Issue by lariane-guerra** [AppFlowy-IO/AppFlowy#2905]
### Description

It is possible that in the future it will be implemented image copy?

Today there is a away to put image in document?

### Impact

Add imagens in documents.

**Comment by lariane-guerra** [comment]
@LucasXu0 yeap, a local image. 

But today, i need to put the image in a host site to get a url? 
Its hard to get a local image ?

**Comment by LucasXu0** [comment]
We will include the functionality to insert local images in the next version.

**Comment by lariane-guerra** [comment]
Wow, nice team! :rocket:

**Comment by annieappflowy** [comment]
can we copy an image and paste it? @LucasXu0

**Comment by LucasXu0** [comment]
@annieappflowy Not support yet.

**Comment by Schrolli91** [comment]
Copy and paste an image direct into the docuemt would be realy nice.
I often take some simple screenshots to clarfy some docuembtations.
The screenshot tool copies the image direct into clipboard.
Saving the image and then load it in AppFlowy is totaly unefficent.

**Comment by annieappflowy** [comment]
Strongly agreed, @Schrolli91 
cc: @LucasXu0

**Comment by annieappflowy** [comment]
Hi @Schrolli91 @lariane-guerra , you can now copy an external image and paste into an AppFlowy doc. Please give it a try with the latest release ([v0.3.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.3.0)) and let us know your feedback. Thanks!

**Comment by Schrolli91** [comment]
@annieappflowy tested and works like a charme - thanks for this beautiful feature :-)

**Comment by annieappflowy** [comment]
Thanks @Schrolli91 for confirming. If you find anything missing in AppFlowy, please don't hesitate to create an issue.

**Comment by lariane-guerra** [comment]
WOW yes @annieappflowy. Thanks for this. I really enjoy the AppFlowy <3.

**Comment by annieappflowy** [comment]
Thanks @lariane-guerra for confirming. If you find something missing in AppFlowy, please feel free to submit an issue. We'll take care of the rest.
