### ISSUE TITLE
[FR] Inline Math Equations

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/AppFlowy#2909]
### Description

Currently AppFlowy supports maths equations as their own blocks, but it would be cool to be able to write them inline as well, to be integrated in paragraphs.

### Impact

Would be highly useful when using AppFlowy in academic setting, especially when doing Maths or Physics.

**Comment by yatendra2001** [comment]
hey, @LucasXu0 have you started working on this?? I can pick up this.
