### ISSUE TITLE
[FR] Import a page from the zip file provided by Notion

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/AppFlowy#2911]
### Description

When we export a page from Notion we get a zip file, which contains a markdown file with all the page contents and another folder having all the assets of the page like images.

<img width="266" alt="Screenshot 2023-06-29 at 5 41 09 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/6f947cb8-7d03-4c10-9f05-2bd12bb0ffb6">

In the import panel, there should be an option for importing from Notion. Then, we should have options to select what we want to import, such as pages, boards, grids, or calendars. When the user clicks on "pages" they should be able to select the zip file and import their page from there.

### Impact

Any user who wants to import a page from Notion

**Comment by Mukund-Tandon** [comment]
I would like to work on this issue

**Comment by LogicFan** [comment]
i think it would be better to fetch notion raw data using notion public api instead of using exported markdown since some info will be missing with exported markdown.

**Comment by Mukund-Tandon** [comment]
> i think it would be better to fetch notion raw data using notion public api instead of using exported markdown since some info will be missing with exported markdown.

I think we can also implement fetching data from the Notion API along with the zip file. Since the Notion API does not provide the complete workspace, we need to use the export workspace option, which gives us a zip file. This issue is a prerequisite for that step.

Additionally, could you please let me know what things are missing with the exported markdown so that I can handle those cases appropriately?

**Comment by LogicFan** [comment]
> > i think it would be better to fetch notion raw data using notion public api instead of using exported markdown since some info will be missing with exported markdown.
> 
> I think we can also implement fetching data from the Notion API along with the zip file. Since the Notion API does not provide the complete workspace, we need to use the export workspace option, which gives us a zip file. This issue is a prerequisite for that step.
> 
> Additionally, could you please let me know what things are missing with the exported markdown so that I can handle those cases appropriately?

one example would be "Notion pages that contain parentheses or dashes in the title will have them removed by Notion while exporting your data so the file will be created without them, even though the link itself will still retain them." as quoted from an opensource implementation of notion2obsidian converter.

**Comment by AkechiShiro** [comment]
Any milestone version for this feature @annieappflowy ?

**Comment by appflowy** [comment]
We support importing notion as a new workspace. I will close this FR

**Comment by MarcusDelvecchio** [comment]
Considering it seems like [a common experience](https://www.reddit.com/r/Notion/comments/mpt7aj/your_data_is_stuck_in_notion/) where the Notion workspace exports never actually succeed (I have been waiting for the email for hours), another import method would be highly valuable.

As mentioned in the original post, if we could import the .html file and the corresponding assets folder—or at least if there would some workaround to mock import the single exported file pair mentioned as a single-file workspace, this would be great. I am easily able to export my single notion file as a .html and assets folder pair, and am able to import said .html file into AppFlowy, but not the assets.

<img width="252" alt="image" src="https://github.com/user-attachments/assets/58d3408b-c86d-434a-8602-8d2cef1c92f5" />

This import issue is preventing me from using the application as a drop-in alternative, but sadly Notion is difficult about exporting.
