### ISSUE TITLE
[Bug] Removing last block in a document makes its body uneditable

### ISSUE THREAD

**Issue by vedant-pandey** [AppFlowy-IO/AppFlowy#2916]
### Bug Description

When you delete the last block on a document it makes the body of the document uneditable.

### How to Reproduce

1. Create a new document
2. Add anything on the only line which exists on the block
3. Delete the block
4. You cannot edit the document anymore

### Expected Behavior

There should always be at least one block in the body of the page

### Operating System

Mac OS - Ventura 13.4 (22F66)

### AppFlowy Version(s)

Latest commit - https://github.com/AppFlowy-IO/AppFlowy/commit/95d4fb68654f008bc0562e8f69c07faba5fab6d4

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/25723331/9a64d24d-7a74-49df-999a-19a949b18dbd

**Comment by LucasXu0** [comment]
Fixed in this commit. https://github.com/AppFlowy-IO/AppFlowy/pull/2913.

I have added some rules to ensure that there must be at least one paragraph, and the last node must also be a paragraph.
