### ISSUE TITLE
[FR] Allow mouse selection actions

### ISSUE THREAD

**Issue by vedant-pandey** [AppFlowy-IO/AppFlowy#2923]
### Description

Currently using mouse left-click to select content/blocks is not possible in appflowy. Allowing this would result in a better user experience as mouse select edits are more intuitive for most people.

### Impact

All desktop users

**Comment by annieappflowy** [comment]
Can you please elaborate?
We support left-click to select contents
We also support using the left menu to select a block
<img width="921" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/1d5e448c-0310-497c-be48-7c7a71504028">

**Comment by vedant-pandey** [comment]
Mouse area select like this

https://github.com/AppFlowy-IO/AppFlowy/assets/25723331/159402ad-54da-43d1-81d8-40f58b3c5382

**Comment by annieappflowy** [comment]
should work?
please reopen if you still see the issue
