### ISSUE TITLE
[FR] Web bookmark inline

### ISSUE THREAD

**Issue by aurkodip** [AppFlowy-IO/AppFlowy#2933]
### Description

Embed links

### Impact

Create easy workflow and visibility for motivation between eg Google docs/MS office

**Comment by annieappflowy** [comment]
Hi @iaurinko , can you please elaborate?

**Comment by iaurinko** [comment]
like if i have a google doc as my next novel, i cannot embed the link(with a view) in the system. if it is there, i will find motivation to continue writing everyday i see it, like in notion

**Comment by annieappflowy** [comment]
Is this what you meant?
<img width="314" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/70d2b045-a4f6-45c4-bef2-86f86fcd51b8">
<img width="415" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c8462eb3-5370-439a-9579-c0e688ec1fb0">

**Comment by annieappflowy** [comment]
Including in the upcoming release
