### ISSUE TITLE
[Bug] Use of undeclared identifier 'FlowyInfraUIPlugin'

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/AppFlowy#2934]
### Bug Description

hi there! I was trying to implement the `flowy_infra_ui` plugin into my app to use with appflowy_editor, but I get the following error when building with iOS:
```
Could not build the precompiled application for the device.
Semantic Issue (Xcode): Use of undeclared identifier 'FlowyInfraUIPlugin'
```
the app seems to compile fine for MacOS and the web targets. i'm not sure if this a bug, or if i'm just setting up the Flutter plugins incorrectly. Thank you so much!

### How to Reproduce

Use AppFlowy Editor package and try to integrate a plugin such as the math equations, which requires flowy_infra_ui.

### Expected Behavior

For the app to compile on iOS

### Operating System

iOS

### AppFlowy Version(s)

main branch

### Additional Context

Thank you for your help :)

**Comment by annieappflowy** [comment]
Could you please provide us with more high-level context? For example, what are you building with appflowy_editor and why did you decide to use it? What AppFlowy plugins do you need in your app?

**Comment by garv-shah** [comment]
Hi @annieappflowy! I'm using `appflowy_editor` for an education app platform which encompasses a tutoring app, an app for my school's maths club and an app for orphanages as of now. Namely, I'm using the editor to streamline the process of making questions, quizzes and posts within the app, so it is easy to curate content. I recently switched to the package because the other WYSIWYG Flutter packages were quite painful to use, and packages like `visual_editor` or `flutter_quill` had numerous problems, which I've outlined here: https://github.com/AppFlowy-IO/appflowy-editor/issues/258#issuecomment-1612393985

Right now, I need the actions plugin and the math_equation plugin for my app, as the platform needs maths support. I am not sure if I implemented the `flowy_infra_ui` plugin wrong, but the app builds fine for MacOS but produces the error above when I try to build on iOS at the path `./ios/Runner/GeneratedPluginRegistrant.m:135:3`.

Would you know of what could cause this issue? Thanks!

**Comment by garv-shah** [comment]
Hi @annieappflowy! Any updates on this?

**Comment by LucasXu0** [comment]
@garv-shah The flowy_infra_ui package is not public. Therefore, I don't think you can import it into your project. We are currently in the process of splitting some common plugins into a new library called appflowy_editor_plugins, which may be more suitable for your use case.

Could you please provide more details about which plugins are currently only in AppFlowy but you would like to import into your project?

**Comment by garv-shah** [comment]
That'd be great, a common plugins library would be extremely useful! :D
The two plugins only in AppFlowy that I would like to import into my project are `math_equation` and `actions`, which both require the `flowy_infra_ui` package as well.

**Comment by garv-shah** [comment]
Closing this for now as it will likely be resolved by the introduction of the `appflowy_editor_plugins` package.
