### ISSUE TITLE
[Bug] Board item detail overlay has overflow.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2937]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/412bed0a-ba48-4655-b783-c8af62ada480)

If there's more than one line of text, the title overflows.

### How to Reproduce

Open a new Board Item and type 100+ characters.

### Expected Behavior

There's a couple of options here:
1. Make the text horizontally scrollable.
2. Make the form field vertically scrollable.
3. Expand the entire overlay as the text grows.
4. Hide the overflow.

I think making the field scrollable is the wisest decision.

### Operating System

Windows

### AppFlowy Version(s)

main

**Comment by yatendra2001** [comment]
Thanks @a-wallen.
@annieappflowy can you assign this to me, I can start fixing this issue by reproducing first.

**Comment by yatendra2001** [comment]
awesome thanks @Xazin for assigning.

**Comment by yatendra2001** [comment]
@Xazin fixed this and added a test for the same in PR.
