### ISSUE TITLE
[FR] Work on multiple workspaces at a time using tabs

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#2942]
### Description

Searched through the issues if someone suggested but didn't find any.

I propose a way to have multiple workspaces open at once (as tabs) so that they can be all edited without going through the note list every time to find other documents.

Obsidian has this for instance.

### Impact

Everyone who may edit several different documents/workspaces at a time.

### Additional Context

I suggest these tabs be in the appbar below the title. When there's only one document open it should be hidden.

Opening a workspace with a double-click opens it in a new tab, while a single-click will open it in place ie open it in the tab that is currently open.

**Comment by annieappflowy** [comment]
Is this what you mean?
<img width="911" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/f838bbdc-8579-4625-9fe2-958c182d24c7">

**Comment by Xazin** [comment]
I actually have something done on my local for this. I could most likely finish it up within a couple of days.

I just checked the progress, there are a few things that I still need to work on, but you can see a small sample here.

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/5aa4c5ab-2f3c-4792-ad66-e8f44ecd1c6b

**Comment by annieappflowy** [comment]
Wow, that's cool! 

FYI, I had a master issue about page organizations: https://github.com/AppFlowy-IO/AppFlowy/issues/2312

**Comment by emmggi** [comment]
@annieappflowy yes, I mean this what @Xazin showed, only it would make more sense for it to be below the title in my opinion.

**Comment by Xazin** [comment]
> @annieappflowy yes, I mean this what @Xazin showed, only it would make more sense for it to be below the title in my opinion.

Below the title? I don't think that would look well and be a good UX to be honest.

I can't find any other application or design where tabs would be below in hierarchy to something that is related to the tab itself.

I am interested if you can tell me more, and maybe if you know of some similar existing solutions?

**Comment by emmggi** [comment]
@Xazin In that way you are right but, visually, because you have a divider (or is it underline) in that widget it would make more sense to have it separate appbar from the rest of the body. Or best, remove the border to make it blend in.

**Comment by Xazin** [comment]
> @Xazin In that way you are right, but, visually, because you have a divider (or is it underline) in that widget it would make more sense to have it separate appbar from the rest of the body. Or best, remove the border to make it blend in.

Ah, okay. What you are seeing in my recording is basically a mock og the functionality, the UI wasn't touched.

I will open a PR next week and include a recording with the end result, it will look cleaner, guaranteed.

**Comment by emmggi** [comment]
Thank you.

**Comment by Xazin** [comment]
@emmggi See #2962

**Comment by emmggi** [comment]
@Xazin This looks great. Thank you.

Is there a possibility to add this behavior as well that I mentioned in my original message?

> Opening a workspace with a double-click opens it in a new tab, while a single-click will open it in place ie open it in the tab that is currently open.

This would make it much easier to open in new tabs than use the menu.

**Comment by Xazin** [comment]
> @Xazin This looks great. Thank you.
> 
> 
> 
> Is there a possibility to add this behavior as well that I mentioned in my original message?
> 
> 
> 
> > Opening a workspace with a double-click opens it in a new tab, while a single-click will open it in place ie open it in the tab that is currently open.
> 
> 
> 
> This would make it much easier to open in new tabs than use the menu.

Would middle mouse button work for you instead of double click?

**Comment by emmggi** [comment]
Sure.
