### ISSUE TITLE
[FR] Adding multiple images at once and creating a grid of multiple images.

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#2947]
### Description

I think it would be useful to group images when adding several at a time. Not when adding one image at a time, only when picking multiple.

It could look something like how social media sites group albums for a preview.
![Album grid layout styles](https://i.etsystatic.com/20343555/r/il/06f8b3/2040762720/il_1588xN.2040762720_ojh9.jpg)

It should also allow clicking on an image to preview in full size.

### Impact

Anyone who imports several images.

### Additional Context

I think adding one image at a time, one below the other is too space consuming and also less readable.

Implementing multi-select for images is a prerequisite for this. As I recall this was already suggested in another issue.

EDIT: I think the type of grid and image order should depend on their size.
EDIT 2: Creating an album of existing images could mean having a button in image block options to select images to group. I don't know how this aligns with how things are done in apps. 
EDIT 3: Suggestion on how this could be implemented is creating a separate "image album block" in the `/` menu.

**Comment by Xazin** [comment]
I'm just dropping this here for the Flutter perspective https://pub.dev/packages/flutter_staggered_grid_view

**Comment by emmggi** [comment]
I forgot to add that it should not show if there's more than 30 images in an album. There should be a button to "Show more", they should be loaded 10 by 10 when you hit show more.

**Comment by emmggi** [comment]
I see this feature is planned @annieappflowy. Is there an approximate ETA? I keep needing to add multiple images at a time but it's time consuming and not grouping images is not very space efficient.

**Comment by annieappflowy** [comment]
Hi @emmggi , we will work on adding multiple images and uploading files in Q2 this year. 
The current priorities are enabling team collaboration, search across the workspace, and mobile improvements.
