### ISSUE TITLE
[Bug] Failed to start Flutter renderer: Unable to create a GL context

### ISSUE THREAD

**Issue by tennox** [AppFlowy-IO/appflowy#295]
**Describe the bug**
First - I tried to run the v0.2.0 release:
```
Failed to execute process './app_flowy'. Reason:
exec: Exec format error
The file './app_flowy' is marked as an executable but could not be run by the operating system.
```

So I tried **building from source** - but I get this when running the compiled binary:
```
⋊> ./app_flowy

** (app_flowy:21547): WARNING **: 03:05:10.061: Failed to start Flutter renderer: Unable to create a GL context

** (app_flowy:21547): WARNING **: 03:05:12.733: Unable to retrieve framework response: No engine to send to
```
(the last line happens when I click inside the empty window)

**To Reproduce**
1. set up dev environment [official instructions](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux)
2. Build using either `cargo make -p development-linux-x86 appflowy-linux-dev` or `cargo make -p production-linux-x86 appflowy-linux`
3. `cd ./app_flowy/product/0.0.3/linux/Release/AppFlowy/ && ./app_flowy` (or `linux/Debug`)
4. See empty window & error in terminal

**Screenshots**
![Screenshot from 2022-02-02 03-08-42](https://user-images.githubusercontent.com/2084639/152082443-c0eab260-a04b-49d8-b478-2539a1699a5c.png)

**Desktop (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera (ubuntu)
 - Version: commit 728d60239a34a73174e99c191299be0ab29b1f97

**Additional context**
 `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on elementary OS 5.1.7 Hera 5.4.0-96-generic, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)
```
`rustup show`
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/manu/.asdf/installs/rust/stable

stable-x86_64-unknown-linux-gnu (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**Comment by irfanbacker** [comment]
You seem to be using the stable channel for rust, but the docs recommend using nightly

**Comment by MikeWallaceDev** [comment]
@irfanbacker, I believe that @appflowy now uses the stable channel (it's 4:22 am, I might be delirious)
If it's the case, then please show me where it says that in the docs and I'll fix it.

**Comment by irfanbacker** [comment]
> @irfanbacker, I believe that @appflowy now uses the stable channel (it's 4:22 am, I might be delirious)
> If it's the case, then please show me where it says that in the docs and I'll fix it. 

Oh okay. The [build instructions for linux](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux) does mention changing default toolchain to nightly in one of the steps.

**Comment by tennox** [comment]
> Also, did you make sure, you were using the x86 build from releases?
Using [x86 release](https://github.com/AppFlowy-IO/appflowy/releases/download/0.0.2/AppFlowy-linux-x86.tar.gz) yields this: :sweat_smile: 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/manu/Downloads/AppFlowy/lib/libdart_ffi.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:19)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:23)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/init_sdk.dart:23)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/init_sdk.dart:19)
#9      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
#10     AppLauncher.launch (package:app_flowy/startup/launcher.dart:36)
<asynchronous suspension>
```

> You seem to be using the stable channel for rust, but the docs recommend using nightly.

Yep, missed that - works now :+1: 

![Screenshot from 2022-02-02 14-53-24](https://user-images.githubusercontent.com/2084639/152167020-d5891d14-841d-4574-8123-ebdb56df827c.png)
