### ISSUE TITLE
[Bug] The animation of scrolling to heading is too slowly when using outline

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2952]
### Bug Description

As the title said, the animation is too slowly now. 

- Just remove the animation is fine.

### How to Reproduce

1. insert some headings.
2. insert an outline block.
3. click the content inside the outline.

### Expected Behavior

Scroll the position of heading directly without any animation.

### Operating System

all platform.

### AppFlowy Version(s)

0.2.5

**Comment by emmggi** [comment]
This slow scrolling also happens when your cursor leaves the screen by scrolling and then start typing. The animation is very slow to bring you back to the cursor.

**Comment by AmanNegi** [comment]
@LucasXu0 I would like to fix this issue with the Outline.

**Comment by LucasXu0** [comment]
@AmanNegi Do you have any ideas now? Feel free to share them here, and we can discuss them together.

**Comment by johansutrisno** [comment]
Hi @LucasXu0 does it meet the requirements? I sped up the animation so the user doesn't feel too slow

https://github.com/AppFlowy-IO/AppFlowy/assets/22239637/60b6a094-470e-4093-af8a-d6efb1cf8029

**Comment by LucasXu0** [comment]
> Hi @LucasXu0 does it meet the requirements? I sped up the animation so the user doesn't feel too slow
> 
>  Screen.Recording.2023-07-19.at.05.08.21.mov

I suggest removing the animation in this case. If you have any ideas, feel free to DM me(Lucas@AppFlowy) on Discord.

**Comment by Xazin** [comment]
I also believe we should remove the animation for the best UX.

**Comment by AmanNegi** [comment]
Yes in a long document this type of scrolling would not be a good experience. If possible we can add a curve to the animation like easeInOut. So that it feels more natural to the user.

**Comment by johansutrisno** [comment]
I see, is it better than before? 
cc @LucasXu0 @Xazin @AmanNegi 

https://github.com/AppFlowy-IO/AppFlowy/assets/22239637/278290f2-ba38-494f-b9cf-b5d2dd3eeefd

**Comment by Xazin** [comment]
> I see, is it better than before? 
> 
> cc @LucasXu0 @Xazin @AmanNegi 
> 
> 
> 
> https://github.com/AppFlowy-IO/AppFlowy/assets/22239637/278290f2-ba38-494f-b9cf-b5d2dd3eeefd
> 
> 
> 
> 

Yeah, best for now. 🙏

**Comment by johansutrisno** [comment]
okay I will create the PR ASAP 🙏🏻

**Comment by johansutrisno** [comment]
I have created the PR for appflowy repo and appflowy-editor repo, please review the PR, thank you in advance
- https://github.com/AppFlowy-IO/AppFlowy/pull/3045
- https://github.com/AppFlowy-IO/appflowy-editor/pull/337
