### ISSUE TITLE
[FR] AppFlowy SyncServer for Multiple instances to edit in real-time

### ISSUE THREAD

**Issue by zparihar** [AppFlowy-IO/AppFlowy#2959]
### Description

Requesting to develop an AppFlowy SyncServer, much like Joplin Server for multiple instances (desktop and mobile) to modify the entries and sync with all instances.

File syncing methods for applications like this are not always ideal - especially in the case where you have your workstation and your laptop running the same application on the shared file and then a modification happens on each while both are open, then the databases/files overwrite each other and it becomes a mess.

### Impact

A user can open multiple instances of AppFlowy and modify the entries without any fear of corruption on write.

### Additional Context

Like the Joplin Server

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy-Cloud
