### ISSUE TITLE
[Bug] Pasting a link in a URL grid crashes the app

### ISSUE THREAD

**Issue by Brikkinus** [AppFlowy-IO/AppFlowy#2965]
### Bug Description

If a link is pasted in a URL type cell, the program crashes.

https://github.com/AppFlowy-IO/AppFlowy/assets/67888185/4cde71cb-d17c-42da-b1ef-6ac2283f3205

### How to Reproduce

1. Create grid page
2. Add a cell column
3. Select type as URL
4. Paste URL

### Expected Behavior

The app should not close.

### Operating System

Windows 11 version 22H2

### AppFlowy Version(s)

0.25

**Comment by annieappflowy** [comment]
I cannot reproduce on my Windows 11 pro

**Comment by Brikkinus** [comment]
From what I have experienced, the program only crashes when a link is pasted using ctrl+v. Using the right click context menu doesn't crash.

**Comment by annieappflowy** [comment]
It works for me with ctrl+v
No worries. We'll find another Windows to test it out.

**Comment by Schrolli91** [comment]
I can confirm that - if i copy a url via STRG+V the app crashes

Version 0.26 on Windows 10 Enterprise

**Comment by Xazin** [comment]
I wasn't able to reproduce on **Windows 10 Home (Build: 19041.2728)**
