### ISSUE TITLE
[Bug] GitHub Logo in Question Bubble is Transparent.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2967]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/8ab9480d-a16f-447e-8781-aaebdd3283eb)

### How to Reproduce

?? cc @annieappflowy 

### Expected Behavior

GitHub logo is visible

### Operating System

macOS

### AppFlowy Version(s)

main

**Comment by annieappflowy** [comment]
How to reproduce: Click on "?" at the bottom right
I'm using the light theme v0.2.5 on Windows 11 pro
<img width="584" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/16c7bb5c-bd74-4549-bfe5-1dc0d8f68456">

**Comment by annieappflowy** [comment]
Switch to the dark mode
Then the logo is visible
<img width="142" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/543c5275-8505-4f73-a1a3-290b910f8269">
