### ISSUE TITLE
[FR] Add specific ports to docker-compose.yml

### ISSUE THREAD

**Issue by Tienisto** [AppFlowy-IO/AppFlowy#2968]
### Description

I host multiple services on the same server so it would be nice to customize the port of AppFlowy.

Currently, the `docker-compose.yml` is configured to use `network_mode: host` which is not a good pattern as it may collide with other services.

### Impact

Users who host multiple services isolated in docker containers on a single server.

**Comment by annieappflowy** [comment]
Please try out https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy
