### ISSUE TITLE
[Bug] Unable to select language in search field on the first attempt.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2975]
### Bug Description

Please refer to the video below

### How to Reproduce

- Go to the settings page.
- Click on the font family button and search for any font.
- Select one of the fonts from the search field.

### Expected Behavior

the users can select the font.

### Operating System

macOS

### AppFlowy Version(s)

0.2.6

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/9273b3e9-9efc-4a23-a8d8-d6467b13b804

**Comment by LucasXu0** [comment]
related issue: https://github.com/AppFlowy-IO/AppFlowy/issues/2980

**Comment by a-wallen** [comment]
I'm almost certain that this is because the text field has focus.
