### ISSUE TITLE
[FR] Ctrl+K shortcut for search

### ISSUE THREAD

**Issue by lays147** [AppFlowy-IO/AppFlowy#298]
**1~3 main use cases of the proposed feature**
Add CTRL+K shortcut to search pages.

**what types of users can benefit from using your proposed feature**
All users. 

**Additional context**
Notion has this shortcut that helps to search pages.

**Comment by gaganyadav80** [comment]
I can have a look at this. I think I will be able to do it. @annieappflowy Can you assign me this issue?

**Comment by MikeWallaceDev** [comment]
Do we even have search functionality?

**Comment by ishtiaqshaheer** [comment]
Hi, is there any update on the global search functionality?

**Comment by akaihola** [comment]
On most applications Ctrl-K is used to create a link. Of those I use daily, this is true at least for Teams, Asana, Miro, Github and Jira.

To avoid confusion, wouldn't it make sense to follow established convention instead of assigning a different action to the same key combination?

**Comment by annieappflowy** [comment]
Hi @akaihola , thanks for sharing your feedback with us. Please review the actual issue for the search function: #2232 
As described in the issue, the shortcut would be ctrl+p

**Comment by shanny2022** [comment]
I WOULD LIKE TO CLAIM

**Comment by Xazin** [comment]
Closed as duplicate
