### ISSUE TITLE
[Bug] require double-click to select a font from the font list

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2980]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/3b27ff4d-544d-4b38-989a-3d82493f26d7

### How to Reproduce

Go to Settings
Click on the current font to trigger the font list
Search Roboto
Click the Roboto option (no effect)
Click again (in effect)

### Expected Behavior

Require only one click to select a font

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.6

**Comment by LucasXu0** [comment]
close the issue as a duplicate. https://github.com/AppFlowy-IO/AppFlowy/issues/2975
