### ISSUE TITLE
[FR] We can link to other other board/grid/calendar, but not a page.

### ISSUE THREAD

**Issue by ayan-iiitd** [AppFlowy-IO/AppFlowy#2984]
### Description

In the `/` popup, we can refer or link to other boards, grids and calendars. Kindly extend the functionality to regular pages as well.

### Impact

Linking existing pages together can be very useful when creating a nested system.

Didn't know if this would be a feature or a bug so putting here - the docker install instructions feel incomplete. After we run `docker-compose up` do we get a webui of appflowy running on a port or does it like just builds appflowy for our x86/arm systems?

**Comment by annieappflowy** [comment]
Thanks for your feedback. You can type `@` to mention/link a page.
We are working on other triggers #2196 

We have not officially supported Docker and don't have a Docker expert on the team :(
So not sure how to fix

**Comment by Xazin** [comment]
Closing this for now, as the main issue already has a working solution, and the other issue is not currently relevant.
