### ISSUE TITLE
[Bug] App crashes after adding a select entry in grid view

### ISSUE THREAD

**Issue by Schrolli91** [AppFlowy-IO/AppFlowy#2985]
### Bug Description

App crashes after saving a new select entry in the grid view.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/1030ccb7-3434-44ae-8a3f-20f86c326136)

After i hit Enter the app terminates directly. But changes where saved.

This will only happen if i add a new select entry. Editing any of the current entries will not kill the app.

### How to Reproduce

Add a new option in an select-column in a grid view. 
See screenshots for detailed instructions.

### Expected Behavior

App will not terminate.

### Operating System

Windows 10 Enterprise (21H2) (Build: 19044.3086)

### AppFlowy Version(s)

0.2.6_windows-x86_64

### Screenshots

1.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/7a65c233-44ee-43b2-a3d9-eecee07818bd)
2.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/4934d152-f139-4f10-8ddc-4c0dd41e3ce5)
3.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/daf9bbc9-f9da-4d2f-b027-6a4be8820ded)

**Comment by Xazin** [comment]
I wasn't able to reproduce on **Windows 10 Home (Build: 19041.2728)**

**Comment by Schrolli91** [comment]
Is there any way to activate/see logging from AppFlowy?
Then i can provide some logs to find out whats going wrong here.

**Comment by annieappflowy** [comment]
Thanks @Schrolli91 . We found a way to reproduce the issue.
