### ISSUE TITLE
Toolbar closes when selecting hyperlink.

### ISSUE THREAD

**Issue by asadamatic** [AppFlowy-IO/AppFlowy#2990]
### Bug Description

In version `1.2.0` the toolbar is showing unexpected behavior and closes immediately when the `hyperlink` button is tapped.

### How to Reproduce

Tap on the `hyperlink` button in the toolbar.

### Expected Behavior

It should show a field to add the link, as it did in the previous version.

### Operating System

IOS

### AppFlowy Version(s)

1.2.0

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/37589169/ed36e338-c21d-42dd-908e-85fd16696828

**Comment by Xazin** [comment]
Duplicate of https://github.com/AppFlowy-IO/appflowy-editor/issues/278

**Comment by LucasXu0** [comment]
close as duplicated. We will keep update in this issue. cc @hyj1204
