### ISSUE TITLE
[FR] File upload and download 

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#2991]
### Description

AppFlowy supports file upload and download. You can insert images into the editor and attach files to the database (work in progress). Currently, the files are saved on the local disk. We are planning to support file uploading to remote storage. The remote storage could be Supabase, Firebase, or others. The process can be decoupled into these steps:

1. Incorporating file upload and download UI into the Editor and Database.
2. Developing an upload and download storage service. It should support resumable uploads as well as standard uploads, have file size limitations, and personal file storage limitations.

### Impact

File upload and download

**Comment by manuareraa** [comment]
Any updates on this feature to upload files to local storage other than just images?
