### ISSUE TITLE
[Bug] Can't paste multiline text inside code block

### ISSUE THREAD

**Issue by xfactor2000** [AppFlowy-IO/AppFlowy#2992]
### Bug Description

It's impossible to paste multiline text inside code block. The pasted text appears either before or after the code block, but not inside

### How to Reproduce

1. Copy some text (multiline)
2. Create code block in AppFlowy document
3. Try to paste the text inside the block
4. You will see the text is not placed inside the block, but rather adjacent to it.

### Expected Behavior

The text is pasted inside the block.

### Operating System

EndeavourOS (arch linux)

### AppFlowy Version(s)

0.2.6

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/4991585/757395cf-c99d-4cef-af6b-746b385ed7ce)

**Comment by MayurSMahajan** [comment]
Hey Lucas! Actually, I am already working on it. It fits in my Octernship project.

**Comment by LucasXu0** [comment]
> Hey Lucas! Actually, I am already working on it. It fits in my Octernship project.

Got it.
