### ISSUE TITLE
[Bug] translations are not applied

### ISSUE THREAD

**Issue by dakaii** [AppFlowy-IO/AppFlowy#3001]
### Bug Description

I'm running the Tauri application on VSCode with the AF-tauri: Debug backend option, and the translation files don't seem to be properly applied.

### How to Reproduce

Run the Tauri application in the AF-tauri: Debug backend mode.

### Expected Behavior

The translation files under `resources/translations` should be properly loaded and applied.

### Operating System

MacOS (Intel)

### AppFlowy Version(s)

0.2.6

### Screenshots

<img width="1418" alt="Screenshot 2023-07-14 at 5 29 00 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/8836096/01fa3e10-eda0-45af-94ca-76563c693164">

**Comment by LucasXu0** [comment]
@qinluhe Are there any pre-tasks?

**Comment by qinluhe** [comment]
Please `cd appflowy_tauri` and restart the client with `pnpm tauri:dev` command

**Comment by dakaii** [comment]
@qinluhe Oh Great! thank you. I'll just close this ticket then.
