### ISSUE TITLE
[Bug] Windows 11 Input Bug

### ISSUE THREAD

**Issue by Cloud33** [AppFlowy-IO/AppFlowy#3005]
### Bug Description

In the Windows 11 environment, using the five-stroke input method, English characters will appear after entering Chinese

Video:

https://github.com/AppFlowy-IO/AppFlowy/assets/8787198/7ac57136-7cee-4eb8-a7c1-3f33909cfaa7

### How to Reproduce

Enter the Chinese

### Expected Behavior

Displays the entered characters correctly

### Operating System

Windows11

### AppFlowy Version(s)

0.25

### Additional Context

Microsoft Five Strokes Input Method.

**Comment by teaper** [comment]
The same is true for Archlinux using fcitx5 input.

**Comment by malik1988** [comment]
Same happens on Windows 10

**Comment by annieappflowy** [comment]
duplicate of #2020
