### ISSUE TITLE
[FR] Use conventional commits to make a better git history

### ISSUE THREAD

**Issue by lays147** [AppFlowy-IO/AppFlowy#301]
**1~3 main use cases of the proposed feature**
This is just a suggestion that I think that it will make everyone's life easier.
You can add a GitHub action to make sure that all PR's are following the convention using commitlint.

https://github.com/wagoid/commitlint-github-action

**Comment by appflowy** [comment]
Hi, @lays147 I have read the commitlint, I think that will be really helpful. Thank you

**Comment by appflowy** [comment]
FYI: https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request

**Comment by MikeWallaceDev** [comment]
Thank you @lays147 for that suggestion!

I'm adding this as a reminder for the docs
* What's with that "there is no need to configure" sentence? Is it needed?
* Add installation instructions for Windows and Linux
*
