### ISSUE TITLE
[FR] Add a tooltip to the theme mode button suggesting the shortcut for toggling theme

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3012]
### Description

We can toggle the theme mode of AppFlowy using the shortcut `Ctrl+Shift+L` or `Cmd+Shift+L` (on mac). 
It would be nice if in the Settings, we informed the user about this shortcut through a tooltip.
This is where we can have the tooltip:

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/a30cd6a5-29a7-4084-9333-efc518eb9f1c)

We want something like this:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/b8301b4f-f995-497c-820e-834f6399c8a0)

### Impact

Users who are not aware of the shortcut for toggling the theme mode will get to know about it.

### Additional Context

- Check out how the tooltip for Close Side Menu is implemented and solve the issue.
- The shortcut suggested in the tooltip must check which OS the app is running on, since in the attached screenshot the app is running on Windows and the shortcut is suggesting to use `Ctrl` but on a Mac, it suggests using `Cmd` instead.

**Comment by Codesbyusman** [comment]
Hi,
I would like to work on it. Can I get some starting point for this?

**Comment by MayurSMahajan** [comment]
Great @Codesbyusman! 
Here is something to help you get started quickly:
1. Find out where the Close Side bar option is implemented within the codebase.
2. There you can understand, how the tooltip is being shown.
3. Then you can apply the same type of implementation on the Theme Mode button. (for that you'll have to find the Theme Mode btn)

That's it.

**Comment by AdiAr11** [comment]
Hi @Codesbyusman , if you decide not to work on this issue, please let me know and i would be happy to work on this.

**Comment by Xazin** [comment]
I would believe it to be best to wait before starting on this, for when this https://github.com/AppFlowy-IO/AppFlowy/pull/2848 has been merged.

Then the tooltip displayed can be with the dynamic hotkey instead of the static one. If they ended up changing it and then seeing the tooltip saying `CTRL/CMD + SHIFT + L` it could be confusing.

**Comment by Codesbyusman** [comment]
@Xazin I didn't look your comment earlier
@AdiAr11 we can do collectively but can wait till merge has been done as @Xazin said

**Comment by AdiAr11** [comment]
@Codesbyusman Yes sure, i would be happy to work together !
