### ISSUE TITLE
[Bug] Unable to delete a filter in grid view if the name of the filter is too long

### ISSUE THREAD

**Issue by xCloudK** [AppFlowy-IO/AppFlowy#3019]
### Bug Description

Unable to delete a filter for checkboxes in the Grid database once made, if the name is too long

### How to Reproduce

0. Make a Grid View page
1. Create a new column of type checkbox with a long name, im using "Very Long Name"
2. Click Filter button and filter by the checkbox column with long name
3. The delete hamburger cannot be clicked

### Expected Behavior

Should be able to delete the filter using the hamburger menu

### Operating System

Linux Debian 11

### AppFlowy Version(s)

0.12

### Screenshots

![AppFlowy Grid Cant Delete Filter report bug](https://github.com/AppFlowy-IO/AppFlowy/assets/107759463/da6f45c6-bd3c-4a9d-8954-346c0d4d4786)

**Comment by annieappflowy** [comment]
I cannot reproduce on Windows 11

**Comment by richardshiue** [comment]
Aside from checkbox, this also affects single-select option, multi-select option and checklist filters.
