### ISSUE TITLE
[Bug] Cutting text does not work

### ISSUE THREAD

**Issue by Harmon758** [AppFlowy-IO/AppFlowy#3023]
### Bug Description

Attempting to cut (CTRL + X) text doesn't seem to do anything.

### How to Reproduce

- Highlight some text
- Right click the highlighted text
- Press "Cut"
- Observe nothing happens

OR

- Highlight some text
- Press CTRL + X
- Observe nothing happens

### Expected Behavior

Cutting text, either through the right click context menu or CTRL + X shortcut, should delete the text and put it in the clipboard.

### Operating System

Microsoft Windows [Version 10.0.19045.3086]

### AppFlowy Version(s)

0.2.7

**Comment by Harmon758** [comment]
I believe this is due to https://github.com/AppFlowy-IO/appflowy-editor/commit/5f136df356b9e776ed9c607d65f20478e9d34432#diff-ab095d92cb562e31ec1168184ff40ebea568dc4c47def8e3107c3ad9a0f5a009L336-L341 being removed in https://github.com/AppFlowy-IO/appflowy-editor/pull/304.

It might make sense to transfer this issue to https://github.com/AppFlowy-IO/appflowy-editor.

**Comment by annieappflowy** [comment]
#2767

**Comment by Harmon758** [comment]
Similarly to #3030 and https://github.com/AppFlowy-IO/appflowy-editor/issues/328, I think this previously worked (https://github.com/AppFlowy-IO/AppFlowy/pull/764) and is a regression rather than a new feature request.

**Comment by Harmon758** [comment]
This was fixed in v0.2.9 (I believe with https://github.com/AppFlowy-IO/appflowy-editor/commit/73d56b44e2daf17123cd50ec8a9ceaa071ec6804 in AppFlowy Editor v1.2.3).
