### ISSUE TITLE
[FR] Paste plaintext without formatting

### ISSUE THREAD

**Issue by Harmon758** [AppFlowy-IO/AppFlowy#3024]
### Description

Add the standard Ctrl + Shift + V shortcut to paste plaintext without formatting.

### Impact

Users who want to easily paste plaintext without formatting.

**Comment by MayurSMahajan** [comment]
This shortcut will be supported from the next release.

**Comment by Harmon758** [comment]
Support for this was released in v0.2.9 (where AppFlowy Editor was updated to v1.2.3, with https://github.com/AppFlowy-IO/appflowy-editor/commit/2b517b2a5bc45a171b19678fe1a042dc9aaacdb1 / https://github.com/AppFlowy-IO/appflowy-editor/pull/338), not v0.2.8.
