### ISSUE TITLE
[FR] Hiding columns in a grid view

### ISSUE THREAD

**Issue by mskorkowski** [AppFlowy-IO/AppFlowy#3028]
### Description

When writing note you can reference a grid. I have a grid where every row has lots of properties (10 columns). I have a document where I would like to reference the same grid but in different context. Whenever I reference a grid in the document new view is created. I would like to be able to select which columns are visible separately for every view. This would make a document view clean and show only relevant data. 

Now there are two choices
1. Every time you reference grid you show all the columns and make a document hard to read for columns which are on the far right position
2. Duplicate a grid and make columns visible, but this leads to an issue where I must update same data multiple times and must not forget any of the copies.

### Impact

Everybody who needs to create a document about slightly more complex data

### Additional Context

I must create a document about the history of an it project and how much we've estimated the project would cost vs it's real costs. I've created a grid where the first column is the project name and other columns represent different costs and cost estimations. Keeping multiple grids in sync when you discover new things as you go with writing a comparison is an error prone adventure.

**Comment by LucasXu0** [comment]
Hey, @mskorkowski. Do you mean that you want to synchronize the filter and sort between different referenced views?

**Comment by mskorkowski** [comment]
> Hey, @mskorkowski. Do you mean that you want to synchronize the filter and sort between different referenced views?
Definitely not. Filter selects rows, order defines in which order they are visible and I'm taking about the structure of the view row (which columns aka properties are visible). For me visibility of columns should behave like filters and sort  when they are applied on the view bases.

To make myself clear I'm going to present trivial example. In the document example I'm going to use horizontal separator to show where are the document blocks present.

Grid 'DATA' contains

| Name | Height | Age |
|:-----------|-----------:|------:|
| John      | 175 | 30 |
| Bob | 180 | 35 |
| Kate | 170 | 40 |

Since every reference to the grid from the document creates new view of the data, I have two views. First one 'HEIGHT' and second 'AGE'.

Let's assume I have a document like this

> We've talked with 3 people. 
> ----
> HEIGHT
> | Name | Height | Age |
> |:-----------|-----------:|------:|
> | John      | 175 | 30 |
> | Bob | 180 | 35 |
> | Kate | 170 | 40 |
> ----
> The average **height** is 175
> ----
> AGE
> | Name | Height | Age |
> |:-----------|-----------:|------:|
> | John      | 175 | 30 |
> | Bob | 180 | 35 |
> | Kate | 170 | 40 |
> ---
> The average **age** is 35

Now if I hide an 'Age' column in the 'HEIGHT' view it becomes hidden in the 'DATA' and 'AGE' views. So my document becomes

> We've talked with 3 people. 
> ----
> HEIGHT
> | Name | Height |
> |:-----------|-----------:|
> | John      | 175 |
> | Bob | 180 |
> | Kate | 170 |
> ----
> The average **height** is 175
> ----
> AGE
> | Name | Height |
> |:-----------|-----------:|
> | John      | 175 |
> | Bob | 180 |
> | Kate | 170 |
> ---
> The average **age** is 35

And I would expect it to be

> We've talked with 3 people. 
> ----
> HEIGHT
> | Name | Height |
> |:-----------|-----------:|
> | John      | 175 |
> | Bob | 180 |
> | Kate | 170 |
> ----
> The average **height** is 175
> ----
> AGE
> | Name | Height | Age |
> |:-----------|-----------:|------:|
> | John      | 175 | 30 |
> | Bob | 180 | 35 |
> | Kate | 170 | 40 |
> ---
> The average **age** is 35

**Comment by annieappflowy** [comment]
Hi @mskorkowski , very much appreciate your detailed explanation. I fully understand your needs. Hiding properties in view not across views of the same database should definitely be supported. I've assigned @appflowy to work on it.

**Comment by annieappflowy** [comment]
<img width="414" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c4517b73-9b2d-4c1b-bff1-060aa1f2ffaf">
<img width="341" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/6433d1d8-4bf3-4b72-9a0f-5698f7b2e595">
<img width="434" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7f45990f-5887-4863-a5c4-72ebc9e21bb3">

Hi @mskorkowski , the request you submitted is completed. Please give it a try with the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases).

**Comment by mskorkowski** [comment]
Impressive. It helps a lot

🚀
