### ISSUE TITLE
[FR] When to support Full-text search of notes

### ISSUE THREAD

**Issue by sr0133** [AppFlowy-IO/AppFlowy#3039]
### Description

It is necessary to use the search function during use

### Impact

More convenient to use

**Comment by Xazin** [comment]
Hey @sr0133, we already have this request, and we are working on making this happen.

We expect to have document search available in v0.2.9, for full-workspace search and searching in databases, it will come in a later version.

Relates to #2315 #2232 #830 #298

**Comment by Xazin** [comment]
Closed as duplicate
