### ISSUE TITLE
[Bug] "Try AppFlowy Free" Button on home page not redirecting to target URL

### ISSUE THREAD

**Issue by parth-ranalkar** [AppFlowy-IO/AppFlowy#3044]
### Bug Description

Every Try AppFlowy Free Button Present on home page is redirecting to AppFlowy github release documentation.

See Video:

https://github.com/AppFlowy-IO/AppFlowy/assets/73604763/17880739-82c1-4bca-a33b-21482724059a

### How to Reproduce

1. Go to AppFlowy Home Page 
2. Scroll Down to 2nd section "Get Things Done"
3. In that section click on "Try AppFlowy Free" button

### Expected Behavior

It Should be redirect to AppFlowy try section UI.

### Operating System

Windows 

### AppFlowy Version(s)

0.2.6

**Comment by Harmon758** [comment]
What's the "try section UI" you're referring to?

**Comment by annieappflowy** [comment]
It works as intended because it would direct users to download the application. However, I understand that why it made you confused. This is something we'll improve with the new official website.
