### ISSUE TITLE
[FR] drag and drop blocks in a document

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3049]
### Description

 I don't  seem to be able to MOVE blocks. For example, move a divider line above or below adjacent blocks. 

### Impact

Document users

**Comment by annieappflowy** [comment]
I meant the way you can move "blocks" in Notion to any where, and then resize the blocks as you see fit. So for example, You can have an image, a text block, and a series of links all in one "row" (by row I mean they're allowed to be next to each other, as opposed to being below each other like how it is now)  and have the image block take more space then the text with the links taking the least for example. Hope this clarifies what I meant 😅 

Is this something planned? Just curious :)

**Comment by moodi1999** [comment]
Hi, any plan on this? it's one of the mostly used features in these kinds of applications.

**Comment by A-Z-X-R** [comment]
Hey... Any updates? I find it really necessary. Or at the very least, give us the option to add a line above a line. Although the option of dragging-and-dropping lines would be much more useful.

**Comment by Xazin** [comment]
> Hey... Any updates? I find it really necessary. Or at the very least, give us the option to add a line above a line. Although the option of dragging-and-dropping lines would be much more useful.

<img width="193" alt="Screenshot 2024-02-09 at 12 06 27" src="https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/258b19fe-5c78-4498-a696-cf0e02733b5e">

You can add a block above, by holding Option and clicking on the `+` to the left of a block. I can't remember if the windows alternative is Alt, but I believe so.

**Comment by A-Z-X-R** [comment]
> > Hey... Any updates? I find it really necessary. Or at the very least, give us the option to add a line above a line. Although the option of dragging-and-dropping lines would be much more useful.
> 
> <img alt="Screenshot 2024-02-09 at 12 06 27" width="193" src="https://private-user-images.githubusercontent.com/42929161/303631586-258b19fe-5c78-4498-a696-cf0e02733b5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTE0MDYsIm5iZiI6MTcwNzcxMTEwNiwicGF0aCI6Ii80MjkyOTE2MS8zMDM2MzE1ODYtMjU4YjE5ZmUtNWM3OC00NDk4LWE2OTYtY2YwZTAyNzMzYjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA0MTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzIwZDViZWMyM2U2N2Q0NTBlZDliOTlhOWU0OGMzZWMzOTIyZWE3MzlmMWY4NWM0NWY1ODEyYzYwMDU4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iQgPFhSLRlKdQcOCkOp6wijcfikseErrlZDg7BPKCZE">
> You can add a block above, by holding Option and clicking on the `+` to the left of a block. I can't remember if the windows alternative is Alt, but I believe so.

Okay thank you! I guess copy-pasting is the alternative solution for now

**Comment by JohnGlod** [comment]
Tell me, has this feature already been implemented?

**Comment by yanayz** [comment]
over a year later, and still nothing? 
that's not very reassuring for new (potential) users...

**Comment by Xazin** [comment]
Closing as it's been completed 🎉
