### ISSUE TITLE
[Bug] 文档输入文字时出现重复

### ISSUE THREAD

**Issue by lanpeng1612** [AppFlowy-IO/AppFlowy#3059]
### Bug Description

系统：win10
System: win10

输入法：微软输入法和搜狗五笔输入法
Input Method: Microsoft Input Method and Sogou Wubi Input Method

输入语言：中文
Input language: Chinese

输入中文时出现重复，输入英文时正常
Repetitive input in Chinese, normal input in English

这是我想输入的 ” 2023年7月25日 测试 问题 重复输入“
This is what I want to input  ” 2023年7月25日 测试 问题 重复输入“

它出现的  ”输入 shu'ru shu'r shu sh s su  2023年7月25日 测试 问题 重复ssusshshushu'rshu'ru输入“
It appears  ”输入 shu'ru shu'r shu sh s su  2023年7月25日 测试 问题 重复ssusshshushu'rshu'ru输入“

### How to Reproduce

输入中文
Enter Chinese

### Expected Behavior

希望能完全适配中文
I hope it can fully adapt to Chinese

### Operating System

win10

### AppFlowy Version(s)

0.2.7

### Screenshots

![屏幕截图 2023-07-25 103313](https://github.com/AppFlowy-IO/AppFlowy/assets/88768735/b2074895-e6fd-465f-a5be-b3de8c6a4946)

**Comment by annieappflowy** [comment]
duplicate of #1756
