### ISSUE TITLE
[Bug] Links don't open in a browser

### ISSUE THREAD

**Issue by maticmeznar** [AppFlowy-IO/AppFlowy#3060]
### Bug Description

I'm a first time user of AppFlowy and I've noticed that none of the external links open in a browser. Same for clicking help and support links from the icon in the bottom right corner. Both AppFlowy and Firefox are running as a Flatpak. I have no problems with links in Obsidian, which also runs as a Flatpak.

When I run AppFlowy from the terminal I get `Jul 25 09:44:40.201 ERROR ThreadId(14) dart_ffi:{"message":"Uncaught platform error"}
{"msg":"Uncaught platform error"}` error each time I click on a link from the help and support icon, but no error when I click "Open link" on a link in a document.

I've also tried it on another computer with Ubuntu 22.04 and Firefox in a snap with the same result.

### How to Reproduce

Click on a link in the help and support menu.

### Expected Behavior

I expect the link to open in my default browser, in a new tab.

### Operating System

Fedora Workstation 38 (x86_64), Ubuntu 22.04 (x86_64)

### AppFlowy Version(s)

0.2.7 (Flatpak)

**Comment by annieappflowy** [comment]
@richardshiue , can you reproduce this issue?

**Comment by ttollet** [comment]
If it helps, I can reproduce this issue.

**Firefox:** system package, version "116.0+linuxmint1+victoria"
**AppFlowy:** flatpak, version 0.2.8
**Operating system:** Linux Mint 21.2 Cinnamon.

**Comment by richardshiue** [comment]
I've narrowed down the problem to this issue. I'll be able to test and fix this after I clear some space on my laptop to build the flatpak

**Comment by rob32** [comment]
I have the same issue here.

Flatpak (v0.4.5).
OS: Fedora 39

**Comment by apollo13** [comment]
I am also running into this. Every click on the link throws:
```
  2024-02-19 13:19:18 ERROR  Uncaught platform error
    at dart-ffi/src/lib.rs:188

  2024-02-19T12:19:18.905514Z ERROR dart_ffi: Uncaught platform error
    at dart-ffi/src/lib.rs:188
```

Flatpak (v0.4.9) on Fedora 39.

**Comment by apollo13** [comment]
A bit of googling suggests that dropping the use of `canLaunch` might fix this (and where needed catch the `PlatformException`)

**Comment by Xazin** [comment]
This should be resolved, feel free to let us know if you are still experiencing issues with launching urls.

**Comment by Xazin** [comment]
> I'd love to verify this, but apparently there are no build for 0.5.1?

New version are released bi-weekly, today is release day and 0.5.1 was just released 1-2 hours ago, cheers

https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.1

**Comment by apollo13** [comment]
Thank you, did a flatpak build against the new release (https://github.com/flathub/io.appflowy.AppFlowy/pull/87) and it works. Would be great if someone from the team could merge the flatpak PR.

**Comment by LucasXu0** [comment]
> Thank you, did a flatpak build against the new release ([flathub/io.appflowy.AppFlowy#87](https://github.com/flathub/io.appflowy.AppFlowy/pull/87)) and it works. Would be great if someone from the team could merge the flatpak PR.

The Flathub bot will automatically sync the version daily and update the release date as well.
