### ISSUE TITLE
[Bug]  Callout Text Theme Issues

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#3063]
### Bug Description

We offer users the ability to choose a color for the callout in our application. However, this customization option often leads to issues such as unreadable text and poor visibility. 

### How to Reproduce

Simply add a callout item, and try to change to different colors and you will find wierd contrast theming issues.

### Expected Behavior

To rectify this problem, we propose implementing a solution where a specific text color is automatically assigned based on the chosen background color. 

### Operating System

Ubuntu

### AppFlowy Version(s)

Latest

### Screenshots

![callout](https://github.com/AppFlowy-IO/AppFlowy/assets/37607224/61b7b174-b21e-4b82-ba14-69fcf8f241a0)

**Comment by hyj1204** [comment]
Perhaps it's a good idea to update the background color choices for the callout to address the visiable issue with the current dark mode. 

<img width="321" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/588a25d0-3da6-431d-9800-69bf82fea01f">

The default text color in the data format is actually `null` for the font color attribute. It is rendered based on the current theme. Therefore, I suggest not changing the text color and instead adjusting the background colors for the callout to better suit the dark mode.

**Comment by AmanNegi** [comment]
@hyj1204 Yeah, I guess we should go ahead with that.

**Comment by AmanNegi** [comment]
@hyj1204 It seems very viable to tone down the colors(opacity) for dark mode. Here's a PR I created with a Demo for same:

https://github.com/AppFlowy-IO/AppFlowy/pull/3079
