### ISSUE TITLE
输入中文会乱码[Bug] 

### ISSUE THREAD

**Issue by Lyeragain** [AppFlowy-IO/AppFlowy#3070]
### Bug Description

输入中文时要先打出英文字母组成拼音再选取中文，例如第一张图：
<img width="585" alt="屏幕截图 2023-07-27 211246" src="https://github.com/AppFlowy-IO/AppFlowy/assets/130667961/eecdadc1-871c-4b8a-a074-da609f0bd208">

可是有时候输入英文字母组成拼音时会乱码，如第二张图：
![1690463992253](https://github.com/AppFlowy-IO/AppFlowy/assets/130667961/92247fd7-20ca-4666-88c9-397469390a95)
红色方框是我需要打出来的，蓝色方框则是乱码

以下是AppFlowy的场景复现：
![AppFlowy](https://github.com/AppFlowy-IO/AppFlowy/assets/130667961/93f20e67-b9f6-4a7b-91ac-12292c321b4c)

正确的应该是：
![txt](https://github.com/AppFlowy-IO/AppFlowy/assets/130667961/8a5cf6be-d7b7-4dcc-967f-1b05e6944cfb)

### How to Reproduce

在AppFlowy编辑页面输入中文就会出现这个bug

### Expected Behavior

期待可以修复中文方面的缺陷

### Operating System

Windows11

### AppFlowy Version(s)

AppFlowy_0.2.7_windows-x86_64

### Additional Context

试用的很多笔记软件，想All-in-AppFlowy，希望开发者可以修复这个缺陷

**Comment by annieappflowy** [comment]
duplicate of #2260
