### ISSUE TITLE
[Bug] Context Menu is not working

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3077]
### Bug Description

None of the options in the context menu works.

### How to Reproduce

1. Open a document
2. Enter some text and select it
3. Right Click, context menu appears
4. Click Cut or Copy (Clicking cut should have deleted the text under selection)
5. Go to an empty line and Right Click, context menu appears
6. Now click Paste
7. Nothing happens

### Expected Behavior

1. Open a document
2. Enter some text and select it
3. Right Click, context menu appears
4. Click Cut or Copy (Cut should delete the selected text)
5. Go to an empty line and Right Click, the context menu appears
6. Now click Paste
7. pastes the selected text in step 2.

### Operating System

Windows 11

### AppFlowy Version(s)

0.2.7

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/e736b047-4b9a-418e-8a04-8cd228b42228)

### Additional Context

In AppFlowy version 0.2.7 copy and pasting multiple lines is not supported, so the shortcut for the same might not work.
In AppFlowy version 0.2.7 cut shortcut is not implemented.

**Comment by Mukund-Tandon** [comment]
I would like to work on this issue

Current Progress -

https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/af8808b8-3576-411d-80f2-25103f8345d9
