### ISSUE TITLE
[FR] Simple Table

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3080]
### Description

This is a part of AppFlowy Mentorship Program

- Insert table command which can get added as selection menu item
- Basic table which also can get duplicate or deleted
- Being able to add/delete/duplicate/update rows and columns of existing table
- Resize column/row feature
- Support rich-text editing in table cells (basic markdown features like bold, italic, checkbox, ...)
- Drag and Drop feature for rows and columns
- Enable text color and background color for rows and columns
- Support Markdown table creation |Col A|Col B| should convert to a table

### Impact

Users who need a simple rich-text table to organize and display structured information

**Comment by Chandan-CV** [comment]
Hi @annieappflowy! I really want to be a part of the mentorship program. The website says this work is already taken though. **I would love to take this up** if no one has taken up this issue and be **a part of the mentorship program**.

Looking forward to learning a lot from you :)

**Comment by annieappflowy** [comment]
This project has been taken by someone. You can take a look at the project [doc](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/appflowy-mentorship-program/mentorship-2022/mentee-projects/table) to learn more about the implementation plan.

Thanks for your interest in the mentorship program. You can follow [this guidance](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/appflowy-mentorship-program/contributor-guidance) to apply.
