### ISSUE TITLE
What's the default font used before v0.2.6?

### ISSUE THREAD

**Issue by realchandan** [AppFlowy-IO/AppFlowy#3085]
I have set a font from Google Fonts, but I don't like it, I want to switch back to the default font that was in place before v0.2.6 , Can you tell me the name of that font?

**Comment by richardshiue** [comment]
It's called Poppins. Should we be able to let user clear a custom font selection @a-wallen?

**Comment by a-wallen** [comment]
Resetting back to Poppins is reasonably trivial. I did not know that the bold variant was used. I can try my best to revert back to the exact default with bold.

I'll add a button to clear the current selection for now.

**Comment by a-wallen** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/4e495104-c6ec-46dc-b4a8-9d05fc023ed7)

**Comment by a-wallen** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/44445638/fffa12ee-ab7f-4a55-a97a-bd6636fc9f4e)

**Comment by annieappflowy** [comment]
@a-wallen the icon doesn't look good in the dark mode as shown in your screenshot
