### ISSUE TITLE
[Bug] Drop down icons in the side bar are reversed

### ISSUE THREAD

**Issue by Harmon758** [AppFlowy-IO/AppFlowy#3088]
### Bug Description

The paradigm for drop down icons is for them to be pointing up (or sideways) when collapsed and down when expanded.
Currently, this is reversed in v0.2.7.

### How to Reproduce

- Create a new page
- Add a subpage to that page
- Collapse and expand the page and observe the icon to the left of the page name in the side bar

### Expected Behavior

The icon should be pointing up (or sideways) when collapsed and down or sideways when expanded.

### Operating System

Microsoft Windows [Version 10.0.19045.3086]

### AppFlowy Version(s)

0.2.7

### Screenshots

Expanded in v0.2.7:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/9403740/7b48428d-09ee-4480-b95e-9b6e6e2ef122)
Collapsed in v0.2.7:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/9403740/f2c96c36-dbd0-4ace-9a6b-9936f1b4c299)

### Additional Context

The new toggle lists (#3016) actually follow the paradigm, so this is inconsistent across AppFlowy itself:
- Expanded:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/9403740/9e47a7da-1c37-4be2-ac52-97a061af6006)
- Collapsed:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/9403740/92d31140-2472-4885-a20e-ee8a4b828da6)

I think this might already be resolved in the main branch, with #3083.

**Comment by LucasXu0** [comment]
@Harmon758 Thanks for reporting. It has been fixed in the main branch.

For the folder, ↑ means Collapsed and ↓ means Expanded.
