### ISSUE TITLE
[Bug] Favorites context menu doesn't work 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3113]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/38805008-3651-4108-a489-2eece63e7012

### How to Reproduce

Try to unpin a favorited page

### Expected Behavior

I'm able to remove a page from Favorites

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.8

**Comment by squidrye** [comment]
It seems this along with view selection not syncing is caused by changes in recent #3107, I have found the exact change that causes the issue, trying to figure out a workaround.

**Comment by annieappflowy** [comment]
Fixed
