### ISSUE TITLE
[FR] (don't) wrap column

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3119]
### Description

In the grid, most if not all fields wrap cell contents if they cannot fit in a single line. There should be a consistent behavior and setting to toggle this on and off, which will allow users to have consistent row height if they wish. In this screenshot, the title field wraps, the multi-select wraps, but date ellides and number has a hard clip.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/26cf128b-5e66-4b57-8021-fc1f107be5d3)

### Impact

Users who want to have consistent row height in their grids

**Comment by clevertension** [comment]
yes, the url cell should also support auto wrap

**Comment by richardshiue** [comment]
Closing as completed via https://github.com/AppFlowy-IO/AppFlowy/pull/5128
