### ISSUE TITLE
[Bug] Selection Menu has no background shadow or border in light modes

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3132]
### Bug Description

As title.

### How to Reproduce

1. Open AppFlowy
2. Make sure you are in Light Mode (of any theme)
3. Type / to activate to the selection menu
4. Observe that the selection menu has no background as shown in the screenshot.

### Expected Behavior

1. Open AppFlowy
2. Make sure you are in Light Mode (of any theme)
3. Type / to activate the selection menu
4. Selection menu has background color and shadow.

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.8

### Screenshots

Default Theme: 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/e0bc3c11-f2be-49a7-8f05-ee216789fa34)

### Additional Context

- Background color and shadow are missing in every theme's light mode.
- Expected background is present in the Dark Mode of every theme.

**Comment by fibbbonachos** [comment]
Looks like it's been fixed @MayurSMahajan 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/115238980/12fb175b-6639-4c23-9b5c-734310cf29ac)

**Comment by Xazin** [comment]
> Looks like it's been fixed @MayurSMahajan ![image](https://user-images.githubusercontent.com/115238980/259013366-12fb175b-6639-4c23-9b5c-734310cf29ac.png)

I just noticed there's a different vertical padding from horizontal, my OCD cried out to me.

(You can tell by looking at the selected item, then looking up and left, there's a wider margin horizontally to the edge of the dialog).

Anyhow, I can reproduce on `main` on MacOS.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/351d3a6c-3839-44b7-ad6d-d3413a8b4f92)

**Comment by fibbbonachos** [comment]
> > Looks like it's been fixed @MayurSMahajan ![image](https://user-images.githubusercontent.com/115238980/259013366-12fb175b-6639-4c23-9b5c-734310cf29ac.png)
> 
> I just noticed there's a different vertical padding from horizontal, my OCD cried out to me.
> 
> (You can tell by looking at the selected item, then looking up and left, there's a wider margin horizontally to the edge of the dialog).
> 
> Anyhow, I can reproduce on `main` on MacOS.
> 
> ![image](https://user-images.githubusercontent.com/42929161/259058567-351d3a6c-3839-44b7-ad6d-d3413a8b4f92.png)

Looks like when the window size is small enough, the shadow and the background disappears, on Windows 11.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/115238980/f9917a31-3718-4b31-8e1d-de452df25142)
But when the window is fully allowing all of the items to exist on screen, the shadow and the background reappears.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/115238980/f654aa4a-0730-4421-ab9f-9a0f64f011b1)

**Comment by MayurSMahajan** [comment]
I can confirm this, on minimized displays the shadow disappears but on the full screen we can see the shadow. 
I checked the code and the background color is just white in light modes.

**Comment by fibbbonachos** [comment]
Working on this

**Comment by fibbbonachos** [comment]
Currently working on something else, unassigned myself.
