### ISSUE TITLE
[FR] Right click on View Item to open context menu

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3135]
### Description

Currently on a navigation item, only when hovering the popover button to show the context menu shows, and you can only open it by clicking the button (`:`).

We should refactor this so that it becomes possible to right-click anywhere on the navigation item to open the context menu. 

The context menu opened with right-click should open relative to mouse.

### Impact

UX

**Comment by dotarjun** [comment]
working on this

**Comment by annieappflowy** [comment]
Are you still working on this, @dotarjun ?

**Comment by dotarjun** [comment]
Hey! I'm not working on this

**Comment by ax920** [comment]
Hi, I'd like to take this on

**Comment by Xazin** [comment]
In case this is going to be picked up at some point, here is some information on the preferred solution:
- Enabling Secondary Click as a Popover Trigger
- Implementing a boolean on whether the Offset should adhere to the pointers offset on trigger, or if it should adhere to child. Eg. `usePointerPosition` - It should default to false so it doesn't break existing Popovers.
- In the Listener used to track whether a click happens, we can make a check inside the `onPointerDown` callback, that checks whether the `event.buttons` is equal to [kSecondaryMouseButton](https://api.flutter.dev/flutter/gestures/kSecondaryMouseButton-constant.html), similarly for the left click see [kPrimaryMouseButton](https://api.flutter.dev/flutter/gestures/kPrimaryMouseButton-constant.html)
- Now for the `showOverlay`, it should take an optional `Offset?`that we can provide in case `usePointerPosition` is set to `true`.
- Also the math for deciding where to display the Popover based on the PopoverDirection, should be different for when using the Pointer Offset, otherwise the popover will show up in odd locations.
