### ISSUE TITLE
[FR] Add a way to notify translation contributors about new UI strings

### ISSUE THREAD

**Issue by dadyarri** [AppFlowy-IO/AppFlowy#315]
**1~3 main use cases of the proposed feature**
To keep translations up-to-date there should be a way to notify contributors that file with english UI strings has been updated.

**what types of users can benefit from using your proposed feature**
Translation contributors

**Proposed soluition**
Github action that triggers on push to `main`, filtered by path to english file
![image](https://user-images.githubusercontent.com/51821039/153065902-80406054-af96-4ee3-964a-fd39dca9e68d.png)

**Comment by dadyarri** [comment]
I think discord is a best way. There is a ready action for this (https://github.com/marketplace/actions/actions-for-discord), we can configure a role "translator" and mention it, when strings updated

@MikeWallaceDev, what do you think?

**Comment by dadyarri** [comment]
Added some actions in #316

**Comment by annieappflowy** [comment]
Discord and email together should work as a lot of people are not on Discord

**Comment by annieappflowy** [comment]
@dadyarri please let me know if you need me to create new channels for this

**Comment by dadyarri** [comment]
@annieappflowy 
> Discord and email together should work as a lot of people are not on Discord

I think it shouldn't because strings action should notify just translators (and there is no easy way to subscribe person to mailing, only editing action/secret) and release notifications is just automating of thing, you're doing manually

> please let me know if you need me to create new channels for this
Yes, something like `appflowy-translations` in News and role `Translator`

**Comment by annieappflowy** [comment]
> @annieappflowy
> 
> > Discord and email together should work as a lot of people are not on Discord
> 
> I think it shouldn't because strings action should notify just translators (and there is no easy way to subscribe person to mailing, only editing action/secret) and release notifications is just automating of thing, you're doing manually
> 
> > please let me know if you need me to create new channels for this
> 
> Yes, something like `appflowy-translations` in News and role `Translator`

Sure. I created a new channel called #translation-needed
Regarding the role 'Translator', I can create one but I might find it hard to maintain as I need to know every translator's Discord ID and assign the role accordingly.

**Comment by dadyarri** [comment]
> I can create one but I might find it hard to maintain as I need to know every translator's Discord ID and assign the role accordingly

Maybe then lock writing to this channel only to bot, who will write notifications and propose to translators subscribe to notifications in this channel?

**Comment by annieappflowy** [comment]
> > I can create one but I might find it hard to maintain as I need to know every translator's Discord ID and assign the role accordingly
> 
> Maybe then lock writing to this channel only to bot, who will write notifications and propose to translators (in docs) subscribe to notifications in this channel?

Sounds good to me! Is there anything else I can facilitate?

**Comment by MikeWallaceDev** [comment]
There is a way on Discord for people to subscribe and unsubscribe to roles by themselves. I've seen this on other servers. Usually it's something like a pinned message, and you get the role by clicking on a reaction icon (those little smileys at the bottom of a message)

I asked for a role like this for developpers so that we can send out critical messages (such as breaking changes in the environment.)

I'll try to find a blog post on this and send it to you @annieappflowy.

https://www.alphr.com/automatically-give-roles-discord/
