### ISSUE TITLE
[Bug] appflowy 0.2.9 for Windows not available

### ISSUE THREAD

**Issue by IMPranshu** [AppFlowy-IO/AppFlowy#3161]
### Bug Description

I checked in the official release page for a link to download Appflowy v0.2.9 but couldn't find an executable or zip file for windows.

### How to Reproduce

Go to the [link](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.2.9) and see there is no executable file nor a zip.

### Expected Behavior

There should be a .exe or .zip file for the latest appflowy version as well.

### Operating System

Windows 11

### AppFlowy Version(s)

0.2.9

### Screenshots

<img width="1184" alt="Screenshot 2023-08-10 at 9 16 36 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/43396684/7e0e73cc-8554-4ae2-96bc-cea66e3b3f6e">
.exe and .zip are present for v0.2.8

<img width="1184" alt="Screenshot 2023-08-10 at 9 16 42 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/43396684/e4070fe6-f468-41cd-9d89-c9938b22876c">

**Comment by Harmon758** [comment]
#3166 is about this.

**Comment by annieappflowy** [comment]
Available to download from https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.2.9
