### ISSUE TITLE
[Bug] can not import exist markdown files that created used the old version 

### ISSUE THREAD

**Issue by langlichong** [AppFlowy-IO/AppFlowy#3163]
### Bug Description

older markdown file is created by version 0.1.x  , then upgrade(directly install a new version ) to version 0.2.8 , after upgrade the old markdown file can not be open from the new one

### How to Reproduce

upgrade from 0.1.x  to 0.2.8

### Expected Behavior

can import old version's markdown files

### Operating System

win11

### AppFlowy Version(s)

0.2.8

**Comment by annieappflowy** [comment]
Hi @langlichong , please use v0.1.6 to export your files and import them with v0.2.0
You can refer to the video instructions in [this](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.2.0) page
