### ISSUE TITLE
[Bug] Windows release job failed

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3166]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5821884409/job/15785252340

### Operating System

Windows

### AppFlowy Version(s)

0.2.9

### Additional Context

https://github.com/AppFlowy-IO/AppFlowy/pull/3141

**Comment by LucasXu0** [comment]
This command doesn't work on either the CI machine or my local PC. 

`dart ./scripts/flutter_release_build/build_flowy.dart . ${{ github.ref_name }}`

**Comment by a-wallen** [comment]
On it.

**Comment by a-wallen** [comment]
`dart ./scripts/flutter_release_build/build_flowy.dart . 0.2.9` runs on my machine, but it looks like the command `cargo build --release --package=dart-ffi --target x86_64-pc-windows-msvc --features "dart,rev-sqlite"` hangs on CI. If it use `cargo build --release --package=dart-ffi --target x86_64-pc-windows-msvc --features "dart,rev-sqlite"` by itself, there's no issue. Also `cargo make --env APP_VERSION=0.2.9--profile production-windows-x86 appflowy --verbose` works on it's own.

**Comment by Harmon758** [comment]
This [seems to be resolved now](https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5948388417) (I believe by #3168).
