### ISSUE TITLE
[Bug] Views beyond the space cannot be access

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3171]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c9783140-6392-41dd-be61-34318657cce6

### How to Reproduce

Create a few views so they cannot fit in one line

### Expected Behavior

I can access all the views I created on the same database

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.9

**Comment by annieappflowy** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/67babca6-6d44-4edc-abb9-6c7e4ba329eb)

I don't see xxx more in v0.2.9

**Comment by richardshiue** [comment]
Will do. In the mean time please use shift-mouse-scroll or horizontal trackpad scroll to display the overflown views.
