### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BeeSee20Eye35** [AppFlowy-IO/AppFlowy#3173]
### Bug Description

No longer supporting OS X Mojave 10.14

### How to Reproduce

I am still avidly following progress and trying out each new version. I was just about to install v0.2.9 and use it for the first small real application (as an exercise and to remove it from Notion) but I ran into a problem.  

I have just tried to install v0.2.9 on my mac but it says it needs a newer version of OS X. 
v0.2.8 worked fine. 

Steps : 
1. download https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.2.9/AppFlowy_0.2.9_macos-x86_64.dmg
2. install 
3. Open
4. Get error message : "You can’t use this version of the application “AppFlowy.app” with this version of macOS. You have macOS 10.14. The application requires macOS 11.0 or later."

### Expected Behavior

I assumed that you would be supporting older versions of operating systems so that we do not have to bow to the update tyranny that is endemic everywhere and is such a time sink. 

Is this a deliberate policy not to support OS X 10.14 or an error? 

Thanks

### Operating System

OS X 10.14

### AppFlowy Version(s)

0.2.9

**Comment by annieappflowy** [comment]
Hi @BeeSee20Eye35 , thanks for following us and trying out AppFlowy. 
We're looking into it. 
Is there any specific reason not upgrading the OS version?

**Comment by BeeSee20Eye35** [comment]
Hi - thanks for getting back to me so quickly!
Re upgrading, I dislike all the changes and messing around each update causes. Apple in particular seem to force more and more integration with the cloud and other hard to control features. Plus, quite often, apps that I am using suddenly stop working. I have also found that some very significant applications such as vmware fusion require considerable reinstallation or resetup after upgrades. Overall, if it's not broken, why fix it. Especially as the only reason seems to be to allow Apple more chance to market to me. 

Thanks for looking into this for me.
