### ISSUE TITLE
[Bug] link cursor

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3175]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/358caf28-3383-49b6-af9c-f24d14b66f5f

### How to Reproduce

Format text as a link
Turn it into a H1
Highlight the text using ctrl + shift + ->
Use mouse to click at the end of the text, trying to un-highlight
The link menu keeps popping up 
I can un-highlight by pressing ->

### Expected Behavior

I can click with my mouse to un-highlight

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.9

**Comment by Xazin** [comment]
Relates https://github.com/AppFlowy-IO/appflowy-editor/issues/357
