### ISSUE TITLE
[FR] Filter in board view of databases

### ISSUE THREAD

**Issue by ErdemAkcali** [AppFlowy-IO/AppFlowy#3176]
### Description

Board view of a database should also be filterable by properties.
Example: Filter medications to show on a board view if the property "current" is checked.
This way only the current medications would show up in the board view.

### Impact

Users who want to use board view that require filtering of the content shown.

**Comment by annieappflowy** [comment]
<img width="978" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/292cfcbc-c266-400c-93af-d93e48a3c9da">

We supported filtering board in the latest release (v0.5.3)
