### ISSUE TITLE
[FR] Open as a page open in full page

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3179]
### Description

Enable us to open a row as full page so that a bigger space is provided to write
<img width="664" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/d2aab4f1-f690-4e30-96c2-266599aa45e8">

### Impact

Database users who write long text in a row

**Comment by Xazin** [comment]
Do we need a design for this? Or how do we want to handle it?

**Comment by AmeerArsala** [comment]
Please do this, I need it for scheduling and organization

**Comment by annieappflowy** [comment]
Supported. Please give it a try with the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases).
<img width="911" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c3e28a25-5558-461d-a8a1-c2c7866a8a49">

<img width="1147" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/d47caa1a-089d-4af4-86d5-61eeda18c0a3">
