### ISSUE TITLE
[Bug] link is not auto formatted

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3180]
### Bug Description

<img width="617" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ce779966-c682-4a9e-ac1a-f72ee7a383c3">

### How to Reproduce

Paste a link into a doc

### Expected Behavior

Auto-format it as a link for me

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.9

**Comment by Harmon758** [comment]
See also https://github.com/AppFlowy-IO/appflowy-editor/issues/328.
