### ISSUE TITLE
[FR] Turn multi-lines into a bulleted list

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3181]
### Description

<img width="562" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/739e3d30-fc9d-4c8d-987a-9e0f0d7754bd">

I'd like to highlight a few lines and turn them into a bulleted list.

### Impact

Editor users

**Comment by MayurSMahajan** [comment]
Would you like a shortcut for the same, or should we present an option in the toolbar?

**Comment by zoli** [comment]
I would like to take this.
