### ISSUE TITLE
[Bug] The background colors for the select / multi-select options in the dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3187]
### Bug Description

 1) kanban board: In the options of the select field, the selectable background colours are now darker (in the dark mode).  For me they could be a bit lighter to make the black font easier to read. Or the font colour could be changed to white or at least to a light colour. 

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/4de5a5f4-1dbb-4650-8869-28c2a613ddc4)

### How to Reproduce

Create a Select property in a database and add a few options

### Expected Behavior

Better contrast 

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.9

**Comment by richardshiue** [comment]
Seemingly a regression from this PR: https://github.com/AppFlowy-IO/AppFlowy/pull/3090
