### ISSUE TITLE
[Bug] German translation

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3189]
### Bug Description

german translation: 'Grid' -> 'Tabelle', 'Board' -> 'Board', 'new property' -> 'neue Eigenschaft' or 'neue Spalte'.

### How to Reproduce

Switch to German in the language setting

### Expected Behavior

As described in the bug description

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.9

**Comment by aryanA101a** [comment]
Should I do the rest or leave it?

**Comment by Xazin** [comment]
> Should I do the rest or leave it?

If you can check if we missed any of the changes and submit a PR for it, I'd be very grateful!
