### ISSUE TITLE
[FR] Move the position of title

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3191]
### Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8b57971b-1c9b-4689-aac3-d4f33fdbaf6f)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/17cf27ef-6132-46e9-87be-597a5996efa0)

The current title position is not ideal. 
It becomes redundant when having multiple tabs.
It's clumsy to edit and placed at a position "too" far away from the core editing area.
As shown in the screenshots, we should move it to the top of the core editing area.

### Impact

Document users

**Comment by annieappflowy** [comment]
The current implementation requires design polish
<img width="659" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c1bca4bf-00ee-4449-b155-89ec38ff5930">

**Comment by henri9813** [comment]
Hello, is this the same issue than ? https://github.com/AppFlowy-IO/AppFlowy/issues/5290

**Comment by Xazin** [comment]
Can we consider this complete @annieappflowy ?
