### ISSUE TITLE
Problem: Copy and paste checkbox

### ISSUE THREAD

**Issue by Cavalletta98** [AppFlowy-IO/AppFlowy#3194]
Hi,
if i try to copy and paste a checkbox, it is showned as normal text. I attach the picture of the problem
![immagine](https://github.com/AppFlowy-IO/AppFlowy/assets/45316566/e54b6c8b-f0fc-4ff1-9060-3e663c92b373)

**Comment by MayurSMahajan** [comment]
Thanks, @Cavalletta98 for filing this bug.
I was able to reproduce it on Windows 11, AppFlowy version 0.2.9

**Comment by annieappflowy** [comment]
Hi @Cavalletta98 , thanks for reporting. This issue was fixed in the latest release ([v0.3.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.3.0)) Let me know if you have any other feedback.
