### ISSUE TITLE
[Bug] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Ghoelian** [AppFlowy-IO/AppFlowy#3195]
### Bug Description

When I open AppFlowy, an exception is thrown, and the application window stays grey.

AppFlowy tries to use OpenSSL 1.1, which has not been included in Ubuntu since 22.04 (not sure about other distros).

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _invoke_log (package:appflowy_backend/ffi.dart)
#5      log (package:appflowy_backend/ffi.dart)
#6      Log.error (package:appflowy_backend/log.dart:61)
#7      PlatformErrorCatcherTask.initialize.<anonymous closure> (package:appflowy/startup/tasks/platform_error_catcher.dart:16)
#8      PlatformDispatcher._dispatchError (dart:ui/platform_dispatcher.dart:1195)
#9      _onError (dart:ui/hooks.dart:117)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      _open (package:appflowy_backend/ffi.dart:27)
#3      _dart_ffi_lib (package:appflowy_backend/ffi.dart:10)
#4      _set_env (package:appflowy_backend/ffi.dart)
#5      set_env (package:appflowy_backend/ffi.dart)
#6      FlowySDK.setEnv (package:appflowy_backend/appflowy_backend.dart:42)
#7      InitRustSDKTask.initialize (package:appflowy/startup/tasks/rust_sdk.dart:27)
#8      AppLauncher.launch (package:appflowy/startup/startup.dart:143)
<asynchronous suspension>
#9      FlowyRunner.run (package:appflowy/startup/startup.dart:71)
<asynchronous suspension>
#10     main (package:appflowy/main.dart:9)
<asynchronous suspension>
```

### How to Reproduce

Install AppFlowy on a stock Ubuntu >= 22.04 system with OpenSSL 3, and try to launch.

### Expected Behavior

The app launches.

### Operating System

Kubuntu 23.04

### AppFlowy Version(s)

0.2.9

### Additional Context

I know this is a duplicate of #1932, but this issue was closed without an actual solution.

Installing a no longer supported (by Ubuntu) version of OpenSSL is not a solution, in my opinion.

**Comment by pablo-01** [comment]
I have the the same issue, I wanted to use the app but seeing it requires no longer supported OpenSSL lib I decided not to use it. Would it be possible for something to be done about it?

**Comment by annieappflowy** [comment]
Hi @Ghoelian @pablo-01 , thanks for your feedback. We're fixing it. Will update the status on this thread.

**Comment by annieappflowy** [comment]
@pablo-01 , please give us another try?
It's fixed

**Comment by richardshiue** [comment]
Note that it'll need a manual build. So you may have to wait until 0.3.0

**Comment by Ghoelian** [comment]
Can confirm this update fixed it for me as well.

For some reason my Plasma shell now crashes when I use the desktop entry, but when I run the Exec line manually it works fine so I guess that's a KDE issue.

**Comment by Ghoelian** [comment]
Actually looks like it might not be an issue with KDE, I've created a separate issue for this #3260

**Comment by pablo-01** [comment]
I have tried again with the latest release, AppImage and deb package both result in app starting with a blank screen. I'm on pop os 22.04.
