### ISSUE TITLE
[Bug] Adding more than three sorts causes an overflow in grid

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3196]
### Bug Description

Adding more than three sorts causes an overflow in grid

### How to Reproduce

1. Open AppFlowy
2. Open or Insert a new Grid
3. Click Sort
4. Insert new sorts
5. Observe after adding more than 3 sorts

### Expected Behavior

The button for Add sort and Delete sort should not get overflowed.

### Operating System

--

### AppFlowy Version(s)

--

### Screenshots

![d062f07cdb145391b0219efb38c5ce573c0b7189_2_690x401](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/61b10d20-88d1-4d30-8fab-426c999f5a36)

### Additional Context

Reported on the forum by Mayur

https://forum.appflowy.io/t/adding-more-than-three-sorts-causes-an-overflow-in-grid/64/3

**Comment by MayurSMahajan** [comment]
Delete sort does delete all sorts and therefore the label must specify this.
