### ISSUE TITLE
[Bug] Grid, sort order icon not visible in dark mode

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3200]
### Bug Description

Description:
As mentioned in the title.

### How to Reproduce

1. Open AppFlowy and switch to a dark theme
2. Open or Insert a grid
3. Click on the Sort button in the top right corner of the grid to apply a sort
4. Click on the new Sort button at the top left of the grid
5. Observe the issue

### Expected Behavior

The icon next to Ascending should be visible in dark mode

### Operating System

Windows 11

### AppFlowy Version(s)

0.2.9

### Screenshots

![](https://global.discourse-cdn.com/standard11/uploads/appflowy/original/1X/04e5fc7ff57d6e80b57688a4f8e1df479266ff06.png)

**Comment by MayurSMahajan** [comment]
Assigned!

**Comment by naveed0000** [comment]
it's too complicated to setup that's why

**Comment by MayurSMahajan** [comment]
If you need help with setup, dm me on discord, we can figure something out.

**Comment by naveed0000** [comment]
@MayurSMahajan  okay

**Comment by MayurSMahajan** [comment]
No problem @naveed0000

**Comment by shridharGits** [comment]
hi @MayurSMahajan I think I can look into this issue, it will be great of you can assign this to me!

**Comment by MayurSMahajan** [comment]
Hi @shridharGits thanks for offering help. If you have a Mac, try to follow the steps in **How to Reproduce** and check if this issue also exists on Mac (it probably does). I'm assigning this issue to you.

**Comment by chaitanyyaa** [comment]
Hey @MayurSMahajan I've taken notice of the bug related to the grid's sort order icon visibility in dark mode. I'd like to step in and I would like to work on it. If possible, could you please assign this issue to me?

**Comment by shridharGits** [comment]
@MayurSMahajan I was unable to setup this one on mac. as @chaitanyyaa has also offered for help. please assign this to him

**Comment by MayurSMahajan** [comment]
It's fine @shridharGits. @chaitanyyaa, how about you complete the required setup and ping me here, then I will assign you this.

**Comment by panugothrakesh** [comment]
@MayurSMahajan can I get the path for the code for the sort element in the file. Thank you!

**Comment by chaitanyyaa** [comment]
> It's fine @shridharGits. @chaitanyyaa, how about you complete the required setup and ping me here, then I will assign you this.

yeah sure !

**Comment by MayurSMahajan** [comment]
hi @panugothrakesh! I don't mind sharing the file path of the issue, but we want to encourage new aspiring contributors such as yourself to explore the codebase while solving these Good First Issues. So I recommend you try to find it yourself. I'll give you a tip: Use the Flutter Widget Inspector.

**Comment by ekakshjanweja** [comment]
Hey was this issue resolved?

**Comment by annieappflowy** [comment]
Are you still working on this issue, @chaitanyyaa ?

**Comment by 1akhanBaheti** [comment]
**I just checked, this issue is resolved**

![Screenshot (34)](https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/08d7d297-5e13-4614-abed-d2684a2bd5d9)

**Comment by MayurSMahajan** [comment]
@1akhanBaheti Thanks for bringing this to my attention!
