### ISSUE TITLE
[Bug] Can't select or edit time if date is not set when picking Date from grid/kanban

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3202]
### Bug Description

Can't select or edit time if date is not set when picking Date from grid/kanban.
If this behavior is intended, then the Input Field of time should **visually indicate that it is disabled.** 
The cursor blinks and the user might try to select the time and edit but that is impossible.

### How to Reproduce

1. Open AppFlowy
2. Create or Open a Kanban/Grid
3. Click on a card to expand it.
4. Add property Date
5. In the Date input dialog box, toggle include time
6. An input field appears with a blinking cursor.
7. Try editing this field

The field is only editable when you select a date.

### Expected Behavior

This input field with a blinking cursor is disabled(maybe on purpose), thus it is expected to appear visually disabled.

### Operating System

Windows 11

### AppFlowy Version(s)

0.2.9 released.

### Screenshots

The culprit input field:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/391b6c4b-eb24-49d1-9338-cf4d5bd24307)

Video:
![time_grid](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/432a139e-8045-4152-8a88-c357f77500ee)

**Comment by richardshiue** [comment]
Hey @MayurSMahajan, I'm trying to understand this bug. Do you mean that the time should be constantly submitted as you enter the date? Or do you mean that the contents should be entered when focus is shifted? Or maybe something else? Currently you can enter time, press enter and the today will automatically be selected

**Comment by MayurSMahajan** [comment]
"Currently you can enter time, press enter and today will automatically be selected" 
@richardshiue are you able to change the time before selecting the date?
The main problem on my end is:
1. When I toggle include time on before I have selected any date 
2. Then the input field for time is selected and the cursor there is blinking
3. So here I tried changing the time but I could not.
As soon as I selected a date, I was able to edit the time input field as well.

So its a minor bug, bcz we can't change the text field and the cursor blinks there and it is in focus.

**Comment by richardshiue** [comment]
Hmm unable to reproduce on my end. 


https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/b0cdcb25-84d3-42f6-9757-229b6523b846

**Comment by MayurSMahajan** [comment]
Which OS are you using?

**Comment by richardshiue** [comment]
I'm using Linux, perhaps it's a platform issue

**Comment by MayurSMahajan** [comment]
Thanks @Nitin-Poojary! Maybe something is wrong at my end. Closing this issue.
