### ISSUE TITLE
[FR] Support Alt + click to add a row above

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3209]
### Description

No way to add a row above the current row.
Simply support a shortcut to enable this

### Impact

Grid users

**Comment by Nitin-Poojary** [comment]
Can I take this as my first issue?

**Comment by annieappflowy** [comment]
Of course. Thank you!

**Comment by Nitin-Poojary** [comment]
Thank you for assigning me the task. If I have specific doubts while working on it, where can I ask for assistance?

**Comment by Xazin** [comment]
> Thank you for assigning me the task. If I have specific doubts while working on it, where can I ask for assistance?

You can join our discord and hit us up in a relevant channel 👍
