### ISSUE TITLE
[Bug] Divider context menu

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3210]
### Bug Description

<img width="807" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/3da91433-7408-4a3c-804b-96a799a2e38f">

It only highlights the half width of a divider

### How to Reproduce

Insert a divider
Click the context menu in the left margin of the divider line

### Expected Behavior

Looks more polished

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.9

**Comment by tanmayyadav2323** [comment]
@annieappflowy can i please work upon this issue #3210.
