### ISSUE TITLE
[Bug] All the colors of the SVGs turn grey

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3211]
### Bug Description

<img width="369" alt="Screenshot 2023-08-15 at 23 03 04" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/3374fb64-3dcb-463d-a2b3-46df96e08b01">

### How to Reproduce

- run the code in the latest main branch

### Expected Behavior

- the SVGs should be rendered accurately.

### Operating System

All Platform

### AppFlowy Version(s)

main branch

### Additional Context

It may be related to this PR. https://github.com/AppFlowy-IO/AppFlowy/pull/3145

**Comment by a-wallen** [comment]
oops, I think that was this PR actually: https://github.com/AppFlowy-IO/AppFlowy/pull/3205

**Comment by LucasXu0** [comment]
There are still some SVGs being rendered incorrectly.

For example, 

the login page
<img width="442" alt="Screenshot 2023-08-16 at 10 17 05" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/fc27e198-3dc2-4ed0-8697-294ee6804577">

the add button
<img width="264" alt="Screenshot 2023-08-16 at 10 17 18" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/f1fda69c-b81d-44e9-ba9a-bb567ef55abb">

the "Reset Default Folder" button and its size are also incorrect.
<img width="297" alt="Screenshot 2023-08-16 at 10 17 52" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/9f260774-844c-4897-821d-04eea8f7b8c5">

And the others I haven't listed here.

**Comment by a-wallen** [comment]
Oops sorry about that. I'll go through the Figma and get everything back in order. It'll be fixed by tomorrow 🤞

**Comment by richardshiue** [comment]
This is now fixed AFAIK
