### ISSUE TITLE
[Bug] Creating a referenced view of a database causes errors.

### ISSUE THREAD

**Issue by nates-white** [AppFlowy-IO/AppFlowy#3224]
### Bug Description

If you create a database and on the same page create a referenced version, you will get AppFlowy error code: 3

### How to Reproduce

1. Create a database on a page, it can be any kind.
2. Create a reference of that database above or below it.
3. It will cause error code 3

### Expected Behavior

It should just make another view, or say that you can't do it.

### Operating System

MacOS Ventura 13.2.1

### AppFlowy Version(s)

0.2.9

### Screenshots

![Screenshot 2023-08-16 at 10 17 56 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/120990379/6c293109-83a9-4cc3-969e-41c0de31cb08)

**Comment by nates-white** [comment]
So, the referenced view will show after I restart the app, but if I delete it and make another referenced view, then the same error will occur.

**Comment by annieappflowy** [comment]
I can't reproduce it with the latest release.
If you run into this issue again, please re-open this issue.
