### ISSUE TITLE
[Task] Normalize SVGs in Flutter 

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3235]
### Description

Currently, by our design spec, we have icons of different sizes.

**The issues we currently face are:**
- SVGs are made up of vectors, thus size does not matter, the SVGs are dynamically sized on-demand
- The SVGs have different margin/padding, as some of them have this "drawn", instead of just being the actual size of the SVG.
- Duplicates exist and it can be confusing for the developer to choose

**What is required to complete this task:**
- Our icons in our design specification should only exist once, and all icons should be eg. 16x16px.
- Our icons should not have any margin or padding hardcoded in their files
- Each SVG should conform to a limited set of rules (eg. 16x16, zero padding, etc.)

### Impact

It will benefit all groups which deal with AppFlowy, users, maintainers, contributors, and designers.

**Comment by a-wallen** [comment]
Thanks for creating this 👍
