### ISSUE TITLE
[Bug] How start code on macOS / 

### ISSUE THREAD

**Issue by Taverz** [AppFlowy-IO/AppFlowy#3244]
### Bug Description

.pb.dart File ? / appflowy_backend/protobuf/ Folder?  
how generate / how run ?  
on mac.  

<img width="1436" alt="Снимок экрана 2023-08-20 в 11 55 59" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/f90a4c2a-3ceb-48ec-bc7b-ee2b4de257f6">

## Doctor -v

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale ru-US)
    • Flutter version 3.10.5 on channel stable at /Users/nikitakovalevtaverz/Documents/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (10 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nikitakovalevtaverz/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### How to Reproduce

1. download code 
2. run script docs macOS setup = ./frontend/scripts/install_dev_env/install_macos.sh
3. pub get dependence frontend flutter
4.  pub get dependence backande flutter
5. install protoc_plugin  - protoc-gen-dart
6. start protoc-gen-dart = running but not responding

### Expected Behavior

1. get dependence
2. worked

### Operating System

Mac os

### AppFlowy Version(s)

last dev - 0.2.9

### Screenshots

<img width="1436" alt="Снимок экрана 2023-08-20 в 11 55 59" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/f61d48e0-ff30-4558-9ae6-9dc09e6d82c4">

**Comment by LucasXu0** [comment]
@Taverz Did you follow the [install-appflowy](https://docs.appflowy.io/docs/essential-documentation/install-appflowy/installation-methods/from-source) documentation?

**Comment by Taverz** [comment]
@LucasXu0  yes

**Comment by LucasXu0** [comment]
@Taverz You can run the application by following step 4.

<img width="816" alt="Screenshot 2023-08-21 at 15 55 36" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/b1dad942-2327-4224-9210-1e1cec6e4f34">
<img width="547" alt="Screenshot 2023-08-21 at 15 56 16" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/61970720-22cc-4780-9edd-650a2fce3880">

**Comment by Taverz** [comment]
@LucasXu0 

I was able to reproduce as you said later, at first the version of the error intl: ^17 popped up, I went up to 18, other errors appeared.


Launching lib/main.dart on macOS in debug mode...
2023-08-21 18:10:12.650 xcodebuild[12725:5532230] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006020-000051621A7B401E }
{ platform:macOS, arch:x86_64, id:00006020-000051621A7B401E }
: Error: Type 'InvalidType' not found.
  InvalidType get locale => throw _privateConstructorUsedError;

  ^^^^^^^^^^^
: Error: Type 'InvalidType' not found.
      InvalidType locale,
      ^^^^^^^^^^^
: Error: Type 'InvalidType' not found.
      InvalidType locale,
      ^^^^^^^^^^^
: Error: Type 'InvalidType' not found.
  final InvalidType locale;
        ^^^^^^^^^^^
: Error: Type 'InvalidType' not found.
      required final InvalidType locale,
                     ^^^^^^^^^^^
: Error: Type 'InvalidType' not found.
  InvalidType get locale;
  ^^^^^^^^^^^
: Error: The non-abstract class '_AppFlowyInputState' is missing implementations for these members:
 - TextInputClient.insertContent
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _AppFlowyInputState extends State<AppFlowyInput>
      ^^^^^^^^^^^^^^^^^^^
: Context: 'TextInputClient.insertContent' is defined here.
  void insertContent(KeyboardInsertedContent content) {}
       ^^^^^^^^^^^^^
: Error: 'InvalidType' isn't a type.
      InvalidType locale,
      ^^^^^^^^^^^
: Error: 'InvalidType' isn't a type.
              as InvalidType,
                 ^^^^^^^^^^^
: Error: 'InvalidType' isn't a type.
      InvalidType locale,
      ^^^^^^^^^^^
: Error: 'InvalidType' isn't a type.
              as InvalidType,
                 ^^^^^^^^^^^
: Error: 'InvalidType' isn't a type.
  final InvalidType locale;
        ^^^^^^^^^^^
: Error: 'InvalidType' isn't a type.
      required final InvalidType locale,
                     ^^^^^^^^^^^
: Error: No named parameter with the name 'valueDefaultOrMaker'.
    ..m<$core.String, BlockPB>(2, _omitFieldNames ? '' : 'blocks', entryClassName: 'DocumentDataPB2.BlocksEntry', keyFieldType: $pb.PbFieldType.OS, valueFieldType: $pb.PbFieldType.OM, valueCreator: BlockPB.create, valueDefaultOrMaker: BlockPB.getDefault)
                                                                                          ^^^^^^^^^^^^^^^^^^^
: Error: No named parameter with the name 'valueDefaultOrMaker'.
    ..m<$core.String, ChildrenPB>(1, _omitFieldNames ? '' : 'childrenMap', entryClassName: 'MetaPB.ChildrenMapEntry', keyFieldType: $pb.PbFieldType.OS, valueFieldType: $pb.PbFieldType.OM, valueCreator: ChildrenPB.create, valueDefaultOrMaker: ChildrenPB.getDefault)
                                                                                          ^^^^^^^^^^^^^^^^^^^
: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
                      text: state.path,
                                  ^
: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragDownDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../dev/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
        onTapDown: onTapDown,
                   ^
: Error: The argument type 'void Function(TapUpDetails)' can't be assigned to the parameter type 'void Function(TapDragUpDetails)?'.
- 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragUpDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../dev/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
        onSingleTapUp: onSingleTapUp,
                       ^
: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragDownDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../dev/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
        onDoubleTapDown: onDoubleTapDown,
                         ^
: Error: The argument type 'void Function(DragStartDetails)' can't be assigned to the parameter type 'void Function(TapDragStartDetails)?'.
- 'DragStartDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragStartDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../dev/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
        onDragSelectionStart: onDragSelectionStart,
                              ^
: Error: The argument type 'void Function(DragStartDetails, DragUpdateDetails)' can't be assigned to the parameter type 'void Function(TapDragUpdateDetails)?'.
- 'DragStartDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'DragUpdateDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragUpdateDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../dev/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
        onDragSelectionUpdate: onDragSelectionUpdate,
                               ^
: Error: The argument type 'void Function(DragEndDetails)' can't be assigned to the parameter type 'void Function(TapDragEndDetails)?'.
- 'DragEndDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../../dev/flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragEndDetails' is from 'package:flutter/src/widgets/tap_and_drag_gestures.dart' ('../../../../dev/flutter/packages/flutter/lib/src/widgets/tap_and_drag_gestures.dart').
        onDragSelectionEnd: onDragSelectionEnd,
                            ^

: Error: Field 'wLanguage' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? wLanguage;
                ^
: Error: Field 'wCodePage' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? wCodePage;
                ^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code

warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
/Users/nikitakovalevtaverz/Documents/GitHub/AppFlowy/frontend/appflowy_flutter/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'ReachabilitySwift' from project 'Pods')
** BUILD FAILED **
Exception: Build process failed
Exited

**Comment by richardshiue** [comment]
There might be a few others, but one of the problems that could be causing this is that AppFlowy is currently being built against Flutter version 3.10.1. From your `flutter doctor -v` it seems like you have 3.10.5 installed. Please downgrade and see if that fixes your issue.

**Comment by Taverz** [comment]
@richardshiue  can I run this particular project on one version, and the rest on another?! I have been interested in this issue for a long time, since different projects, different versions

**Comment by richardshiue** [comment]
You can look into something like fvm that manages different flutter versions on your system.

**Comment by Mo5hu** [comment]
@Taverz Can you show the error details, when you are running clean + rebuild all ?

**Comment by Taverz** [comment]
<img width="1496" alt="Снимок экрана 2023-08-27 в 21 49 19" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/db0e964c-2708-42f4-8109-eedb1af46562">
<img width="789" alt="Снимок экрана 2023-08-27 в 21 49 25" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/86acb728-fc12-47a8-ab08-ab1aeaa686c5">
<img width="920" alt="Снимок экрана 2023-08-27 в 21 50 01" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/3260a1b9-9b69-4610-8905-6f8af34d5541">
<img width="733" alt="Снимок экрана 2023-08-27 в 22 18 04" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/52d20168-7047-4c09-9754-58db55584365">
<img width="823" alt="Снимок экрана 2023-08-27 в 22 18 09" src="https://github.com/AppFlowy-IO/AppFlowy/assets/55701501/646a8975-33e5-4288-9c00-9c3355881808">

**Comment by Taverz** [comment]
Description problem

https://github.com/AppFlowy-IO/AppFlowy/issues/3244#issuecomment-1686600007

**Comment by Taverz** [comment]
@LucasXu0   Changing the version didn't help. I ran =All Desktop: Clean + Rebuild= then fixed all the problems, after each fix I ran =All Desktop: Clean + Rebuild= and new problems appeared, I changed the version of intl / appflowy_editor , after they stopped crying I ran -All DEsktop: Build Dart Only - , after running more problems I just commented out these problems and restarted. everything works cheers, but I destroyed half of the project, it's a joke )) but I had to comment out a lot of code, I'll probably create a new branch and launch it to reflect the changes
