### ISSUE TITLE
[Bug] List cards always jump to top/bottom when add/rename card 

### ISSUE THREAD

**Issue by thaidmfinnick** [AppFlowy-IO/AppFlowy#3249]
### Bug Description

When I create new card, other lists (not contains new card) always jump to top of each list. After card created, list contains new card will jump to top.

When I rename a card, other lists (not contains new card) always jump to top of each list. List contains card renamed will jump to bottom.

### How to Reproduce

**Create Card**
1. Create card with long list (needs to be scrolled)
2. Type content and click outside

**Rename Card**
1. Hover a card and click button edit

### Expected Behavior

**Created card**
List contains new card does not scrolled after created. Other lists keep scroll position.

**Rename card**
List contains card renamed does not scrolled after renamed.

### Operating System

MacOS Ventura 13.2

### AppFlowy Version(s)

v0.2.9

### Screenshots

Case Create Card: 00:00 -> 00:20
Case Rename Card: remain

https://github.com/AppFlowy-IO/AppFlowy/assets/83997264/098f5f8c-4dda-4f68-8f71-fdaadf2362f7

**Comment by Xazin** [comment]
> Hi, I am interested in tackling this bug. I was able to reproduce the bug on my end. Can I please be assigned to this issue?

Sure Tony, I've assigned you, feel free to reach out if you meet any issues.

**Comment by thaidmfinnick** [comment]
Thank you, so looking forward to hearing updates from you.

**Comment by thaidmfinnick** [comment]
Hi @tonynguyen111997, have you found the problem or any updated on this issue?
