### ISSUE TITLE
[Bug] Build has an error when not Ubuntu

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#326]
**Describe the bug**
When trying to build on Linux, the build process checks for the existence of a protobuf compiler. If not present the build script then tries to install it.  This fails on any distribution of Linux which does not use apt as the package installer.

In my case, I already have the protobuf compiler installed, yet it still tried to install it. So I'm not sure what it's looking for...

Also, the build script ask for my administrator password, and we can't even see what the command is.  This is a REALLY bad idea, and I highly recommend that nobody ever enter their password.

**To Reproduce**
1. Try to build the app.

**Expected behavior**
App builds without the need to enter my administrator password. :)

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/153731627-5e1293dd-486b-4fec-8178-c892e9ed272d.png)

**Desktop (please complete the following information):**
 - OS: Any Linux distro that does not use apt-get
 - Browser: N/A
 - Version 3.0 beta 2

**Additional context**
 - None

**Comment by appflowy** [comment]
I'm sorry to hear that. I just want to hide the complexity of the tool installation of AppFlowy. The scripts in located in frontend/scripts/makefile/protobuf.toml

![image](https://user-images.githubusercontent.com/86001920/153735228-eb8a5b17-e88d-45ac-a661-4d8df1a71869.png)

Is there a better way to reduce the install steps of AF? Or we just let the developer decide what to do next step by step. Any suggestions will be helpful.

**Comment by appflowy** [comment]
For the moment, there is no need to install protoc binary anymore. The build process uses the [embedded protoc binary](https://github.com/stepancheg/rust-protoc-bin-vendored) to the compiler the proto files. Check out this [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/328) for more details.
