### ISSUE TITLE
[FR] Getting Started adapts to the system supporting dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3266]
### Description

It's only in the light mode
Would be great to support the dark mode
<img width="404" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c73b5097-78c3-4b8f-8b4e-be37e3a0482e">

### Impact

System in the dark mode

**Comment by hyj1204** [comment]
It has been solved in the current version 0.3.6
<img width="793" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/a1993ae6-2e4d-4e31-b541-24074b03c3ce">
