### ISSUE TITLE
[Bug] Dandelion theme color in dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3268]
### Bug Description

<img width="195" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/f62ab414-0726-4284-8346-d66a4a71f21b">

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/582c6d08-5872-4884-9d7a-e1d75ab9a505)

### How to Reproduce

Turn on the dark mode
Choose Dandelion

### Expected Behavior

Theme color should closely match the user expectation 

### Operating System

Windows 11

### AppFlowy Version(s)

v0.3.0

**Comment by hyj1204** [comment]
I made a Figma preview(some elements may not be correct, for color preview only) for the dandelion theme. Please feel free to share any suggestions you have. @annieappflowy @MayurSMahajan 

Light mode: 
<img width="855" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/b5b955dc-5150-46fc-bad2-9918c1cc1bec">

Dark mode:
<img width="863" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/47479b05-adb3-4741-8db2-b5a6809fc376">

**Comment by MayurSMahajan** [comment]
Looks absolutely beautiful!
