### ISSUE TITLE
[Bug] Improve theme in restore prompt (dark mode)

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#3276]
### Bug Description

When we are in a document and we delete it, we are prompted by a restore/delete permanently prompt. The prompt looks perfect in all themes in light mode, However the text is not optimised for dark mode. 

### How to Reproduce

1. Open any document.
2. Delete the document, from the document menu options (in side bar, using the 2 dots).
3. You will be prompted by a restore/delete permanently bar at top.
4. While you see the prompt, go to settings and toggle theme between dark and light mode. You can easily notice the readability issue and low accessibility of text in dark mode.

### Expected Behavior

The text and buttons should be optimised for dark mode as well.

### Operating System

Ubuntu

### AppFlowy Version(s)

0.3.0

### Screenshots

![Screenshot from 2023-08-25 10-49-32](https://github.com/AppFlowy-IO/AppFlowy/assets/37607224/55c2e9ff-3e4f-4cb9-b192-bf6e01b57f6b)

![Screenshot from 2023-08-25 10-50-55](https://github.com/AppFlowy-IO/AppFlowy/assets/37607224/5cd81173-b579-4677-99a9-24da71f325a5)

**Comment by AmanNegi** [comment]
I'd like to fix this minor theme issue :)

**Comment by MayurSMahajan** [comment]
Assigned!
