### ISSUE TITLE
[Bug] Can't copy paste into empty code block 

### ISSUE THREAD

**Issue by tokkyuuressha** [AppFlowy-IO/AppFlowy#3277]
### Bug Description

After creating a code block, copy pasting a single line into it replaces the code block with plain text line.
Can be worked around with typing anything(spacebar, new line) and then pasting.

I noticed there's another issue #2992 reported about copy pasting into code block, so perhaps the feature needs some reworking.

### How to Reproduce

1. Copy a line of text
2. Create a code block
3. Paste the text (without typing in the codeblock beforehand)
4. Code block disappears and line of plain text appears

### Expected Behavior

Line of text is pasted inside the code block

### Operating System

Windows

### AppFlowy Version(s)

0.3.0

**Comment by MayurSMahajan** [comment]
cc @LucasXu0 The PR #3151 should solve this issue

**Comment by MayurSMahajan** [comment]
In the next release of AppFlowy, this bug will be resolved as the respective PR is merged.
