### ISSUE TITLE
[Bug] Chinese character input

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#3282]
### Bug Description

I have raised the issue of Chinese input in version 0.0.7 [ISSUE](https://github.com/AppFlowy-IO/AppFlowy/issues/1488) but there are still problems with 3.0.0, so I have not had the opportunity to use appflowy. However, in this test, I find that compared with the last time, I can input a single Chinese character, but still cannot input continuously.

### How to Reproduce

Enter Chinese in any edit area.

### Expected Behavior

Enter a single character, then a space
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/fae1382b-f706-4d3a-8949-26241711a5c5)
Continuous input
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/a3a647c9-2862-43c8-af56-4d82e15d4b9b)

### Operating System

Microsoft Windows 10

### AppFlowy Version(s)

v 3.0.0

**Comment by annieappflowy** [comment]
Thanks @enomothem for your feedback. We're working on it. Will let you know once it's fixed.

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/3278

**Comment by annieappflowy** [comment]
<img width="556" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/134f8c0a-b327-417e-b242-fa00f1923ae9">

Fixed

**Comment by annieappflowy** [comment]
Thanks for confirming, @enomothem

**Comment by wfeii1980** [comment]
I also encountered the same problem

## My system:

```shell
~  neofetch 
                   -`                    wii@relink 
                  .o+`                   ---------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 20AWS1XF01 ThinkPad T440p 
               `+oooooo:                 Kernel: 6.6.6-arch1-1 
               -+oooooo+:                Uptime: 19 mins 
             `/:-:++oooo+:               Packages: 1332 (pacman) 
            `/++++/+++++++:              Shell: bash 5.2.21 
           `/++++++++++++++:             Resolution: 3440x1440 
          `/+++ooooooooooooo/`           DE: LXQt 1.4.0 
         ./ooosssso++osssssso+`          WM: Openbox 
        .oossssso-````/ossssss+`         Theme: Pop [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: breeze [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: lxterminal 
     /ossssssss/        +ssssooo/-       Terminal Font: 文泉驿等宽微米黑 10 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-4810MQ (8) @ 3.800GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel 4th Gen Core Processor 
 `++:.                           `-/+/   Memory: 2053MiB / 15875MiB 
 .`                                 `/
```

```shell
~  fcitx5 --version
5.1.5
```

## Bug demonstration:
[video](https://wii-public.oss-cn-beijing.aliyuncs.com/videos/appflowy-chinese-input-bug-test.mp4)

**Comment by d0ngyu** [comment]
@annieappflowy This bug still exists in the v0.4.2

**Comment by d0ngyu** [comment]
@annieappflowy This bug still exists in the v0.4.2

**Comment by annieappflowy** [comment]
@d0ngyu , what's the operating system you run AppFlowy on?

**Comment by d0ngyu** [comment]
> @d0ngyu , what's the operating system you run AppFlowy on?

Windows 11

**Comment by annieappflowy** [comment]
@d0ngyu , I have tested it on Windows 11, and I can input Chinese characters without any issue. Can you share a screen recording of the issue you have?

**Comment by d0ngyu** [comment]
@annieappflowy , sorry, I have uninstalled the software long long ago

**Comment by Sameer-bot-maker** [comment]
@annieappflowy Any fix for the Chinese characters?? I can't type on my Fedora KDE it duplicates the words when i type and i am using wayland.. I am not sure what's going on but other browsers chatting it all works fine for me... It's just appflowy for me..
