### ISSUE TITLE
Additional options (delete, duplicate, etc) does not show up for each note in the notes list.

### ISSUE THREAD

**Issue by Hubrisjunk** [AppFlowy-IO/AppFlowy#3288]
### Bug Description

In my AppFlowy instance i cannot get the additional options to show up for the notes that i make and using keyboard shortcuts does not work to delete a note. 

### How to Reproduce

I am using it on a windows Surface 8 running windows 11 pro. Intel I5 Evo with screen refresh rate at 60hz. Aside from that its just a normal install.

### Expected Behavior

Well i expected to see the 2 small dots that when clicked let me have the additional options to delete, duplicate etc. 

### Operating System

Windows 11 Pro

### AppFlowy Version(s)

0.30

### Screenshots

![Screenshot 2023-08-29 013433](https://github.com/AppFlowy-IO/AppFlowy/assets/143493083/afb4ca08-3b26-41cb-bf43-ff781e78c993)

### Additional Context

Perhaps it is due to the device being a touchscreen?

**Comment by LucasXu0** [comment]
@Hubrisjunk, since hover actions are not working on touch screens, I have made the hover actions always visible when a page is selected.

<img width="223" alt="Screenshot 2023-08-30 at 18 07 58" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/f2f83e07-7170-4e1e-8a28-85665ad2b406">
