### ISSUE TITLE
[FR] Wiki-like links between pages

### ISSUE THREAD

**Issue by angryreindeer** [AppFlowy-IO/AppFlowy#3294]
### Description

Hello! I have been using Zim for awhile as the wiki format is nice. Appflowy has similar structure, with nested menus and subpages. I also enjoy the modularity. It would be nice to have a feature where links between pages can be made.

### Impact

I believe this would complement the features present in the current release.

### Additional Context

Comparable capability can be seen in fandom.com, wikipedia.org, etc.

**Comment by annieappflowy** [comment]
Have you tried typing @ to link a subpage?
If this cannot meet your need, could you elaborate on how you would want to link between pages?
