### ISSUE TITLE
[Bug] Misleading "expand" icon button on the documents which doesn't have any nested pages

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#3300]
### Bug Description

Currently, an arrow icon button shows in front of the page **no matter** it has a nested page or not. 

I think we should show this arrow button **only** when it has a nested page. If there is no nested page, the arrow button should be removed. 

https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/3513b465-f329-497c-a358-8d170d641e41

### How to Reproduce

Add new pages in the side bar

### Expected Behavior

No "expand" icon button shows on the pages that don't have any nested pages.

### Operating System

macOS

### AppFlowy Version(s)

0.3.0

**Comment by annieappflowy** [comment]
We have revamped the sidebar and fixed this issue. If there is no subpage, the expand icon won't show.
<img width="241" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/53854b39-35ee-4eb1-b209-c472864cd635">
