### ISSUE TITLE
[FR] Selction of AI writer model.

### ISSUE THREAD

**Issue by sina-mansour** [AppFlowy-IO/AppFlowy#3305]
### Description

Currently, OpenAI provides a range of [alternative AI models](https://platform.openai.com/docs/models/gpt-4) (e.g. `text-davinci-003`, `gpt-4`, and `gpt-3.5-turbo`). Given the considerable difference in the [pricing of these models](https://openai.com/pricing), it would be awesome if AppFlowy could enable the selection of the model by the user (e.g. a dropdown or textbox in settings).

The [current codebase](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/service/openai_client.dart) seems to be using Davinci. However, there are now alternatives that either perform better or are comparatively cheaper. I hence wanted to ask for this new feature to be added.

Many thanks for developing such a great open-source application.

### Impact

Anyone using the AI writer would benefit from this feature.

**Comment by yatendra2001** [comment]
I think @annieappflowy, I can include this feature during the development of the #2782 project.

**Comment by annieappflowy** [comment]
cc: @LucasXu0

**Comment by annieappflowy** [comment]
<img width="206" alt="image" src="https://github.com/user-attachments/assets/99039398-8872-4b83-b697-931f819a3160">
