### ISSUE TITLE
[FR] Use platform standard icons for more actions

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3307]
### Description

Change the more action icons to the established platform default "three dots".

AppFlowy:
<img width="172" alt="Screenshot 2023-09-01 at 13 46 06" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/9e4a4de9-ce80-4a08-a365-5f92f948d2c5">

macOS:
<img width="267" alt="Screenshot 2023-09-01 at 13 47 22" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/d9a7638b-4066-4f9f-a05d-2c922f996b4e">

### Impact

Using familiar icons for well established actions improves usability and reduces cognitive load especially when using newly installed software that the user is not familiar with.

**Comment by annieappflowy** [comment]
<img width="215" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/0e3ac708-ff95-4347-af03-e4ca7d8ecc4b">

Fixed
