### ISSUE TITLE
[FR] Delay tooltip presentations

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3310]
### Description

- Set tooltip presentation delay to ~300ms.
- And/or Remove tooltip interactivity

Currently tooltips appear almost immediately when hovering over items:
- they can obstruct other interactive elements as first you have to click to hide the tooltip before being able to click on them
Example:
<img width="138" alt="Screenshot 2023-09-01 at 14 01 52" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/5cf74c99-14f7-4433-9d22-cce45cc805d7">

<img width="226" alt="Screenshot 2023-09-01 at 14 08 45" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/8c64552f-4624-4693-815d-aad957f44dc4">

- They create visual clutter as moving the mouse around
- Windows and macOS both delay tooltips, so a delay also aligns with platform conventions better

### Impact

- Improves the overall feel of the app by appearing more clean
- Creates less visual clutter for users who already know their way around the app and click intentionally and fast

**Comment by AdiAr11** [comment]
Hi @MayurSMahajan , I would like to work on this issue. Should we add a delay of around 300 ms before showing the tooltip? Or anything else also needs to be done?

**Comment by MayurSMahajan** [comment]
@AdiAr11 Thanks for helping, Assigned!
cc @Xazin @LucasXu0 is 300ms delay desirable to us, or we should use some other value?

**Comment by intonarumori** [comment]
I looked more into it.

I think the takeaways are:
- Any delay of > 100-200ms improves the feel of the app by not presenting tooltips all over the place just by hovering
- 1 sec is the default for macOS apps (which some people find too slow), but it's up the the application developer to override it (more info [here](https://apple.stackexchange.com/questions/328908/how-to-reduce-tooltip-appearance-delay-in-xcode))
Use the following command to see some overrides: `defaults read | grep "NSInitialToolTipDelay"`

Some examples:
```
"org.audacityteam.audacity" =     {
        NSInitialToolTipDelay = 1000;
}
"us.zoom.xos" =     {
        NSInitialToolTipDelay = 100;
}
```
- Looks like we have to come up with something reasonable, to me it seems something in the range of 200-500ms would be nice.

**Comment by MayurSMahajan** [comment]
Yes, I think something in the range of 100ms to 300ms.

**Comment by Xazin** [comment]
https://api.flutter.dev/flutter/material/Tooltip/waitDuration.html

300ms in my opinion would be nice.
