### ISSUE TITLE
[FR] Apply consistent style to quick command menu results

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3313]
### Description

Look of the quick command menu is different when the result set is empty.
Note the sharp corners.

<img width="404" alt="Screenshot 2023-09-01 at 14 16 30" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/5b01df83-9ae2-49ab-afcc-d745a6c87008">

<img width="212" alt="Screenshot 2023-09-01 at 14 16 35" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/63eb2940-1f33-4f59-8390-45769c1b6a74">

### Impact

Consistency improves perceived app quality.

**Comment by MayurSMahajan** [comment]
Nice catch! So essentially the issue can be solved if 
- the border radius on both the menus is same. 
 
Or is there something more you want to add @intonarumori

**Comment by intonarumori** [comment]
@MayurSMahajan I experimented a bit more, I think it would be nice to match the width of the result display when it has only one column, it's a minor thing, but would probably look better when typing, deleting etc. less jumping around.

One column result list:
<img width="217" alt="Screenshot 2023-09-03 at 12 19 59" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/a78034a2-8a2f-4b8f-a7fa-ce04650eaa23">

No results right now:
<img width="212" alt="Screenshot 2023-09-03 at 12 20 04" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/fdcc2d61-a6bb-4128-aeb6-4091bd49320a">

**Comment by khurramrizvi** [comment]
Please assign this to me, I would like to contribute.

**Comment by MayurSMahajan** [comment]
@khurramrizvi assigned! have fun.

**Comment by khurramrizvi** [comment]
@MayurSMahajan Hey, it seems the issue was not assigned to me, could you please assign this to me.

**Comment by Kritarthsharma** [comment]
Hi @MayurSMahajan, I've added one fix to appFlowy_editor repo for this issue and raised a PR. Can you please review it and assign this to me. Thanks!

[https://github.com/AppFlowy-IO/appflowy-editor/pull/567](url)
