### ISSUE TITLE
[Bug] Invisible window top bar obstructs title editing on macOS

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3314]
### Bug Description

macOS windows are draggable at the top, but the app also uses that area to display and edit the document title.
Most of the time it's impossible to click or select in the editable text field as the mouse click is recognized as a drag gesture for the whole window.

### How to Reproduce

- Use macOS Ventura
- Open a document
- Try to edit the title
- Select another document
- Try to edit the title

### Expected Behavior

The title is editable.

### Operating System

macOS Ventura 13.2.1

### AppFlowy Version(s)

Version 0.3.0 (0.3.0)

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/86030/ded178fb-652a-46c4-852d-82cb6179f7db

**Comment by annieappflowy** [comment]
#3191

**Comment by annieappflowy** [comment]
Hi @intonarumori , how do you like the new design of changing the title?
<img width="285" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/4207cad5-0ced-4198-91ca-4a9306780149">
