### ISSUE TITLE
[FR] Use faster animations to toggle sidebar

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3315]
### Description

The current animation duration for hiding and showing the sidebar is very slow.
It gives you the impression of the app being "sluggish".

### Impact

Makes the app feel more "snappy" and higher quality.

### Additional Context

Experimenting with easing functions would also improve the overall feel.

**Comment by richardshiue** [comment]
Hi @intonarumori thanks for raising this issue. Could you help me to clarify whether it's the delay when pressing on the button or the animation duration that's making the sliding animation feel sluggish?

**Comment by intonarumori** [comment]
You can fine tune the animation in two ways:
- Use shorter duration for the animation, this is what I was referring to
- Use a more natural curve for the animation: this greatly affects the feel of the animation.
- In real life moving objects have momentum, so they cannot stop abruptly. I think the current animation uses a linear curve and thus it feels unnatural. You can see the options here: https://api.flutter.dev/flutter/animation/Curves-class.html
I think `easeOut` would work best here, but feel free to experiment.

**Comment by Sumit4482** [comment]
Hello, I would like to work on this issue. Can you please assign it to me ?

**Comment by richardshiue** [comment]
Sure thing, have fun!

**Comment by Sumit4482** [comment]
Thanks :)

**Comment by Sumit4482** [comment]
Hey @intonarumori

**Comment by Sumit4482** [comment]
Hi @intonarumori ,
I reduced the panel duration and found easeInOut to work best. Any thoughts or suggestions?
Thanks!  [Preview](https://drive.google.com/file/d/1azGuWoUvG7yRG3HN-ldg4ggt5rd6E3Z3/view?usp=drive_link)

**Comment by richardshiue** [comment]
Could you make a PR so that we can have a look at it?

**Comment by Sumit4482** [comment]
Sure !

**Comment by intonarumori** [comment]
@Sumit4482 Good job, looks better already ✨ 

I think in general `easeOutXXX` should be the goal here, with the current `easeInOut` you start slowly, speed up, then slow down again at the end. I think for this animation we don't need the `in` part.

As for the curve itself, you can study the visual representation of them on the [Curves documentation](https://api.flutter.dev/flutter/animation/Curves-class.html).
You can see that the start of the curve gets steeper in this order: `easeOut`, `easeOutSine`, `easeOutQuad`, `easeOutCubic`, `easeOutQuart`, `easeOutQuint`, `easeOutExpo`.

We are at the beginning of this spectrum with `easeOut`, it can be subjective and it's best to try all of them and use them for a bit of time to see if it feels natural, I usually end up with `easeOutCubic` for my apps.

Please note you might need to adjust the duration for some of these curves, the Flutter documentation explicitly mentions this for `easeOutExpo` here: https://api.flutter.dev/flutter/animation/Curves/easeOutExpo-constant.html

I would go for a bit more aggressive `easeOutQuad` or `easeOutCubic`, merge the PR, let the testers and the team use it for a bit and fine tune if necessary.

**Comment by annieappflowy** [comment]
Can you @Sumit4482 @richardshiue update the status of this issue?

**Comment by richardshiue** [comment]
Closing as completed from Sumit's PR merge
