### ISSUE TITLE
[FR] Use platform native shortcut for settings

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3317]
### Description

macOS uses `CMD + ,` to display the application menu.

Flutter provides shortcuts and [`PlatfromMenuBar`](https://api.flutter.dev/flutter/widgets/PlatformMenuBar-class.html) to integrate with the shortcuts and menu systems.
Once you enable it the menu item will be active as well.

<img width="323" alt="Screenshot 2023-09-01 at 14 39 23" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/f7944175-19ef-42da-9cc8-b17bf9af6215">

### Impact

All users familiar with system wide macOS shortcuts.

**Comment by PalaniappanC** [comment]
Hi @annieappflowy Can you assign this issue to my name.

**Comment by Xazin** [comment]
> Hi @annieappflowy Can you assign this issue to my name.

I've assigned you, let me know if you need any assistance :+1:

**Comment by PalaniappanC** [comment]
Hi @Xazin @intonarumori @annieappflowy. The settings option is itself disabled in the AppFlowy. What should be the action item on clicking the Settings option, should the mac settings open or do we have any settings for appflowy.

**Comment by PalaniappanC** [comment]
Hi @annieappflowy  @Xazin The PlatfromMenuBar is a stateful widget and our SettingsDialog is a StatelessWidget. I am not able to call the SettingsDialog via PlatformMenuBar. Kindly help me with this

**Comment by PalaniappanC** [comment]
Hi @Xazin @annieappflowy @MayurSMahajan @intonarumori Hope this is not possible in the current version of PlatformMenuBar provided by flutter as it does not have an option to list all the current menu items of the host (the MainMenu.xib items present now). 
Due to this when I implement the custom logic with PlatformMenuBar all the previous Menu Items like Edit Help Windows everything goes away. 

Flutter Issue Reference : https://github.com/flutter/flutter/issues/133039

**Comment by PalaniappanC** [comment]
Hi @intonarumori  we can't just assign the shortcut to settings using the PlatformMenuBar. We have to construct the entire mac os menu bar the appflowy has now. Shall I proceed with that

**Comment by intonarumori** [comment]
@PalaniappanC Thanks for looking into this.

Please take a look at [PlatformProvidedMenuItem](https://api.flutter.dev/flutter/widgets/PlatformProvidedMenuItem-class.html) to preserve some of the system provided items. You have to add them into your menu hierarchy and the library will make sure they will be added.

If something is still missing, then we probably have to file an issue on the Flutter Github repo.

I was even able to modify the native side to preserve the search functionality in the Help menu. There's an ongoing discussion about fixing that in Flutter here: https://github.com/flutter/flutter/issues/133039

Let me know how it goes and I'm happy to assist.

**Comment by PalaniappanC** [comment]
Sure @intonarumori. I can implement the whole menubar. But need some time hope its okay.

**Comment by annieappflowy** [comment]
Would you like to work on this @PalaniappanC ?

**Comment by PalaniappanC** [comment]
Hi @annieappflowy you can unassign me...

**Comment by annieappflowy** [comment]
Supported cmd + , to open up Settings
