### ISSUE TITLE
[FR] Close context menus when an item is selected in settings

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3318]
### Description

Context menus usually close when an item is selected.

In AppFlowy settings they tend to not do that, which is inconsistent with the conventions on most platforms.

https://github.com/AppFlowy-IO/AppFlowy/assets/86030/1815301b-b1c9-4768-8537-4a1cf38dd718

### Impact

- Better meets user expectations
- Improves consistency with platform conventions

**Comment by MayurSMahajan** [comment]
@intonarumori Good catch!

**Comment by AdiAr11** [comment]
Hi @MayurSMahajan @annieappflowy I would like to work on this issue!

**Comment by annieappflowy** [comment]
Thanks @AdiAr11 
Assigned

**Comment by AdiAr11** [comment]
Hi @annieappflowy I'm sorry but this issue was assigned to me but someone else got their PR merged first.
