### ISSUE TITLE
[Bug] Settings -> Appearance -> Font Family: Font name hidden

### ISSUE THREAD

**Issue by gellenburg** [AppFlowy-IO/AppFlowy#3319]
### Bug Description

When attempting to change the application's font, if the font name is too long to fit in the drop down window it is wrapped (I assume) and the full name becomes invisible.

This makes it impossible to tell the correct font you want to apply to the application.

### How to Reproduce

Open the Settings window.

Navigate to Appearance.

Select the current font within the "Font Family" option. A drop down appears with a search box.

Search for "Noto Sans". A popular font.

Several dozen other "Noto Sans" varieties of fonts appear. But since the font names are too long to actually appear on one line in the drop-down their names are truncated. This makes it impossible to determine which is the correct font you want to apply.

### Expected Behavior

I would expect the full name to at least be partially/ be visible within the drop-down window, even if the font name is too long to fit on a single line.

Seems like the only thing that needs to happen here is word-wrap needs to be turned off for this UI element?

### Operating System

Windows 11 Pro

### AppFlowy Version(s)

0.3.0

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7026750/384e37f5-6bd7-4f42-a221-6859c9fcaca0)

**Comment by MayurSMahajan** [comment]
@gellenburg, good catch! Thanks for reporting. 
cc @a-wallen 
Should we display a tooltip on long font options that contains the full name, that way if we have a font name that is longer then hovering on it will show its full name in a tooltip?
Or is there a better way?

**Comment by AdiAr11** [comment]
Hi @MayurSMahajan , how about adding text ellipsis along with tooltip?

**Comment by MayurSMahajan** [comment]
That's a good idea @AdiAr11

**Comment by AdiAr11** [comment]
I can also work on this!

**Comment by MayurSMahajan** [comment]
Sure @AdiAr11, I suggest you solve the issue that you are assigned to and then begin working on this later.

**Comment by AslamThachapalli** [comment]
Hi @MayurSMahajan , Greetings. I am new to this repo. 
If ok, I would like to solve this issue.

**Comment by MayurSMahajan** [comment]
Great @AslamThachapalli! You can start working on this.

**Comment by AslamThachapalli** [comment]
Sure.

**Comment by annieappflowy** [comment]
@AslamThachapalli , are you still working on this?

**Comment by AslamThachapalli** [comment]
Pardon for the late reply. 
I will push the latest changes soon. I am working on it.
