### ISSUE TITLE
[FR] Make optional "Support for editing name when creating a new page"

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#3335]
### Description

V.0.3.1 brings new feature:
> Support for editing name when creating a new page.

Sometimes it's a bit annoying. I don't need it. Sometimes I prefer to change items names after creating them. Previous UX-way was much better. Please roll back —  give me an option to choose, make default page name ("Untitled") or type manual.

Before this update all was OK with naming, because there was no pop-up.

### Impact

UX economy and time saving

### Additional Context

In addition to #3324

**Comment by LucasXu0** [comment]
Hey, @Twilightssuperb. I have added an option on the settings page and it will be released in the next version.


![Image](https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/4d565aa9-dcf3-4feb-aa0c-a00315bd2766)
