### ISSUE TITLE
[FR] Allow Reorder Select Box Items

### ISSUE THREAD

**Issue by Schrolli91** [AppFlowy-IO/AppFlowy#3339]
### Description

In the Gridview i have created a select box for some state.
I haven't found any function to order these items.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/6d7c7846-8306-43b8-9c83-409bcc224188)

If i will show these in a board view and will group by state, they will be showed in the wrong order.

### Impact

Better overview

**Comment by artemg2006** [comment]
It would be great to do it like in Notion. Attached a video for an example. Thanks!

https://github.com/AppFlowy-IO/AppFlowy/assets/6279961/92b0f04e-cfca-420a-a4e3-7d409e021854
