### ISSUE TITLE
[FR] Board - Show checkbox title on card

### ISSUE THREAD

**Issue by Schrolli91** [AppFlowy-IO/AppFlowy#3340]
### Description

If i will look at the board view on a single card, i dont know whats the meaning of a checkbox will be.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/c7ae46a3-3388-4af9-a247-ab8383001e34)

If i want to get more information i have to click the item to see its checkbox title:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/68c2ac08-f4b4-447b-96ae-5d28e272c628)

Better is to show the title on a checkbox also on the card view.
Maybe in general its better to show some sort of title to the other fields too? (optional?)

### Impact

More/clear Overview

**Comment by richardshiue** [comment]
This issue has been fixed.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/9f0e073c-34bf-4bca-9815-5b61dafef72d)
