### ISSUE TITLE
[Bug] DB Problem with version 0.3.1

### ISSUE THREAD

**Issue by Cavalletta98** [AppFlowy-IO/AppFlowy#3341]
### Bug Description

Hi, i have updated from version 0.3.0 to 0.3.1. My data disappear. If i go back to version 0.3.0 i get it back. It seems to be some problem of compatibility

### How to Reproduce

Pass from version 0.3.0 to 0.3.1

### Expected Behavior

To see the original data into 0.3.1

### Operating System

Ubuntu 22.04

### AppFlowy Version(s)

0.3.1

**Comment by annieappflowy** [comment]
Thanks @Dialga @Cavalletta98 for reporting!
Looking into it.
@Dialga , which OS do you use?

**Comment by Dialga** [comment]
Mine is Arch Linux x64.

**Comment by LucasXu0** [comment]
@Cavalletta98 @Dialga I have addressed the issue and will provide the new package later. Please don't modify the folder directly.

**Comment by Dialga** [comment]
Hi @LucasXu0, I can confirm that fixes the problem. Thanks!
Ideally there should be a version bump for fixing this major issue.
Also which commit fixed this problem? Because I can't see it.

**Comment by Cavalletta98** [comment]
@LucasXu0 It works, thanks

**Comment by LucasXu0** [comment]
@Dialga This PR. https://github.com/AppFlowy-IO/AppFlowy/pull/3344

I have replaced the existing deb package to prevent more users from downloading the old one.
