### ISSUE TITLE
[FR] Filtering for Calender

### ISSUE THREAD

**Issue by Schrolli91** [AppFlowy-IO/AppFlowy#3345]
### Description

The Grid View will support filtering for some conditions.

It will be nice to see this feature also at boards and calendars to hide some specific items (f.e. the done ones)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/5a807f0f-78c3-4b39-b599-fc8840e2bc32)

Also sorting would be nice on board (per column) and calendar (per day) that we can show High Prio at first for example.

### Impact

Better overview for users

**Comment by annieappflowy** [comment]
Filtering Kanban is supported in v0.5.3
