### ISSUE TITLE
[Bug] Filtering for select box "is not" will hide also empty ones

### ISSUE THREAD

**Issue by Schrolli91** [AppFlowy-IO/AppFlowy#3346]
### Bug Description

If I want to filter this way, it will also hide the empty ones.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/6043382/60cf3b87-262b-4adc-ad65-7efddc1e20ec)

### How to Reproduce

Add an filter and take a look at empty select fields.

### Expected Behavior

IS NOT "done" I will expect, that is see also the empty ones, because

DONE != Empty

### Operating System

Windows

### AppFlowy Version(s)

v0.3.1

**Comment by SaifEl-Deen** [comment]
I can confirm this bug, if I set a filter as "Is not" + Some tag, all entries with this tag will disappear + all entries with empty tag.
