### ISSUE TITLE
[Bug] Erase button ← and Del button both don't work

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#335]
AppFlowy 0.0.3-beta2, Win 8.1 x64

Make note.
Type something at text field.
Try to delete it with button ←
Symbols won't be erased.

Move cursor to first symbol at text field.
Press Del.
Get nothing again.

It's extremely annoying. I can't use this version for note-taking or anything else.

**Comment by Twilightssuperb** [comment]
Suddenly they works after PC reboot... I don't know what it had been happened. (No malware, keylogger or security threats — I use strong Internet security suite by famous vendor with last updates.) Maybe, just weird bug.

**Comment by a-wallen** [comment]
I ran into the same issue. Restarting my computer worked around the issue.

**Comment by Xazin** [comment]
> Del key doesn't work for me even after restart. Version 0.2.5.

What OS are you using?

**Comment by xfactor2000** [comment]
EndeavorOS (arch linux)

**Comment by MayurSMahajan** [comment]
Hey @xfactor2000! Actually, this issue is solved in the AppFlowy Editor, in the next AppFlowy release, the delete functionality will work as intended. Please wait for the next release which is: 0.2.6. Sorry for the inconvenience.

**Comment by MayurSMahajan** [comment]
Hey @xfactor2000! We have solved this issue actually in the AppFlowy editor. In the next release when we update the dependencies of AppFlowy to include the latest AppFlowy release, the delete functionality will work as intended. So you have to wait till we release version 0.2.6. Sorry for the inconvenience.

**Comment by xfactor2000** [comment]
@MayurSMahajan it's a pity such thing persists for so long. I really want to adopt AppFlowy, but there's still many issues to iron out. That said, I also think it's a great product and do hope it will improve soon.

**Comment by MayurSMahajan** [comment]
@xfactor2000 We appreciate your support and patience.

**Comment by annieappflowy** [comment]
Hi @xfactor2000 , could you please write a list of issues that you think we should iron out? This will help us improve under a much rapid pace. Thanks in advance.

**Comment by xfactor2000** [comment]
Hi @annieappflowy, glad you asked.

Here's a couple of things that come to mind:
1. Editor issues (I see the new version with del button fix is out, but haven't got to testing it yet).
2. Pasting things from clipboard
3. PlantUML/kroki support
4. Markdown/Asciidoctor syntax support (at least for importing stuff, as I have many notes in the aforementioned formats).
5. Kanban boards - small things like inability to remove 'No status' column, and custom fields not showing up until you reopen the ticket.
6. Usability issues - like being able to close the opened ticked on `Escape` keypress.
7. Some query language for boards? Although it's complicated.
8. Support for archiving board tickets.

This is not comprehensive, but some of the biggest pet peeves. Hope it helps!

**Comment by MayurSMahajan** [comment]
Delete feature is supported now with the latest release 0.2.6

**Comment by annieappflowy** [comment]
Thanks @xfactor2000 for the feedback. Very much appreciate.
What markdown syntaxes are missing? Here is our markdown[ guidebook](https://appflowy.gitbook.io/docs/essential-documentation/markdown)

**Comment by xfactor2000** [comment]
@annieappflowy asciidoc would be really useful.

**Comment by Twilightssuperb** [comment]
IDK why, but I've just get bug again at 0.3.1 (Win) while typing a text with lots of paragraphs. Buttons have been broken on paragraph 6 sfter some editing.

**Comment by MayurSMahajan** [comment]
@Twilightssuperb did you encounter the bug on a release build or you compiled the latest main app and got the bug.

**Comment by Twilightssuperb** [comment]
@MayurSMahajan, I use Github release.

Noticed another some weird bug with this document — when erasing one symbol, missing not only it but nearby word too...

**Comment by MayurSMahajan** [comment]
@Twilightssuperb Oh I see, which button are you using for erasing, also are you pressing the `Ctrl` key with it? If possible can you share a screen-recording? Thanks!

**Comment by Twilightssuperb** [comment]
@MayurSMahajan, no, just Del and `←`. I can't use video blurring, this doc contains some private data (in Russian). It's Web, I have to be careful nowadays, sorry (I know, u need to reproduce this bug or see it directly). 😅

Maybe, the matter is Russian language in doc, but I'm not sure.

**Comment by Twilightssuperb** [comment]
Seems `←` button works OK at v.0.3.2.
