### ISSUE TITLE
[FR] have a shortcut for text alignment

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3351]
### Description

have a shortcut for text alignment

### Impact

Customers who frequently use text alignments in the editor

**Comment by MayurSMahajan** [comment]
Ideally the following are shortcuts for text alignment:
`Ctrl+L` : align left
`Ctrl+R` : align right
`Ctrl+E` : align center

`Ctrl+E` is already used to format code.
Also on the web, Ctrl+R refreshes the page in the browser.

So I propose we use a new set of shortcuts for text alignment:
`Ctrl+Alt+L` : align left
`Ctrl+Alt+R` : align right
`Ctrl+Alt+E` : align center

This way all our text alignment commands will be uniform and won't interfere with any existing commands.
cc @annieappflowy

**Comment by sherazahmad720** [comment]
@annieappflowy can i work on this?

**Comment by MayurSMahajan** [comment]
Sure! Thanks @sherazahmad720 for helping out.

**Comment by Xazin** [comment]
Hey @sherazahmad720, are you still working on this? Do you need help?

**Comment by sherazahmad720** [comment]
@Xazin Sorry i stuck somewhere if you want you can continue on this

**Comment by annieappflowy** [comment]
We could give you @sherazahmad720  more hints if you're keen to complete it.

**Comment by Xazin** [comment]
> @Xazin Sorry i stuck somewhere if you want you can continue on this

If you still want a go, feel free to mention me on our discord and I will guide you.

**Comment by Jayaprakash-dev** [comment]
Hey @annieappflowy can I work on this?
I've already worked on it, and everything seems to be working smoothly.

One thing to note is that I haven't written a test for it yet. Would that be alright?

**Comment by Xazin** [comment]
> Hey @annieappflowy can I work on this? I've already worked on it, and everything seems to be working smoothly.
> 
> One thing to note is that I haven't written a test for it yet. Would that be alright?

Hey @Jayaprakash-dev , I've assigned you.

Do you need help with adding tests for it? Feel free to mention me on our Discord (I have the same handle as on github) if you need assistance.

**Comment by Jayaprakash-dev** [comment]
Hey @Xazin. Thanks for assigning it to me!

Sure I'll definitely reach out if I encounter any challenges. Could you provide a hint on where I should add the test in terms of the file or module? That would be super helpful.

**Comment by Xazin** [comment]
> Hey @Xazin. Thanks for assigning it to me!
> 
> Sure I'll definitely reach out if I encounter any challenges. Could you provide a hint on where I should add the test in terms of the file or module? That would be super helpful.

Sure thing!

You can add a test for the alignment shortcut in this file: `appflowy_flutter/integration_test/document/document_alignment_test.dart`- It currently holds the corresponding test for the toolbar. You can see how the `expect` is used, it should be similar to the test you will have to write.
