### ISSUE TITLE
[FR] Change text highlighting so it's not as intrusive

### ISSUE THREAD

**Issue by ZibingZhang** [AppFlowy-IO/AppFlowy#336]
At the moment, when highlighting text, it takes some time for the options to appear, and when they do, they take up the entire screen. Overtime, this has become slightly annoying for a couple of reasons. I propose that the design be changed so that it's just a little color selector that appears above the fill / highlight icon near the bar at the bottom.

**1~3 main use cases of the proposed feature, i.e. why change?**

- Highlighting text in the long run gets very tiring. It may only take a moment for the color menu to appear, but over time when I want to highlight lots of text, it gets really annoying that I have to sit through the animation each time.
- I'm unable to see the text that I'm highlighting. Since the entire screen gets blurred, I am unable to see the text that I'm highlighting, if my selection was accurate, etc. From a functionality standpoint, I would hope to able to view the text I'm highlighting while selecting the highlight color.

**what types of users can benefit from using your proposed feature**

- Speed up time of highlighting.
- Ease of use. The whole screen will be visible.

**Comment by gaganyadav80** [comment]
Hi @annieappflowy, it's me again xD. I can improve this one also. We can discuss further on how the resulting widget should be on discord.

**Comment by annieappflowy** [comment]
Hi @gaganyadav80 thanks for offering the help!. @soulisa will help you with the design. I'll take the discussion further on Discord.

**Comment by soulisaye** [comment]
> Hi @annieappflowy, it's me again xD. I can improve this one also. We can discuss further on how the resulting widget should be on discord.

we can take a discussion on discord，my ID is soulisa#4233

**Comment by gaganyadav80** [comment]
Update:
The design is not finalized yet. I will start working on the issue once it will be finalized. 

@annieappflowy Can you assign me another task in the meantime. I will comment on the issue I would like to work on.

**Comment by annieappflowy** [comment]
Ready to start in Q1 2023

**Comment by annieappflowy** [comment]
Upcoming v0.1.3 fixed this
<img width="801" alt="image" src="https://user-images.githubusercontent.com/12026239/233056585-6e35a20f-e2eb-49d7-b40f-ade3ef598c22.png">
