### ISSUE TITLE
[Bug] AppFlowy 3.1 refuses to start

### ISSUE THREAD

**Issue by mskorkowski** [AppFlowy-IO/AppFlowy#3363]
### Bug Description

I'm using flatpak version of the appflowy. After upgrading to 3.1 it refuses to start

### How to Reproduce

Update to flathub version of the appflowy 3.1

### Expected Behavior

It should run

### Operating System

Fedora Silverblue Linux

### AppFlowy Version(s)

3.1

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/90662755/c2c027f1-684a-4a06-ab29-24081508a763)

### Additional Context

If I run appflowy from terminal I get the result shown on the screenshot

Appflowy 3.1 requires `socket=session-bus` in the flatpak sandbox. Enabling it by hand in the flatseal did solve an issue.

**Comment by LucasXu0** [comment]
Hi, @mskorkowski. There's a workaround. `flatpak run --own-name=io.appflowy.appflowy io.appflowy.AppFlowy`.
