### ISSUE TITLE
[FR] Urdu Language

### ISSUE THREAD

**Issue by sherazahmad720** [AppFlowy-IO/AppFlowy#3372]
### Description

With Urdu Language support people From Pakistan can use it easily.

### Impact

All Persons from Pakistan easily use this app. And by adding more language support app look more professional

**Comment by MayurSMahajan** [comment]
Refer here to know more about Translating AppFlowy:
https://docs.appflowy.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/translation

**Comment by vyshaj** [comment]
Hi, I would like to solve this issue. Could you please assign it to me? This is something new to me but I could try to solve it.

**Comment by MayurSMahajan** [comment]
@vyshaj thank you! Assigned.
