### ISSUE TITLE
[Bug] fn not working

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3375]
### Bug Description

I'm using Filco MAJESTOUCH MINILA-R 63 US ASCII Convertibl
To use the navigation arrows, I need to press `fn` + E/S/D/F
In AppFlowy, these keybindings are not working

### How to Reproduce

As described in the bug description

### Expected Behavior

I can use `fn` + E/S/D/F to move the cursor

### Operating System

macOS

### AppFlowy Version(s)

v0.3.1 cloud

**Comment by Ramesh176** [comment]
Can you provide more detail description including screen shots of the page.

**Comment by annieappflowy** [comment]
I might close it once v0.3.2 is out
I can't reproduce in v0.3.2
