### ISSUE TITLE
[FR] Drag and drop a column in the Grid.

### ISSUE THREAD

**Issue by qinluhe** [AppFlowy-IO/AppFlowy#3378]
### Description

1. In the grid view, locate the top header of the column you want to move
2. Hover your mouse over the column's header. You'll notice that the cursor changes to a four-arrow icon, indicating it can be dragged.
3. Click and hold the left mouse button, then drag the column to the desired location.
4. When you've dragged the column to the target position, release the left mouse button, and the column will be placed in its new location.

### Impact

Users who use Tauri desktop

**Comment by fangwufeng-v** [comment]
Got it. It takes about 2 days
