### ISSUE TITLE
[FR] FieldVisibility popup revamp

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3382]
### Description

Currently, we have the following UI to show and hide field visibility. It can be triggered by opening a grid/kanban/calendar, clicking on the settings button on the toolbar, then clicking on Properties.

![Screenshot 2023-09-12 at 6 02 13 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/4ccb443f-861b-44af-a279-7490bc2e2c48)

There are a few problems:

- no drag thumb means that a message is necessary to communicate to users that the field is draggable
- while dragging, a ghost of the dragged field is shown in the `ReorderableColumn` but so is the original field.

We'd like to use this UI instead:

![Screenshot 2023-09-12 at 6 05 10 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/0539f27c-8780-42c3-bdf5-402546cb6d5c)

hint: ReorderableListView

### Impact

Database users

**Comment by RawatDevanshu** [comment]
Hello, can i be assigned on this issue

**Comment by SunilKividor** [comment]
Hey @richardshiue  Can i be assigned to this issue ?

**Comment by richardshiue** [comment]
Assigned, have fun!

**Comment by SunilKividor** [comment]
Hey can you please help me setting up the project ?

**Comment by RawatDevanshu** [comment]
you can follow the instructions here 
[https://docs.appflowy.io/docs/documentation/appflowy/from-source/environment-setup](setup docs)
I followed all instructions and was able to run the project

**Comment by SunilKividor** [comment]
okay thankyou I will surely try

**Comment by SunilKividor** [comment]
@richardshiue I am finding it difficult to clone , It is taking more than enough time to clone

**Comment by richardshiue** [comment]
Hi @SunilKividor, please take your time. If you need additional help, feel free to reach me on Discord. My username is the same.

**Comment by SharmaDhruv2511** [comment]
I want to work on this issue.  If you can assign me, it would be great. @richardshiue
