### ISSUE TITLE
[Bug] Minimum width for grid fields

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3388]
### Bug Description

If you resize a grid field, you can see that you can actually make the so small that you can't actually use it any more. This is not ideal and it would be much better if a minimum width is set for grid fields (e.g. 50px) such that you can shrink the field beyond that point.

### How to Reproduce

1. Open a grid that contains some fields
2. Shrink the width of a field
3. Observe that you can make it infinitesimally small

### Expected Behavior

There is a minimum width

### Operating System

All platforms

### AppFlowy Version(s)

0.3.1

**Comment by Nitin-Poojary** [comment]
I want to take this issue.

**Comment by Nitin-Poojary** [comment]
I have created a draft PR addressing this issue. Please take a look at it and let me know if I have to write test for it.

**Comment by richardshiue** [comment]
Hi @Nitin-Poojary, sure thing! I've assigned it to you.
