### ISSUE TITLE
[Bug] divider between new page and trash does not stretch to edge of sidebar

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3389]
### Bug Description

Title says all.

Please make sure that while fixing this, the rest of the sidebar UI doesn't change

### How to Reproduce

1. Open AppFlowy.

### Expected Behavior

The divider should start from the edge of the window and extend to the edge of the sidebar

### Operating System

macOS

### AppFlowy Version(s)

0.3.1

### Screenshots

![Screenshot 2023-09-12 at 9 29 24 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/6dfe6c00-5956-488d-9d01-d838e680ddb3)

**Comment by Abhineya** [comment]
assign this task to me @MayurSMahajan

**Comment by richardshiue** [comment]
Assigned! Have fun

**Comment by SharmaDhruv2511** [comment]
is this issue currently open or anyone working on it?? I want to contribute to it.

**Comment by rituraj2000** [comment]
@MayurSMahajan Could you please assign it to me ?

**Comment by Kritarthsharma** [comment]
Hi Team. I have worked on a fix for this. Please assign this to me.
