### ISSUE TITLE
[Bug] Missing white space between text of a primary field and the row's icon

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3390]
### Bug Description

Title says all. The lack of whitespace makes the cell look cramped.

### How to Reproduce

1. Open an AppFlowy grid
2. Open a row as a page
3. Add a title to the row
4. Add an icon to the row
5. Close the popup
6. Observe that there is no space between the icon and the title 

### Expected Behavior

A 6px space between the icon and the title

### Operating System

macOS

### AppFlowy Version(s)

0.3.1

### Screenshots

![Screenshot 2023-09-12 at 9 36 10 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/0f8d8196-f29e-45c0-8031-fd4ac7f05df2)

**Comment by onyicodes** [comment]
Hi @richardshiue, I would like to take on this issue please can you assign it to me? Thanks

**Comment by 1akhanBaheti** [comment]
Hi @richardshiue, I would like to work on this.

**Comment by MayurSMahajan** [comment]
@Abhineya since you have other issues assigned, I request you to let this one go to @onyicodes.
@onyicodes you are assigned.
@1akhanBaheti please can you take a look at other issues, thanks!

**Comment by onyicodes** [comment]
Thanks @MayurSMahajan

**Comment by 0xJaskeerat** [comment]
Can you assign me this @richardshiue , I have setup the project , would love to contribute to this
