### ISSUE TITLE
[Bug] Visual bug on board accessory

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3391]
### Bug Description

The discontinuous border presents a lack of polish.

### How to Reproduce

1. Open a kanban board
2. Hover over a card.
3. Observe that the border of the card accessories "break" at the corners

### Expected Behavior

The rounded border should be visible

### Operating System

macOS

### AppFlowy Version(s)

0.3.1

### Screenshots

![Screenshot 2023-09-12 at 9 46 52 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/08f36bcc-df43-42de-a973-f3bc91fd02cb)

**Comment by onyicodes** [comment]
Hi @richardshiue, it's been a long while. I will like to take on this issue please can you assign it to me? Thanks

**Comment by richardshiue** [comment]
Hey there @onyicodes, welcome back! Thanks Mayur for assigning

**Comment by onyicodes** [comment]
Thanks @richardshiue and @MayurSMahajan. Glad to be back
