### ISSUE TITLE
[Bug] Can run docker on arm64

### ISSUE THREAD

**Issue by cybr-dev** [AppFlowy-IO/AppFlowy#3400]
### Bug Description

When trying to run the docker image on my arm64 server I get the following error:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Is there a way to get this docker contianer running on arm64?

### How to Reproduce

Run docker container on arm64

### Expected Behavior

Container should start

### Operating System

Ubuntu 22.04LTS

### AppFlowy Version(s)

latest

**Comment by annieappflowy** [comment]
https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy
would you like to try this ^
we now support self-hosting AppFlowy
