### ISSUE TITLE
[Bug] Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by litaipo** [AppFlowy-IO/AppFlowy#3407]
### Bug Description

2023-09-14 21:48:21.297 xcodebuild[93313:453353] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008112-001469023C03401E }
{ platform:macOS, arch:x86_64, id:00008112-001469023C03401E }
Undefined symbols for architecture arm64:
  "_link_me_please", referenced from:
      _$s16appflowy_backend21AppFlowyBackendPluginC28dummyMethodToEnforceBundlingyyFZ in appflowy_backend(AppFlowyBackendPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/Users/lijing/CodeProjects/AppFlowy-0.3.1/frontend/appflowy_flutter/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'ReachabilitySwift' from project 'Pods')
** BUILD FAILED **

### How to Reproduce

1. source:AppFlowy-0.3.1 
2. build all
3. build dart only

### Expected Behavior

success

### Operating System

platform:macOS, arch:arm64

### AppFlowy Version(s)

0.3.1

**Comment by LucasXu0** [comment]
Hi, @litaipo. Sometimes, you may have built the Rust library with x86_64 architecture. In such cases, you should try cleaning and rebuilding.
