### ISSUE TITLE
[Bug] Updating icon of a row does not change the last modified value

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3409]
### Bug Description

When a cell of a row is changed, a notification is sent not only to the field to which it belongs to, but also last-modified fields. However, changing the icon of the row doesn't do this, and this isn't ideal.

NOTE: Compared to most other issues tagged with "hacktoberfest", this issue is a bit more involved since you would need to understand the rust backend. If you are looking for an issue to get your hands dirty, I suggest looking for another issue to tackle.

### How to Reproduce

1. Open a grid
2. Create a last modified field and note the current value of the cell
3. Wait for a minute or two
4. Open the first row as a page, hover over the header area and add an icon
5. Close the row detail page
6. Observe that the timestamp value hasn't changed

### Expected Behavior

It should be updated

### Operating System

macOS

### AppFlowy Version(s)

v0.3.1

**Comment by kurokochin** [comment]
Hi @richardshiue! I'm interested in this issue, but I'm having difficulties to reproduce step 4-6, do you mind to share more detail?

**Comment by richardshiue** [comment]
I meant pressing the "Add icon" button here

![Screenshot 2023-10-03 at 6 19 50 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/e87a134e-4275-4b2c-8aa8-aa94266c3287)
