### ISSUE TITLE
[Bug] The placeholder text for URL cells shouldn't be underlined

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3411]
### Bug Description

Please make a check for whether the URL cell data is empty before setting the underline flag to be true.

![Screenshot 2023-09-15 at 3 44 50 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/153e499e-2dce-449c-bf8d-4ef5721daadb)

### How to Reproduce

1. Open a grid
2. Create a URL field
3. Open the first row as grid
4. Observe that the placeholder "Empty" text is underlined

### Expected Behavior

It shouldn't be

### Operating System

macOS

### AppFlowy Version(s)

0.3.1

**Comment by Abhineya** [comment]
assign this issue to me

**Comment by ahsanahmad4654** [comment]
Hey, @richardshiue  are you able to assign this one to me to work on?

**Comment by richardshiue** [comment]
Hey there @ahsanahmad4654, would you like to work on this?

**Comment by ahsanahmad4654** [comment]
yes, @richardshiue , i would love to work on it

**Comment by ahsanahmad4654** [comment]
@richardshiue Please review the PR.

**Comment by ahsanahmad4654** [comment]
I had fixed this issue and raised the PR. Please review it @richardshiue
