### ISSUE TITLE
[Bug] Can't get "a" (Latin/English) in page name when creating it

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#3420]
### Bug Description

See above

### How to Reproduce

1. Let's make a new page.
2. Get popup naming menu.
3. Press small "a" manually or from virtual keyboard.
4. Get all text selected instead of typed letter — or nothing if name field is empty.
5. Pressing "a" with Shift button or Caps Lock works OK — big A appears in name.

### Expected Behavior

The small "a" key should be processed as usual.

### Operating System

Win 8.1 x64

### AppFlowy Version(s)

0.3.1 (x86_64 ZIP-version from Github)

### Additional Context

[BTW](https://github.com/AppFlowy-IO/AppFlowy/issues/335#issuecomment-1708718124)

**Comment by Twilightssuperb** [comment]
BTW, @LucasXu0 or someone else, please, look at [mentioned comment](https://github.com/AppFlowy-IO/AppFlowy/issues/335#issuecomment-1708718124) from my very old issue. I still have weird bug with erasing button `←`, when I press it once, it erases whole word, not one symbol. There was some newer discussion at that issue, so I decided not to start new issue

**Comment by annieappflowy** [comment]
@Twilightssuperb still having this issue?

**Comment by Twilightssuperb** [comment]
Yep, still actual for 0.3.9 x64 Win. ☹
