### ISSUE TITLE
[Bug] Border loses thickness after "New property" ends in Grid

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3421]
### Bug Description

Under the `Filter`, `Sort` and `Settings` in a Database/Grid, the border is less thick than the one where there are columns in the Grid.

This misalignment feels weird.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/fa5d265f-07d5-45be-bcc8-5833a40c21e5)

### How to Reproduce

1. Open AppFlowy
2. Create a Grid/Database
3. See the thickness of the border becoming thinner after the `New property` cell

### Expected Behavior

1. Open AppFlowy
2. Create a Grid/Database
3. The thickness of the divider between the top bar and the header row is the same

### Operating System

*

### AppFlowy Version(s)

0.3.1

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/c7315e34-6132-497b-81c9-8c58d62a6a91)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/de49219f-1463-439c-9f23-df2572c190c7)

### Additional Context

_For solution guidance, join our discord and mention me!_

**Comment by richardshiue** [comment]
Seconded. Do note that while fixing this bug, make sure that when there is a filter, there should still be a separator!

**Comment by narayann7** [comment]
@Xazin hey, can you assign me this issue?

**Comment by nikhilgarg26** [comment]
hey @Xazin i would like to take up this issue, can you please guide how to start with this issue it would be a great help

**Comment by MayurSMahajan** [comment]
Hey @nikhilgarg26 I have assigned this one to @narayann7, can you please take a look at some other issues we have to solve. Thanks

**Comment by Xazin** [comment]
> @Xazin hey, can you assign me this issue?

If you need any assistance please let us know! :+1:

**Comment by narayann7** [comment]
@Xazin sure, i will let you know

**Comment by narayann7** [comment]
@Xazin i tried to adjust the size of divider and grid cell, still it will difficult to make them same but i think we cant use both divider and grid cell border at a time

**Comment by Xazin** [comment]
> @Xazin i tried to adjust the size of divider and grid cell, still it will difficult to make them same but i think we cant use both divider and grid cell border at a time

Hey Narayan, it's definitely possible.

Here are some hints:
- Have you tried to remove _only_ the top border of the cell field? (`field_cell.dart`)
- The `New property` button also has it's own top border, track it down and remove _only_ the top one. `grid_header.dart`
- Now as Richard mentioned, the filter/sort menu needs to have the bottom border, I'll let you play with this yourself, I'll give you the file though: `setting_menu.dart`

Let me know if you still need more help! :+1:

**Comment by narayann7** [comment]
@Xazin sure, yes we can remove the top border of the cell but when we click on filter then we have to show the border, i will go through this case and i will let you know, thank you

**Comment by Xazin** [comment]
> @Xazin sure, yes we can remove the top border of the cell but when we click on filter then we have to show the border, i will go through this case and i will let you know, thank you

The solution I explained above takes care of this case.

**Comment by Xazin** [comment]
Hey @narayann7, since you haven't made progress, I'll take over this issue and resolve it :+1:
