### ISSUE TITLE
[Bug] Remove max length of 30 while creating a new select option in the header

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3425]
### Bug Description

A while back, we received a request to remove the then-existing 30-character cap on the length of an option in a single-select or multi-select field, and we've incorporated that change. When you click on a cell in a select option cell, you will no longer find that max length restriction.

However, this still exists in the field's header, as pictured below.

<img width="491" alt="Screenshot 2023-09-17 at 7 58 14 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/767d821a-04ad-4b70-b73f-f733b44607ef">

Please remove this restriction so that users can create their special-options-with-exceptionally-long-names.

### How to Reproduce

1. Open a new grid
2. Click on the field header titled "Type"
3. Click on add option
4. Observe that there is a counter at the end of the text field, and that you can't enter more than 30 characters into it.

### Expected Behavior

There shouldn't be a restriction

### Operating System

macOS

### AppFlowy Version(s)

0.3.1

**Comment by ahsanahmad4654** [comment]
Hey @richardshiue  are you able to assign this one to me to work on?

**Comment by richardshiue** [comment]
Assigned, have fun!
