### ISSUE TITLE
[Bug] Tiny padding between field name text field and field type selector button

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3426]
### Bug Description

There should be a 12 px vertical whitespace between. The current 4px is awfully cramped.

<img width="491" alt="Screenshot 2023-09-17 at 8 04 26 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/d76a3263-ade7-48bf-9368-87b4133b5338">

### How to Reproduce

1. Open a grid
2. Click on the field header of any field
3. Click on edit field
4. Observe that the spacing is tiny

### Expected Behavior

There should be ample spacing between the field name textfield and the field type button

### Operating System

macOS

### AppFlowy Version(s)

0.3.1

**Comment by Xazin** [comment]
I think 12px is a bit overkill.. maybe 8px?
