### ISSUE TITLE
[Bug] Missing space between Card Actions

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3428]
### Bug Description

When a card is open, you have two actions to the right, `Delete` and `Duplicate`.

Between these two actions, there is no space, according to the design specification, there should be a vertical space of 8 px between actions.

Add this space using eg. the `VSpace(8)` or `Padding` widget.

### How to Reproduce

1. Open AppFlowy
2. Open a Board or Database/Grid
3. Open an item in Card view
4. Hover `Delete` and `Duplicate` and see there is no space between

### Expected Behavior

8 pixel space between the actions

### Operating System

all

### AppFlowy Version(s)

0.3.1

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/bdd4372e-edef-463f-bd74-c540ba9d3782)

**Comment by richardshiue** [comment]
I remember adding a 4px spacing between the two in accordance to the design doc 🤔

**Comment by Xazin** [comment]
> I remember adding a 4px spacing between the two in accordance to the design doc 🤔 

Will check on main, was doing this on 0.3.1.

**Comment by ahsanahmad4654** [comment]
Hey @Xazin you able to assign this one to me to work on?

**Comment by Xazin** [comment]
> Hey @Xazin you able to assign this one to me to work on?

Hey Ahsana, this is already resolved.
