### ISSUE TITLE
[Bug] RecordNotFound after adding a board view, deleting a view and adding it again

### ISSUE THREAD

**Issue by yuuz233** [AppFlowy-IO/AppFlowy#3435]
### Bug Description

Cannot display board view correctly.

### How to Reproduce

Add a calendar from a document
Add a board view (don't change anything, name or properties)
Delete the board view
Add a board view

Showing RNF error code.

### Expected Behavior

Should show a new board view correctly.

### Operating System

Windows 10 LTSC 21H2

### AppFlowy Version(s)

0.3.1

**Comment by yuuz233** [comment]
upd: not fixed in 0.3.2.

**Comment by Xazin** [comment]
I can't reproduce in 0.5.0 on MacOS, is this still an issue?
