### ISSUE TITLE
[Bug] The mouse cannot copy strings arbitrarily

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#3438]
### Bug Description

The mouse cannot copy strings arbitrarily，only use keyboard shift+ left and right

### How to Reproduce

Edit text arbitrarily
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/3f4706ae-c350-47ab-9f78-117fe57d075e)

### Expected Behavior

When I copy a short paragraph, the selection starts from the first character

### Operating System

windows 10

### AppFlowy Version(s)

Appflowy 0.3.2

**Comment by annieappflowy** [comment]
I can't reproduce this issue using the latest. Please feel free to reopen the issue if it persists
