### ISSUE TITLE
[FR] Ability to re-order sorts

### ISSUE THREAD

**Issue by Hexara7777** [AppFlowy-IO/AppFlowy#3442]
### Description

When I create multiple sorts, there is no ability to re-order them.

### Impact

If I changed my mind from:
1. Date sort as a primary sort
2. Status sort as a secondary sort

To:
1. Status sort primary sort
2. Date sort secondary sort

I have to delete the first one then re-add it so it appears as the second one.

**Comment by annieappflowy** [comment]
<img width="373" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/34b4e749-9371-4175-a8a1-f04eaa5a9efc">

@Hexara7777 , the proposed feature was completed. Please try it out with the latest release.
