### ISSUE TITLE
[Bug] In grid view, modifying a filter will mess the sorts

### ISSUE THREAD

**Issue by Hexara7777** [AppFlowy-IO/AppFlowy#3443]
### Bug Description

I set a date sort in a grid view, when I add a filter for a Checkbox property then modify that filter, the Date sort doesn't work anymore, I have to either modify the Date sort from ascending to descending then back again or close the app and re-open it.

### How to Reproduce

1. Create a date sort
2. Create a Checkbox filter
3. Modify the checkbox filter criteria
4. Date sort doesn't work anymore
5. Works again by closing and app and re-opening it

### Expected Behavior

Filters shouldn't affect sorts

### Operating System

Windows 11 Home

### AppFlowy Version(s)

0.3.2.0

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/130001839/b54f86a2-fe7d-480e-a92b-584f281ad167)

**Comment by annieappflowy** [comment]
This issue was resolved.
