### ISSUE TITLE
[Bug] Deleted sorts won't be available to re-choose until app restart

### ISSUE THREAD

**Issue by Hexara7777** [AppFlowy-IO/AppFlowy#3444]
### Bug Description

Described in reproducing steps

### How to Reproduce

1. Add a sort
2. Delete that sort
3. You won't find it again in the Add sort menu until you restart the app

### Expected Behavior

Ability to find deleted sorts after deleting them

### Operating System

Windows 11 Home

### AppFlowy Version(s)

0.3.2.0

### Additional Context

It happens randomly, not all the time.

**Comment by Xazin** [comment]
I don't seem to be able to reproduce this on MacOS in v0.4.6.

Do you know if this has been resolved already @richardshiue ?

**Comment by richardshiue** [comment]
Steps to reproduce (copied from above PR):

1. Create a sort on a field
2. Switch to a different document/database and come back
3. Delete that sort
4. Attempt to create a sort on that same field.
