### ISSUE TITLE
[Bug] Last modified property is not available for sorting

### ISSUE THREAD

**Issue by Hexara7777** [AppFlowy-IO/AppFlowy#3445]
### Bug Description

I can't find any Last modified properties in the sorting menu.

### How to Reproduce

1. Add a Last modified property
2. Try to add a sort for it
3. You won't find it in the sort menu

### Expected Behavior

To be able to sort by Last modified property type

### Operating System

Windows 11 Home

### AppFlowy Version(s)

0.3.2.0

**Comment by richardshiue** [comment]
Closing as completed via https://github.com/AppFlowy-IO/AppFlowy/pull/4601
