### ISSUE TITLE
[Bug] Spacing above "New row" in grid

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3446]
### Bug Description

Currently, the "New row" button in the grid, is just below the last row, this seems good when the button is not hovered on, but doesn't seem great with hover.

We should add 8px spacing between the last row and the `New row` button.

### How to Reproduce

...

### Expected Behavior

8px spacing

### Operating System

all

### AppFlowy Version(s)

0.3.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/040ebd0c-fbde-4abe-9693-502d2aaa3c65)

**Comment by shadan1234** [comment]
Can i solve this issue using Flutter

**Comment by Xazin** [comment]
> Can i solve this issue using Flutter
> 
> 

Yeah, it is pure flutter. Do you want me to assign you?

**Comment by shadan1234** [comment]
Yeah i want to learn. please assign me

**Comment by Xazin** [comment]
> Yeah i want to learn. please assign me

Sure thing, feel free to reach out to us on Discord if you need assistance, feel free to mention me on Discord `@Xazin` :+1:

**Comment by shadan1234** [comment]
Hey how to find your Discord channel and which files has this issue of spacing ,
Actually i needed certain assistance because backend is not there and it is showing me 6k errors

**Comment by annieappflowy** [comment]
@shadan1234 , in this case, you should set up the environment and successfully run AppFlowy on your computer first before asking for an issue to work on.
I'll just undo the assign for now. Once you are ready, please feel free to find your first issue to work on.

**Comment by ahsanahmad4654** [comment]
Hey @Xazin you able to assign this one to me to work on?
