### ISSUE TITLE
[Bug] Count number should have different color than label

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3447]
### Bug Description

In a Grid, we have the `Count` at the bottom of the view. The number should be a different color than the `Count` label itself.

Introduce a color variable for theming and use it for the number.

The color for dark mode is: `#00BCF0` (Dark Primary)
The color for light mode is: `#000000` (Black)

### How to Reproduce

Add a Grid and add rows, see the Count at the bottom, the number is the same color as the label

### Expected Behavior

Add a Grid and add rows, see the Count at the bottom, the number should have the correct color

### Operating System

all

### AppFlowy Version(s)

0.3.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/b889570b-d587-47d0-8b35-d724b0758779)

**Comment by 1akhanBaheti** [comment]
Hi @Xazin,
I would like to work on it, can you assign this to me ?

**Comment by 1akhanBaheti** [comment]
![appflowy_dandelion](https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/8e9371cc-331e-4e9d-9564-32b9d2b2e1fb)
![appflowy_default_theme](https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/39ffab8d-fc21-4281-b09c-dff866b0f6d6)

### **I have acheived the expected,**
by adding one more parameter in AFThemeExtension class, is this is the correct way ?

![Screenshot (33)](https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/0195d55e-8292-4567-aaf6-6238fbb1ef98)
