### ISSUE TITLE
[Bug] Grid Row Actions is using wrong SVG

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3450]
### Bug Description

In the grid, when hovering a Row, there is a visible drag handler. Currently, the drag handler is 2 dots, which is the wrong asset.

It should be the same as in the document, the 6-dot version.

### How to Reproduce

1. Add Grid
2. Hover row
3. Observe Wrong SVG

### Expected Behavior

1. Add Grid
2. Hover row
3. Observe Correct SVG

### Operating System

all

### AppFlowy Version(s)

0.3.2

### Screenshots

**Current:**
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/d30357a9-46d4-4c2e-bccd-2f38305ba650)

**Expected:**
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/dc7a7177-c58d-4dfa-a2a0-f698358ddafd)

**Comment by DeveloperMalay** [comment]
hi there can I work on this issue?

**Comment by Xazin** [comment]
> hi there can I work on this issue?

Hey Malay, sure thing!

If you need any assistance feel free to hit me up on Discord :+1:

**Comment by DeveloperMalay** [comment]
ok Xazin thank you

**Comment by DeveloperMalay** [comment]
Xazin can you please help me set up the project locally I'm having some issues during setup.

**Comment by DeveloperMalay** [comment]
ok sure

**Comment by SharmaDhruv2511** [comment]
Hi, I want to work on this issue. Can you please assign me?

**Comment by DeveloperMalay** [comment]
@Xazin I am having some problems working on this issue please assign @SharmaDhruv2511 for the task.

**Comment by MayurSMahajan** [comment]
What are your problems, if you want dm me on discord, maybe we can work something out.

**Comment by DeveloperMalay** [comment]
@MayurSMahajan  Actually I am having some difficulties to setup the project locally. also can't able to create the generated files.

**Comment by MayurSMahajan** [comment]
Which OS are you using?

**Comment by DeveloperMalay** [comment]
I messaged you on Discord let's talk there.

**Comment by SharmaDhruv2511** [comment]
If nobody is working on it, can you please assign me the task??
