### ISSUE TITLE
[Bug] Number type label is too similar to the buttons

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3452]
### Bug Description

Inside a Grid, when editing a property, if you select "Number" as the type, you can select the "Number format", the label for this looks exactly the same as the below button which lets you select the actual format.

There should be more distinction between these so that it's easily visible that it's a label and not a button.

The other types do not have labels.

### How to Reproduce

1. Add a Grid
2. Change the type of any property to number
3. When editing a Number property, try to hover the "Number format" and see it's not a button.a 

### Expected Behavior

1. Add a Grid
2. Change the type of any property to a number
3. When editing a Number property, be able to easily recognize that "Number format" is a label

### Operating System

all

### AppFlowy Version(s)

0.3.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/7d77b568-9d6d-411b-890f-c12d0b7f096f)

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/4fc98850-5c04-4a3e-a135-119fed3e5682)

**Comment by SharmaDhruv2511** [comment]
Hi I want to work on this issue, Can you please assign me??

**Comment by Xazin** [comment]
> Hi I want to work on this issue, Can you please assign me??
> 
> 
> 
> 

Assigned! Let me know if you need any assistance.

**Comment by SharmaDhruv2511** [comment]
Hi, I have a question. When we select the number type it should be able to show the Number and its format right?? For example 
I select the number property and in the grid it should be label as "Number(US Dollar)". Am I right?
