### ISSUE TITLE
[Bug] Settings > Properties - Not working 

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3456]
### Bug Description

When in a Board/Grid/Calendar view, we have the `Settings` in the top right, when pressing this and going to `Properties`, you see a list of all current properties.

You should be able to press on a Property to edit it, but doing this does nothing. A small overlay flickers at the top left of the window.

### How to Reproduce

1. Add or navigate to any Grid/Calendar/Board
2. Press the `Settings` button in the top right
3. Press the `Properties` button
4. Press any Property to edit the property
5. Overlay flickers but no "Edit property"-menu opens

### Expected Behavior

1. Add or navigate to any Grid/Calendar/Board
2. Press the `Settings` button in the top right
3. Press the `Properties` button
4. Press any Property to edit the property
5. "Edit property"-menu shows

### Operating System

Windows

### AppFlowy Version(s)

0.3.2

### Screenshots

Sadly the recording software I used here does not show the flickering, but none the less shows the lack of action:

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/201e8563-844f-4f8c-a085-40a444a5eedd

**Comment by nk3z** [comment]
The same thing happens in linux flatpack
