### ISSUE TITLE
[Bug] Hide/show icon in `Settings > Properties` is too small

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3457]
### Bug Description

In a Board/Grid/Calendar, when pressing the `Settings` in the top right, and then `Properties`, you can press on the `Hide` or `Show` action to the right of a property, this icon button is way too small, making it really hard to make out what the icon even is.

Increase the size of the Icon button to the same as the icon on the left of the property (the type icon)

### How to Reproduce

1. Add or navigate to a Grid/Board/Calendar
2. Press `Settings` in the top right corner
3. Press `Properties`
4. Observe the icon on the right of the properties, it is an icon button that is clickable, but it's way too small to see what it is

### Expected Behavior

1. Add or navigate to a Grid/Board/Calendar
2. Press `Settings` in the top right corner
3. Press `Properties`
4. Easily notice the button to the right and see what the icon is

### Operating System

All

### AppFlowy Version(s)

0.3.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/f87116b8-f025-4be4-b18b-e6bf2a0a2595)

**Comment by 1akhanBaheti** [comment]
Hi @Xazin,
I would like to work on it, can you assign this to me ?

**Comment by Xazin** [comment]
> Hi @Xazin, I would like to work on it, can you assign this to me ?

Hi, sure thing!

I've assigned you, let me know if you need help! Feel free to hop on our Discord, it's really convenient to provide guidance there. :+1:

**Comment by 1akhanBaheti** [comment]
Hi @Xazin,
I have fixed this issue, can you check this once.
