### ISSUE TITLE
Cannot Deploy appflowyio/appflowy_client to DigitalOcean

### ISSUE THREAD

**Issue by spenceratwatson** [AppFlowy-IO/AppFlowy#3460]
### Bug Description

2023-09-19T22:17:08.264816642Z 
2023-09-19T22:17:08.264870079Z (app_flowy:1): Gtk-WARNING **: 22:17:08.264: cannot open display: 
The build was skipped for component "appflowyio-appflowy-client"

### How to Reproduce

Create a new DigitalOcean App and create resource Docker Hub.

### Expected Behavior

This should deploy a working version.

### Operating System

linux/amd64

### AppFlowy Version(s)

0.3.2

**Comment by annieappflowy** [comment]
Hi @spenceratwatson , wanna give this a try https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy
