### ISSUE TITLE
[FR] Create a step-by-step video tutorial on how to set up the development environment

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3473]
### Description

Requirements: 
- one video for each operating system
- before working on it, create a separate issue for this task and indicate what OS you will be working with
- once you're assigned, you may start the work

### Impact

Help first-timers to set up the development environment

**Comment by MayurSMahajan** [comment]
Hi @annieappflowy, I can work on a video for Windows 11. 
I also wanted to ask you where will this video be published?

**Comment by annieappflowy** [comment]
Thanks @MayurSMahajan 
Can be a file or published on YouTube
We can then insert the file or the link into our documentation

**Comment by narayann7** [comment]
hey, @annieappflowy i can work on the video for mac os (M2). should it require audio too?

**Comment by annieappflowy** [comment]
Hi @narayann7 , it's up to you!

**Comment by AmanSikarwar** [comment]
Hi @annieappflowy, I can work on a video for Linux.

**Comment by annieappflowy** [comment]
Please create a separate issue for the linux video @AmanSikarwar 
I'll then assign it to you
