### ISSUE TITLE
[FR] Embeds Block Component - Github Preview

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3474]
### Description

- [ ] convert the GitHub link to embed block after pasting.
- [ ] support inserting a GitHub embed via a slash command.
- [ ] support turning the GitHub embed back link.
- [ ] show tips or error messages if not authorized.

### Impact

for the users who want to preview the GitHub content

### Additional Context

UI Example

<img width="737" alt="Screenshot 2023-09-20 at 21 09 55" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/3b142359-8ee1-4d26-af66-a52735df94d5">

**Comment by balogun14** [comment]
@LucasXu0 can you explain a bit more

**Comment by AlvBarros** [comment]
Using this issue to understand AppFlowy's architecture better. Working on a fork on appflowy-editor

**Comment by AlvBarros** [comment]
My understanding is that when you type "/" or paste a Github.com link, the 'embed github' component should show up.
