### ISSUE TITLE
[Bug] Missing the hand gesture icon in the text alignment options

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3475]
### Bug Description

<img width="121" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/11ed40aa-1932-4b97-92c7-7ca5f1cddd83">

Hovering on left, center, or right shows a pointer rather than a hand

### How to Reproduce

Selecting a piece of text to trigger the format menu
Click on the text alignment
Hover on any alignment options

### Expected Behavior

Making it Consistent with other options by showing a hand gesture icon when hovering on any alignment options (left, center, and right)

### Operating System

macOS

### AppFlowy Version(s)

v0.3.2

**Comment by 1-ankush-1** [comment]
.take

**Comment by narayann7** [comment]
@annieappflowy Hey, I would like to take this fix this issue

**Comment by MayurSMahajan** [comment]
Have fun!
