### ISSUE TITLE
[FR] Add a copy button to the top-right corner of the code block.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3478]
### Description

- only show the copy button when hovering on the code block

### Impact

It would be more convenient to copy the code from the code block without having to select it all.

### Additional Context

Please refer to the implementation of the menu of the image block

**Comment by MayurSMahajan** [comment]
Hey Lucas, actually I have made this feature already in my project (the Standalone Codeblock package).
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/63883556-9747-4472-98d7-58c9935a7d45)

**Comment by Xazin** [comment]
Hey @MayurSMahajan, will you be opening a PR for this? 😄

**Comment by MayurSMahajan** [comment]
Yes sir. It's ready in my CodeBlock project. I am currently adding the CodeBlock package to AppFlowy. Within this week you ll have a big PR to review 😁

**Comment by Xazin** [comment]
> Yes sir. It's ready in my CodeBlock project. I am currently adding the CodeBlock package to AppFlowy. Within this week you ll have a big PR to review 😁

Looking forward to that haha :D :+1:
