### ISSUE TITLE
[FR] Edit the field by clicking on the drag icon

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3479]
### Description

When you click on the draggable thumb, a popup of the field editor should appear. The field editor should be the exact same one that you'd get if you were to click on the field button just to the right. Please add the necessary hover effects as well.

<img width="431" alt="Screenshot 2023-09-20 at 10 34 06 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/81b86151-b7ec-4f92-bfa0-187922268371">

### Impact

Row detail page users

**Comment by Nitin-Poojary** [comment]
> The field editor should be the exact same one that you'd get if you were to click on the field button just to the right.

Can you please elaborate on this?

**Comment by ekakshjanweja** [comment]
Hi, I was wondering if I could work on this issue.

**Comment by richardshiue** [comment]
@Nitin-Poojary something like this, but different menu and this one is in the document.

@ekakshjanweja Sure! I have assigned it to you.

**Comment by ekakshjanweja** [comment]
@richardshiue So I was looking around the codebase do you have any hints for me on where I should look? This may be unusual to ask in open-source projects but here goes nothing. Thanks for the help though.

**Comment by richardshiue** [comment]
@ekakshjanweja yep sure! You can look for something called a `RowDetailPage`

**Comment by ekakshjanweja** [comment]
I finally found something basically we need a popup menu thing here. 
Now I will find where this menu has been implemented already and then see where things move forward from there.
Will ask for help if needed.

https://github.com/AppFlowy-IO/AppFlowy/assets/73514964/69461455-50fa-4f55-8eb0-c31e58b1bec9

**Comment by AdiAr11** [comment]
Hi @ekakshjanweja , are you still working on it?

**Comment by ekakshjanweja** [comment]
> Hi @ekakshjanweja , are you still working on it?

Yes I am i have got mid semester exams this week but I I am still working on this 😊

**Comment by ekakshjanweja** [comment]
@richardshiue I was able to make this does this look good?

https://github.com/AppFlowy-IO/AppFlowy/assets/73514964/faa1b9a3-915e-4bd2-97e5-746ad02d39d9

**Comment by ekakshjanweja** [comment]
@richardshiue I just created this PR. Just tell me if you want anything changed. Thanks for all the help and support till now.
https://github.com/AppFlowy-IO/AppFlowy/pull/3656

**Comment by ekakshjanweja** [comment]
@richardshiue should we close this issue?

**Comment by richardshiue** [comment]
Yes, thanks for the reminder
