### ISSUE TITLE
[FR] apply a corner radius to the selection area.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3480]
### Description

<img width="203" alt="Screenshot 2023-09-20 at 22 39 57" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/e6c51450-d303-494e-9935-2cf219972e87">

### Impact

It would appear more user-friendly with a corner radius.

**Comment by noelg-cj** [comment]
Hey! I would like to take this fix

**Comment by Xazin** [comment]
> Hey! I would like to take this fix

Hi Noel, I've assigned you. Let us know if you need help or have any problems.

**Comment by noelg-cj** [comment]
Thanks!

**Comment by Mandeep56Singh** [comment]
are you still working on it

**Comment by k22sumit** [comment]
is this issue still open?

**Comment by 0xJaskeerat** [comment]
Hey @MayurSMahajan , if @noelg-cj is not able to progress, can you please assign this to me so that I can try my hands on this

**Comment by MayurSMahajan** [comment]
Sure, since @noelg-cj hasn't contacted after two weeks. You can try your hands on it. Submit a PR directly, I won't be assigning you or anyone this issue.

**Comment by 0xJaskeerat** [comment]
> Sure, since @noelg-cj hasn't contacted after two weeks. You can try your hands on it. Submit a PR directly, I won't be assigning you or anyone this issue.

Cool so would love to discuss this first in detail , for what type of component is this issue for , can you @LucasXu0 give a lil more description  and are you expecting the container of the arrow should have a corner radius ?

**Comment by 0xJaskeerat** [comment]
@LucasXu0 @Xazin @MayurSMahajan Are you guys talking about this selection 

<img width="1440" alt="Screenshot 2023-10-05 at 2 07 22 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/124770018/637f61eb-8bd8-423f-a76f-eb595cfc1509">

The selection area , do you want to make it rounded from all corners ? , I guess in that case the padding would be required to beautify it otherwise it may look lil awful , anyways am open to discussion 
Please list out what you guys think of this

**Comment by 0xJaskeerat** [comment]
> @LucasXu0 @Xazin @MayurSMahajan

@LucasXu0 @Xazin @MayurSMahajan Any updates guys ?

**Comment by LucasXu0** [comment]
@0xJaskeerat Yes. The selection area.

Now
<img width="30" alt="Screenshot 2023-10-13 at 10 08 15" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/ce5019da-5b5b-4b30-b9ad-92b166196c6a">

Expected
<img width="44" alt="Screenshot 2023-10-13 at 10 08 07" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/97ca184b-ea58-4abb-bc8d-263780515130">

**Comment by ShivamMenda** [comment]
@LucasXu0 If this issue is still open can I take it up?

**Comment by zaidhussain2k6** [comment]
Please Assign it to me #3480

**Comment by ekakshjanweja** [comment]
@LucasXu0 is any one working on this>

**Comment by 0xJaskeerat** [comment]
Hey yes am working on this

**Comment by SharmaDhruv2511** [comment]
Hi @LucasXu0 I want to work on this issue. Can you please assign me??

**Comment by Xazin** [comment]
Hey everyone, I've assigned this issue to me for now.

@0xJaskeerat If you still want to submit the PR for this, please hit me up on our discord, and I'll guide you through the implementation. Otherwise I'll have to pick someone else :)

**Comment by 0xJaskeerat** [comment]
> Hey everyone, I've assigned this issue to me for now.
> 
> @0xJaskeerat If you still want to submit the PR for this, please hit me up on our discord, and I'll guide you through the implementation. Otherwise I'll have to pick someone else :)

Hey I still wish to work on this , as I have been banging my head to find a fix for this

 I didn't knew this was supposed to be for a different repo , was thinking it belonged to Appflowy repo only
@richardshiue told me about this

**Comment by 0xJaskeerat** [comment]
Hey @Xazin @LucasXu0 @richardshiue 

Checkout and review this PR to this issue 
https://github.com/AppFlowy-IO/appflowy-editor/pull/556
