### ISSUE TITLE
[FR] support RTL in toolbar 

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3481]
### Description

the items in the toolbar should show from right to left if the layout direction equals RTL. 

**'Aa H1 H2 H3 ...' should become '...  H3 H2 H1 Aa'**

<img width="648" alt="Screenshot 2023-09-20 at 22 46 46" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/5db8b3e2-ccac-4762-b592-0a1349625d7e">

### Impact

more friendly for the RTL users.

**Comment by 1akhanBaheti** [comment]
Hi @LucasXu0,
I have tried to add this feature, can you check this once
https://github.com/AppFlowy-IO/appflowy-editor/pull/496

**Comment by AlvBarros** [comment]
Since this has already been solved, should this issue still be Open?
