### ISSUE TITLE
[FR] A step by step video guide on setting up AppFlowy on Windows 11 X86_64

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3489]
### Description

A video tutorial that walks the viewer through the process of running AppFlowy locally on their machine.

### Impact

Helps new contributors to set up the local environment for running AppFlowy.

**Comment by DevanshuNagpal** [comment]
Can you assign me this?

**Comment by MayurSMahajan** [comment]
Hi @DevanshuNagpal! Actually, I have started working on the video already, maybe you can try for another OS or look for other good first issues, please.

**Comment by MayurSMahajan** [comment]
The video is done: https://youtu.be/RhyTyNZuAFo
