### ISSUE TITLE
[FR] Enable Shift-key+click to select multiple lines Feature Request

### ISSUE THREAD

**Issue by fuzzthink** [AppFlowy-IO/AppFlowy#349]
**Main use cases of the proposed feature**
The use of shift-key & click to select multiple lines is an expected feature for all editors.

**what types of users can benefit from using your proposed feature**
All

**Comment by annieappflowy** [comment]
Supported
https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/01810b27-94a0-41fc-9f23-e81eb3bc98f9

**Comment by Ghoelian** [comment]
I can't quite tell from the video, but aren't you just click+dragging to select?

On Kubuntu 23.04 shift+clicking does nothing, the cursor just moves to the place I clicked.
