### ISSUE TITLE
[FR] Add cover/icon to Database pages (Grid/Calendar/Board)

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3491]
### Description

Currently, you can only add a cover and icon to documents, however, this should be possible on all pages no matter the type.,

### Impact

Customizations and organization

**Comment by abhinav700** [comment]
@Xazin  I didn't understand the issue. We can already add cover and icon to pages in AppFlowy. Can you please explain more (I am a beginner)
