### ISSUE TITLE
[Bug] Unable to drag mouse to select correct text.

### ISSUE THREAD

**Issue by Martim233** [AppFlowy-IO/AppFlowy#3492]
### Bug Description

When I drag the mouse to select text, it always selects from the beginning and cannot select the text I want.

### How to Reproduce

Just install and use.

### Expected Behavior

Please help fix this bug.Thanks.

### Operating System

MacOS 13.5.2

### AppFlowy Version(s)

0.3.2

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/87696169/52eec3f5-f7a6-4ad3-b028-abf1f45d76b2

**Comment by tio-trom** [comment]
Maybe it is related but at times, for some big code blocks, I cannot select parts of the code at all:

https://github.com/AppFlowy-IO/AppFlowy/assets/38043315/2becfe6b-f648-4c54-8eff-9f684d515825

Click it nothing happens....

**Comment by annieappflowy** [comment]
Do you still have this issue with the latest release?

**Comment by tio-trom** [comment]
No all good now thanks!
