### ISSUE TITLE
[FR] Database type option integration tests

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3502]
### Description

Please write integration tests for files in the subdirectory `frontend/appflowy_flutter/lib/plugins/database_view/application/field/type_option`. You can first try to understand how the UI is supposed to function, then refer to the existing integration tests to write your new tests.

If you'd like, you can focus on writing tests just for one field type. In that case, please create a separate issue detailing the scope of the task and work from there.

### Impact

Code coverage

**Comment by yashjanidev** [comment]
@richardshiue can you assign me this issue i want to work?

**Comment by richardshiue** [comment]
Sure thing. I look forward to your work!

**Comment by richardshiue** [comment]
Hello @yashjanidev, how's the progress? Do you need any help?

**Comment by yashjanidev** [comment]
@richardshiue hello sir i am learning state management for this task and it is taking more time

**Comment by richardshiue** [comment]
No problem, take as much time as you need and feel free to let me know if you have any questions
