### ISSUE TITLE
[Bug] Can't start snap just after a fresh install

### ISSUE THREAD

**Issue by laszukdawid** [AppFlowy-IO/AppFlowy#3514]
### Bug Description

I've installed the _snap_ using `sudo snap install appflowy` and got a response that `appflowy 0.3.2 from AppFlowy installed`. However, when running it, I'm getting

```shell
> appflowy 
OnLoad

** (AppFlowy:19658): WARNING **: 17:21:43.151: Failed to register: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.138" is not allowed to own the service "io.appflowy.appflowy" due to AppArmor policy
```

### How to Reproduce

Snap install, and snap run? 

### Expected Behavior

To execute.

### Operating System

Ubuntu 22.04 LTS

### AppFlowy Version(s)

0.3.2

**Comment by LucasXu0** [comment]
I will update the necessary permission in the snap profile, and there's a workaround for v0.3.2.

```bash
sudo ln -s /var/lib/snapd/apparmor/profiles/snap.appflowy.appflowy /etc/apparmor.d/
sudo apt install apparmor-utils
sudo aa-complain snap.appflowy.appflowy
snap run appflowy
```

**Comment by LucasXu0** [comment]
@laszukdawid I have added the required permission in the snap file. please try to install the latest version 'appflowy(12)' again.
