### ISSUE TITLE
[Bug] Mouse highlight always starts from the block's beginning

### ISSUE THREAD

**Issue by laszukdawid** [AppFlowy-IO/AppFlowy#3515]
### Bug Description

When highlighting with mouse, regardless where in text I start highlighting, the highlight will begin with the line. Single click within text will move the coursor there. Then, if I press'n'drag, within milliseconds the cuoursor jumps to the beginning of the line, disappears and highlight is stretch from the line's start to the current position.

Additionally, I can't seem to be able to drag blocks around. When hovering over the "lift" icon (6 dots in two columns), the coursor changes icon to the hand, but drag'n'move only highlights the text.

Double click on a word correctly highlights just the word. I can extend the highlight by individual characters with Shift + left/right arrow.

### How to Reproduce

I just installed the program. As I was following the first page, I ticket the checkbox and then tried to highlight something.

### Expected Behavior

Highlight should start with the drag initiation and finish at lifting a click.

### Operating System

Ubuntu 22.04 LTS

### AppFlowy Version(s)

0.3.2

### Additional Context

As I was trying to see some other effects, I can tell that font and theme don't change the behaviour. I can correctly format the text that's highlight.

**Comment by laszukdawid** [comment]
I just checked and `0.3.1` doesn't have that problem, i.e. I can highlight text anywhere.

Dragging blocks, however, doesn't work.

**Comment by annieappflowy** [comment]
#3980
