### ISSUE TITLE
[Bug] Appflowy is so limited

### ISSUE THREAD

**Issue by Maniues** [AppFlowy-IO/AppFlowy#3516]
### Bug Description

Hi. I know that the problem is probably trivial.

I wanted to start using Appflowy because it is 100% open source and packed with features. However, when I launched the application, it turned out that it was a very poor notebook. I can't even make a separate section, let alone all the other features like connecting to the cloud, etc. Interestingly, the older version 0.1.* had more features.

Am I doing something wrong? I don't believe the new version is so poor when the old one is so much better.

### How to Reproduce

Download AppFlowy from GH Releases and run

### Expected Behavior

Have all expected features, not only markdown editor with database.

### Operating System

Tested on Linux Mint and Windows

### AppFlowy Version(s)

Tested on 0.2.9 - 0.3.2

**Comment by annieappflowy** [comment]
Hi @Maniues , could you take some screenshots showcasing where you consider AppFlowy a poor notebook?
And I have to know what features you used in v0.1.* are not available in v0.2.*?

**Comment by annieappflowy** [comment]
You can treat parent pages as sections and add subpages to each section
<img width="398" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/f9c78a5e-7b7c-4c40-b94b-41b3837ee5f2">

We also allow you to create multiple workspaces, simply by changing your file path:
<img width="776" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/a0248e2b-a890-43c0-b6f6-e52723220301">

AppFlowy Cloud is on a private beta mode. You need to sign up for it to get access: https://survey.appflowy.io/private-beta

**Comment by annieappflowy** [comment]
Of course. You can follow [this guide](https://docs.appflowy.io/docs/essential-documentation/appflowy-with-supabase) to self host AppFlowy with Supabase.
We will soon support self-hosting with Docker.

**Comment by annieappflowy** [comment]
AppFlowy is 100% open source licensed under AGPL
We don't have a plan to build closed-source features for now, although we have a plan to include paid features such as more storage and faster image/file uploads in our cloud service. That said, it's free for you to self host AppFlowy.

**Comment by annieappflowy** [comment]
Thanks @Maniues , very much appreciate your questions and suggestions.
We're on our way to creating a plugin marketplace where, hopefully, some plugin creators can be rewarded for their efforts. Wordpress is a great example from which we can draw inspiration.
If you have any questions or feedback for us, please don't hesitate to share. Look forward to seeing you around in the community.
