### ISSUE TITLE
[FR] Showcase when a card entry has notes

### ISSUE THREAD

**Issue by tio-trom** [AppFlowy-IO/AppFlowy#3522]
### Description

Add a little icon, like a text icon, to the card entries that have notes to them. Like so:

![2023-09-25_03-08](https://github.com/AppFlowy-IO/AppFlowy/assets/38043315/1ab93638-0994-4fc7-ac66-73f74571286a)

Maybe maybe even make it have the accent color to make sure it is obvious. 

### Impact

At times I forget that I have to expand such an entry because I may have more notes inside. I am sure others will too. This is a usability issue in my view.

### Additional Context

And I would say to make it more clear that we can add notes to cards because I was clueless for many days. 

![2023-09-25_03-03](https://github.com/AppFlowy-IO/AppFlowy/assets/38043315/c4848bb7-9bb0-419e-90c8-ad3a5d017d5e)

I had no clue I had to click that huge empty space to add more notes...

**Comment by MayurSMahajan** [comment]
Nice catch @tio-trom! It will save a lot of time if we knew which card to expand for notes.

**Comment by annieappflowy** [comment]
<img width="312" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/267974e8-7317-4231-a590-8a921b864b40">
