### ISSUE TITLE
[FR] Add a vertical scrollbar for page link menu and hide the current page

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3524]
### Description

> When I entered @ for a link to a page, I was confused because the window only showed five pages. I then realized that I had to enter more letters. Then the desired page was also displayed 😃 . Would it be useful to have a vertical scrollbar in the window to show that there are more pages to choose from?  And another hint: In the window also the page is shown where I insert the link. This page should not be available for selection. Keep up the good work 👍 ! 
by MacMeikel, Copied from Discord.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/5642a31e-7107-463e-9358-c202af8e8deb)

Tasks:
- [ ] Add vertical scrollbar to page link menu 
- [ ] Remove the current page as an option from the menu

### Impact

Less confusion while using Page Link Menu

**Comment by narayann7** [comment]
@MayurSMahajan hey, can you assign me?

**Comment by MayurSMahajan** [comment]
Sure, happy coding!

**Comment by SharmaDhruv2511** [comment]
is this issue currently open or anyone working on it?? I want to contribute to it.

**Comment by narayann7** [comment]
@SharmaDhruv2511 it is assigned to me and i am currently working on it

**Comment by 0xJaskeerat** [comment]
@MayurSMahajan Hey buddy , can you please assign me this issue

**Comment by MayurSMahajan** [comment]
Hey @0xJaskeerat! Thanks for your interest but since this issue is already assigned to @narayann7. I recommend you to look for other open issues. Good Luck!

**Comment by 0xJaskeerat** [comment]
> Hey @0xJaskeerat! Thanks for your interest but since this issue is already assigned to @narayann7. I recommend you to look for other open issues. Good Luck!

Hey if @narayann7 is not able to do it , then can I take over right ?

**Comment by narayann7** [comment]
@MayurSMahajan removed the current page option and if increase the item count, list expands horizontally, is it fine
<img width="858" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/64174995/36169b29-6b15-4a7d-8801-cfe7a879a14c">

**Comment by MayurSMahajan** [comment]
can't we make it vertically scrollable? 
What are your thoughts on this cc: @hyj1204 @Xazin

**Comment by Xazin** [comment]
I believe this has completely changed in the `main`, can you check you're on the latest version of `main`?

**Comment by narayann7** [comment]
@Xazin, @MayurSMahajan yes it is changed, only thing i need to do is to remove the link for current page
