### ISSUE TITLE
[FR] Basic tables array

### ISSUE THREAD

**Issue by moolight-seashell** [AppFlowy-IO/AppFlowy#3532]
### Description

today we have a database table and this is great, but in most of case i d'ont need this. And a data table is a very restrcitive way to do that.

instead it will be great to have a basic table with feature like colspan and rowspan, with an easy graphical gui to edit them like add column row or cells

### Impact

imrpoving the text view

**Comment by annieappflowy** [comment]
Have you tried simple tables?
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/a6083055-7aae-41db-88d1-d796b0e9808e)
<img width="555" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/af8586d3-09ae-45de-a42f-184d2a8f438f">

**Comment by moolight-seashell** [comment]
oh i diddnt see it srry for the issue
