### ISSUE TITLE
[FR] Insert inline page reference using `[[`

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3541]
We currently only support inserting inline page reference using the `@` (action) menu.

One of the most common ways to insert an inline page reference in editors is using the character commands `[[`, writing this should trigger a menu that enables the user to search for a page to insert.

**Comment by narayann7** [comment]
hey, @Xazin can you assign me this issue, i currently worked on same flow, i think i can add this feature

**Comment by Xazin** [comment]
> hey, @Xazin can you assign me this issue, i currently worked on same flow, i think i can add this feature

Hey @narayann7, I want to assign you, but I can see you're still assigned to another issue, do you plan on completing #3421 or do you want to pass on it?

**Comment by narayann7** [comment]
i was thinking i will try it again to fix it, i will Complete #3421 first then i will take this issue if no one is assigned

**Comment by shah-aman** [comment]
i would like to work on this issue can i be assigned this issue

**Comment by annieappflowy** [comment]
Assigned to @shah-aman

**Comment by Xazin** [comment]
Hey @shah-aman, I have implemented this :+1:
