### ISSUE TITLE
[FR] Rearrange pages using drag-and-drop in the left-hand sidebar

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#355]
**1~3 main use cases of the proposed feature**
Drag-and-drop pages make it easy to structure contents in the left-hand sidebar 

**what types of users can benefit from using your proposed feature**
Users who write a lot of pages

**Comment by gaganyadav80** [comment]
I can work on this as well. Please assign me if no one is working on this.

**Comment by annieappflowy** [comment]
> I can work on this as well. Please assign me if no one is working on this.

@gaganyadav80 thanks for claiming it. I've assigned it to you. If you need help, please contact Nathan on Discord.
