### ISSUE TITLE
[FR] Show a tooltip when hovering over the "No date" button

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3557]
### Description

There might be confusion to users as to what the No Date button is supposed to represent. Please add a tooltip that explains its functionlity, something along the lines of "Unscheduled events will show up here". Or if you can think of a more descriptive label, you can use that as well.

<img width="431" alt="Screenshot 2023-09-29 at 10 16 33 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/024d9b4d-5374-48b6-8dc0-577e083a6fa1">

### Impact

Calendar users

**Comment by gantanikhilraj** [comment]
I would like to work on this, please assign this to me.

**Comment by malik-vishu** [comment]
@richardshiue Can you please assign this to me?

**Comment by richardshiue** [comment]
@gantanikhilraj Sure! I've assigned it to you. Let me know if you need any help. Also, maybe you can make it say "unscheduled events will show up here" when it's empty, and then "x events are unscheduled" when it's not.

@malik-vishu Hey there, thanks for your interest. There are many other hacktoberfest issues that you can work on, feel free to find another one and I can assign it to you!

**Comment by malik-vishu** [comment]
@richardshiue Thank You for assigning this issue to me.
Yes, I will definitely look for other issues.

**Comment by malik-vishu** [comment]
@richardshiue Can you please tell me how to set up this project? Do I need Docker to work on this issue?

**Comment by richardshiue** [comment]
Sorry I'm a bit confused. Are you the same person as @gantanikhilraj?

**Comment by malik-vishu** [comment]
@richardshiue  No I am not.

**Comment by MayurSMahajan** [comment]
@malik-vishu Richard has not assigned you this issue, can you look for other issues

**Comment by malik-vishu** [comment]
@MayurSMahajan Oh, I see that now. Ya I'll look for other issues.

**Comment by gantanikhilraj** [comment]
@richardshiue , can you help me in setting up this project.
Give me the step-by-step process to setup after forking the project.

**Comment by MayurSMahajan** [comment]
Hey @gantanikhilraj! Did you try the docs: https://docs.appflowy.io/docs/documentation/appflowy/from-source for the setup part

**Comment by 0xJaskeerat** [comment]
Hey @MayurSMahajan , I was myself setting up Appflowy in my local , but this is really not going as expected , do you have any video or any resource of the installation , as am getting a lot of unexpected things while setting this up in my system

**Comment by 0xJaskeerat** [comment]
> Hey @0xJaskeerat, what kind of issues are you facing while setting up the environment? You can also message me on Discord to discuss further

Hey can you please list your username or maybe send a lil dm , here's my username : jas.chill

**Comment by MayurSMahajan** [comment]
Hey @0xJaskeerat, here's a video I am working on. Please forgive my audio, I am re-recording as we speak. But this should help you setup: https://youtu.be/JMvRXr0fKNM?si=I-cejUXdY_CHOLdE

**Comment by 0xJaskeerat** [comment]
> Hey @0xJaskeerat, here's a video I am working on. Please forgive my audio, I am re-recording as we speak. But this should help you setup: https://youtu.be/JMvRXr0fKNM?si=I-cejUXdY_CHOLdE

Hey this is for the windows. No words @richardshiue Helped me with setting up 🚀

**Comment by 0xJaskeerat** [comment]
Hey @richardshiue, can I work on this issue  if @gantanikhilraj  is encountering issues , since I have setup the project so would wrap up this soon

**Comment by gantanikhilraj** [comment]
@0xJaskeerat , I am working on the issue soon I will create a PR.

**Comment by 0xJaskeerat** [comment]
> @0xJaskeerat , I am working on the issue soon I will create a PR.

No worries mate , you can continue 🤝

**Comment by gantanikhilraj** [comment]
@MayurSMahajan , I've submitted the PR, if you need any changes please let me know.

**Comment by Kritarthsharma** [comment]
Hi team can I work on this? If this is not closed yet.
