### ISSUE TITLE
[FR] UI enhancement for the dropdown menu that change languages

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#356]
**1~3 main use cases of the proposed feature**
I want to change the language from French to English

**what types of users can benefit from using your proposed feature**
Users who need to change languages
![image](https://user-images.githubusercontent.com/12026239/154824365-bfa52430-4079-4a5d-b5bd-c2d06e2dba7b.png)

**Additional context**
Contact @annieappflowy for the design spec on the dropdown menu

**Comment by gaganyadav80** [comment]
I can work on this one. @annieappflowy can you share the design spec with me so I can have a look. 

PS: This time I will do it quickly xD.

**Comment by gaganyadav80** [comment]
The design file for text highlight dialog issue isn't complete yet. I can work on this one till then. Can you assign me this? @annieappflowy

**Comment by gaganyadav80** [comment]
Hi @annieappflowy, if no one is working on this one. I am more than happy to help.

**Comment by vincentdchan** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/2352832/180357062-e9fdca0c-fea1-4c1e-b3e7-694abe12591e.png">

**Comment by vincentdchan** [comment]
Figma: https://www.figma.com/file/RBbkhQkcCf69c0Bos1L1aH/Language-Setting?node-id=0%3A1

**Comment by Poly-Pixel** [comment]
@annieappflowy I think that this issue can be closed since #699 is merged.
