### ISSUE TITLE
[Refactor] Migrate the markdown feature from Dart to Rust

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#357]
We support exporting a page in Markdown format in Dart. Currently, all the data processing-related functions but Markdown are developed in Rust. We would like to refactor the Markdown function from Dart to Rust.
The main reason for this is that using Rust to process large files increases performance. 

Need to know Rust

**Comment by gabriel-viviani** [comment]
Hey @annieappflowy , I'm learning rust and would like to have some impact here, can I take this one?

**Comment by appflowy** [comment]
> Hey @annieappflowy , I'm learning rust and would like to have some impact here, can I take this one?

That's awesome. I've assigned you. Thanks for offering help.

**Comment by rileyhawk1417** [comment]
@gabriel-viviani do you need any help on this?

**Comment by annieappflowy** [comment]
@gabriel-viviani any update? We'd probably need to un-claim it if your plan is changed :D

**Comment by matrixhead** [comment]
hi, can i work on this?

**Comment by annieappflowy** [comment]
that's awesome! I already assigned it to you. Thank you for helping out

**Comment by annieappflowy** [comment]
@matrixhead hope all is well! Any update on this issue? Do you need some help?

**Comment by matrixhead** [comment]
@annieappflowy thanks for asking,  I'm still working on it nathan is helping me with problems

**Comment by annieappflowy** [comment]
Is this all set @matrixhead ? If it's done, please update the status and close the issue. Thanks!

**Comment by matrixhead** [comment]
i think it is done but it would be better to have @appflowy 's opinion on this

**Comment by appflowy** [comment]
> i think it is done but it would be better to have @appflowy 's opinion on this

Got it
