### ISSUE TITLE
[FR] Copy markdown to clipboard, as a share option.

### ISSUE THREAD

**Issue by HatWearingMann** [AppFlowy-IO/AppFlowy#3577]
### Description

The share button should display two options after pressing it, one for saving the document as a file, and the other for copying the document to the clipboard, still as markdown, of course. 

### Impact

Adding an option for sharing that would simply copy the markdown version of the document, instead of only being able to save it as a file, would make it extra convenient for sharing the document on services such as GitHub Gist.

**Comment by emmggi** [comment]
I think we should also add share as HTML (in file) since we have `documentToHTML()`.

**Comment by StarTrooper08** [comment]
Hey! can I work on this issue?

**Comment by AdiAr11** [comment]
Hi @MayurSMahajan, Can i work on this?
Thank you

**Comment by MayurSMahajan** [comment]
Sure, @AdiAr11 you can work on this.

**Comment by AdiAr11** [comment]
@MayurSMahajan Thank you

**Comment by AdiAr11** [comment]
Hi @Xazin, yes, will try to create a pr this weekend.

**Comment by HatWearingMann** [comment]
> Hi @Xazin, yes, will try to create a pr this weekend.

Heya, status update?

**Comment by HatWearingMann** [comment]
> Hi, I actually upgraded Flutter version, and this project currently does not work with it. Was trying to get it working. And got busy with work. Will try to finish it this weekend.

I hope it's not rude to bug you with this :stuck_out_tongue_winking_eye:

**Comment by AdiAr11** [comment]
> > Hi, I actually upgraded Flutter version, and this project currently does not work with it. Was trying to get it working. And got busy with work. Will try to finish it this weekend.
> 
> I hope it's not rude to bug you with this :stuck_out_tongue_winking_eye: 

No no, its fine, and I'm really sorry, got busy with work. Will try to complete this soon.

**Comment by HatWearingMann** [comment]
> No no, its fine, and I'm really sorry, got busy with work. Will try to complete this soon.

bump

**Comment by Lagrange1813** [comment]
Hi, @MayurSMahajan 
I noticed that this issue had been previously assigned to someone else, but it appears that it hasn't been resolved yet. I would like to offer my assistance in completing this issue if it is still open.
Thank you.
