### ISSUE TITLE
[Bug] : Documentation Page missing for OS specific development instructions

### ISSUE THREAD

**Issue by 0xJaskeerat** [AppFlowy-IO/AppFlowy#3578]
### Bug Description

The Documentation Page Link is broken for OS specific development instructions

### How to Reproduce

* Head over to [Link](https://github.com/AppFlowy-IO/AppFlowy#getting-started-with-development)
* Click on Documentation Link to get <code> Page Not Found </code>

### Expected Behavior

The page should have the guide for OS specific development instructions

### Operating System

mac

### AppFlowy Version(s)

0.3.3

### Screenshots

<img width="1440" alt="Screenshot 2023-10-02 at 5 31 18 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/124770018/1d24e7c2-3d7d-4089-8b1f-9c179c8c6b6c">

**Comment by MayurSMahajan** [comment]
Hey @0xJaskeerat! would you like to work on this issue?

**Comment by 0xJaskeerat** [comment]
Hey @MayurSMahajan , yup I would love to contribute 
You can assign this issue to me

**Comment by deanurag** [comment]
Should i replace t it with this link ?
https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods

**Comment by MayurSMahajan** [comment]
Hey @deanurag! Since I have assigned this already to @0xJaskeerat, can you help us by finding other open issues to contribute? Your interest is much appreciated.

**Comment by Xazin** [comment]
Hey @0xJaskeerat, can you open the PR to this repository? Seems you've just opened a PR to your own fork, if you need assistance let me know.
