### ISSUE TITLE
[Bug] Shift-Click Selection

### ISSUE THREAD

**Issue by HatWearingMann** [AppFlowy-IO/AppFlowy#3579]
### Bug Description

Clicking text with shift held down does not make a selection.

### How to Reproduce

Left click to place the cursor at the beginning of the desired selection.
While holding the shift button, left click at the end of the desired selection.

### Expected Behavior

The text is selected.

### Operating System

Fedora Linux

### AppFlowy Version(s)

Gnome Software, 0.3.3

**Comment by Xazin** [comment]
Related: https://github.com/AppFlowy-IO/appflowy-editor/issues/31

**Comment by MayurSMahajan** [comment]
sorry my bad

**Comment by Xazin** [comment]
> sorry my bad

Haha no worries, I'll make this a priority :+1:

**Comment by Xazin** [comment]
This will be included in 0.3.5 :+1:

**Comment by HatWearingMann** [comment]
Wow, done so quickly? You guys are sick! :D
