### ISSUE TITLE
[Unit Test] Flutter Bloc Unit Test - Listeners and Events

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#358]
Write unit tests for the blocs (located at `frontend/app_flowy/lib/workspace/infrastructure/repos`):
1. Test each event input and output
2. Test listeners of each bloc and verify the input and output

**Comment by moksh-mahajan** [comment]
@annieappflowy Are you mentioning blocs located at frontend/app_flowy/lib/workspace/application/, since there is no infrastructure directory inside frontend/app_flowy/lib/workspace/ ?

**Comment by appflowy** [comment]
> @annieappflowy Are you mentioning blocs located at `frontend/app_flowy/lib/workspace/application/`, since there is no infrastructure directory inside `frontend/app_flowy/lib/workspace/ `?

The infra layer was implemented in Rust. You can check out this https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/architecture/domain-driven-design

**Comment by moksh-mahajan** [comment]
Thanks @appflowy 
I will definitely take a look.

**Comment by annieappflowy** [comment]
Hi @moksh-mahajan, any update on this? As we have more people on the team, I can assign a mentor who can offer help :D

**Comment by Nike682631** [comment]
@appflowy is this issue available to work on?

**Comment by annieappflowy** [comment]
Hi @moksh-mahajan , are you still working on this?

**Comment by moksh-mahajan** [comment]
Hi @annieappflowy 
I'm not currently working on this issue.

**Comment by annieappflowy** [comment]
@Nike682631 would you like to take this?

**Comment by Nike682631** [comment]
@annieappflowy  Yes

**Comment by glitchpop-frenzy** [comment]
Hey @annieappflowy, is there any active development on this? I would like to work on this if this is available.

**Comment by Nike682631** [comment]
@glitchpop-frenzy hey saksham, yes I'm working on this

**Comment by glitchpop-frenzy** [comment]
Cool, let me know if I can be of any help. 😄

**Comment by annieappflowy** [comment]
@Nike682631 , can you update the progress on this issue?
@glitchpop-frenzy , thanks for offering the help. If you are interested in this topic, @LucasXu0 can find some interesting work for you to do. Just let us know!

**Comment by kelvinwieth** [comment]
Anyone working on this one? I'm interested, but first want to take a look. We need to test all blocs from `frontend/appflowy_flutter/lib/workspace/application/`, right?
