### ISSUE TITLE
[Bug] Add hint text or placeholder to suggest that this section is editable

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3582]
### Bug Description

Right now when you expand a card in the Kanban board/ Grid/ Calendar you get the UI shown in the screenshot. It would be nice if there was some hint text that suggested to the user that you can edit this section marked with red.

### How to Reproduce

1. Open AppFlowy
2. Create a new Kanban/Grid/Calendar
3. Create and open a new card
4. Observe that there is no visual clue to suggest user that this area is editable.

### Expected Behavior

Some visual clue to show that this area is editable.

### Operating System

every

### AppFlowy Version(s)

0.3.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/d8d648ae-2412-4aec-8a80-8f96083986aa)

### Additional Context

Originally this bug was noticed and mentioned in this issue: #3522

**Comment by prakadesh** [comment]
Hey, I'd like to do it. Can you assign it to me?

**Comment by MayurSMahajan** [comment]
Sure thing! Assigned

**Comment by RUDRANSHFLY** [comment]
This issue is still open ?
If open can I do on this issue if you can assign me

**Comment by MayurSMahajan** [comment]
It is already assigned to @prakadesh. You can look up other open issues which are not assigned to anyone. Thanks for your interest

**Comment by aspiringgarv** [comment]
hey could you assign this issue to me will be happy to contribute

**Comment by prakadesh** [comment]
@MayurSMahajan i was able to add the hint text but it works only when the focus is set on it

**Comment by MayurSMahajan** [comment]
Hey @prakadesh, it is okay, for now that will be sufficient, at least it is some improvement, go ahead and submit a PR, if you already haven't.

**Comment by prakadesh** [comment]
@MayurSMahajan submitted PR
