### ISSUE TITLE
[Bug] Record Not Found

### ISSUE THREAD

**Issue by NightBright199** [AppFlowy-IO/AppFlowy#3583]
### Bug Description

When I tried to make another board Inside of a board... It's that.

AND when I exit out of the board and come back to It, both of the board becomes the same and even does the same action that happened on one board, although not realtime, have to exit and enter again to update.

### How to Reproduce

Make a board inside of a Document
Modify the board
Add another board

### Expected Behavior

Add a different board that's independent from the other board.

### Operating System

Windows 10 22H2

### AppFlowy Version(s)

0.3.3

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/70122416/8b5c5cf3-53a9-429e-9149-c2279f7d9642)

after exiting and entering the board again

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/70122416/65668c9e-dd49-4a31-884b-5b4c5ac90461)

**Comment by SunilKividor** [comment]
Hey @NightBright199 Can you please explain me the bug in detail ? I would like to know more.

**Comment by annieappflowy** [comment]
Should be fixed
