### ISSUE TITLE
[Bug] Link to Style Guide outdated, need to be updated

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3584]
### Bug Description

In the PR template, we have a link pointing to AppFlowy Style Guide.
This link is broken now.
Need to update the link to point to the correct documentation page.

### How to Reproduce

Go in any existing PR, or create a new one.
Click the link of AppFlowy Style Guide 
Observet that the link is broken

### Expected Behavior

The link takes you to the right place.

### Operating System

Not Applicable

### AppFlowy Version(s)

Not related to AppFlowy

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/93a52e6b-26ca-4ac5-877e-32cd0fa17f62)

**Comment by Xazin** [comment]
Already merged and resolved :+1:
