### ISSUE TITLE
[Bug] Selecting inline code has no visual feedbacks

### ISSUE THREAD

**Issue by tio-trom** [AppFlowy-IO/AppFlowy#3585]
### Bug Description

I am using the default AppFlowy theme on Arch Linux. Here:

https://github.com/AppFlowy-IO/AppFlowy/assets/38043315/31a3b7ca-3b18-44cc-8cfa-02d661f77878

The select highlight color should be different from the inline code background color, else it is impossible to see what you are selecting.

### How to Reproduce

As stated above.

### Expected Behavior

As mentioned.

### Operating System

Arch Linux with XFCE - kernel 6.1

### AppFlowy Version(s)

0.3.3

**Comment by annieappflowy** [comment]
Fixed
<img width="404" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/76942006-8ea7-48a2-b428-29e9bf4eded6">
