### ISSUE TITLE
[Problem in filling table] 

### ISSUE THREAD

**Issue by freeboson0** [AppFlowy-IO/AppFlowy#3586]
### Bug Description

The problem in the table is when i create several rows and i want  to fill information, it doesn't give me access if i write something somewhere else outside the table and i want to come back to continue filling it. 
To do so, I am obliged to click on the first rows and press the arrow button (down) to reach the desired row.

### How to Reproduce

1. create table with several rows
2. fill some information in the first rows
3. write a note outside the table 
4. come back to the table  and click in one of the last rows

### Expected Behavior

 I expect after writing a note outside the table, i still can modify the rows by clicking on them.

### Operating System

windows 11

### AppFlowy Version(s)

0.3.3

**Comment by Abood2284** [comment]
Hello @freeboson0 would you mind sharing ScreenShot of the bug,

I have tried to reproduce the bug, by the steps you mentioned.

- Created a table with several rows.
- Created a note outside the table and again tried to write on the latest row

it works perfectly fine for me

**Comment by annieappflowy** [comment]
Please feel free to reopen if the issue still persists.
I'm not able to reproduce it with the latest release.
