### ISSUE TITLE
[Bug] Can't Select AI dropdown

### ISSUE THREAD

**Issue by Joso997** [AppFlowy-IO/AppFlowy#3597]
### Bug Description

So when I click on AI Assistant a dropdown shows but it is so fast you can't do anything with it.

### How to Reproduce

Select text, and click AI Assistant...

### Expected Behavior

Select text->AI Assistant->dropdown menu showing

### Operating System

Windows 10

### AppFlowy Version(s)

0.1.2

**Comment by Joso997** [comment]
Yeah, I got it.
The link to the download site might be old then (the one on GitHub readme):
https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods/mac-windows-linux-packages

uto, 3. lis 2023. u 15:22 Annie ***@***.***> napisao je:

**Comment by Joso997** [comment]
Nope, the screenshot on the link is old actually. I am using the 0.3.4v
So here is the bug: when I click on this dropdown, it shows with more
options but closes so fast that you can't do anything with it.
[image: image.png]

sri, 4. lis 2023. u 10:24 Joso Marich ***@***.***> napisao je:

**Comment by annieappflowy** [comment]
still running into this issue?
I'm not able to reproduce.
