### ISSUE TITLE
[Bug] Why Quill?

### ISSUE THREAD

**Issue by jonymei** [AppFlowy-IO/appflowy#36]
1. quill is dead. visit https://github.com/quilljs/quill/issues/3359
2. quill does not have a real table module.

**Comment by annieappflowy** [comment]
Hi Jony,

We used flutter-quill, which is actively maintained.

**Comment by hobdob** [comment]
@jonymei flutter-quill is a different project from quilljs, which is written in JavaScript instead of Dart

**Comment by britannio** [comment]
https://github.com/superlistapp/super_editor looks promising

**Comment by annieappflowy** [comment]
flutter-quill is written in Dart while quilljs is written in JS

**Comment by notd5a-alt** [comment]
Probably should close this issue since its just clutter amongst actual FR's and Bugs

**Comment by increeks** [comment]
Resolved in PR #43. Added client-side and server-side Zod validation for numeric `teamSize` and `stipendExpectation` fields, blocking wizard step navigation when invalid and displaying explicit error messages.
