### ISSUE TITLE
[FR] Support Workspace Settings - name and icon

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#360]
**1~3 main use cases of the proposed feature**
As a user, I want to rename my workspace and set another icon for it.

**what types of users can benefit from using your proposed feature**
All the users

**Additional context**
Currently, the purple icon and the name are hardcoded. We want to enable users to change them through "Settings"
![image](https://user-images.githubusercontent.com/12026239/154825335-9324fd66-1cc9-4494-94ed-308cab6bbf3a.png)
There should be a new section in "Settings" called "Workspace":
1. Keep the default as it is.
2. The user can rename the workspace and set an emoji icon. 
3. The changes should be reflected in the left-hand sidebar after pressing the "Update" button on the "Workspace" setting page.

**Comment by appflowy** [comment]
> I'd like to contribute; can I use this one as a starting point? @annieappflowy?

Yes, that will separate into two parts:
1. implement the UI on the dart side.
2. save the data on the rust side.

You can DM me on Discord if you need help.

**Comment by ENsu** [comment]
There is already an `user_table.name` field in the db, but no field to store the emoji icon. Should I simply create one?

**Comment by appflowy** [comment]
> There is already an `user_table.name` field in the db, but no field to store the emoji icon. Should I simply create one?

I think you can create a new column that stores the user icon. But, do you have any idea about how to store the icon data? I think the URL of the icon would be better. For the moment, the URL is a local file path.

**Comment by appflowy** [comment]
There is some context that may help you to finish this FR. 

1. How to save the URL in user_table.

- Database
AppFlowy use [diesel](https://diesel.rs/guides/getting-started) as SQLite ORM. You need to add a migration and run it. 
For example, I added a new column to view_table.
`ALTER TABLE view_table ADD COLUMN ext_data TEXT NOT NULL DEFAULT '';`

- Update user profile
You can extend the struct UpdateUserPayload by adding a new property, thumbnail.
```
pub async fn update_user_handler(
    data: Data<UpdateUserPayload>,
    session: AppData<Arc<UserSession>>,
) -> Result<(), FlowyError> {
    let params: UpdateUserParams = data.into_inner().try_into()?;
    session.update_user(params).await?;
    Ok(())
}
```

2. How to read the URL?
Use UserEvent::GetUserProfile event to get the UserProfile

3. How to send a notification to Dart side when a user profile was changed.

- Set up a listener on the Dart side to listen for the UserNotification::UserProfileUpdated event.
- Send the notification on the Rust side by calling

```
dart_notify(&token, UserNotification::UserProfileUpdated)
                        .payload(profile)
                        .send();
```

DM me if you need help.

**Comment by aarhusgregersen** [comment]
Is this still being worked on @ENsu ?
If not, I'd like to give it a jab.

**Comment by aarhusgregersen** [comment]
Is this still being worked on @ENsu ?
If not, I'd like to give it a jab.

**Comment by annieappflowy** [comment]
@aarhusgregersen thanks for offering help. I believe @ENsu is still working on it: https://github.com/AppFlowy-IO/AppFlowy/pull/778
You can take a look at https://github.com/orgs/AppFlowy-IO/projects/5/views/4 to check out friendly issues for new contributors.

**Comment by ENsu** [comment]
Hello, @aarhusgregersen. It's a pleasure to meet you. I believe I am nearly finished.

**Comment by ENsu** [comment]
@annieappflowy @appflowy 

I think https://github.com/AppFlowy-IO/AppFlowy/pull/778 is ready for merging. 

I've only added 10 icons from https://openmoji.org/ so far, but I think it works well. I don't trust my aesthetic, so I'm hoping that someone else will decide which icon files should go in the emoji folder. 😅

**Comment by appflowy** [comment]
@ENsu I merged it. Thanks for contributing again!
