### ISSUE TITLE
[FR] Please add toggle List 

### ISSUE THREAD

**Issue by nillem-14** [AppFlowy-IO/AppFlowy#3603]
### Description

This enables to easily open and close “chunks” of note. Toggle Lists, in a way, behave like checkpoints in writings

### Impact

Many students are using toggle list as falshcard (for example by taking notes with questions)

**Comment by Xazin** [comment]
Have you tried inserting a toggle list using the slash command?

IIRC we already have this.

**Comment by Xazin** [comment]
Closing, please see video

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/732d0acb-c244-451d-9fe1-0790131abe2f
