### ISSUE TITLE
[FR] Resize the left-hand sidebar

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#361]
**1~3 main use cases of the proposed feature**
* I want to make the sidebar smaller instead of hiding it as I want to make the editing part bigger but have the ability to view the left-hand bar at the same time.
* I like having longer titles for pages so the ability to make the sidebar wider enables me to view more contents of the titles.

**what types of users can benefit from using your proposed feature**
All the users

**Additional context**
Need to know: Flutter

**Comment by matrixhead** [comment]
hey can I work on this?

**Comment by annieappflowy** [comment]
Hi @matrixhead , hope this is not too late. Can you confirm if you'd like to work on this issue? I will then assign it to you and a mentor who can offer help.

**Comment by annieappflowy** [comment]
@matrixhead  awesome! thanks for offering the help. @LucasXu0 is the mentor on this FR. You can reach out to him on Discord if you'd like to have quick chats. Join Discord: https://discord.gg/9Q2xaN37tV

**Comment by Poly-Pixel** [comment]
@annieappflowy I think that this issue can be closed now as #660 has been merged.
