### ISSUE TITLE
[Bug] Changing bullet list to toggle list deletes sublist bullets 

### ISSUE THREAD

**Issue by Technowulff** [AppFlowy-IO/AppFlowy#3613]
### Bug Description

When you start a bullet list, but later decide you want that bullet list to be contained within a toggle list, if you change the top-level bullet into a toggle list, the sublist disappears. If you don't undo the change, and switch pages, you will permanently lose sublist.

### How to Reproduce

1. Create a bullet list using either the "/" menu or markdown "*" + SPACE. Enter some text.
2. Press ENTER and then TAB to create a sublist. Enter some text.
3. Go back to the top of the list, and change that bullet into a toggle list using markdown ">" + SPACE. 

The toggle list will automatically open and delete any sublist under it.

### Expected Behavior

Converting the top level bullet into a toggle list would place the sublist under the toggle list, not delete the sublist.

### Operating System

Windows 10

### AppFlowy Version(s)

0.3.1 & 0.3.4

**Comment by mr-loop-1** [comment]
Hi @MayurSMahajan I would like to take this issue. Please assign me
