### ISSUE TITLE
[Bug] Prior date used when selecting date in grid's date property

### ISSUE THREAD

**Issue by Technowulff** [AppFlowy-IO/AppFlowy#3614]
### Bug Description

When you create a date property in a grid and select a date, the previous date is selected instead. 

- If you select Sunday October 1, you will get Saturday September 30.
- If you select Wednesday October 4, you will get Tuesday October 3.

### How to Reproduce

1. Create a new grid or modify an existing grid.
2. Create a date property by either adding one or modifying an existing property.
3. Hover your mouse over a date, and click it.
4. The date immediately prior to the date you clicked will be highlighted and appear on the grid.

### Expected Behavior

Highlight the date I clicked on, and use that date on the grid.

### Operating System

Windows 10

### AppFlowy Version(s)

0.3.0 & 0.3.1 & 0.3.4

### Additional Context

This has thrown me off several times. I've worked around this by selecting the date immediately after the date I want to select.

**Comment by richardshiue** [comment]
Hey there thanks for reporting this issue. Do you mind giving me your timezone so I can debug this?
