### ISSUE TITLE
[Bug] Unchecked checkbox color is wrong

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3620]
### Bug Description

The outline of the checkbox should have a light grey color. This is present in Grid and Board cards, board header and perhaps some other places as well. Take the time to look through each place where a checkbox could appear.

### How to Reproduce

![Screenshot 2023-10-05 at 5 01 54 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/e5aacc24-cae8-429a-baa8-5892bc44fb70)

### Expected Behavior

![Screenshot 2023-10-05 at 4 59 11 PM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/9ed99cdf-ec6f-4dde-a082-d0a7a1531578)

### Operating System

macOS

### AppFlowy Version(s)

0.3.4

**Comment by abd529** [comment]
attempt/ #3620

**Comment by sarthakkimtani** [comment]
I want to work on this issue. Can I be assigned?

**Comment by shahjugal** [comment]
I want to work on this issue. Can I be assigned?

**Comment by SharmaDhruv2511** [comment]
is anyone working on the issue? I want to contribute to it ? @richardshiue Can you please assign it to me?

**Comment by richardshiue** [comment]
Hi @sarthakkimtani, would you like to work on this?

**Comment by sarthakkimtani** [comment]
Yes, I'll work on it.

**Comment by richardshiue** [comment]
Awesome, I have assigned it to you. Have fun coding!

**Comment by Isoumyajit** [comment]
Hey @richardshiue ,
I want to work on this issue please assign this to me
Thank you,
