### ISSUE TITLE
[FR] Refrencing Documents in Document content (Like Nuclino collection)

### ISSUE THREAD

**Issue by Joso997** [AppFlowy-IO/AppFlowy#3622]
### Description

Ability to have a <a></a> equivalent or at least a list of clickable names (Derived from document names) like collection in Nuclino.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/23720628/c6ce5607-d024-410c-ba8d-14cf6f276946)

### Impact

Besides having a more organized environment, you also gain a way to reference documents on boards and calendars. Which could add an interesting new way of writing tasks.

**Comment by annieappflowy** [comment]
Hi @Joso997 , have you tried typing @ to link an existing page? Would this meet your needs?

**Comment by Joso997** [comment]
Yeah, that will do, awesome. It is a little buggy though. Like when you
rename a document you need to switch to a different document and back for @
to take the rename into account.
Something like that at least, I will write a bug once I figure it out.

Thanks!

pet, 6. lis 2023. u 15:46 Annie ***@***.***> napisao je:

**Comment by annieappflowy** [comment]
#3641

**Comment by annieappflowy** [comment]
Fixed. When the referenced document's title is updated, the reference is also updated.
