### ISSUE TITLE
[FR] "uk_UA" Request to add Ukrainian language

### ISSUE THREAD

**Issue by SimonOriginal** [AppFlowy-IO/AppFlowy#3625]
### Description

Dear AppFlowy Development Team,

I am writing to request the addition of the Ukrainian language to the list of supported languages for the AppFlowy program. I have translated the application into Ukrainian, and at the moment, approximately 90% of the application is translated. Ukrainian is my native language, and I would like more people from Ukraine and Ukrainian speakers to be able to use AppFlowy in their native language.

I have attached the translation file to this email. You can download it from the following link on Google Drive: "https://drive.google.com/file/d/1Gn9Ip-078uCeFREwuM9gUAH0kmT4bMWz/view?usp=sharing".

Best regards,
Simon

### Impact

Ukrainian users and those who know the Ukrainian language.

**Comment by MayurSMahajan** [comment]
Thanks @SimonOriginal! We would love to add Ukrainian to AppFlowy

**Comment by MayurSMahajan** [comment]
Anybody wanting to claim this issue has to do the following:
 - [ ] Create a new PR adding Ukrainian translation.
 - [ ] The translation should be taken from the link provided by Simon

**Comment by SaadTanveer14** [comment]
@MayurSMahajan the assets/translations/ is in .gitignore so the json file will not be uploaded. Is it okay to upload without file or should i remove assets/translations/ .gitignore?

**Comment by sarthakkimtani** [comment]
Is this issue already assigned? Can I be assigned if it's available?

**Comment by MayurSMahajan** [comment]
No it is not assigned to anyone, you can directly submit a PR if you want, then I'll assign you

**Comment by SimonOriginal** [comment]
A bug was detected: when setting Ukrainian as the main language and then restarting the application, the working field becomes gray. If you return the language to English, for example, everything works correctly. Attached screenshot for clarity. 
![изображение](https://github.com/AppFlowy-IO/AppFlowy/assets/94782611/874619a2-98c8-4dae-a98d-4a2f2ad81258)
