### ISSUE TITLE
[Bug] The appearance of slash menu didn't change along with theme mode changes

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#3630]
### Bug Description

When we changed the theme or theme mode, the slash menu's appearance didn't change.

### How to Reproduce

1. Open the slash menu
2. Change theme or theme mode
3. Open the slash menu again, it shows the same appearance as the previous theme. 

### Expected Behavior

The slash menu shows the updated/current theme and theme mode color. 

### Operating System

macOS

### AppFlowy Version(s)

0.3.4

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/42b836de-e90d-4ec4-a7e5-6822b873831f

**Comment by lielfr** [comment]
Hi, I'd like to work on this one if possible 😄

**Comment by MayurSMahajan** [comment]
@hyj1204 can assign you, if she is not already working on it.

**Comment by hyj1204** [comment]
> Hi, I'd like to work on this one if possible 😄

Here you go

**Comment by lielfr** [comment]
hi again, I think I managed to fix the bug. However, I'm having some trouble running the integration tests, and would like some help with that (it's probably a good idea to have at least one new test for this)
