### ISSUE TITLE
To add icons with the button 

### ISSUE THREAD

**Issue by AditiSingh2003** [AppFlowy-IO/AppFlowy#3636]
### Description

<img width="960" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/97729662/acc718a0-c0c5-4919-b806-64a4ba40fe99">
Add Github and Discord Icon.

### Impact

It will improve the UI.

**Comment by Xazin** [comment]
Hey Aditi, thanks for the suggestion!

We're currently working on something that will completely change the homepage, thus I will close this. :pray:
