### ISSUE TITLE
[Bug] Chinese fonts / Chinese characters display problem

### ISSUE THREAD

**Issue by XJPeng12** [AppFlowy-IO/AppFlowy#3640]
### Bug Description

There is a problem with the display of some Chinese characters, such as ‘专门’，
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/50786186/a80049b5-53cc-4495-a67e-38fcee0cb817)

### How to Reproduce

input Chinese characters

### Expected Behavior

Can display Chinese characters correctly

### Operating System

window10

### AppFlowy Version(s)

0.3.1

**Comment by cidxb** [comment]
Actually, this happens to the Ubuntu system too, in which the font config file `/etc/fonts/conf.d/64-language-selector-prefer.conf ` preference is the Chinese characters used in Korean and Japan, the solution is to change the order.

I wonder if there is a simple solution similar to Appflowy in this matter.

**Comment by sky96111** [comment]
No need to bundle CJK fonts, l10n can choose correct fonts automaticlly.
https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization

without l10n:
![Snipaste_2023-12-08_17-32-45](https://github.com/AppFlowy-IO/AppFlowy/assets/22412214/060366f6-fab0-43a1-b490-606323623005)

with l10n:
![Snipaste_2023-12-08_17-40-58](https://github.com/AppFlowy-IO/AppFlowy/assets/22412214/d4023561-892f-47cb-9d56-342b20c40eb9)

**Comment by annieappflowy** [comment]
Please go to Settings and choose Workspace -> Workspace font -> System
<img width="289" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/573db644-4ab9-4615-8a31-34766cdb5a50">
