### ISSUE TITLE
[FR] make a step-by-step video tutorial for self-hosting AppFlowy with Supabase

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3643]
### Description

as described in the title, create a video to guide people to self-host AppFlowy using Supabase

### Impact

Developers who want to self-host AppFlowy using Supabase

**Comment by MayurSMahajan** [comment]
@annieappflowy what will be the ideal deadline for this task? I would like to take it up.

**Comment by annieappflowy** [comment]
@MayurSMahajan , by the end of Oct would be great!

**Comment by MayurSMahajan** [comment]
On it!

**Comment by Prathap-Chandra** [comment]
@MayurSMahajan Any update on the video to guide people to self-host AppFlowy using Supabase

**Comment by MayurSMahajan** [comment]
It is in progress, you can expect it within a couple of weeks.

**Comment by annieappflowy** [comment]
Hi @MayurSMahajan , is this done?

**Comment by MayurSMahajan** [comment]
No, it is not complete yet, a draft is ready though and I have sent it to you on Discord, on the last step I am facing an error. I am not able to sign in with Google. I am talking with Nathan to resolve the issue, but he seems busy.

**Comment by Prathap-Chandra** [comment]
@MayurSMahajan Could you please send the draft to me as well. prathap.chandra.754@gmail.com is email Id. Also I've pinged you on discord. I've completed my Google Setup and able to run. I just wanted to see how your using the database? Let me know if we can catch up on discord

**Comment by lynnww** [comment]
hope to take it up. I followed the instructions of Docs and the database was ready, but I can not get me log in and supabase return erro 400.

**Comment by lynnww** [comment]
good for u! 
Thanks very much~

**Comment by MayurSMahajan** [comment]
@Valaiscom-AG you can read about it in the discussion of this PR: https://github.com/AppFlowy-IO/AppFlowy/pull/5069
