### ISSUE TITLE
[FR] Issue with 'toggle' & can't drag and drop elements

### ISSUE THREAD

**Issue by fredericgoossens** [AppFlowy-IO/AppFlowy#3650]
### Description

It's worth noting that placing elements within the toggle element is not currently supported in AppFlowly, unlike in Notion where this behavior is allowed.

Additionally, in AppFlowly, there is an issue where you cannot drag and drop the element to a different location when hovering over the 'drag' icon, such as inside a toggle. Notion, on the other hand, allows this functionality, and I believe it would be beneficial to have this feature implemented in AppFlowly as well.

![Kapture 2023-10-09 at 12 42 21](https://github.com/AppFlowy-IO/AppFlowy/assets/18092968/20471c6a-542b-4aca-a2e3-c61920d41779)

### Impact

This feature would have a positive impact on all users, as it is one of the standout features in Notion. If you're aiming to develop an open-source Notion clone, implementing these features would be highly beneficial in providing a comprehensive and user-friendly experience for all users.

**Comment by annieappflowy** [comment]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/9fe24498-3d03-429c-bab5-1d50a7ba4ec4">

Supported drag and drop and fixed the toggle issue reported here
