### ISSUE TITLE
[Bug] impossible to click on any sub-items if the top level item is off-screen

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3651]
### Bug Description

It appears to be impossible to click on any sub-items if the top level item is off-screen. So if I have something that looks like this screenshot, if the checkbox line at the top leaves the screen I can only select the other lines via the home/end keys, not by clicking

### How to Reproduce

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8705d01a-18fa-474f-9021-c9d41821d4f9)

### Expected Behavior

Items on a doc are clickable

### Operating System

Windows 10

### AppFlowy Version(s)

v0.3.4

**Comment by emmggi** [comment]
I also have this on Linux and v0.3.4. If the top level item is not visible then it selects the first top level item after it (in this case it would focus on `Backup Google Drive again`).

**Comment by LucasXu0** [comment]
> I also have this on Linux and v0.3.4. If the top level item is not visible then it selects the first top level item after it (in this case it would focus on `Backup Google Drive again`).

It should be fixed in the previously mentioned PR. I will check it again and bump the new version tomorrow.

**Comment by LucasXu0** [comment]
Fixed in 0.3.6
