### ISSUE TITLE
[Bug] Main Page suddenly only displays "placeholders" text instead of containing the subpages.

### ISSUE THREAD

**Issue by HeathenHacks** [AppFlowy-IO/AppFlowy#3652]
### Bug Description

Main Page suddenly only displays "placeholders" text instead of containing the subpages. Even after adding referenced grids/boards, the "placeholders" text do not disappear.

### How to Reproduce

Not sure if it's reproduceable or not

### Expected Behavior

Should display the subpages

### Operating System

ArcoLinux

### AppFlowy Version(s)

23.08 (Flatpak}

### Screenshots

[Main Page suddenly only displays "placeholders" instead of containing the subpages](https://i.imgur.com/x2W5AT6.png)
["placeholders" text does not disappear](https://i.imgur.com/pFj3v2B.png)

### Additional Context

Debug Info:

name: Freedesktop SDK
version: 23.08 (Flatpak runtime)
id: org.freedesktop.platform
idLike: null
versionCodename: null
versionId: 23.08
prettyName: Freedesktop.org SDK 23.08 (Flatpak runtime)
buildId: null
variant: null
variantId: null
Document: /home/heathenhacks/.var/app/io.appflowy.AppFlowy/data/AppFlowy/data

**Comment by LucasXu0** [comment]
Fixed in 0.3.6.
