### ISSUE TITLE
[Bug] Possible issue with the latest version of libnotify

### ISSUE THREAD

**Issue by HeathenHacks** [AppFlowy-IO/AppFlowy#3661]
### Bug Description

Possible issue with the latest version of [libnotify](https://i.imgur.com/zhANuJ8.jpg).

The Flatpak version from KDE's Discover does not launch anymore. Whether clicking on the desktop shortcut, via Krunner, or terminal.

Tried to use the latest AppImage after uninstalling the Flatpak version, but it's still not launching.

Tried to follow the steps on the [website](https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods/mac-windows-linux-packages/installing-on-linux) on how to install it manually after I removed the AppImage, but it also produced [error](https://i.imgur.com/E729Rnq.png) when trying to launch AppFlowy.

Am I just doing things wrong?

### How to Reproduce

Update libnotify to latest version, maybe? Can't really downgrade to check and confirm, because quite a few apps require it.

### Expected Behavior

Would launch via using Krunner, a desktop shortcut or the terminal.

### Operating System

ArcoLinux

### AppFlowy Version(s)

0.3.3 (Flatpak) and 0.3.5 AppImage and latest release version

### Screenshots

Possible issue with the latest version of [libnotify](https://i.imgur.com/zhANuJ8.jpg).
[error](https://i.imgur.com/E729Rnq.png) when trying to launch AppFlowy

### Additional Context

Tried to use the Flatpak, AppImage and latest release versions of AppFlowy, and all failed to launch. 

Thanks!

**Comment by LucasXu0** [comment]
@HeathenHacks I have updated the latest version 0.3.5 in Flathub. Can you try to install the latest version?

**Comment by LucasXu0** [comment]
> > @HeathenHacks I have updated the latest version 0.3.5 in Flathub. Can you try to install the latest version?
> 
> Will do, thanks. At the moment, it's still 0.3.3 on both the Flathub website and on Discover via Flatpak.

You can try installing it in test mode.

`flatpak install --user https://dl.flathub.org/build-repo/54999/io.appflowy.AppFlowy.flatpakref`

Or, have you tried to install libnotify via apt-get? `sudo apt install libnotify-dev`

**Comment by HeathenHacks** [comment]
> You can try installing it in test mode.

Hello again. I reinstalled AppFlowy's Flatpak version via KDE's Discover and it's working now.

Thanks!
