### ISSUE TITLE
[Bug]  Unable to launch AppFlowy Flatpak - Missing library

### ISSUE THREAD

**Issue by Sharkitty** [AppFlowy-IO/AppFlowy#3662]
### Bug Description

Since the update that just dropped for the flatpak version (`0.3.4`), AppFlowy won't launch anymore. Nothing happens, just the wobbling icon to say it's loading and nothing appears. If I launch it from the command line (`flatpak run io.appflowy.AppFlowy`), all I get is this error:
```
AppFlowy: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```

If I rollback to the previous version it works again.

### How to Reproduce

- Update AppFlowy flatpak to `0.3.4`.
- Launch it, it should fail to launch.

### Expected Behavior

AppFlowy should successfully launch.

### Operating System

Fedora-KDE 38

### AppFlowy Version(s)

`0.3.4` (Flatpak)

**Comment by HatWearingMann** [comment]
I have the same issue, when attempting to launch the software from the terminal, I get this:

```
$ flatpak run io.appflowy.AppFlowy
AppFlowy: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
```
`

**Comment by Sharkitty** [comment]
> @HatWearingMann @Sharkitty
> 
> Please try to install the libnotify manually.
> 
> `sudo apt-get install libnotify4`
> 
> or
> 
> `sudo dnf install libnotify`
> 
> And I have updated the version to 0.3.5. It should be available on Flathub tomorrow.

This shouldn't be required to run a flatpak. The whole point of this packaging format is to resolve dependencies separately from the system.

**Comment by Sharkitty** [comment]
I checked and `libnotify` was already installed on my system.

**Comment by shanlalit** [comment]
Same here running on Pop OS 22. Running version 0.3.4

❯ flatpak run io.appflowy.AppFlowy
AppFlowy: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory


❯ sudo apt-get install libnotify4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libnotify4 is already the newest version (0.7.9-3ubuntu5.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by HatWearingMann** [comment]
Works again after update.

**Comment by Sharkitty** [comment]
Works for me as well with `0.3.5`. Thanks a lot for the fast fix :smile_cat:

**Comment by LucasXu0** [comment]
> This shouldn't be required to run a flatpak. The whole point of this packaging format is to resolve dependencies separately from the system.

Agreed. So I added `libnotify4` as a dependency in flatpak.yml.
