### ISSUE TITLE
[FR] support dialogue with AI

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3679]
### Description

Now, in the image block, we're unable to keep the context from AI when regenerating the image. For example,

```
Q: a blue cat with wings.
A: image 1, image 2, image 3...
Q: make the eyes bigger.
A: ...
```

The second prompt will only regenerate an image without any reference to the first one, and we should maintain the previous context when generating the second image.

### Impact

Ensure that the generated content, such as images and text, is more reasonable and related.

**Comment by ParthMakode** [comment]
where are the files related to this ai gen image block?

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/3695
