### ISSUE TITLE
[Windows]There is no release version of WIN platform?

### ISSUE THREAD

**Issue by bukuyuxuan** [AppFlowy-IO/AppFlowy#368]
After waiting so long, why hasn't the win platform been released

**Comment by annieappflowy** [comment]
Hi @bukuyuxuan ,

Thanks for your patience. We're releasing a Windows package, and it should be ready for downloading shortly.

**Comment by annieappflowy** [comment]
> After waiting so long, why hasn't the win platform been released

Done. Please download from https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.0.3

**Comment by fhmohen** [comment]
> 
有了啊~
