### ISSUE TITLE
[Bug] Missing the hover tooltip in the RTL mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3690]
### Bug Description

<img width="794" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/bee5a9c8-8fd2-4086-8eb3-61933abc0783">

### How to Reproduce

Text layout : RTL
Select text to trigger the format menu
Hover on the last icon "T"
No tooltip hint

### Expected Behavior

Has hint like other options

### Operating System

macOS

### AppFlowy Version(s)

v0.3.5

**Comment by annieappflowy** [comment]
The same issue in the LTR mode

**Comment by katlehotech** [comment]
Please assign me this issue

**Comment by increeks** [comment]
@annieappflowy Please assign this issue!

**Comment by prasadsunny1** [comment]
I tried to debug but I could not pinpoint the source of the tooltip message

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me
