### ISSUE TITLE
[FR] Integrate image picker for image widget into cover image

### ISSUE THREAD

**Issue by TDuffinNTU** [AppFlowy-IO/AppFlowy#3695]
### Description

When adding an image to a document you can select an image from unsplash via the API, or use Stability to produce one via AI. However, this picker is missing from the cover image section where it would also be useful!

### Impact

This would give cover images more use and make them easier to generate/add to documents

### Additional Context

Notion uses the same picker for images and cover images, bar colors I believe. Would be good to have for people migrating from the platform.

**Comment by annieappflowy** [comment]
<img width="619" alt="image" src="https://github.com/user-attachments/assets/7c67b546-c1ba-42f5-969d-06df0c608203">
