### ISSUE TITLE
[Bug] Images from URL return "invalid URL" if URL contains extra arguments.

### ISSUE THREAD

**Issue by TDuffinNTU** [AppFlowy-IO/AppFlowy#3696]
### Bug Description

https://images.pexels.com/photos/732444/pexels-photo-732444.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2

Take the above image URL from pexels. It'll open in a browser tab just fine, and is the result of copying the link to an image on the site. However, in Appflowy the image doesn't apply as the URL is "invalid". Removing the arguments makes the image work fine.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/43959652/12241475-408e-4a0e-ad40-ae8b687bf361)

### How to Reproduce

Copy an image from pexels, unsplash, etc. using "copy link to image" or "copy image url" in your browser.

Example:  https://images.pexels.com/photos/732444/pexels-photo-732444.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2

Attempt to set it as your document's cover photo with the image from URL feature:

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/43959652/98ce5985-90ae-4131-a0af-ff86017f0fcc)

### Expected Behavior

Image is detected and loaded.

### Operating System

Windows

### AppFlowy Version(s)

0.3.5

### Screenshots

As above.

### Additional Context

Possibly failing because the Uri parser is expecting an image file extension such as .jpg? We had some issues with this on our own apps and found that making a get request to the URI and parsing the returned content-type in the response header was a good indicator of whether the link contained the document type we were expecting.

**Comment by DevaanshPathak** [comment]
@MayurSMahajan I want to work on this please assign it to me.

**Comment by MayurSMahajan** [comment]
Assigned. Have fun !

**Comment by DevaanshPathak** [comment]
It is a kind of SQL injection to be exact I am working on the uri parser for it to just expect img extensions and ignore the extra attributes.

**Comment by annieappflowy** [comment]
@DevaanshPathak , still working on this? need help?

**Comment by DevaanshPathak** [comment]
@annieappflowy I was working on it until yesterday but am unable to find a fix. Working on open source code is not as easy as it sounds.

**Comment by Xazin** [comment]
Since this issue was created, a lot has changed for the document cover, and I can't reproduce on MacOS anymore.

I'm going to close this for now, we can reopen or create a new issue if still needed.
