### ISSUE TITLE
[Bug] The setter 'observer' isn't defined for the type 'Bloc'

### ISSUE THREAD

**Issue by xurenda** [AppFlowy-IO/appflowy#37]
In `app_flowy/lib/startup/tasks/application_task.dart`,  line 19:
```
class AppWidgetTask extends LaunchTask {
  @override
  LaunchTaskType get type => LaunchTaskType.appLauncher;

  @override
  Future<void> initialize(LaunchContext context) {
    final widget = context.getIt<EntryPoint>().create();
    final app = ApplicationWidget(child: widget);
->Bloc.observer = ApplicationBlocObserver();
    runApp(app);

    return Future(() => {});
  }
}
```
The error arises: `The setter 'observer' isn't defined for the type 'Bloc'.`

I run: `flutter run -d macos`
Got:
```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:1606BB77-0B9B-5455-A3BF-7DE0EC417A85 }
{ platform:macOS, name:Any Mac }
lib/startup/tasks/application_task.dart:19:10: Error: Setter not found: 'observer'.
    Bloc.observer = ApplicationBlocObserver();
         ^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in parallel
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```
Does anyone know what to do? Thank you very much!

**Comment by appflowy** [comment]
@xurenda Would you mind showing me your flutter env by running: flutter pub get?

**Comment by xurenda** [comment]
@appflowy Sure, thanks for your reply.

`flutter pub get`:
```
Running "flutter pub get" in app_flowy...                        2,252ms
```

<details>
  <summary><code>flutter pub get -v</code></summary>
<pre>
[ +151 ms] executing: sysctl hw.optional.arm64
[  +32 ms] Exit code 0 from: sysctl hw.optional.arm64
[   +3 ms] hw.optional.arm64: 1
[   +8 ms] executing: [/Users/kingen/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2901cd720879ba3d7ba7cbd7d447ec9e80f937b6
[   +1 ms] executing: [/Users/kingen/flutter/flutter/] git tag --points-at 2901cd720879ba3d7ba7cbd7d447ec9e80f937b6
[  +26 ms] Exit code 0 from: git tag --points-at 2901cd720879ba3d7ba7cbd7d447ec9e80f937b6
[        ] 2.8.0-3.2.pre
[  +13 ms] executing: [/Users/kingen/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/kingen/flutter/flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +154 ms] Unable to locate an Android SDK.
[   +9 ms] executing: [/Users/kingen/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +9 ms] executing: sw_vers -productName
[  +31 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +18 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.5.2
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G95
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] Running "flutter pub get" in flutter_tools...
[   +6 ms] executing: [/Users/kingen/flutter/flutter/packages/flutter_tools/] /Users/kingen/flutter/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose get --no-precompile
[  +90 ms] MSG : Resolving dependencies...
[  +17 ms] MSG :   devtools_shared 2.7.0 (2.8.0 available)
[        ]     |   pedantic 1.11.1 (discontinued replaced by lints)
[        ]     |   shelf 1.1.4 (1.2.0 available)
[        ]     |   test 1.17.12 (1.19.3 available)
[        ]     |   test_api 0.4.3 (0.4.7 available)
[        ]     |   test_core 0.4.2 (0.4.8 available)
[        ]     |   vm_service 7.3.0 (7.5.0 available)
[        ] MSG : Downloading devtools_shared 2.7.0...
[        ] MSG : Downloading dwds 11.4.0...
[        ] MSG : Downloading dds 2.1.4...
[        ] MSG : Downloading archive 3.1.6...
[   +2 ms] MSG : Got dependencies!
[ +139 ms] Running "flutter pub get" in flutter_tools... (completed in 3.9s)
[  +24 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +98 ms] Found plugin flowy_editor at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_editor/
[   +8 ms] Found plugin flowy_infra_ui at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_infra_ui/
[   +4 ms] Found plugin flowy_sdk at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_sdk/
[   +2 ms] Found plugin flowy_infra_ui_web at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_infra_ui/flowy_infra_ui_web/
[  +91 ms] Running "flutter pub get" in app_flowy...
[   +3 ms] executing: [/Users/kingen/Desktop/code/app/app_flowy/] /Users/kingen/flutter/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --verbose get --no-precompile
[  +92 ms] MSG : Resolving dependencies...
[  +19 ms] MSG :   bloc 8.0.0 (8.0.1 available)
[        ]     |   build_resolvers 2.0.4 (2.0.5 available)
[        ]     |   dartz 0.10.0-nullsafety.2 (0.10.0 available)
[        ]     |   flutter_colorpicker 0.6.1 (1.0.2 available)
[        ]     |   flutter_svg 0.22.0 (0.23.0+1 available)
[        ]     |   freezed 0.14.5 (1.0.0 available)
[        ]     |   freezed_annotation 0.14.3 (1.0.0 available)
[        ]     |   path_provider_android 2.0.7 (2.0.8 available)
[        ]     |   quiver_hashcode 2.0.0 (3.0.0+1 available)
[        ]     |   test_api 0.4.3 (0.4.7 available)
[        ]     |   url_launcher 6.0.13 (6.0.14 available)
[        ] MSG : Downloading vector_math 2.1.1...
[        ] MSG : Downloading animations 2.0.2...
[        ] MSG : Got dependencies!
[  +98 ms] Running "flutter pub get" in app_flowy... (completed in 5.7s)
[  +54 ms] Found plugin window_size at /Users/kingen/.pub-cache/git/flutter-desktop-embedding-e48abe7c3e9ebfe0b81622167c5201d4e783bb81/plugins/window_size/
[  +36 ms] Found plugin flutter_inappwebview at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-5.3.2/
[   +1 ms] Found plugin flutter_keyboard_visibility at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_keyboard_visibility-5.1.0/
[        ] Found plugin flutter_keyboard_visibility_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_plugin_android_lifecycle at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_plugin_android_lifecycle-2.0.4/
[   +7 ms] Found plugin image_picker at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.8.4+4/
[        ] Found plugin image_picker_for_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/image_picker_for_web-2.1.4/
[   +7 ms] Found plugin package_info_plus at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/package_info_plus-1.3.0/
[        ] Found plugin package_info_plus_macos at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/package_info_plus_macos-1.3.0/
[   +1 ms] Found plugin package_info_plus_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/package_info_plus_web-1.0.4/
[   +1 ms] Found plugin path_provider at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider-2.0.7/
[        ] Found plugin path_provider_android at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_android-2.0.7/
[        ] Found plugin path_provider_ios at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_ios-2.0.7/
[        ] Found plugin path_provider_linux at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_linux-2.1.2/
[        ] Found plugin path_provider_macos at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_macos-2.0.3/
[        ] Found plugin path_provider_windows at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_windows-2.0.4/
[  +11 ms] Found plugin url_launcher at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher-6.0.13/
[   +1 ms] Found plugin url_launcher_linux at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_linux-2.0.2/
[   +1 ms] Found plugin url_launcher_macos at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_windows-2.0.2/
[   +1 ms] Found plugin video_player at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/video_player-2.2.7/
[        ] Found plugin video_player_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/video_player_web-2.0.4/
[   +4 ms] Found plugin flowy_editor at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_editor/
[   +1 ms] Found plugin flowy_infra_ui at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_infra_ui/
[   +1 ms] Found plugin flowy_sdk at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_sdk/
[        ] Found plugin flowy_infra_ui_web at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_infra_ui/flowy_infra_ui_web/
[  +37 ms] Found plugin window_size at /Users/kingen/.pub-cache/git/flutter-desktop-embedding-e48abe7c3e9ebfe0b81622167c5201d4e783bb81/plugins/window_size/
[   +7 ms] Found plugin flutter_inappwebview at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-5.3.2/
[        ] Found plugin flutter_keyboard_visibility at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_keyboard_visibility-5.1.0/
[        ] Found plugin flutter_keyboard_visibility_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_plugin_android_lifecycle at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_plugin_android_lifecycle-2.0.4/
[   +2 ms] Found plugin image_picker at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.8.4+4/
[   +1 ms] Found plugin image_picker_for_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/image_picker_for_web-2.1.4/
[   +2 ms] Found plugin package_info_plus at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/package_info_plus-1.3.0/
[        ] Found plugin package_info_plus_macos at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/package_info_plus_macos-1.3.0/
[        ] Found plugin package_info_plus_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/package_info_plus_web-1.0.4/
[        ] Found plugin path_provider at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider-2.0.7/
[        ] Found plugin path_provider_android at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_android-2.0.7/
[        ] Found plugin path_provider_ios at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_ios-2.0.7/
[        ] Found plugin path_provider_linux at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_linux-2.1.2/
[        ] Found plugin path_provider_macos at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_macos-2.0.3/
[        ] Found plugin path_provider_windows at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/path_provider_windows-2.0.4/
[   +8 ms] Found plugin url_launcher at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher-6.0.13/
[        ] Found plugin url_launcher_linux at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_windows-2.0.2/
[        ] Found plugin video_player at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/video_player-2.2.7/
[        ] Found plugin video_player_web at /Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/video_player_web-2.0.4/
[   +2 ms] Found plugin flowy_editor at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_editor/
[   +1 ms] Found plugin flowy_infra_ui at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_infra_ui/
[        ] Found plugin flowy_sdk at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_sdk/
[        ] Found plugin flowy_infra_ui_web at /Users/kingen/Desktop/code/app/app_flowy/packages/flowy_infra_ui/flowy_infra_ui_web/
[  +15 ms] Generating /Users/kingen/Desktop/code/app/app_flowy/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +51 ms] executing: sysctl hw.optional.arm64
[  +14 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +593 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[        ] Xcode 13.1
           Build version 13A1030d
[  +13 ms] "flutter get" took 10,842ms.
[ +266 ms] ensureAnalyticsSent: 259ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
</pre>
</details>

`app_flowy/.dart_tool/package_config.json`:
```
...
{
      "name": "bloc",
      "rootUri": "file:///Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/bloc-8.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
},
...
{
      "name": "flutter_bloc",
      "rootUri": "file:///Users/kingen/.pub-cache/hosted/pub.flutter-io.cn/flutter_bloc-8.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
},
...
```
Is there something wrong with my version?

Here is additional information:
<details>
  <summary><code>flutter doctor -v</code></summary>
<pre>
[✓] Flutter (Channel beta, 2.8.0-3.2.pre, on macOS 11.5.2 20G95 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.8.0-3.2.pre at /Users/kingen/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2901cd7208 (33 hours ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

! Doctor found issues in 3 categories.
</pre>
</details>

`flutter --version`:
```
Flutter 2.8.0-3.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2901cd7208 (33 hours ago) • 2021-11-18 11:15:09 -0800
Engine • revision bcc2b7f12c
Tools • Dart 2.15.0 (build 2.15.0-268.18.beta)
```

`dart --version`:
```
Dart SDK version: 2.15.0-268.18.beta (beta) (Wed Nov 17 11:39:23 2021 +0100) on "macos_x64"
```

**Comment by appflowy** [comment]
Thank you, the errors caused by the flutter_bloc version changed. I will fix it asap.

**Comment by appflowy** [comment]
@xurenda Done, Pulling the latest main branch code, please.

**Comment by xurenda** [comment]
@appflowy Great, it works fine!
