### ISSUE TITLE
[Bug] Incorrect version shown in realease v0.0.3 on Windows

### ISSUE THREAD

**Issue by Arbaba** [AppFlowy-IO/AppFlowy#370]
**Describe the bug**

An incorrect version is shown when clicking on the `?` button for `Help & Support`.

**To Reproduce**
1. Click on the `?` button at the bottom right of the screen to show the current version.

**Expected behavior**
`app_flowy 0.0.3` should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/25588945/155181712-e00aac51-74a6-45c1-a824-b1a4706610b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.0.3

**Comment by annieappflowy** [comment]
Fixed
<img width="140" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ff205b77-2462-42fd-8e5b-1eadae82eb77">
