### ISSUE TITLE
[FR] improve existing Japanese translation for AppFlowy

### ISSUE THREAD

**Issue by rbdog** [AppFlowy-IO/AppFlowy#3702]
### Description

As mentioned in issue #3464, I would like to improve Japanese translation in the json files.

### Impact

Japanese users and those who know the Japanese language.

### Additional Context

No response

**Comment by rbdog** [comment]
Hello, @annieappflowy.
Please assign me 🐶

**Comment by annieappflowy** [comment]
Assigned. Thank you, @rbdog
