### ISSUE TITLE
[Bug] Shortcut settings `Reset to default` is missing bottom margin

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3710]
### Bug Description

The button at the bottom of the `Shortcuts`-page in the Settings dialog, is missing bottom margin.

<img width="804" alt="Screenshot 2023-10-16 at 08 57 27" src="https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/328f36a3-3719-41a7-9b2c-8f9fe4e38b4b">

### How to Reproduce

1. Open AppFlowy
2. Open Settings
3. Navigate to `Shortcuts`
4. See the button does not have any bottom margin

### Expected Behavior

1. Open AppFlowy
2. Open Settings
3. Navigate to `Shortcuts`
4. The button has the proper bottom margin

### Operating System

All

### AppFlowy Version(s)

0.3.5

**Comment by SaadTanveer14** [comment]
Hi i would like to do it @Xazin ,
thanks

**Comment by Xazin** [comment]
> Hi i would like to do it @Xazin , thanks

I've assigned you :+1:
