### ISSUE TITLE
[FR] Option to go back to quick start menu after initialized

### ISSUE THREAD

**Issue by yuuz233** [AppFlowy-IO/AppFlowy#3720]
### Description

The quick start menu, which is the first menu after a fresh install, a way to be back was not found by me yet other than deleting/moving database in the original location it sets to. Could there be an intuitive way to "open this folder as appflowy db"?

### Impact

Nearly impossible to local sync database across devices.

### Additional Context

Intel Darwin Sonoma, 0.3.6 universal.

**Comment by annieappflowy** [comment]
<img width="654" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8efc95c7-3ffe-45d9-bf0e-97615949f938">
