### ISSUE TITLE
[Bug] Board/Grid/Calendar view -> Setting -> Properties overflow

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/AppFlowy#3740]
### Bug Description

The properties view shows an overflow error

### How to Reproduce

1. Add or navigate to any Grid/Calendar/Board
2. Press the Settings button in the top right
3. Press the Properties button

You will see the overflow error when it has many properties

### Expected Behavior

It should be scrollable when it exceed the maximum menu height.

### Operating System

macOS

### AppFlowy Version(s)

0.3.6

### Screenshots

<img width="269" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/7928396d-51d0-44de-94a2-f605319560e8">

**Comment by SaadTanveer14** [comment]
hi i would like to do it please.
