### ISSUE TITLE
[Bug] Code is hard to read with these themes ( using the lemon theme )

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3743]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/89271921-3242-44c5-ac3c-d9b8f4efe8dd)

### How to Reproduce

Use the theme "Lemonade" in the dark mode
Insert a code block

### Expected Behavior

Better contrast to view the text clearly in a code block

### Operating System

Windows 11

### AppFlowy Version(s)

v0.3.6

**Comment by MayurSMahajan** [comment]
Actually, that is the case for all dark themes. Not just Lemonade.
