### ISSUE TITLE
[Bug] font size option is showing overflowing error

### ISSUE THREAD

**Issue by SaadTanveer14** [AppFlowy-IO/AppFlowy#3749]
### Bug Description

The Russian and Ukrainian translation of font size option is showing overflowing error.

### How to Reproduce

1. Create a new page.
2. On the top right corner select the two dot button for more options.

Large font size button can be seen overflowing in case of Russian and Ukrainian language.

### Expected Behavior

Large font size button should either dynamically increase size or text inside the button should dynamically decrease size.

### Operating System

Windows 10

### AppFlowy Version(s)

0.3.6

### Screenshots

Russian

<img width="650" alt="Russian" src="https://github.com/AppFlowy-IO/AppFlowy/assets/99664282/579535cd-c87c-4793-baab-d8bc7a8c86d4">

Ukrainian

<img width="653" alt="Ukrainian" src="https://github.com/AppFlowy-IO/AppFlowy/assets/99664282/fe0a4f35-c7a9-4e1a-9ae8-d0956cbd611e">

**Comment by MayurSMahajan** [comment]
maybe we should increase the width of the container.

**Comment by SaadTanveer14** [comment]
> maybe we should increase the width of the container.

That would be ideal.

**Comment by Sumit4482** [comment]
Hey @SaadTanveer14 ,
I want to give it a try.
Can you please assign it to me?
@MayurSMahajan

**Comment by MayurSMahajan** [comment]
Assigned @Sumit4482!

**Comment by ZakAnun** [comment]
Hey @MayurSMahajan ,
I have tried to make modifications. Could you please help me review the code?
