### ISSUE TITLE
[Bug] pages show as empty gray

### ISSUE THREAD

**Issue by Generic-Ripe** [AppFlowy-IO/AppFlowy#3757]
### Bug Description

App starts with correctly populated left side bar but all pages are displayed as empty gray. Does this every time app starts.
Temp workaround: By changing data folder to something random and then change back to correct data folder all pages start to show as intended.

### How to Reproduce

No idea how to reproduce. 

### Expected Behavior

Page content visible when page selected on side bar.

### Operating System

Windows 11 Enterprise 22H2

### AppFlowy Version(s)

0.3.3 0.3.6

### Screenshots

![appflowy_screendump_gray_page](https://github.com/AppFlowy-IO/AppFlowy/assets/144800764/4cff6a59-26ae-44fc-9570-7fc19ccc09dd)

**Comment by Generic-Ripe** [comment]
A copy of data folder with other path does not help. It must be some other data folder with either empty initial data or a folder where app may create new initial data folder. Something in my current data seems wrong.

**Comment by annieappflowy** [comment]
Thanks for reporting!
Are you able to view and edit your existing workspace at the moment? 
We need this input to prioritize bug fixes.

**Comment by Generic-Ripe** [comment]
Without workaround pages are not editable. 
Everything else works as far as I have noticed so far.

**Comment by LucasXu0** [comment]
Hi, @Generic-Ripe. This issue has been resolved in the latest main branch and will be included in the next release version. The workaround is to switch the language to English.
