### ISSUE TITLE
[Bug] AppImage package missing some important libraries

### ISSUE THREAD

**Issue by elvanor** [AppFlowy-IO/AppFlowy#3760]
### Bug Description

Hi, I tried to install on my Gentoo system via the AppImage package and it did not work. I got the following error:

libkeybinder needs to be added to the AppImage libraries:
error while loading shared libraries: libkeybinder-3.0.so.0

Then once I installed libkeybinder on the system, got the following error:

symbol lookup error: /usr/lib64/libpango-1.0.so.0: undefined symbol: g_string_free_and_steal

Apparently it's because you bundle glib library within the AppImage package, but not libpango, so it uses system libpango that uses a new symbol in glib (g_string_free_and_steal). However since the glib bundled within AppImage is old, it does not have this symbol. So either you need to bundle libpango as well, or you need to update the glib library. But now it turns out it uses the system libpango with an outdated bundled glib, which does not work.

On a side note, I was able to start the .tar.gz package instantly. Only issue I have so far is a very small font size on my laptop screen (with large resolution). Increasing font size worked for contents but it's still very small in Settings etc.

### How to Reproduce

Start the AppImage package on a standard, stable amd64 system.

### Expected Behavior

AppImage package should start without any errors.

### Operating System

Gentoo Linux

### AppFlowy Version(s)

3.0.6

**Comment by Ahks** [comment]
Encountered similar on a clean install of Ubuntu 23.10

```
~/Apps$ ./AppFlowy-0.3.6-linux-x86_64.AppImage 
/tmp/.mount_AppFlotdRuxC/AppFlowy: symbol lookup error: /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0: undefined symbol: g_string_free_and_steal
```

A quick google points at a similar issue with glib versions as above. .tar.gz package works here too

```
$ sudo apt list --installed | grep glib2

libglib2.0-0/mantic,now 2.78.0-2 amd64 [installed,automatic]
libglib2.0-bin/mantic,now 2.78.0-2 amd64 [installed,automatic]
libglib2.0-data/mantic,now 2.78.0-2 all [installed,automatic]
libpackagekit-glib2-18/mantic,now 1.2.7-1 amd64 [installed,automatic]
```

Thanks for a great piece of software :)

**Comment by duckfat** [comment]
I encountered a similar issue on Manjaro when executing the .AppImage. (tar.gz works)
```
./AppFlowy-0.3.6-linux-x86_64.AppImage 
/tmp/.mount_AppFlo7Zowvw/AppFlowy: symbol lookup error: /usr/lib/libjson-glib-1.0.so.0: undefined symbol: g_string_free_and_steal
```

```
sudo pacman -Q | grep glib2
glib2 2.78.0-2
lib32-glib2 2.78.0-2


sudo pacman -Q | grep json
json-c 0.17-1
json-glib 1.8.0-1
jsoncpp 1.9.5-2
```

**Comment by LucasXu0** [comment]
Hi, @elvanor @Ahks @duckfat. I attempted to package libkeybinder into AppImage. Can you help to test this installation?

https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.3.7/AppFlowy-0.3.7-linux-x86_64.AppImage

**Comment by duckfat** [comment]
> Hi, @elvanor @Ahks @duckfat. I attempted to package libkeybinder into AppImage. Can you help to test this installation?
> 
> https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.3.7/AppFlowy-0.3.7-linux-x86_64.AppImage

it works
thank you
