### ISSUE TITLE
[Bug] lack of hints to guide users to add a reminder

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3761]
### Bug Description

However, I have not yet understood how to use notifications.   Can someone explain this to me? === Is it useful to repeat already reported errors when there has been no direct response? As a precaution, I am attaching problems already reported once again. 

- [ ]  add Reminder to the slash menu
- [ ]  add "Learn more about the reminders" in the reminder picker. click to open up the documentation 
- [ ]  add more hints to the reminder picker (at the moment, it doesn't have a hint)
<img width="255" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ed3c0708-3c2c-4593-b1dc-300a9f625fd9">

### How to Reproduce

type @ to mention a date to trigger the reminder picker

### Expected Behavior

More intuitive and user friendlier

### Operating System

macOS

### AppFlowy Version(s)

v0.3.6

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me
