### ISSUE TITLE
[Bug] Document show menu button has multiple tooltip on hover

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3762]
### Bug Description

Title says all

### How to Reproduce

Hover over the show menu button in a document

### Expected Behavior

This shouldn't happen

### Operating System

macOS

### AppFlowy Version(s)

latest main

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/0bc7a47e-5f4e-4bb0-9017-ac2293e8be40

**Comment by MayurSMahajan** [comment]
Hey @richardshiue can you now reproduce it with the latest main? I am not able to reproduce on Windows11 Latest Main as of commit: 71f80be

**Comment by richardshiue** [comment]
I can no longer reproduce this issue, but the cursor no longer changes to the hand cursor. If it does switch back to the hand cursor, it could still be causing the same issue
