### ISSUE TITLE
[Bug] Kanban group card display

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3764]
### Bug Description

Kanban: If a change is made in Settings>Group, the cards appear without content. Only if another page is selected and then again Kanban, the text is displayed. 

### How to Reproduce

Set up a Kanban Board 
Add a few cards including a few properties
Go to Settings -> Group -> Choose a group by property

### Expected Behavior

Can display cards properly

### Operating System

macOS

### AppFlowy Version(s)

v0.3.6

**Comment by richardshiue** [comment]
Hi @annieappflowy do you recall which field type you switched to? Or even better, configuration you had prior to triggering this bug? I can't seem to reproduce this

**Comment by annieappflowy** [comment]
any property in my board can reproduce the bug
