### ISSUE TITLE
[Bug] data update emoji in open as a page

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3765]
### Bug Description

I open a card (pic-1) and add an icon at the top of the card (pic-2). But when the card is closed, no icon is displayed (pic-3). When the card is opened again, the icon is gone there too (pic-4). If you then change the page and come back to the modified Kanban card, the icon is displayed in the card when you open it  (pic-5), but not when it is closed.

### How to Reproduce

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c2040d66-baa5-49db-bcb5-fdf51bae9339)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/934ab9f2-31a8-4a48-b221-b79b9aadd207)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/314ac904-2648-435b-a72a-d58bfe7b21b4)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/caaf7fa0-bc05-4938-a3c9-ca82eea8633a)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8c917c1e-7e29-46a1-8192-74f5f80b42fa)

### Expected Behavior

After adding an icon, it's immediately saved and display in the open as a page

### Operating System

macOS

### AppFlowy Version(s)

v0.3.6

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me

**Comment by annieappflowy** [comment]
@lalitkumawat1m , are you still working on this?
