### ISSUE TITLE
[Bug] Notes with inserted tables bug if we select them through tabs

### ISSUE THREAD

**Issue by Rasterisko** [AppFlowy-IO/AppFlowy#3780]
### Bug Description

Changing notes with inserted tables through tabs will freeze AppFlowy and start to increase memory consumption indefinitely.

### How to Reproduce

1. Create two notes, one of which has a table inserted
2. Open the two notes with tabs
3. Change from the note that don't have table inserted to the note that have the table inserted using tab
4. Look at the ram consumption of the software on your computer

### Expected Behavior

That wouldn't freeze and that wouldn't start increasing RAM consumption indefinitely

### Operating System

Linux Mint 21.2

### AppFlowy Version(s)

0.3.6

**Comment by Xazin** [comment]
I couldn't reproduce it on Windows and haven't tried it on MacOS yet.

**Comment by annieappflowy** [comment]
cannot reproduce on macOS

**Comment by marco4mp** [comment]
Hi, I tried to reproduce the issue and the same thing happens to me using Linux (Fedora 39). 
I recorded a video showing the steps to reproduce the issue.


https://github.com/AppFlowy-IO/AppFlowy/assets/52709674/29eea908-fbf7-4af1-8ce3-3daf98f3cb72

**Comment by annieappflowy** [comment]
Will fix it when working on the tab improvements

**Comment by Xazin** [comment]
This has been resolved 🙏
