### ISSUE TITLE
[Bug] Plus symbol is outside the card in Multiselect Card.

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#3784]
### Bug Description

Originally posted by MacMeikel#6475 in discord.

> I use W11-Home (22H2, Build 22621.2428) and AppFlowy-portable (V0.3.6). Here's what I just noticed: 1) Kanban: When I add a new property with "multi-select" and then want to add new options, then for language "English" nothing happens when I click on the plus symbol and for language "German" the card is too narrow so that the plus symbol is outside the card and cannot be selected (see screenshots). Is the plus symbol necessary at all, since a new option is automatically created when text is entered?

### How to Reproduce

1. Switch your AppFlowy Langauge to German, Deutsch.
2. Create or Open a Kanban Board.
3. Create or Open and Expand a card within the board.
4. Add or Edit a new field with type Multiselect
5. Observe how the plus button appears outside the card.

### Expected Behavior

The plus button should appear within the card.

### Operating System

All

### AppFlowy Version(s)

v0.3.6

### Screenshots

![plus_in_deutsch](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/d9149e8a-454b-4f06-b59a-c83ec83bb7ef)

![plus_in_english](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/54968c8b-3e0b-43da-b399-f5966ed116d5)

### Additional Context

How this issue should be solved depends on how the team thinks and wants this design to be.

**Comment by bryanoli** [comment]
Hello @MayurSMahajan  can I work on this issue

**Comment by MayurSMahajan** [comment]
Sure @bryanoli! Thanks for helping out.
