### ISSUE TITLE
[Bug]  Multiple duplicate shortcuts appear within the shortcuts tab.

### ISSUE THREAD

**Issue by Kritarthsharma** [AppFlowy-IO/AppFlowy#3791]
### Bug Description

Multiple duplicate shortcuts appear within the shortcuts tab.

### How to Reproduce

1. Open AppFlowy
2. Go to settings
3. Go to the shortcuts tab

### Expected Behavior

Should not be displaying duplicate shortcuts

### Operating System

All

### AppFlowy Version(s)

0.3.7

### Screenshots

<img width="1115" alt="Screenshot 2023-10-26 at 1 04 07 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/42487588/b79bffe1-68f4-44db-9430-7c533b044cf4">
<img width="1115" alt="Screenshot 2023-10-26 at 1 05 18 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/42487588/7402e40e-575a-4b3d-9033-120c2d7929e3">

**Comment by Kritarthsharma** [comment]
Hi team. I can work on this issue and close this.

**Comment by annieappflowy** [comment]
Assigned! Thanks for helping

**Comment by hyj1204** [comment]
solved by #4196
