### ISSUE TITLE
[Bug] The + icon should disappear when swiping left 

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3793]
### Bug Description

Needs Design.

<img width="301" alt="Screenshot 2023-10-26 at 17 18 52" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/9f1c9c60-f2c2-4bb4-8fe5-276c353b62a4">

### How to Reproduce

- swipe the page item to left side

### Expected Behavior

TBD

### Operating System

mobile

### AppFlowy Version(s)

0.3.7

**Comment by vinaykatewa** [comment]
Hi @LucasXu0 did you already solved this? Can i work on this as my first issue.

**Comment by LucasXu0** [comment]
> Hi @LucasXu0 did you already solved this? Can i work on this as my first issue.

Not yet. Sure. By the way, this issue occurs on the mobile platform.

**Comment by vinaykatewa** [comment]
Thanks I'll try to solve this then, also is this issue occur in android right?

**Comment by LucasXu0** [comment]
Yes. Android and iOS.

**Comment by vinaykatewa** [comment]
I just set the whole code base on my laptop and it's running fine on desktop (by AF-desktop: Clean + Rebuild All) but its giving errors while i run it for android (AF-Android: Clean + Rebuild All).
Is there something you know about this?

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/3713

You can refer to this PR.

**Comment by vinaykatewa** [comment]
Still same error
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/103169973/1eff73b2-65c1-482d-8b2a-89a5263d106e)

**Comment by LucasXu0** [comment]
@vinaykatewa Can you post the error messages?

**Comment by vinaykatewa** [comment]
The error message is too long.
Here is first few of them

Error: 'RowMetaPB' isn't a type.
board_bloc.freezed.dart:1041
    TResult? Function(GroupPB group, RowMetaPB row, int? index)? didCreateRow,
                                     ^^^^^^^^^
: Error: 'GroupPB' isn't a type.
board_bloc.freezed.dart:1042
    TResult? Function(GroupPB group, RowMetaPB row)? startEditingRow,
                      ^^^^^^^
: Error: 'RowMetaPB' isn't a type.
board_bloc.freezed.dart:1042
    TResult? Function(GroupPB group, RowMetaPB row)? startEditingRow,
                                     ^^^^^^^^^
: Error: 'FlowyError' isn't a type.
board_bloc.freezed.dart:1044
    TResult? Function(FlowyError error)? didReceiveError,
                      ^^^^^^^^^^
: Error: 'DatabasePB' isn't a type.
board_bloc.freezed.dart:1045
    TResult? Function(DatabasePB grid)? didReceiveGridUpdate,
                      ^^^^^^^^^^
: Error: 'GroupPB' isn't a type.
board_bloc.freezed.dart:1046
    TResult? Function(List<GroupPB> groups)? didReceiveGroups,
                           ^^^^^^^
: Error: 'GroupPB' isn't a type.
board_bloc.freezed.dart:1060
    TResult Function(GroupPB group, RowMetaPB row, int? index)? didCreateRow,
                     ^^^^^^^
: Error: 'RowMetaPB' isn't a type.
board_bloc.freezed.dart:1060
    TResult Function(GroupPB group, RowMetaPB row, int? index)? didCreateRow,
                                    ^^^^^^^^^
: Error: 'GroupPB' isn't a type.
board_bloc.freezed.dart:1061
    TResult Function(GroupPB group, RowMetaPB row)? startEditingRow,
                     ^^^^^^^
: Error: 'RowMetaPB' isn't a type.
board_bloc.freezed.dart:1061
    TResult Function(GroupPB group, RowMetaPB row)? startEditingRow,
                                    ^^^^^^^^^
: Error: 'FlowyError' isn't a type.
board_bloc.freezed.dart:1063
    TResult Function(FlowyError error)? didReceiveError,
                     ^^^^^^^^^^
: Error: 'DatabasePB' isn't a type.
board_bloc.freezed.dart:1064
    TResult Function(DatabasePB grid)? didReceiveGridUpdate,

**Comment by LucasXu0** [comment]
@vinaykatewa I think the main reason is that the Rust library build failed. Can you please try running this command in the 'frontend/rust-lib/' folder?

```
PS C:\Users\Desktop\AppFlowy\frontend\rust-lib> cargo ndk -t arm64-v8a build
```

**Comment by vinaykatewa** [comment]
Its saying i don't have ndk but in the picture about you can see i have NDK

cargo ndk -t arm64-v8a build
info: syncing channel updates for '1.70-x86_64-pc-windows-msvc'
info: latest update on 2023-06-01, rust version 1.70.0 (90c541806 2023-05-31)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
error: no such command: `ndk`

        Did you mean `add`?

        View all installed commands with `cargo --list`

**Comment by LucasXu0** [comment]
It's not NDK; it's cargo-ndk. To install it, you should use Cargo.

```
cargo install cargo-ndk
```
