### ISSUE TITLE
[FR] Cutting and pasting of Reminders does not work

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#3795]
### Description

When using cut, and paste on Reminders, nothing happens.

Expected Behavior:
- Cutting a Reminder: Should delete the Reminder
- Pasting a Reminder: Should add a new Reminder (Update ID to not have duplicates in case the paste is a result of a copy)

### Impact

- Follows the users expected behavior
- Ease of use, ability to move Reminders around

**Comment by bryanoli** [comment]
Hello @Xazin I would like to work on this issue for hacktober. Can you give me the steps to how to create a Reminder?

**Comment by bryanoli** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/66151079/88d77cef-bbd4-4862-ab38-d91921987584

Is this the reminder that we are suppose to check for the cut and paste or is there a different one?

**Comment by Xazin** [comment]
> AppFlowy.2023-10-27.19-03-04.mp4 
> Is this the reminder that we are suppose to check for the cut and paste or is there a different one?

Yes it is, but this is definitely not a beginner feature, I don't mind assigning you if you are confident.

**Comment by rileyhawk1417** [comment]
@bryanoli are you working on this issue?

**Comment by bryanoli** [comment]
@rileyhawk1417 No I am not.

**Comment by annieappflowy** [comment]
Also there's a small bug with @remind. I'm not sure you know of it. Adding a @remind and setting it, then deleting doesn't remove it from notifications.
I just created 2 for tomorrow and another one for next week. Deleted the first two in document and added one for next week, but they're still all under "upcoming" in notifications.
