### ISSUE TITLE
[FR] adding more options than the input bar can fit

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3797]
### Description

<img width="337" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/53131774-e651-4b1e-b4b4-8f4059ac8aa9">

As shown in the screenshot, the third option takes up more space than the input bar can fit
In this scenario, the cursor should jump to the end and be shown in the input bar

### Impact

Database select and multi-select users

**Comment by Xazin** [comment]
I assume this can be fixed very easily without the below by an interim solution, but I'm going to leave them some references below:

https://github.com/AppFlowy-IO/AppFlowy/issues/3453
https://material.angular.io/components/chips/overview#chips-input
https://v4.mui.com/components/autocomplete/#multiple-values
https://primeng.org/chips

**Comment by Devas45** [comment]
Thanks to @Xazin references to PrimeNG Chips

I made changes to the select_option.dart as follows::

1.Using InputChip widgets to display options as chips.

2.Ensuring compatibility with PrimeNG's ChipsModule .
(Added dependencies)

Suggest the changes to be made.

`class _OptionChips extends StatelessWidget {
  final List<SelectOptionPB> options;
  final PopoverMutex? popoverMutex;

  const _OptionChips(this.options, this.popoverMutex, {Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: 8.0, 
      children: options.map((option) {
        return InputChip(
          label: Text(option.name), 
          selected: option.selected, 
          onSelected: (selected) {
            context.read<SelectOptionTypeOptionBloc>().add(
              SelectOptionTypeOptionEvent.toggleSelection(option),
            );
          },
          onDeleted: () {
            context.read<SelectOptionTypeOptionBloc>().add(
              SelectOptionTypeOptionEvent.deleteOption(option),
            );
          },
        );
      }).toList(),
    );
  }
}`

**Comment by annieappflowy** [comment]
@Devas45 , would you like to submit a PR? We'll review

**Comment by annieappflowy** [comment]
Fixed
