### ISSUE TITLE
[Bug] Capital letters in the translation files

### ISSUE THREAD

**Issue by MidouWebDev** [AppFlowy-IO/AppFlowy#380]
**Describe the bug**
The first letter of each word in the translation files is a capital letter except in the fr-FR.json that i worked on. #371 
So i want to fix this in all the translation files.
Please assign me !

@annieappflowy

**Comment by MikeWallaceDev** [comment]
Please make sure that is the correct procedure for each language that you wish to modify. 
For example, here are some recommendations for English capitalization : https://ni.github.io/design-system/style/text-capitalization/
