### ISSUE TITLE
[Bug] option value in dark mode

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3801]
### Bug Description

<img width="249" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/871cb93c-90d9-4362-a3c9-6c4ace426e2d">

### How to Reproduce

Try to add an option to a select / multi-select column

### Expected Behavior

better contrast

### Operating System

Windows 11

### AppFlowy Version(s)

v0.3.7

**Comment by rituraj2000** [comment]
@annieappflowy Please assign it to me

**Comment by rituraj2000** [comment]
Thanks @richardshiue for assigning the issue. I am new to opensource. Could you provide me more context for this issue?

**Comment by rituraj2000** [comment]
@annieappflowy could you please elaborate the issue further?

**Comment by richardshiue** [comment]
Please set up the environment based on instructions from our documentation [docs.appflowy.io](https://docs.appflowy.io/docs/documentation/appflowy/from-source) and then start looking for the component which has this bug. If you run into problems, you can reach out to me on discord. You can find me in the AppFlowy discord channel

**Comment by rituraj2000** [comment]
> Please set up the environment based on instructions from our documentation [docs.appflowy.io](https://docs.appflowy.io/docs/documentation/appflowy/from-source) and then start looking for the component which has this bug. If you run into problems, you can reach out to me on discord. You can find me in the AppFlowy discord channel

Thanks for replying! I have setup the environment. I just wanted a little more elaboration regarding the issue here and how can i replicate this.

**Comment by richardshiue** [comment]
You can replicate this issue like the video below illustrates

https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/11b13797-9158-49c9-a1a7-46043d605fa2
