### ISSUE TITLE
[Bug] '+' to add an option to a select column

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3802]
### Bug Description

I use W11-Home (22H2, Build 22621.2428) and AppFlowy-portable (V0.3.6). Here's what I just noticed: 1) Kanban: When I add a new property with "multi-select" and then want to add new options, then for language "English" nothing happens when I click on the plus symbol and for language "German" the card is too narrow so that the plus symbol is outside the card and cannot be selected (see screenshots). Is the plus symbol necessary at all, since a new option is automatically created when text is entered?
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/80811825-42aa-4dcd-99a8-b679ca1f7279)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/0c180fd1-f33b-4f62-a673-d9d5a8bde60d)

### How to Reproduce

Try to click '+' to add an option to a select column

### Expected Behavior

I can click '+' to add a new option

### Operating System

Windows 11

### AppFlowy Version(s)

v0.3.7

**Comment by rituraj2000** [comment]
@annieappflowy Please assign this issue to me. I would like to work on this

**Comment by MayurSMahajan** [comment]
Guys this issue is actually already solved #3784
