### ISSUE TITLE
[Bug] Flowy Icon button wrong color in specific circumstances

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#3820]
### Bug Description

Title says all

### How to Reproduce

Follow the steps in the video below

1. Click and hold on the button, the icon at this point is of the correct color
2. move cursor outside of the button, hover effect is now disabled (the mouse button is still being pressed btw)
3. move it back in 
4. observe that the icon doesn't change color

### Expected Behavior

The icon should change color

### Operating System

macos

### AppFlowy Version(s)

latest main

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/73d6cebf-e68c-46b3-a944-c111bc41c40f

**Comment by SharmaDhruv2511** [comment]
Hi @richardshiue I want to work on this issue. Can you please assign it to me?

**Comment by richardshiue** [comment]
Hi @SharmaDhruv2511 are you able to reproduce this issue? I'm no longer seeing it on my end

**Comment by SharmaDhruv2511** [comment]
I just show the issue open and seems doable so i ask it to work on it. This issue no longer exist by end also
