### ISSUE TITLE
[Bug] can't typed multiple words in a snake case format

### ISSUE THREAD

**Issue by EvgenyAfanasev** [AppFlowy-IO/AppFlowy#3824]
### Bug Description

When I typed some word in format: {snake_case} and added another word with snake_case to this line, app comes broken and I can't write any word without restart

### How to Reproduce

Write next words in one line (including spec symbols):
{sname_case}/another_word 

### Expected Behavior

all characters will be typed

### Operating System

Windows 10

### AppFlowy Version(s)

0.3.6

**Comment by annieappflowy** [comment]
#3964

**Comment by annieappflowy** [comment]
Cmd / Ctrl + Z to escape the markdown syntax

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ae9526f3-07fe-408c-ad56-97191bebe676
