### ISSUE TITLE
[FR] Add a horizontal scrollbar for kanban boards

### ISSUE THREAD

**Issue by SOSeriously** [AppFlowy-IO/AppFlowy#3826]
### Description

Please add a horizontal scrollbar for kanban boards and a help icon that shows the shortcut for scrolling kanban boards (shift + mouse scroll). It is not clear on how to scroll through kanban boards at first and especially for beginners.

### Impact

Anyone who uses kanban boards will benefit from it.

**Comment by annieappflowy** [comment]
@richardshiue , will this be supported in v0.3.7 since we bumped up the kanban package?

**Comment by Xazin** [comment]
Relates #3825
