### ISSUE TITLE
[Bug] Self-hosting with Supabase doesn't seem to work

### ISSUE THREAD

**Issue by ekisu** [AppFlowy-IO/AppFlowy#3829]
### Bug Description

When following the [guide](https://blog.appflowy.io/self-hosting-appflowy-free-using-supabase/) to self-host AppFlowy with Supabase, the generated application on the Releases page doesn't seem any different from the normal AppFlowy program (as in, there's no sign in screen, documents are saved on the local machine, etc)

### How to Reproduce

Follow the guide linked above

### Expected Behavior

The generated application to look like the one screenshotted in the guide, and my notes to be stored in the cloud, and not locally

### Operating System

Windows 11

### AppFlowy Version(s)

I suppose it's the latest main commit, by looking at the workflow on the template

**Comment by smartyhero** [comment]
I also encountered the same situation

**Comment by appflowy** [comment]
Would you mind sending your download page of self-host AppFlowy?

**Comment by smartyhero** [comment]
https://github.com/smartyhero/AppFlowy-App-Supabase-Template/releases/tag/0.3.0.4_main

**Comment by ekisu** [comment]
https://github.com/ekisu/AppFlowy-App-Supabase-Template/releases/tag/0.3.0.4_main

**Comment by appflowy** [comment]
Thank you very much! I've corrected the issue and updated the documentation, which you can find here: [Self-Hosting AppFlowy Using Supabase](https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy-using-supabase#how-to-self-host-appflowy-with-supabase).

It's necessary to add the `CLOUD_TYPE` variable.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/86001920/23837f5f-d798-44ab-82b0-76957bdbcc8a)

Please synchronize your forked template with the main repository. The build CI script has been updated as well.
[AppFlowy-App-Supabase-Template](https://github.com/AppFlowy-IO/AppFlowy-App-Supabase-Template)

**Comment by annieappflowy** [comment]
Let us know if you need help
