### ISSUE TITLE
[FR] Support sections

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3844]
### Description

Since there is already a section named "Personal", psychologically it meant to be the top level header. When organising something, wouldn't you prefer having multiple table rather than one very big table with infinity drawer?

Also the section is kind of easy to fold and unfold. On the other hand pages inside the section required to click on the little arrow icon in the left to fold and unfold it. So I think it would be user friendly as well

### Impact

Power users who want dedicated spaces within the same workspace

**Comment by annieappflowy** [comment]
maybe Work, I have YouTube channel, so I might have a section only for my channels content planning.

**Comment by inson1** [comment]
#3974
