### ISSUE TITLE
[Bug] Language change for items in the slash menu only applies when restarting the app

### ISSUE THREAD

**Issue by jramke** [AppFlowy-IO/AppFlowy#3858]
### Bug Description

I set up appflowy and set the language to german in the first startup screen. When i wanted to set language back to english i went to the settings and the language setting still showed english as active language. 
After setting it again to german and back to english i recognized that the popup when typing the `/` is still german like i set it in the startup screen.
The change only applied after a restart.

### How to Reproduce

In new installation setup, set language to german, then try to change it back to english in settings.

### Expected Behavior

Also update the translation of the popup or provide a small hint that you sould restart the app to update all translations.

### Operating System

MacOS

### AppFlowy Version(s)

0.3.7

**Comment by annieappflowy** [comment]
Supplement: 1) You have to switch the active page of Appflowy once to switch the language of the /-menu. After that it is partly in English and in German. (s. screenshot)

**Comment by annieappflowy** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/51bd4f70-08f6-40b0-b116-c24fbf0c6a9a)
