### ISSUE TITLE
[Bug] Delayed inputs on keypress

### ISSUE THREAD

**Issue by ZibingZhang** [AppFlowy-IO/AppFlowy#386]
### Describe the bug
There are multiple instances where, after a keypress, the result of the keypress is delayed until another key has been pressed.

### Steps to reproduce the behavior:
Either,
1. Navigate to the getting started page
2. Delete the "g" of the word "blog" at the bottom of the page
3. Try typing in the letter "g" again
4. It's not appearing for me until I type in another character

or,

1. Navigate to a new page (sorry if that's not the proper terminology)
2. Type the pound sign (#). You might have to play around with this a bit, it only happens in certain scenarios.
3. Sometimes, the sign won't appear until another key is pressed.

### Expected behavior
I would expect the keypress to show up immediately.

#### System Information
OS: Microsoft Windows 10 Home
Version: 10.0.19043 Build 19043
System Manufacturer: Dell Inc.
System Model: XPS 13 7390
System Type: x64-based PC

Downloaded application for Windows

**Comment by annieappflowy** [comment]
Cannot reproduce.
Please try the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases)
