### ISSUE TITLE
[Bug] copy paste a bulleted list from outside

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3865]
### Bug Description

I select Bulleted List and a bullet point and the word List appears. The cursor flashes in front of the "L". I switch to another program e.g. Browser copy a word (ctrl+c). Then I go back to Appflowy and paste the clipboard (ctrl-v). Then the bullet point disappears. (see screenshot). But this does not happen when copying words inside AppFlowy!!! 🤔  (I could create a video otherwise).

### How to Reproduce

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/948a6999-95c6-4915-b066-8608812ef12e)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/54460ee3-7c67-4396-9eae-84e87ea48946)

### Expected Behavior

the bullet list should stay after copy-pasting pure text (or with the bullet) 

### Operating System

macOS

### AppFlowy Version(s)

v0.3.7

**Comment by omavi** [comment]
I've experienced this issue as well. I'm not familiar with this codebase but if someone points me in the right direction, I may open a PR.

**Comment by zhouxinghong** [comment]
+1

**Comment by annieappflowy** [comment]
cmd/ctrl + shift + v works for me
Please reopen if this method doesn't work for you
