### ISSUE TITLE
[Bug] AppFlowy tries to retrieve google fonts constantly

### ISSUE THREAD

**Issue by Moini** [AppFlowy-IO/AppFlowy#3871]
### Bug Description

I've just tested AppFlowy, and as I didn't really trust it too much, I put it into firejail with no internet access.

Turns out the program is constantly trying to access Google Fonts to load the Roboto font, for whatever obscure reason (my bet would be, it's using some kind of dependency that does it, and noone has bothered).

### How to Reproduce

1. Download AppImage
2. chmod +x
3. firejail --net=none --appimage AppFlowy-0.3.7-linux-x86_64.AppImage

### Expected Behavior

1. AppFlowy should not need to access the internet to load fonts
2. AppFlowy should ask before it tries to access the internet, after all, it is a note-taking application.
3. AppFlowy should have a privacy policy, if it does otherwise, ESPECIALLY when it tries to access Google sites without the user's knowledge
4. AppFlowy should be using local fonts. I have Roboto installed. If it really needs a font, it can package it, or require it as a dependency.

### Operating System

Linux

### AppFlowy Version(s)

0.3.7

### Screenshots

![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/3240233/91e4ac46-bbf9-42bc-a0eb-4d0d001e4955)

### Additional Context

Data protection and privacy are normally very important to open source users. 

Unrequested calls to Google violate that expectation.

**Comment by Xazin** [comment]
Hey, we actually do have a privacy policy https://appflowy.io/privacy

I understand your concern, but this is intentional and not something we didn't "bother" with.

I agree that the application should work without requiring to fetch fonts from Google, maybe we can make it optional and include a default font in the application.

**Comment by Moini** [comment]
Thanks - it wasn't obvious *in the app*, especially as the promise is that it works 100% offline (as far as I remember, I looked at multiple note taking apps).

**Comment by annieappflowy** [comment]
Hi @Moini , thanks for testing and reporting this issue. The practice is obviously not the best to a local first app. I consider it an oversight as we don't thoroughly review the code implemented the logic. We will have a fix as soon as possible.

**Comment by Moini** [comment]
Thanks, @LucasXu0 & @annieappflowy !
