### ISSUE TITLE
Use an .ics file and sync with normal calendars

### ISSUE THREAD

**Issue by Moini** [AppFlowy-IO/AppFlowy#3872]
### Description

When I saw in the feature description that AppFlowy was able to use calendars, I got the impression that I could import and write to my normal, synced calendars with it. 

So when I tried it out, I was looking for options to import an existing calendar, however, that does not seem possible.

Neither is it possible to export a calendar as a standardized calendar file.

I don't know whether this is on the roadmap yet, but it would make AppFlowy's calendar feature so much more useful.

### Impact

Everyone who uses the calendar feature. Syncing them with other calendar apps would make it possible to not have to have two calendars. 

The AppFlowy calendars cannot import appointments, or anything, so one would always need a second calendar, and keeping them in sync manually is not something I would ever want to do.

**Comment by annieappflowy** [comment]
Thanks @Moini for the input!
Syncing with other calendars is included in our Q1 2024 roadmap.

**Comment by Moini** [comment]
Oh, that's great to read, @annieappflowy ! Closing.
