### ISSUE TITLE
[Bug] Docker Hub (app_flowy:1): Gtk-WARNING **: 10:44:25.079: cannot open display: 

### ISSUE THREAD

**Issue by tenneck** [AppFlowy-IO/AppFlowy#389]
When using the instructions provided at https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker with the container from Docker Hub I receive the following error: 

(app_flowy:1): Gtk-WARNING **: 10:44:25.079: cannot open display: 

System information:
MacBook Air (Retina, 13-inch, 2018)

Is anything missing here?

Thank you!

**Comment by bolshoytoster** [comment]
@tenneck note the text on the page you linked:

> Note: Appflowy inside docker needs access to your X server. In case of lack of permissions, it's recommended to build the docker image yourself. The least recommended option is running xhost + before running the container, but this command is ! So make sure you run xhost - after it.

You might need to run `xhost +` on your host to give permission to the for the docker process to access it.

Make sure to run `xhost -` afterwards otherwise anyone on your network would be able to connect.

**Comment by Ab19a1l** [comment]
Same problem is happening, but I am building on VM, do i need to do anything else to set it up?

**Comment by Loocos** [comment]
> @tenneck note the text on the page you linked:
> 
> > Note: Appflowy inside docker needs access to your X server. In case of lack of permissions, it's recommended to build the docker image yourself. The least recommended option is running xhost + before running the container, but this command is ! So make sure you run xhost - after it.
> 
> You might need to run `xhost +` on your host to give permission to the for the docker process to access it.
> 
> Make sure to run `xhost -` afterwards otherwise anyone on your network would be able to connect.

In my case, I'm getting the same message "xhost:  unable to open display """  when I type `xhost +`
I'm not familiar with this and made search in order to understand what's going on and what I'm doing wrong but I still don't know why.

@bolshoytoster Could I ask you why it's needed and blocking ? I would want to use it as a web app only. 

Help would be really appreciated

Thanks in advance for your anwsers.

**Comment by bolshoytoster** [comment]
@Loocos could you try running appflowy with `DISPLAY=:0`?

So like `DISPLAY=:0 docker run ...`

**Comment by Loocos** [comment]
> @Loocos could you try running appflowy with `DISPLAY=:0`?
> 
> So like `DISPLAY=:0 docker run ...`

Still same, I've tried everything. But I think I got the anwser by joining the discord, I found this issue : https://github.com/AppFlowy-IO/AppFlowy/issues/313
And that's what I'm trying to do. I want to host it and use it on my domain. But it's currently available only for local mode

**Comment by MikeWallaceDev** [comment]
@Loocos Please be advised that AppFlowy currently does not run as a web app...

**Comment by Loocos** [comment]
@MikeWallaceDev Yes, I've read that after. So currently, can I host the solution on a linux based system (dedicated server) and use it for myself and a friend, then share docs between us in two different network ?
Thanks for your confirmation!

**Comment by MikeWallaceDev** [comment]
@Loocos so sorry, I never saw this.

AF is currently a single user desktop application. We don't support multi-user yet.  

However, what magic that you are able to do with symlinks and a cloud to share data, that's up to you.  :)  I've never tried it, and I have no clue what will happen if two users modify the pages at the same time.
