### ISSUE TITLE
[FR] improve the mobile UI

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3895]
### Description

improve the mobile UI.

- toolbar item - callout

<img width="469" alt="Screenshot 2023-11-07 at 17 31 31" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/1c9dae86-b3cd-4d2d-af15-c6455c1a425d">

- math equation - icon

<img width="476" alt="Screenshot 2023-11-07 at 17 32 17" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/e1a15ad8-40de-42d3-83f1-94e5073c3810">

- actions icon

<img width="465" alt="Screenshot 2023-11-07 at 17 34 01" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/6c5d8bf6-b4c1-40ec-bfc1-c90ca1819d33">
<img width="471" alt="Screenshot 2023-11-07 at 17 34 37" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/143ea0db-f9d2-4324-bb0e-46ce5d51ab98">

- emoji page

<img width="543" alt="Screenshot 2023-11-07 at 17 34 47" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/6b06e3c4-3376-4190-8315-979c9a3d3f44">

**Comment by rohit27-2** [comment]
Hey @LucasXu0, Good to meet you. I would like to take this up.

Thank you
Best Regards,
Rohith G

**Comment by LucasXu0** [comment]
Hi, @rohit27-2. I have assigned to you.

**Comment by LucasXu0** [comment]
Update:

<img width="533" alt="Screenshot 2023-11-12 at 18 31 35" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/2ac00dc4-7e7a-4ece-8e2c-7828eefa76c4">

Improve the page icon for the mobile platform. Currently, the page icons are transparent, and they don't look good in the recent section.

**Comment by rohit27-2** [comment]
Okay, I'm on it!
Thank you!
