### ISSUE TITLE
[FR] Add .vscode/settings.json to .gitignore

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#3897]
### Description

I plan to integrate [FVM](https://fvm.app/) into the AppFlowy project. Since FVM recommends developers to add the '.fvm/flutter_sdk' directory to the settings.json, and I want to ensure that it doesn't affect developers who don't use FVM to run our project, I suggest adding the `settings.json` file to the `.gitignore`.

### Impact

- the developers who use fvm

**Comment by AnsahMohammad** [comment]
Is this issue still relevant ?

**Comment by LucasXu0** [comment]
> Is this issue still relevant ?

Yes.

**Comment by AnsahMohammad** [comment]
Okay, i've made a PR
