### ISSUE TITLE
[FR] RTL support

### ISSUE THREAD

**Issue by asafm** [AppFlowy-IO/AppFlowy#39]
**1~3 main use cases of the proposed feature**
Notion doesn't have right to left languages support. This can be a great thing to have in the open source 

**what types of users can benefit from using your proposed feature**
Population of world using right to left languages 

**Additional context**

**Comment by notd5a-alt** [comment]
I think this would be possible to implement once the developers implement their plugin system for the app.

**Comment by zoli** [comment]
@annieappflowy If by plugin label you mean appflowy editors plugin, How this can be implemented via plugin? From what I see for supporting RTL in Appflowy document which is mostly related to appflowy editor core. Appflowy editor should enable setting `textDirection` on `RichText` which `FlowyRichText` builds it.

**Comment by zoli** [comment]
Just noting some thoughts here: 
Probably `TextNode` should support direction attribute which sets the `RichText` `textDirection` property.
There could be LTR, RTL, AUTO for `TextNode` direction attribute which could get determined by appflowy toolbar. As `RichText` doesn't support AUTO internally appflowy editor should handle that part itself (maybe with strong directionality concept).

**Comment by zoli** [comment]
I would like to take on this.

cc: @annieappflowy

**Comment by annieappflowy** [comment]
Thank you!!

**Comment by zoli** [comment]
Now Appflowy Editor supports RTL. IMO the next step will be RTL support in Appflowy Board and Grid.

**Comment by annieappflowy** [comment]
@asafm, please try out the latest [release ](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.3.3)

Toggle on the RTL switch in Settings to write in the RTL layout


![Image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/605606f8-2b4f-493b-b3cc-7b2e0e0c164b)

**Comment by zoli** [comment]
@annieappflowy Still RTL support for board and grid is left.

**Comment by asafm** [comment]
It's very weird implementation.
Usually if you are in Google Doc, or Word, you choose the LTR or RTL direction for the current paragraph. Many times it simply detects if the language is LTR and switches for you automatically - Facebook posts (when you create a new post) is a good example.
It doesn't make a lot of sense to have one direction set for the entire app.

**Comment by zoli** [comment]
> It's very weird implementation. Usually if you are in Google Doc, or Word, you choose the LTR or RTL direction for the current paragraph. Many times it simply detects if the language is LTR and switches for you automatically - Facebook posts (when you create a new post) is a good example. It doesn't make a lot of sense to have one direction set for the entire app.

You can have auto direction detection when setting direction to AUTO. About the per-paragraph direction, I agree with you. This was available in Appflowy a while ago but now its limited to RTL layout direction, So If you set the layout direction to RTL you can set a paragraph direction to either LTR/RTL/AUTO.
I discussed with @LucasXu0 enabling per-paragraph direction in all layout directions we concluded to put a setting for enabling it in the toolbar menu for all layout directions.
The reason for not enabling it by default is because it might confuse some users.
