### ISSUE TITLE
[Bug] Enable notification toggle button doesnt work

### ISSUE THREAD

**Issue by inson1** [AppFlowy-IO/AppFlowy#3914]
### Bug Description

Můj click nedělá nic on enable notification.

### How to Reproduce

If I click on it nothing happens
![AppFlowy_uzhXHQuvjd](https://github.com/AppFlowy-IO/AppFlowy/assets/75314629/f779fff4-997c-40bb-bbfa-5428a8e09d75)

### Expected Behavior

It should be disabled after I click on it.

### Operating System

Windows 10

### AppFlowy Version(s)

0.3.7

**Comment by annieappflowy** [comment]
Hi @inson1 , thanks for reporting. This bug was fixed already. The fix will be included in the upcoming release (v0.3.8)

**Comment by inson1** [comment]
oh okay, I only looked in issues, sorry

**Comment by annieappflowy** [comment]
No problem at all. Thank you!

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
