### ISSUE TITLE
[FR] Set bold for headings

### ISSUE THREAD

**Issue by rinodrops** [AppFlowy-IO/AppFlowy#3916]
### Description

In modern documentation, headings (H1, H2, and H3) are drawn as bold fonts.
For instance, notion and obsidian's default themes use bold fonts for headings.
It makes it easier to distinguish headings and paragraphs.

### Impact

Everyone who got tired of pressing ⌘B every time a new heading was created.

**Comment by annieappflowy** [comment]
Completed
