### ISSUE TITLE
[FR] Pocketbase source

### ISSUE THREAD

**Issue by axelra82** [AppFlowy-IO/AppFlowy#3931]
### Description

Wondering if [PocketBase](https://pocketbase.io) could be a nice alternative to SupaBase as source, for a "100% self-hosted/no account" solution? 🤔

### Impact

I would imagine most, if not all, AppFlowy users would have some interest in this since "self-hosted service users" probably care about complete agency of content to some extent 🤷‍♂️

### Additional Context

This would make AppFlowy very portable and could be served on a fully secured setup (i.e. with no external internet access).

No more fork etc for self-hosting (from [How to self-host](https://docs.appflowy.io/docs/guides/appflowy/appflowy-with-supabase#how-to-self-host-appflowy-with-supabase)). AppFlowy could just include PocketBase and connect to that 🤓

**Comment by dqhoang** [comment]
FYI. Supabase is selfhostable.

https://supabase.com/docs/guides/self-hosting

**Comment by axelra82** [comment]
Yes, I saw that after posting. I would still argue that PocketBase seems a bit simpler to start with (just less complex). I guess it depends on the target audience in the end 🤷‍♂️

I'm comfortable with Docker, so I'll look into the linked solution 👍
