### ISSUE TITLE
[Bug] The 'quick start' button cannot be used in WIN ([🔵 INIT - End, Uncaught platform error) 

### ISSUE THREAD

**Issue by pein0saga** [AppFlowy-IO/AppFlowy#3943]
### Bug Description

Clicking 'quick start' does nothing after installation

```
{"msg":"🔥AppFlowy Configuration { storage_path: \"E:\\\\DB\\\\APPFLOW\\\\AppFlowyDataDoNotRename\" }"}
{"msg":"Network type: Wifi"}
{"msg":"Network type: Wifi"}
{"msg":"AppLauncher dispose"}
{"msg":"[INIT - Event] 🔥AppFlowy Configuration { storage_path: \"E:\\\\DB\\\\APPFLOW\\\\AppFlowyDataDoNotRename\" }"}
{"msg":"[🔵 INIT - End]","line":136,"file":"flowy-core\\src\\lib.rs","elapsed_milliseconds":39}
{"msg":"Network type: Wifi"}
{"msg":"Network type: Wifi"}
{"msg":"Uncaught platform error"}
{"msg":"Uncaught platform error"}
{"msg":"Uncaught platform error"}
{"msg":"Uncaught platform error"}

```

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/2074641/a4f6caf1-04af-4911-aa8e-d5220021615f)

### How to Reproduce

1. after installation, set data location
2. click 'quick start' 
3. nothing happens

### Expected Behavior

1. after installation, set data location
2. click 'quick start' 
3. app will open 

### Operating System

WIN 10 22H2

### AppFlowy Version(s)

0.38

**Comment by annieappflowy** [comment]
Please reopen the issue if you still encounter the same with the latest release.
