### ISSUE TITLE
[Bug] Naming dialog OK button doesn't work after press enter 

### ISSUE THREAD

**Issue by mtbf99** [AppFlowy-IO/AppFlowy#3950]
### Bug Description

In the New Page naming dialog, after pressing Enter on the keyboard, the popup is not closed and the OK button stops working and it's not possible to click it

### How to Reproduce

1. Turn on "Show naming dialog when creating a page"
2. Create a new page
3. Insert any name
4. Press enter on keyboard
5. Click on OK button

### Expected Behavior

The "enter key" should be accepted as valid to accept the page name or the click button should work after pressing enter

### Operating System

Windows

### AppFlowy Version(s)

0.3.8

**Comment by annieappflowy** [comment]
Thanks for reporting. I was able to reproduce this bug on macOS. 
The current workaround is to click the "OK" button instead of pressing Enter.

**Comment by Pranav2612000** [comment]
I wanted to work on this, so I tried to reproduce it but I'm not able to. Pressing Enter accepts the page name.

**Comment by annieappflowy** [comment]
@Pranav2612000 , it's fixed already. Please find another issue to work on
