### ISSUE TITLE
Request for Text-sizing features

### ISSUE THREAD

**Issue by armaneousuf** [AppFlowy-IO/AppFlowy#3955]
### Description

Dear AppFlowy Team,

I hope this message finds you well. I am a dedicated user of your app and have found AppFlowy to be an invaluable tool for organizing and managing my tasks. The simplicity and effectiveness of your platform have significantly improved my productivity.

However, I would like to bring a suggestion to your attention that I believe would enhance the user experience even further. It would be immensely helpful if you could introduce a text sizing feature within the app. The ability to adjust the size of text within lists and notes would allow users like me to tailor the visual presentation of information based on individual preferences and needs.

### Impact

Here are a few reasons why I believe this feature would be beneficial:

1. Customization: Users have different preferences when it comes to text size. Allowing customization would cater to a broader audience and make the app more user-friendly.

2. Improved Readability: Some users may find larger text sizes more comfortable to read, especially on smaller screens. This feature would enhance the overall readability of the content.

3. Accessibility: A text sizing feature can contribute to improved accessibility for users with visual impairments or those who require larger text for various reasons.

4. Enhanced Aesthetics: The ability to adjust text size can also contribute to the visual aesthetics of the app, providing a more pleasing and personalized user interface.

### Additional Context

I understand that feature development involves careful consideration, and I appreciate the hard work that goes into maintaining and improving AppFlowy. I believe that the addition of a text sizing feature aligns with the user-centric approach that AppFlowy embodies.

**Comment by annieappflowy** [comment]
Hi @Formicidae98 , I'd like to first thank you for this well-written and information-rich request. I feel strongly about enabling our users to resize text within databases and documents. We'll start working on this feature shortly after completing the initial version of AppFlowy Mobile. Please keep an eye on the status change of this issue. We'll close it once the feature is built

**Comment by annieappflowy** [comment]
[#3711 ](https://github.com/AppFlowy-IO/AppFlowy/issues/2280)

**Comment by annieappflowy** [comment]
You can use ctrl/cmd +/- to zoom in and zoom out
ctrl/cmd + 0 to reset
