### ISSUE TITLE
[Bug] underline markdown syntax in conflict with typing _

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3964]
### Bug Description

I just discovered a bug

When I tried to wrote "PORT_OF_YOUR_VM", AppFlowy got stuck when 2 "_" was on the same line (example : "PORT_OF_" <- here trigger the bug)

After the bug got triggered, impossible to write anything else until I close and open AppFlowy again

Minor bug, but that make me felt confused at first

### How to Reproduce

as described in the description

### Expected Behavior

can escape the markdown syntax

### Operating System

Windows 11

### AppFlowy Version(s)

v0.3.8

**Comment by rituraj2000** [comment]
@annieappflowy Please assign this to me
