### ISSUE TITLE
[FR] visual clue for subpages in the side panel

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3965]
### Description

It's great that the Kanban cards now show with an icon whether text is stored in the card. (Very practical! 👍 🥳 ) Wouldn't that also be useful for the overview list on the left-hand side? When a page is collapsed, there is no indication whether there are other subpages.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/32130370-4c0a-4bea-a0cd-172f1b5c58f7)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/cd5a4acc-2c42-4f85-97b7-905ecf991034)

### Impact

all the users

**Comment by ShatilKhan** [comment]
Hi @annieappflowy 
Can you please assign this to me?

**Comment by annieappflowy** [comment]
Fixed in v0.5.9
