### ISSUE TITLE
[Bug] create a subpage of subpage cannot rename

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3966]
### Bug Description

I noticed a bug when creating this example. If you add a subpage, this new page is highlighted. If you then click on the plus sign on this page to create a subpage there too, the name is not applied when you click on OK. 

### How to Reproduce

as described in the description

### Expected Behavior

I'm able to rename it via the dialog when creating a subpage of subpage
<img width="411" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/19730766-1bba-4ae4-baa4-d4ea067c2845">

### Operating System

macOS

### AppFlowy Version(s)

v0.3.8

**Comment by Pranav2612000** [comment]
@annieappflowy Can I work on this issue?

**Comment by annieappflowy** [comment]
Sure. Assigned.

**Comment by Pranav2612000** [comment]
@LucasXu0 has already pushed a fix as discussed on Discord. Can you close this issue now?
