### ISSUE TITLE
[Bug] 默认选中底色太浅，与代码块颜色底色相近

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#3972]
### Bug Description

默认选中底色太浅，与代码块颜色底色相近，无法明显看到选中的

### How to Reproduce

编辑文字，变成代码，然后选中

### Expected Behavior

明显区别

### Operating System

win11

### AppFlowy Version(s)

0.3.7

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/2f6852cb-b376-4cb3-8a07-9265569cb107)

**Comment by LucasXu0** [comment]
Provide an option in settings page to let the users to customize the cursor and selection color.

**Comment by enomothem** [comment]
That's good advice
