### ISSUE TITLE
error: failed to select a version for `flowy-folder`.

### ISSUE THREAD

**Issue by goodforever** [AppFlowy-IO/AppFlowy#398]
cargo make --profile production-mac-x86 appflowy

error: failed to select a version for `flowy-folder`.
    ... required by package `flowy-sdk v0.1.0 (/Users/foo/AppFlowy/frontend/rust-lib/flowy-sdk)`
    ... which satisfies path dependency `flowy-sdk` (locked to 0.1.0) of package `dart-ffi v0.1.0 (/Users/foo/AppFlowy/frontend/rust-lib/dart-ffi)`
versions that meet the requirements `*` are: 0.1.0

the package `flowy-sdk` depends on `flowy-folder`, with features: `flowy-folder` but `flowy-folder` does not have these features.

failed to select a version for `flowy-folder` which could resolve this conflict
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.

**Comment by MikeWallaceDev** [comment]
Why was this closed @goodforever ?  Did you find a solution? Is it something we need to document?

**Comment by dxafn** [comment]
I've changed the feature line 

> dart = ["lib-infra/dart", "flowy-folder/dart"]

 into 

> dart = ["lib-infra/dart"]

 from the file `frontend/rust-lib/flowy-folder/Cargo.toml`, and managed to build
