### ISSUE TITLE
[FR] Drag & drop content

### ISSUE THREAD

**Issue by fredericgoossens** [AppFlowy-IO/AppFlowy#3980]
### Description

It would be excellent to have this feature incorporated into AppFlowy, mirroring the functionality found in Notion. This entails the ability to seamlessly drag and drop content to desired locations. Additionally, it would be highly beneficial to extend this capability to include the dragging of items within a 'toggle' element, smth I use frequently in Notion, particularly with code blocks. Here is an example of how Notion does it:

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/18092968/50b829d8-46d6-4132-9742-1a055158ad25)

### Impact

This feature significantly enhances the application's usability by introducing a more intuitive and flexible content organization system. The ability to drag and drop content, streamlines user interactions and makes the application more adaptable to individual preferences. This feature promotes a smoother workflow, allowing users to arrange and customize information effortlessly. Ultimately, the enhanced flexibility and user-friendly interface contribute to a more efficient and satisfying experience with the application.

**Comment by Jayaprakash-dev** [comment]
Hey **@LucasXu0**, can I work on this?

**Comment by annieappflowy** [comment]
Hi @Jayaprakash-dev , this task will be handled by @LucasXu0 
Please consider another issue that interests you.

**Comment by fredericgoossens** [comment]
When will we see this feature in Appflowy?

**Comment by annieappflowy** [comment]
https://forum.appflowy.io/t/drag-and-drop-blocks-in-a-document/52/4
Very interested in having the feature added to the toolkit. The ability to move around blocks to re-order blocks in a document is very useful. Especially for lists.

A use case I have is related to capturing use cases and requirements for product development. The intent is to define use cases and requirements as a narrative with separate paragraphs (that are blocks). Then I would be able to work with each one independently. I would like to add a block per use case or requirement then be able to move them around (to group them) as well as select an individual block and take an action against it.

The apps that you are positioning AppFlowy as an alternative to provide this capability: Notion, ClickUp, Microsoft Loop.

**Comment by annieappflowy** [comment]
Supported in v0.7.0
