### ISSUE TITLE
Sum, count etc in datagrid 

### ISSUE THREAD

**Issue by Nice2Work** [AppFlowy-IO/AppFlowy#3986]
### Description

One feature I am using a lot is the sum, count feature in the tables/grids that notion.so has. It is strong as it is simple and fast to implement without going overboard. 
Right now under the grid we only have a link/button that adds a row, but having this 'row' below the grid where you can use sum, count, average etc, is something really usefull. 

### Impact

I think this is one of the strongest features in notion as non other block editors does provide this.

### Additional Context

What I really like about AppFlowy is the look and feel. It feels simpler, easier and is much faster than Notion. But to be honest as I am using the grid a lot it is something I personally need to step away from Notion into Flowly, but I will keep track as I believe this product does have other features that are much better than notion.

**Comment by annieappflowy** [comment]
#2499

**Comment by annieappflowy** [comment]
Hi @Nice2Work , we recently supported calculations. Please give it a try!
<img width="378" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/5696955e-9f79-498c-be69-386cd27c4b77">
