### ISSUE TITLE
[Bug] Can't scroll tab bar | [FR] Inintial tabs management

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#3988]
### Bug Description

1. Open more and more tabs.
2. See one tab is "lost" from tab bar
3. Switch to least left or least right tab.
4. Get "disappeared" tab available.
5. Click on any tab.
6. Try to scroll like at browser tabs etc.
7. Get nothing

### How to Reproduce

See above. It's a bit inconvenient.

### Expected Behavior

Be able to scroll tabs or select them from popup tab menu (button at the right corner of tab bar (like Chrome tab search button)

### Operating System

Win 8.1 x64

### AppFlowy Version(s)

0.3.8x64-86 ZIP-release from Github)

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7080928/70181ea3-181c-46ad-82ae-cc038ee72df5)

**Comment by emmggi** [comment]
Generally you scroll horizontal lists using shift+mouse wheel.

Though I would also like to see a drop down list of tabs like shown on the image.

**Comment by Xazin** [comment]
This should have been resolved, we still need to improve the behavior and layout though.
