### ISSUE TITLE
[Bug] Add button contrast is too low to see in dark mode

### ISSUE THREAD

**Issue by shakg** [AppFlowy-IO/AppFlowy#399]
**Describe the bug**
Add button appears on left side drawer is not visible in dark mode.

**To Reproduce**
1. Open V.0.0.3
2. Click on Settings
3. Open dark mode
4. Look at add button on left side drawer.
5. Yes, you can't even see add button 

**Expected behavior**
Color contrast of described button must be higher. 

**Screenshots**
![add_button_contrast_low](https://user-images.githubusercontent.com/76657662/156049067-2018a9a2-0a06-4bce-a900-3fee94387d68.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.0.3

**Additional context**
 - It should be easy fix. Just changing color of add button in dark mode. 
 - I have searched add button for 5 minutes when i switched to dark mode so i think it is huge improvement in UX.

**Comment by annieappflowy** [comment]
Upcoming v0.1.3 fixed this
<img width="273" alt="image" src="https://user-images.githubusercontent.com/12026239/233056140-ec1413e6-4eaf-4ef2-af46-d39e27013017.png">
