### ISSUE TITLE
[Bug/Suggestion] shift + delete / backspace

### ISSUE THREAD

**Issue by CarlSinclair** [AppFlowy-IO/AppFlowy#3999]
### Bug Description

Can't use delete or backspace while shift is held down

### How to Reproduce

Hold down shift and try o use delete or backspace

### Expected Behavior

Backspace and delete should function normally regardless of shift state. As a power user, I often forget shift pressed down while doing other things. I'm used to his behavior based on every other environment I work in. Appflowy is he only exception, so it's very jarring.

### Operating System

Windows

### AppFlowy Version(s)

Not sure

**Comment by annieappflowy** [comment]
shift + backspace works
shft + del doesn't
