### ISSUE TITLE
[Bug] Broken Link in the Documentation

### ISSUE THREAD

**Issue by AnsahMohammad** [AppFlowy-IO/AppFlowy#4010]
### Bug Description

The link to the Environment setup in the section https://docs.appflowy.io/docs/documentation/appflowy/draft-how-to-contribute-to-appflowy#working-on-your-issue of the documentation is broken. It leads to a "**page not found** instead of the expected page. 
The current link is pointing to https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions#environment-setup which doesn't exist

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/85027826/cff7a1cf-ff90-4a82-b0af-bde55e5ebe96)

### How to Reproduce

Go to the Link: https://docs.appflowy.io/docs/documentation/appflowy/draft-how-to-contribute-to-appflowy#working-on-your-issue

And click on `environment` in the bullet point 2.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/85027826/1cfb69dd-d26d-4e73-be75-869f32ceca90)

### Expected Behavior

This link should direct you to the page that explains how to set up the environment for contributing to AppFlowy.

### Operating System

Ubuntu LTS 22.04

### AppFlowy Version(s)

NA

**Comment by MuthoniMN** [comment]
I'm interested on working on this issue

**Comment by MuthoniMN** [comment]
> I'm interested on working on this issue

Hey @annieappflowy, can I please work on this?

**Comment by annieappflowy** [comment]
Already fixed
