### ISSUE TITLE
[Bug] duplicating card then cannot use the arrow 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4017]
### Bug Description

Kanban [Bug] (W11): After duplicating a card, the cursor flashes in front of the first letter of the text, but it cannot be moved to the right using the arrow keys. Only after moving the cursor with the mouse to another position in the text can the cursor be moved with the arrow keys.

### How to Reproduce

reported by MacMeikel on Discord

### Expected Behavior

can use the arrow key

### Operating System

Windows 11

### AppFlowy Version(s)

v0.3.8

**Comment by hyj1204** [comment]
It seems this bug has been fixed in 0.3.9

https://github.com/AppFlowy-IO/AppFlowy/assets/14248245/423bc1ec-88b5-4505-9e6a-c538f84f0a2b
