### ISSUE TITLE
How do I set the code language in the text?

### ISSUE THREAD

**Issue by jhon65496** [AppFlowy-IO/AppFlowy#4023]
### Bug Description

How do I set the code language in the text?

How do I format this code?!!!
I inserted the code into the note.
And what's next?

Is used: 
Win 10.

### How to Reproduce

Как размножать

### Expected Behavior

Ожидаемое поведение

### Operating System

Win 10.

### AppFlowy Version(s)

0.3.8-windows-x86_64

### Screenshots

![27 11 2023_10-56-17](https://github.com/AppFlowy-IO/AppFlowy/assets/128128859/3e5a6b1a-3acf-4709-9a6e-0e03f31a9b41)

**Comment by annieappflowy** [comment]
<img width="336" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/5ccace6e-c214-428d-9429-98ab4a4436c5">

**Comment by annieappflowy** [comment]
<img width="427" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/991f13cb-8f3d-47eb-adcf-1516ea6dd724">

**Comment by annieappflowy** [comment]
@jhon65496 , please refer to my comments above
and let me know if you need more help
