### ISSUE TITLE
[FR] Mobile app?

### ISSUE THREAD

**Issue by gasull** [AppFlowy-IO/AppFlowy#4033]
### Description

Is a phone app for Android (and iOS) in the roadmap?  Or at least a PWA?  (I didn't find it on the roadmap page).

I haven't tried AppFlowy yet because without a phone app for Android or a PWA, it wouldn't be useful to me.

### Impact

Mobile users.

**Comment by annieappflowy** [comment]
<img width="710" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/2545d444-8f57-42ae-a724-b4a295a11ea8">
Working on it

**Comment by e-p-s** [comment]
coming in december (see homepage)

i'm counting the hours, too :)

**Comment by vedxp** [comment]
Is there any update regarding the launch of mobile version?

**Comment by annieappflowy** [comment]
@Log4Jake , can you share a screenshot of the error message?

**Comment by Log4Jake** [comment]
> @Log4Jake , can you share a screenshot of the error message?

Sure here you go :) ![Screenshot_20240108-205436_Package installer.jpg](https://github.com/AppFlowy-IO/AppFlowy/assets/62357760/9f880642-f808-4ac7-be4e-c9e963954859)

**Comment by annieappflowy** [comment]
@Log4Jake can you try to download it via [this link ](https://drive.google.com/file/d/1HLOefyDiaz-GAgmpDPP5LQZ-h24Lc30F/view?usp=sharing)

**Comment by Log4Jake** [comment]
> @Log4Jake can you try to download it via [this link ](https://drive.google.com/file/d/1HLOefyDiaz-GAgmpDPP5LQZ-h24Lc30F/view?usp=sharing)

Unfortunately I get the same error. Thanks for the quick responses and help.

**Comment by LucasXu0** [comment]
@Log4Jake can you share your device model and android system version?

**Comment by LucasXu0** [comment]
> > @Log4Jake can you share your device model and android system version?
> 
> Samsung Galaxy S8+ Android 9

Since the Google Play Console has requested us to upgrade the minimum target SDK to 32, and the target SDK of Android 9 is 28, I believe this is the main problem.

https://support.google.com/googleplay/android-developer/answer/11926878?hl=en

**Comment by Log4Jake** [comment]
> > > @Log4Jake can you share your device model and android system version?
> > 
> > Samsung Galaxy S8+ Android 9
> 
> Since the Google Play Console has requested us to upgrade the minimum target SDK to 32, and the target SDK of Android 9 is 28, I believe this is the main problem.
> 
> https://support.google.com/googleplay/android-developer/answer/11926878?hl=en

Oh ok thanks this is unfortunate perhaps I will compile my own version then.

**Comment by annieappflowy** [comment]
You can now download AppFlowy Mobile from https://appflowy.io/download#ios-and-android

**Comment by Log4Jake** [comment]
Here is an update on this. For Android users using Android 9 or lower install with apkpure as it bypasses these restrictions. Now that app flowy is on the Play Store you can use the APK Pure app. However, make sure to verify the signature of the apk before installing.
