### ISSUE TITLE
[Bug] cannot view the full description if the property name is over the width

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4071]
### Bug Description

<img width="260" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/d78ef154-5788-48ae-9dd9-8e80a4f55dd2">

### How to Reproduce

Create a property, giving it a longer name
Open it as page

### Expected Behavior

Hovering on it can see its full description

### Operating System

macOS

### AppFlowy Version(s)

v0.3.8

**Comment by hyj1204** [comment]
It has been added by @richardshiue in PR #4075 

https://github.com/AppFlowy-IO/AppFlowy/pull/4075/files#diff-c0ad6a2a3c6fd3b4edfe11a46aeb712377b8ea35ce1dd099075c73c37e2b53e5
