### ISSUE TITLE
[FR] Time field type

### ISSUE THREAD

**Issue by zoli** [AppFlowy-IO/AppFlowy#4083]
### Description

A field type for determining time like 20 minutes, 3 hours, etc. It's useful for task management purposes, To show how much time a task needs or how much I've spent time on the task.

### Impact

Users who use the Kanban or grid view for managing tasks or similar stuff.

### Additional Context

I would like to implement this my self if its an acceptable feature.

**Comment by zoli** [comment]
Maybe for project management that will be fine (not all the cases though). But not for personal task management. Also, it won't work for how much I've spent time. For example, the estimate is 4 hours but I've spent 1.5 and I want to submit and continue from that later on.
Besides the above notes I also was thinking maybe in the future it will be possible to have time tracking within AppFlowy, Like I hit a button and it starts tracking time spent until I hit the button again. This needs a continuous field instead of STH discrete like Single Select.
Another possible future could be AppFlowy supporting some sort of scripting or functions in Grid cells so it can show the total time that the tasks took and the total time the user has spent on tasks or this week, etc. This also needs a field that stores data as a number.

I was thinking of a field type similar to number field type with some extra display option for showing the time in the frontend (similar to date field display options).

**Comment by Xazin** [comment]
> Thank you for the insights, Mathias. Maybe for project management that will be fine (not all the cases though). But not for personal task management. Also, it won't work for how much I've spent time. For example, the estimate is 4 hours but I've spent 1.5 and I want to submit it and continue from that later on. Besides the above notes I also was thinking maybe in the future it will be possible to have time tracking within AppFlowy, I hit a button and it starts tracking time spent on a specific card until I hit the button again. This needs a continuous field instead of STH discrete like Single Select. Another possible future could be AppFlowy supporting some sort of scripting or functions in Grid cells so it can show the total time that all the tasks in the grid took and the total time the user has spent on tasks or within this week, etc. This also needs a field that stores data as a number.
> 
> I was thinking of a field type similar to number field type with some extra display option for showing the time in the frontend (similar to date field display options).

Hmm, I'd love to see this in practice, I can't really come up with an especially good way of visually representing these options, but I'm sure you'll figure something out :D 

I've assigned you, maybe this can lead to some more interesting types of fields in the future as well.
