### ISSUE TITLE
[Bug] 短横在代码中变为长横 

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#4085]
### Bug Description

[Bug] 短横在代码中变为长横 ，很影响写代码的体验

### How to Reproduce

新建一个代码块，输入 -- 会变为 ——

### Expected Behavior

--version
 -- 而不是 ——

### Operating System

win11

### AppFlowy Version(s)

0.3.7

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/12140edd-31b2-427d-a04e-0026d8a5e0bc)

**Comment by smartyhero** [comment]
I also encountered the same problem

**Comment by wa1kmoon** [comment]
this problem also exists on macOS Monterey 12.5
