### ISSUE TITLE
[Bug] Option bar truncated

### ISSUE THREAD

**Issue by speed2exe** [AppFlowy-IO/AppFlowy#4091]
### Bug Description

When screen in not wide enough, when highlighting texts, not all options appears.

### How to Reproduce

highlight some text in document closer to the right. adjust width of window.
<img width="451" alt="Screenshot 2023-12-05 062810" src="https://github.com/AppFlowy-IO/AppFlowy/assets/33050391/dd415fd8-c6e1-486e-a6de-683d8c826617">

### Expected Behavior

- allow user to access more options either by reorientation or alternative pop up layout

### Operating System

Windows 11

### AppFlowy Version(s)

0.3.9.1

**Comment by annieappflowy** [comment]
I can't reproduce it
