### ISSUE TITLE
[FR] Shortcuts for Sidebar

### ISSUE THREAD

**Issue by cb0s** [AppFlowy-IO/AppFlowy#4095]
### Description

While using the App (which I honestly really like), I stumbled upon one flaw that bothered me quite a bit. Not only aren't there any right click options like mentioned here (#2858) for instance, but you also cannot use shortcuts that you are used to from other apps.
Let's take renaming a document as an example: When already selected (supreme would be shortcuts for doing so), I want to press either F2, Shift+F6 (like in Jetbrains Products) or at least something like CTRL+(SHIFT)+R...
Deleting a page or moving by cutting and pasting would be some other examples of where it is almost necessary to have shortcuts for a more fluent workflow without just using the mouse...

### Impact

Imo this would make editing faster and more ergonomic because you don't need to move away from the keyboard all the time. Especially when starting new notebooks, this makes setting up a design easier.

**Comment by Xazin** [comment]
Thanks for the suggestions.

I have recently implemented fixes/features for:
- Rename current view with F2
- Toggle sidebar for MacOS
- Open settings using `CTRL + ,`

And I will continue to improve shortcuts for AF. I will close this issue as completed for now.

Feel free to open a new one if you have more suggestions.
