### ISSUE TITLE
[HELP] Build process failed

### ISSUE THREAD

**Issue by test210820** [AppFlowy-IO/AppFlowy#410]
# Env
* `git log`
![image](https://user-images.githubusercontent.com/65008815/156441679-f555f7ab-4611-4d07-8469-9bab53ef0a6f.png)

* `flutter doctor`
![image](https://user-images.githubusercontent.com/65008815/156440219-bd220bda-ace3-4baf-8222-3c7b9a42a24a.png)

* `flutter devices`
![image](https://user-images.githubusercontent.com/65008815/156440314-1be3f873-3c3c-438d-bd49-08c43bf7139a.png)

* `cargo --version`   `rustc --version`  `vcpkg --version`
![image](https://user-images.githubusercontent.com/65008815/156440660-aba95ecb-2d37-4399-ae6d-8a5dcb9ccb62.png)

# Error message

`cargo make -p production-windows-x86 appflowy-windows`

![image](https://user-images.githubusercontent.com/65008815/156442328-08b33258-da5e-4d86-8567-65e0a698d6a1.png)

### More details

[build.log](https://github.com/AppFlowy-IO/AppFlowy/files/8172693/build.log)

**Comment by appflowy** [comment]
Hi @test210820 .  Check out the this [link](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-windows) please.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/86001920/156871410-8b5f85d3-6ff0-44ab-b379-b3ce3cd5db86.png">

**Comment by test210820** [comment]
I built it successfully, thank you very much for your guidance.

But I found that the text rendering of flutter desktop on windows does not seem smooth and there will be a slight delay.

![image](https://user-images.githubusercontent.com/65008815/156891666-0ffed9f4-21f3-4da9-9378-2811a0652641.png)

**Comment by annieappflowy** [comment]
@test210820 hi, thanks for your feedback. Please create a new issue for the delay on Windows you've encountered. We'll try to reproduce.
