### ISSUE TITLE
[FR] When changing column type, attempt to preserve current column information

### ISSUE THREAD

**Issue by speed2exe** [AppFlowy-IO/AppFlowy#4104]
### Description

changing a column type will truncate all the column data associated with it.
propose that app should attempt to change to a column type. 

### Impact

This will help user in exporting and importing csv from database table. due to limited information that can be stored in csv(column type information is lost), appflowy can also consider using other export format(eg. json
<img width="727" alt="ss2" src="https://github.com/AppFlowy-IO/AppFlowy/assets/33050391/a0231068-9c38-4633-9b97-988c316edc8f">
<img width="744" alt="ss1" src="https://github.com/AppFlowy-IO/AppFlowy/assets/33050391/c37e1be0-8f08-43dd-b044-3eebfc53deb9">
).

**Comment by appflowy** [comment]
The CSV file currently consists only of plain text. However, we have the capability to add more detailed information to the CSV file during the export process. To accommodate this, we could introduce a new export format, which we could name 'afcvs'.
