### ISSUE TITLE
[Database] Its possible save this?

### ISSUE THREAD

**Issue by lariane-guerra** [AppFlowy-IO/AppFlowy#4107]
Hi guys, it's me again.

I have a question about the database and the files.
Exemple:
I'm using pop OS, and now I decide to remove this system and install the new system, but I don't want to lose my files (docs) in Appflowy.

It's possible to use GitHub to version this database and reuse this? 
Or maybe send this database to google drive? 

I don't know if my question its clear.

**Comment by LucasXu0** [comment]
Sure. You can save the folder using Git or Google Drive if you're not using the cloud version.

**Comment by annieappflowy** [comment]
@lariane-guerra , gDrive is not recommended. iCloud and OneDrive have been working fine given the feedback we've received so far.

**Comment by lariane-guerra** [comment]
@LucasXu0 can u help me? 
how i can save this datebase in google drive?

**Comment by LucasXu0** [comment]
Hi @lariane-guerra. If you want to sync the data, you can use our cloud server. The data will be synced to your new account.

**Comment by lariane-guerra** [comment]
@LucasXu0 yes, i prefet to use the appflowy cloud, but i dont know how to do this. im a linux leraning yet, so  i dont know how to use docker, and aws and this things.
I need to have account on aws?i need to pay for this? 
I saw this: https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy

```
GOTRUE_SMTP_USER=user1@example.com
# this is typically an app password that you would need to generate: https://myaccount.google.com/apppasswords
GOTRUE_SMTP_PASS=somesecretkey
# You can leave this field same as GOTRUE_SMTP_USER
GOTRUE_SMTP_ADMIN_EMAIL=user1@example.com
```

about it, its my email like: larianespalenza@gmail.com?

**Comment by LucasXu0** [comment]
@lariane-guerra If you upgrade to our latest version, you can simply sign in to your account in settings page. Or, would you prefer to self-host?
