### ISSUE TITLE
[FR] Export markdown

### ISSUE THREAD

**Issue by LailaNabil** [AppFlowy-IO/AppFlowy#411]
Since the app is mainly a better alternative to Notion, I think It makes sense to be able to export from Notion or generally export markdown files

**what types of users can benefit from using your proposed feature**
Users who used Notion for a while and looking for an alternative while still having access to their older Data

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/2706
