### ISSUE TITLE
[Bug]Chinese translation problem

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#4115]
### Bug Description

The text in the added image is incorrect

### How to Reproduce

Set appflowy to display in Chinese

### Expected Behavior

Display as normal text

### Operating System

mac

### AppFlowy Version(s)

0.3.9

### Screenshots

<img width="866" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/c96080a4-8823-4692-8ac5-24bc210712fb">

**Comment by smartyhero** [comment]
His Chinese should be "内嵌" ?

**Comment by smartyhero** [comment]
<img width="808" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/4f4fce63-07a1-4d0d-ab75-2fedac412e05">

**Comment by zou2699** [comment]
> <img alt="image" width="808" src="https://private-user-images.githubusercontent.com/76774978/288698893-4f4fce63-07a1-4d0d-ab75-2fedac412e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTg5NTAsIm5iZiI6MTcwMTk5ODY1MCwicGF0aCI6Ii83Njc3NDk3OC8yODg2OTg4OTMtNGY0ZmNlNjMtMDdhMS00ZDBkLWFiNzUtMmZlZGFjNDEyZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NWMxYWUzZDQyZjFjYzQ0ZjRiYzlhMjQ0MGFhMzkxODdiN2NjMzI1ZWYwOGM4NzJlY2EzNmE4NTYzODk2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3vwfZG90zzfWcKUkUlJiutdAeAqieoWgXyTr-9_INiQ">

按键绑定

**Comment by LucasXu0** [comment]
@zou2699 Feel free to submit a new PR to help us fix them. Some of the translations were generated by a machine.
