### ISSUE TITLE
[Bug] Docker deployment does not find the port through which the application can be accessed

### ISSUE THREAD

**Issue by kokojacket** [AppFlowy-IO/AppFlowy#4116]
### Bug Description

Appflowy was successfully deployed through docker-compose, but I found that I could not find the port to enter the application, and there was no corresponding display in the container log.

### How to Reproduce

Official deployment documentation

### Expected Behavior

Web page enters the container

### Operating System

x86

### AppFlowy Version(s)

image: appflowyio/appflowy_client:main

**Comment by annieappflowy** [comment]
@kokojacket , need help?
