### ISSUE TITLE
[Bug] DatabaseNotificationList memory leak

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#4127]
### Bug Description

<img width="1099" alt="Screenshot 2023-12-11 at 10 20 29" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/8ea34422-b338-4a7b-90fd-c8c922779b1d">

### How to Reproduce

1. open memory devtool
2. open the grid, calendar or board repeatedly
3. check the memory diff

### Expected Behavior

all the `DatabaseNotificationList` should be released.

### Operating System

macOS

### AppFlowy Version(s)

0.3.9

**Comment by Xazin** [comment]
Specifically `DatabaseNotificationListener` is no longer an issue.

I will close this, let's keep checking up on this.
