### ISSUE TITLE
[Bug] Version number is not displayed in the application correctly

### ISSUE THREAD

**Issue by adrian-r-villa** [AppFlowy-IO/AppFlowy#4134]
### Bug Description

When clicking on the "?" icon and viewing AppFlowy's version number, it is displayed as "AppFlowy 1.0.0" instead of the expected "AppFlowy 0.3.9.1"

### How to Reproduce

N/A

### Expected Behavior

"AppFlowy 0.3.9.1" instead of "AppFlowy 1.0.0"

### Operating System

Windows 10

### AppFlowy Version(s)

v0.3.9.1

### Screenshots

![appflowy](https://github.com/AppFlowy-IO/AppFlowy/assets/38902903/8b6c9ac9-df6c-4bbf-82e6-61ba7287cd12)

### Additional Context

I am sure that this was unintended and a mistake, if it wasn't, feel free to ignore everything here!

**Comment by shekhawat-harsh** [comment]
ya, it seems like a mistake

**Comment by annieappflowy** [comment]
fixed
