### ISSUE TITLE
[FR] Time entry in date property | Automatic colon for 24-hour input

### ISSUE THREAD

**Issue by rei-00** [AppFlowy-IO/AppFlowy#4145]
### Description

When entering the time in the date property, the inclusion of inputting the colon ( : ) is necessary for 24 hour formats. I would expect a behavior in which I can simply input '1600' and press enter, with the entry being auto-completed as '16:00'. Haven't used Notion for years so I'm unsure if I picked the habit up from there, but that was my muscle memory when inputting the time. Would assume this intuition/habit is shared by most.

### Impact

Anyone that is as lazy as me. Having to input the colon is a significant detriment to my workflow.

**Comment by afradahsan** [comment]
Hey, Can you assign this to me, I'm ready to do it.

**Comment by JustYousefSameh** [comment]
Hey, if this is not assigned to anyone. Can I do it?
