### ISSUE TITLE
[FR] i18n for duplicated field names

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#4153]
### Description

When duplicating a field, the new field will have the old name + the suffix "(copy)". For example, duplicating a field named `Due Date` will create a new field called `Due Date (copy)`. It would be better if copy were translated according to the user's current language.

Requires both Flutter and Rust

### Impact

Non-english AppFlowy users

**Comment by Akila-Kavisinghe** [comment]
Hey Richard I can pick this up as a good first task

**Comment by annieappflowy** [comment]
Thanks, @Akila-Kavisinghe . Assigned.
