### ISSUE TITLE
[FR] delete confirmation when deleting a page in trash

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4165]
### Description

there is no confirmation for deleting in the trash menu (guess like when empty the recycle bin or delete the already deleted in recycle bin in desktop you always get an alert dialog

### Impact

All users

**Comment by AnsahMohammad** [comment]
I would like to work on this issue, can you assign this to me ?

**Comment by afradahsan** [comment]
I'm ready to work on this issue, would be great if you can assign this to me.
