### ISSUE TITLE
[FR] wrapping/unwrapping text in table? 

### ISSUE THREAD

**Issue by vasnt** [AppFlowy-IO/AppFlowy#4166]
### Description

it is sometimes useful to have wrapping/unwrapping text in database(grid) rows. 

### Impact

It helps to hide portion of long text string

**Comment by annieappflowy** [comment]
Did you mean in a simple table or database (grid, kanban)?

**Comment by vasnt** [comment]
database (grid/kanban).  updated description.

**Comment by annieappflowy** [comment]
Supported
<img width="415" alt="image" src="https://github.com/user-attachments/assets/be2fa354-6c21-4ee9-972d-0536d54bfac6">
