### ISSUE TITLE
[FR] Can Data Storage save in other Cloud Service like Amazon S3 or Aliyun OSS?

### ISSUE THREAD

**Issue by fr4nkhe** [AppFlowy-IO/AppFlowy#4169]
### Description

I want to save data in a familiar private space and synchronize it easily.

### Impact

some use other Cloud Service people.

**Comment by annieappflowy** [comment]
Have you tried this: https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy

**Comment by fr4nkhe** [comment]
> Have you tried this: https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy

ok,It looks good.
