### ISSUE TITLE
[Bug] Texts disappeared when typing EN/Chinese characters interchangeably

### ISSUE THREAD

**Issue by firstprayer** [AppFlowy-IO/AppFlowy#4174]
### Bug Description

If I start typing Chinese characters immediately after English characters, the English characters will disappear magically. This happens on OSX, M1 Pro chip. AppFlowy Version 0.3.9 (1)

### How to Reproduce

1. Switch to Chinese input method (I'm using Simplified Chinese)
2. Type an English word. Even though it's under Chinese input method, it can recognize English word, e.g. "remote"
3. After the word is typed into the doc, try to type any Chinese character with Pinyin (e.g. "一定" = "yiding")
4. Half way through step 3, you will see the English word from step 2 just disappeared

Also attached the screen-record for a more vivid demonstration

### Expected Behavior

The texts don't disappear by themselves.

### Operating System

OSX

### AppFlowy Version(s)

AppFlowy Version 0.3.9 (1)

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/2390732/c4efc3e6-9db7-43d0-b274-dd690c000b80

### Additional Context

Strangely, this bug doesn't happen if
1. I type a space after the EN word
2. I use US keyword to type the EN word first, then switch to CN keyword. It only happens when the EN word is typed through the CN keyword

**Comment by LucasXu0** [comment]
closed as completed. https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/178
