### ISSUE TITLE
[Bug] Font selection makes the app freeze

### ISSUE THREAD

**Issue by PhilJbt** [AppFlowy-IO/AppFlowy#4177]
### Bug Description

Hover the `Font selection` button in the toolbar makes the whole menu disappearing and the app freezing. I found out that hover and click very quickly do not produce the bug.

### How to Reproduce

Hover the `Font selection` button slowly or at a normal speed.

### Expected Behavior

- The font selection sub-menu should appear
- The whole toolbar should not disappear
- The app should not freeze

### Operating System

Windws 10 Family 22H2 (19045.3803)

### AppFlowy Version(s)

v0.3.9

### Screenshots

[appflowly_bug.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/22506952/d5ab7e3b-0712-4e87-bf84-3acb707e7364)

### Additional Context

- I have some custom fonts installed on my system, see the list below
- However unlikely, I may have inadvertently uninstalled Windows built-in fonts during a recent fonts cleaning
- No other buttons behave this way

<details><summary>Family fonts installed</summary>
<p>

- Arial

- Awraq

- Bahnschrift

- BIZ UDGothic

- BIZ UDPGothic

- Cairo

- Calibri

- Cambria

- Candara

- Cascadia Code

- Cascadia Mono

- Comic Sans MS

- Consolas

- Constantia

- Corbel

- Cormorant Infant

- Courier New

- DengXian

- Dense

- Droid Sans

- Ebrima

- Figtree

- Fira Code

- Franklin Gothic

- Gadugi

- Gentium Book Basic

- Georgia

- Grimoire Of Death

- Halfmoon

- Kirvy

- Lato

- Leelawadee UI

- Malgun Gothic

- Meiryo

- Meiryo UI

- Microsoft JhengHei

- Microsoft JhengHei UI

- Microsoft New Tai Lue

- Microsoft PhagsPa

- Microsoft Tai Le

- Microsoft YaHei

- Microsoft YaHei UI

- Monaspace Krypton SemiWide

- Myanmar Text

- Nanaya Free

- Nirmala UI

- Noto Sans

- Octobre

- Palatino Linotype

- Petrona

- Poppins

- Segoe Print

- Segoe Script

- Segoe UI

- Sitka Banner

- Sitka Display

- Sitka Heading

- Sitka Small

- Sitka Subheading

- Sitka Text

- Source Serif Pro

- Spectral

- Tahoma

- Terminal

- Terror Babble

- Terror Babble 3D

- Terror Babble Mangled

- Terror Babble Staggered

- Times New Roman

- Trebuchet MS

- Typey McTypeface

- Uni Neue

- Uni Neue-Trial

- Veleka

- Verdana

- Volkhov

- Yu Gothic

- Yu Gothic UI

- Yu Mincho

</p>
</details>

**Comment by LucasXu0** [comment]
There are some hover (tooltip) issues introduced because we upgraded the Flutter version. I suspect this issue is related to the same problem.

**Comment by PhilJbt** [comment]
Is there a way to launch AppFlowy with the tooltips disabled (a configuration file to modify or a specific build) ?

**Comment by LucasXu0** [comment]
> Is there a way to launch AppFlowy with the tooltips disabled (a configuration file to modify or a specific build) ?

Yes, this issue has been addressed in the latest Flutter version. However, the Flutter team has not yet published it to the stable channel. So, I'm searching for a workaround.

**Comment by PhilJbt** [comment]
Sorry, my last message was not clear. I was asking if it was possible to disable it for the user with the current AppFlowy downloadable build.

**Comment by PhilJbt** [comment]
Issue fixed with v0.4.0
