### ISSUE TITLE
[FR] Suggestion for Page Collapse/Expand Icon

### ISSUE THREAD

**Issue by sornay** [AppFlowy-IO/AppFlowy#4178]
### Description

Hi,

I have a couple of suggestions to enhance user experience:

1.**Change the Direction of the Arrow:**
Currently, when a page is collapsed, the arrow points up, and when expanded, it points down. I believe it would be more user-friendly if the arrow, when collapsed, looked like it's pointing to the right

2.**Increase the Size of the Icon:**
Additionally, it would be helpful if the collapse/expand arrow could be a bit bigger. This would make it easier to notice and use

### Impact

I believe this change would make it more user-friendly

**Comment by afradahsan** [comment]
yup, that makes sense, and if you can assign this work to me, I'll do it.

**Comment by annieappflowy** [comment]
@sornay , we have improved the sidebar per your feedback. Please give it a go with the[ latest release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.9), and let us know how you like it.
<img width="236" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/15d95369-cd2f-498b-85ce-af4fe56c51b9">
