### ISSUE TITLE
[Bug]  Can't get to the page i want to reference [FR] Scroll down or search menu in referenced menus

### ISSUE THREAD

**Issue by matheuscaminha** [AppFlowy-IO/AppFlowy#4179]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/134650122/20ad3a2f-d88f-4e73-9cd2-b294c06e4c4b)

If you have too many pages, greeds, boards or calendars it gets to a point in wich you can't get to the one you want to reference because that is no scroll down bar or search bar in that menu.

### How to Reproduce

Create a lot of pages and try to reference the last one you created

### Expected Behavior

You will not be able to select the last page that you created

### Operating System

windows

### AppFlowy Version(s)

v0.3.9

**Comment by annieappflowy** [comment]
Hi @matheuscaminha , you can try to type out the page name @yourpagename. In this way, the menu will dynamically return based on your typed keywords.

**Comment by PeterHero** [comment]
Are '@', '+' and '/referenced Document' the same?

**Comment by Xazin** [comment]
> Are '@', '+' and '/referenced Document' the same?

Not exactly, `+` and `@` are the same type of menu, but the `/referenced document/grid/kanban/calendar` is an old type of menu that doesn't support search.

We need to add a boxconstraints with scrollable content on the Actions Menu (The one referring to `@` and `+`), and then we need to change out the slash menu references to use the action menu as well.

At least that would be my solution, to enable search and scrolling in both menus.

**Comment by PeterHero** [comment]
Why keep 3 ways to do the same? I'm not sure it is a good practice.
