### ISSUE TITLE
[Bug] Failed to load module "canberra-gtk-module" and grey screen when building with docker

### ISSUE THREAD

**Issue by NicolasPaquet** [AppFlowy-IO/AppFlowy#418]
Hi!

**Describe the bug**
I've just stumbled upon your repo and decided to give it a try.
I followed this part of your documentation: https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker

When I run  `docker-compose up`, a grey screen is appearing and I get this message in the logs:
```
-> docker-compose up
Starting appflowy_app_1 ... done
Attaching to appflowy_app_1
app_1  | 
app_1  | (app_flowy:1): dbind-WARNING **: 16:09:59.473: Couldn't register with accessibility bus: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)
app_1  | Gtk-Message: 16:09:59.494: Failed to load module "canberra-gtk-module"
app_1  | Gtk-Message: 16:09:59.495: Failed to load module "canberra-gtk-module"
app_1  | 
app_1  | ** (app_flowy:1): WARNING **: 16:09:59.592: Failed to start Flutter renderer: No available configurations for the given RGBA pixel format
^CGracefully stopping... (press Ctrl+C again to force)

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9379839/158640637-a6e423ed-f329-4a9c-93c1-7b80e58e171b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04

I've been quickly investigating but without success yet.
Is it a known issue? I'm happy to provide any additional detail if that can be helpful.

**Comment by airdogvan** [comment]
same here, Ubuntu LTS 20.04.  Even stopped apparmor with exactly the same results.

**Comment by annieappflowy** [comment]
Please try https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy
