### ISSUE TITLE
[Bug] Duplicate commands and key bindings in Shortcuts menu

### ISSUE THREAD

**Issue by AnsahMohammad** [AppFlowy-IO/AppFlowy#4193]
### Bug Description

Duplicate Shortcut command entry for the following: 
- Copy
- Cut
- Paste

### How to Reproduce

Open the `Shortcuts` Menu from settings

### Expected Behavior

There should only be unique commands. Multiple same commands confuse the user

### Operating System

Ubuntu LTS 22.04

### AppFlowy Version(s)

0.3.9

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/85027826/5af9aae8-5122-4c59-af59-1d08e4d44642)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/85027826/d9b8b278-0c9c-46e8-8ed3-de5416896c0c)

**Comment by LucasXu0** [comment]
We should change the shortcut names here. Actually, one of them pastes the raw content without formatting.

**Comment by AnsahMohammad** [comment]
Okay, I will work on this.
