### ISSUE TITLE
[Bug] The Windows executable is not signed

### ISSUE THREAD

**Issue by tomaszs** [AppFlowy-IO/AppFlowy#4195]
### Bug Description

It's not signed and Windows shows a warning

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/834977/426ea01f-5e24-4770-a101-1ed903c0e9fd)

### How to Reproduce

1. Download Windows file
2. Try to run it

### Expected Behavior

File is signed

### Operating System

Windows 11

### AppFlowy Version(s)

Latest

**Comment by annieappflowy** [comment]
Done
