### ISSUE TITLE
[Bug] android version

### ISSUE THREAD

**Issue by momayyezi** [AppFlowy-IO/AppFlowy#4211]
### Bug Description

After changing font, edit menu doesnt show any more.
Doesnt support right to left languages.
After changing main app languages, some parts of app dont change to that languages.
By holding finger on words, selecting text doesnt perform. I only can select word by double tap on word.

### How to Reproduce

Support rtl languages

### Expected Behavior

Support rtl languages

### Operating System

Android

### AppFlowy Version(s)

0.4.0

### Screenshots

![Screenshot_20231226_082825](https://github.com/AppFlowy-IO/AppFlowy/assets/6181220/974a1c19-2f9b-4027-99a2-8c9c7a510802)
![Screenshot_20231226_082813](https://github.com/AppFlowy-IO/AppFlowy/assets/6181220/8c7df49b-8ed1-431a-975f-579bfbfc8760)

https://github.com/AppFlowy-IO/AppFlowy/assets/6181220/9fef3aac-6157-4ce8-84c6-db5ab2278dec

###

**Comment by LucasXu0** [comment]
> Doesnt support right to left languages.

Please submit a new feature request for RTL support on mobile.

> After changing main app languages, some parts of app dont change to that languages.

Currently, not all the words are translated, so it will fallback to English if the translation is missing. You're welcome to help improve the missing translations.
