### ISSUE TITLE
[Bug] Android: Toolbar colors wrong in dark mode

### ISSUE THREAD

**Issue by rxkris** [AppFlowy-IO/AppFlowy#4213]
### Bug Description

When switching the app theme to dark mode the toolbar background colors are wrong (see attached screenshots)

![dark_light](https://github.com/AppFlowy-IO/AppFlowy/assets/9157720/8b55e7eb-b302-467a-b0a2-24204773209f)

### How to Reproduce

1. Open the app and go the settings
2. Set the Theme Mode to Dark Mode
3. Open any page and start typing

### Expected Behavior

Toolbar background should be dark, font color seems fine

### Operating System

Android

### AppFlowy Version(s)

9b55f5b

**Comment by rxkris** [comment]
The changed colors are now better:

![Screenshot_20231227-202620~2.png](https://github.com/AppFlowy-IO/AppFlowy/assets/9157720/d0f7114f-a7ea-43e9-ab51-404b7d06e797)

**Comment by e-p-s** [comment]
Beta? Where can i find the apk?

**Comment by LucasXu0** [comment]
> Beta? Where can i find the apk? 

You can download the apk from our discord mobile channel. The Google play one is still in review.
