### ISSUE TITLE
I am new to rust how can I run this app?

### ISSUE THREAD

**Issue by aliscie** [AppFlowy-IO/AppFlowy#422]
Should I run `npm run` or `cargo start` to launch the app and use it?

**Comment by aliscie** [comment]
I tried that but it didn't work for me so I am using by charm

**Comment by AkechiShiro** [comment]
Alright, could you please explain in details the error (logs, what command did you run if you ran any?) in order for someone to help you ?
Or you only opened the source code in your Charm IDE ? (And what Charm IDE are you using from Jetbrains I assume)

**Comment by aliscie** [comment]
Hello, I change my mind I will not use appflowy I found a better option written in Tauri with reactjs

**Comment by aliscie** [comment]
when I ran `cargo make flowy_dev` I got this error 
``1
Install protoc_plugin (Dart)
/var/folders/v3/4llt971130g6vvbq53m6k84w0000gn/T/apple/fsio/lXIX1aqSSm.sh: line 4: dart: command not found
[cargo-make][1] ERROR - Error while executing command, exit code: 127
[cargo-make][1] WARN - Build Failed.
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: restore-crate-type
[cargo-make] ERROR - Task error detected, exit code: 1
[cargo-make] WARN - Build Failed.

```

**Comment by AkechiShiro** [comment]
@aliscie you probabky have an issue with flutter, could you run `flutter doctor` and show its output ?
Because the `dart` command is coming from flutter.
What distro linux are you on ? How did you install flutter and did you make any PATH modification after installing flutter ?
Finally can you run `dart --version` in your shell ?

**Comment by aliscie** [comment]
Well, I already installed flutter and dart.
```py
(base) apples-MBP:~ apple$ flutter --version
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
(base) apples-MBP:~ apple$ dart --version
Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"
(base) apples-MBP:~ apple$ 

```
