### ISSUE TITLE
[Bug] ai icon not shown

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4238]
### Bug Description

<img width="1034" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/928aafa4-fc4d-4e82-b9da-732c59dd84aa">

### How to Reproduce

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/ce0d3fb1-abea-4d99-b7f7-ab7108d2cad3

### Expected Behavior

The AI icon is clickable in the toolbar

### Operating System

macOS

### AppFlowy Version(s)

v0.3.9.1

**Comment by ChiragKr04** [comment]
Hey, @annieappflowy I assume you have added the open api key inside settings right?
<img width="764" alt="Screenshot 2024-04-26 at 4 32 53 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/62651867/f2921d46-d23f-46e6-84cf-7ad7a80c52c2">

**Comment by Xazin** [comment]
> Hey, @annieappflowy I assume you have added the open ai key inside settings right? <img alt="Screenshot 2024-04-26 at 4 32 53 PM" width="764" src="https://private-user-images.githubusercontent.com/62651867/325955548-f2921d46-d23f-46e6-84cf-7ad7a80c52c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzEyNDEsIm5iZiI6MTcxNDEzMDk0MSwicGF0aCI6Ii82MjY1MTg2Ny8zMjU5NTU1NDgtZjI5MjFkNDYtZDIzZi00NmU2LTg0Y2YtN2FkN2E4MGM1MmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDExMjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NTg2MjBkMjk2Y2ZjNmQyMWI4MDI0NmEzNjA3NjM5Y2VkOTQ1NDRkOTExN2UwZjBhYzZhYzI3M2ZjZWFjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlDz-g9DA77sS-fho5bf1UY6lT90Q9jSjM-UzxbqPCk">

This was reported by another user, most likely in our Discord channels. From the video it's possible to tell that the setting is filled, because the AI feature is used in the beginning.

Most likely this relates to the AI item not being available in the toolbar when it spans multiple nodes.
