### ISSUE TITLE
[Bug] Duplicate button labels for done and cancel

### ISSUE THREAD

**Issue by math-GH** [AppFlowy-IO/AppFlowy#4244]
### Bug Description

Duplicate button labels for `done` and `cancel`

![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/2cae9500-28b2-4dcf-b555-2cda7d4ee289)

### How to Reproduce

see the file `frontend/resources/translations/en.json`

### Expected Behavior

have no duplicated labels

### Operating System

-

### AppFlowy Version(s)

current main branch

**Comment by LucasXu0** [comment]
Removing the duplicated keys should be fine.
