### ISSUE TITLE
[Bug] Version 1.0.0 or 0.3.9.1?

### ISSUE THREAD

**Issue by math-GH** [AppFlowy-IO/AppFlowy#4245]
### Bug Description

If you click on `Help&Support` there is a version given: AppFlowy 1.0.0

![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/4626a931-4b23-45bd-8225-8435e18e339d)

### How to Reproduce

click on `Help&Support` in the bottom right corner

### Expected Behavior

The current version number is shown

### Operating System

Windows

### AppFlowy Version(s)

0.3.9.1

**Comment by annieappflowy** [comment]
fixed
