### ISSUE TITLE
[FR] Please increased to 6 level headings 

### ISSUE THREAD

**Issue by Angel0726** [AppFlowy-IO/AppFlowy#4249]
### Description

markdown has 6 level headings， but appflowy only have 3 level headings. so i can not import markdown file to appflowy Lossless (complete)。

### Impact

markdown has 6 level headings， but appflowy only have 3 level headings. so i can not import markdown file to appflowy Lossless (complete)。

**Comment by annieappflowy** [comment]
you can type ######
<img width="224" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7aa04119-dbb5-402d-b6a9-7c66af485356">

**Comment by Angel0726** [comment]
THANKS
