### ISSUE TITLE
[Bug] Cannot exit import window by pressing escape

### ISSUE THREAD

**Issue by PeterHero** [AppFlowy-IO/AppFlowy#4259]
### Bug Description

I like to close pop up windows by pressing escape. I would expect all windows to support this. I found that the import window does not support this. Not sure if it is a bug.

### How to Reproduce

1. Hover over a page in the left bar
2. Click +
3. Click import
4. Windows opens up
5. Pressing escape does nothing

### Expected Behavior

The window is expected to close after pressing escape.

### Operating System

Linux (arch)

### AppFlowy Version(s)

0.3.9

**Comment by Smit56R** [comment]
Hey! I am a first-time contributor here. If this is a Flutter issue, can this be assigned to me?

**Comment by annieappflowy** [comment]
Assigned. Thanks, @Smit56R , for offering the help.

**Comment by ekakshjanweja** [comment]
Hey @Smit56R, 
Are you still working on this?

**Comment by Smit56R** [comment]
Hi @ekakshjanweja. My builds were failing so I have worked on the issue for a while. Sorry to not inform it sooner.

**Comment by vkuasar0** [comment]
Hey, is this issue still open? I just reproduced this issue, and I might know a way of solving it. Can I send a PR?

**Comment by annieappflowy** [comment]
Feel free to send a PR @vkuasar0

**Comment by Xazin** [comment]
> Hey, is this issue still open? I just reproduced this issue, and I might know a way of solving it. Can I send a PR?

Hey Vkuasar, you can follow other examples in our application, we use a Listener (Most of the time a KeyboardListener), to pop the dialog when Escape is pressed (remember to only check for KeyDownEvent's).

**Comment by vkuasar0** [comment]
Hey, I'm a first time contributor, so I'm a little confused. Do I have to add a video in the pull request description?
PS: I used KeyboardListener, and also checked for KeyDownEvent

**Comment by Xazin** [comment]
> Hey, I'm a first time contributor, so I'm a little confused. Do I have to add a video in the pull request description? PS: I used KeyboardListener, and also checked for KeyDownEvent

It's not required to add a preview.

**Comment by vkuasar0** [comment]
Yep, done sending PR
