### ISSUE TITLE
[FR] Maths Support

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/AppFlowy#426]
**1~3 main use cases of the proposed feature**
Ex: As a math student , I think it'd be great to be able to have support for inline maths or full maths blocks. This could possibly be achieved with LATEX similar to how Notion does it

**what types of users can benefit from using your proposed feature**
Ex: math students, general note takers which include equations, programmers, etc

**Additional context**

**Comment by tjlujianqiao** [comment]
agreed and It would be my please if I can contribute to the math equation set-up ;)

**Comment by SSebigo** [comment]
I'm desperately looking for this feature on every Flutter editor I've found but none of them have it, some are working on it, but it's taking quite a long time.
Would be cool to have AppFlowy have a stable support first.

**Comment by garv-shah** [comment]
I've been working a bit on maths support on quill like editors, you can take a look at [this pr](https://github.com/visual-space/visual-editor/pull/109) if you'd like to add anything

For now the best bet seems either to make a popup dialogue where you enter the LATEX, that then gets embedded in, like notion, or to have in text maths editing with a custom keyboard, powered by 'math_keyboard'

**Comment by LucasXu0** [comment]
Hi, @SSebigo @garv-shah. Recently, we implemented a KateX plugin in our editor. Does it meet your expectations?

![katex](https://user-images.githubusercontent.com/11863087/195752607-e8bcd9ed-ae72-495d-aa7a-c5cda4029b2e.gif)

**Comment by garv-shah** [comment]
ah that's great! it might be nice to have the ability to edit the maths afterwards, or to have an inline editor without the popup dialogue, not sure, but it's really nice to see that the support for maths is there now :)

**Comment by SSebigo** [comment]
@LucasXu0 is it possible to have a toolbar to make the editor look like a basic WYSIWYG editor?
I can't seem to find anything related to that in the README.

Thx for the info, I'll try that today, it looks almost like what I'm looking for.

**Comment by LucasXu0** [comment]
> or to have an inline editor without the popup dialogue

Did you mean to embed the Latex in the text? Like this,

<img width="509" alt="" src="https://user-images.githubusercontent.com/11863087/196073395-2bc346be-568e-4480-b512-977893394f7e.png">

**Comment by LucasXu0** [comment]
> is it possible to have a toolbar to make the editor look like a basic WYSIWYG editor?

It's possible. But it hasn't happened yet.

**Comment by SSebigo** [comment]
@LucasXu0 How did you achieve the inline formula in your screenshot?

**Comment by LucasXu0** [comment]
@SSebigo I didn't implement the inline formula for now. This screenshot is from Github. The inline LateX feature is on my plan.

> <img alt="" width="509" src="https://user-images.githubusercontent.com/11863087/196073395-2bc346be-568e-4480-b512-977893394f7e.png">

**Comment by annieappflowy** [comment]
<img width="151" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/78590f3d-4719-4dcf-b4af-ccd5640b7a9a">
inline is supported

**Comment by Junphy-Jan** [comment]
> <img alt="image" width="151" src="https://private-user-images.githubusercontent.com/12026239/292685610-78590f3d-4719-4dcf-b4af-ccd5640b7a9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDg5NTksIm5iZiI6MTcwNDI0ODY1OSwicGF0aCI6Ii8xMjAyNjIzOS8yOTI2ODU2MTAtNzg1OTBmM2QtNDcxOS00ZGNmLWI0YWYtY2NkNTY0MGI3YTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMjQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmNhZTMwZjMyOTc4YjAzNjNlZWU3Njg1ZjU5NTZlN2FkOTk3ZmJlNjQ3NzAzMGY4MDYyMTU4OGVkZGVhNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QjiiEP13n3O2ylCZPTaQlQuc894v8CpXkMkakRzmQLo"> inline is supported

May I ask how to write inline latex? Still could not find the menu.

**Comment by axiomtutor** [comment]
Note to anyone who sees this later: It is not clear how to access the inline editor, as you don't get an option when writing `/math` or any other slash command.  (By the way, it would be nice to have that!)

To get inline math you have to right-click on a point in the document and find it in the context menu.
