### ISSUE TITLE
[Bug] Slow rendering on monitors above 60hz

### ISSUE THREAD

**Issue by jivvy** [AppFlowy-IO/AppFlowy#427]
**Describe the bug**
Rendering -- highlighting tested -- is slow on monitors faster than 60hz.
Might be a case of being locked at 60hz

**To Reproduce**
Simply launch AppFlowy, and highlight on a page.

**Expected behavior**
Highlighting responsive, see the Screenshots section for a demonstration of both expected and current behavior

**Screenshots**
Here is [a video that was slowed down](https://youtu.be/Mizi1heVfDA) (so it can be viewed on 60hz monitors) showing highlighting on a Chromium browser, and on AppFlowy

**Desktop (please complete the following information):**
 - OS: Arch Linux (64-bit)
 - Browser Chromium 99.0.4844.84
 - Version v0.0.3

**Comment by LucasXu0** [comment]
The rendering issue is due to the old editor taking too much time to calculate the selection. We have optimized this in our new editor.
