### ISSUE TITLE
[Bug] non translateable labels

### ISSUE THREAD

**Issue by math-GH** [AppFlowy-IO/AppFlowy#4276]
### Bug Description

(Please add the "translations" label to this issue)

There are a bunch of English labels that are not coming from the .json files and/or cannot be translated into other lanuages

### How to Reproduce

You can see the non translatable labels with the complete German translation file (see PR #4272)

The board feature
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/1833f742-db80-44bb-b773-8575976f889e)

The settings menu of the board:
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/0881dee8-1b41-41fc-ae67-6e32f90402ef)

Calendar:
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/c4bd8443-bff8-45e1-b2ef-82d7ed0ca674)

New block (nearly every type is affected) menu:
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/e9f4e7f0-0033-41d6-bfff-e4a920c42e89)

Grid:
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/3f7b94b6-c973-4d30-9acf-1a0933be69ab)

Month of the calendar:
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/5e08eb2a-a221-4a10-b849-81d4f6eb7846)

### Expected Behavior

Translated labels into the target language

### Operating System

Windows

### AppFlowy Version(s)

0.3.9.1

**Comment by math-GH** [comment]
One more label that would be nice to have it translated: #2609

**Comment by math-GH** [comment]
The whole list of shortcut commands are not translateable:
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/1645099/92c2c1e3-d5e2-4a56-83a7-c31090403ff2)

**Comment by jpenna** [comment]
Hi! I'd like to take this one

**Comment by jpenna** [comment]
@LucasXu0 I see the translations for the editor's shortcuts should be in [appflowy_editor package](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/lib/src/editor/block_component/table_block_component/table_commands.dart#L17) using context, but for the AppFlowy it uses inlang. 

Do we keep the same structure or move everything to inlang?

**Comment by jpenna** [comment]
@LucasXu0 Could you give me more context on this PR https://github.com/AppFlowy-IO/appflowy-editor/pull/550, please? I see it added translations from the editor in the app, but wouldn't it be better as one single source of truth?

**Comment by jpenna** [comment]
Some shortcuts shouldn't be allowed to be overridden or at least should be put in an "Advanced" section. Maybe only show them to the user. For example: "Navigate around the cells at same offset in reverse" or "Move cursor to the right".
