### ISSUE TITLE
[Bug] Bad UX with date picker

### ISSUE THREAD

**Issue by apollo13** [AppFlowy-IO/AppFlowy#4287]
### Bug Description

The date picker opens always on the current day and doesn't highlight the selected date/range.

After clicking the date column:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/81547/920b2c49-3e27-479b-8dad-9b40b6edbfc9)
I would expect the date picker to show march.

Changing the date picker to march:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/81547/ba428673-b4eb-4ad4-8ebe-bccfea8c9e2b)
There is no indication about the currently selected range.

### How to Reproduce

Create a date column and play with the date picker.

### Expected Behavior

The date picker should by default focus to the selected date and visually show the selected date(range)

### Operating System

Linux

### AppFlowy Version(s)

0.4.0

**Comment by Xazin** [comment]
Forgot to close this long ago...
