### ISSUE TITLE
[FR] support wrapping a new line on mobile platform

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#4290]
### Description

on desktop, I can use shift+enter to keep the text quoted. Don’t know how to achieve it on mobile

### Impact

uses who wants to insert a '\n' instead of creating a new paragraph.

**Comment by RikinR** [comment]
hello can you please tell me how to recreate it . and I would like to work on this issue

**Comment by annieappflowy** [comment]
Supported with Enter on mobile
