### ISSUE TITLE
[Bug] Dark mode maybe a little too dark

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#433]
**Describe the bug**

There are someplace where the dark mode is a little too dark. 😄 

**Screenshots**

<details>
  <summary><strike>The add button (+) is barely (or not at all) visible</strike> (fixed in 0.0.4.1)</summary>

  <img width="276" alt="The add button (+) is barely (or not at all) visible" src="https://user-images.githubusercontent.com/22211097/162058889-746496a8-05cc-4bca-874a-cba64d6a9d1f.png">
</details>

<details>
  <summary>The inline code color is difficult to read</summary>
  
 When dark mode is enabled the default color of the inline code is very complexe to read.
<img width="249" alt="The inline code color is difficult to read" src="https://user-images.githubusercontent.com/22211097/162070108-d55d04b2-83b9-49a9-8783-d48bcbfd1c1f.png">
</details>

<details>
  <summary>Text highlighted not readeable</summary>
  When a text is highlight it should reverse is color to still be readable. This is only true on dark mode.
<img width="249" alt="Text highlighted not readeable" src="https://user-images.githubusercontent.com/22211097/162070386-d24b34c0-f422-44cd-925b-21cef0ca7a25.png">
</details>

<details>
  <summary><strike>Text format toolbar</strike> (fixed in 0.0.4.1)</summary>
<img width="535" alt="Text format toolbar" src="https://user-images.githubusercontent.com/22211097/162076128-3a03fe12-151a-41bf-95f0-5dc5007ec2a5.png">
</details>

<details>
  <summary>Header (titles) are like 'muted' instead of promoted</summary>
<img width="428" alt="Header (titles) are like 'muted' instead of promoted" src="https://user-images.githubusercontent.com/22211097/162076365-eaac438b-a121-4adf-ae38-fc31028399b1.png">
</details>

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 0.0.4.1

**Additional context**

If you wish to check the colour contrast compliance with a11y, I personally use these the [webaim tool](https://webaim.org/resources/contrastchecker/) or [colors.a11y tool](https://color.a11y.com/)

**Comment by apomalyn** [comment]
@annieappflowy I updated the PR to match the remaining bugs. If possible, could you also add the 'bug' label (maybe add the design also)?  😄

**Comment by appflowy** [comment]
@apomalyn , thank you. I added the labels. I also granted you the permission to triage the issues. You should receive an invitation for this. 
Please also check this if you dont: https://github.com/AppFlowy-IO/AppFlowy/invitations
Thanks a lot for helping us!

**Comment by notstyle** [comment]
Hi, additionally to this drop down also looks bad:

![image](https://user-images.githubusercontent.com/38030665/179923930-652c4b51-9acf-423d-ae32-e62eb97e6caf.png)

**Comment by fangykai** [comment]
Was told to comment on; even with the latest beta version it is still difficult to read highlights with Dark Mode UI

**Comment by annieappflowy** [comment]
I'm sourcing a designer to work on this

**Comment by tuqueque** [comment]
(I'm adding this as a commend here as @apomalyn suggested).

Hello. First of all, thank you for making this incredibly promising application. I really hope this project takes off. We need a proper Notion alternative and this one seems really well done.

My problem is with the dark theme setup. When I use it, highlighted text becomes unreadable...
![2022-09-14_12-06](https://user-images.githubusercontent.com/13471025/190207484-563eafd2-482f-40bf-abd7-84d327f0989f.png)

My suggestion: make the highlighting colors "semi transparent" inside the program (like 50%). So if the user sets a green highlight, it looks like a light-green with the white background of the bright theme of the application, generating good contrast with the black text... and that same semi-transparent green, looks like dark-green with the black backdround of the dark theme, making good contrast with the white text.

Thank you in advance!

**Comment by Jmsi18** [comment]
Hello, annie...
congratulations for this great project that is AppyFlow...I'm sure it will become one of the best options to other apps of its kind. For now I join those who suggest improving the readability of the text in the dark theme. Hopefully in the future you have an open color palette for the user to choose the color of your preference.
And I think it will solve many improvement reports.
Greetings!!!

**Comment by brodiefairhall** [comment]
I understand a designer is needed to fix this, I am adding this comment for completeness.

I am also having issues with poor contrast for the following items;
**Options in a "Select" property on a Board or Grid** 

![Screenshot from 2023-01-26 15-34-17](https://user-images.githubusercontent.com/13863518/214759642-340c0159-dab0-444c-977c-d1b7ee273ecb.png)

![Screenshot from 2023-01-26 15-41-28](https://user-images.githubusercontent.com/13863518/214759975-f0127228-712a-432e-b625-ad22ecdf71bc.png)


**Tooltip text**
![Screenshot from 2023-01-26 15-33-52](https://user-images.githubusercontent.com/13863518/214759727-5faf217a-9d88-4166-bb83-6d7f422a41eb.png)
 

**Desktop:**
    OS: Linux (Fedora 37 Gnome 43.2 Wayland)
    Version 1.0.0.1 (Flatpak)

Thank you for your amazing application and contribution!

**Comment by annieappflowy** [comment]
Upcoming v0.1.3 fixed this
<img width="282" alt="image" src="https://user-images.githubusercontent.com/12026239/233054987-64094228-60d3-410c-a9a6-d51069be85fc.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/12026239/233055413-de92c6f0-cc6f-47bd-b8c2-75177612e016.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/12026239/233055721-5d7c0172-891f-471b-9347-a169e33191e2.png">
