### ISSUE TITLE
[Bug] "No preview available" message can not be removed

### ISSUE THREAD

**Issue by abcamus** [AppFlowy-IO/AppFlowy#4334]
### Bug Description

When pasted a hyperlink which I can not access through network. The editor shows the message "No preview available".

There is no menu on mouse hover, and no way to remove this block.

### How to Reproduce

paste an invalid network address, "http://192.168.100.100/" for example. 

### Expected Behavior

I can still remove this network link block.

### Operating System

Windows 11

### AppFlowy Version(s)

0.4.1

### Screenshots

![Uploading image.png…]()

**Comment by JosueGauthier** [comment]
Hello, 

I had the same problem. The only solution I found while waiting for the fix is to do Ctrl+Z to undo your changes.

**Comment by annieappflowy** [comment]
Fixed
<img width="913" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/eddf719f-e03f-47d0-a662-46349fca0224">
