### ISSUE TITLE
[Bug] Issue Description: Unexpected Expansion Tile Icon in Single-Page View

### ISSUE THREAD

**Issue by Jayaprakash-dev** [AppFlowy-IO/AppFlowy#4336]
### Bug Description

The current implementation of the app's sidebar displays a folder view containing pages and subpages. However, an unexpected behaviour has been identified when dealing with single-page folders, specifically calendar, grid and board pages. 

When a folder contains only a single page, the sidebar incorrectly displays an expansion tile icon and 'No Pages inside' message init, which is not expected behaviour.

### How to Reproduce

Navigate to the sidebar.
Locate a folder containing only a single page like Calendar, Grid or Board page.

### Expected Behavior

For single-page folders, we do not anticipate or intend to show an expansion tile icon and a list view.
It should create a `SingleInnerViewItem` widget without an expansion tile icon instead of `InnerViewItem` widget.

### Operating System

All

### AppFlowy Version(s)

0.4.1

### Screenshots

<img width="249" alt="Screenshot 2024-01-08 at 9 24 29 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/68953739/ec7c01f8-3e44-428b-9c69-071ea5b03152">

**Comment by Jayaprakash-dev** [comment]
Hey @**annieappflowy** @**Xazin**,

If this behaviour is unintended or not expected, I would like to work on this.

I would like to suggest a quick and effective solution: If the desired document page view is a single-page layout, such as Calendar, Board, or Grid pages, we can streamline the UI by exclusively building the  `SingleInnerViewItem` without including its expansion tile icon on the left side and the wrapping expansion feature for this view item.

**Comment by LucasXu0** [comment]
> I would like to suggest a quick and effective solution: If the desired document page view is a single-page layout, such as Calendar, Board, or Grid pages, we can streamline the UI by exclusively building the SingleInnerViewItem without including its expansion tile icon on the left side and the wrapping expansion feature for this view item.

Agreed. You can disable the 'No page inside' tip when the page layout type is either Calendar, Board, or Grid.
