### ISSUE TITLE
[FR] Recently viewed area on mobile

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4338]
### Description

When displaying the most recently accessed pages, I find the tiles to be too large. Considering smaller displays, they should only have the necessary height (see screenshot 2).
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7e05f4fb-2b48-4575-a9f1-acbe362b89a0)

### Impact

Mobile users

**Comment by Xazin** [comment]
This is no longer relevant, closing as completed. :+1:
