### ISSUE TITLE
[FR] self-host support mobile

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4340]
### Description

Can we switch the url in the mobile app to self hosted as well? Or is there a workaround in the mean time?

### Impact

self-hosting appflowy users

**Comment by LucasXu0** [comment]
For now, I have disabled the self-hosted entry on the mobile platform with the beta AppFlowy cloud server. The entry will only show if we publish AppFlowy without embedding the beta cloud server.

Is it necessary to display the entry even when the application has been linked to the AppFlowy cloud? In my opinion, it's a little redundant. For internal use, of course, we can still display the entry.

**Comment by vlbosch** [comment]
I wouldn't mind two versions. One with the Cloud server you're offering and one version where people can login on their own server (be it Cloud or Supabase). Some VOIP providers for example provide two versions as well. One for their hosting and one for connecting to other servers. 

If you prefer to provide only one version , I would default to the AppFlowy server, but provide a button to change to self hosted servers. If left blank, then default to the AppFlowy cloud server again. 

Looking forward to a build I can use with my self hosted server. Thanks in advance! :-)

**Comment by annieappflowy** [comment]
@vlbosch you can log in randomly and go the cloud settings to connect to your server
In the upcoming mobile version, there will be a self-hosted login option on the startup page
