### ISSUE TITLE
[Bug] Workspace failed to load

### ISSUE THREAD

**Issue by system125** [AppFlowy-IO/AppFlowy#4341]
### Bug Description

It fails on startup!

### How to Reproduce

It started occuring after i started to share directory across multiple devices. It did disappear after fresh reinstall.

### Expected Behavior

I expected it to open without any fault!.

### Operating System

windows

### AppFlowy Version(s)

0.4.1

### Screenshots

![Screenshot 2024-01-09 120600](https://github.com/AppFlowy-IO/AppFlowy/assets/67843153/31138a0c-9d36-4d3b-bed3-f3a6a8393495)

**Comment by annieappflowy** [comment]
Did you save the data folder on Google Drive?

**Comment by SekiBetu** [comment]
When I log in to Windows 11 using the administor account, a clean install of appflowy to open the local session mode does the same thing, can't read the data

**Comment by annieappflowy** [comment]
Please try 
1. Locate the data folder: C:\Users\YOUR_USER_NAME\AppData\Roaming\AppFlowy.io\AppFlowy\data
In the data folder, there should exist a folder named "AppFlowyDoNotRename" 
2.Copy the folder and paste it into a secure local location, or compress it into a zip file and email the zip file to yourself for safekeeping.
3. Delete the folder
4. Restart AppFlowy to see if it's successfully opened.
5. Unzip your backup folder
6. Go to Settings --> Files --> Import your backup folder

<img width="1332" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/64d599ea-ec20-43dd-af54-46b1c2cdaffd">

You're welcome to join our [Discord server ](https://discord.gg/9Q2xaN37tV)for quick help
