### ISSUE TITLE
[Bug] Can't create a new document when there is no internet connection AppFlowyCloud Beta

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#4344]
### Bug Description

I am on AppFlowy Cloud beta but can not create a new document when am offline. I can create a grid, board and calendar but not a document. Only when connection is restored can I create a new document.

### How to Reproduce

1. Log into AppFlowyCloud on the AppFlowy application.
2. Ensure the internet connection is on and create a new file `document` type.
3. Turn off the internet then try to create a new `document` offline. Which should refuse.

### Expected Behavior

I expect to be able to create a `document` offline and not have to be online to create a `document`.

### Operating System

ArchCraft Linux + Reproduced on MacOS
### AppFlowy Version(s)

0.4.1

### Screenshots

The screen recording of me doing the action is [here](https://icedrive.net/s/FbN5gGjf9gAPuWjTBg18YNZtQ6xj)

**Comment by appflowy** [comment]
fix #4350
