### ISSUE TITLE
[FR] Image issues

### ISSUE THREAD

**Issue by mieyeaa** [AppFlowy-IO/AppFlowy#4346]
### Description

The imported image seems to be unable to be dragged by the mouse.

The expansion ratio of the imported image is too large.

The image cannot be enlarged and expanded by a mouse click, which is done very well (notion and anytype).

### Impact

Users who primarily rely on image recording.

**Comment by Xazin** [comment]
I will close this considering we can resize the image in a simple block, have multiple images layout in an image browser or grid gallery, and we can now expand images by double clicking to pan and zoom.
