### ISSUE TITLE
[Bug] No option to log in on desktop

### ISSUE THREAD

**Issue by davystrong** [AppFlowy-IO/AppFlowy#4351]
### Bug Description

I feel I'm missing something, but I got access to AppFlowy mobile and logged in to GitHub. However, I can't work out how to log in to GitHub on my computer. The [documentation](https://docs.appflowy.io/docs/guides/sync-desktop-and-mobile) suggests I should get a screen like this when I start the app for the first time:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/22416924/fe9e1389-e70f-4600-8d9a-37c4835a8a61)
So I deleted my data (I was just testing), uninstalled my current version and installed the latest version. However, my start screen doesn't have the option to log in:
<img width="687" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/22416924/1104b435-2f21-4e27-b2e4-d823817e6345">
And when I click quick start, it just opens the home page, with my notes on it.

### How to Reproduce

1. Start a fresh install of AppFlowy.
2. Observe how there is no login button.

### Expected Behavior

A login button for GitHub.

### Operating System

macOS 14.2.1

### AppFlowy Version(s)

0.4.1

**Comment by LucasXu0** [comment]
Hi, @davystrong. Did you join our desktop beta program?

**Comment by davystrong** [comment]
Hi @LucasXu0, thanks for your reply! No, I tried to sign up for the cloud beta a while ago but never received anything further. Never signed up to a desktop beta program, if that's something different.

**Comment by LucasXu0** [comment]
You can DM annie@appflowy on Discord to get the latest cloud desktop version. The packages from GitHub releases are not the cloud version.

**Comment by davystrong** [comment]
Perfect, thanks!

**Comment by annieappflowy** [comment]
The cloud version is available to download from the release page
