### ISSUE TITLE
[Bug] Mobile: minor updates to the getting started document

### ISSUE THREAD

**Issue by halr9000** [AppFlowy-IO/AppFlowy#4365]
### Bug Description

I'm sure you know this but for the record, several items need to be modified to apply well to the mobile client. For example:

* No Sidebar
* No/commands

### How to Reproduce

Open getting started page

### Expected Behavior

The page should be either customized for mobile, or include both mobile and desktop items

### Operating System

android

### AppFlowy Version(s)

0.4.1

**Comment by annieappflowy** [comment]
Updated in the upcoming release (v0.6.8)
