### ISSUE TITLE
Make it easier to rename new page

### ISSUE THREAD

**Issue by halr9000** [AppFlowy-IO/AppFlowy#4367]
### Description

I usually, but not always want to choose the title as I create a page. But I NEVER want a page called untitled! Consider an automatic naming convention feature such as https://en.m.wikipedia.org/wiki/Zettelkasten

### Impact

Every single time I create a note

**Comment by MariMightyMedia** [comment]
I'd like to have that to +1

**Comment by Xazin** [comment]
I've added a shortcut (F2) to rename current view. Let me know if you have any suggestions for improvements.

Will close this for now.

**Comment by halr9000** [comment]
> I've added a shortcut (F2) to rename current view. Let me know if you have any suggestions for improvements.

How would this help on mobile? Please also try the same workflow from there. No such thing at an F2 on phones. :)

**Comment by Xazin** [comment]
> > I've added a shortcut (F2) to rename current view. Let me know if you have any suggestions for improvements.
> 
> 
> 
> How would this help on mobile? Please also try the same workflow from there. No such thing at an F2 on phones. :) 

I think the automatic naming conventions similar to Zettelkasten would be too non-specific and generic to work for most use cases. I would say this is really specific.

We can improve renaming pages on Mobile, of course. But I think the two taps to rename the current page doesn't seem too bad to me.

In the future we will have the title of the view at the top of a document/database to be readily editable, also on Mobile.

**Comment by halr9000** [comment]
> I think the automatic naming conventions similar to Zettelkasten would be too non-specific and generic to work for most use cases. I would say this is really specific.

For the record, I respect Zettelkasten-style systems and want that to work for me, but am not quite a convert, mainly due to not having found a tool which automatically takes care of the parts I don't want to think about, or when I have, I didn't find appealing the amount of perceived work required to learn and customize that system to do what I wanted. (Mostly thinking of Obsidian in the latter case, into which I have invested much time an typing.)

> We can improve renaming pages on Mobile, of course. But I think the two taps to rename the current page doesn't seem too bad to me.

Agree to disagree, but that's ok, as there's no one right way to please everyone in this realm of Personal Knowledge Management. The "P" aspect has to do with how we've trained our brains to work over years and decades of various kinds of notetaking. In my case, key requirements are: 
1. super minimal time-to-notetaking
  - forcing me to make decisions such as where to place a note or what to title it can kill an idea mid-stream
2. automated/templated title, metadata extraction & classification
  - knowing what causes (1), it is equally unlikely that I will remember to "properly" categorize a note, resulting in "Untitled Note Syndrome", and inability to make best use of past notes.

> In the future we will have the title of the view at the top of a document/database to be readily editable, also on Mobile.

Looking forward to this! Have you considered some sort of simple template/macro system? There's no need to change a title when creation follows a pattern that makes sense to the user
