### ISSUE TITLE
[Bug] there is no sorting by "Last modified time" or "Created time" in table mode

### ISSUE THREAD

**Issue by u5893405** [AppFlowy-IO/AppFlowy#4369]
### Bug Description

There is no option to sort by "Last modified time" or "Created time" in table mode.
It could be called "lack of feature", but since columns "Last modified time" or "Created time" could be created, lack of sorting by them could be considered as a bug.

### How to Reproduce

Create or open any table (spreadsheet), create "Last modified time" or "Created time" types of columns, press "sort" button on top-right above table, press "Sort" button on the left, press "Add sort" and see that there's no option to sort by "Last modified time" or "Created time" in table mode.

### Expected Behavior

To have sorting by these columns too.

### Operating System

Linux

### AppFlowy Version(s)

0.4.1

**Comment by richardshiue** [comment]
Closing as completed via https://github.com/AppFlowy-IO/AppFlowy/pull/4601

**Comment by annieappflowy** [comment]
<img width="736" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/7f2c3455-83c7-4775-b295-8f57d1492826">
@u5893405 , please try it out with the latest release.
