### ISSUE TITLE
[FR] Feature/Bug report button

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#437]
**1~3 main use cases of the proposed feature**

As a user when I see a bug or possible enhancements I would like to easily fill an issue with an annotated screenshot from the application.

**what types of users can benefit from using your proposed feature**

All the users.

**Additional context**

On another [project](), I worked on, we used the [feedback plugin](https://pub.dev/packages/feedback) mixed with the [Github plugin](https://pub.dev/packages/github) (and some community_plus plugins to get the version of the app, devices, etc.) to achieve that.

**Comment by annieappflowy** [comment]
<img width="186" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/3505c773-80c7-4019-a210-7fc4ae6d17c7">
