### ISSUE TITLE
[Bug]  Android App stuck "signing in..."

### ISSUE THREAD

**Issue by MikeyC3040** [AppFlowy-IO/AppFlowy#4371]
### Bug Description

Logging in/signing up with the GitHub and Google get to the signing in spinning icon, but never progresses.
If interrupted, and app reopens it just crashes.

### How to Reproduce

Login with OAuth options

### Expected Behavior

Finish logging in and take me to whatever is the initial screen

### Operating System

Android Version 14

### AppFlowy Version(s)

0.41

### Additional Context

Running on galaxy z flip 5 with all the latest updates. Tried switching between the 3 browsers on the device, with clearing data in between

**Comment by LucasXu0** [comment]
Hi, @MikeyC3040. Can you DM me your Google account on Discord? I will invite you to join our Google Play internal test.

**Comment by MikeyC3040** [comment]
> Hi, @MikeyC3040. Can you DM me your Google account on Discord? I will invite you to join our Google Play internal test.

Done!

**Comment by LucasXu0** [comment]
sent.

**Comment by lakano** [comment]
Hi, I have the same problem with Discord and Github account. I haven't tested with Google as I doesn't own an account.
BTW, my phone is an un-google phone ( "e/OS", similar to LineageOS ).
