### ISSUE TITLE
[FR] Auto reference/index sub pages in parent page

### ISSUE THREAD

**Issue by Disar** [AppFlowy-IO/AppFlowy#4372]
### Description

A function that allows us to create an index of references to all sub pages in the parent page. 

### Impact

I use empty pages as separators for projects which usually end up with nothing in them.
It would be great if it's possible to auto generate an index of references to all child documents, recursively.

This way you don't have to scroll through your outliner and expand every sub page. It gives you a quick overview what is available in the parent doc.

### Additional Context

* Give the user the option to choose the depth of references to create  ( i.e 1 = only create an index for immediate child pages but not the child pages of those pages.
* Maybe give the option to choose the root to start from. The root must be one of the sub pages of the page the index will be generated in. Being able to create multiple indexes might give a more impactful oversight of the important docs when dealing with many of them. 
* references should be a simple bullet list with indentation for every depth.

**Comment by Jayaprakash-dev** [comment]
Hey @Disar, I've made a [pull request](https://github.com/AppFlowy-IO/AppFlowy/pull/4420) that will fix this issue.

**Comment by Jayaprakash-dev** [comment]
Hey @Disar, I've submitted a [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/4420) that will fix this issue.

**Comment by lalomartins** [comment]
This was never merged, so maybe the FR shouldn't be closed until that happens?

**Comment by Xazin** [comment]
> This was never merged, so maybe the FR shouldn't be closed until that happens?

This is a duplicate of #4282 thus it doesn't need to stay open, the PR also links to the original issue.
