### ISSUE TITLE
[FR] outline improvements

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4377]
### Description

is there a way to create auto references on a parent doc of all the child documents and task boards?

### Impact

Wiki users

**Comment by PeterHero** [comment]
Is the meaning of the feature the same as #4282?

**Comment by Jayaprakash-dev** [comment]
Hey @annieappflowy, is this issue related to #4282 ? If so, I've submitted a [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/4420) that addresses this issue.
