### ISSUE TITLE
[Bug] Docker build error

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#4389]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/actions/runs/7519924478/job/20469034083

### How to Reproduce

- build the docker image

### Expected Behavior

- no errors

### Operating System

Linux

### AppFlowy Version(s)

0.4.2

**Comment by richardshiue** [comment]
This should be fixed by https://github.com/AppFlowy-IO/AppFlowy/commit/c41a7aaacf970a7c66bbbefe99a6fd73867f2e54#diff-5a4e027ebbe7a4e655dd8464433e70c9ff647fbd379bd4a3e8c47fddf5052931
