### ISSUE TITLE
[Bug] Cannot install android app.

### ISSUE THREAD

**Issue by ayan-iiitd** [AppFlowy-IO/AppFlowy#4396]
### Bug Description

I tried installing the v0.4.2 on two Android devices, one with Android 12 and one with Android 10. Both couldn't install it with the following error - `There was a problem parsing the package.`

### How to Reproduce

Trying to install it on an Android device.

### Expected Behavior

Installs correctly.

### Operating System

Android 10, 12

### AppFlowy Version(s)

v0.4.2

**Comment by LucasXu0** [comment]
@ayan-iiitd you can try to install it from Google play. https://play.google.com/store/apps/details?id=io.appflowy.appflowy

**Comment by ayan-iiitd** [comment]
> Only invited members can access that page no? Since it's not yet released, and is only a test version. (At least I can't access it)

You are right, link doesn't open. 


> PS. Our `minSdkVersion` is set to `33` -> Android 13, we should set it to eg. 29 or 26. (29 = Android 10 and up, 26 = Android 8 and up)

Thanks. Would love to test and report back.

**Comment by LucasXu0** [comment]
I have made the link public and updated the latest APK on GitHub release, ensuring support for API level 29 or higher (Android 10 and above).
