### ISSUE TITLE
[Bug] Can't use v.0.4.2 after I killed it via Task manager app and restarted app

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#4399]
### Bug Description

I updated AppFlowy from 0.4.1 to 0.4.2 (Win_x64-86 ZIP). Then did first launch. Unexpectedly got empty window. Killed it with Task manager. Restart AppFlowy and got this: 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7080928/ef932572-c1ba-4216-8411-da5e3626ab3b)
Close window and launch `AppFlowy.exe` again. Nothing new. I see error page again. I even can't reset anything!
[log_2024-01-15.txt](https://github.com/AppFlowy-IO/AppFlowy/files/13941759/log_2024-01-15.txt)

### How to Reproduce

See above.

### Expected Behavior

All works fine on 0.4.1.

P.S. **I had to downgrade version to 0.4.1.** Then it started normally, yahoo!

### Operating System

WIn 8.1 x64.

### AppFlowy Version(s)

0.4.2 (x64-86 ZIP-version from Github)

### Additional Context

Account is local, no cloud connection

**Comment by Xazin** [comment]
From your logs it seems you used OneDrive to store AppFlowy Data.
```
{"msg":"[INITIALIZE - Event] 🔴open collab db error: Error { message: \"IO error: No such file or directory: Failed to open LogFileC:\\\\Users\\\\poshi_000\\\\OneDrive\\\\🔙🆙🈁🔲🆔\\\\AppFlowy\\\\appflowy_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk/203107150254313472\\\\collab_db\\\\logs/C__Users_poshi_000_OneDrive______________________AppFlowy_appflowy_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk_203107150254313472_collab_db_LOG: ������� �� ������� ����� ��������� ����.\\r\\n\" }","uid":203107150254313472,"workspace_id":"f9a9f3d8-7fed-4f2a-8661-0e3944590122"}
```

What most likely happened, is you killed the AppFlowy process, but OneDrive locked the file and thus AppFlowy couldn't read it when you opened it again. At least that would be one of the most reasonable explanations for RocksDB to throw an IO error.

The screen you see appears when 1. Workspace data is corrupt (unlikely in this case), or 2. Failed to read Workspace data (eg. file is locked by system, can happen in Windows especially in virtual drives).

**Comment by Twilightssuperb** [comment]
But when I downgraded to 0.4.1, that AppFlowy version starts as usual, nothing is locked...

**Comment by appflowy** [comment]
@Twilightssuperb thank you for bringing this to our attention. The error is occurring because the log file's name is excessively long. We will address this issue and release a new version with the fix.

**Comment by annieappflowy** [comment]
Fixed. @Twilightssuperb , please try the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.4.3) and let us know how it goes

**Comment by Twilightssuperb** [comment]
> try the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.4.3) and let us know how it goes

No ZIP-file available. ☹ I prefer portable/standalone apps.
