### ISSUE TITLE
[FR] CodeBlock may use monospace font

### ISSUE THREAD

**Issue by FOWind** [AppFlowy-IO/AppFlowy#4405]
### Description

Currently CodeBlock use the default font, but generally CodeBlock may use monospace font

### Impact

CodeBlock will use use monospace font

**Comment by Xazin** [comment]
> This issue was closed as completed, but my code blocks still use whatever font I have configured for the app (not a monospace font).

We close issues when the pull request to resolve it has been merged. That means the next version will include the resolution, you'll see the monospace font in 0.5.5.
