### ISSUE TITLE
[Bug] Chinese input problems

### ISSUE THREAD

**Issue by naheux** [AppFlowy-IO/AppFlowy#4407]
### Bug Description

When I use MacOS default Simplified Chinese Pinyin Input Method, two problems occur.
1. The Chinese characters are converted to their spelling letter form after page switch;
2. Can't input anything after the letter input by Simplified Chinese Pinyin Input Method;

### Problem-1
Reproducibility: ocassionally

Phenomenon:
First, spell some Chinese characters with Simplified Chinese Pinyin Input Method
<img width="480" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/105796616/898ab85e-f465-4966-a331-4dc0670703b7">
Second, confirm the selected Chinese characters to complete the input with "SPACE" key(or "1" key)
<img width="259" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/105796616/c4737a17-9866-4c40-ab2d-edd1bf5330ca">
Then, switch to other page and switch back, the Chinese characters become their spelling letter form
<img width="258" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/105796616/02895f03-9baa-487c-bca3-e928ca73b9b8">

### Problem-2
Reproducibility: always

Phenomenon:
First, input only one letter with Simplified Chinese Pinyin Input Method
<img width="480" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/105796616/aa370e51-158f-465d-8ba8-9e8ff9c73c01">
Second, use "ENTER" key to complete the input(this is a fast way to input letter without switching Input Method)
<img width="315" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/105796616/3257f45b-e9dd-4f32-83ea-a7a7bda5e244">
Then, any letter input and DELETE key are ignored by AppFlowy unless I input numbers or "SPACE".

### Problem-1
Expected: stick to Chinese characters, no fallback to spelling letter form

### Problem-2
Expected: no stuck cursor

### Operating System

MacOS 14.2.1

### AppFlowy Version(s)

0.8.3

**Comment by annieappflowy** [comment]
Should be fixed already
