### ISSUE TITLE
[Bug] Paste text into a callout block

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4421]
### Bug Description

It was changed the "callout" type into the normal type after I pasted the text.
That means the "callout" icon disappears.
When I press shift + enter, it will new input line, and then I can paste the text.
But I have to return to the last line to delete the blank line. It's not make senes.

### How to Reproduce

Insert a callout block
Paste more than one line of text

### Expected Behavior

Auto expand the height of the callout block to fit the pasted text

### Operating System

macOS

### AppFlowy Version(s)

v0.4.3

**Comment by jpenna** [comment]
I think this is the same as this? https://github.com/AppFlowy-IO/appflowy-editor/issues/679

**Comment by hyj1204** [comment]
It should be fixed by https://github.com/AppFlowy-IO/appflowy-editor/pull/689
