### ISSUE TITLE
Release/package_info_plus.build/Objects-normal/x86_64/Binary/package_info_plus normal x86_64 (in target

### ISSUE THREAD

**Issue by zyxcambridge** [AppFlowy-IO/AppFlowy#4427]
sers/zhangyixin/Desktop/appflowy/frontend/appflowy_flutter/build/macos/Build/Intermediates.noindex/Pods.buil
d/Release/shared_preferences_foundation.build/DerivedSources -Xcc -DPOD_CONFIGURATION_RELEASE\=1 -Xcc
-DCOCOAPODS\=1 -emit-objc-header -emit-objc-header-path
/Users/zhangyixin/Desktop/appflowy/frontend/appflowy_flutter/build/macos/Build/Intermediates.noindex/Pods.build/
Release/shared_preferences_foundation.build/Objects-normal/arm64/shared_preferences_foundation-Swift.h
-import-underlying-module -Xcc -ivfsoverlay -Xcc
/Users/zhangyixin/Desktop/appflowy/frontend/appflowy_flutter/build/macos/Build/Intermediates.noindex/Pods.build/
Release/shared_preferences_foundation.build/unextended-module-overlay.yaml -working-directory
/Users/zhangyixin/Desktop/appflowy/frontend/appflowy_flutter/macos/Pods -no-emit-module-separately-wmo
[   +1 ms] warning: Run script build phase 'Run Script' will be run during every build because it does not
specify any outputs. To address this warning, either add output dependencies to the script phase, or configure
it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter
Assemble' from project 'Runner')
[        ] ** BUILD FAILED **
[        ] The following build commands failed:
[        ]      Ld
/Users/zhangyixin/Desktop/appflowy/frontend/appflowy_flutter/build/macos/Build/Intermediates.noindex/Pods.build/
Release/package_info_plus.build/Objects-normal/x86_64/Binary/package_info_plus normal x86_64 (in target
'package_info_plus' from project 'Pods')
[        ] (1 failure)
[   +4 ms] Building macOS application... (completed in 24.2s)
[        ] "flutter macos" took 34,096ms.
[   +1 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:159:5)
           <asynchronous suspension>
           #2      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +209 ms] ensureAnalyticsSent: 209ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
[cargo-make][1] ERROR - Error while executing command, exit code: 1
[cargo-make][1] WARN - Build Failed.
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: restore-crate-type
[cargo-make] ERROR - Task error detected, exit code: 1
[cargo-make] WARN - Build Failed.
(base) zhangyixin@zhangyixin frontend % cargo make --profile production-mac-arm64 appflowy

**Comment by LucasXu0** [comment]
@zyxcambridge Please provide the version of Flutter you're using, and the type of Mac chip.

**Comment by Xazin** [comment]
Hey @zyxcambridge , as we haven't heard back from you, I'm going to close this issue.

If you're still experiencing trouble or in need of assistance, feel free to open a new issue or reach out to us on discord.
