### ISSUE TITLE
[FR] Add to Favorites

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#443]
**1~3 main use cases of the proposed feature**
Favoriting a page allows users to quickly access it without searching it or clicking through nested pages

**what types of users can benefit from using your proposed feature**
Users who have go-to pages that are frequently visited

**Additional context**
Key features:  
- Favorite a page: navigate to a page, then click a button at the top right of the page. 
- Favorites: a section in the left sidebar. It will appear when you favorite your first page. Here you can find pinned pages.
- Remove from Favorites: an option for the user to unpin a page

Scope: well-defined (see Key features) native application development

Difficulty level: Medium
Skills required: Flutter, Rust

**Comment by squidrye** [comment]
Implementation flow

- [ ] Update the view struct in AppFlowy-Collab
- [ ] Expose a new method that calculates the views marked as favorite
- [ ] update the ViewPB and add a new handler that marks view as a favorite
- [ ] add tests in collab and rust-lib
- [ ] update the frontend with a new bloc to use backend handlers
- [ ] add unit / integration tests in flutter

**Comment by squidrye** [comment]
Hey @annieappflowy, kindly assign me to this issue.

**Comment by annieappflowy** [comment]
Assigned. Thanks!
