### ISSUE TITLE
[FR] Hi! friend! Why not provide a .zip file?

### ISSUE THREAD

**Issue by zhouxinghong** [AppFlowy-IO/AppFlowy#4436]
### Description

Hi! friend! Why doesn’t Windows system provide .zip installation-free files?

### Impact

Hi! friend! Windows systems hope to continue to provide .zip installation-free files as before. Thank you so much!

**Comment by aliesbelik** [comment]
#4430

**Comment by LucasXu0** [comment]
Hey, @zhouxinghong. I have uploaded the Windows package in ZIP format.

**Comment by zhouxinghong** [comment]
Hi! Friends, may I ask if the data directory has been changed.
The previous data directory was:
`AppFlowyDataDoNotRename`
The data directory of version 0.43 has changed to: `AppFlowyDataDoNotRename_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk`?
