### ISSUE TITLE
[Bug] I save a Chinese character, it becomes Pinyin when I reopen it.

### ISSUE THREAD

**Issue by 2lovecode** [AppFlowy-IO/AppFlowy#4439]
### Bug Description

I save a Chinese character, it becomes Pinyin when I reopen it.

Before：
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/22025624/5406e96c-db2d-4767-99be-bc62d4718de3)

After：
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/22025624/6ebbfc02-18f9-4ed1-9add-b2b249ee04ad)

### How to Reproduce

1.create a document, named "test-01"
2.input chinese character "并发" and save
3.reopen "test-01",it becomes "bign fa"

### Expected Behavior

No matter when you open it, it will always be in Chinese characters

### Operating System

macOS 14.2.1

### AppFlowy Version(s)

Version 0.3.9 (1)

**Comment by rustui** [comment]
I am also encountering the same issue.

Operating System
macOS 14.2.1
AppFlowy Version(s)
Version 0.4.3

**Comment by LucasXu0** [comment]
Hi, @2lovecode. Thanks for reporting. It will be solved in the next version.

**Comment by lidangg** [comment]
希望尽快修复
拼音输入正常的话，还可以试用一下

**Comment by LucasXu0** [comment]
closed as completed. https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/178
