### ISSUE TITLE
[FR] simplify the menu display

### ISSUE THREAD

**Issue by abcamus** [AppFlowy-IO/AppFlowy#4472]
### Description

when page has no child, omit expand button and "No page inside".
something like this

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/17241681/c1b56b57-9c44-4a86-969c-0d4a1dbae2bb)

### Impact

make the side menu shorter; easier to know whther the page has any child.

**Comment by abcamus** [comment]
hi @annieappflowy , can I try working on this?

**Comment by annieappflowy** [comment]
@abcamus , we have revamped the sidebar and fixed the issue. If there isn't an expand icon, there isn't a subpage inside.
