### ISSUE TITLE
[FR] Have a way to submit bug reports on mobile

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#4474]
### Description

Having a way to implement submit bug reports for mobile device would be useful for debugging.
Ideally if there can be a button that can just copy the latest debug log or allow the user to upload the file to a new issue.
![2024-01-24T05:50:55,158568192+02:00](https://github.com/AppFlowy-IO/AppFlowy/assets/42723553/634f820e-feff-4b7e-bbca-4b16b0c8909e)
On desktop there is a log file in the default data folder, so am going to assume on mobile a similar file is there, which can be used for debugging.

### Impact

Improve debugging problems and troubleshooting the mobile app.

**Comment by LucasXu0** [comment]
closed as completed.
