### ISSUE TITLE
[Bug] Undo/redo makes list items disappear.

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#4487]
### Bug Description

It seems the undo/re-do history is messed up when using it on lists.

### How to Reproduce

[Screencast from 2024-01-24 19-11-51.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/fcde4022-cce3-470d-8974-43f0434b13b7)

At the end of the video all I used was CTRL+Z several more times.

### Expected Behavior

Should go one step at a time using undo/re-do.

### Operating System

Linux

### AppFlowy Version(s)

0.4.3

**Comment by StartAGarden** [comment]
@LucasXu0 Is there any news on this? This is actually a critical bug for me, it has happened several times and I have lost important data from this. Data consistency or at least the option to undo what happened would be extremely important for me to be able to use Appflowy further...

**Comment by LucasXu0** [comment]
Trying to fix it in the next version 0.5.0. I am able to reproduce it now.

**Comment by emmggi** [comment]
@LucasXu0 Looking forward to it. I'm not using the app anymore because of some of these breaking features. This and https://github.com/AppFlowy-IO/AppFlowy/issues/4492.
