### ISSUE TITLE
[Bug] Turning list item to heading removes items of the list

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#4492]
### Bug Description

Using `### ` to create a heading will make the items of the list disappear.

### How to Reproduce

[Screencast from 2024-01-25 09-47-15.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/1f4b11cc-f48f-4b48-98fd-6abc8d2c399f)

### Expected Behavior

I would like to turn this item into a heading.

### Operating System

Linux

### AppFlowy Version(s)

0.4.3

### Additional Context

Strange thing is even if you remove the bullet from `Item 1` and try turning it into a heading it will do the same. 

Trying to retrieve the data using CTRL+Z/Y can result in data loss. Undo/redo doesn't do anything anymore after a few tries.

**Comment by LucasXu0** [comment]
This issue has been addressed and will be included in the next version.
