### ISSUE TITLE
[Bug] Certain documents won't open.

### ISSUE THREAD

**Issue by Joso997** [AppFlowy-IO/AppFlowy#4509]
### Bug Description

Certain documents won't open.

computerName: DESKTOP-RAZVOJ.tri-m.local
numberOfCores: 12
systemMemoryInMegabytes: 32768
userName: sivanusec
majorVersion: 10
minorVersion: 0
buildNumber: 19045
platformId: 2
csdVersion: 
servicePackMajor: 0
servicePackMinor: 0
suitMask: 256
productType: 1
reserved: 0
buildLab: 19041.vb_release.191206-1406
buildLabEx: 19041.1.amd64fre.vb_release.191206-1406
digitalProductId: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 192, 12, 47, 48, 83, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 3, 0, 0, 0, 0, 0, 80, 203, 39, 59, 83, 2, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 32, 180, 37, 59]
displayVersion: 22H2
editionId: Professional
installDate: 2021-09-06 06:33:48.000
productId: 00330-80000-00000-AA760
productName: Windows 10 Pro
registeredOwner: Dajana
releaseId: 2009
deviceId: {28D91B16-0CFD-4572-BE03-52116C0897A0}
Document: C:\Users\Sivanusec\AppData\Roaming\io.appflowy\AppFlowy\data

### How to Reproduce

Try losing internet connection while using beta cloud sync.

### Expected Behavior

Showing up the document

### Operating System

Windows 10 Pro

### AppFlowy Version(s)

0.4.3

### Screenshots

![Screenshot 2024-01-26 144821](https://github.com/AppFlowy-IO/AppFlowy/assets/23720628/725d99f5-26e5-425e-acce-5de9f45eb77c)

**Comment by LucasXu0** [comment]
@Joso997 We're fixing this issue. There's a temporary workaround: try to sign out and sign in again.

**Comment by Joso997** [comment]
workaround not working, 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/23720628/94b48d15-6265-4dda-b15b-10f8a29694bd)

**Comment by LucasXu0** [comment]
Is this issue happening on the other Windows machine you're using, not the one on which you wrote this content?

**Comment by Joso997** [comment]
it is happenig on all of them

**Comment by annieappflowy** [comment]
@Joso997 , the "MissingAuthField" issue should be fixed for now. Could you please try it again?

**Comment by Xazin** [comment]
Closing for now, feel free to let us know if you're still experiencing issues!
