### ISSUE TITLE
[Bug] Unable to login - Missing Auth Field

### ISSUE THREAD

**Issue by vedxp** [AppFlowy-IO/AppFlowy#4517]
### Bug Description

When trying to login using one of the available providers (I use Google), it throws this error:
```
code: MissingAuthField
msg:
```

### How to Reproduce

- Open Appflowy
- Try to login with Google

NOTE: Haven't tested with other providers

### Expected Behavior

Login should work without any error.

### Operating System

Android 13

### AppFlowy Version(s)

0.4.3

### Screenshots

![Screenshot_20240126-222633](https://github.com/AppFlowy-IO/AppFlowy/assets/87353286/c8223537-fcaa-478f-9e00-4abd6b3863b8)

**Comment by vedxp** [comment]
Sometimes, if the above error doesn't occur, it gets stuck at this page:
![Screenshot_20240126-222438](https://github.com/AppFlowy-IO/AppFlowy/assets/87353286/da74b521-2472-4f81-a954-96921e515000)

**Comment by emmggi** [comment]
Same thing on Linux. There's just no visible error shown. You have to run it through the terminal to get the error.

**Comment by dubeyKartikay** [comment]
I have the same bug on linux ( flatpak)

**Comment by rileydes** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/114444261/1b181f41-0464-4ac5-b7a0-903ac6650400)
Tested fresh install on Windows with 0.4.3 exe released through the website, same bug while logging in with google

**Comment by emmggi** [comment]
Mine works now. Didn't do anything it just worked.

**Comment by LucasXu0** [comment]
@vedxp Did you use self-hosting or did you just use our built-in AppFlowy cloud server?

**Comment by vedxp** [comment]
> @vedxp Did you use self-hosting or did you just use our built-in AppFlowy cloud server?

Haven't touched that option ever, it's the default (https://beta.appflowy.cloud) one.

**Comment by vedxp** [comment]
> @vedxp Did you use self-hosting or did you just use our built-in AppFlowy cloud server?

Haven't touched that option ever, it's the default (Appflowy Cloud Beta) one.

**Comment by vedxp** [comment]
Update: Login works without any error now. Haven't changed anything, just tried to login again after reading [this comment](https://github.com/AppFlowy-IO/AppFlowy/issues/4517#issuecomment-1913538647).

**Comment by LucasXu0** [comment]
FYI, some errors occurred on the server for a certain period of time. This issue has been fixed.
