### ISSUE TITLE
[FR] Add Vietnamese translations

### ISSUE THREAD

**Issue by ngthailam** [AppFlowy-IO/AppFlowy#4519]
### Description

Contributing to https://github.com/AppFlowy-IO/AppFlowy/issues/3464, I would like to add missing Vietnamese translations.

### Impact

Vietnamese national language users.

### Additional Context

None

**Comment by annieappflowy** [comment]
Thanks @ngthailam , you can submit a PR with your proposed changes.

**Comment by ngthailam** [comment]
Ticket https://github.com/AppFlowy-IO/AppFlowy/pull/4536 merged
