### ISSUE TITLE
[FR] integration of a word count tool within the app

### ISSUE THREAD

**Issue by mawnir** [AppFlowy-IO/AppFlowy#4524]
### Description

Word count by document and by selection.

### Impact

A word count feature can significantly improve writing efficiency by providing users with real-time feedback on the length of their text. and helps in organizing and structuring content effectively.

**Comment by emmggi** [comment]
Please make this togglable in the settings. Most don't need this because they take notes with the app.

**Comment by mawnir** [comment]
settings? i need it for article writing

> Please make this togglable in the settings. Most don't need this for note taking.

**Comment by LucasXu0** [comment]
@mawnir Is this a desktop or a mobile feature request?

**Comment by mawnir** [comment]
> or a mo
Desktop.

**Comment by Xazin** [comment]
I believe this would be really cool, some features that can be considered together with this one:
- Being able to see both Word Count, Character count, Character count without spaces
- Being able to select text, use a command and then see the above statistics but for only the selected text.

**Comment by Xazin** [comment]
Hey @mawnir, I've finished the initial implementation of a word/character counting service in the Editor package.

I was wondering what would fit your use-case the most, and maybe you have some insights to share.

Some ideas on the actual implementation of this in AppFlowy that came to my mind, which I thought you might be able to share your preference on was:

Would a keybind that shows the word/char count of the document (and if anything is selected, also the word and char count of the current selection) in a popup modal (See how Google Docs does this) fit your usecase?

Would you rather be able to have a small floating toast in eg. the left bottom corner of the editing area, that shows the word and character count permanently, which can be toggled on/off with a keybind or in the settings?

Or would it be enough to see just the word and character count, when pressing on the two dots in the documents top bar, similar to Notion?

---

Please let me know, I will take your thoughts into consideration when implementing it in AppFlowy.

**Comment by mawnir** [comment]
Thank you so much @Xazin  

1- For me `pressing on the two dots in the documents top bar, similar to Notion` to get the word count is enough. 

2- And for the `small floating toast in eg. the left bottom corner of the editing area`,  Yes i like the left bottom corner and would be great if visible only when selecting text.. to keep the editing area clean.

**Comment by Xazin** [comment]
> Thank you so much @Xazin
> 
> 1- For me `pressing on the two dots in the documents top bar, similar to Notion` to get the word count is enough.
> 
> 2- And for the `small floating toast in eg. the left bottom corner of the editing area`, Yes i like the left bottom corner and would be great if visible only when selecting text.. to keep the editing area clean.

Thanks for the information, I'll implement number 1 first, and then I'll see if I can implement number 2 with a decent user experience :+1:

**Comment by mawnir** [comment]
@Xazin the feature is not working with Arabic text: 
<img width="800" alt="Screen Shot 2024-04-15 at 14 53 51" src="https://github.com/AppFlowy-IO/AppFlowy/assets/62011430/5cf567a0-02a9-45f1-9a63-63bab6f57b49">

**Comment by Xazin** [comment]
> @Xazin the feature is not working with Arabic text

That's odd, the character count seems to work, I'll take a look :+1:

**Comment by Xazin** [comment]
Closing this again, the fix for the accents and arabic characters will be included in the next release, thanks @mawnir for reporting.
