### ISSUE TITLE
[FR] Add option to sync page level Appflowy to its Github repo.

### ISSUE THREAD

**Issue by salmanub** [AppFlowy-IO/AppFlowy#4526]
### Description

Setup an option to sync a Page to its equal Github repo. 
A user may organize some repos to be under a named Github project so that reflects they are related in the same project when you acces your Appflowy session.

### Impact

The SEO's freaks (they are everywhere!)

### Additional Context

I'm about to give affiliate marketing websites a try. I am a web full-stack (basically js, html and css) developer with foundation in C++ (good level in coding with C++).
To carry on every affiliates project I dev each one by using Zola framework because of its ease of use and quick path to publish.

**Comment by appflowy** [comment]
@salmanub We may not going to support this feature. I will close this feature request.
