### ISSUE TITLE
[Bug] Upload Theme doesn't allow me to upload files

### ISSUE THREAD

**Issue by singhayushh** [AppFlowy-IO/AppFlowy#4530]
### Bug Description

The modal that opens on clicking the `Upload Theme` icon doesn't allow me to upload files on clicking the `Upload` button from the modal. Instead it directly shows a message `Please wait while we validate and upload your theme`.

### How to Reproduce

Settings -> Upload Theme -> Upload

### Expected Behavior

Should open file manager to select files to upload

### Operating System

Arch Linux

### AppFlowy Version(s)

aur/appflowy-bin 0.4.3-1

### Additional Context

Went through the logs to find these error logs:
```
  2024-01-28 23:03:31 ERROR  Uncaught platform error
    at dart-ffi/src/lib.rs:178
  2024-01-28T17:33:31.351411Z ERROR dart_ffi: Uncaught platform error
    at dart-ffi/src/lib.rs:17
```

**Comment by annieappflowy** [comment]
Have you tried to upload a file by just ignoring the error message?

**Comment by Whax** [comment]
Same problem here using awesome VM. I think it works with gnome but don't have any desktop environment based on it to try :/

@singhayushh I can confirm it's the same problem of the [https://github.com/AppFlowy-IO/AppFlowy/issues/2300](2300) issue :)

```sh
  2024-02-02 07:32:47 ERROR  Uncaught platform error
    at dart-ffi/src/lib.rs:178

  2024-02-02T06:32:47.539221Z ERROR dart_ffi: Uncaught platform error
    at dart-ffi/src/lib.rs:178
```

**Comment by Whax** [comment]
Hello,

Not for me on the latest ` 0.4.6-1`, on the `AppImage` version

```sh
  2024-02-06 04:54:01 ERROR  Uncaught platform error
    at dart-ffi/src/lib.rs:179

  2024-02-06T03:54:01.881285Z ERROR dart_ffi: Uncaught platform error
    at dart-ffi/src/lib.rs:179
```

This time, the error is on line 179 ;)

**Comment by Whax** [comment]
@singhayushh 

- OS : Arch Linux
- WM / DE : Awesome

**Comment by singhayushh** [comment]
Hi @Whax,
It doesn't seem to work with the AppImage executable.

However, it worked on installing from source // pacman

**Comment by annieappflowy** [comment]
Can you share a sample file that you were tying to upload with us? We'll look into this issue.
