### ISSUE TITLE
[Bug] Links behaviour

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#454]
**Describe the bug**

I did found some issues with the link usage. Here is the list of what I found (if prefixed with 🐛 it's a bug, otherwise it's a behaviour problem):

1. 🐛  Links aren't clickable
2. 🐛 Can't remove a link without deleting the text that contains the link
3. 🐛 On the link edition/creation dialog you can type anything and it's still accepted, it should only accept URL (from web URL to system (I don't know how they are called) URL like `mailto`, `call`, etc.)
4. Link icon on the tool bar disabled until you select some text, even if your cursor is on a existing link.
5. **UPDATE** 🐛 On a link if you add text, the link is cut in two.

<details>
<summary>Link cut in two</summary>

![Screen Recording 2022-06-28 at 12 09 34](https://user-images.githubusercontent.com/22211097/176228463-a494774f-9fbc-49a1-b918-d0a5264da503.gif)

</details>

**Expected behavior**

1. A link should be clickable (or a tooltip should indicate how to open it, like for example: Ctrl + click)
2. On the dialog to set a link we could have a 'delete'/'clear' button, when we clear the URL text field and click on 'save' the link should be deleted.
3. If the URL is invalid the 'save' button should be disabled and an error message under the text field should explain the error
4. If the cursor is positioned in a link, the link button is enabled.
5. The added text should be added to the link.
6. On a long hover, the user could see a helper that should allow to open or edit the link

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 0.0.4.1

**Comment by appflowy** [comment]
Thanks @apomalyn

**Comment by johnblommers** [comment]
When the user clicks on link text nothing really happens. Ideally Appflowy would expand the link so the user can edit both the link text and the URL independently.

Normally we type `[link text](http://site.com)` by hand. When we do Appflowy does not recognize that this is a link. IMHO that would be very desirable. It's what a WYSIWYG Markdown editor would be expected to do.

**Comment by apomalyn** [comment]
> When the user clicks on link text nothing really happens. Ideally Appflowy would expand the link so the user can edit both the link text and the URL independently.
Exact. Let me update the expected behaviour to include `on a long hover, the user could see a helper that should allow to open or edit the link`. Is it okay with you?

> Normally we type `[link text](http://site.com)` by hand. When we do Appflowy does not recognize that this is a link. IMHO that would be very desirable. It's what a WYSIWYG Markdown editor would be expected to do.
Currently, AppFlowy doesn't support Markdown at all (correct me if I'm wrong @appflowy)

**Comment by johnblommers** [comment]
A long hover over a link sounds like a terrific solution.

So I just assumed Workflowy was a Markdown editor?

**Comment by annieappflowy** [comment]
Hi @apomalyn , the link feature has been significantly improved. Please have a try!

Most of the issues you reported are fixed, except for handling invalid URLs. I'll create a new issue for that. Hope to get more feedback from you soon!

- [ ]  Links aren't clickable
- [ ]  Can't remove a link without deleting the text that contains the link
- [ ] On the link edition/creation dialog you can type anything and it's still accepted, it should only accept URL (from web URL to system (I don't know how they are called) URL like mailto, call, etc.)
- [ ] Link icon on the tool bar disabled until you select some text, even if your cursor is on a existing link.
- [ ] UPDATE 🐛 On a link if you add text, the link is cut in two.
