### ISSUE TITLE
[FR] Change Notification icon from timer to bell

### ISSUE THREAD

**Issue by andersonjeccel** [AppFlowy-IO/AppFlowy#4564]
### Description

At the moment, the notifications icon is represented by a timer symbol, which can be confusing, especially when several other solutions on the market use this association to indicate some type of time count for tasks or related things.

My suggestion would be to change to an icon with greater ease of association, such as a bell.
If the purpose of the button is to really cause a feeling that something is running out of time, indicating "remaining time for the task" or similar, I would suggest using the hourglass icon, but the bell idea still sounds better.

### Impact

Users could understand the button's function more easily and potentially reduce the platform's learning curve.

**Comment by AnsahMohammad** [comment]
I would like to work on this

**Comment by Xazin** [comment]
With the sidebar redesign we have a new icon for notifications button, I will close this :+1:
