### ISSUE TITLE
[Bug] Image sync with Appflowy-Cloud (self-hosted) seems not resilient enough

### ISSUE THREAD

**Issue by j-mir-prazak** [AppFlowy-IO/AppFlowy#4568]
### Bug Description

If images are sync with Appflowy-Cloud, they do not get reuploaded, if the first try fails - yet they do get url even before the upload process if finished. As a result the image is unavailabe via the link on second device. On the first device, the image is referenced by the local path, so it is still available.

### How to Reproduce

1/ disconnect from the internet
2/ add image to the page; add text to the page
3/ connect to the internet
4/ on second device check if the page is updated - text should be available; image not

### Expected Behavior

On reconnect (maybe on open in general), the device should check local path and remote path and if the remote path does not exist and local does, should try to upload again.

### Operating System

Android 14; Fedora

### AppFlowy Version(s)

android 0.4.3; linux - build from main

### Screenshots

File does exist on phone
![Screenshot_20240131_171210](https://github.com/AppFlowy-IO/AppFlowy/assets/25672201/e4ef86fd-8cb3-4b13-852f-0cc9ddae7634)

File does not exist online
![Screenshot from 2024-01-31 17-08-17](https://github.com/AppFlowy-IO/AppFlowy/assets/25672201/eb4bdf02-c0d6-4f7d-8d18-6d5ac52601ed)

### Additional Context

The behavior is prominent if you have spotty internet connection.

Maybe indication icon that the image is indeed on the minio cloud be added? Or button to manually reupload?

**Comment by LucasXu0** [comment]
Thanksfor reporting. It is a known issue, and we are planning to optimize the image upload process in the next version.

**Comment by j-mir-prazak** [comment]
I also noticed, that often, I need to relogin on the second device, in order to get the image pulled: the first device will upload it fine (even after day of being logged in), however the second needs to be logged in again (after 15-30 minutes of being logged in)

This might be also known issue, so if it is not, let me know, i will try figure out reproducible example
