### ISSUE TITLE
[Bug] ios and macos not sync after few days

### ISSUE THREAD

**Issue by hi-reeve** [AppFlowy-IO/AppFlowy#4584]
### Bug Description

the data are not synced on macos and ios after sometimes, at first it was syncing good but after i turn off my mac and start to write on ios, it lost the ability to sync.

### How to Reproduce

1. login using github
2. turn off macos
3. start writing on ios
4. see if it's syncing on macos

### Expected Behavior

always syncing whenever update happen on both devices

### Operating System

macos,ios

### AppFlowy Version(s)

macos 0.4.5 ios 0.4.4 (2)

### Screenshots

macos
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45350572/fbe8b57c-09a7-41a1-b49d-4fd3afd6d7fc)

ios
![IMG_49B5C0156D93-1](https://github.com/AppFlowy-IO/AppFlowy/assets/45350572/8206095c-dbd0-481a-9ec0-bc15dd919b5a)

**Comment by LucasXu0** [comment]
@hi-reeve You can upgrade to the latest version. We recently fixed some verification token issues.

**Comment by hi-reeve** [comment]
> @hi-reeve You can upgrade to the latest version. We recently fixed some verification token issues.

both my apps are already on the latest version, but still have not synced

**Comment by skiunke** [comment]
I have the same problem, but it initially started. I started on a Windows machine and then wanted to access it on macOS, but only saw the blank file.

**Comment by appflowy** [comment]
> > @hi-reeve You can upgrade to the latest version. We recently fixed some verification token issues.
> 
> both my apps are already on the latest version, but still have not synced

The latest version of  iOS is `0.5.5` and  macOS is `0.5.4`

**Comment by appflowy** [comment]
> I have the same problem, but it initially started. I started on a Windows machine and then wanted to access it on macOS, but only saw the blank file.

Hello @skiunke. Please ensure that you are using the latest version of the application. Could you try closing the application on your macOS device, and then reopening it? Let us know if this resolves the issue.

**Comment by griff-rees** [comment]
May relate to #4848. I think I've had a similar issue, and in the past reopening the `macOS` app did help but an attempted series of restarts yesterday led to me having similar experience to #5188 (though that ticket was originally created for an `android` instance, not sure if that's related enough).
