### ISSUE TITLE
[Bug] Mobile: Supabase同步，手机端输入网址和密钥后不能点击重启

### ISSUE THREAD

**Issue by zoneXShy** [AppFlowy-IO/AppFlowy#4593]
### Bug Description

Supabase同步，手机端输入网址和密钥后不能点击重启；
通过清除缓存等方法均无效。
如果不能实现实时同步，建议增加同步按钮，手动同步。

### How to Reproduce

安卓版AppFlowy使用Supabase同步数据，

### Expected Behavior

输入URL和密钥后仍然不能点击重启。

### Operating System

android

### AppFlowy Version(s)

0.4.3

**Comment by annieappflowy** [comment]
Please try out [this](https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy) self-hosting solution
We'll stop maintaining the Supabase solution soon.
