### ISSUE TITLE
[Bug] Workspace failed to load

### ISSUE THREAD

**Issue by knono** [AppFlowy-IO/AppFlowy#4609]
### Bug Description

It is not possible to sync contents. On Linux and iPhone are working. On Mac is not working.

### How to Reproduce

timeout while authenticate using GitHub account

### Expected Behavior

timeout while authenticate using GitHub account

### Operating System

macos

### AppFlowy Version(s)

0.4.6

### Screenshots

<img width="1257" alt="Screenshot 2024-02-05 at 16 51 12" src="https://github.com/AppFlowy-IO/AppFlowy/assets/8377275/2a7e32de-2152-4232-b7f3-ff82142908e5">

**Comment by appflowy** [comment]
Hi @knono. Thank you for reporting this.  Could you please share your email with me? This will allow me to review the server logs related to your account. For privacy, feel free to DM me on Discord

**Comment by knono** [comment]
Finally, It is working again. It solved deleting all contents on /Users/$user/Library/Application Support/com.appflowy.appflowy.flutter, once installed again via brew. It synced straightly, perfectly. 

Thanks in advance.

**Comment by knono** [comment]
It is working.
