### ISSUE TITLE
[FR] A simple basic feature - Anyone can add a bulleted list, a checkbox, toggle list inside of a table

### ISSUE THREAD

**Issue by tasnuva1** [AppFlowy-IO/AppFlowy#4616]
### Description

Inside a table, some basic functionality:
- Able to add a bulleted list.
- Able to add a checklist.
- Able to add toggle list.

![pic-selected-240206-2147-33](https://github.com/AppFlowy-IO/AppFlowy/assets/62549329/d5a1d4d8-5bb9-45f4-bdd6-a66ea3edb7f1)

### Impact

For all types of users. It's a basic feature and an important one.

#### Current Behaviour
- Inside a new cell, after adding a text then press `shift+enter`. At that moment, adding a bulleted list, or adding a checkbox functionality was gone.  
- And there was never an option to add a toggle list inside a table.

#### Wired Behaviour
- Inside a new cell, after adding a bulleted list, or a checkbox, `shift+enter` functionality was gone.

**Comment by annieappflowy** [comment]
Supported in the upcoming release (v0.7.8)

**Comment by tasnuva1** [comment]
> Supported in the upcoming release (v0.7.8)

Hip Hip Hurray, Can I work on this issue? 
And if say yes, at any point in time I'll let you know, if I am unable to do so.
