### ISSUE TITLE
[FR] Date

### ISSUE THREAD

**Issue by AbdalrhmanShaban** [AppFlowy-IO/AppFlowy#4617]
### Description

Add a field to type the date using the keyboard in the Date panel,
This will make choosing the date easier.
![Annotation 2024-02-06 175839](https://github.com/AppFlowy-IO/AppFlowy/assets/77964363/2b58d295-e4dc-4b19-85c6-76483390f8f1)

### Impact

All users can benefit

**Comment by theEpicjosh** [comment]
I would certainly benefit with this!
