### ISSUE TITLE
[Bug] Mobile: Duplicating sheets and not syncing correctly since 0.4.6(1)

### ISSUE THREAD

**Issue by MariMightyMedia** [AppFlowy-IO/AppFlowy#4618]
### Bug Description

Since the newest version (0.4.6) AppFlowy is duplicating every sheet depending on how many devices I have connected to the Beta Cloud. One sheet even was deleted completely with all subpages…

### How to Reproduce

macOS 
iPhone
iPad
Connected via AppFlowy Beta Cloud Account 
With the AppFlowy Self Hosted Parameter selected but the default domain of the cloud
`„https://beta.appflowy.cloud“ `
until 0.4.5 everything worked perfectly fine but from upgrading today everything went crazy

### Expected Behavior

Normal syncing of sheets as before 

### Operating System

ios / macOS / iPadOS 

### AppFlowy Version(s)

0.4.6

### Screenshots

See iOS Beta Feedback via TestFlight

**Comment by annieappflowy** [comment]
Sorry for the inconvenience this may have caused you.
Could you please share your log files?
You can export it on Mobile by going to Settings --> Report an issue --> Export log files
On desktop, go to Settings --> Files --> Open Current Data Directory, and then locate the log file with suffix as 02-06
You can share here, email them to support@appflowy.io, or DM me on Discord.
Thank you for the help!

**Comment by MariMightyMedia** [comment]
Hey, I've just sent an email

**Comment by annieappflowy** [comment]
Are you still having the issue with the latest release?
