### ISSUE TITLE
[Bug] How to perform ctrl + enter operation on mobile terminal, in some blocks

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#4623]
### Bug Description

How to perform ctrl + enter operation on mobile terminal, in some blocks

### How to Reproduce

For example callout, quote

### Expected Behavior

Can perform corresponding operations just like the desktop version

### Operating System

mobile

### AppFlowy Version(s)

main

**Comment by annieappflowy** [comment]
Press Enter to go to the next line within the same block, supporting Code, Quote, and Callout.
Tap outside the block to leave 
Let us know if you have any questions @q200892907
