### ISSUE TITLE
[Bug] Cannot Open Workspace On Different Computer

### ISSUE THREAD

**Issue by NPaes12** [AppFlowy-IO/AppFlowy#4634]
### Bug Description

I absolutely love AppFlowy but am struggling to have it work seamlessly between two computers (work - PC, and home - Laptop). Due to the nature of my work we cannot store data on cloud services and the data must be self hosted. In order to use AppFlowy across both my devices I thought I could just use SVN for the data folder. However, while my work computer works just fine, when I try to open the exact same folder, with the exact same AppFlowy version, it fails to load the workspace.

I should mention that I started the workspace with 0.4.1 and later upgraded to 0.4.6

### How to Reproduce

Start AppFlowy on one computer and have the data folder in your documents. Commit this folder to SVN and then try to open it from another computer with the same AppFlowy version. 

### Expected Behavior

'Something went wrong, failed to load the workspace. Try to close any open instance of AppFlowy and try again'

### Operating System

Windows 10 Enterprise

### AppFlowy Version(s)

0.4.6

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/23161981/7d9b352c-2a0f-4b2f-b3fb-cf6206c47a93)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/23161981/14d7a41f-26e6-4df8-afd5-53d094e14f2a)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/23161981/d6a2bdf8-f7c6-44f5-9bb1-08bf2026a27c)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/23161981/f53a3f59-12a0-4fa6-b9e4-1c3b72c29ab6)

### Additional Context

I also noticed that when upgrading from 0.4.1 to 0.4.6 a new folder was automatically created. You will see it in the pictures 
'AppFlowyDataDoNotRename_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk'

**Comment by annieappflowy** [comment]
@NPaes12 , please try out our self-hosting [solution](https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy)
