### ISSUE TITLE
[Bug] Seems all my data is lost after update to v.0.4.7

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#4645]
### Bug Description

I'd just downloaded and unpacked 0.4.7 ZIP-file, started `AppFlowy.exe` and got... empty start screen with suggestion to login, although I have local account. Then I decided that it's weird error and press `Continue with anonymous account`. But got empty data sidebar. Tried to switch some data folders, but nothing again!

I have only 1 AppFlowy instance on my PC.

Attached yesterday log-file (v.0.4.5) and today (with update)
[log_2024-02-10.txt](https://github.com/AppFlowy-IO/AppFlowy/files/14233641/log_2024-02-10.txt)
[log_2024-02-11.txt](https://github.com/AppFlowy-IO/AppFlowy/files/14233642/log_2024-02-11.txt)

### How to Reproduce

See above.

### Expected Behavior

All was OK before update

### Operating System

Win 8.1 x64

### AppFlowy Version(s)

0.4.7 (x64-86 ZIP-version from Github)

### Additional Context

IDK what to do and how restore my data. I don't believe it's really gone.

If there is essential bug, publish update v.0.4.8.1, no v.0.4.9. :)

**Comment by annieappflowy** [comment]
If you downgrade the app to v0.4.6, can you open your existing data folder?

**Comment by Twilightssuperb** [comment]
@annieappflowy, no. ☹ V.0.4.6 shows empty sidebar again. IDK what was happened... I see some huge DB-files at AppFlowy data folder, so it looks my data isn't erased. 🤷‍♂️

**Comment by Twilightssuperb** [comment]
Also UI language unexplainably switched to Russian (OS settings) from English.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7080928/b5148a86-5b88-44e3-b233-88a1037f9711)

**Comment by appflowy** [comment]
Hey @Twilightssuperb, I've reviewed the logs and couldn't replicate the error you encountered. However, I noticed the errors from logs file, so I just want to make sure these things

1. Have you launched multiple instances of AppFlowy simultaneously?
2. Are you using AppFlowy's cloud services, or just local?

Your data is in your local disk. It can be restored from disk. Please DM me on Discord if you need help.

**Comment by Twilightssuperb** [comment]
> Have you launched multiple instances of AppFlowy simultaneously?

No, I marked that I have only 1 AppFlowy instance.

> Are you using AppFlowy's cloud services, or just local?

Just local, but data is stored at OneDrive folder.

> I've temporarily removed version 0.4.7

Oh, I just noticed more font size settings for text (new feature since 0.4.6), it gladded me so much.
___
Could you tell me, which data directory is correct — root `C:\...\OneDrive\AppFlowy` or some inner directory, inside `\AppFlowy\...`? I'm confused, sorry.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7080928/3d73ee81-10b4-4ae1-80b5-7b951aab74e2)
I can attach here more logs.

**Comment by singhayushh** [comment]
just curious, does this issue have to do with the directory name?

**Comment by appflowy** [comment]
@Twilightssuperb From the logs, I can tell your folder is `appflowy_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk` . But in order to use it. it requires to modify the cache.db file. You can send the cache.db file to me via discord. I can update the record inside the db(The cache.db doesn't contain any private data.).

**Comment by appflowy** [comment]
> just curious, does this issue have to do with the directory name?

Yes, each directory corresponds to a different user's data.

**Comment by Twilightssuperb** [comment]
@appflowy, you can find cache.db file here https://dropmefiles.com/suu3D Mention me when you'll download it, I remove this comment.

**Comment by appflowy** [comment]
@Twilightssuperb  I've opened the link but I can't download the file.

**Comment by Twilightssuperb** [comment]
@appflowy, UPD link https://dropmefiles.com/k0CEm

**Comment by appflowy** [comment]
I've created a guide on how to restore local user data, which you can find [here](https://docs.appflowy.io/docs/appflowy/product/data-storage#restore-specific-local-user-data-manually), @Twilightssuperb. If you need further assistance, please don't hesitate to contact me. For immediate responses, feel free to send a direct message to me on Discord.

**Comment by appflowy** [comment]
@Twilightssuperb For a quick try, download version 0.4.8, open it, and you should see the `continuous anonymous session` button. After clicking the button, it should bring you to the original data folder.

If it doesn't work. I've created a guide on how to restore local user data, which you can find [here](https://docs.appflowy.io/docs/appflowy/product/data-storage#restore-specific-local-user-data-manually), @Twilightssuperb. If you need further assistance, please don't hesitate to contact me. For immediate responses, feel free to send a direct message to me on Discord.

**Comment by Twilightssuperb** [comment]
@appflowy, thx for guide. I open `flowy-database.db` and see... empty (!) user workspace table, so IDK what to add in cache.db
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7080928/d740eadb-32a8-42ff-9091-bddbe3193c8c)
Also I backed up my data, then decided to delete all AppFlowy files, so I don't have almost none old logs. 😅 Just three files. I know my` user id` & `workspace id` but no `user workspace`.

Well, you we can talk on Discord, yes. How to chat your there?

**Comment by Twilightssuperb** [comment]
Oh, I've just imported my data from unpacked zip-file, I didn't change any DB-file. Finally I see my notes list at sidebar Seems my problem is solved.
