### ISSUE TITLE
[Bug] Font tooltip is selectable

### ISSUE THREAD

**Issue by PhilJbt** [AppFlowy-IO/AppFlowy#4646]
### Bug Description

The tooltip displayed when hovering an item during the font selection is selectable.
It catches the left-click and prevents scrolling.

### How to Reproduce

1. Go to **Settings → Appearance → Font Family**
2. Click on the dropdown font family menu
3. Hover any item of the list to show the tooltip

### Expected Behavior

Any mouse behavior should not trigger the tooltip.
Also, its usefulness can be questioned.

### Operating System

Windows 10.0.19045 Build 19045

### AppFlowy Version(s)

0.4.7

### Screenshots

[font_label.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/22506952/2fecfb82-a050-41d7-bd8c-ec29ca13edb7)

**Comment by annieappflowy** [comment]
Fixed
