### ISSUE TITLE
[FR] Ability to search in doc list

### ISSUE THREAD

**Issue by JiBe-DE** [AppFlowy-IO/AppFlowy#4648]
### Description

As number of documents created in AppFlowy grows continuously, it would like really helpful to being able to search for a document either from a CTRL+F just like in the document or like Notion with ⌘+K. 

### Impact

- Decrease time to find a document
- avoid scrolling or opening every folder
- quick access to any info in a document (even if the document is not displayed)

**Comment by annieappflowy** [comment]
#2232
