### ISSUE TITLE
[Bug] Can not paste directly from clipboard in Numberd list.

### ISSUE THREAD

**Issue by nikunjkumarnakum** [AppFlowy-IO/AppFlowy#4649]
### Bug Description

As we create a numbered list copied text can not be pasted directly in the list you need to write a single character and then paste the text. If we paste directly the numbered list terminates.

### How to Reproduce

1. Create a numbered list.
2. Copy some text.
3. Paste directly or using shortcut keys.

### Expected Behavior

The numbered list number will be terminated.

### Operating System

Windoews 11

### AppFlowy Version(s)

0.4.3

### Screenshots

![Untitledvideo-MadewithClipchamp-ezgif com-video-to-gif-converter](https://github.com/AppFlowy-IO/AppFlowy/assets/40589688/0ce822b7-3a30-444f-a45d-584e2e90a1d6)

**Comment by emmggi** [comment]
I think this is because you copied a bigger text with formatting that got treated as a heading. You can't have a heading as a list. Try pasting it without formatting, ie CTRL+SHIFT+V.

I have a related issue: https://github.com/AppFlowy-IO/AppFlowy/issues/4492

**Comment by nikunjkumarnakum** [comment]
No this doesn't help either.

**Comment by Aditya-Mi** [comment]
I have tried using CTRL+SHIFT+V and it works fine. So i guess what [emmggi](https://github.com/emmggi) has said is correct it treats it as a heading.

**Comment by q200892907** [comment]
#4906
