### ISSUE TITLE
discuss investment with hedgehog.vc (part of posthog)

### ISSUE THREAD

**Issue by jamesefhawkins** [AppFlowy-IO/AppFlowy#465]
hey team! i [saw one of my friends invested](https://twitter.com/annieanqi/status/1519305576026886147) and i'm really impressed at your progress

our team runs [PostHog](https://github.com/posthog/posthog) (popular open source platform, 10k customers) - we recently [raised $2M to invest in $100K cheques](https://github.com/PostHog/hedgehog.vc/) as part of increasing the number of successful products in the world. i'm one of the two founders. we're entirely focussed on open source especially people that build in public. we'd love to share what we're learning with you in more detail (and to bring you together with other projects), to help everyone build a better product

Would you be up for [talking to us](https://github.com/PostHog/hedgehog.vc/issues/new?assignees=&labels=pitch&template=pitch.md&title=%5BPITCH%5D)? no need to answer all the qs if you're unsure.

**Comment by jamesefhawkins** [comment]
(thought it'd be fun to raise this as an issue, hope that's ok)

**Comment by annieappflowy** [comment]
> (thought it'd be fun to raise this as an issue, hope that's ok)

Hi @jamesefhawkins , thanks a lot for reaching out. I love the transparency PostHog is creating, and I have learnt a lot from your handbook. It's a great resource for open-source founders. I'd love to connect! I can be reached at annie@appflowy.io

**Comment by jamesefhawkins** [comment]
Awesome, email en route :)
