### ISSUE TITLE
[Bug] initial sign-in using Google account doesn't work

### ISSUE THREAD

**Issue by micklat** [AppFlowy-IO/AppFlowy#4657]
### Bug Description

The login process via Google gets stuck after feeding credentials and pressing "Continue".

### How to Reproduce

1. open appflowy (using AppImage) for the first time
2. press "Log in with Google"
3. a browser opens, I feed my credentials
4. I get a page saying "Sign in to AppFlowy cloud", with the text:
`
By continuing, Google will share your name, email address, language preference and profile picture with AppFlowy Cloud. See AppFlowy Cloud’s [privacy policy](https://appflowy.io/privacy) and [Terms of Service](https://www.appflowy.io/terms).
`
and the buttons "Cancel" and "Continue".
5. I press "Continue"
6. the click is registered, and the status bar briefly shows some activity. Yet nothing happens.
7. The AppFlowy login window is still animating, showing that the login process is in progress, but no progress is made.

### Expected Behavior

expected login to complete and the app to start working

### Operating System

Linux, 6.6.10-1-MANJARO

### AppFlowy Version(s)

0.4.8

### Screenshots

![appflowy_stuck_in_login](https://github.com/AppFlowy-IO/AppFlowy/assets/3190517/afc36e32-2ddd-4b35-8706-a4aae49b917f)
![I did press continue](https://github.com/AppFlowy-IO/AppFlowy/assets/3190517/5ee26d4d-5af9-40b4-95aa-dc34b115db52)

**Comment by micklat** [comment]
Tried to log in with github, similar problem (different dialogs but identifying doesn't get me in)

**Comment by poldueta** [comment]
After updating to v0.4.8 faced with the same issue - app log out after each restart and then can't log in. Similar behaviour both on mobile and desktop apps. Exactly as were mentioned: 

> The AppFlowy login window is still animating, showing that the login process is in progress, but no progress is made.

**Comment by 10nayan** [comment]
I have faced the same issue, it wasn't working for GitHub and Discord also.

**Comment by poldueta** [comment]
Yes, looks like it fixed - after upgrading to 0.4.9 there is no such problem.

**Comment by justkelvin** [comment]
@micklat  This is what I added and liked to the app location. The mimetype helps recognize the app. Now the app works fine.

`cat /usr/share/applications/appflowy.desktop`

[Desktop Entry]
Name=AppFlowy
Icon=app_flowy.svg
Exec=/home/justkelvin/AppFlowy/AppFlowy
Terminal=false
Type=Application
MimeType=x-scheme-handler/appflowy-flutter;

**Comment by cenunix** [comment]
@justkelvin  what xdg-desktop portal are you using out of curiosity ? I haven't been able to sign in on a number of different browsers even after modifying the .desktop file and adding the association to my mimeapps.list file

**Comment by SolarDesalination** [comment]
I'm still having this issue with version 0.56. Linux Mint. Is there a preferred browser to use?

**Comment by speed2exe** [comment]
@SolarDesalination have you tried installing using flatpak instead? https://flathub.org/apps/io.appflowy.AppFlowy

**Comment by SolarDesalination** [comment]
Flathub login works thanks. Appimage doesn't.

**Comment by EnriqueRiosUniversidad** [comment]
0.5.9, the log in is still not workin
