### ISSUE TITLE
[Bug] Workspace failed to load

### ISSUE THREAD

**Issue by ezzobirbezziou** [AppFlowy-IO/AppFlowy#4663]
### Bug Description

.

### How to Reproduce

.

### Expected Behavior

.

### Operating System

linux

### AppFlowy Version(s)

0.4.8

**Comment by annieappflowy** [comment]
Are you still facing the same issue with v0.4.9?

**Comment by ezzobirbezziou** [comment]
No, thank you so much
You do great work ♥️
