### ISSUE TITLE
.

### ISSUE THREAD

**Issue by realaminesl** [AppFlowy-IO/AppFlowy#4670]
### Bug Description

Sign out after closing the apk

### How to Reproduce

remember my account 

### Expected Behavior

I expected to not need to enter an account when I logged in

### Operating System

android 14

### AppFlowy Version(s)

0.4.8

**Comment by annieappflowy** [comment]
@realaminesl , are you still facing the same issue with 0.4.9?

**Comment by annieappflowy** [comment]
Should be fixed already. Please re-open if you still have the same issue.
