### ISSUE TITLE
[Bug] Redirecting to Sign In page again and again even after successful authentication on MacOS desktop app

### ISSUE THREAD

**Issue by 10nayan** [AppFlowy-IO/AppFlowy#4671]
### Bug Description

When I try to authenticate after downloading the app or try to Sign In visiting Setting > User > Sign In with any of three options Google, Github or Discard it redirects to their respective auth providers sign in page. But after successfull sign in instead of redirecting to the app's home page it redirects me to the app sign in page again. I tried multiple times to sign with Google, Github or Discord but every time it fails to authenticate.

### How to Reproduce

Sign In using any of three auth provider Google, Github or Discord 

### Expected Behavior

The app should redirects me to my home page after successful signing or at least thorw error in case of invalid credentials. 

### Operating System

macOS Sonoma 14.3.1 (23D60)

### AppFlowy Version(s)

Appflowy 0.4.8

### Screenshots

<img width="746" alt="Screenshot 2024-02-17 at 10 36 20 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/44505856/450d3965-6661-46e8-8bb5-cccbd01874cd">

**Comment by mediacvg** [comment]
Yes, I have the same problem. Regardless of whether I’m using the Mac or iOS version and no matter which of the three login methods I use, I get sent back to the login page after authorization. The only way to solve this problem is to close the app and re-login and authorize again. Essentially, I need to authorize twice.”

**Comment by appflowy** [comment]
@10nayan @mediacvg Thank you for reporting this. I've fixed in [0.4.9](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.4.9)

**Comment by 10nayan** [comment]
Thank you @appflowy For responding it quickly, new version working fine
