### ISSUE TITLE
Still not possible to add sections?

### ISSUE THREAD

**Issue by fschlegelone** [AppFlowy-IO/AppFlowy#4673]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/118682177/9765b6fb-9e7f-4e2e-afa0-525c5abf1fac)

I brought this feature up 6 months ago and its still not possible to add sections to group your pages..
Looks like a big benefit for small effort to me.
Or is there a reason why you dont wanna implement it?

**Comment by emmggi** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/3974

**Comment by annieappflowy** [comment]
@fschlegelone , I'd like to understand your goals of creating multiple sections. Could you please elaborate on what you're trying to achieve by creating sections and how you can benefit from this feature? It would be very helpful if you can compare using parent pages with nested subpages to organize vs creating different sections while having the ability to create nested pages.

**Comment by annieappflowy** [comment]
#3974 #3844
