### ISSUE TITLE
[Bug] Mobile: Login page (and likely the app) not working in portrait mode

### ISSUE THREAD

**Issue by NightClawZ** [AppFlowy-IO/AppFlowy#4674]
### Bug Description

Hello,

Using the app on the Google Pixel 7 Pro. 

1. **The app when in portrait mode is stuck on login options, only showing AppFlowy logo no matter how long I wait :** 
![Screenshot_20240218-124957](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/00afa6d5-4b44-42fb-9366-79106f59d940)

2. **Only when I switch to landscape should I see some login options :** 
![Screenshot_20240218-125004](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/805e67df-93b2-4aca-a37c-b4fedd0b191d)

3. **After logging in, I see my data. I did not try if everything is functional but at least I am in my workspace :**
![Screenshot_20240217-224058](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/4e86b96e-117f-4732-b5dd-c954e26fee52)

4. **However when I switch back to portrait, the app does not make use of the full screen and the app is not really usable like this :** 
![Screenshot_20240217-224102](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/e029bdd1-ebdb-4231-861c-7a48296ca86f)

And somehow every time I have to log in again (using Google). 

### How to Reproduce

1. **The app when in portrait mode is stuck on login options, only showing AppFlowy logo no matter how long I wait :** 
![Screenshot_20240218-124957](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/00afa6d5-4b44-42fb-9366-79106f59d940)

2. **Only when I switch to landscape should I see some login options :** 
![Screenshot_20240218-125004](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/805e67df-93b2-4aca-a37c-b4fedd0b191d)

3. **After logging in, I see my data. I did not try if everything is functional but at least I am in my workspace :**
![Screenshot_20240217-224058](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/4e86b96e-117f-4732-b5dd-c954e26fee52)

4. **However when I switch back to portrait, the app does not make use of the full screen and the app is not really usable like this :** 
![Screenshot_20240217-224102](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/e029bdd1-ebdb-4231-861c-7a48296ca86f)

And somehow every time I have to log in again (using Google). 

### Expected Behavior

To be able to use the app as described in the Play Store and mainly make use of the full screen space even in portrait mode. 

### Operating System

Android 14

### AppFlowy Version(s)

0.4.8, 0.4.9

### Screenshots

![Screenshot_20240218-124957](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/00afa6d5-4b44-42fb-9366-79106f59d940)
![Screenshot_20240218-125004](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/805e67df-93b2-4aca-a37c-b4fedd0b191d)
![Screenshot_20240217-224058](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/4e86b96e-117f-4732-b5dd-c954e26fee52)
![Screenshot_20240217-224102](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/e029bdd1-ebdb-4231-861c-7a48296ca86f)

**Comment by FFaranna** [comment]
I have exactly the same problem. It's basically not usable like this.

**Comment by FFaranna** [comment]
![Screenshot_20240220-163545](https://github.com/AppFlowy-IO/AppFlowy/assets/7949710/be8d5f7c-cdc9-4b4c-ae35-1cf20688f3b5)

**Comment by NightClawZ** [comment]
Here you are : 
![share_5293092258426651501](https://github.com/AppFlowy-IO/AppFlowy/assets/4301769/2b825280-6ce6-4836-bde0-ad3de08872c4)

**Comment by NightClawZ** [comment]
Hello @LucasXu0  
The version 0.5.0 fixed the issue for me. 
Same case for you @FFaranna  ?

**Comment by FFaranna** [comment]
Yes it did! Thanks for letting me know!
