### ISSUE TITLE
[Bug] Uploading Image

### ISSUE THREAD

**Issue by abc36222** [AppFlowy-IO/AppFlowy#4693]
### Bug Description

when I upload image to cloud, after I close the appflowy and open it again , I get HttpException: invalid status code 404 instead of showing me the image. 

### How to Reproduce

I don't know what is the problem.

### Expected Behavior

I expect when I upload an image I could see it in my document.

### Operating System

Windows 10

### AppFlowy Version(s)

0.4.6

### Screenshots

![error](https://github.com/AppFlowy-IO/AppFlowy/assets/4419322/8c33dda4-dc1f-4c9a-9345-b0cb2d8e7055)

**Comment by LucasXu0** [comment]
Now, the image will only be synced if it's successfully uploaded in version 0.5.0.
