### ISSUE TITLE
[Bug] Backend Dockerfile doesn't build

### ISSUE THREAD

**Issue by weex** [AppFlowy-IO/appflowy#47]
**Describe the bug**
The backend Dockerfile doesn't build

**To Reproduce**
1. Clone the repo.
2. `cd backend`
3. `docker build .`

**Expected behavior**
A docker image should be built.

**Log**
https://gist.github.com/weex/a472ddfc39e612d47f08f0cad361c876

**Additional context**
  Docker Engine 20.10.8

**Comment by annieappflowy** [comment]
Same topic: https://github.com/AppFlowy-IO/appflowy/issues/13
