### ISSUE TITLE
[Bug] Chinese text display issues

### ISSUE THREAD

**Issue by rsdyxjh1** [AppFlowy-IO/AppFlowy#4701]
### Bug Description

![1](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/829c1346-18d3-4bce-bd3e-01ec1643479b)

### How to Reproduce

Create a document---Enter Chinese：创建数据库 ----Close the appflowy---open the appflowy --You'll see：
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/c26980b4-3bc0-4cdd-bc55-de1de1a418aa)

### Expected Behavior

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/cf9e1e59-9118-403b-99e7-05ca5ed96d2e)

### Operating System

windows10

### AppFlowy Version(s)

AppFlowy-0.4.9

**Comment by annieappflowy** [comment]
This was fixed. Please feel free to reopen if you still have this issue.
