### ISSUE TITLE
[Bug] No preview available

### ISSUE THREAD

**Issue by rsdyxjh1** [AppFlowy-IO/AppFlowy#4703]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/e4e05fdd-c47e-4a01-9ba0-aed95cd7ba99)

### How to Reproduce

创建一个文档--只粘贴一个网址---No preview available ，问题是无法删除掉

### Expected Behavior

No preview available

### Operating System

windows10

### AppFlowy Version(s)

AppFlowy-0.4.9

**Comment by annieappflowy** [comment]
Fixed
<img width="895" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8d423af9-499c-4e71-83b5-e4fd4e85b1aa">
