### ISSUE TITLE
[Bug] Unable to paste a URL link into a document

### ISSUE THREAD

**Issue by jish** [AppFlowy-IO/AppFlowy#4708]
### Bug Description

When I attempt to paste a URL link into a document, I expect to see that link in the document

### How to Reproduce

Copy a link to your clipboard for example, `https://github.com`
Open a document in AppFlowy
Paste the link into the document

![Screenshot 2024-02-22 at 09 05 24](https://github.com/AppFlowy-IO/AppFlowy/assets/1817/192c8f6f-ffb9-4f9c-bb15-48a3433d80f0)

### Expected Behavior

When I paste a link into a document, I see the link

Here is a link: https://github.com

### Operating System

Mac OS

### AppFlowy Version(s)

0.4.9

### Screenshots

![Screenshot 2024-02-22 at 09 09 20](https://github.com/AppFlowy-IO/AppFlowy/assets/1817/53901a18-d345-42dd-a9c0-895ce5ef4aea)

**Comment by annieappflowy** [comment]
We'll work on the improvement.
The workaround solution at the moment is to use the url format 
<img width="762" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/679f68ff-bc8b-44c7-a072-30cbd38a4580">
