### ISSUE TITLE
[Bug] After changing theme several times, i can't continue change it, no options appear when i click the 'default' button.

### ISSUE THREAD

**Issue by giz9551** [AppFlowy-IO/AppFlowy#4712]
### Bug Description

After changing the theme several times, I can't continue changing it, no options appear when i click the 'default' button.

### How to Reproduce

I can upload themes but can't change it because of the motionless 'default' button. Even the app's themes can't be selected.

### Expected Behavior

please give me access to unlimited theme changing

### Operating System

Windows

### AppFlowy Version(s)

0.4.9

**Comment by LucasXu0** [comment]
Hi, @giz9551. Are there stable steps to reproduce? I can't reproduce it in version 0.4.9.

**Comment by annieappflowy** [comment]
Please reopen if the issue still persists
