### ISSUE TITLE
[Bug] Time Parser Fails to Correctly Parse 12-Hour Format

### ISSUE THREAD

**Issue by AnsahMohammad** [AppFlowy-IO/AppFlowy#4720]
### Bug Description

The time parser encounters issues when the user opts for the 12-hour format. The current implementation struggles to parse time input in the 'HH:mm a' format.

### How to Reproduce

1. Select the Time format as 12 Hour format (from user settings)
2. Enter the time in the time field "08:00 PM"
Then the time gets parsed as "08:00 AM"

### Expected Behavior

When given input "08:00 PM"
The parser should parse the input to "08:00 PM"

### Operating System

Ubuntu LTS 22.04

### AppFlowy Version(s)

0.4.9

### Screenshots

[Screencast from 24-02-24 12:22:26 AM IST.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/85027826/ca513458-6a29-4d59-b2d1-e8c48510f015)

### Additional Context

From the code, The twelve Hour format is not being recognized by the if condition
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/85027826/4a9a867d-378c-4029-ad01-e6824e83232a)

**Comment by maxweilun1989** [comment]
@richardshiue hi, do you work on this? I debug for a while and found the root cause of this may be the `timeFormat` variable passed in is not the same object of TimeFormatPB.TwelveHour. 
using 
```dart 
timeFormat.toString() == TimeFormatPB.TwelveHour.toString()
``` 
may fix the problem. But I'm not sure if it's the proper way we should do.
