### ISSUE TITLE
0.5.0 can't open my pages

### ISSUE THREAD

**Issue by dungeon-slave** [AppFlowy-IO/AppFlowy#4745]
![Screenshot_20240226-155110.png](https://github.com/AppFlowy-IO/AppFlowy/assets/70040363/2fd695b0-2dbc-4201-bf41-1ebf1404a0e5)

All i see after click on my page. Pixel 7a, Android 14

**Comment by LucasXu0** [comment]
Fixed in https://github.com/AppFlowy-IO/AppFlowy/pull/4747

**Comment by LucasXu0** [comment]
Updated: https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.5.0/AppFlowy-0.5.0-android-arm64-v8a.apk
