### ISSUE TITLE
[Bug] Version 0.5.0 Appflowy flashbacks

### ISSUE THREAD

**Issue by rsdyxjh1** [AppFlowy-IO/AppFlowy#4746]
### Bug Description

Upgraded the version and found that Appflowy was flashing back when I opened it, so I had to go back to the version again!

### How to Reproduce

Upgraded the version and found that Appflowy was flashing back when I opened it, so I had to go back to the version again!

### Expected Behavior

Upgraded the version and found that Appflowy was flashing back when I opened it, so I had to go back to the version again!

### Operating System

windows10

### AppFlowy Version(s)

AppFlowy-0.5.0

**Comment by LucasXu0** [comment]
@rsdyxjh1 Can you provide the crash log or the error screenshot?

**Comment by rsdyxjh1** [comment]
I just overwrote the install again and it didn't flash back
