### ISSUE TITLE
[Bug] The uploaded image is still being uploaded.

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#4748]
### Bug Description

When inserting a picture, I chose to upload the picture. After uploading, it has been in image uploading. I am using supabase.
![bug](https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/3ed2c4d1-baa4-4852-836e-6d3ef3feb7ac)

### How to Reproduce

Upload pictures normally. Cloud settings use supabase.

### Expected Behavior

Uploaded images can be displayed normally

### Operating System

mac

### AppFlowy Version(s)

0.5.0

**Comment by speed2exe** [comment]
@smartyhero supabase self-host image upload is not supported at the moment. you can consider switching to the AppFlowy-Cloud Self-Host instead. https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md

**Comment by smartyhero** [comment]
No, when I used it before, the image would be uploaded to the local, but now it is always uploading. I hope it will either still be uploaded to the local, or it will be directly displayed. This function is not supported when using supabase.

**Comment by annieappflowy** [comment]
Hi @smartyhero , please consider self-hosting with a cloud service provider by following [this guide]([url](https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy))
We'll stop maintaining the Supabase solution soon as it doesn't support real-time collaboration.
