### ISSUE TITLE
Will AppFlowy v.0.5.xxx and newer support Win 8.1?

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#4755]
### Description

I see notice at v.0.5.0 release details that it doesn't support Win 8.1 due to Flutter upgrade. So should I wait for newer versions, otherwise AppFlowy for 7/8.1 would stop at 0.4.9?

### Impact

Yep, these OS are outdated, but... It hurts a bit.

### Additional Context

I wanna ask it in Discussions. but seems that page is locked for new topics.

**Comment by LucasXu0** [comment]
Hi, @Twilightssuperb. The last version that supports Windows 7 and 8 is 0.4.9. As you know, we're using Flutter to build our frontend, and we have upgraded to the latest version (3.19.0) to access new features and bug fixes.

Here's the announcement from Flutter. 

> As Flutter evolves, we’re excited to focus on the latest technologies by ending support for Windows 7 and 8 with Dart 3.3 and Flutter 3.19 releases. This shift, in line with Microsoft’s strategy, allows us to enhance Flutter on modern operating systems. We appreciate the adjustments required from our developers and are committed to assisting you through this transition. This move paves the way for a more secure, efficient, and feature-rich development environment on supported versions of Windows. Thank you for your understanding and adaptability as we continue to innovate together in the Flutter ecosystem.

**Comment by Twilightssuperb** [comment]
You should edit note from "...are not yet supported" to "Win 7, 8.1 and iOS11 won't be supported further". 😢

**Comment by Twilightssuperb** [comment]
Well, I've just created 2nd instance specially for 0.5.0 (x86-64.zip) and launched it on Win 8.1. It works and looks that UI became a bit faster since 0.4.9... 🤓

**Comment by Twilightssuperb** [comment]
After I restarted my PC, this 2nd instance failed to load frontend. Yesterday it launched on Win 8.1, today — no. **It's just my own experience with obvious risks.** I'm not sure that it would be to ask for your help, but anyway I attach two logs for 0.5.0 weird behavior.
[log_2024-02-28.txt](https://github.com/AppFlowy-IO/AppFlowy/files/14446374/log_2024-02-28.txt)
[log_2024-02-29.txt](https://github.com/AppFlowy-IO/AppFlowy/files/14446376/log_2024-02-29.txt)

**Main AppFlowy instance (0.4.9) works fine.**

Also it's a bit inconvenient — I expected that 2nd instance won't connect to my main AppFlowy data folder (it' just unpacked ZIP-file!). I thought that I got new data folder for 2nd instance. But nope!

So AppFlowy needs complete portable version... #390
