### ISSUE TITLE
[Bug] Version 5.0.0 starts and flashes back

### ISSUE THREAD

**Issue by rsdyxjh1** [AppFlowy-IO/AppFlowy#4758]
### Bug Description

Version 5.0.0 starts and flashes back   ，Which file is the log so I can upload it
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/854a25ec-ad9e-49c8-92b9-ce5a93f6873f)

### How to Reproduce

Which file is the log so I can upload it

### Expected Behavior

thanks

### Operating System

windows10 pro

### AppFlowy Version(s)

AppFlowy-0.5.0

**Comment by LucasXu0** [comment]
@rsdyxjh1 I thought it would work after you reinstalled it?

Here's the other issue you submitted: https://github.com/AppFlowy-IO/AppFlowy/issues/4746

**Comment by rsdyxjh1** [comment]
@LucasXu0  I tried to overwrite the installation several times in the morning but flashed back, 
so I had to fall back to version 0.4.9，But just now, I upgraded version 5.0.0 and opened it again surprisingly well！！！

I started a Windows 10 system with a virtual machine and copied that the installation of version 5.0.0 is normal. 
It may be caused by a problem with my notebook operating system.

Thanks for your interest, looking forward to the next release
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/973ff63b-8801-4a80-9e45-81cb6f4b51f4)

**Comment by LucasXu0** [comment]
@rsdyxjh1 OK, then I will close this issue.

**Comment by rsdyxjh1** [comment]
@LucasXu0  Log of program flashbacks

START]","target":"flowy_user::user_manager::manager_user_awareness"}
{"msg":"🔥AppFlowy Configuration { app_version: \"0.5.0\", storage_path: \"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\io.appflowy\\\\AppFlowy\\\\data_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk\", application_path: \"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\io.appflowy\\\\AppFlowy\\\\data\", base_url: \"https://beta.appflowy.cloud\", ws_url: \"wss://beta.appflowy.cloud/ws\", gotrue_url: \"https://beta.appflowy.cloud/gotrue\" }","target":"flowy_core"}
{"msg":"💡System info: Some(\"Windows 10 Pro\")","target":"flowy_core"}
{"msg":"init user session: 296434774963130368:343a8e13-bca9-479a-909f-f36f8fa857dc@appflowy.io","target":"flowy_user::user_manager::manager"}
{"msg":"open collab db for user 296434774963130368 at path: \"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\io.appflowy\\\\AppFlowy\\\\data_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk/296434774963130368\\\\collab_db\"","target":"flowy_user::services::db"}
{"msg":"open collab db to validate data integration for user 296434774963130368","target":"flowy_user::services::db"}
{"msg":"Prepare user data migration","target":"flowy_user::user_manager::manager"}
{"msg":"[🟢 BACKUP_COLLAB_DB - START]","target":"flowy_user::services::db"}
{"msg":"[BACKUP_COLLAB_DB - EVENT] Current backup: 3","target":"flowy_user::services::db"}
{"msg":"[BACKUP_COLLAB_DB - END]","target":"flowy_user::services::db","elapsed_milliseconds":0}
{"msg":"[🟢 TRY_INITIAL_USER_AWARENESS - START]","target":"flowy_user::user_manager::manager_user_awareness"}

**Comment by rsdyxjh1** [comment]
C:\Users\Administrator\AppData\Roaming\io.appflowy\AppFlowy\

I changed the name of the storage path in the previous version, and opened version 5.0.0 and auto-generated the data and solved the flashback problem.

**Comment by rsdyxjh1** [comment]
{"msg":"backend_log","target":"dart_ffi"}
{"msg":"[Flutter]: Uncaught platform error","target":"dart_ffi"}
{"msg":"flowy_user::event_handler","target":"flowy_user::event_handler","error":"AppFlowyDataFolderImportError: Can't find the session cache in the appflowy data folder at path: O:\\部署文档\\2024-02-18 AppFlowy-cloud云笔记服务器搭建\\AppFlowy存储位置"}
{"msg":"backend_log","target":"dart_ffi"}
{"msg":"[Flutter]: code: AppFlowyDataFolderImportError\nmsg: Can't find the session cache in the appflowy data folder at path: O:\\部署文档\\2024-02-18 AppFlowy-cloud云笔记服务器搭建\\AppFlowy存储位置\n","target":"dart_ffi"}
{"msg":"backend_log","target":"dart_ffi"}
{"msg":"[Flutter]: Uncaught platform error","target":"dart_ffi"}
{"msg":"[🟢 REFRESH_USER_PROFILE - START]","target":"flowy_user::user_manager::manager"}
{"msg":"[REFRESH_USER_PROFILE - END]","target":"flowy_user::user_manager::manager","elapsed_milliseconds":0}
{"msg":"backend_log","target":"dart_ffi"}
{"msg":"[Flutter]: Uncaught platform error","target":"dart_ffi"}
{"msg":"[🟢 USER_DIR - START]","target":"flowy_user::user_manager::manager"}
{"msg":"[USER_DIR - END]","target":"flowy_user::user_manager::manager","elapsed_milliseconds":0}
{"msg":"backend_log","target":"dart_ffi"}
{"msg":"[Flutter]: Uncaught platform error","target":"dart_ffi"}
{"msg":"backend_log","target":"dart_ffi"}
{"msg":"[Flutter]: Uncaught platform error","target":"dart_ffi"}
{"msg":"backend_log","target":"dart_ffi"}

**Comment by rsdyxjh1** [comment]
@LucasXu0 
I used version 0.5.0 to import data and set up local storage with errors and flashbacks, reinstalling and modifying data didn't fix it, and I eventually rolled back to version 0.4.9 to use it properly!

**Comment by LucasXu0** [comment]
@rsdyxjh1 I'm creating a new Windows package (with added logging to address the crash issue). Would you mind installing it later?

**Comment by rsdyxjh1** [comment]
I just upgraded version 0.5.0 and it starts up fine, so as not to interfere with work, I'll use the version you gave me tomorrow morning, thanks!

**Comment by rsdyxjh1** [comment]
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/c773151d-a3ec-4a2f-bb54-d652dc5af37f)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/112694961/cce64c0d-d3f8-4a85-9c41-9f03903a51ae)

The flashback problem is caused by Configuration file and storage path，I changed the name of the file in it -bk，And cleared the data folder（C:\Users\Administrator\AppData\Roaming\io.appflowy\AppFlowy\）, then started, it's finally normal

**Comment by LucasXu0** [comment]
@rsdyxjh1 I've added more logs and wanted to know the exact crash information to fix it, in case future users encounter it. Could you share the logs from when it crashes if you have installed the version I posted in the comments?

**Comment by rsdyxjh1** [comment]
@LucasXu0 
https://github.com/rsdyxjh1/msjzkdy/blob/main/log.2024-03-01

**Comment by LucasXu0** [comment]
@rsdyxjh1 It seems there are no more crashes. I can't find the 'uncaught platform errors' in the logs.

**Comment by hekimolacagim** [comment]
@LucasXu0 I'm experiencing the same crash. 
Here is my log (from the updated application with added log capacities.):
[log.2024-03-01](https://github.com/AppFlowy-IO/AppFlowy/files/14464673/log.2024-03-01.txt)

**Comment by rsdyxjh1** [comment]
Importing data from an external folder can also cause a flashback when restarting.
