### ISSUE TITLE
[FR] search in all data & Create a sub document from rows like ( referenced Document )

### ISSUE THREAD

**Issue by AhmedSaif500500** [AppFlowy-IO/AppFlowy#4768]
### Description

1 : please add search in all data it's a necessary thing and core and main 
2 : please make an option  to create an new document in ( referenced Document ) to make it easy to create an sub document while i am writing in rows and it should be a sub document for the current document

### Impact

All people

### Additional Context

please make it faster as you can

**Comment by Xazin** [comment]
Can insert a new page in a document using the / menu! 🙏 

We have issues open for the 1st FR you described, we will track it in another issue.
