### ISSUE TITLE
[Bug] Windows open row as a page pop up window too large

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#478]
**Describe the bug**
Opening a row record as a page on Windows too large to block other stuff

**Expected behavior**
A pop-up window over the main editor is displayed. The user can click elsewhere to close the pop-up window

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v0.0.4-beta.3

**Comment by MikeWallaceDev** [comment]
Should have closed automatically with fix #485
