### ISSUE TITLE
[Bug] Desktop not loading

### ISSUE THREAD

**Issue by denmarkgit** [AppFlowy-IO/AppFlowy#4805]
### Bug Description

Windwos Desktop App not loading

### How to Reproduce

Restarting Application

### Expected Behavior

![lfZXOCtuoO](https://github.com/AppFlowy-IO/AppFlowy/assets/25674370/6ea8ef57-63d8-4839-b5f8-7dde76245d1f)

### Operating System

Windows 11

### AppFlowy Version(s)

0.50

### Additional Context

Windows events log
Faulting application name: AppFlowy.exe, version: 0.5.0.0, time stamp: 0x65dc513b
Faulting module name: flutter_windows.dll, version: 0.0.0.0, time stamp: 0x65cc028f
Exception code: 0xc0000409
Fault offset: 0x0000000000d25c29
Faulting process id: 0x0x54F0
Faulting application start time: 0x0x1DA6DBCF770C281
Faulting application path: C:\Program Files (x86)\AppFlowy\AppFlowy.exe
Faulting module path: C:\Program Files (x86)\AppFlowy\flutter_windows.dll
Report Id: be2f3011-1fdf-49f9-b621-5d500c87e671
Faulting package full name: 
Faulting package-relative application ID:

**Comment by LucasXu0** [comment]
closed as duplicated. https://github.com/AppFlowy-IO/AppFlowy/issues/4808
