### ISSUE TITLE
[FR] reduce the delay of holding to drag

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#483]
There is a delay to the column becoming draggable, which I assume is intentional to prevent accidental reordering of the grid. I think it might be useful to add a tooltip or something which lets users know that they have to hold to drag. I wonder if it might also be better to reduce the delay a bit. It seems to take about 1 second before the drag is possible, but perhaps this should only be 500ms.

**Comment by moksh-mahajan** [comment]
@annieappflowy How about instead of holding to drag we add a reorder icon at the extreme right of the column heading cell and drag directly using it? We can also show a tooltip (say "Drag to reorder") while hovering on it.

**Comment by richardshiue** [comment]
(related to #1043) Initially did not know of this issue, but this is now fixed in v0.0.5.3. Please feel free to close

**Comment by annieappflowy** [comment]
@moksh-mahajan , love the idea of showing a tooltip as a hint for users. Can you draw something roughly to demonstrate your idea? I'm not sure about how the reordering icon would work.

**Comment by annieappflowy** [comment]
Resolved
