### ISSUE TITLE
[FR] icons larger

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#484]
The only other issue I have noticed so far is that some of the icons seem really tiny. I don't have the best vision, and maybe it's a subjective thing, but for instance the double dot icon / menu button, the star icon next to the "getting started" folder, the trash icon and the drop down chevrons, they all seem really small and hard to make out.

**Comment by bburdette** [comment]
I'd like it if icons would be scalable to larger sizes, as well as the fonts.  The app isn't really usable for me since I have a high DPI monitor.

**Comment by annieappflowy** [comment]
We supported zooming in/out and revamped most of the icons
<img width="989" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/872ccfe6-1e9c-4b03-93fd-e97b327e2d96">
