### ISSUE TITLE
[FR] Option to not show notifications icon, when there isnt any notification

### ISSUE THREAD

**Issue by inson1** [AppFlowy-IO/AppFlowy#4847]
### Description

I dont use notification, so its just cluttering my screen

### Impact

Users, who dont use notifications or at least not often

### Additional Context

I think its better option than not showing it at all, because what if?

**Comment by emmggi** [comment]
Notifications have reminders. Also how much of a clutter is it to have a single additional button in a panel that can be hidden?

**Comment by inson1** [comment]
@emmggi I just meant option for this in settings, I dont see anything bad with that.

**Comment by ahsanfarooq210** [comment]
Hi there. I want to solve this issue. A little detail would be helpful

**Comment by inson1** [comment]
@ahsanfarooq210 I dont think you need to be assign, just try to create the PR
