### ISSUE TITLE
[FR] Create a document for the database’s title.

### ISSUE THREAD

**Issue by ker-j** [AppFlowy-IO/AppFlowy#4852]
### Description

I don't understand why the title of the database can't be a document, I really need this function

### Impact

I can record in the database title whether my poem is completed or not, and if not, I can continue writing.

### Additional Context

If the title of the database is not a document, it is no different from an ordinary table.

**Comment by annieappflowy** [comment]
#3619

**Comment by annieappflowy** [comment]
Supported

<img width="821" alt="image" src="https://github.com/user-attachments/assets/8541f201-4b79-45c4-8687-8335c74d27d5">
