### ISSUE TITLE
[Bug] An operational question entered

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#4853]
### Bug Description

First create the title through shortcut keys and then enter the shortcut keys for other styles.

### How to Reproduce

After entering #+space
, enter 1.+space
. What I want is the text of “1.” in title 1. Now it will automatically switch the format of the block for me

### Expected Behavior

Can format switching only take effect in plain text format?

### Operating System

all

### AppFlowy Version(s)

main

**Comment by annieappflowy** [comment]
#2801
