### ISSUE TITLE
[Bug] Appflowy installed via snap not opening

### ISSUE THREAD

**Issue by Chandan-CV** [AppFlowy-IO/AppFlowy#4862]
### Bug Description

I installed Appflowy on Ubuntu 22.04 LTS using snap. It was working until last week, but since then the app is not launching.

error I get on `snap run appflowy` :

`chandan@chandans-ideapad-5:~$ snap run appflowy`

`Gtk-Message: 13:23:07.385: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
/usr/share/libdrm/amdgpu.ids: No such file or directory
thread '<unnamed>' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-appender-0.2.3/src/rolling.rs:154:14:
initializing rolling file appender failed: InitError { context: "failed to create initial log file", source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)`

running it with sudo doesn't work either.

### How to Reproduce

install using snap... try running the app.

### Expected Behavior

App runs.

### Operating System

Ubuntu 22.04.2 LTS

### AppFlowy Version(s)

v0.5.0 rev29

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/e4ab07a4-f2a6-4ab6-83e8-1d962c1f0efd)

### Additional Context

Thank you for reading through the issue :)

**Comment by LucasXu0** [comment]
Hi, @Chandan-CV. A new version 0.5.1 has been released on Snap. Please feel free to let me know if the issue persists in the latest version.

**Comment by Chandan-CV** [comment]
I changed the channel to latest/edge on snap to get the v0.5.1

but the launcher still doesn't work...

**Comment by Chandan-CV** [comment]
![Screenshot from 2024-03-12 09-48-16](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/ac219ee5-90f4-4240-a614-02fc7e202472)
![Screenshot from 2024-03-12 09-47-35](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/581a3318-2c38-439a-91e2-81bcf6776e67)

**Comment by Chandan-CV** [comment]
@LucasXu0 launching it through the terminal `./AppFlowy` works as expected... only the launcher has this issue.

**Comment by LucasXu0** [comment]
Got it. So it failed when you executed sudo snap run appflowy, but you were able to run it through appflowy or ./AppFlowy, right?

**Comment by Chandan-CV** [comment]
yup :)

**Comment by Chandan-CV** [comment]
Here you go :)

![Screenshot from 2024-03-12 18-36-53](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/a10bc25e-c22f-4394-bd95-1273bf9291a3)

![Screenshot from 2024-03-12 18-37-03](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/dd9a61d0-cbed-49e3-aea5-1ca5b51a12e0)

**Comment by Chandan-CV** [comment]
@LucasXu0 I started working again :)

Thank you!

**Comment by LucasXu0** [comment]
@Chandan-CV Is the permission issue fixed?
