### ISSUE TITLE
[Bug]  Links does not work in Android App

### ISSUE THREAD

**Issue by enel96** [AppFlowy-IO/AppFlowy#4864]
### Bug Description

Im using v0.5.0 (2905003) in Android (Samsung Galaxy S20+5G) with the Last update and when I create a text and then add a link to it (selecting the text I want add the link, touching "Aa" icon and then in the link option) it does not work. Does means that when touching the underlined text with the link added, nothing happens. I expected an Internet browser should be opened and the url is shown. If I touch for long time or I'm in editing mode and touch over the text I can edit the link, bit I can't go to the link directly. 

### How to Reproduce

Add a link to a text. Then hide the keyboard and touch the text where you added the link

### Expected Behavior

Internet browser is opened showing the link page

### Operating System

Android device

### AppFlowy Version(s)

0.5.0

**Comment by LucasXu0** [comment]
Hi, @enel96. Did your URL come with an HTTP(S) scheme?

**Comment by enel96** [comment]
Yes, I also used the link  https://www.google.es/ to test

**Comment by LucasXu0** [comment]
@enel96 If the URL includes the http(s) scheme, you should be able to open the link in read-only mode (when the keyboard is closed). I have fixed the issue where links without the http(s) scheme failed to launch.

**Comment by enel96** [comment]
Hmm, interesting but I am not able to open the links even if they start by http(s) like the Google link above. Do you have a link that works I can test? I guess in the next app verson i could test the new updates?

Thaaaanks so much!!

**Comment by LucasXu0** [comment]
I tested the link you provided: https://www.google.es/. If you're still unable to open the link with the HTTPS scheme, then it might be another problem. Could you send me the log files? You can find them by going to the settings page and selecting 'Report an Issue'.

**Comment by LucasXu0** [comment]
Hi, @enel96. We have released version 0.5.1. You can try updating to it.

**Comment by enel96** [comment]
Hey! I cant see the update in playstore (tells me that i have the app already installed, not update button, Last update 26 feb. ) is there any way to look for updates inside the app?  Thanks!

**Comment by enel96** [comment]
Ok, today i could update the app and it seems the links are working fine! Many thanks!!!! 😊😊😊
