### ISSUE TITLE
[Bug] Workspace failed to load

### ISSUE THREAD

**Issue by korodarn** [AppFlowy-IO/AppFlowy#4869]
### Bug Description

Unable to load workspace

### How to Reproduce

I'm trying to load the same copy of AppFlowy instance in Linux and Windows.  Error loading occurred in Linux after successful load in Windows earlier, going to retry to see if this is happening there

### Expected Behavior

Hopefully I"ll be able to load it fine in Linux and Windows, since it'd be nice to keep a shared notebook between them 

### Operating System

linux

### AppFlowy Version(s)

0.5.0

**Comment by korodarn** [comment]
It just completely crashes in windows, doesn't even take me here to report it like the linux appimage did.

Removing folder contents doesn't cause a reset (I did zip them first in case). Uninstalling the app did not reset the settings to default (windows version).

I assume it must keep some config in appdata or registry, going to try resetting a bit more and see if I can get it fixed

**Comment by korodarn** [comment]
registry didn't seem to have anything. 
I forgot about this, and wonder if it's somehow connected, in windows the google login auth will not clear, so I can't sign into app. 

I think choosing other sign-in methods would not link back to the same thing, since there doesn't seem to be an option for login that connects these options.

**Comment by korodarn** [comment]
After deleting io.appflowy again it will load if I choose anonymous, unfortunately my original directory seems to be borked, if I point at it the app goes back to crashing :(

**Comment by annieappflowy** [comment]
Hi @korodarn , very sorry about the inconvenience the issue has caused you. It's a known bug that we fixed in the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.1) (v0.5.1). Please give it a try Have it pointed to your original directory and let us know if it doesn't work for you. We're happy to help you recover if by any chance your data folder is corrupted.

**Comment by korodarn** [comment]
I was able to figure out the recovery part thanks to the documentation on how to manipulate the sqlite databases and gained a better understanding of how the zip files work through some experimentation, so I consider this closed now. Thanks!
