### ISSUE TITLE
[Bug] Appflowy crashed when try to open it

### ISSUE THREAD

**Issue by FullNavDev** [AppFlowy-IO/AppFlowy#4876]
### Bug Description

Appflowy exits at startup.

No problems with the 0.4.9 version.

### How to Reproduce

Just try to open Appflowy.

### Expected Behavior

Open successfully

### Operating System

Windows

### AppFlowy Version(s)

0.5.0

### Screenshots

![Captura de pantalla 2024-03-11 102633](https://github.com/AppFlowy-IO/AppFlowy/assets/148588742/14f88e5c-f3bd-4d9a-8b6d-ef0d1a367e77)

**Comment by annieappflowy** [comment]
Could you please try the latest[ release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.1) (v0.5.1)?
Let us know if it doesn't work for you.

**Comment by FullNavDev** [comment]
Solved! Thanks!
