### ISSUE TITLE
[Bug] self-hosting AppFlowy，login with github account，error message: code: UserUnauthorized msg: sign in with oauth error -10003

### ISSUE THREAD

**Issue by qeuyee** [AppFlowy-IO/AppFlowy#4887]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/31116292/6a520c7c-da43-49a8-89ac-9c232231104d)

### How to Reproduce

login with github account

### Expected Behavior

login with github account

### Operating System

win11

### AppFlowy Version(s)

0.5.1

**Comment by zack2627** [comment]
@qeuyee Hi! Thanks for reporting. As we are unable to reproduce this. We want to get more information on how to reproduce this error.

- Does this happen with other OAuth providers (google/discord)
- Is there error logging information from the docker containers that was deployed?
