### ISSUE TITLE
[Bug] Cant Login using Sign in with google

### ISSUE THREAD

**Issue by Bloodraven21** [AppFlowy-IO/AppFlowy#4901]
### Bug Description

I installed appflowy using snap then i tried to login using sign in with google I cant login plus my company was thinking of using appflowy to write docs and maybe maintaining tickets and there is no user management for multiple people

### How to Reproduce

just fresh install snap thn try to log in 

### Expected Behavior

should be able to login

### Operating System

ubuntu 20.04

### AppFlowy Version(s)

latest from snap

**Comment by LucasXu0** [comment]
@Bloodraven21 You can try installing it via .deb or Flathub. I have submitted an issue to Snap because the D-Bus service always fails to launch. Additionally, the collaborative workspace is a work in progress.

**Comment by Bloodraven21** [comment]
Any timeline how soon we can see that update?? Looking forward to use it in the org

**Comment by annieappflowy** [comment]
@Bloodraven21 , in the upcoming release (v0.5.4) up to 10 collaborators. You can give it a try!

**Comment by justkelvin** [comment]
@Bloodraven21 This is what I added and liked to the app location. The mimetype helps recognize the app.

`cat /usr/share/applications/appflowy.desktop`

[Desktop Entry]
Name=AppFlowy
Icon=app_flowy.svg
Exec=/home/justkelvin/AppFlowy/AppFlowy
Terminal=false
Type=Application
MimeType=x-scheme-handler/appflowy-flutter;

**Comment by annieappflowy** [comment]
Team collaboration is live! Add members to your workspace to edit and collaborate on pages together.
@Bloodraven21 , feel free to reopen it if you still have issues signing in with Google.
