### ISSUE TITLE
[FR] When pasting text into an empty blcok with formatting, is it possible to not replace the block style?

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#4905]
### Description

When pasting text into an empty blcok with formatting, is it possible to not replace the block style?

For example, in an empty H1, pasting text will be replaced with text style. I want it to maintain the style of H1. The same is true for other formats, which is more in line with most people's operating habits.

### Impact

The empty block style will not change into the format I don’t want.

**Comment by q200892907** [comment]
The idea is that when pasting is in text format and is empty, the format is maintained and pasted. If it is formatted, the text is pasted.

**Comment by LucasXu0** [comment]
@q200892907 So, your expectation is to apply formatting only to pasted text when the block is a paragraph, not to headings, bulleted lists, etc.

**Comment by q200892907** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/4517301/3c64ded8-2cca-4fbb-8154-eacab916d0fc

Just like recording the screen 
 If you paste formatted text in a formatted block, only the text will be pasted 
 If you paste it in a standard text block, the original format will be maintained

@LucasXu0

**Comment by LucasXu0** [comment]
@q200892907 It's clear. I've merged your pull request.

**Comment by dandv** [comment]
> So, your expectation is to apply formatting only to pasted text when the block is a paragraph

The standard expectation when pasting unformatted text (Ctrl+Shift+V) is to preserve the existing formatting (i.e. apply it to the pasted text) and discard any rich text metadata from the clipboard.
