### ISSUE TITLE
[Bug] Enter Chinese and display it as Pinyin

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#4910]
### Bug Description

When I entered two Chinese characters into the form, switched to another page, and then came back, the original Chinese characters were displayed without pinyin.

The input method I use is Sogou
![bug-image-pinying](https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/f13c7010-791f-4781-986f-667854bf9b31)

### How to Reproduce

see Bug Description

### Expected Behavior

Display normal Chinese

### Operating System

mac

### AppFlowy Version(s)

0.5.2

**Comment by LucasXu0** [comment]
closed as completed. https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/178
