### ISSUE TITLE
[Bug] need to refresh the page to see the emoji after the configuration

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4912]
### Bug Description

as described in the title

### How to Reproduce

open up a card to set up an emoji
close up
open up again
the emoji is not shown

### Expected Behavior

shown as expected

### Operating System

macOS

### AppFlowy Version(s)

v0.5.2

**Comment by DevaanshPathak** [comment]
I think that this bug only occurs in the new version as it doesn't bother me in the old version.
