### ISSUE TITLE
[Bug] Dark Mode is not perfect

### ISSUE THREAD

**Issue by normalhh** [AppFlowy-IO/AppFlowy#492]
**Describe the bug**
Look at the screenshot
<img width="1151" alt="ScreenShot_2022-05-10_10-18-28" src="https://user-images.githubusercontent.com/5423840/167530314-630ca644-7b92-49b7-9a6d-f6ad93ebd899.png">

The backgroud of some highlighted words is so similar with foreground color, words can not be read in the dark mode.

**Comment by apomalyn** [comment]
Duplicate of #433.

**Comment by apomalyn** [comment]
Please @normalhh could you close this issue because it's a duplicate 😄 to avoid keeping it on the opened issues.
