### ISSUE TITLE
[Bug] Keyboard up/down arrows are not working in code block

### ISSUE THREAD

**Issue by unbreakabl3** [AppFlowy-IO/AppFlowy#4923]
### Bug Description

When creating a code block with some code inside, the up and down keyboard keys are not working. Only left/right is ok.

### How to Reproduce

Create a code block with a few lines and try to go up / down with a keyboard

### Expected Behavior

The selector will follow the keyboard's arrows

### Operating System

MacOS

### AppFlowy Version(s)

0.5.2

**Comment by inson1** [comment]
i'm on 0.5.1 and I can reproduce it

**Comment by emmggi** [comment]
Works on Linux v0.5.2.
