### ISSUE TITLE
[FR] Grid Select/Multiselect - color of the badge should be visible while editing property

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#493]
**Use case of the proposed feature**

As a user, I would like to see the colour of the badge when I'm editing it. Exactly like I see it when I assign an option to a cell (see screenshots).

**Current edition dialog**
<img width="474" alt="design - the badge color should appear like in 2" src="https://user-images.githubusercontent.com/22211097/167707883-5457ef56-6473-4f3a-97c9-d65b0cd2043e.png">

**Current assign option dialog**
<img width="302" alt="design 2" src="https://user-images.githubusercontent.com/22211097/167708076-9cfcb57f-d4cb-4b99-93a8-0d1e04e55f09.png">

We should see the same badges on the edition and assign dialogs.

**what types of users can benefit from using your proposed feature**
All users using the grid

**Comment by richardshiue** [comment]
This issue is no longer present in the latest version. Now, both menus use the same SelectOptionTag component that includes the colored background
