### ISSUE TITLE
[FR] Code Blocks

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4930]
### Discussed in https://github.com/AppFlowy-IO/AppFlowy/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **Drallas** December 30, 2022</sup>
Are Codeblocks on the Roadmap? 

The current way of displaying code is not appealing to me, and can't find a way to get normal code blocks. The way GitHub does this would be best.

### Appflowy 🤯
<img width="408" alt="Screenshot 2022-12-29 at 19 34 32" src="https://user-images.githubusercontent.com/24792888/209994910-0c6daf15-b9d9-4967-adc3-fa1b902b28ae.png">

### Marktext 🫤
<img width="668" alt="Screenshot 2022-12-29 at 19 34 40" src="https://user-images.githubusercontent.com/24792888/209994912-90657fe0-735e-4baa-8cbe-dbf1f0a902b9.png">

### GitHub 🤩
```python
print("Hello, world!")
for i in range(10):
    print(i)
```</div>

**Comment by emmggi** [comment]
I'd prefer Marktext because much easier to tell visually it's a code block.

**Comment by annieappflowy** [comment]
<img width="1016" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/32c410f8-ad31-4927-a935-18bd0b2dae52">
