### ISSUE TITLE
[Bug] Typing inside a code block breaks it.

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#4932]
### Bug Description

Create a code block with some text in it. Typing inside after it was created splits it.

### How to Reproduce

1. Create a code block either from highlighted text or manually using ticks.
2. Type inside the block.

### Expected Behavior

It should keep being a code block.

### Operating System

Linux

### AppFlowy Version(s)

0.5.2

### Additional Context

[Screencast from 2024-03-18 10-26-43.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/4e3392cc-dbb8-4b77-88c3-8636c5c8248f)

**Comment by inson1** [comment]
on Windows 10 and 0.5.0 it doesnt happen

**Comment by annieappflowy** [comment]
reproducible on v0.5.3 macOS

**Comment by annieappflowy** [comment]
Fixed in the upcoming release
