### ISSUE TITLE
 [FR] Being able to make a copied page a sub-page of the original

### ISSUE THREAD

**Issue by Wonderien** [AppFlowy-IO/AppFlowy#4933]
### Description

When I copy a page, I can't make it a sub-page of the original page by just dragging it over into it.

### Impact

When you created a page and made some good notes or sheet with data in it, but then your research grows. Now you want to copy it and make it a sub-page of the main page, which will turn into an umbrella page for all the sub-topics.

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/62dc1145-742e-44bb-9a7d-986b6af3cce1

Have you tried using drag-and-drop? I attached an example here

**Comment by Wonderien** [comment]
Great, works now! 
Don't think it did before.

**Comment by Wonderien** [comment]
I would now like to be able to drag-and-drop pages from the private to the general space. This was possible in yesterday's release, but now with the hierarchydrop-down menu of the 2 spaces, I can't drag notes from private space to the general space anymore, it seems.
