### ISSUE TITLE
[FR] Grid Select/Multiselect - always offer to add another option after creation of a new option.

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#494]
**1~3 main use cases of the proposed feature**
As a user, when I create an option in a select or multi-select column there is a high probability that I will create another one.
To avoid switching from the keyboard to the mouse only to click the 'Add option' button, the text field to create another option should appear after I created a new option.

![Current behaviour](https://user-images.githubusercontent.com/22211097/167709525-0961a0fd-a74d-4a05-b141-c79f4c2d33a1.gif)

**Comment by appflowy** [comment]
@apomalyn Thank you for reporting. The issue was solved and will be released in next release package.
