### ISSUE TITLE
[Bug] Images not showing after reopening AppFlowy

### ISSUE THREAD

**Issue by Bug-g0** [AppFlowy-IO/AppFlowy#4946]
### Bug Description

If I add an image everywhitn is fine but after closing and reopening I get "Exception: Invalid image data" and an empty rectangle
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/160112469/613e9464-9cd8-427a-b8dc-ad2aa32705fd)
("Impossibile caricare l'immagine" means Impossible to load the image )

### How to Reproduce

Close and reopen AppFlowy

### Expected Behavior

Images shoud open properly

### Operating System

Manjaro Linux

### AppFlowy Version(s)

0.5.2

**Comment by annieappflowy** [comment]
Could you go to Settings --> Files --> Clear Cache?
<img width="904" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/5fe5ddb7-5466-4829-a063-fd522153bfb7">
Let us know if it doesn't work for you

**Comment by Bug-g0** [comment]
I reopened it a day later and everything was fine and the same images showed correctly. Nothing changed and I didn't need to clear the cache. Honestly I have no idea what happened

**Comment by annieappflowy** [comment]
Let us know if it occurs again. Thank you for the report. Closing this for now.
