### ISSUE TITLE
[Bug] OpenAI writer does not work. Infinite loading screen

### ISSUE THREAD

**Issue by kmaximoff** [AppFlowy-IO/AppFlowy#4948]
### Bug Description

After adding an API, and trying to use OpenAI writer goes to infinite load mode. 

### How to Reproduce

1. Add OpenAI key
2. Try to use OpenAI writer

### Expected Behavior

Loading text

### Operating System

MacOS 14.1.1 (23B81)

### AppFlowy Version(s)

Latest

**Comment by AgentSanchez** [comment]
I'm experiencing the same issue. Windows 10 - 10.0.19045
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37169160/b6fa1b49-d02d-48d5-9703-e6139bb157df)
I am using the same API key I use in other applications without issues, so the key is not wrong.

**Comment by AgentSanchez** [comment]
Seems to be related to #4767
