### ISSUE TITLE
[Bug] Grid Select/Multiselect - Unable to add option after column creation

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#495]
**Describe the bug**

Just after the creation of a column, I can't add an option for the select and multi select properties.
To be able to create an option I must exit the edition dialog and then reopen it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a grid page
2. Click on '+ New column'
3. Select the 'Select' or 'Multiselect' property type.
4. Click on '+ Add an option'
5. Type a random string
6. Hit 'enter'
7. See the error 

**Expected behaviour**
The new option should be saved and visible.

**Screenshots**

![Screen Recording 2022-05-10 at 16 01 28](https://user-images.githubusercontent.com/22211097/167716259-dfe901ac-04d2-495f-a316-a858b52bed3c.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.3.1 (intel)
 - Version: 0.0.4.3.1

**Comment by MikeWallaceDev** [comment]
Should have closed automatically with fix #485
