### ISSUE TITLE
[Bug] Reoordering columns in a grid on the mobile platform isn't very user-friendly

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#4958]
### Bug Description

 The velocity isn't particularly fast since it follows the reorderable listview's default.

The issue occurs when the user long presses on a field header. Instead of staying stationary under the user's finger, it automatically starts reordering.

### How to Reproduce

1. Open a grid on mobile
2. Long press on a field header
3. Observe that the field immediately starts scrolling. 

### Expected Behavior

The header should only start scrolling after the user moves his finger towards either side.

### Operating System

iOS, Android

### AppFlowy Version(s)

0.5.3

**Comment by annieappflowy** [comment]
It's much better as feeling in control. Closing it for now
