### ISSUE TITLE
[Bug] Help menu icons don't load properly.

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#4965]
### Bug Description

Icons in the help menu never loaded properly for me.

### How to Reproduce

Not sure.

### Expected Behavior

Icons are loaded properly.

### Operating System

Linux

### AppFlowy Version(s)

0.5.2

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/0d09a23c-9115-4028-8cb5-7d0ff3686327)

### Additional Context

Installed using [package from AUR](https://aur.archlinux.org/packages/appflowy-bin).

**Comment by inson1** [comment]
on Windows 10 it works, 0.5.2 too

**Comment by emmggi** [comment]
@inson1 It may be a Linux bug. I don't recall ever having them load properly.

**Comment by LucasXu0** [comment]
@emmggi It's a font issue on the Linux platform. The emojis we're using may not be supported on some Linux platforms. We're planning to replace them with SVG icons.

**Comment by emmggi** [comment]
Fixed in v0.6.7.
