### ISSUE TITLE
The VS Code Go to the Run and Debug TAB is abnormal

### ISSUE THREAD

**Issue by Mrwu-gui** [AppFlowy-IO/AppFlowy#497]
Hello team,

I have a problem when I run with VS Code, and the screenshot is attached as follows
![image](https://user-images.githubusercontent.com/65527488/168199119-59c1f029-606a-4579-8e15-60d84c3c915e.png)

Hope to get your early solution, thank you

**Comment by zhengcan** [comment]
You should add `import 'package:collection/collection.dart';` to the header of file.

Some files need `import 'dart:collection';` as well.

**Comment by annieappflowy** [comment]
Hello @Mrwu-gui  is this resolved?
