### ISSUE TITLE
[Bug] After updating to 0.5.3 many pages are showing AppFlowy Error

### ISSUE THREAD

**Issue by plasticboy** [AppFlowy-IO/AppFlowy#4997]
### Bug Description

I updated to 0.5.3 using flathub and now when I open certain existing pages I get a couple different AppFlowy error messages. See screenshots.

### How to Reproduce

1. Upgrade to 0.5.3
2. Open several pages until you see error

### Expected Behavior

Pages display existing content

### Operating System

Ubuntu 22.04.4 LTS

### AppFlowy Version(s)

0.5.3

### Screenshots

![Screenshot from 2024-03-27 06-19-20](https://github.com/AppFlowy-IO/AppFlowy/assets/54499/cfd1f8b8-f2a9-49e2-b791-ce7385adfa2a)
![Screenshot from 2024-03-27 06-21-52](https://github.com/AppFlowy-IO/AppFlowy/assets/54499/cf4a0bb7-7902-4e20-8e84-2adb4fff02dc)

### Additional Context

Here's a bit of the log file that seems relevant:

`{"msg":"[🟢 GET_DOCUMENT - START]","target":"flowy_document::manager","doc_id":"214ed608-0013-4bf8-9819-bb24177e87aa"}
{"msg":"[GET_DOCUMENT - END]","target":"flowy_document::manager","doc_id":"214ed608-0013-4bf8-9819-bb24177e87aa","elapsed_milliseconds":0}
{"msg":"[🟢 REFRESH_USER_PROFILE - START]","target":"flowy_user::user_manager::manager"}
{"msg":"[REFRESH_USER_PROFILE - END]","target":"flowy_user::user_manager::manager","elapsed_milliseconds":0}
{"msg":"flowy_folder::event_handler","target":"flowy_folder::event_handler","error":"RecordNotFound: View:cbcac4eb-c8f0-499b-9320-bd3aa8056533 is in trash"}
{"msg":"[🟢 REFRESH_USER_PROFILE - START]","target":"flowy_user::user_manager::manager"}
{"msg":"[REFRESH_USER_PROFILE - END]","target":"flowy_user::user_manager::manager","elapsed_milliseconds":0}
{"msg":"flowy_database2::event_handler","target":"flowy_database2::event_handler","error":"RecordNotFound: Record not found"}
{"msg":"[🟢 GET_DOCUMENT - START]","target":"flowy_document::manager","doc_id":"214ed608-0013-4bf8-9819-bb24177e87aa"}
{"msg":"[GET_DOCUMENT - END]","target":"flowy_document::manager","doc_id":"214ed608-0013-4bf8-9819-bb24177e87aa","elapsed_milliseconds":0}
{"msg":"[🟢 GET_DOCUMENT - START]","target":"flowy_document::manager","doc_id":"aef2f7af-7925-450c-ba47-25610e91346c"}
{"msg":"[GET_DOCUMENT - EVENT] request_id: \"d0dce181f21cd061772bc4cd9f6e293e\"","target":"client_api::http","doc_id":"aef2f7af-7925-450c-ba47-25610e91346c"}
{"msg":"[GET_DOCUMENT - EVENT] flowy_document::manager","target":"flowy_document::manager","error":"InvalidParams: NoRequiredData","doc_id":"aef2f7af-7925-450c-ba47-25610e91346c"}
{"msg":"[GET_DOCUMENT - END]","target":"flowy_document::manager","elapsed_milliseconds":874,"doc_id":"aef2f7af-7925-450c-ba47-25610e91346c"}
{"msg":"flowy_document::event_handler","target":"flowy_document::event_handler","error":"InvalidParams: NoRequiredData"}
`

**Comment by LucasXu0** [comment]
Hi, @plasticboy. Did you use the local mode?

**Comment by plasticboy** [comment]
@LucasXu0 I may have started in local mode but I later signed in with my Google account and turned on Cloud Sync.

**Comment by LucasXu0** [comment]
@plasticboy Got it. Can you DM me your full log files on Discord (lucas_appflowy)?

**Comment by nullswordpgs** [comment]
I'm having the same problem in 0.5.8 but weirdly enough it only happens with my databases
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/144389519/9386b1fe-223c-410c-b2ea-afc4c15b53d1)

So for I looked into cache.db, the 2 flowy-database.db files present in the data folder, and 000004 files and I couldn't figure out by myself what is happening nor fix it myself.
Though I could confirm from the 000004 file that the data from the databases still there, maybe it just created assigned a new view id for the databases and now it doesn't find them even though they exist?
