### ISSUE TITLE
[FR] Please increased to 6 level headings & import markdown

### ISSUE THREAD

**Issue by Angel0726** [AppFlowy-IO/AppFlowy#501]
**1~3 main use cases of the proposed feature**
i have many mardown file, and want import it to appflowy. can you develop feature whice imports markdown files. What's more,
markdown has 6 level  headings， but appflowy only have 3 level headings. so i can not import markdown file to appflowy  **Lossless (complete)**。

**Comment by annieappflowy** [comment]
<img width="172" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/37a097aa-d4f6-48b3-85ce-78ca3beaa95f">
<img width="640" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/059c83f0-9add-4c4f-a2e2-14505b17bbf7">
