### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SWASTIKpy** [AppFlowy-IO/AppFlowy#5013]
### Bug Description

dunno opened it and it doesnt show anything data is working properly i checked it

### How to Reproduce

cant say i just openend it

### Expected Behavior

it could be a cloud integration problem or just a temporal bug maybe

### Operating System

ANDROID AND WIN10

### AppFlowy Version(s)

0.5.3

### Screenshots

![Screenshot (102)](https://github.com/AppFlowy-IO/AppFlowy/assets/165389491/fc772a69-9ce8-49bc-8fc2-f62527eec438)

**Comment by appflowy** [comment]
Thank you, @SWASTIKpy, for bringing this to our attention. 
We have identified the issue as a bug and are pleased to inform you that it has been resolved. The fix will be included in our upcoming release.

**Comment by SWASTIKpy** [comment]
Thank you for for resolving the bug. I appreciate the update and look forward to the upcoming release. If I encounter any further issues, I'll be sure to let you know. Thanks again for your help!
