### ISSUE TITLE
[Bug] Emoji picker stuck until reboot

### ISSUE THREAD

**Issue by apomalyn** [AppFlowy-IO/AppFlowy#502]
**Describe the bug**

If you open the emoji picker and switch pages, you will have the emoji picker still open but cannot interact with it (can't close it, can't use it to add emoji)

**To Reproduce**
1. Go to a random doc page
2. Click on the emoji icon to open the picker
3. Change page to go on another Doc or Grid page.

**Expected behavior**

When I switch pages with the emoji picker open, it should be closed on the new page.

**Screenshots**

<details>
<summary>Video of the bug</summary>

https://user-images.githubusercontent.com/22211097/169405683-9fe00c19-3216-43f1-999e-dcf43674a342.mov

</details>

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 0.0.4.beta.3

**Comment by annieappflowy** [comment]
Thanks @apomalyn , I added the bug label, and I will check with Nathan to see if it's good first issue for dev :D
BTW, are you able to add labels? I'm trying to figure out if I need to grant you some extra permissions.

Thanks,
Annie

**Comment by apomalyn** [comment]
> Thanks @apomalyn , I added the bug label, and I will check with Nathan to see if it's good first issue for dev :D
> BTW, are you able to add labels? I'm trying to figure out if I need to grant you some extra permissions.
> 
> Thanks,
> Annie

Hi @annieappflowy ! I'm only able to create and comment issues. It would be wonderful if I could add labels! 😀

**Comment by moksh-mahajan** [comment]
Working on the fix.
