### ISSUE TITLE
[Bug] cannot change the cursor's color through Settings

### ISSUE THREAD

**Issue by enomothem** [AppFlowy-IO/AppFlowy#5082]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/287c5660-4fb0-4c10-9b8e-5243aa7816c4)

### How to Reproduce

更改光标颜色确定

### Expected Behavior

更改其他颜色

### Operating System

Windows1

### AppFlowy Version(s)

5.3

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45089051/4e00f5d8-15fc-499b-af09-a857b719d856)

**Comment by richardshiue** [comment]
Hi @enomothem thanks for reporting this issue. We need the changes to apply immediately when the value has been changed. Right now, you can only change the color after changing the value and then pressing enter. Please use this workaround in the meantime.

**Comment by Xazin** [comment]
Completed in newest version.
