### ISSUE TITLE
[Bug] Problem with Chinese input

### ISSUE THREAD

**Issue by 120L021026** [AppFlowy-IO/AppFlowy#5089]
### Bug Description

In the Debian system, using the Chinese input method (fcitx5) will result in cluttered input (Pinyin disorder mixed before and after Chinese).

### How to Reproduce

Just as the Bug Description.

### Expected Behavior

Just as the Bug Description.

### Operating System

Debian12

### AppFlowy Version(s)

0.5.3

**Comment by LucasXu0** [comment]
Thanks for reporting. There's a similar [issue](https://github.com/AppFlowy-IO/AppFlowy/issues/3540) already reported on Linux.

**Comment by JARVNM** [comment]
<img width="948" height="692" alt="Image" src="https://github.com/user-attachments/assets/1ade31f3-25d2-4144-970c-903f419d1070" />
just uncheck this option

<img width="1016" height="747" alt="Image" src="https://github.com/user-attachments/assets/b56bb1bf-103f-4be5-9207-6b0bf7cf27e7" />
