### ISSUE TITLE
[Bug] Don't see Supabase as one of the cloud options on Release on Mac universal Version 0.5.4

### ISSUE THREAD

**Issue by allenlinli** [AppFlowy-IO/AppFlowy#5108]
### Bug Description

Can't see the Supabase cloud option

### How to Reproduce

1. Install AppFlowy Mac universal Version 0.5.4

### Expected Behavior

Have the Supabase option

### Operating System

Mac OS 14.4.1 (23E224)

### AppFlowy Version(s)

0.5.4

### Screenshots

<img width="1239" alt="Screenshot 2024-04-10 at 12 47 35 AM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/849911/896ba697-5726-4679-a099-781ee80d698e">

**Comment by annieappflowy** [comment]
Hi @allenlinli , we have sunset supporting Supabase as one of the cloud options. You can get more context from [this PR](https://github.com/AppFlowy-IO/AppFlowy/pull/5069)

**Comment by allenlinli** [comment]
Please update the document [here](https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy-using-supabase), it is misleading.
It took me like one to two hours to try it out lol

**Comment by annieappflowy** [comment]
@allenlinli , v0.5.2 still supports Supabase. 
I've updated the doc to reflect the latest changes.

**Comment by SC-Josh** [comment]
When will a free self-hosted option be available?
