### ISSUE TITLE
[FR]Batch import markdown

### ISSUE THREAD

**Issue by S-xgx1** [AppFlowy-IO/AppFlowy#5125]
### Description

现在markdown只能单个导入，无法批量导入
我希望可以导入文件夹及其子文件夹下所有文件，并且保留文件夹层级结构

### Impact

从obsidian和types迁移到本程序的用户
我是obsidian用户，obsidian非开源程序，并且对wayland没有中文输入支持，我看到此程序有部分中文输入法支持，并且开发者也正在积极修复中文输入有bug的部分，我想要迁移过来。

### Additional Context

https://github.com/AppFlowy-IO/AppFlowy/issues/1058 这个问题并且解决，但管理员将其关闭了，这很不好，并且与本问题重复。

@annieappflowy

**Comment by annieappflowy** [comment]
Supported. Please check out the demo [here](https://www.reddit.com/r/AppFlowy/comments/1f31119/demo_how_to_bulk_import_markdown_and_csv_files/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
