### ISSUE TITLE
[FR] View/edit body of grid items on mobile

### ISSUE THREAD

**Issue by not-a-ethan** [AppFlowy-IO/AppFlowy#5132]
### Description

When I use a grid its a pain that I cant edit the body of a grid item. 

### Impact

Users that use the mobile app that want to edit the body of a grid item.

### Additional Context

I mainly use this for my task manager to include context or more details so I dont need to make a new property clogging up my view.

**Comment by annieappflowy** [comment]
Hi @not-a-ethan , can you share some screenshots or recordings to showcase which parts of the grid can't be edited on mobile?

**Comment by not-a-ethan** [comment]
@annieappflowy @Xazin is correct with what part I am referring to

**Comment by annieappflowy** [comment]
Supporting it in v0.6.8


https://github.com/user-attachments/assets/b5f4c1c9-d852-4e19-a258-f754ed59a668
