### ISSUE TITLE
[FR] Create a new page inside page

### ISSUE THREAD

**Issue by xky0007** [AppFlowy-IO/AppFlowy#5134]
### Description

When type `/page`, create a new page inside current page and automatically open and edit the new page.

### Impact

Easy to add new linked doc to current page.

**Comment by Dav-sa** [comment]
any updates ?

**Comment by DimaZava** [comment]
Would like to make the same request. Simple, but very useful feature

**Comment by henri9813** [comment]
Hello,

It's a duplicate of #5417 

Can you maybe close your issue please ?

Best regards,
