### ISSUE TITLE
[FR] Do we have a plan to release an iOS app?

### ISSUE THREAD

**Issue by Hector1990** [AppFlowy-IO/AppFlowy#5142]
### Description

I notice we have an Android app, do we have a plan to release an iOS app.

### Impact

There are many iOS users who need to edit or read the notes on the mobile device.

**Comment by annieappflowy** [comment]
@Hector1990 , our iOS app is available to download on TestFlight

**Comment by Hector1990** [comment]
Cool! Could you provide me with a intivation code of TestFlight?

**Comment by Hector1990** [comment]
Or a link that I can download?

**Comment by annieappflowy** [comment]
@Hector1990 , click on "TestFlight" via [this link](https://appflowy.io/download#ios-and-android)
