### ISSUE TITLE
[FR] Delete Unnecessary images from the "Image" folder.

### ISSUE THREAD

**Issue by jiceylc** [AppFlowy-IO/AppFlowy#5145]
### Description

I've noticed that when it comes to image operations, especially with uploaded banner images, the original unused images are not deleted after selecting a different banner image. Over time, this can lead to significant disk space usage.

### Impact

people who use a lot of picutres

**Comment by VADDIJASWANT** [comment]
Hello Guys, is it ok if I try to work on this issue

**Comment by Scienticious** [comment]
@apomalyn  can I work on this issue?

**Comment by Xazin** [comment]
> @apomalyn can I work on this issue?

Everyone is free to work on any issue that isn't assigned, feel free to open a PR :)

**Comment by Ahad-patel** [comment]
Hey @Xazin is this issue can be solved using flutter or it requires knowledge of rust? I have opened a draft PR but not sure if it works? can you help me ?
