### ISSUE TITLE
[Bug] Cannot sync data between mac and iPhone with self hosted cloud

### ISSUE THREAD

**Issue by Hector1990** [AppFlowy-IO/AppFlowy#5148]
### Bug Description

I deployed AppFlowy on my NAS and signed in with a GitHub account in the mac and iPhone client. Then I created a test page in the mac client. But I cannot see the page on the iPhone.

I map the ports 6001:80

![CleanShot 2024-04-16 at 23 25 48@2x](https://github.com/AppFlowy-IO/AppFlowy/assets/14172847/fd7577e6-1998-4b90-9ae4-eb99d9151a7f)

### How to Reproduce

1. Create a test page on the mac client
2. Open the iPhone to check

### Expected Behavior

Can sync data between Mac and iPhone.

### Operating System

mac and iOS

### AppFlowy Version(s)

latest

**Comment by Korov** [comment]
When client connect to self hosted cloud, the websocket will use the default port 80 or 443. So the base url should be 80 or 443 too. I have created a PR to fix it https://github.com/AppFlowy-IO/AppFlowy/pull/5123, you can build the client by yourself.

**Comment by Hector1990** [comment]
@Korov OK, so even if I export the other port to 80, like 6001 -> 80, the client will still use 80, right?

**Comment by Korov** [comment]
> right

YES!

**Comment by Hector1990** [comment]
Thanks!
