### ISSUE TITLE
[FR] CodeBlock Indentation and Font Optimization.

### ISSUE THREAD

**Issue by iceyjchen** [AppFlowy-IO/AppFlowy#5150]
### Description

The code indentation spacing in CodeBlock seems a bit small. Although it's also 4 spaces, it looks much better in Typora. When dealing with a large amount of code, it can be quite uncomfortable to read. Additionally, it would be nice if the font and size of CodeBlock could be customized, as the reading and typesetting experience for code is different from text.

this is appflowy
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/38155271/3ba698df-082d-4625-8dfa-a9cd25de8048)

and this is  in typora 

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/38155271/6d34ff97-c95b-4790-9661-2e049175ad98)

### Impact

people who always use codeblock

**Comment by annieappflowy** [comment]
<img width="408" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/8433990e-27de-49ed-9e82-5fdf86fc1a3a">

Consider this was fixed
