### ISSUE TITLE
[Bug] [Mobile] sync 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5186]
### Bug Description

Hi guys saw something weird on the mobile UI. Not sure if its a sync issue.

The sync icon just stays yellow on this one grid document in particular, although on the desktop client it does sync eventually and the sync icon on the desktop turns green but its stayed the same yellow color on mobile.

Even though the grid document did sync

### How to Reproduce

Unsure

### Expected Behavior

Sync properly across devices
Clear the yellow status

### Operating System

Android

### AppFlowy Version(s)

v0.5.4

### Screenshots

https://discord.com/channels/903549834160635914/903553722804748309/1231618812659372052

**Comment by griff-rees** [comment]
I think I had something similar yesterday. I've had delays syncing before but I think this is a case where I've lost changes.

**Comment by appflowy** [comment]
@annieappflowy  We have removed the sync icon and are currently refactoring our syncing protocol to enhance its reliability and functionality. As part of this process, we will revisit and improve the sync icon logic to make it more robust and consistent. For now, I will close this bug.
