### ISSUE TITLE
[Bug][Mobile] the sync indicator in yellow although the data has been synced

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5190]
### Bug Description

I had strange synchronization effects.
1) I logged out of the mobile app and deleted several pages in the desktop app. When I logged into the mobile app, the deleted pages suddenly appeared again in the desktop app.
I then had to repeat this a few times and now both are in sync.
2) The pages that permanently had a yellow synchronization point were still synchronized. And after I duplicated the pages, a green sync point also appeared. (@rhombozoid: Unfortunately, grids and boards cannot be shared as Markdown.)
3) What I don't understand, however, is that some pages show a circle with my first letter next to the green synchronization indicator and others don't. (see screenshot).
<img width="563" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/b4a64124-aead-417c-9279-79eeaecbdff7">

4) The sync point is yellow on the mobile app board and green on the desktop app, even though the change has been updated. 

### How to Reproduce

not sure

### Expected Behavior

properly display the current sync status

### Operating System

iPhone

### AppFlowy Version(s)

v0.5.4

**Comment by emmggi** [comment]
I've noticed the same thing. Here's a strange behavior when using tabs.

Have a page opened then open another one in a new tab, then switch between tabs. It can get yellow on both now even when it was green, with no change to the page. It seems stuck on yellow, only going to green when I connect with a different device and open the same page. But when I switch between again it will go back to yellow again.

**Comment by Xazin** [comment]
We have sunsetted the sync indicator, I will close this issue for now.
