### ISSUE TITLE
[Bug] Exporting link previews should export to []() format

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#5193]
### Bug Description

When exporting a document to markdown that contains link previews, they should be exported to the Markdown format `[Page title](https://link.com/image.png)`. _(We store the url and title metadata, use this to build the markdown link)_

Original author: https://discord.com/channels/903549834160635914/903553722804748309/1232305891643232317

### How to Reproduce

Export a document containing link previews to Markdown

### Expected Behavior

The links are transformed to proper markdown format

### Operating System

All

### AppFlowy Version(s)

0.5.4

**Comment by Omegaviv** [comment]
@Xazin can I work on this?

**Comment by Omegaviv** [comment]
@LucasXu0 as @Xazin  has mentioned to display Page title and url, so according to the current implementation there is no Page title metadata on LinkPreviewNode

<img width="393" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86337946/8fc10374-ea3f-4bbe-bbb6-f5c5d2895e69">

**Comment by Xazin** [comment]
> @LucasXu0 as @Xazin has mentioned to display Page title and url, so according to the current implementation there is no Page title metadata on LinkPreviewNode
> 

This requires a change to the Link Preview Block, we should store the metadata when it's first loaded on the node itself.

What is the site has changed since? We can add an action to reload the metadata in case the author thinks it's wrong, which would go on to refetch the metadata. This way we also don't have to refetch it for every single user, it's enough to fetch it once for all users.

**Comment by Omegaviv** [comment]
okay I will create a issue on AppFlowy-plugin repository and push the changes there.

**Comment by Xazin** [comment]
> okay I will create a issue on AppFlowy-plugin repository and push the changes there.

Thanks a lot, feel free to DM me or reach out on our discord if you have questions or if I can assist you with anything.

**Comment by annieappflowy** [comment]
Supported
