### ISSUE TITLE
[Bug] Linux failing on `cargo make flowy_dev` pre-request step  

### ISSUE THREAD

**Issue by thxv3n0lvl** [AppFlowy-IO/appflowy#52]
**Describe the bug**
After setting up Flutter and Rust using  nightly version on a clean environment, tried to execute `cargo make flowy_dev` (actual Step 7 from BUILD_ON_LINUX.md) I got an error stating `Task flowy_dev not found`

**To Reproduce**
1. Follow  BUILD_ON_LINUX.md 
2. Execute command from Step 7 

**Actual behavior**  
Rust throws the next error:
```
➜  appflowy git:(main) cargo make flowy_dev
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: flowy_dev
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task flowy_dev not found
[cargo-make] WARN - Build Failed.
```

**Expected behavior**
Step succeeded without any error. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: 5.13.0-7620-generic Ubuntu  x86_64 GNU/Linux (Pop_OS!)
 - Browser: CLI
 - Version Latest commit d4fc1b91261b8575716476aa00a967c43367e43e

**Additional context**
Environment:
`rustup show`
```
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2021-03-12-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.58.0-nightly (a77da2d45 2021-11-19)
```
`flutter doctor`
```
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on Pop!_OS 21.04 5.13.0-7620-generic, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

```
I might be missing the Android and chrome stuff but I don't think is related, if I'm missing something please let me know. 
Thanks in advance !

**Comment by pdckxd** [comment]
oops, the folder struct has been changed. instruction didn't get updated. I will update later.  Below steps should work

```
cd appflowy/frontend
cargo make flowy_dev
```

**Comment by thxv3n0lvl** [comment]
Hi @pdckxd thanks for the quick reply. This worked only for that step, right after that on step 8 this command fails with the next error
``` 
➜  appflowy git:(main) ✗ cargo make -p development-linux-x86 pb
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: pb
[cargo-make] INFO - Profile: development-linux-x86
[cargo-make] ERROR - Task pb not found
[cargo-make] WARN - Build Failed.
```
However this is not related to this issue but maybe will be good to address it as part of an improvement for that linux doc.
Have a great one !

**Comment by pdckxd** [comment]
> Hi @pdckxd thanks for the quick reply. This worked only for that step, right after that on step 8 this command fails with the next error
> 
> ```
> ➜  appflowy git:(main) ✗ cargo make -p development-linux-x86 pb
> [cargo-make] INFO - cargo make 0.35.6
> [cargo-make] INFO - Build File: Makefile.toml
> [cargo-make] INFO - Task: pb
> [cargo-make] INFO - Profile: development-linux-x86
> [cargo-make] ERROR - Task pb not found
> [cargo-make] WARN - Build Failed.
> ```
> 
> However this is not related to this issue but maybe will be good to address it as part of an improvement for that linux doc. Have a great one !

This step is actually optional. You can skip and move on

**Comment by thxv3n0lvl** [comment]
Indeed, I was able to proceed, after finishing the steps from the doc I executed `flutter run` from `appflowy/frontend/app_flowy` (not sure if this is the correct command as I'm not using any IDE and don't know exactly how Flutter works) so was able to see the app running, with minor UI bugs. Thanks @pdckxd for the help!
