### ISSUE TITLE
[Bug] Click the option capsule to create a new value

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#522]
**Describe the bug**
Entering a new option value shows "Create (the value)" but it cannot be clicked to confirm

**To Reproduce**
1. Using a single-select column to add a new option value
2. Click on the capsule button

**Expected behavior**
The new option value should be created and selected 

**Screenshots**
![image](https://user-images.githubusercontent.com/12026239/171420154-6a73a105-1b9c-4944-bb94-9810d51084e3.png)

**Comment by moksh-mahajan** [comment]
@annieappflowy @appflowy I would love to work on this enhacement. Can you please assign it to me?

**Comment by moksh-mahajan** [comment]
@appflowy I think we can close this now.
