### ISSUE TITLE
[Bug] Version 0.5.5 not yet released on FlatHub

### ISSUE THREAD

**Issue by suntorytimed** [AppFlowy-IO/AppFlowy#5224]
### Bug Description

Release 0.5.5 is still missing on FlatHub.

### How to Reproduce

Version 0.5.5 doesn't appear on https://flathub.org/apps/io.appflowy.AppFlowy

### Expected Behavior

New release available on same day as a release is tagged on GitHub

### Operating System

Linux (openSUSE Tumbleweed)

### AppFlowy Version(s)

0.5.5

**Comment by LucasXu0** [comment]
https://github.com/flathub/io.appflowy.AppFlowy/pull/93
