### ISSUE TITLE
[Bug] Renaming window doesn't close when creating another new option

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#523]
**Describe the bug**
While renaming an option value persists, I can create another new option value

**To Reproduce**
1. Rename an option value
2. Enter another value

**Expected behavior**
Renaming window should auto close

**Screenshots**
![image](https://user-images.githubusercontent.com/12026239/171420689-7bd728ef-2c49-405e-b11a-5c4530c51819.png)

**Comment by appflowy** [comment]
> @annieappflowy I would like to work on this issue. @appflowy Can I work on this?

Hi, @moksh-mahajan Thank you for your contribution to AppFlowy. I assigned the ticker for you. You can DM me if you have any questions.

**Comment by moksh-mahajan** [comment]
@appflowy Can we close this one?

**Comment by annieappflowy** [comment]
Thank you for contributing to AppFlowy!
