### ISSUE TITLE
[Bug] the recent views should refresh after switching to another workspace.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#5230]
### Bug Description

The recent views should refresh after switching to another workspace.

### How to Reproduce

- switch to another workspace

### Expected Behavior

- The recent views should refresh after switching to another workspace.

### Operating System

Mobile

### AppFlowy Version(s)

0.5.6

### Screenshots

<img width="536" alt="Screenshot 2024-04-30 at 18 56 39" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/b38a73ef-23a0-4dbc-bc8a-aa38d67eafcc">

**Comment by LucasXu0** [comment]
Because the _isInitialized flag does not reset after switching workspaces, the mobile app always uses the cached version.

**Comment by Xazin** [comment]
We should call `getIt<CachedRecentService>().reset()` on changing workspace. That should be enough to resolve this.

**Comment by LucasXu0** [comment]
How about renaming the `fetchRecentViews` event to `resetRecentViews` and call `_service.reset()` in this event?
