### ISSUE TITLE
[FR]  Add Suport for Video and Files upload

### ISSUE THREAD

**Issue by felipegenef** [AppFlowy-IO/AppFlowy#5258]
### Description

It would be nice to be able to store files that can be downloaded and Videos that can be seen on AppFlowy.

### Impact

Users who store files alongside documentation or insert videos to help add a more dynamic and visual approach to the doc.

### Additional Context

I usually use Notion for storing my company invoices and Video Calls on the pages alongside my documentation about the call/ video tutorial summary. It is the only feature missing on Appflowy for me and I believe that would be the same for a lot of users too. Expected behavior is listed below:
- Select a file from our PC and store it in the AppFlowy Data folder. After that, you are able to download it.
- Select a video (Eg: mp4) from our PC and store it in the AppFlowy Data folder. After that, you are able to play it on AppFlowy or download it.

**Comment by annieappflowy** [comment]
File upload will be supported in the upcoming release (v0.6.7)
