### ISSUE TITLE
[Bug] the hover color of the wrap text field overlaps with the switcher color.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#5274]
### Bug Description

the hover color of the wrap text field overlaps with the switcher color.

### How to Reproduce

See the attached video

### Expected Behavior

better UI design 

### Operating System

Desktop

### AppFlowy Version(s)

0.5.6

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/a2c9e817-a15e-40ab-a74f-ef841f7c4782

**Comment by anshulpoonia** [comment]
attempt/#5274

**Comment by richardshiue** [comment]
The hover color is now a more pleasant light grey. Closing as completed.

![image](https://github.com/user-attachments/assets/b719bb21-286b-4198-bd5c-ba460679055c)
