### ISSUE TITLE
[FR] mutil tab

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#5286]
### Description

Just like opening code files with vscode, I hope that when opening multiple documents, I can directly switch between different documents through tabs on the right side.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/0bdc82f3-3e3c-45d7-9a89-ab6e4403de31)

### Impact

Users who often open multiple documents will definitely like it

**Comment by annieappflowy** [comment]
We actually support multi-tabs. 
<img width="274" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/a9e3d66a-fd79-47ef-8b59-1644a68389a0">

**Comment by annieappflowy** [comment]
shortcut: ctrl + click to open a page
let us know if you need more help
