### ISSUE TITLE
[Bug] Table height problem

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#5287]
### Bug Description

Reference video
When the content in the table is a URL, there will be a problem with the display

https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/793a31e1-e65c-42c8-8aaf-d53ff706b489

### How to Reproduce

Reference video

### Expected Behavior

Table width can be dynamically adjusted

### Operating System

mac

### AppFlowy Version(s)

0.5.6

**Comment by annieappflowy** [comment]
Fixed in the upcoming release (v0.7.8)
