### ISSUE TITLE
[Bug] Page title not visible on page

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#5290]
### Bug Description

My page name is "My Page Title" but this is not present alongside the icon

### How to Reproduce

Create a page with a name, put an icon, the page name is not visible

### Expected Behavior

I should be able to see the title aside the icon.

### Operating System

MaCOS

### AppFlowy Version(s)

0.56.0

### Screenshots

<img width="746" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/4645967/173dbd19-10c4-4c55-a723-ffef499df657">

**Comment by LucasXu0** [comment]
The page title is displayed only in the title bar on desktop. We are planning to optimize the layout of the icon, title, and cover.

**Comment by henri9813** [comment]
Hello,

Do you have an issue mentioning this ?

That is very disturbing  :D

**Comment by Xazin** [comment]
Closed as completed :+1:
