### ISSUE TITLE
[Bug] The toolbar will hide behind the keyboard if the Android user deactivates the navigation bar at the bottom

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#5292]
### Description

The toolbar will hide behind the keyboard if the Android user deactivates the navigation bar at the bottom.

<img width="196" alt="Screenshot 2024-05-09 at 16 44 28" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/f7e2f878-3b4c-4b78-9f08-b7166dd12e74">

**Comment by Aurel-C** [comment]
I'm experiencing the same issue on two devices and it does not depend on the keyboard app used.

**Comment by LucasXu0** [comment]
It's not caused by the keyboard app itself. The toolbar position depends on the height of the navigation bar and the height of the keyboard. However, the system doesn't return the correct height after deactivating the navigation bar.

**Comment by Aliang-code** [comment]
same problem
![Screenshot_2024-05-27-10-34-39-974_io appflowy appflowy](https://github.com/AppFlowy-IO/AppFlowy/assets/30334745/24a749f4-7acd-457b-af9e-983836d9bf17)

**Comment by Aurel-C** [comment]
This is fixed with the last update
