### ISSUE TITLE
[Bug] Callout created in dark theme stay in dark theme even in light theme

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#5296]
### Bug Description

During the night, my system is in dark theme.

I create some content including callout, the dark theme rendering was fine, but the tomorrow, my callout are still in dark theme but in my light theme appflowy app.

But the new callout are created in light theme ( as I show in my screenshot )

### How to Reproduce

In dark theme:
- Create a callout
- Go in light theme
- The callout is still in dark theme

### Expected Behavior

The callout change change to light theme

### Operating System

MacOS

### AppFlowy Version(s)

0.56.0

### Screenshots

<img width="1374" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/4645967/ce871d2d-0b43-49cf-bfb6-f4aa921c3387">

**Comment by annieappflowy** [comment]
Unable to reproduce. Please reopen if the issue persists
