### ISSUE TITLE
[Bug] Characters deleted while typing board card title

### ISSUE THREAD

**Issue by plasticboy** [AppFlowy-IO/AppFlowy#5301]
### Bug Description

When you create a board card or edit an existing one and type in the title field, characters are randomly deleted.

See screen recording below for example

### How to Reproduce

1. Got to any board
2. Click the "New" button in any column and start typing
3. Type for a while and observe characters deleted

### Expected Behavior

Characters are not deleted.

### Operating System

Windows 11 and Ubuntu 22.04

### AppFlowy Version(s)

0.5.6

### Screenshots

![board_card_create](https://github.com/AppFlowy-IO/AppFlowy/assets/54499/2ebed6e5-cc78-4390-abb7-8f253ea77504)

**Comment by joe-eklund** [comment]
Just started playing with Appflowy for the first time and also ran into this issue. :( Can confirm it happens on macos installed through brew.
