### ISSUE TITLE
[FR] Filter tags in calander

### ISSUE THREAD

**Issue by Artemis1-0** [AppFlowy-IO/AppFlowy#5303]
### Description

Have an option to only show events with specific tags in the calendar, similar to the filter option in grid and board.

### Impact

All users

### Additional Context

I would like to help on this issue but due to personal reasons I can't devote any time to learning the appflowy conventions and how to submit pull requests and all of the things required to do a code submission. Also, I'm not familiar with Flutter or any of the languages or api's used with appflowy as I am still quite a novice at programming so any description how you did this would be greatly appreciated. I may be able to submit my first pull request this summer

**Comment by Artemis1-0** [comment]
@factotvm

**Comment by Artemis1-0** [comment]
@annieappflowy

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/3345
https://github.com/AppFlowy-IO/AppFlowy/issues/6234

**Comment by Artemis1-0** [comment]
mb. Guess I didn't check properly. Should I close this issue then?

**Comment by Artemis1-0** [comment]
@annieappflowy Sorry if I'm being very annoying but should I close this issue since someone already created a similar one?
