### ISSUE TITLE
[Bug] Inset on getting started screen on windows non-existing on top on small screens

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#5304]
### Bug Description

On Windows, when the window is as small in height as it can be, the logo collides with the app bar.

This does not look very good, let's ensure there's a minimum amount of space at the top.

### How to Reproduce

Open AppFlowy, if signed in already then simply sign out.

### Expected Behavior

Equal distribution such as same minimum inset on top and bottom.

### Operating System

Windows

### AppFlowy Version(s)

0.5.6

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/5292d3b3-9a90-4429-b456-e4afe3b2a818)

**Comment by Trapiz** [comment]
I would like to work on this issue!
