### ISSUE TITLE
[Bug] can't launch appimage

### ISSUE THREAD

**Issue by superiums** [AppFlowy-IO/AppFlowy#5306]
### Bug Description

can't launch, display this msg:
```
./AppFlowy-0.5.6-linux-x86_64.AppImage                                                                                                   ✘ 1

(AppFlowy:9850): Gtk-WARNING **: 10:18:44.121: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: 无法识别的图像文件格式 (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: 无法识别的图像文件格式 (gdk-pixbuf-error-quark, 3)
fish: Job 1, './AppFlowy-0.5.6-linux-x86_64.A…' terminated by signal SIGABRT (Abort)
```

### How to Reproduce

download the appimage.
```
sudo chmod 755 appimage-file
./appimage-file
```

### Expected Behavior

be launched.

### Operating System

Arch Linux

### AppFlowy Version(s)

0.5.6

**Comment by superiums** [comment]
gdk-pixbuf2 2.42.11-2 was installed already.

**Comment by LucasXu0** [comment]
I did a search. Can you try this workaround?

https://github.com/wyyadd/LaLa/issues/40#issuecomment-1950290223

```
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
echo $XDG_DATA_DIRS
./XXXX.AppImage
```

**Comment by superiums** [comment]
thanks for suggestion, i've tried to set XDG_DATA_DIRS, but not work.
also i've tried to refresh mime cache, still no lucky.

**Comment by si-erik** [comment]
Modern themes use svg for icons.
It seems like 'libpixbufloader-svg.so' is missing in the appimage, so it fails to load theme resources.

**Comment by superiums** [comment]
extra/gdk-pixbuf2 2.42.12-1 was already installed.

**Comment by frandmb** [comment]
> I did a search. Can you try this workaround?
> 
> [wyyadd/LaLa#40 (comment)](https://github.com/wyyadd/LaLa/issues/40#issuecomment-1950290223)
> 
> ```
> export XDG_DATA_DIRS="/usr/local/share:/usr/share"
> echo $XDG_DATA_DIRS
> ./XXXX.AppImage
> ```
@LucasXu0 
It seems to be a bundle time error.
I was having the same issue when bundling locally and realized it was because the [AppImage recipe](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml) is still set to use `jammy` sources and the CI runs on `ubuntu:latest`. Replacing every `jammy` with `noble` (for Noble Numbat) did the trick for me
