### ISSUE TITLE
[Bug]Numbered List export bug

### ISSUE THREAD

**Issue by eisesser** [AppFlowy-IO/AppFlowy#5313]
### Bug Description

When I export an file with a numbered list  in, in the exported file every number is 1

### How to Reproduce

Make a file with a numbered list, export as .md or .html

### Expected Behavior

it will be exported like it looks in the app

### Operating System

Linux (Endeavour OS)

### AppFlowy Version(s)

0.5.5-1

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/150927066/d10264b5-aa9d-41c4-a174-841dbef8b2fd)
![Screenshot_20240510_200508](https://github.com/AppFlowy-IO/AppFlowy/assets/150927066/3b1c4026-4755-48a0-8fcb-f43c2025b803)

**Comment by emmggi** [comment]
It was addressed in https://github.com/AppFlowy-IO/AppFlowy/issues/5216

HTML exports correctly in v0.5.6 so you need to upgrade. Markdown needs a viewer that displays the correct enumeration.
