### ISSUE TITLE
[FR] Add a border to the selected Unsplash image.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#5318]
### Description

Currently, only the built-in images are given a border when selected. We should also add a border to selected Unsplash images.

<img width="402" alt="Screenshot 2024-05-13 at 13 34 50" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/80752ecb-9208-4019-818d-24364d010177">
<img width="553" alt="Screenshot 2024-05-13 at 13 33 39" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/7ffd26f0-7d77-401c-947d-cd2fff578b6a">

### Impact

Make the UI consistent.

### Additional Context

Related file: https://github.com/AppFlowy-IO/AppFlowy/tree/main/frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart

**Comment by sudhar08** [comment]
Hey @LucasXu0 I can't understand what you are trying to do. so can you explain a bit more clearly it was very important to build a new feature for this community.

**Comment by Xazin** [comment]
> Hey @LucasXu0 I can't understand what you are trying to do. so can you explain a bit more clearly it was very important to build a new feature for this community.

In the first image that Lucas attached to the issue report, under the `Background image` category, you see that the selected image has a blue border with some spacing and then the image.

Now in the second image attached, you see how selecting an Unsplash image looks, but if the unsplash image is already the selected image, there is no blue border indicating this.

This issue aims to address this discrepancy, by adding the same border from the first picture, to the unsplash image if it is the currently used (selected) one.

**Comment by sudhar08** [comment]
@Xazin Thank you for explaining
