### ISSUE TITLE
[Bug] Editor loses focus when typing / as part of the text

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#5324]
### Bug Description

It happens sometimes that when I enter something like 'red/white' into the editor, it will lose focus.

### How to Reproduce

Type in a slash as part of the text and continue typing. It loses focus after the 4th character following the slash.

### Expected Behavior

Should not lose focus.

### Operating System

Linux

### AppFlowy Version(s)

0.5.7

### Screenshots

[Screencast from 2024-05-13 12-01-05.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/7174edb9-6fec-4c33-a961-a0d78ed17700)

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/23f98166-fa41-4b4c-9b54-52c02a970a83)

### Additional Context

Not sure under what conditions it happens.

**Comment by Xazin** [comment]
CC @LucasXu0

Could be the slash menu on exit doesn't return focus properly to the editor in some cases.
