### ISSUE TITLE
[Bug] Can't duplicate a Grid.

### ISSUE THREAD

**Issue by moksh-mahajan** [AppFlowy-IO/AppFlowy#533]
**Describe the bug**
The duplicate option is working fine for the **Doc**, but not for the **Grid**.

**To Reproduce**
1. On a page create a Grid by clicking on + and choosing the **Grid** option.
2. Click on the ':' icon on the grid file.
3. Click on the **duplicate** option
4. Option window pops but grid copy is not being created.

**Expected behavior**
On click of the duplicate option, a new grid copy must be created.

**Desktop**
 - **macOS** Monetary
 - Version 12.0.1

**Comment by moksh-mahajan** [comment]
Tried debugging the issue and found a FlowyError being returned with the following message:
`msg: Error("invalid type: map, expected a sequence", line: 1, column: 1)`

I am no good at rust, so it would be better if someone who knows rust should look at this.
`frontend/rust-lib/flowy-folder/src/services/view/controller.rs` is a good place to start.

**Comment by appflowy** [comment]
Hi @moksh-mahajan  I have fixed it in the 0.0.4 release version.
