### ISSUE TITLE
[FR] Hotkey to reset application scale to 1.0

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#5340]
### Description

We probably need somewhere in the settings where we can set the scale level, but for starters just being able to forcefully reset the application scale to 1.0 would be very nice to have.

### Impact

If need be, we can easily zoom in/out and then more easily come back to default when needed.

**Comment by Trapiz** [comment]
I would like to pick up this issue! 

I was thinking of using the Ctr+0 for resetting the application scale, I think that's the most common approach but I'd love to hear a different opinion

**Comment by Xazin** [comment]
> I would like to pick up this issue!
> 
> I was thinking of using the Ctr+0 for resetting the application scale, I think that's the most common approach but I'd love to hear a different opinion

Sounds good to me, I'll assign you :+1:
