### ISSUE TITLE
[Bug] Update title in a card will push the cursor at the end of the title

### ISSUE THREAD

**Issue by cyrilcharlier-jvs** [AppFlowy-IO/AppFlowy#5342]
### Bug Description

After created a card, i open it on clicking the title 

I go to the middle of the title to change something, and after modifying and after a small delay the cursor go to the end of the title, even if i want to continue modifying the the title

### How to Reproduce

Go to the middle of the title of a card to change something, and after modifying and after a small delay the cursor go to the end of the title, even if i want to continue modifying the the title

### Expected Behavior

I would like the cursor stay at the same place to continue to modify the title

### Operating System

Mac OS

### AppFlowy Version(s)

0.5.7

### Screenshots

Before modifying
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/24fdd4c2-be41-4d0e-87f7-64e78f8d3076)

After a delay after modifying
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/3ecee3aa-71a3-46aa-9d48-402a29b3c148)

**Comment by Xazin** [comment]
This should be resolved in next release. 🙏

**Comment by annieappflowy** [comment]
@cyrilcharlier-jvs , please download the latest ([v0.5.8](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.8)), and let us know if the issue remains.

**Comment by cyrilcharlier-jvs** [comment]
Hi @annieappflowy, yes it is always the same display for date :
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/4b390bd4-ca6a-4f30-88d8-37c121836eea)

I'm on 0.5.8 : 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/17dd8e31-58d3-47d9-a404-e2fea83326df)

thanks

**Comment by cyrilcharlier-jvs** [comment]
Perfect it is ok !
