### ISSUE TITLE
[Bug] Duplicated shortcut entries and missing translation strings

### ISSUE THREAD

**Issue by suntorytimed** [AppFlowy-IO/AppFlowy#5355]
### Bug Description

In the shortcut overview there are lots of duplicated entries and most of them don't have a translation string in InLang to add a translation to them.

### How to Reproduce

Open shortcut window in the dekstop application (Flatpak 0.5.7 on Linux)

### Expected Behavior

Entries are shown only once and they have translation strings connected to them, so that a language specific translation can be added. This includes the keynames.

### Operating System

Linux

### AppFlowy Version(s)

0.5.7

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/2744377/b4029022-9ce8-4f9b-b47a-8e71dc9bf06d)

**Comment by MayurSMahajan** [comment]
@Xazin does inlang translation doesn't have appflowy editor translations? If so, how can they be included?
