### ISSUE TITLE
[Bug] error message when loading themes

### ISSUE THREAD

**Issue by yotamguttman** [AppFlowy-IO/AppFlowy#5359]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/92977002/0232fa59-0692-448b-834a-2309b2f92ee2)
receiving different error messages when attempting to upload any theme file.

### How to Reproduce

I downloaded all the official themes from the Themes Appflowy Docs Article. I tried to upload them all: base, barbie, and dracula. I kept receiving an error in return that the light theme file is faulty and the learn more button just sends me back to the same docs page...

### Expected Behavior

the theme file should have been added to the theme list and applied to the app UI.

### Operating System

Fedora 40, Gnome 46

### AppFlowy Version(s)

unknown

### Additional Context

also, when you download a theme file from the Appflowy docs page, you get a zip file which when extracted, has an odd structure. check this image:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/92977002/577c933f-9b84-42c4-8a42-dea63bbc1492)

there's the zipping folder which inside has a folder of the same name and some mac crap folder. and this can be confusing to some users because the docs article steps describe having to unzip the archived file and uploading the extracted folder to the Appflowy theme UI. but if you do that you get the following error message:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/92977002/8f0610b6-27c2-45d5-84f5-3ea660038cdb)

because Appflowy expects to see the light+dark json files right in side this folder, but instead there's a duplication of the same folder and some empty mac folder. I figured that I should pick the folder inside which housed the Json files but it isn't at all reproducible according to the docs article.
https://docs.appflowy.io/docs/appflowy/product/themes

---

and the cherry on top is that the 'debug info' button does not do anything. so I cannot share the version details because it doesn't show in the settings page either. I updated all my apps 2 days ago so I suppose it's the latest vers.
![Screenshot from 2024-05-18 11-02-31](https://github.com/AppFlowy-IO/AppFlowy/assets/92977002/33e67dc2-9d28-40f9-97c5-b7ff719f8f71)

**Comment by Xazin** [comment]
I believe there are a lot of improvements to the theme upload handler that can be done.

This is one of many, but at least:
- [ ] A theme should not require dark/light mode versions, it should be optional.
- [ ] Concise error messages, if eg. a variable is missing, it should warn the user but still succeed in importing _(the missing color should be it's default variant, instead of failing completely)_

**Comment by yotamguttman** [comment]
let me just emphasis again that the only theme files I've tried to import are from the official doc article. I'd find it hard to believe the theme files were faulty.

**Comment by MayurSMahajan** [comment]
Hey @yotamguttman, the error message is because there is a new color field called `secondaryTextColor` added to the `FlowyColorScheme` but the themes in the documentation do not have any color for that field. 

I am going to add a new zip adding this new color field. Thanks for filing this issue.

**Comment by MayurSMahajan** [comment]
I have updated the official docs, but the official docs will take some time to reflect those changes, till then you can download this zip file here:
[Dracula.flowy_plugin.zip](https://github.com/AppFlowy-IO/AppFlowy/files/15366432/Dracula.flowy_plugin.zip)

**Comment by MayurSMahajan** [comment]
While we are here, I think the error UI can be improved.

**Comment by annieappflowy** [comment]
@yotamguttman , this issue should be fixed. Please feel free to reopen
