### ISSUE TITLE
[Bug] changing field type from text to checkbox causes exception

### ISSUE THREAD

**Issue by zoli** [AppFlowy-IO/AppFlowy#5360]
### Bug Description

In board view changing field type from text to checkbox throws an exception when you hover the cursor on the card.
`'CellController<CheckboxCellDataPB, String>' is not a subtype of type 'CellController<String, String>' in type`

### How to Reproduce

Open a card and create new field which its type is text by default. Change the field type to checkbox and close the card. Hover on any card and you get exception.
converting any field from `CellController<String, String>` to a `CellController<SomeCellDataPB, String>` causes exception.

### Expected Behavior

Not throwing any exception.

### Operating System

Linux

### AppFlowy Version(s)

v0.5.7

**Comment by zoli** [comment]
From what I've learned the problem is `TextCardCell` not getting disposed. The field type changes from text to checkbox but it's still going with `TextCardCell`.

**Comment by Xazin** [comment]
> From what I've learned the problem is `TextCardCell` not getting disposed. The field type changes from text to checkbox but it's still going with `TextCardCell`.

Most likely caused by recent changes to the database by @richardshiue, however he is on leave at the moment.

Do you want to pick up this issue @zoli? Else I'll find some time to resolve it before version 0.5.9.

**Comment by zoli** [comment]
> Do you want to pick up this issue @zoli? Else I'll find some time to resolve it before version 0.5.9.

Yes, Currently I'm looking into it. When are you going to release 0.5.9?

**Comment by Xazin** [comment]
> > Do you want to pick up this issue @zoli? Else I'll find some time to resolve it before version 0.5.9.
> 
> Yes, Currently I'm looking into it. When are you going to release 0.5.9?

0.5.9 is scheduled for release on June 3rd, so still a little over 2 weeks left.
