### ISSUE TITLE
[Bug] Appearing and disappearing caracters when editing an item in the calendar view

### ISSUE THREAD

**Issue by oppZ** [AppFlowy-IO/AppFlowy#5365]
### Bug Description

If we type fast enough and correct the name by deleting caracters (with backspace), caracters can appear and disappear. It looks like the bug is an issue of the synchronization between the box where we type the name of the item and where the item is displayed in the calendar.

### How to Reproduce

The key to reproduce the bug is perform the key presses before the change is displayed in the calendar. The change time is around a second, so the two key presses need to be done within this one second

Go to the calendar view, create an item and click on it to edit it ; a box will appear to edit its name
**Appearing caracters:** 
Press any letter (like "s") then Backspace _before the change is displayed in the calendar_. 
 --> the letter "s" will come back

Expected behavior:
The letter "s" should not be present anymore

**Disappearing caracters:**
First, type in the box the same letters like "dddd"
Press Backspace then "d" _before the change is displayed in the calendar_. 
 --> the last "d" will disappear

Interestingly, for this "trick" to work, the last caracter needs to be the same as the one that we are pressing ; if item name is "aaaa" and we Press Backspace then "d", the last letter (here "a") will not disappear and it will be working as expected.

Expected behavior:
The letter "d" should be still present 

### Expected Behavior

See How to Reproduce

### Operating System

Ubuntu 24.04 LTS

### AppFlowy Version(s)

0.5.7 with the AppImage version

### Screenshots

![Screenshot from 2024-05-19 14-17-55](https://github.com/AppFlowy-IO/AppFlowy/assets/28532065/934632a2-0063-454d-a3c9-bb60c6f294db)

I would have included a video but the default app to make screenshots do not have the option to switch to screencast for some reason

**Comment by annieappflowy** [comment]
This issue should be resolved in the upcoming release (v0.5.8).

**Comment by oppZ** [comment]
> This issue should be resolved in the upcoming release (v0.5.8).

Well, the update kinda fixed it. If we try the same how to reproduce it, the text will be different in the box and the calendar as shown here :
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/28532065/667f81ea-80c7-4d2d-97b4-964526a19660)

However, if we click away, the correct text will be set to the item. So a minor visual bug is left

**Comment by annieappflowy** [comment]
@oppZ , thank you for the confirmation. Could you please share a video recording? I wasn't able to reproduce it on macOS and Windows 11 with the latest release (v0.5.8)

**Comment by oppZ** [comment]
@annieappflowy I downloaded the zip version of windows 11 with the latest latest release (v0.5.8) and this is the video :

https://github.com/AppFlowy-IO/AppFlowy/assets/28532065/36b259bf-8413-4697-8f4e-0bc7e7021c62

**Comment by oppZ** [comment]
Same behavior on Linux using the latest latest release (v0.5.8)

**Comment by PineTreePizza** [comment]
> Same behavior on Linux using the latest latest release (v0.5.8)

I'm getting the same issue in boards I use the flatpak version also 0.5.8

**Comment by annieappflowy** [comment]
Should be fixed. We modified the behavior of updating the card title through the pop up window. Now you need to press Enter or Leave the window to reflect your title changes.
