### ISSUE TITLE
[Bug] Excessive application memory usage

### ISSUE THREAD

**Issue by elliotsoomro** [AppFlowy-IO/AppFlowy#5372]
### Bug Description

Today I got a warning that AppFlowy was using excessive application memory, exceeding over 100 GB and rising quickly, causing the system to run out of it and forcing me to quit the app. I was creating a grid within a grid item when this occured. Removing the top level page and restarting the app solved the issue. Re-creating the grid within a grid and the issue re-evolved.

### How to Reproduce

1. Create a new page
2. Create a grid within that page
3. Create an item in the grid
4. Open the item as a page
5. Create a new grid on that page
6. Click to open the menu of that nested grid, select View database

### Expected Behavior

AppFlowy should not use that much application memory.

### Operating System

macOS Sonoma 14.4.1

### AppFlowy Version(s)

0.5.7

### Screenshots

![Screenshot 2024-05-20 at 11 00 01](https://github.com/AppFlowy-IO/AppFlowy/assets/10349178/adce154e-fc35-404d-9cf7-ff5bc22338b2)
![Screenshot 2024-05-20 at 11 11 08](https://github.com/AppFlowy-IO/AppFlowy/assets/10349178/df063662-e07d-4381-92f2-442056e87527)
![Screenshot 2024-05-20 at 11 15 22](https://github.com/AppFlowy-IO/AppFlowy/assets/10349178/11aabb47-c448-4e1e-8d01-78036b0855b7)

**Comment by LucasXu0** [comment]
@elliotsoomro Thank you for reporting this issue. We have addressed it, and the fix will be included in the next version.
