### ISSUE TITLE
[Bug] Date are shown with incorrect format

### ISSUE THREAD

**Issue by cyrilcharlier-jvs** [AppFlowy-IO/AppFlowy#5385]
### Bug Description

I have chosen the french format for displaying date, but the english format is applied even after reboot of AppFlowy

### How to Reproduce

Choose the french format J/M/A in the preferences and reboot AppFlowy

### Expected Behavior

Date are shown in J/M/A format

### Operating System

Mac OS

### AppFlowy Version(s)

0.5.7

### Screenshots

Preferences : 
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/5832d622-b684-4be1-8b10-58d98800d461)

Date display as :
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/de46c8d7-0e7f-4695-9e26-c868eefa6a0a)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/6c2728ab-dc6c-4a98-8657-10ac4e12ad9e)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/79188763/26427a00-fc85-4c9e-a48d-c28012664277)

**Comment by Xazin** [comment]
The date format for a date in database has it's own settings, and are currently unrelated to the global settings.

**Comment by Xazin** [comment]
I'm going to close this for now as this is intentional behavior, until we decide otherwise. :pray:
