### ISSUE TITLE
[Bug] wrong string for workspace icon subtitle

### ISSUE THREAD

**Issue by suntorytimed** [AppFlowy-IO/AppFlowy#5392]
### Bug Description

The subtitle for the workspace icon in the settings uses the wrong string for the subtitle text

### How to Reproduce

Use v0.5.8 and go into the new settings menu for the workspace design.

### Expected Behavior

using the correct strings for the new settings menu, instead of the old translation strings.

### Operating System

Linux

### AppFlowy Version(s)

0.5.8

### Screenshots

![Screenshot from 2024-05-22 08-12-13](https://github.com/AppFlowy-IO/AppFlowy/assets/2744377/73d63d3e-6d6c-428a-a91f-ad6baf82bf43)

It uses `settings.workspacePage.workspaceIcon.description`:
![Screenshot from 2024-05-22 08-54-38](https://github.com/AppFlowy-IO/AppFlowy/assets/2744377/868656b9-376f-4add-a66f-80c0ac670559)

instead of `newSettings.workplace.workplaceIconSubtitle`:
![Screenshot from 2024-05-22 08-54-22](https://github.com/AppFlowy-IO/AppFlowy/assets/2744377/86c7b629-aaad-4047-85d8-355e8bbe782f)

**Comment by Xazin** [comment]
The translation occurred just before the change, therefore the translation is not up to date. :pray:

**Comment by suntorytimed** [comment]
@Xazin so do I have to update the translation for `settings.workspacePage.workspaceIcon.description` or will the switch to the new string happen with a future update?

**Comment by Xazin** [comment]
> @Xazin so do I have to update the translation for `settings.workspacePage.workspaceIcon.description` or will the switch to the new string happen with a future update?

It's just the translation value to the key that is wrong for Deutsch, so just updating the Deutsch value will suffice.

**Comment by suntorytimed** [comment]
Ah, in that case I will fix the english string as well. Thanks for clarifying.
