### ISSUE TITLE
[Bug] Text direction settings not working

### ISSUE THREAD

**Issue by zoli** [AppFlowy-IO/AppFlowy#5402]
### Bug Description

`defaultTextDirection` is not getting updated.

### How to Reproduce

Open settings go to the workspace section and change the text direction to RTL you should see all the text in the document to get RTL but it doesn't happen anything.

### Expected Behavior

all the text in the document should start from right to left.

### Operating System

Linux

### AppFlowy Version(s)

v0.5.8

### Additional Context

I think this bug came after the settings have changed, I'm not sure. Please assign it to me. I want to add some tests to maybe prevent this from happening again.

**Comment by Xazin** [comment]
What if you change layout direction?

There is no change from the old to the new settings, but it might be that even the old setting was unused, thus the new one isn't used either.

**Comment by zoli** [comment]
> What if you change layout direction?

That works fine.

Maybe it stopped working after another change, I remember it was working before.
