### ISSUE TITLE
[Bug] text duplicates on insert a block attribute

### ISSUE THREAD

**Issue by CatHood0** [AppFlowy-IO/AppFlowy#5403]
### Bug Description

The same of the title. When you type some random text, and, insert a block (on another line), if you go to an empty line (i just tested in empty lines) and writes something, will be writed the text from the last block inserted, and you letter.

_Sorry for my bad english_

### How to Reproduce

1) Append 3 new lines
2) At last new line, put a block attribute (i just test this with headings and list)
3) Write something in this block
4) Select another empty line
5) Just try to type a letter

### Expected Behavior

Actual (it's valid with headings too):

listT
* List

Expected:

T
* List

### Operating System

Android

### AppFlowy Version(s)

0.5.8 

### With heading:

_And yes, there's some error in selection, that forces selection to the index 0 instead just go to last as i want it_

https://github.com/AppFlowy-IO/appflowy-editor/assets/114286961/21f79c37-c00b-497f-ac62-0cfc046c7b06

### With list:

https://github.com/AppFlowy-IO/appflowy-editor/assets/114286961/0b4be1e5-b016-4e5e-9f64-fafbec35a4ec

**Comment by LucasXu0** [comment]
Hi, @CatHood0. I'm unable to reproduce it following your steps. Could you please check my video and see if there is anything missed?

https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/ccfe5ff4-f83e-4ab2-a633-a490de8b96eb

**Comment by CatHood0** [comment]
It's strange, i make the steps as you, and the issue happens...

I got this:


https://github.com/AppFlowy-IO/AppFlowy/assets/114286961/236000ad-97f1-4961-897d-6cffaa432d42
