### ISSUE TITLE
Persian Language Support 

### ISSUE THREAD

**Issue by brightuniverse** [AppFlowy-IO/AppFlowy#5427]
### Description

Hello AppFlowy Team,
I hope this message finds you well!

I truly appreciate your effort and time, what you've done is incredible.
However, Notion doesn't support Persian language and they've said multiple times that they have no plan to add it anytime soon so I was wondering if you could add Persian language? Persian is written from right to left but in Notion and AppFlowy it's written from left to right. Also, no cool Persian font is supported either.

Please let me know what your thoughts are on this matter
I really appreciate you!

### Impact

Iranian & Arabic users because these two languages have the same alphabet however they're different languages 

### Additional Context

I've included everything

**Comment by zoli** [comment]
AppFlowy supports RTL & AUTO (mixed RTL & LTR) direction in its document editor. Also, there is some work to support it in kanban board (#5387).

**Comment by 0xKayvan** [comment]
@brightuniverse In case your texts are appearing from left to right you have to enable RTL Support in settings (Settings > Workspace > Text Direction)
<img width="1098" alt="SC01" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11921744/3129fac0-8d93-4492-bc8e-1aa209df63a1">
<img width="1114" alt="SC02" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11921744/1ff9929b-06c7-4b9b-9bad-b1e21907cbd2">
