### ISSUE TITLE
[Bug] Keys not working while editing Status for Workspace in board view

### ISSUE THREAD

**Issue by bbard** [AppFlowy-IO/AppFlowy#5451]
### Bug Description

Trying to type the following keys `e n , . BACKSPACE DELETE`  in the status for Workspaces are not working/showing up.
I can type normally inside anything in the application like task or pages.

Change the language of the keyboard shows the same behavior.

### How to Reproduce

Create a new workspace
Create a new board
Make sure you are in the board layout
Edit the title of the column
Type the keys `e n , . BACKSPACE DELETE` 
None of the keys are typed/work

### Expected Behavior

The keys `e n , . BACKSPACE DELETE`  show type/work normally in the field for board view

### Operating System

Windows 11

### AppFlowy Version(s)

0.5.8

**Comment by aaronang** [comment]
I can confirm this bug. I was able to reproduce it on a Windows 11 machine.

**Comment by zoli** [comment]
It seems this is intended behavior. Which comes from https://github.com/AppFlowy-IO/AppFlowy/pull/5270 PR. For example, see [here](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart#L460-L471). 
I think it's very annoying not being able to hit backspace on creating a new card. @richardshiue @Xazin Why backspace is disabled?

**Comment by LucasXu0** [comment]
> It seems this is intended behavior. Which comes from #5270 PR. For example, see [here](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart#L460-L471). I think it's very annoying not being able to hit backspace on creating a new card. @richardshiue @Xazin Why backspace is disabled?

It's not intended behavior. The shortcuts' scope should be limited to the card itself, not including the card header. Never mind, I'm fixing it.

**Comment by zoli** [comment]
@LucasXu0 What about adding a new card why backspace is disabled there?
