### ISSUE TITLE
[Bug] Some keys int board view are not registered

### ISSUE THREAD

**Issue by JustScreaMy** [AppFlowy-IO/AppFlowy#5462]
### Bug Description

I have experienced a few key not working in changing group names in board view. Exactly `e`, `n`, `Enter`, `Backspace`, `Delete` but upper case of `e` and `n` works normally. Also this issue only persist when changing name of a group in board.

### How to Reproduce

1. Create a new board
2. Try to rename any of the groups
3. You cannot delete characters using backspace or delete, confirm with enter or use `e` or `n` in titles

### Expected Behavior

Expected is to be able to use `e` and `n` in titles or be able to submit the changes or creating a new column

### Operating System

Fedora 40

### AppFlowy Version(s)

0.5.8 - Flathub

**Comment by TheReal-Flo** [comment]
I have the same problem, boards are very much unusable without the `Enter` key

**Comment by LucasXu0** [comment]
closed as completed. https://github.com/AppFlowy-IO/AppFlowy/pull/5460
