### ISSUE TITLE
[Bug] Checklist exception on fast typing

### ISSUE THREAD

**Issue by zoli** [AppFlowy-IO/AppFlowy#5478]
### Bug Description

The problem is AppFlowy changes the task name with a delay (debounce), probably to prevent sending a lot of event to the backend. But on updating the task name with a delay it doesn't send text selection data (cursor offset) so the selection wont get sync with the text (task name) and sometimes the selection offset is grater than task name length which causes error.

### How to Reproduce

1. In Kanban view create a checklist field type
2. Click on the add button to add a new task
3. Start fast typing and you will see an error message and exception details in logs also the task height will grow suddenly.

### Expected Behavior

Not seeing an exception.

### Operating System

Linux

### AppFlowy Version(s)

v0.5.8

**Comment by zoli** [comment]
My initial solution is to remove [`didUpdateWidget`](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart#L186-L193) but I'm not sure that it won't cause any side effect.

**Comment by annieappflowy** [comment]
Hi @zoli , this issue should be fixed in[ v0.6.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.0).
