### ISSUE TITLE
[Bug] Lost connection to device when trying to login or start anonymous session after successfully build

### ISSUE THREAD

**Issue by nhthanh719** [AppFlowy-IO/AppFlowy#5480]
### Bug Description

I am using Window 11 x64. I successfully built the app and get it running in the login screen. But I cannot proceed further with any options of login or start an anonymous session.

![Screenshot 2024-06-06 112805](https://github.com/AppFlowy-IO/AppFlowy/assets/81922015/1f7687e9-3a2c-450c-b443-7ccafdda7565)

When I start an anonymous session, the app stops and shows "Lost connection to device" error in the debug console
![Screenshot 2024-06-06 113514](https://github.com/AppFlowy-IO/AppFlowy/assets/81922015/f4b7ab0e-090a-44cc-a8ce-40f4c6b0447f)

### How to Reproduce

In VsCode, at Run and Debug tab:
1. Start Debugging with option AF: Clean and Rebuild All
2. After building successfully, the app starts at the Login screen
3. Choose start an anonymous session

### Expected Behavior

The app should run normally

### Operating System

Window 11 x64

### AppFlowy Version(s)

0.5.9

### Additional Context

flutter doctor in the internal
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22631.3672], locale vi-VN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.90.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

Here is the text of Debug console:

```
{"msg":"[INITIALIZE_WITH_NEW_USER - EVENT] initialize_when_sign_up: is_new: true","time":"06-06 11:32:39","target":"flowy_folder::manager","email":"5a2b5bc9-4862-4f58-8b9b-58a766725e9a@appflowy.io","name":"Me","authenticator":"Local"}
{"msg":"[🟢 INITIALIZE - START]","time":"06-06 11:32:39","target":"flowy_folder::manager_init"}
  2024-06-06 11:32:39  INFO flowy_folder::manager_init: Init workspace: eacd81f9-8542-430f-aa1b-38ffea90b4a5 from: LocalDisk
    at flowy-folder\src\manager_init.rs:23
    in flowy_folder::manager_init::initialize with uid: 334880165605675008, workspace_id: "eacd81f9-8542-430f-aa1b-38ffea90b4a5"
    in flowy_folder::manager::initialize_with_new_user
    in flowy_user::user_manager::manager::continue_sign_up
    in flowy_user::user_manager::manager::sign_up with authenticator: Local
    in flowy_user::event_handler::sign_up with email: 5a2b5bc9-4862-4f58-8b9b-58a766725e9a@appflowy.io, name: Me

{"msg":"[INITIALIZE - EVENT] Init workspace: eacd81f9-8542-430f-aa1b-38ffea90b4a5 from: LocalDisk","time":"06-06 11:32:39","target":"flowy_folder::manager_init","name":"Me","uid":334880165605675008,"workspace_id":"eacd81f9-8542-430f-aa1b-38ffea90b4a5","email":"5a2b5bc9-4862-4f58-8b9b-58a766725e9a@appflowy.io","authenticator":"Local"}
  2024-06-06 11:32:39  INFO flowy_user::services::db: open collab db for user 334880165605675008 at path: "C:\\Users\\nhtha\\AppData\\Roaming\\io.appflowy\\AppFlowy\\data_dev_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk/334880165605675008\\collab_db"
    at flowy-user\src\services\db.rs:203
    in flowy_folder::manager_init::initialize with uid: 334880165605675008, workspace_id: "eacd81f9-8542-430f-aa1b-38ffea90b4a5"
    in flowy_folder::manager::initialize_with_new_user
    in flowy_user::user_manager::manager::continue_sign_up
    in flowy_user::user_manager::manager::sign_up with authenticator: Local
    in flowy_user::event_handler::sign_up with email: 5a2b5bc9-4862-4f58-8b9b-58a766725e9a@appflowy.io, name: Me

{"msg":"[INITIALIZE - EVENT] open collab db for user 334880165605675008 at path: \"C:\\\\Users\\\\nhtha\\\\AppData\\\\Roaming\\\\io.appflowy\\\\AppFlowy\\\\data_dev_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk/334880165605675008\\\\collab_db\"","time":"06-06 11:32:39","target":"flowy_user::services::db","name":"Me","uid":334880165605675008,"workspace_id":"eacd81f9-8542-430f-aa1b-38ffea90b4a5","email":"5a2b5bc9-4862-4f58-8b9b-58a766725e9a@appflowy.io","authenticator":"Local"}
Lost connection to device.

Exited.
```

**Comment by annieappflowy** [comment]
@nhthanh719 , were you able to log in?
