### ISSUE TITLE
[FR] Download images and upload files

### ISSUE THREAD

**Issue by Somegirl111** [AppFlowy-IO/AppFlowy#5486]
### Description

Hi, I would like to request these features for your app
: upload files (pdf,txt,docx, etc.)
: download images(and other files) by viewing them and download like in Notion 

### Impact

It will be beneficial because some people want to upload files, Notion has that but only for 5 mb... same with images and videos. I also saw that saving images, makes the link to them get copied to clipboard...I think having a download feature like Notion would be better to download files.

**Comment by annieappflowy** [comment]
Supported
