### ISSUE TITLE
[Bug] Occasional glitching when adding checklist tasks

### ISSUE THREAD

**Issue by OctoShotG** [AppFlowy-IO/AppFlowy#5490]
### Bug Description

Random glitching when creating checklist tasks

### How to Reproduce

Attached video

### Expected Behavior

There is no grey rectangle appearing

### Operating System

Win11

### AppFlowy Version(s)

0.5.9

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/99288687/a308b1fa-e404-4545-82e8-303fe9ba7b9d

**Comment by annieappflowy** [comment]
The issue was fixed in [v0.6.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.0)
Feel free to reopen if it persists
