### ISSUE TITLE
[Bug] Ubuntu: 'AppFlowy: error while loading shared libraries: `libmpv.so.1`'

### ISSUE THREAD

**Issue by evdcush** [AppFlowy-IO/AppFlowy#5492]
### Bug Description

I recently upgraded my AppFlowy from `0.5.8` to `0.5.9`, using the `AppFlowy-0.5.9-linux-x86_64.deb` file published in Releases.

When I attempted to open the application from the desktop, nothing happened.

I then attempted to launch the app through the CLI, and received the following error:

```
AppFlowy: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

**It seems `0.5.9` has a new dependency on `libmpv1` package.**

I installed the package through apt:

```sh
sudo apt install libmpv1
```

I then was able to launch AppFlowy without problem.

### How to Reproduce

From the CLI:
```
sudo dpkg -i AppFlowy-0.5.9-linux-x86_64.deb

AppFlowy
```

### Expected Behavior

Application launches without issue, because the `.deb` installation also installs any new dependencies currently unavailable on the system.

### Operating System

`Ubuntu 22.04; 6.5.0-35-generic`

### AppFlowy Version(s)

0.5.9

**Comment by chxp** [comment]
`sudo apt install libmpv1` works for me

**Comment by seanradford** [comment]
libmpv1 is not available for Ubuntu 23.10 as superseded by libmpv2...

**Comment by ngirard** [comment]
@evdcush , could yo uplease reopen this issue ?

As @seanradford said, libmpv1 is not available any longer in recent Ubuntu versions.

**Comment by ngirard** [comment]
Thanks, @evdcush !
