### ISSUE TITLE
[bug] macos can not be built

### ISSUE THREAD

**Issue by lucasjinreal** [AppFlowy-IO/AppFlowy#5494]
vendor/appflowy/frontend/appflowy_flutter/macos/Pods/../Flutter/ephemeral/.symlinks/plugins/media_kit_libs_macos_video/macos/Frameworks/.symlinks/mpv/macos' not found
ld: framework 'Mpv' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

Building macOS application...
Error: Build process failed

**Comment by annieappflowy** [comment]
Please join our Discord [server](https://discord.gg/9Q2xaN37tV) for quick help
