### ISSUE TITLE
[Bug] Blank screen in 0.5.9 when loading with GDK_GL=gles 

### ISSUE THREAD

**Issue by Thrilleratplay** [AppFlowy-IO/AppFlowy#5497]
### Bug Description

When opening AppFlowy v 0.5.9, using either the application link or the command from the application link, `env GDK_GL=gles /usr/bin/AppFlowy %U`, AppFlowy opens but is blank.  If opening AppFlowy without the environmental flag, it opens but is very slow to render and visual artifacts are left such as titles from dialog boxes that had been closed.

The only difference between the logs when initially loading is when using GDK_GL there is an extra line before :

```
** (AppFlowy:12331): WARNING **: 11:04:30.274: Failed to link program: error: fragment shader lacks `main'
```

### How to Reproduce

1. Click the AppFlowy.desktop link or exec the command, `env GDK_GL=gles /usr/bin/AppFlowy %U` in a terminal.
2. Application opens but is blank. 
3. Close application
4. Execute the command `/usr/bin/AppFlowy %U`
5. Aplication opens and interface is visible but slow to render changes.

### Expected Behavior

AppFlowy to open with content appearing.

### Operating System

Linux

### AppFlowy Version(s)

0.5.9

### Additional Context

I installed AppFlowy via AUR using the [AppFlowy-bin](https://aur.archlinux.org/packages/appflowy-bin) package.  The package extracts the precompiled contents from the Debian package.  I have not tried compiling AppFlowy but will try that today.

I'm aware this is not a supported installed.  However, based on a comment in #5492, "The GUI glitches or goes black randomly.", I opened this as it may give more context for others that may be seeing a similar issue.  If it is not relevant, please feel free to close this.

**Comment by emmggi** [comment]
I also have this. Have also used `appflowy-bin` from AUR on Endeavour OS.

Running only `$ AppFlowy` in terminal works for me and is not slow to render changes.

**Comment by khorshuheng** [comment]
By any chance, was the Mesa package updated to version 24.1.1?

**Comment by Thrilleratplay** [comment]
> By any chance, was the Mesa package updated to version 24.1.1?

No, I do not have Mesa installed.

**Comment by emmggi** [comment]
> By any chance, was the Mesa package updated to version 24.1.1?

Yes. Mine is 24.1.1-1.

**Comment by imoize** [comment]
same issue, related to mesa 24.1.1-1 ?

**Comment by LucasXu0** [comment]
I will remove the environment variable GDK_GL=gles in the next version. However, the primary issue might be related to a recent update in Mesa, as this environment variable has been in place for quite some time.

> Aplication opens and interface is visible but slow to render changes.

This issue will also be fixed in the upcoming release.

**Comment by b-quentin** [comment]
> > By any chance, was the Mesa package updated to version 24.1.1?
> 
> Yes. Mine is 24.1.1-1.

Me too.

**Comment by b-quentin** [comment]
I downgraded this package but the problem persists
```
local/lib32-mesa 1:24.0.7-3
    Open-source OpenGL drivers - 32-bit
local/libva-mesa-driver 1:24.0.7-3
    Open-source VA-API drivers
local/mesa 1:24.0.7-3
    Open-source OpenGL drivers
```

**Comment by emmggi** [comment]
Downgrading to 23.1.1-1 (and rebooting) which was what I had before the upgrade, doesn't do any good either.

**Comment by Thrilleratplay** [comment]
I incorrectly thought I did not have Mesa installed (updated above), but have 21.3.9 installed.  This has not changed for me since January.  There may also be an issue with the latest Mesa version but it does not seem to be the only cause.

**Comment by b-quentin** [comment]
I tested with rofy with the terminal, I have the same problem but I was able to obtain logs

```
$ /tmp rofi -show drun -debug > with_rofi.log

(process:22792): Modes.Window-WARNING **: 21:36:25.616: Unsupported window field name :role. Wayland window switcher supports only 'title' and 'app-id' ('class') fields

(process:22792): Modes.Window-WARNING **: 21:36:25.616: Unsupported window field name :name. Wayland window switcher supports only 'title' and 'app-id' ('class') fields

(process:22792): Modes.Window-WARNING **: 21:36:25.616: Unsupported window field name :desktop. Wayland window switcher supports only 'title' and 'app-id' ('class') fields

(process:22792): Helpers.IconFetcher-WARNING **: 21:36:25.642: Failed to load image: |network.cycles.wdisplays| 23 23 Failed to open file “network.cycles.wdisplays”: No such file or directory ((nil))
$ /tmp
** (AppFlowy:22808): WARNING **: 21:36:27.885: Failed to link program: error: fragment shader lacks `main'
```

**Comment by LucasXu0** [comment]
FYI, I have removed the 'env' line from the .desktop file. It will be included in the upcoming version.
