### ISSUE TITLE
[Bug] Having a kanban board inside a document causes "/" commands to stop working.

### ISSUE THREAD

**Issue by Trixe-space** [AppFlowy-IO/AppFlowy#5501]
### Bug Description

Creating a kanban board with "/Create a new Board" or referencing one inside a document with "/Referenced Board" causes all "/" commands to stop working. The only way to fix it is to get rid of the referenced board. This does not effect grids and calendars.

### How to Reproduce

- Create a new document.
- Use "/Create a new Board" or "/Referenced Board" in that document.

### Expected Behavior

It should use the "/" properly.

### Operating System

Windows 11

### AppFlowy Version(s)

0.5.8, 0.5.9

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/121346649/a433d986-ae88-4123-8054-d8fcc1d2d199

**Comment by zoli** [comment]
This bug still exists and it's not only with board reference, create a grid reference focus on one of cells then focus on document you will see same problem.
What I've found is when [`keayboardService.disable()`](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/lib/src/editor/editor_component/service/keyboard_service_widget.dart#L115-L119) is called after slash command menu showing ([here](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/lib/src/editor/selection_menu/selection_menu_service.dart#L133)), Sometimes `DatabaseBlockComponentWidget` [`onFocusChange`](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart#L86-L90) is called which clears the selection and causes the problem of not being able to reference another board or grid.

**Comment by annieappflowy** [comment]
#6398
