### ISSUE TITLE
[FR] Content field for cards on mobile

### ISSUE THREAD

**Issue by IamSAB** [AppFlowy-IO/AppFlowy#5510]
### Description

On mobile, you can onlyn edit properties but not the content of a card (in kanban, list or calendar). On desktop, this is possible.

### Impact

Edit content on mobile. Structured text for cards on all devices.

### Additional Context

Win10 App
![grafik](https://github.com/AppFlowy-IO/AppFlowy/assets/8931240/2dce3de4-ce1c-4a16-b045-3234ca788aae)

Android App
![threema-20240610-202428515](https://github.com/AppFlowy-IO/AppFlowy/assets/8931240/56331aed-d54d-49dc-8089-f9973691fd78)

**Comment by emmggi** [comment]
+1 to this. I was wondering why the field is missing on mobile.

Could it be that it's missing only on the v7a apk?

**Comment by annieappflowy** [comment]
This is not supported yet on mobile. We plan to work on it this month.

**Comment by annieappflowy** [comment]
https://github.com/user-attachments/assets/19c782b2-933c-4d5f-ad83-a737bf60cc11

Supporting it in v0.6.8
