### ISSUE TITLE
[Bug] Broken underline style when adding an underline to a piece of text containing Chinese, English and numbers

### ISSUE THREAD

**Issue by curlykay** [AppFlowy-IO/AppFlowy#5514]
### Bug Description

When I add an underline to a paragraph of text containing Chinese, English and numbers, the underline style is broken.

### How to Reproduce

Select a section of text containing Chinese, English and numbers and add an underline.

### Expected Behavior

Add an underline to a paragraph of text containing Chinese, English and numbers, the underline should be a continuous straight line

### Operating System

macos 14.2.1

### AppFlowy Version(s)

0.5.8

### Screenshots

<img width="740" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/35558285/71d92ccc-f386-4b08-ba91-5f0c2c8c2fbb">

<img width="392" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/35558285/952b3668-6ca4-4d4c-8771-29b76d4810f3">

**Comment by annieappflowy** [comment]
<img width="177" alt="image" src="https://github.com/user-attachments/assets/89102d99-5815-457d-b04a-1eda14a4a139">

Should work as desired
