### ISSUE TITLE
[Bug] When Version 0.5.9 is installed for the first time, an error occurs when switching languages after startup

### ISSUE THREAD

**Issue by Saber-CC** [AppFlowy-IO/AppFlowy#5516]
### Bug Description

When Version 0.5.9 is installed for the first time, an error occurs when switching languages after startup. Cause of error:Unable to load asset:"asset/translations/zh-CN.json".
<img width="836" alt="iShot_2024-06-11_16 35 54" src="https://github.com/AppFlowy-IO/AppFlowy/assets/49194769/d3478dd7-970c-4436-ad96-e711b18ec9a1">

### How to Reproduce

Uninstall AppFlowy completely on macos and then install version 0.5.9 of AppFlowy, switching language to Simplified Chinese

### Expected Behavior

normal use

### Operating System

MacOS

### AppFlowy Version(s)

0.5.9

**Comment by annieappflowy** [comment]
Unable to reproduce with the latest release (v0.7.0)
