### ISSUE TITLE
[Bug] The interface is buggy since version 0.5.9-3

### ISSUE THREAD

**Issue by b-quentin** [AppFlowy-IO/AppFlowy#5519]
### Bug Description

Hello,

I am under Arch Linux with hyprland, and since I updated appflowy on version 0.5.9-3 the application interface no longer works, but when I launch appflowy from the terminal, the interface works correctly.

### How to Reproduce

With Archcraft linux and hyprland launch the app with rofi launcher.

### Expected Behavior

When I launch the appflowy I have the interface that works without using the terminal.

### Operating System

Archcraft

### AppFlowy Version(s)

0.5.9-3

### Screenshots

![2024-06-11_17-08](https://github.com/AppFlowy-IO/AppFlowy/assets/31655487/c70d9b4e-917d-45ba-a450-3d2c407ef789)

**Comment by emmggi** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/5497

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/AppFlowy/pull/5564

**Comment by annieappflowy** [comment]
This issue was fixed. Please try out the latest release ([v0.6.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.0)).
