### ISSUE TITLE
[Bug] Fail to build at main branch, version 093c637

### ISSUE THREAD

**Issue by ENsu** [AppFlowy-IO/AppFlowy#552]
**Describe the bug**
I try to build the latest version of AppFlowy codebase but failed with many code issues.

**To Reproduce**
1. I updated my Flutter to 3.0 and run Flutter doctor and pass the test.
2. I run make `flowy_dev_install` under the `/frontend` folder without error.
3. I also run the Build Task under the `/frontend` folder without error.
4. Then I run the Run and Debug using AF: Clean + Rebuild All as suggested
However, I got many issues in the code, VS code popup with `Build errors exist in your project.`

**Expected behavior**
Run successfully and generate an AppFlowy desktop build.

**Screenshots**
![image](https://user-images.githubusercontent.com/5762483/173722182-0137ca3e-a185-4684-bdab-a47cdff24b79.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey with Apple Chip 
 - Version 12.3.1
 
 **Environment**
 - Flutter: Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale en-TW)
 - Rust: rustc 1.61.0 (fe5b13d68 2022-05-18)

**Comment by appflowy** [comment]
I noticed that the AF: Clean + Rebuild doesn't clean the flutter side cache. Run `flutter clean` in frontend/app_flowy, and then try again the AF: Clean + Rebuild.

**Comment by ENsu** [comment]
I believe the new PR has resolved the problem.
