### ISSUE TITLE
[Bug] Low res screen "Add Date" is missing 

### ISSUE THREAD

**Issue by ForeverLiveArt** [AppFlowy-IO/AppFlowy#5521]
### Bug Description

On a lower resolution screen there is impossible to add a date and other options. It should be scrollable on a horizontal scroll i suppose, so it's possible to see other options on a smaller screen. 

### How to Reproduce

Reduce screen resolution and press plus sign to add element. There are no ability to pick "Add Date" or some other elements, as they not visible and not scrollable

### Expected Behavior

It should be scrollable

### Operating System

Mac OS

### AppFlowy Version(s)

0.5.5

### Screenshots

<img width="949" alt="Screenshot 2024-06-11 at 5 19 19 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/38789044/94ba41cf-7f4d-4852-a086-b4e12150169a">

**Comment by apomalyn** [comment]
Hi @ForeverLiveArt 
Thakn you for reporting this. I agree with you, this menu isn't optimal for smaller screens. 

I think we could go with a classic dropdown list with an autocomplete like is experimenting.

<details><summary>Example</summary>

https://github.com/AppFlowy-IO/AppFlowy/assets/22211097/4076d1aa-c7d2-439f-84d2-f17596e960e8

</details>
