### ISSUE TITLE
[Bug] Find in doc

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5548]
### Bug Description

Enter doesn't go to the next match; instead, it deletes the matched keyword in the doc

### How to Reproduce

Use Find to highlight all the matched keywords
Try to use Enter to navigate

### Expected Behavior

Should work as expected

### Operating System

macOS

### AppFlowy Version(s)

v0.6.0

**Comment by MayurSMahajan** [comment]
Similar to: #5491.
Don't close this issue as a duplicate though, because the description in #5491 is a bit vague.
