### ISSUE TITLE
[FR] multiple images / columns

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5557]
### Description

Also in documents, u can put only 1 image at a place, and even if u resize it small you cant use free space to write or put another image..  the image takes a portion of the document regardless of its size.. it would be nice to be able to put multiple images side by side or just use that space for writing

### Impact

Doc users

**Comment by emmggi** [comment]
This could be achieved by creating an album of images as suggested in https://github.com/AppFlowy-IO/AppFlowy/issues/2947
