### ISSUE TITLE
[Bug] Mobile editor toolbar height issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#5573]
### Bug Description

Mobile editor toolbar height issue

### How to Reproduce

Huawei mate40 pro 

### Expected Behavior

Toolbar position is normal

### Operating System

mobile

### AppFlowy Version(s)

main

### Screenshots

![WechatIMG8](https://github.com/AppFlowy-IO/AppFlowy/assets/4517301/b21b54dd-62b8-4cb4-94f0-593f6c80d8e6)

**Comment by q200892907** [comment]
final height = MediaQuery.of(context).viewInsets.bottom;
Consider using it in combination
@LucasXu0

**Comment by LucasXu0** [comment]
<img width="653" alt="Screenshot 2024-06-19 at 16 55 46" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/bab992d9-3260-4530-9ab5-9d76ef1e3543">

@q200892907 I have added the keyboard height to viewPadding.bottom. Does it not work?

**Comment by q200892907** [comment]
> <img alt="截图 2024-06-19 16 55 46" width="653" src="https://private-user-images.githubusercontent.com/11863087/341000023-bab992d9-3260-4530-9ab5-9d76ef1e3543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODg3ODIsIm5iZiI6MTcxODc4ODQ4MiwicGF0aCI6Ii8xMTg2MzA4Ny8zNDEwMDAwMjMtYmFiOTkyZDktMzI2MC00NTMwLTlhYjUtOWQ3NmVmMWUzNTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA5MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMzM3ODE5YWJjZWI2ZGUzZTJjZDViYmYxMWRlNzc2YTFiMTRjNWFkZWZmYmM4MzFmZTdlMDkxNTRiZjcxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ienj3zAccaCoqF6rt0VUWS4yKkO0LxKunQwCHsMt94Q">
> @q200892907我已将键盘高度添加到 viewPadding.bottom。这不起作用吗？

@LucasXu0 Didn't work

**Comment by q200892907** [comment]
keyboard_height_plugin:
    git: https://github.com/q200892907/keyboard_height_plugin.git
I forked the plugin and modified it, and it works on the phone with the problem

**Comment by LucasXu0** [comment]
I noticed that you submitted a PR to the official repo already. If it's merged, you can submit a PR to upgrade the keyboard_height_plugin dependency.

**Comment by q200892907** [comment]
> 我注意到您已经向官方仓库提交了 PR。如果已合并，您可以提交 PR 来升级`keyboard_height_plugin`依赖项。

OK, I will follow the information of keyboard_height_plugin

**Comment by LucasXu0** [comment]
@q200892907 Could you confirm that your PR has fixed the blocking toolbar issue?

**Comment by LucasXu0** [comment]
I tried your PR. The API still doesn't return the correct keyboard height. You can check my screenshot.

<img width="842" alt="Screenshot 2024-07-05 at 10 56 03" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/5c24b4c4-84d0-4a4b-9c93-4f6e524c08d4">

**Comment by q200892907** [comment]
@LucasXu0 Xiaomi, Huawei, I can test the hand with the bottom toolbar of the phone test no problem
