### ISSUE TITLE
[Bug] Not all keyboard keys work when typing in kanban boards

### ISSUE THREAD

**Issue by SOSeriously** [AppFlowy-IO/AppFlowy#5577]
### Bug Description

- Backspace does not work when renaming an existing card.
- Backspace does not work when entering a name for a new card.
- When adding a new kanban group some of the keys does not work: 
   Backspace
   enter
   e
   n
   ,
   .

There may be more keys not responding.
This only happens in kanban boards. The keyboards works correctly when typing in a document.

### How to Reproduce

- Create a new kanban board
- Add new card or rename existing card
- Add new group

### Expected Behavior

All keys should respond when typing

### Operating System

Windows 11 Pro 23H2

### AppFlowy Version(s)

v0.5.9

**Comment by annieappflowy** [comment]
Please try out with the latest release ([v0.6.0](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.0)). This issue was fixed.
