### ISSUE TITLE
[Bug] Two private spaces + not visible font color in private space name

### ISSUE THREAD

**Issue by dungeon-slave** [AppFlowy-IO/AppFlowy#5578]
### Bug Description

I have two private spaces on linux

### How to Reproduce

Open AppFlowy and check spaces in left sidebar

### Expected Behavior

I expect to have one private space)

### Operating System

Linux Mint 21.3 with Cinnamon and X11

### AppFlowy Version(s)

0.6.0

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/70040363/0fd1be57-ca63-4bb4-86b9-6172ea228a3f)

### Additional Context

Log out and clean cache, problem is still here

**Comment by annieappflowy** [comment]
You can create as many public / private spaces as you want. 
If you don't need another private space, you can click on the dot menu next to the space name and delete it.
<img width="500" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/01366159-c29a-4be0-8276-5c32ae489ac3">

We'll investigate into this duplicate space issue.

**Comment by dungeon-slave** [comment]
> You can create as many public / private spaces as you want. If you don't need another private space, you can click on the dot menu next to the space name and delete it. <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/12026239/341093965-01366159-c29a-4be0-8276-5c32ae489ac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Mjc0MTcsIm5iZiI6MTcxODgyNzExNywicGF0aCI6Ii8xMjAyNjIzOS8zNDEwOTM5NjUtMDEzNjYxNTktYzI5YS00YmUwLTgyNzYtNWMzMmFlNDg5YWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE5NTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjc2OGY5YWQ4ODJjNzY3YTgzZTI1NTE2ZDE5MjM2MWVjNTY0ODRmNzM1ZTI1MWYxMmU4M2RkYzM4MTJiMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRTQtbGDUfsPWLLaTtrGZ4pr8tJN4IUt4QDt_fIOKL4">
> 
> We'll investigate into this duplicate space issue.

Thank you for the response! Yeah, i know this, problem is that this two spaces have similar pages and if i delete one, then all my pages deleted also from another :(

**Comment by LucasXu0** [comment]
@dungeon-slave You can restore the deleted page from the trash bin first. I'm checking the migrate steps. Did it happen when you launch the app first time?

**Comment by dungeon-slave** [comment]
Yeah, i update app (i use .deb format) and then this happens

**Comment by dungeon-slave** [comment]
i also check this issues on my x86 macbook, and with two private spaces still here, but font color is normal, there is no issues with it

**Comment by LucasXu0** [comment]
@dungeon-slave By the way, are the pages in these two spaces the same?

**Comment by dungeon-slave** [comment]
Yeah, they are same

**Comment by dungeon-slave** [comment]
I try it now, second became empty. I'll try now create one more different private space, move all pages here and delete these buggy privates)

**Comment by LucasXu0** [comment]
@dungeon-slave FYI, We're going to release the "duplicate space" feature in the upcoming version. Please keep your current pages, then you can duplicate all of them and delete these two duplicated spaces.

**Comment by dungeon-slave** [comment]
Okay, thank you!

**Comment by annieappflowy** [comment]
@dungeon-slave , was this issue resolved? Please feel free to reopen if you need more help.
