### ISSUE TITLE
[Bug] Wrong selection in sidebar

### ISSUE THREAD

**Issue by dungeon-slave** [AppFlowy-IO/AppFlowy#5579]
### Bug Description

If i click on pages in sidebar one by one, then all of them showed as selected

### How to Reproduce

Open sidebar in private space and click in pages one by one

### Expected Behavior

I think only current should be selected

### Operating System

Linux Mint 21.3 with Cinnamon and X11

### AppFlowy Version(s)

0.6.0

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/70040363/b3c58017-1b4a-437c-8827-3c4c1f0ef53e)

**Comment by LucasXu0** [comment]
@dungeon-slave Did you use the custom theme?

**Comment by annieappflowy** [comment]
I think it's Dandelion
<img width="476" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/fe72514f-35d7-46df-afa0-a8105e28706e">

**Comment by dungeon-slave** [comment]
I use built-in theme, lemonade probably, can't say exactly now

**Comment by dungeon-slave** [comment]
Additional info to this bug: on x86 macbook i cant reproduce it, its only happens on linux

**Comment by Xazin** [comment]
I can reproduce on windows and found the cause, I've assigned Lucas and message him about the cause.

**Comment by dungeon-slave** [comment]
Issue no longer exist)
