### ISSUE TITLE
[Bug] Black screen in 6.0

### ISSUE THREAD

**Issue by drakenlie024** [AppFlowy-IO/AppFlowy#5582]
### Bug Description

the app open with a black screen, its possible to click on things but nothing appears 

### How to Reproduce

Just open the app

### Expected Behavior

See the app

### Operating System

WIN 11

### AppFlowy Version(s)

6.0

### Additional Context

computerName: FRANCISCO
numberOfCores: 8
systemMemoryInMegabytes: 12288
userName: Francisco
majorVersion: 10
minorVersion: 0
buildNumber: 22631
platformId: 2
csdVersion: 
servicePackMajor: 0
servicePackMinor: 0
suitMask: 256
productType: 1
reserved: 0
buildLab: 22621.ni_release.220506-1250
buildLabEx: 22621.1.amd64fre.ni_release.220506-1250
digitalProductId: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 92, 92, 63, 92, 67, 58, 92, 85, 115, 101, 114, 115, 92, 70, 114, 97, 110, 99, 105, 115, 99, 111, 92, 65, 112, 112, 68, 97, 116, 97, 92, 82, 111, 97, 109, 105, 110, 103, 92, 105, 111, 46, 97, 112, 112, 102, 108, 111, 119, 121, 92, 65, 112, 112, 70, 108, 111, 119, 121, 92, 100, 97, 116, 97, 95, 97, 72, 82, 48, 99, 72, 77, 54, 76, 121, 57, 105, 90, 88, 82, 104, 76, 109, 70, 119, 99, 71, 90, 115, 98, 51, 100, 53, 76, 109, 78, 115, 98, 51, 86, 107, 92, 51, 50, 54, 55, 57, 52, 51, 50, 54, 49, 48, 55, 52, 57, 50, 51, 53, 50, 92, 105, 110, 100, 101, 120, 101, 115, 92, 102, 111, 108, 100, 101, 114, 95, 105, 110, 100, 101, 120, 92, 109, 101, 116, 97, 46, 106]
displayVersion: 23H2
editionId: Professional
installDate: 2024-04-11 17:34:01.000
productId: 00330-80000-00000-AA988
productName: Windows 11 Pro
registeredOwner: Francisco
releaseId: 2009
deviceId: {B47E5735-7C00-4A81-AF89-123D96700D66}
Document: C:\Users\Francisco\AppData\Roaming\io.appflowy\AppFlowy\data

**Comment by suntorytimed** [comment]
can confirm the black screen on Linux with the latest flatpak as well

**Comment by annieappflowy** [comment]
Are you guys still having this issue with the latest release?
