### ISSUE TITLE
[Bug] Black screen after second launch [LINUX][FLATPAK][WAYLAND]

### ISSUE THREAD

**Issue by AxelSkye** [AppFlowy-IO/AppFlowy#5583]
### Bug Description

On first launch everything works fine, but once the app is closed if I try to launch it again I get a black screen, just the titlebar works. The only way to open it is to fully remove it and install it again (only working for one single launch).

### How to Reproduce

1. Install the app from Flathub.
2. Run it
3. First launch is okay
4. Close it
5. Open it again
6. Black screen

### Expected Behavior

The content should be seen

### Operating System

Linux - openSUSE Aeon, Gnome Desktop, Wayland session

### AppFlowy Version(s)

0.6.0

### Screenshots

![Captura desde 2024-06-19 21-35-34](https://github.com/AppFlowy-IO/AppFlowy/assets/31951244/efe1a7a2-5a21-451c-83b7-689081a3683a)

**Comment by LucasXu0** [comment]
@AxelSkye Any outputs from the terminal when you launch the flatpak?

**Comment by HeathenHacks** [comment]
Same thing happening on the Flatpak version on X11.

It launches just fine using the terminal, but it's saying these:

```
Gtk-Message: 15:26:37.612: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:26:37.612: Failed to load module "appmenu-gtk-module"

** (AppFlowy:2): CRITICAL **: 15:26:37.755: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

Not sure if these would be useful, since I did not connect any cloud accounts to it nor use AI, but, here are some more errors that might be related to it:

ERROR client_api::http: error: code:NotLoggedIn msg: Not Logged In:token is empty

ERROR flowy_user::user_manager::manager_user_workspace: error: NotSupportYet: Not support yet

ERROR flowy_user::event_handler: error: NotSupportYet: Not support yet

ERROR flowy_folder::manager: Can't find the view with id:

ERROR flowy_folder::event_handler: error: RecordNotFound: Record not found



```

**Comment by LucasXu0** [comment]
@HeathenHacks The error message doesn't matter if you didn't log in.

**Comment by HeathenHacks** [comment]
i see. how about the error mentioning gtk-modules and XDG desktop portal?

**Comment by suntorytimed** [comment]
#5582 mentions this issue with Windows 11 as well. I can confirm it with Flatpak on openSUSE Tumbleweed running GNOME, but it doesn't happen at every start.

**Comment by AxelSkye** [comment]
> @AxelSkye Any outputs from the terminal when you launch the flatpak?

I think that the relevant error I get is this:

** (AppFlowy:2): WARNING **: 18:25:17.322: Failed to link program: error: fragment shader lacks `main'

**Comment by LucasXu0** [comment]
https://github.com/flathub/io.appflowy.AppFlowy/pull/109

FYI, I have removed the OpenGL env in Flatpak. Updating to the latest version should fix the black screen issue.
