### ISSUE TITLE
[Bug] Too narrow sidebar in settings

### ISSUE THREAD

**Issue by suntorytimed** [AppFlowy-IO/AppFlowy#5589]
### Bug Description

The sidebar in the settings is too narrow to show all of the text

### How to Reproduce

Run AppFlowy 0.6.0 in German translation

### Expected Behavior

sidebar is wider to show all of the text

### Operating System

openSUSE Tumbleweed

### AppFlowy Version(s)

0.6.0

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/2744377/897bbd30-54f0-42f9-b5d1-4e14d623143a)

**Comment by Xazin** [comment]
I believe we improved this but forgot to close.

Will close as completed now, if this is still an issue please open a new report 🙏👍
