### ISSUE TITLE
[Bug] Neither Favorites and Spaces are displayed in sidebar

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#5595]
### Bug Description

I've just updated to 0.6.0, then 0.6.1...

I know, I'm launching AppFlowy on unsupported OS, but...

UPD. There are no Favorites section, beacuse none note is starred. Yes?

But how to create Spaces?

### How to Reproduce

🤷‍♂️ 

### Expected Behavior

Get full-functioning sidebar.

### Operating System

Win 8.1 x64

### AppFlowy Version(s)

0.6.1

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/7080928/14fd0fe7-0933-48ed-a87d-28978169389f)

**Comment by annieappflowy** [comment]
Hi @Twilightssuperb , 

- There are no Favorites section, beacuse none note is starred. Yes? Yes
- Since Spaces require permissions (either private or public), it's not available in the local mode.
