### ISSUE TITLE
[Help]: Debug Linux Build

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/appflowy#56]
We have a half-baked Linux Build with some issues: some icons are missing.
![image](https://user-images.githubusercontent.com/86001920/142748349-42150dd0-d4f2-46eb-938c-d91f7721eb31.png)

So I want to debug on Ubuntu, but I'm having trouble debugging on Linux. Every time I'm on debug mode, the build process gets stuck, and my system becomes frozen.

At this point, I've come to a decision to focus on higher ROI work and put this one on hold, unfortunately. As a team of two, we have to keep going, and there are many important tasks on our plate. I'd like to make a call out here for help with this issue. Anyone interested in this can take it from where it's left out. 

Debug environment setup:
Step 1: 
Follow the instructions on https://github.com/AppFlowy-IO/appflowy/blob/main/doc/BUILD_ON_LINUX.md

Step 2:
open the frontend/scripts/build_sdk.sh, comment out the command based on your system.

![image](https://user-images.githubusercontent.com/86001920/142750345-6d81bdab-2b6e-4cd8-81b9-cc0d23d7f036.png)

```shell
# for macos
#cargo make --profile development-mac flowy-sdk-dev

# for window
#cargo make --profile development-windows flowy-sdk-dev


# for linux amd64
#cargo make --profile development-linux-x86 flowy-sdk-dev

# for linux aarch64
#cargo make --profile development-linux-aarch64 flowy-sdk-dev
```

Step 3:
open frontend/app_flowy with vs code.
![image](https://user-images.githubusercontent.com/86001920/142750352-597a08ba-8a2b-4ec4-92eb-ac0abd1dc3b8.png)

**Comment by notd5a-alt** [comment]
Im on Arch but i can try and see if the same issues arise there as well. If they do ill try and patch them.

**Comment by RaghaVdot24** [comment]
I'm on Ubuntu. Will try running this

**Comment by notd5a-alt** [comment]
Ok. From what i can deduce, this seems to be a weird path capitalization issue with the icons.
For example: Flutter tries to load `assets/images/home/trash.svg` but the icon name is actually capitalized i.e. Trash.svg
The Error Thrown:
> `Unable to load asset: assets/images/editor/bold.svg`
What its affecting:
- trash.svg
- add.svg
- bold.svg
- italic.svg
- underline.svg
- strikethrough.svg
- numbers.svg
- checkbox.svg
- quote.svg
- share.svg
Simply changing the icon names from: `Trash.svg` to `trash.svg` seems to fix this issue.

**Comment by Silcet** [comment]
I just managed to get AppFlowy running for the first time on a Manjaro (Arch Linux) distro. I can see that some of the icons are missing as mentioned before. I did my build based on main branch. I'll continue debugging a bit, but so far I got this screenshot in case it helps someone else:
![image](https://user-images.githubusercontent.com/11076250/142915324-b50238e3-7a87-43c3-aa3d-e086f13f3a19.png)

**Comment by Laegel** [comment]
Hey, just tried to run it on my machine (**Ubuntu 20.04, x86_64**) and everything went well.
In my case, I already had Rust installed and didn't go through the optional steps.
I first checked it was building fine using the `cargo make -p development-linux-x86 appflowy-linux-dev` command.
As there was nothing wrong here, I went through steps 2 and 3 to install the debug environment and it was also working just fine:

![image](https://user-images.githubusercontent.com/3584791/143026689-62896995-0ea5-4358-bf38-1c2f580358eb.png)

Did you have trouble to make it run on this specific Ubuntu too or just the aarch64 architecture?
Do you want me to update the verified systems list?

**Comment by pdckxd** [comment]
I am experience same issue when running debug version of appflowy on lubuntu 20.04 . Looks like this is flutter issus specific for Linux.

**Comment by notd5a-alt** [comment]
So changing icon names and refs didnt fix the issue? Maybe an underlying flutter issue. Ill research and check.

**Comment by pdckxd** [comment]
> So changing icon names and refs didnt fix the issue? Maybe an underlying flutter issue. Ill research and check.

I mean debug version of appflowy prevents people from typing. Sorry for confusion.

**Comment by notd5a-alt** [comment]
Ah ok

**Comment by irfanbacker** [comment]
> I mean debug version of appflowy prevents people from typing. Sorry for confusion.

No issue for me on Pop!_OS 21.04 on both production and development builds

**Comment by annieappflowy** [comment]
Thank you all. Closing this issue as it's resolved.
