### ISSUE TITLE
[Bug] 0.6.1. Blank Page on startup, Windows 10

### ISSUE THREAD

**Issue by Alaztor10** [AppFlowy-IO/AppFlowy#5602]
### Bug Description

Using standalone .zip for windows, when running the setup always show blank page. Help & Support icon is visible and works as intended

### How to Reproduce

Run standalone version from [AppFlowy-0.6.1-windows-x86_64.zip](https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.1/AppFlowy-0.6.1-windows-x86_64.zip)

### Expected Behavior

Running application should default into frontpage UI for appFlowy, not a full screened blank page

### Operating System

Windows 10

### AppFlowy Version(s)

0.6.1

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/81707734/b1d4e219-2f08-4aff-b325-d3855af9f460)

**Comment by annieappflowy** [comment]
Did you have more than 1 AppFlowy running?

**Comment by Alaztor10** [comment]
> Did you have more than 1 AppFlowy running?

No, singular app instance running.  Tried it with a fresh computer restart, issue still persisted
