### ISSUE TITLE
[Bug] Wrong width of section selection menu

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#5609]
### Bug Description

All is in the title and visible in the screenshot

### How to Reproduce

Have multiple long section name.

Go to the switch section button, and see the the result

### Expected Behavior

The width should be of the width of the longest item.

### Operating System

MacOS

### AppFlowy Version(s)

0.61.0

### Screenshots

<img width="332" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/4645967/83a40906-330f-4469-94c6-ce3b42e07d25">

**Comment by emmggi** [comment]
There's also this text overflow in the popover of the More menu under Favorites on Linux.
