### ISSUE TITLE
[Bug] Sync status is gone

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#5614]
### Bug Description

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/166f372b-980b-41a6-a243-8a5350d867ba)

### How to Reproduce

open the appflowy

### Expected Behavior

You can see the synchronization status like in previous versions

### Operating System

mac

### AppFlowy Version(s)

0.6.1, 0.6.0

**Comment by SteffeyDev** [comment]
I'm a new user and didn't know there used to be a sync status, but coming here to say that I would appreciate seeing a sync status on MacOS as well, when using self-hosted cloud. I'm using 0.6.7 now

**Comment by appflowy** [comment]
@SteffeyDev We have removed the sync icon and are currently refactoring our syncing protocol to enhance its reliability and functionality. As part of this process, we will revisit and improve the sync icon logic to make it more robust and consistent. For now, I will close this bug.
