### ISSUE TITLE
[FR] Move page to another space

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#5625]
### Description

Since the integration of space, I have multiple space and I would like to move page from default space, to my new space.

### Impact

Permit to migrate easily from space A to space B.

### Additional Context

<img width="622" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/4645967/c14f4022-1a70-41c3-a361-2dd6e8be4f9a">

**Comment by LucasXu0** [comment]
I believe that is what you need: https://github.com/AppFlowy-IO/AppFlowy/pull/5618

It will be included in the upcoming release.

**Comment by henri9813** [comment]
You are the goat
