### ISSUE TITLE
[Bug] Missplaced icon in callout

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#5626]
### Bug Description

The icon is not correctly placed.

### How to Reproduce

Create a callout.

Look the pinto.

### Expected Behavior

The picto should be vertically centered.

### Operating System

MacOS

### AppFlowy Version(s)

0.6.1

### Screenshots

<img width="235" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/4645967/0ebd480a-b049-4d41-a3e6-b6d85404d356">

**Comment by annieappflowy** [comment]
<img width="160" alt="image" src="https://github.com/user-attachments/assets/5c800370-32d5-4244-96ff-076da3b4b29c">
