### ISSUE TITLE
[Bug] Typing text inside a code span is not anymore in "code mode"

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#5629]
### Bug Description

Typing text inside a code span is not anymore in "code mode"

### How to Reproduce

Type somehing in code mode

such as:
`awesome word`.

Then, type letters between the already placed code. The text is not in code mode

### Expected Behavior

The text should be in code mode.

### Operating System

MacOS

### AppFlowy Version(s)

0.6.1

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/4645967/a47c4fc6-05d2-4f06-8872-86d29a21e59f

### Additional Context

Sorry, but it's hard to do a bug summary of this

**Comment by annieappflowy** [comment]
Fixed in the upcoming release (v0.6.2)
