### ISSUE TITLE
[Bug] Text overflow in Group title when group by date and week condition

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#5636]
### Bug Description

When grouping by date and selecting the "Week" group condition, the copy is quite long which can cause the title to overflow.

We should find a better copy that is shorter but retains the meaning.

### How to Reproduce

-

### Expected Behavior

-

### Operating System

all

### AppFlowy Version(s)

0.6.0

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/fb7f798c-c635-4c11-b137-2e1c3701ddfb)

**Comment by MayurSMahajan** [comment]
Should we remove the phrase "Week of" and just keep the date instead?

**Comment by annieappflowy** [comment]
Hover on the group name -> Display the full name
