### ISSUE TITLE
[Bug] The status is clipping in board cards on mobile

### ISSUE THREAD

**Issue by SOSeriously** [AppFlowy-IO/AppFlowy#5642]
### Bug Description

The status is clipping in board cards on mobile

![Screenshot 2024-06-27 123653](https://github.com/AppFlowy-IO/AppFlowy/assets/18901536/9a1700e1-047d-41b3-8099-5e3a12383024)

### How to Reproduce

Create a new board card
Set a status for the card

### Expected Behavior

The text of the status should not clip

### Operating System

Android 14

### AppFlowy Version(s)

v0.6.1

**Comment by LucasXu0** [comment]
Fixed in v0.6.2
