### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ben5220** [AppFlowy-IO/AppFlowy#5647]
### Bug Description

Desktop - When I upload a cover picture it doesn't appear until I upload it again.
iOS - some items entered in the calendar on the desktop show up as undated.

### How to Reproduce

Upload a picture from the computer. I have an iMac running MacOs 10.15.7, yes I have an old iMac.
Enter information in the calendar on the desktop in several different days and look for it in the mobile app.

### Expected Behavior

I expected the picture to show up immediately like it does in Notion.
I notice differences in information entered into the desktop and iOs. 

### Operating System

MacOs 10.15.7 and iOS 17.5.1

### AppFlowy Version(s)

Version 0.6.1 (0.6.1)

**Comment by annieappflowy** [comment]
> I expected the picture to show up immediately like it does in Notion.
It works as desired at least with v0.7.0 on macOS.

> I notice differences in information entered into the desktop and iOS.
We're improving the syncing service. In the meantime, a quick fix is to keep the page open on the device where you made the latest updates until the data syncs to the other device.
