### ISSUE TITLE
[FR] Keyboard shortcut to open search

### ISSUE THREAD

**Issue by SOSeriously** [AppFlowy-IO/AppFlowy#5658]
### Description

Could you please add a keyboard shortcut to open search.
Default shortcut: ctrl + f

### Impact

People who uses search a lot.

**Comment by annieappflowy** [comment]
Enter the edit mode in the doc, cmd / ctrl + f to open find and replace
Cmd + p to open up the workspace search

**Comment by SOSeriously** [comment]
Thank you. The shortcuts for find and replace and workspace search does not show in the documentation under Shortcuts Guide  (https://docs.appflowy.io/docs/appflowy/product/shortcuts) and doesn't show in settings > shortcuts.

**Comment by MayurSMahajan** [comment]
I have added the shortcuts to the documentation, you may close this issue, if you are satisfied @annieappflowy.
