### ISSUE TITLE
[Bug] copy paste bug in a bulleted list

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5661]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/23ecc9ce-7601-4d9f-a9c3-33f63ea077ac

### How to Reproduce

refer to the video

### Expected Behavior

don't overwrite content

### Operating System

macOS

### AppFlowy Version(s)

v0.6.2

**Comment by emmggi** [comment]
@annieappflowy This should be closed with this commit, no? https://github.com/AppFlowy-IO/AppFlowy/pull/5917
