### ISSUE TITLE
[FR] Improve Selection Menu's appearance

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#5667]
### Description

- The Selection Menu has a lot of options, 21 to be precise. 
A lot of these options consume multiple lines and thus their padding is insufficient. They look congested.

<details>
 <summary>
    See Screenshot
 </summary>
  <img width="300" alt="congested-selection-menu" src="https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/040c6c71-7cf8-4e82-b82d-760d64e7a9a5">
</details>

- The Selection Menu takes a lot of space and sometimes goes out of window which causes Accessibility issues 

<details>
 <summary>
    See Screenshot
 </summary>
<img width="800" alt="Screenshot 2024-07-01 at 4 31 35 PM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/aae8b6b6-50b9-4146-b16d-e1d779497059">

> Note how the selection menu here goes out of the window.
</details>

--- 

### Possible Solution:

<details>
 <summary>
    My two cents
 </summary>
Nest some of selection menu items: 

Heading: h1, h2, h3
List: Bulleted, Numbered, Checkbox
Database: Grid, Board, Calendar, Referenced Grid, Referenced Board, Referenced Calendar, Referenced Document
Blocks: Codeblock, Math Equation, Quote, Outline, Table, Divider
etc
</details>

### Impact

Everyone who uses the Selection Menu often will have a better experience.

### Additional Context

Now this Selection Menu going out of the window is an old issue, and I remember it being solved, but probably it has resurfaced after the Zoom In and Zoom Out feature.

**Comment by emmggi** [comment]
Nesting like this is a good suggestion

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/45419292/0d838b58-9804-4958-a7cf-98165974e72e)

**Comment by MayurSMahajan** [comment]
It looks like the team has redesigned the selection menu from 0.6.6. Thus closing this issue.
