### ISSUE TITLE
[Bug] iOS App - No names of statuses appearing

### ISSUE THREAD

**Issue by OctoShotG** [AppFlowy-IO/AppFlowy#5669]
### Bug Description

Specifically, running iOS app on iPad
The names of statuses aren’t showing up, only the colours
<img width="1080" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/99288687/5bc9b255-3d97-4bff-ba41-0e0208a791d9">
<img width="1080" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/99288687/0249b916-5273-45d6-ab40-3acc9cb0242f">

### How to Reproduce

Edit status of task in Kanban board

### Expected Behavior

Names show up

### Operating System

iPadOS 17.5.1

### AppFlowy Version(s)

0.6.1

**Comment by LucasXu0** [comment]
Fixed in v0.6.2.
