### ISSUE TITLE
Themed/Monochrome App Icon

### ISSUE THREAD

**Issue by NielSync** [AppFlowy-IO/AppFlowy#5678]
![Screenshot_20240702-224857.jpg](https://github.com/AppFlowy-IO/AppFlowy/assets/20804647/03df94af-3a52-413b-b83b-38ededaca76c)

Please implement a monochrome/themed app icon that blends with Android's color theme.

**Comment by annieappflowy** [comment]
#5989 
Will support it in our official Android release
