### ISSUE TITLE
[FR] Upgrade the Stable Version for the Snapstore on Linux

### ISSUE THREAD

**Issue by md-weber** [AppFlowy-IO/AppFlowy#5687]
### Description

Currently the Stable Version for Appflowy on Linux Snapcraft is 0.5.0 and could be safely upgraded to version 0.6.0. 

<img width=200 src="https://github.com/AppFlowy-IO/AppFlowy/assets/8026644/90f01752-6719-483a-9253-9ffa7d7a9784" />

Also it would be interesting to know if it is possible to deploy directly to the snapcraft store when there is a new release via GitHub Actions.

### Impact

- No confusion how to install the latest version from the snapcraft store
- No issues related bugs that have been already fixed ([Example](https://github.com/AppFlowy-IO/AppFlowy/issues/5680))

**Comment by LucasXu0** [comment]
I updated to the latest version v0.6.2.
