### ISSUE TITLE
[FR] Need a most important feature 

### ISSUE THREAD

**Issue by favouritesir** [AppFlowy-IO/AppFlowy#5692]
### Description

I think it is simple but powerful feature.

### Impact

If we can add new page in command list like notion then it may be give us a better documentation or note. Here our program may add this new page to the subpage automatically.

**Comment by emmggi** [comment]
So you want a shortcut for creating a new page inside the one you have open?

**Comment by favouritesir** [comment]
yes.

**Comment by DimaZava** [comment]
I'd like to request the same feature. It Is really helpful in Notion, so it would be cool to have the same here

**Comment by annieappflowy** [comment]
#5134 #5417

**Comment by henri9813** [comment]
@annieappflowy , to avoid duplicate issue, @favouritesir  can you close your issue please ?

**Comment by favouritesir** [comment]
oh sorry to do it

**Comment by annieappflowy** [comment]
@favouritesir , we recently supported creating a subpage through '+'. Please give it a try. Thank you ❤️

**Comment by favouritesir** [comment]
Thanks, I'll check it out.
