### ISSUE TITLE
[Bug] No file saved when user try to share page as markdown.

### ISSUE THREAD

**Issue by AshishKhedar** [AppFlowy-IO/AppFlowy#5698]
### Bug Description

No markdown file is saved on the path when the user shares a page as markdown. the appflowy share window shows the window to save the file but no files are saved.

### How to Reproduce

- Create a page
- Open the page
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37495381/dcfe6c34-be79-41d5-ae4f-dea2dd38125e)

- click on the share button given in the top right corner
- select share a markdown
- A Save window will open, select the folder to save the file and click on the save.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37495381/f18ec8e4-413a-403a-ae69-9077795b798d)

- Check the path. there is no files saved.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37495381/7416e393-3dde-4c19-85f2-a97614286582)

### Expected Behavior

The page should be saved as a markdown file.

### Operating System

Windows 11 build 23H2 22631.3737

### AppFlowy Version(s)

0.6.2

**Comment by annieappflowy** [comment]
Hi @AshishKhedar , can you try again with the latest [release (v0.6.3)](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.3)?
I wasn't able to reproduce on my Windows 11

**Comment by AshishKhedar** [comment]
Hi @annieappflowy, after more debugging I found this is a specific case, some data is causing this issue. 
After removing the below block the export is working fine.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37495381/cd7e8790-5ca4-4c49-8904-eb3e157306e1)

the data inside the block is 

`{"type":"table","children":[{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Full Command"}]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"ip address"}]}}],"data":{"colPosition":0,"height":40.0,"rowPosition":1,"width":331.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Short Command"}]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"ip a"}]}}],"data":{"rowPosition":1,"colPosition":1,"height":40.0,"width":330.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Description"}]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Show IP address details"}]}}],"data":{"height":40.0,"colPosition":2,"rowPosition":1,"width":608.0}},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[{"insert":"Co"}]}}]},{"type":"table/cell","children":[{"type":"paragraph","data":{"delta":[]}}],"data":{"colPosition":3,"height":40.0,"rowPosition":1,"width":80.0}}]}`


@annieappflowy, A humble request to please add a message showing the error message to the user if the export fails like the message we get when the export is successful.

**Comment by LucasXu0** [comment]
@AshishKhedar I'll add a toast notification when exporting file failed. It's helpful for debugging to get the table data here.

**Comment by AshishKhedar** [comment]
Thanks @LucasXu0 @annieappflowy 
I am very happy with the support.
