### ISSUE TITLE
Logo similar to Slack's

### ISSUE THREAD

**Issue by sno2** [AppFlowy-IO/appflowy#57]
I dunno if this is on purpose or not but your logo is extremely similar to Slack's.  Here's a comparison:

![image](https://user-images.githubusercontent.com/43641633/142752568-dc3b4d0f-9d5f-4156-896a-9cfe924af471.png)

![image](https://user-images.githubusercontent.com/43641633/142752570-bcac53ff-ef0d-40ad-88ea-b560263fcbd9.png)

As you can see, the colors basically match in the four corners except the top left.  Furthermore, it basically has a similar shape patterns in the corners.

Personally, I think ya'll should change your logo to more unique as I had thought it was the Slack logo and that this was a project by Slack initially.

**Comment by annieappflowy** [comment]
I appreciate your point of view. Will leave it open here. Welcome feedback 😁

**Comment by SleepDaemon** [comment]
ig make it a flowing wave since its called flowy

**Comment by notd5a-alt** [comment]
I think a wave would be great as well
