### ISSUE TITLE
[Bug] Triple-click does not select a paragraph

### ISSUE THREAD

**Issue by ivan** [AppFlowy-IO/AppFlowy#570]
**Describe the bug**

Triple-clicking does not select a paragraph. It is processed like a double-click followed by a single-click.

**To Reproduce**
1. Triple-click a word anywhere
2. Observe that nothing is selected after the third click

**Expected behavior**
I expected the paragraph or line to be selected

**Desktop (please complete the following information):**
I tested https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.0.4 on Windows 10 21H2

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by simonbengtsson** [comment]
Related to this issue in flutter https://github.com/flutter/flutter/issues/63576

**Comment by appflowy** [comment]
I can reproduce on Mac OS

**Comment by vincentdchan** [comment]
That's true, Ivan. This will be fixed in our new editor.

**Comment by Xazin** [comment]
@annieappflowy This works for me on `main` on `MacOS`, I believe we can close?

**Comment by annieappflowy** [comment]
Thanks @Xazin 
Works on my Windows too
