### ISSUE TITLE
[FR] [Mobile] allow creating a workspace

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5702]
### Description

Hello! Got android app at 0.6.2 and I cannot create workspaces from the app I have to create them from desktop. Android app only allows me to change between already crated workspaces. Could the add workspace button be added? Thanks!

### Impact

Mobile users

**Comment by Vivian-appflowy** [comment]
Same as [#5702](https://github.com/AppFlowy-IO/AppFlowy/issues/5996)
