### ISSUE TITLE
[FR] No snackbar after clicking Copy To Clipboard & the appearance of the snackbar in dark themes

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/AppFlowy#5703]
### Description

- On a document page, when you click Share and select either `Markdown` or `HTML`, after the operation, a snackbar is shown. But upon clicking `Copy To Clipboard` no snackbar is shown, thus there is no visual indication of the operation.

- Also the appearance of the Snackbar is not distinguishable in dark themes. It just merges with the rest of the app, and thus one might not notice it at all.

--- 

<details>
 <summary>
    No Snackbar for Copy To Clipboard
 </summary>
https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/34236cdb-d50d-4102-a9ea-0d89a2c85bcb
</details>

<details>
 <summary>
    Snackbar appearance in dark theme
 </summary>
<img width="700" alt="Screenshot 2024-07-08 at 10 36 43 AM" src="https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/e7abde81-e41e-479a-8164-cf7ea537e6aa">
</details>

### Impact

Visual consistency, better UX

**Comment by annieappflowy** [comment]
<img width="478" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c6444b10-c26d-477b-936d-6b2d3bc621fa">

We have revamped the menu. Please wait for v0.6.3 and let us know your feedback
