### ISSUE TITLE
[Bug] dates alignment

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#573]
**Describe the bug**
dates in cells are not left aligned

**To Reproduce**
1. Create a date column
2. Set a few dates including time

**Expected behavior**
Left-aligned looks cleaner

**Screenshots**
<img width="158" alt="image" src="https://user-images.githubusercontent.com/12026239/174746845-c544b98e-eb29-4354-b6fc-bfbcc7046118.png">

**Comment by richardshiue** [comment]
The date text is left-aligned in the latest version. This issue has been resolved!

![image](https://user-images.githubusercontent.com/71320345/203934066-3f4e2831-da4e-4d24-9829-73b0bd9834b7.png)
