### ISSUE TITLE
[Bug] unable to replace the text in checkbox list

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#5758]
### Bug Description

Pasting text into a checkbox will replace the entire paragraph.

### How to Reproduce

Please follow the steps shown in the video.

https://github.com/user-attachments/assets/7018f74e-c76f-4c54-b1ab-75b452654a66

### Expected Behavior

Replace only the selected text.

### Operating System

Desktop

### AppFlowy Version(s)

0.6.4

### Additional Context

It works in version 0.5.9.

**Comment by LucasXu0** [comment]
@Xazin I assume it's caused by this PR. https://github.com/AppFlowy-IO/AppFlowy/pull/5621

**Comment by emmggi** [comment]
This is not just with this combination. Pasting a piece of text that was in a bullet list will replace the entire item of the list with the pasted one.

**Comment by annieappflowy** [comment]
@emmggi have you tried Ctrl + shift + v

**Comment by emmggi** [comment]
@annieappflowy Yeah that works. I'm reporting because I didn't think this was intended behavior.
