### ISSUE TITLE
[Bug] After update 0.5.6 the program no longer identifies gifs

### ISSUE THREAD

**Issue by Rasterisko** [AppFlowy-IO/AppFlowy#5760]
### Bug Description

When trying to insert an image in version 0.5.5 both pngs, jpegs and gifs will appear as an option. As of version 0.5.6+ the gifs saved on my PC no longer appear as an option to be selected and added to a note.

### How to Reproduce

Try adding a gif in appflowy using version 0.5.6 onwards

### Expected Behavior

The application identify gifs as options just as it did in version 0.5.5

### Operating System

Linux Mint XFCE 21.2

### AppFlowy Version(s)

0.5.6+

**Comment by Timisorean** [comment]
When I drag a GIF into AppFlowy, it works. But when I do `/image > Click to upload an image,` I cannot select the same image that I just dragged into the document.

**Comment by Xazin** [comment]
I've added WEBP, GIF, and BMP support in the file picker when selecting image(s) for upload.

https://github.com/AppFlowy-IO/AppFlowy/pull/6250
