### ISSUE TITLE
[Bug] Buttons in the top-right corner misalign after I minimize and maximize appflowy window.

### ISSUE THREAD

**Issue by samyogdhital** [AppFlowy-IO/AppFlowy#5808]
### Bug Description

https://github.com/user-attachments/assets/570655d9-baaa-4b82-af0f-68a3f92de70b

### How to Reproduce

Minimize and Maximize appflowy window in Windows 11

### Expected Behavior

Should have aligned in place.

### Operating System

Windows 11

### AppFlowy Version(s)

0.6.5

### Screenshots

When started initially
![image](https://github.com/user-attachments/assets/a6097f41-b721-4332-a6ae-b62ab53be5ea)

After minimizing and maximizing window
![image](https://github.com/user-attachments/assets/9520f9fc-7af9-4445-a936-46eb7917519c)

**Comment by samyogdhital** [comment]
I am using 1920x1080p monitor

**Comment by annieappflowy** [comment]
Unable to reproduce this issue. Please feel free to reopen if the issue persists
