### ISSUE TITLE
[Bug] Mobile: 

### ISSUE THREAD

**Issue by RustyProot** [AppFlowy-IO/AppFlowy#5809]
### Bug Description

Can't type. Keyboard flashes and is immediately deselected. This also blocks copy/paste and other operations

### How to Reproduce

Go I to a notebook and begin to use it normally. Sometimes it may work properly the first time, but it will not on repeated accesses to app.

### Expected Behavior

Cursor begins flashing, keyboard appears and stays, and text appears as I type.

### Operating System

android build 2024-04-26_16-21_3.5.1.09995231c for Onyx NoteAir 3C

### AppFlowy Version(s)

0.6.4

**Comment by annieappflowy** [comment]
Let us know if the issue persists
