### ISSUE TITLE
[Bug] Unable to drag block content

### ISSUE THREAD

**Issue by ngdangtu-vn** [AppFlowy-IO/AppFlowy#5812]
### Bug Description

Like the title said, I believe the 6-dot icon aside works as context-menu on 1 click, it should also work as dragable handler for the block content.

### How to Reproduce

Try to drag the block content by click on the 6 dots icon and hold than move to higher/lower position. 

### Expected Behavior

I expected the block should be move along but it didn't.

### Operating System

Linux/Tuxedo OS (Ubuntu based) + KDE Plasma 6

### AppFlowy Version(s)

0.6.5 (*.deb installer)

**Comment by emmggi** [comment]
I would appreciate this as well.

**Comment by Xazin** [comment]
Closed as completed 🎉

**Comment by EndlessPotatoes** [comment]
@Xazin this still doesn't work, trying to drag just highlights

**Comment by Xazin** [comment]
> @Xazin this still doesn't work, trying to drag just highlights

Can you make a video of what you're trying to do? This FR mentions dragging the block content by using the 6 dots to the left of the block, and that should work.

There are other feature requests for dragging around partial text (selection), but that hasn't been implemented yet.

**Comment by EndlessPotatoes** [comment]
https://github.com/user-attachments/assets/a722b463-92c5-46c8-9369-7967dbfa4c4e

Yes just dragging the block up and down isn't working for me

**Comment by Xazin** [comment]
> Yes just dragging the block up and down isn't working for me

CC @LucasXu0

**Comment by LucasXu0** [comment]
@EndlessPotatoes Which version are you using?

**Comment by EndlessPotatoes** [comment]
> @EndlessPotatoes Which version are you using?

Not sure how to check but I downloaded the one from the site to update & it works now, thanks. There wasn't a prompt to update though so that's probably something to add!

**Comment by LucasXu0** [comment]
> Not sure how to check but I downloaded the one from the site to update & it works now, thanks.

The drag feature was introduced in version 0.7.0.

> There wasn't a prompt to update though so that's probably something to add!

We do have a plan to integrate an auto-updater in the future. Thanks for the hint.
