### ISSUE TITLE
[Bug] Appflowy pages hangs  or responds slowly  when in contact with any grid  [Linux Ubuntu]

### ISSUE THREAD

**Issue by unknoxx** [AppFlowy-IO/AppFlowy#5829]
### Bug Description

AppFlowy pages seem to hang whenever I get in touch with a grid, pages where the grid is becomes slow and unresponsive and making an action like typing on another page does the same thing after a few seconds

### How to Reproduce

1. Go  to a page where a grid is 
2. Click on a column to fill
3. No response from typing or selecting with a cursor
4. move to other pages 
5. The new page  also becomes unresponsive for a few or more seconds

### Expected Behavior

1. Grid  works normally and smoothly as usual
2. Pages become responsive without any tardiness

### Operating System

Ubuntu Budgie 22.04.4 LTS x86_64

### AppFlowy Version(s)

0.6.5

### Screenshots

None

### Additional Context

Noticed this problem since AppFlowy 0.6.4

**Comment by annieappflowy** [comment]
Hi @unknoxx , can you share how may rows your grid has?

**Comment by unknoxx** [comment]
> Hi @unknoxx , can you share how may rows your grid has?

It has 3 rows  and also I face this situation even on new grids and not just existing ones

**Comment by annieappflowy** [comment]
<img width="793" alt="image" src="https://github.com/user-attachments/assets/20714bd8-ac3e-4558-9ec8-f8c1a34da0ff">


Can you try clearing cache and see if it gets improved?
Is there any published page in your workspace?

**Comment by unknoxx** [comment]
Hi @annieappflowy thank you for your response I do not have any active published workspace,   I cleared the cache as shown, closed the app and reopened it despite it still doing the same thing, for some reason, the grid unresponsiveness and page delayed response stops when the sidebar is closed and if reopened the unresponsiveness restarts (new popups show lightly until mouse hover over it and old popup will rest on the screen fadely delayed )

**Comment by LucasXu0** [comment]
Hi, @unknoxx. Can you share the log files with me? Here's the **[guide](https://appflowy.com/a1b45051-39f5-469b-88da-d008ef40bc5a/AppFlowy-Q-A-efd81847-90da-4ca7-af28-9e7491c2d9ea)** on how to export log files.

**Comment by unknoxx** [comment]
The last log file or all of it? (They're quite a lot)

**Comment by LucasXu0** [comment]
> The last log file or all of it? (They're quite a lot)

Please compress the log files from the last 7 days. Kindly reminder that the log file name contains the date at the end.

<img width="233" alt="Screenshot 2024-08-02 at 10 04 20" src="https://github.com/user-attachments/assets/25ab5592-5d8b-46f1-9726-fd1cbf8ee48d">

**Comment by unknoxx** [comment]
[Log files Pushed on GitHub](https://github.com/unknoxx/Appflowylogfiiles)

**Comment by evdcush** [comment]
I am experiencing the same issue described here and in https://github.com/AppFlowy-IO/AppFlowy/issues/5842.

Every grid page I click on takes 5-10s to load--even when opened just prior to opening a different grid.
Clearing cache did not resolve the issue.

Grids and board are the primary use-case for me for AppFlowy.

- Ubuntu 22.04; vanilla GNOME
- X windowing with official nvidia drivers
- Bug has been consistent across minors and patches; currently `v0.6.7.1`

**Comment by annieappflowy** [comment]
> After updating AppFlowy to `v0.6.8`, I am no longer experiencing the bug reported in this issue.
> Thank you @annieappflowy for tracking this bug for a fix in `v0.6.8`! 🙇🏻‍♂️

Thank you for confirming that this issue was improved! ☺️
