### ISSUE TITLE
[Bug] Clicking to a linked page is slower and sometimes does not change the view to that page

### ISSUE THREAD

**Issue by oppZ** [AppFlowy-IO/AppFlowy#5842]
### Bug Description

Clicking to a linked page is slower and sometimes does not change the view to that page. As you will able to see, this behavior is only present when clicking on the link - not when changing the page through the left plane

### How to Reproduce

See the video

At the beginning, i changed pages in the left plane - fast

Then, i clicked on the linked page and it is noticeably slower.

Then, i clicked on the linked page and moved the mouse while doing so. This time, it took like 5 seconds to change the view. From experience, clicking on this link does nothing afterwards, but i may be wrong and it's just way longer.

Finally, i cleared the cache and tried again clicking on the linked page - it returned to the previous state (switching to the linked page but slower)

https://github.com/user-attachments/assets/2e564b72-a300-48bf-8ab7-b357171509bd

### Expected Behavior

- change to the linked page as fast as clicking on the left plane 
- when clicking and moving the mouse it should not become much slower and possibly stuck 

### Operating System

Ubuntu 24.04

### AppFlowy Version(s)

0.6.6 installed with flatpak

**Comment by annieappflowy** [comment]
Hi @oppZ , are you still having this issue with our latest release?
