### ISSUE TITLE
[Bug] Paste text deletes text line.

### ISSUE THREAD

**Issue by damarro3** [AppFlowy-IO/AppFlowy#5846]
### Bug Description

When pasting text in the middle of a line, the previous text in the line dissapears.

### How to Reproduce

Create a Document page, create a bullet list, paste in the middle of the line any text.

### Expected Behavior

It should paste the text without deleting the previous text in the line

### Operating System

macOs 14.5 (23F79)

### AppFlowy Version(s)

0.6.6

### Screenshots

![PasteBug](https://github.com/user-attachments/assets/aac6186e-7fc4-41af-9789-05f51fa8c931)

**Comment by emmggi** [comment]
Same as https://github.com/AppFlowy-IO/AppFlowy/issues/5661

In the mean time you can use CTRL+Shift+V to paste without formatting.
