### ISSUE TITLE
[Bug] Code block line numbers not in sync

### ISSUE THREAD

**Issue by Kirandeep-Singh-Khehra** [AppFlowy-IO/AppFlowy#5880]
### Bug Description

Hi there, 
I am on Mac and using AppFlowy for my developer docs, the issue that i am facing is of line numbers not in sync with content in code block. Line numbers are lagging behind content of code block.
<img width="1406" alt="Screenshot 2024-08-05 at 8 12 55 PM" src="https://github.com/user-attachments/assets/4eb262d5-3f9d-425d-bf16-689961caedd5">

### How to Reproduce

Paste a long code in code block. Even less lines work but more lines exaggerate the bug.

### Expected Behavior

Line numbers must be directly inline with lines in code block.

### Operating System

MacOS (Sonama 14.5)

### AppFlowy Version(s)

0.6.6 and 0.6.1

### Screenshots

<img width="1406" alt="Screenshot 2024-08-05 at 8 12 55 PM" src="https://github.com/user-attachments/assets/892729d2-4f9c-4302-bd9c-f92520c6a06f">

**Comment by annieappflowy** [comment]
We removed line numbers in the code block
