### ISSUE TITLE
Mobile: Cant add new documents

### ISSUE THREAD

**Issue by Maxitendo1** [AppFlowy-IO/AppFlowy#5891]
### Bug Description

The new update v0.6.6 brought some new bugs. First of all you can't make any new documents and so on with the button in the navigation bar. Now, the second bug is in the design. It is now way too far on the left as you can see in the screenshots. Also please fix these issues:

https://github.com/AppFlowy-IO/AppFlowy/issues/5685

### How to Reproduce

Just look and click on the "+" button in navigation bar.

### Expected Behavior

It needs to work.

### Operating System

Nothing OS

### AppFlowy Version(s)

0.6.6

### Screenshots

![Screenshot_20240806-200818](https://github.com/user-attachments/assets/33b0929c-6e16-480f-b7c6-3cdc5b800091)

**Comment by appflowy** [comment]
Thanks for your feedback. To clarify, did you mean too far (red box) or too far (blue box)?
<img width="834" alt="image" src="https://github.com/user-attachments/assets/2706baf8-550c-4ea1-af17-4f792bbf3ae3">

**Comment by Maxitendo1** [comment]
A bit of both. Weirdly enough it looks like that on your screenshot there is now a bit of more space, but if you look at my edited image now, the word "personal' and the "arrows" are too far on the left. This section needs to be moved to the right.

![ResizedImage_2024-08-06_22-24-18_3175.png](https://github.com/user-attachments/assets/07fb7a33-b32d-484f-a940-ca4d845135f7)

**Comment by annieappflowy** [comment]
Is it just aesthetic not pleasing or does it affect your experience?
If it's latter, can you describe the experience issue you had with this design?

**Comment by Maxitendo1** [comment]
Yes, it is aesthetic not pleasing and it does slightly affect the user experience. It is now harder to click on the arrow and I'm also lightly touching my phone case.

**Comment by annieappflowy** [comment]
Thank you @Maxitendo1 
Have you tried out the Recent and Favorites tabs?
You can also move Favorites / Recent to the first tab by pressing on the header name and moving it to the first place.

**Comment by Maxitendo1** [comment]
I actually haven't, but they look pretty useful for me. Thanks for the hint!

**Comment by annieappflowy** [comment]
The '+' button bug was fixed
