### ISSUE TITLE
[Bug] After opening a reference to a row in another grid it's name nullifies

### ISSUE THREAD

**Issue by glitchheadgit** [AppFlowy-IO/AppFlowy#5893]
### Bug Description

Grid with projects before visiting a link:
![изображение](https://github.com/user-attachments/assets/747e35ce-fb47-40aa-a21e-5caafaf85079)
After visiting:
![изображение](https://github.com/user-attachments/assets/f797037e-8b26-4bc8-a4a0-33c2c2a40250)

### How to Reproduce

1. Open row with a reference as a page in another grid:
![изображение](https://github.com/user-attachments/assets/45c7c62c-2ff6-4ab2-9447-d6711bbcf9bf)
2. Click on a link: 
![изображение](https://github.com/user-attachments/assets/795e1019-82ef-4107-aae1-f68684574cdb)
3. It visits a page of the project and deletes its name automatically:
![изображение](https://github.com/user-attachments/assets/43421242-2439-4dd2-9150-47f29d691a3a)

### Expected Behavior

Name remains

### Operating System

Windows 11

### AppFlowy Version(s)

0.6.6

**Comment by KristijanDjeri** [comment]
+1 Same thing happens on Linux(ubuntu based os)

**Comment by stratofax** [comment]
> +1 Same thing happens on Linux(ubuntu based os)

Version 0.6.7, Flatpak

Debug info:
name: Freedesktop SDK
version: 23.08 (Flatpak runtime)
id: org.freedesktop.platform
idLike: null
versionCodename: null
versionId: 23.08
prettyName: Freedesktop SDK 23.08 (Flatpak runtime)

**Comment by SteffeyDev** [comment]
I've noticed the same thing just opening a grid item without using references. Sometimes it will open fine, and sometimes when the item is opened, the name is blanked out. MacOS v0.6.7

**Comment by dvsekhvalnov** [comment]
Second that, have observed both behaviors on MacOS as well:
- navigating references nullifies grid item's name
- creating & opening straight from grid (not from 'new' dialog) also nullifies

Seems like some 'async' type of bug to me at first glace.

**Comment by stratofax** [comment]
This is unfortunately a "show stopper" bug for me as it has already resulted in data loss.

**Comment by annieappflowy** [comment]
This bug was fixed in the latest release (v0.7.0). Please give it a try!
