### ISSUE TITLE
[Bug] the master list of editor bugs to be fixed in v0.6.8

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#5898]
### Bug Description

1. copy paste https://github.com/AppFlowy-IO/AppFlowy/issues/5846
2. inline code markdown https://github.com/AppFlowy-IO/AppFlowy/issues/5299
3. code block markdown https://github.com/AppFlowy-IO/AppFlowy/issues/4431
4. mentioned page open up slow https://github.com/AppFlowy-IO/AppFlowy/issues/5842 https://github.com/AppFlowy-IO/AppFlowy/issues/5829
5. sidebar performance issue 
<img width="635" alt="image" src="https://github.com/user-attachments/assets/97419338-ccc7-4f98-9386-1c735196c5f2">

6. copy paste doesn't work sometimes in the first try: copy a chat message and paste it into a doc / paste an image from the clipboard

### How to Reproduce

as described in the description

### Expected Behavior

please look into each mentioned issue and the description

### Operating System

macOS

### AppFlowy Version(s)

v0.6.6

**Comment by Xazin** [comment]
I guess 2 and 3 could be related to https://github.com/AppFlowy-IO/appflowy-editor/issues/772

**Comment by emmggi** [comment]
I'd like to add that you can't move from an indented to a non-indented list using arrow-down but you can using arrow-up.

[Screencast from 2024-08-26 14-16-04.webm](https://github.com/user-attachments/assets/2f11ca7a-562c-4849-95d1-895e29dd34ad)

**Comment by annieappflowy** [comment]
@emmggi , 

> @annieappflowy @LucasXu0 I'd like to add that you can't move from an indented to a non-indented list item using arrow-down unless you're at the end of the item, but you can using arrow-up.
> 
>  Screencast.from.2024-08-26.14-16-04.webm

Is this bug on Windows?
I wasn't able to reproduce it on macOS.
