### ISSUE TITLE
[FR] Hover on bottom toolbar icons doesn't display a tooltip

### ISSUE THREAD

**Issue by Pranav4399** [AppFlowy-IO/appflowy#59]
Hovering on the icons at the bottom doesn't display a tooltip which can be useful to understand what that particular icon does.

![image](https://user-images.githubusercontent.com/28348429/142756668-382cf5f8-8d5e-49c6-a38c-faae9d82df37.png)

**Comment by Hari-07** [comment]
I can take this up if its not being worked on by anyone as of now
