### ISSUE TITLE
[Bug] lagging issue

### ISSUE THREAD

**Issue by moolight-seashell** [AppFlowy-IO/AppFlowy#5900]
### Bug Description

extremely laggy ui when load some documents

the ui is flikering sometime

not sure but can be a duplicates of https://github.com/AppFlowy-IO/AppFlowy/issues/5898

### How to Reproduce

not sure this is a strange bug i try to understand more about it

### Expected Behavior

to not wait 2sec when scrolling with my wheel on a document to have the content =)

### Operating System

manjaro (with nouveau & nvida, and with xorg and wayland)

evrything is fine on windows

### AppFlowy Version(s)

0.6.5 and 0.6.6 flatpak, snap & aur

### Screenshots

https://github.com/user-attachments/assets/da993ce6-a9c9-4639-bb34-805062816bef

_No response_

**Comment by annieappflowy** [comment]
Hi @moolight-seashell , do you feel the app is responding slowly in the latest release? We made some improvements over the past two months.

**Comment by moolight-seashell** [comment]
hey no it looks fine
