### ISSUE TITLE
[Bug] Dragging window by title bar doesn't respond to first click / lags on macOS

### ISSUE THREAD

**Issue by pablosichert** [AppFlowy-IO/AppFlowy#591]
**Describe the bug**
When trying to drag the AppFlowy window, the window doesn't respond to the first click. When clicking again and dragging the window, the window moves in a very wonky manner.

**To Reproduce**
1. Open the AppFlowy app on macOS.
2. Click and drag the title bar.
3. Nothing happens.
4. Click on the title bar again and drag the window.
5. Window moves in a very wonky manner.

**Expected behavior**
It should be possible to drag the window on the first click, and it should not wobble around when moving.

**Screenshots**

https://user-images.githubusercontent.com/4450694/177346054-b5ca8186-1246-4212-bdb5-803769796cdc.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1

**Additional context**
Downloaded the latest release from https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.0.4.

**Comment by annieappflowy** [comment]
Should be fixed. Let us know if you still have this issue.
