### ISSUE TITLE
[FR] Add the Scroll Bar Horizontal on the Board

### ISSUE THREAD

**Issue by rodolfogoulart** [AppFlowy-IO/AppFlowy#5922]
### Description

Add a Scroll Bar visible on the Board, its dificult to scrool the board when is off the screen with a normal Mouse, when is on notebook is fine to scrool with the 2 fingers, but on the mouse dont have the option to scrool Horizontal

### Impact

All the users that dont use the notebook mouse pad

### Additional Context

try to scrool using the mouse, the board dont show the scrool bar when the content go beyond the screen

**Comment by annieappflowy** [comment]
shift + scroll can scroll the kanban board horizontally
