### ISSUE TITLE
[Bug] Paste pictures and file blocks into text

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#5934]
### Bug Description

Paste pictures and file blocks into text, no response or abnormal layout appears

### How to Reproduce

Paste pictures and file blocks into text, no response or abnormal layout appears

### Expected Behavior

Normal paste

### Operating System

desktop

### AppFlowy Version(s)

main

### Screenshots

https://github.com/user-attachments/assets/1586c611-38d2-4adb-9e52-34afcfa15512

### Additional Context

@LucasXu0

**Comment by q200892907** [comment]
@LucasXu0 
Please have a look, paste a more serious problem

**Comment by LucasXu0** [comment]
@q200892907 Did you try the latest version? The image data is not allowed to be pasted into the text block now.

**Comment by q200892907** [comment]
> @q200892907您试过最新版本了吗？现在不允许将图像数据粘贴到文本块中。

Updated is good, thank you

**Comment by q200892907** [comment]
Hello, just copy the picture and paste it into the text, no problem. Copying multiple blocks, including text, etc. and then pasting them will cause an error

**Comment by q200892907** [comment]
@LucasXu0 You can try it

**Comment by Xazin** [comment]
This should have been resolved in 0.7.1, let us know if you're still experiencing this issue :+1:
