### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Nabaddon** [AppFlowy-IO/AppFlowy#5940]
### Bug Description

Created a new board, wanted to created a new group, when pressing enter to create it with the name given a new column appears but text is either invisible or not saved (it doesn't display anything to me). When I rename it, text appears as expected.

### How to Reproduce

Create new board, created new group and see whether giving it any name actually shows up. If it creates a new group without a title and you can rename it and it then shows text it is reproduced.

### Expected Behavior

When I create a new group on a board I expect the title I type in to immediately show up.

### Operating System

Sonoma - 14.5 (23F79)

### AppFlowy Version(s)

0.6.6

### Screenshots

<img width="1218" alt="Screenshot 2024-08-12 at 11 15 07" src="https://github.com/user-attachments/assets/900b7957-7762-4cb9-afed-93ab52a85d44">

### Additional Context

systemGUID: 1C12D972-19C6-5AFE-8FFE-68C2C8FA7FAC
model: Mac15,10
majorVersion: 14
hostName: Darwin
minorVersion: 5
arch: x86_64
activeCPUs: 14
osRelease: Version 14.5 (Build 23F79)
patchVersion: 0
kernelVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
cpuFrequency: 2400000000
memorySize: 38654705664
Document: /Users/xxxxx/Library/Application Support/com.appflowy.appflowy.flutter/data

**Comment by annieappflowy** [comment]
This issue was fixed
