### ISSUE TITLE
[Bug] Unexpet behaviour of window when changing Appearance(Light Mode or Dark Mode)

### ISSUE THREAD

**Issue by BobH-Official** [AppFlowy-IO/AppFlowy#595]
**Describe the bug**
The window unexpectly reload its size, when changing Appearance(Light Mode or Dark Mode).

**To Reproduce**
1. Open the App, do either below:
   * change the window's **size** (maxmize or just drag the corner to resize), either bigger or smaller,
   * change the window's **position**,
2. Open settings
3. **Click on the switch to change Appearance**
4. The window unexpectly reload to the **default(initial)** **size** and **position**.

**Expected behavior**
When click on the switch, only the contents inside the window change it appearance, and the window ***remain its size and position***

**Screenshots**
The bug cannot be showed by images, I will upload a video to Bilibili.com
Here is the video: [https://b23.tv/Y4xrso5](https://b23.tv/Y4xrso5) .

**Desktop (please complete the following information):**
 - 版本		Windows 11 專業版
 - 版本		22H2
 - 安裝於	‎令和‎4/‎06/‎12
 - OS 組建	22621.105
 - 體驗	Windows Feature Experience Pack 1000.22632.1000.0
 - Language:	Traditional Chinese (Taiwan, China)
 - Time		Japan

(My translations)
 - Version		Windows 11 Pro
 - Version		22H2
 - Installelled at	‎2022/‎06/‎12
 - OS Build		22621.105
 - Experience		Windows Feature Experience Pack 1000.22632.1000.0
 - Language:		Traditional Chinese (Taiwan, China)
 - Time			Japan

**Additional context**
If bilibili.com is slow in your region, replay me under this issue, I will upload one to my GitHub.com repo.

**Comment by LucasXu0** [comment]
We have fixed this bug and merged it into the `main` branch, thanks for submitting the issue.
