### ISSUE TITLE
[Bug] Unsupported block: multi_image

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#5951]
### Bug Description

Gallery block isn't shown in the published page.

### How to Reproduce

1. Create a photo gallery.
2. Publish to web.

### Expected Behavior

Should show gallery block.

### Operating System

Linux/Firefox

### AppFlowy Version(s)

v0.6.7

### Screenshots

![image](https://github.com/user-attachments/assets/6714b891-aeb7-42a6-a6b9-d6b23fb94af5)

**Comment by annieappflowy** [comment]
Supported
