### ISSUE TITLE
[Bug] Can't create checklist/to-do list

### ISSUE THREAD

**Issue by jonahclarsen** [AppFlowy-IO/AppFlowy#5970]
### Bug Description

There's no way to add a checklist/to-do list. On the / menu, it doesn't show there (see screenshots), and when I use the keyboard shortcut for "Toggle to do list" it doesn't do anything.

### How to Reproduce

Install v0.6.7.1 on macOS and try to add a checklist.

### Expected Behavior

There should be a "checklist" or "to do list" option on the / menu, and the "Toggle to do list" keyboard shortcut should do something.

### Operating System

macOS 14.2

### AppFlowy Version(s)

v0.6.7.1

### Screenshots

<img width="396" alt="image" src="https://github.com/user-attachments/assets/39543c60-13c0-40d5-98ba-9fcfc4366e5c">
 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/c5aa8da1-21b2-4a68-bbf9-bbab8b9abccf">

### Additional Context

This happens at least on the macOS universal and x64 builds.

**Comment by annieappflowy** [comment]
@jonahclarsen we will add it back soon

You can type ```
-[]
``` to insert a checkbox
