### ISSUE TITLE
[FR][Mobile]  Ability to edit properties 

### ISSUE THREAD

**Issue by egt98** [AppFlowy-IO/AppFlowy#5972]
### Description

Once a property is created, can edit, delete or change the order of the property in any of the views and in any object.

### Impact

All users.

**Comment by annieappflowy** [comment]
Hi @egt98 , you can go to Settings -> Properties to edit, delete, and duplicate a property. You can also reorder them.
<img width="708" alt="image" src="https://github.com/user-attachments/assets/69a080f6-5a46-4fc9-8a95-1f647b96504f">

**Comment by egt98** [comment]
Hi @annieappflowy.

Excellent!
Thanks for your time, help and prompt response.
Also keep up the great work on the app.
Best regards!

**Comment by annieappflowy** [comment]
Thanks, @egt98 , for your input. Let me make it a mobile-specific FR 🙏

**Comment by egt98** [comment]
Thanks @annieappflowy!
Sounds good.
Keep up the great work.
Best regards.

**Comment by richardshiue** [comment]
Hi @egt98, here are two ways you can edit properties on mobile. You can also reorder by long press and dragging

https://github.com/user-attachments/assets/48375340-cc8b-4dd8-8928-a2a0f6e90458

**Comment by annieappflowy** [comment]
Hi @egt98 , please refer to the above video to edit properties in Kanban / Calendar views.
