### ISSUE TITLE
Download Link issue

### ISSUE THREAD

**Issue by oxblixxx** [AppFlowy-IO/AppFlowy#5985]
### Bug Description

I encountered an issue when attempting to download the Appflowy app for Windows. Specifically, the download does not initiate when using the link provided on the GitHub Releases page or the link available on the official Appflowy website. , but the download fails to start![image](https://github.com/user-attachments/assets/43a1e3a4-764f-4fa6-be98-d19b2687074d)

### How to Reproduce

Using the downloads link for windows from `https://appflowy.io/`

### Expected Behavior

To download the exe file

### Operating System

windows

### AppFlowy Version(s)

0.6.7.1

**Comment by LucasXu0** [comment]
@oxblixxx Could you please try downloading the package from this [link](https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.7.1/AppFlowy-0.6.7.1-windows-x86_64.exe)? If that doesn't work, check if you have any security settings or safe mode enabled in your browser that might be preventing direct downloads.

**Comment by oxblixxx** [comment]
still the same issue, trying to download only redirects to this url `https://objects.githubusercontent.com/github-production-release-asset-2e65be/377496562/7f75be16-fd4f-4ed0-b4ee-f51a2873da5f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240816%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240816T161108Z&X-Amz-Expires=300&X-Amz-Signature=aa136dce07510cfb4363239f93abc36bc421e352976b2ad7e226addf5ea62a35&X-Amz-SignedHeaders=host&actor_id=97739416&key_id=0&repo_id=377496562&response-content-disposition=attachment%3B%20filename%3DAppFlowy-0.6.7.1-windows-x86_64.exe&response-content-type=application%2Foctet-stream`. I have tried on 3 different workstation and used different browsers as well,
