### ISSUE TITLE
the authenication does not redirect me even after setting up manually![Bug] 

### ISSUE THREAD

**Issue by chipichipi15** [AppFlowy-IO/AppFlowy#5993]
### Bug Description

the issues makes my login to app almost impossible!! PLEASE FIX IT UP FOR ME! my work relies on this app

### How to Reproduce

as of now i dont have anything for reprodcue part,as the problem's solution cant be found by me.

### Expected Behavior

i wanted the authorization process to navigate me to the app after github and google approvals.

### Operating System

macos

### AppFlowy Version(s)

0.6.7.1

### Additional Context

the problem makes login process super bad.needs ux improvements.

**Comment by annieappflowy** [comment]
Hi @chipichipi15 , can you please take a screenshot of where you're having issues with login? We'll need to locate the problem first.
