### ISSUE TITLE
[Bug] themes other than the default one sidebar text contrast

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6003]
### Bug Description

all themes besides the default one have the space font black under dark theme, which is barely visible.
![image](https://github.com/user-attachments/assets/45cbc0ef-5555-4df7-aebc-a2f088af65b0)

### How to Reproduce

Choose a theme other than the default
Switch to Dark Mode

### Expected Behavior

no contrast issues

### Operating System

macOS

### AppFlowy Version(s)

v0.6.7

**Comment by emmggi** [comment]
Same on Linux.

**Comment by annieappflowy** [comment]
Fixed
