### ISSUE TITLE
[FR] Uploading files also for local workspaces

### ISSUE THREAD

**Issue by zetashift** [AppFlowy-IO/AppFlowy#6014]
### Description

I would like to be able to upload/embed files in a doc and access them without signing in/internet access.

- I expect images/videos/pdfs to be locally available.
- I don't mind if things like youtube links or anything like that aren't.

### Impact

People that use AppFlowy for work, but can't use the Cloud version because of security reasons.
Also everybody with bad internet :P.

**Comment by Xazin** [comment]
This should be supported, did you have issues uploading files in anonymous/local mode?

**Comment by zetashift** [comment]
I did, but since I can't reproduce anymore, I'll close this ticket!
