### ISSUE TITLE
[FR] How. does it sync cross devices?

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#602]
### Discussed in https://github.com/AppFlowy-IO/AppFlowy/discussions/540

<div type='discussions-op-text'>

<sup>Originally posted by **jinfagang** June  5, 2022</sup>
currently now account, how should users sync docs cross devices?</div>

**Comment by alexanderadam** [comment]
This is a [duplicate of one of the oldest issues here](https://github.com/AppFlowy-IO/AppFlowy/issues/17), right?

**Comment by annieappflowy** [comment]
Yes
This one is more specific though. The feature will be implemented as a part of the appflowy_mobile project

**Comment by alexanderadam** [comment]
Maybe it would be easier to close all issues except for one and write a comment on the closed ones, which issue is the central one.
Is there somewhere more information on `appflowy_mobile`?

**Comment by annieappflowy** [comment]
Sure. I will add this one to https://github.com/AppFlowy-IO/AppFlowy/issues/17 and close this one.
https://github.com/AppFlowy-IO/AppFlowy/discussions/1715
Nothing specific yet but it's planned to start soon. The design spec is ready for the mobile versions.

**Comment by annieappflowy** [comment]
@alexanderadam , here is our roadmap: https://github.com/AppFlowy-IO/AppFlowy/discussions/1715
