### ISSUE TITLE
[FR] Hide field in grid view but not in page

### ISSUE THREAD

**Issue by Tech-dea** [AppFlowy-IO/AppFlowy#6027]
### Description

Currently if I click hide for one of the field, it might actually be hidden in both page view and grid view, is it possible to only just having it hidden in grid view? As having a small grid view will be better 

### Impact

This is going to be benefit for trim down the columns before we clicking into the actual thing. Or else there might be chances that there is a long list of fields in grid and is hard to look at it

**Comment by annieappflowy** [comment]
You can create two views on the same database with different hide/unhide configurations.
In this way, configuring the view in a page won't affect the other view.

<img width="747" alt="image" src="https://github.com/user-attachments/assets/1f67ae14-956f-4bfd-a9a5-e73fc31ac10a">

<img width="1118" alt="image" src="https://github.com/user-attachments/assets/897587f6-8614-4770-a88b-918a8eb98bd7">


Let me know if you need more help.

**Comment by Tech-dea** [comment]
Sorry for late reply, how can I achieve what was mentioned above?
