### ISSUE TITLE
[Bug] Unable to write easily "normal" text after `code` text

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#6048]
### Bug Description

When I write some documentation, I often use: \` to mention variable values, path or others.

For now, I can't use \` because when I close tags, it make crash appflowy ( I open another issue here #5299 ).

So, I use the editor button "code", but when I want to add text just after code text, it's stay in code mode !

### How to Reproduce

Type:

```
I love `appflowy` because it's `fantastic`
```

Whatever text you add after `fantastic` will be in code mode. which is not my wanted behavior.

### Expected Behavior

There should be an "ending virtual space" at the end which I can access using my right arrow to permit me to leave the code text block.

### Operating System

MacOS

### AppFlowy Version(s)

0.6.6

### Screenshots

https://github.com/user-attachments/assets/0b714055-f228-46f1-a8fe-3fed88ec8d39

**Comment by Xazin** [comment]
I haven't looked deeply into the solution yet, but a suggestion would be to have right arrowkey cancel the slice so that the next character would be outside of the highlight.

**Comment by annieappflowy** [comment]
Supported in v0.7.1
