### ISSUE TITLE
[FR] hovering on a group name in Kanban should show its full name

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6054]
### Description

<img width="250" alt="image" src="https://github.com/user-attachments/assets/3db1330b-c54f-4ba3-85a3-48032e546103">
Display the full name in the tooltip

### Impact

Kanban users

**Comment by richardshiue** [comment]
Closing as completed via https://github.com/AppFlowy-IO/AppFlowy/pull/6307
