### ISSUE TITLE
[Bug] macOS Open to blank page with no sidebar

### ISSUE THREAD

**Issue by clbx** [AppFlowy-IO/AppFlowy#6070]
### Bug Description

When opening the application it brings me to a screen with no content except the help menu in the bottom left. None of my content or the sidebar is shown.

### How to Reproduce

Open AppFlowy when using a local store

### Expected Behavior

It shows my data

### Operating System

macOS 14.2.1

### AppFlowy Version(s)

0.6.7 (2)

### Screenshots

![image](https://github.com/user-attachments/assets/34f2ccd9-26ce-43bf-aef7-02058d4a1515)

### Additional Context

I think this may be the first time I closed and re-opened the app, but I'm not certain.

**Comment by annieappflowy** [comment]
Did you have two instances of AppFlowy opened?
This error often occurs when there are multiple instances of the application.
