### ISSUE TITLE
[Bug] Where is sync status indicator?

### ISSUE THREAD

**Issue by DWolf-19** [AppFlowy-IO/AppFlowy#6095]
### Bug Description

Is this feature removed or it's a bug?
![image](https://github.com/user-attachments/assets/b09592b0-171d-4c44-9401-0917a5e13404)

It's been gone for a few months or so.

### How to Reproduce

1. Open AppFlowy
2. Open or create new page
3. Sync status indicator is missing

### Expected Behavior

1. Open AppFlowy
2. Open or create new page
3. See the sync status indicator

### Operating System

Fedora Linux 40 | Android (GrapheneOS)

### AppFlowy Version(s)

v0.6.7.2

**Comment by emmggi** [comment]
Removed.

**Comment by DWolf-19** [comment]
Why?

**Comment by emmggi** [comment]
They said it wasn't a very good representation of the sync status.

It's supposed to be syncing all the time so you shouldn't worry about it.

**Comment by DWolf-19** [comment]
Ok, thanks.
