### ISSUE TITLE
[FAQ] Cannot access flutter quill package from git@github.com:appflowy/flutter-quill.git

### ISSUE THREAD

**Issue by premkumar5012002** [AppFlowy-IO/appflowy#61]
**Describe the bug**
When try to get package for appflowy in pubspec.yaml. it says i dont have access or package does not exist in git@github.com:appflowy/flutter-quill.git for flutter-quill.

**To Reproduce**
1. get packages from pubspec.yaml
2. it shows error says does not have access to package

**Comment by annieappflowy** [comment]
Hi Kumar,

Can you please check this : https://stackoverflow.com/questions/2643502/git-how-to-solve-permission-denied-publickey-error-when-using-git

**Comment by premkumar5012002** [comment]
Thanks, Problem Fixed
