### ISSUE TITLE
[Bug] Link to page not referenced

### ISSUE THREAD

**Issue by NicolasRidoire** [AppFlowy-IO/AppFlowy#6101]
### Bug Description

When using the "/" for using Link to page the option is shown properly but when trying to search for it the option is nowhere to be found

### How to Reproduce

type "/Link"

### Expected Behavior

The option Link to page should be shown

### Operating System

Windows

### AppFlowy Version(s)

0.6.7.2

### Screenshots

![image](https://github.com/user-attachments/assets/acd03f42-6249-4756-8711-d8d49fd5503a)
![image](https://github.com/user-attachments/assets/f59d2fde-7b63-4547-a9a8-9b37d87568b9)

**Comment by LucasXu0** [comment]
@NicolasRidoire Thanks for reporting. I'll add the keyword "Link to page" into the current keywords: `['page', 'notes', 'referenced page', 'referenced document', 'Link to page']`
