### ISSUE TITLE
[Bug] Context menu stays open when switching to another tab

### ISSUE THREAD

**Issue by emmggi** [AppFlowy-IO/AppFlowy#6109]
### Bug Description

When you highlight text on a page and switch to a new page using tabs, the context menu stays open.

### How to Reproduce

1. Highlight something on a page.
2. Switch to another tab.

### Expected Behavior

It should close itself when switching to a new tab and maybe be open again when we switch back.

### Operating System

Linux

### AppFlowy Version(s)

v0.6.7

### Screenshots

[Screencast from 2024-08-23 11-07-29.webm](https://github.com/user-attachments/assets/34883be4-7a56-4563-9613-5e0ddf4be880)

**Comment by Xazin** [comment]
For now I've just made the document lose focus, as that's what we have support for currently. I think in the future we can expand the solution to retain the selection if any, and as you mention, open the menu again when returning.
