### ISSUE TITLE
[Bug] Lost table after add some and cmd + z undo changes

### ISSUE THREAD

**Issue by theimaginationless** [AppFlowy-IO/AppFlowy#6146]
### Bug Description

[Bug] Lost table after add some and ctrl + z undo changes

### How to Reproduce

1. Insert table
2. Filling by some data
3. Press cmd + z for undo (mac os)
4. Restart app

### Expected Behavior

Table is there

### Operating System

Macos

### AppFlowy Version(s)

0.6.7 (2)

### Screenshots

<img width="788" alt="Screenshot 2024-08-31 at 20 45 52" src="https://github.com/user-attachments/assets/850a9818-8e30-486c-9ce1-e30d77e83dc0">

**Comment by annieappflowy** [comment]
The issue should be fixed in the upcoming release (v0.7.8)
