### ISSUE TITLE
[FR] Can you add the server side to be deployed through the cloud server?

### ISSUE THREAD

**Issue by LaoJiuYes** [AppFlowy-IO/AppFlowy#6149]
### Description

Dear developer!
Can you add the server side to be deployed through the cloud server? This is just a suggestion, thank you.

### Impact

This provides greater autonomy and controllability, and is more conducive to privacy and security, which is perfectly in line with the core values ​​of this project.

**Comment by khorshuheng** [comment]
Do you mean https://github.com/AppFlowy-IO/AppFlowy-Cloud ?
