### ISSUE TITLE
[Bug] The app breaks the window manager?

### ISSUE THREAD

**Issue by eburakova** [AppFlowy-IO/AppFlowy#6153]
### Bug Description

Opens only the lower quarter of the window, with the black frame and glitches ~~the current virtual desktop~~ window management system (not sure if that's Mutter or Wayland which is broken here!). May also affect other apps after a few seconds.

The window stays reactive though. 

The only way out is to close the app by switching the desktop and right-click on the dock icon -> Close

### How to Reproduce

I really don't know. It opens on startup on my other Ubuntu machine  works perfectly. 

### Expected Behavior

The window would open at the size it was last closed. The virtual desktop would not break.

### Operating System

Ubuntu 22.04.4 LTS

### AppFlowy Version(s)

0.6.7.2. (Flatpak)

### Screenshots

Made with the in-built tool 

* The area of AppFlowy and a bit more
![image](https://github.com/user-attachments/assets/28f1a3c5-e24d-44b8-8a5e-3516b7e5efad)

* The entire screen
![image](https://github.com/user-attachments/assets/52332092-69e1-4592-8c96-30ba6a2166da)

The background, icons on the dock and other windows beneath this do not disappear but flicker. It is just nothing beneath the weird Appflowy window is captured by the screenshot - apart from the upper panel. 

### Additional Context

This is a 3k display and I use 200% scaling. Wayland. GNOME 42.9.

MacBook Pro - early 2015

#### The reference machine
Where everything is running as intended
* 1920x1080, 100% scaling
* AMD desktop PC
* Same Ubuntu 22.04.4 LTS, Wayland, everything else is the same.

**Comment by Emil71** [comment]
😶

**Comment by eburakova** [comment]
Ah, this makes sense: the permissions to use X11 and Wayland were conflicting. 

As soon as I switched off the permission to use X11, the app would start normally. 

![image](https://github.com/user-attachments/assets/34400df7-6314-48f8-aa09-e5e7c959564f)

Both X11 and Wayland permissions are on by default, afaik, so maybe just leave one of them?
