### ISSUE TITLE
[FR] Show/Hide Fields on Board Cards

### ISSUE THREAD

**Issue by LinuxLowell** [AppFlowy-IO/AppFlowy#6189]
### Description

I would like to show or hide fields displayed on the cards in the board. If i have three fields, currently all three are shown and the cards get cluttered. 

Ideally I would like to select which fields to hide or hide/show all.

### Impact

This feature would be beneficial to any user that makes use of multiple fields on their cards and wants to condense the view or hide certain data or types of data.

### Additional Context

My specific use case is I am using the board as a product roadmap, each column being a quarter. The fields I have defined are products, themes, and team doing the work. When I have all three populated the cards are very cluttered - almost unusable. I use all of these fields for filtering. I can filter by team so a team can see just their work. I can filter by theme to show a sponsor the work supporting their initiative. 

In this use case I would hide the product and team day to day and just display the theme. Most of our management is around themes (since it is a communication tool to stakeholders).

**Comment by richardshiue** [comment]
Hi @LinuxLowell! If I understand your needs, you can hide properties from the cards through the settings by pressing Settings at the top right corner of the board and then Properties, then choosing to show or hide a property to your liking. Alternatively, you can open a card as a popup, and then hiding the property from there.

![Screenshot 2024-09-04 at 9 42 36 PM](https://github.com/user-attachments/assets/0689a3fd-19f1-4e24-8d4a-cfc0d44bb436)

**Comment by LinuxLowell** [comment]
> Hi @LinuxLowell! If I understand your needs, you can hide properties from the cards through the settings by pressing Settings at the top right corner of the board and then Properties, then choosing to show or hide a property to your liking. Alternatively, you can open a card as a popup, and then hiding the property from there.
> 
> ![Screenshot 2024-09-04 at 9 42 36 PM](https://private-user-images.githubusercontent.com/71320345/364400451-0689a3fd-19f1-4e24-8d4a-cfc0d44bb436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTkxODEsIm5iZiI6MTcyNTQ1ODg4MSwicGF0aCI6Ii83MTMyMDM0NS8zNjQ0MDA0NTEtMDY4OWEzZmQtMTlmMS00ZTI0LThkNGEtY2ZjMGQ0NGJiNDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE0MDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOTU2MjUwMTYxZmFhMzZlZDg1NGE4ZDYxZjc3NTlhMGViNmEzOGRmNTU5ZjRjOTFiNzgwZjFlOWY2NzBmYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lf__ATSp0wmLKQNWgUzIcH-4CbX6T5SNXvJLod32zm8)

Ah. Ok. I thought I looked in all the obvious places but didn’t find anything. That is what I am looking for, thank you.
