### ISSUE TITLE
[Bug] Automatically some texts and images are deleted

### ISSUE THREAD

**Issue by Yuvaraaj2004** [AppFlowy-IO/AppFlowy#6204]
### Bug Description

I have been using Appflowy about two months for my studies
And I have expirenced multiple time some of notes are missing and I thought its a dejavu or illusion
but today morning I have taken notes on certain topic but now the notes are not visible
and this issue aroused in the same device which i used to take notes
hope you will resolve this issue
Thankyou

### How to Reproduce

Honestly I dont know ! some time when randomly search for previous class notes it seems missing

### Expected Behavior

The notes shouldn't be vanished

### Operating System

Windows

### AppFlowy Version(s)

0.6.4

**Comment by annieappflowy** [comment]
@Yuvaraaj2004 , just to double check. Is the page missing from the sidebar or some text is missing from the page?

**Comment by Yuvaraaj2004** [comment]
> @Yuvaraaj2004 , just to double check. Is the page missing from the sidebar or some text is missing from the page?

Contents from the page are missing

**Comment by appflowy** [comment]
Hi @Yuvaraaj2004 , I am trying to reproduc your issues. You could upgrade to latest version and see the problem is still exist or not. Thank you.

**Comment by Yuvaraaj2004** [comment]
> Hi @Yuvaraaj2004 , I am trying to reproduc your issues. You could upgrade to latest version and see the problem is still exist or not. Thank you.

Yes, I updated the software today. I haven't experienced the issue so far, but if I do, I'll let you know.

**Comment by Arche151** [comment]
I experienced this recently. I have a self-hosted AppFlowy Cloud and two pages were randomly moved to the trash. Blocks on pages and even a picture were deleted. I immediately (and regrettably) switched back to Notion when this happened, because this is the worst thing to happen.
