### ISSUE TITLE
[FR] Find function - locate  the occurance

### ISSUE THREAD

**Issue by Yuvaraaj2004** [AppFlowy-IO/AppFlowy#6211]
### Description

in most of the applications like word,pdf there will be find option which help us to find and locate its occurance 
appflowy tells about the occurance of word but doesnt move
sometimes presssing enter also deletes the word

### Impact

As its a note taking app, there can be need for particular subtopic. upon search for key word this can help us find its location
plz include this function, as the page grows the finding gets difficult

**Comment by emmggi** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/5548
