### ISSUE TITLE
[FR] Keep cursor in place after changing windows focus

### ISSUE THREAD

**Issue by prsgh** [AppFlowy-IO/AppFlowy#6226]
### Description

Hi
Thanks for your great project. 
There is an annoying issue with cursor. When I'm typing and then switch the windows (for example check the chrome) and then return to appflowly desktop application cursor is not in end of the line anymore and each time I had to select the line to start typing again It can be a great thing to keep to position of cursor and when windows focus back to appflowly you can start writing from the previuse place.

### Impact

It's a common thing I guess to switch multiple time between an application like chrome and your note-taking application and each time you had to use mouse for selecting the line

**Comment by cuisws** [comment]
I have the same problem as you.
