### ISSUE TITLE
[FR] FlowyEditor Design Document.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#623]
The document should be including:

- [x]  Data Structure Design.
    - [x] Json and keyword description.
    - [x] Collaborative data model description.
        - [x] Node Collaboration.
        - [x] Text Collaboration.

- [x]  Plugin Design.
    - [x] Plugin Registration.
        - [x] Type.
        - [x] Subtype.
    - [x] How to render the plugins.
    - [x] How to update the UI when node changed.

- [x] Example Code and Show Case.

**Comment by TheSecEng** [comment]
Should also include security design 🤷‍♂️
