### ISSUE TITLE
[FR] Calendar filters

### ISSUE THREAD

**Issue by shnikita-cr** [AppFlowy-IO/AppFlowy#6234]
### Description

Feature proposal is **filter in calendar view**. Being able to manage calendar view like other views (Grid and Board) would be *delightful*.

### Impact

Nearly all types of users can benefit from this feature. For example it is helpful when managing tasks: mark tasks status as Done and filter them out to clear the view.

### Additional Context

AppFlowy competitor Notion has this feature.

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/5303
