### ISSUE TITLE
[Bug] Template download failed

### ISSUE THREAD

**Issue by 740638339** [AppFlowy-IO/AppFlowy#6247]
### Bug Description

Template download failed

On the platform, downloading the template failed. After clicking the 'use the template' button, the account cannot be synchronized to the client after authorization. It can automatically redirect to the client, but cannot download templates to the client, and there are no abnormal prompts on the interface.

### How to Reproduce

PC：Windows 11 Professional Edition not activated
Software version： 0.6.8 & 0.6.7.2

### Expected Behavior

![20240909_181038](https://github.com/user-attachments/assets/1fbddea8-c164-4822-a35a-8d45ffc84f5a)

### Operating System

Windows 11 Professional Edition not activated

### AppFlowy Version(s)

 0.6.8 & 0.6.7.2

**Comment by 740638339** [comment]
It may be due to regional restrictions. Because when I close the proxy, the page prompts that the website has been blocked.

**Comment by annieappflowy** [comment]
It was not fully supported when this bug report was created. Please give it a another try.
