### ISSUE TITLE
[Bug] Icon search missing result

### ISSUE THREAD

**Issue by Timisorean** [AppFlowy-IO/AppFlowy#6248]
### Bug Description

For example, when I search the calendar icon: 📅 

As you can see, it exists:
![image](https://github.com/user-attachments/assets/c8199c7d-7ce8-4c21-9eee-09586f9341c2)

But search not finding it:
![image](https://github.com/user-attachments/assets/0353fcc1-fc65-4deb-a2ff-5dc9c2cfaa1e)
![image](https://github.com/user-attachments/assets/8ee9b25f-6a42-4ec4-81af-77b4625330f8)

### How to Reproduce

1. On a document, "Add icon":
![image](https://github.com/user-attachments/assets/cae4a2c7-a852-4d79-b3fc-c7cccd7ab798)
2. Search

### Expected Behavior

Find the corresponding item.

### Operating System

macOS Sonoma Version 14.6.1

### AppFlowy Version(s)

Version 0.6.8

**Comment by annieappflowy** [comment]
Fixed in the upcoming release (v0.7.9)
