### ISSUE TITLE
[Bug] Drag images into grid page not working

### ISSUE THREAD

**Issue by Timisorean** [AppFlowy-IO/AppFlowy#6249]
### Bug Description

I cannot drag images onto a page that is from a grid. Not when it is in centered view, nor when I put it in full mode.

### How to Reproduce

1. Create a new grid page
2. Open page
3. Try to drag an image onto the page
4. (Open the page in full mode, and also try there)

### Expected Behavior

Should behave like on normal pages where you can drag images into it.

### Operating System

macOS Sonoma Version 14.6.1

### AppFlowy Version(s)

Version 0.6.8

**Comment by Xazin** [comment]
Hey @Timisorean can you elaborate where you are trying to drag images?

Grid/Calendar/KanBan don't allow images/text outside of their format (eg. Grid Row, Calendar Event, and KanBan Card)

**Comment by Timisorean** [comment]
Hi, here is a video of what I am trying to do:


https://github.com/user-attachments/assets/0518da39-0fba-47fa-816a-43836e666028

It works when you do the same on a normal document.

**Comment by Xazin** [comment]
> Hi, here is a video of what I am trying to do:
> 
> 
> 
> 
> 
> https://github.com/user-attachments/assets/0518da39-0fba-47fa-816a-43836e666028
> 
> 
> 
> It works when you do the same on a normal document.

I see what you mean, thanks a lot 🙏 we will add this ✌️
