### ISSUE TITLE
[Bug] Weird list behavior within tables

### ISSUE THREAD

**Issue by Timisorean** [AppFlowy-IO/AppFlowy#6251]
### Bug Description

I cannot create a new bullet point when I have a list within a table.

### How to Reproduce

1. Create a table
2. Type `- ` to create a list (with space)
3. Try to add a new bullet point to that list

### Expected Behavior

When pressing `ENTER`, `SHIFT + ENTER`, ... (or something else) I expect that a new bullet point gets created.

### Operating System

macOS Sonoma Version 14.6.1

### AppFlowy Version(s)

Version 0.6.8

**Comment by annieappflowy** [comment]
Resolved in the upcoming release (v0.7.8)
