### ISSUE TITLE
[Bug] Missing name when opening grid pages in full view in tabs

### ISSUE THREAD

**Issue by Timisorean** [AppFlowy-IO/AppFlowy#6253]
### Bug Description

You cannot see the name/title of the grid page in the tabs at the top.

![image](https://github.com/user-attachments/assets/6d81f049-afad-494e-a197-ad59c3222aab)

### How to Reproduce

1. Create grid
2. Create new row and give it a name
3. Open any other page as a new tab, so that you have at least two tabs
4. Observe the empty tab name

### Expected Behavior

It should show the name of the row.

### Operating System

macOS Sonoma Version 14.6.1

### AppFlowy Version(s)

Version 0.6.8

**Comment by annieappflowy** [comment]
Supported
