### ISSUE TITLE
[FR] Movable checklist item in grid view

### ISSUE THREAD

**Issue by Timisorean** [AppFlowy-IO/AppFlowy#6254]
### Description

Easily drag checklist items up and down to rearrange them.

![image](https://github.com/user-attachments/assets/40390772-8b87-4dfc-a36c-b80e7c91c167)

### Impact

Users can then quickly rearrange their checklist items. This could be practical, for example, when you want them in any order, like sorting them from top being important to bottom being unimportant. And when this order changes, you intuitively want to rearrange your items.

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/5896
