### ISSUE TITLE
[FR] Kanban stack names color background

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6258]
### Description

<img width="381" alt="image" src="https://github.com/user-attachments/assets/412a39a2-9ef7-4c09-a2fc-cc0522ad47af">

The colors should be consistent with the select colors.

### Impact

Kanban users

**Comment by Sreyeesh** [comment]
Hello,  Is this being worked on ? What's the status of this ?

**Comment by Xazin** [comment]
> Hello, Is this being worked on ? What's the status of this ?

It's already been implemented by @richardshiue in #6270
