### ISSUE TITLE
[Bug] `Wrap text` shows toggle animation when you open property menu

### ISSUE THREAD

**Issue by SillyCoon** [AppFlowy-IO/AppFlowy#6262]
### Bug Description

When I open property menu `Wrap text` toggle animation plays like when you click it to turn on.
It's not critical, but a bit annoying.

### How to Reproduce

1. Create grid
2. Click on property's header

### Expected Behavior

Toggle is on without animation

### Operating System

macOS 14.6.1 (23G93)

### AppFlowy Version(s)

0.6.8

### Screenshots

https://github.com/user-attachments/assets/7f9bf1fb-9576-48b5-89a6-39e31300d4ee

**Comment by Xazin** [comment]
Hey @SillyCoon, I believe this issue has been resolved and you shouldn't experience this visual bug in the next version :pray:
