### ISSUE TITLE
[Bug] Searching command with / only works in English

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#6265]
### Bug Description

Hello,

Another bug using / search only in english terms but not other language ( i'm French ).

When I try to search my block in my local, I'm unable to find it.

### How to Reproduce

Create a new document, and try to make a callout.

```
/Call 
```

You will have the callout block proposed with a name in your locale.

Type:

```
/Encadrée
```

Nothing will be proposed.

### Expected Behavior

Callout is proposed ( or whatever block ).

### Operating System

MacOS

### AppFlowy Version(s)

0.6.8

### Screenshots

<img width="461" alt="image" src="https://github.com/user-attachments/assets/87f80b48-df16-4825-b669-6e8bd146e658">
<img width="479" alt="image" src="https://github.com/user-attachments/assets/3d9752c2-9435-4908-96f4-73e4bf0884e1">
<img width="293" alt="image" src="https://github.com/user-attachments/assets/e845c011-e73e-482a-a674-4c3695102753">

### Additional Context

I'm French

**Comment by Xazin** [comment]
The keywords seem to be untranslated, or non-existing in the case of the callout.

We should definitely add the name of each item as a keyword itself (the translation).
