### ISSUE TITLE
[FR] Convert bullet list to to-do

### ISSUE THREAD

**Issue by petersullivan1985** [AppFlowy-IO/AppFlowy#6271]
### Description

It would be a useful feature to be able to change a bullet list into a to-do list. Either by highlighting the list and having the option appear above and convert the whole list or by right clicking on a specific bullet point to convert one list item at a time.

### Impact

I often start a bullet list and then want to mark what has been done so not having to create another to-do list from scratch would be a time saver.

**Comment by hug0b** [comment]
Agreed I convert text or bullet lists to to-do lists all the time when using tools like Notion or Obsidian

**Comment by annieappflowy** [comment]
#2279

**Comment by annieappflowy** [comment]
<img width="443" alt="image" src="https://github.com/user-attachments/assets/ffc40b6f-b379-4313-8bf0-49363ba47908">

Supported
