### ISSUE TITLE
[FR] AVIF and JPEG-XL image support

### ISSUE THREAD

**Issue by stickyfran** [AppFlowy-IO/AppFlowy#6274]
### Description

With the latest adittion of Files & Image property support in tables. It's becoming more apparent the necessity of having latest format images (and videos) support on this app.
It would be great.                  

### Impact

Everyone. Avif and JPEG-XL are the best image formats out there right now

### Additional Context

-AVIF and JPEG-XL are the next-gen of images format
-Right now, it's not possible to have thumbnails or play those formats in the app

**Comment by Xazin** [comment]
I made a comment just last week about this in the code, the reason why these formats aren't supported is because they simply aren't supported natively on most platforms, as such they are not supported in Flutter.

See https://api.flutter.dev/flutter/widgets/Image-class.html
