### ISSUE TITLE
[Bug] Grid: Open as a page clears the name property

### ISSUE THREAD

**Issue by thedevcharles** [AppFlowy-IO/AppFlowy#6278]
### Bug Description

When using the grid page (after entering a row of information) attempting to open the row as a page, the name property's value is erased or cleared when the page is opened. The value is cleared on the page and on the grid.

### How to Reproduce

1. Create a new grid page.
2. Fill in rows with content including the name property (or column)
3. Click the expansion icon labelled as 'open as a page'.
4. The page's name is cleared on the page and on the grid.

### Expected Behavior

1. Create a new grid page.
2. Fill in rows with content including the name property (or column)
3. Click the expansion icon labelled as 'open as a page'.
4. The page's name is visible on the page and on the grid.

### Operating System

Windows 11

### AppFlowy Version(s)

1.0.0

### Screenshots

![ezgif-2-632cfae409](https://github.com/user-attachments/assets/c211b894-4416-40a5-9799-c4109cec4c25)

### Additional Context

I am using local storage (the folder is NOT synced on a cloud storage, just a regular folder)

**Comment by annieappflowy** [comment]
I run into the same issue, but it's not 100% reproducible.

**Comment by annieappflowy** [comment]
Fixed
