### ISSUE TITLE
[Bug] crashed on Windows 11, runs as background process but not as app

### ISSUE THREAD

**Issue by billybillymc** [AppFlowy-IO/AppFlowy#6292]
### Bug Description

My computer just froze up and when I got it back on and reopened everything only AppFlowy refused to reopen.

### How to Reproduce

It appears that Appflowy (without any action on my part) crashed my computer and now refuses to let me in. I can see AppFlowy running as a background process and accessing location data on Windows 11, but it is not loading the GUI on the machine where it crashed. I was able to load my locally hosted data from another machine, so the issue is not the locally saved data. I have uninstalled and reinstalled AppFlowy on this machine many times now and it won't open. I have also reinstalled Windows and done multiple system restarts.

### Expected Behavior

AppFlowy to open as an app.

### Operating System

Windows 11

### AppFlowy Version(s)

0.6.7, 0.6.7.2, 0.6.8, 0.6.9, 0.6.5, 0.6.6 (I have tried uninstalling and reinstalling many times and the issue has persisted through these installations since the initial crash)

**Comment by LucasXu0** [comment]
Hi, @billybillymc. Were you using AppFlowy Cloud or Local mode before your computer froze up?

**Comment by billybillymc** [comment]
> Hi, @billybillymc. Were you using AppFlowy Cloud or Local mode before your computer froze up?

I was using local model when my computer froze up

**Comment by LucasXu0** [comment]
"C:\Program Files (x86)\AppFlowy\AppFlowy.exe"

**Comment by billybillymc** [comment]
I have my local folder saved.

I have executed the command from CMD. Same result: AppFlowy appears as a background process and initiates contact with my location data but does not launch as a foreground app as I see happening on the machine where it is still working.

**Comment by billybillymc** [comment]
This issue has been resolved. The uninstallation executable doesn't remove the settings in C:/Users/{username}/AppData/Roaming/io.appflowy. I'm not sure what exactly inside the settings/cache in there was causing this specific bug but after deleting that folder I was able to get AppFlowy.exe to launch as an app and not just a background process. Thank you very much @LucasXu0 for replying!

**Comment by LucasXu0** [comment]
> This issue has been resolved. The uninstallation executable doesn't remove the settings in C:/Users/{username}/AppData/Roaming/io.appflowy. I'm not sure what exactly inside the settings/cache in there was causing this specific bug but after deleting that folder I was able to get AppFlowy.exe to launch as an app and not just a background process. Thank you very much @LucasXu0 for replying!

We didn't remove this path before because it contains user data. If the user accidentally uninstalls our app while using local mode, all the data would be cleared. Let me see if we can set a configuration in the uninstall program to allow the user to clear the data if they toggle the configuration.

**Comment by billybillymc** [comment]
That makes sense! I think the more primary issue may be whatever caused
that kernel event. I would suppose that whatever was in the AppRoaming that
caused that event led Microsoft to prevent AppFlowy from launching as an
app and kept it confined to background process status. Let me know if you'd
like to look at the specific files I had in AppRoaming at the time that the
issue persisted!
