### ISSUE TITLE
[Bug] cannot end inline code when using markdown syntax

### ISSUE THREAD

**Issue by xcpky** [AppFlowy-IO/AppFlowy#6293]
### Bug Description

I cannot end inline code in markdown syntax.
that is, if I type `abc`d, d is also in the inline code.

### How to Reproduce

type `abc`d, d is also in inline code.

### Expected Behavior

d is normal text.

### Operating System

Linux

### AppFlowy Version(s)

0.6.9 (flatpak)

### Screenshots

[Screencast from 2024-09-13 11-22-46.webm](https://github.com/user-attachments/assets/3bc045f0-e57f-4768-902f-a19e5d2ec578)

**Comment by annieappflowy** [comment]
#6048

**Comment by annieappflowy** [comment]
Fixed in v0.7.1
