### ISSUE TITLE
[FR] storing multiple image in a single enity with dynamic grid like layot

### ISSUE THREAD

**Issue by Yuvaraaj2004** [AppFlowy-IO/AppFlowy#6294]
### Description

In appflowy insertion of images like screen shot and photos occupies a large amount of space and when multiple images of same contents are stored together it destroys the readablity
so if there is a possiblity for organizing image in a grid like manner it will help in readablity and better user expirence

### Impact

Improved readablity and Convinience to Manage
![Screenshot 2024-09-13 095805](https://github.com/user-attachments/assets/f88682be-a7bf-4b19-a662-c9531a5cd176)

**Comment by Xazin** [comment]
Have you tried the Photo Gallery block? It supports Browser and Grid view.

You can write `/photo` to locate it 🙏

**Comment by Yuvaraaj2004** [comment]
> Have you tried the Photo Gallery block? It supports Browser and Grid view.
> 
> You can write `/photo` to locate it 🙏

I just tried it, but it seems that it doesn't allow images from the clipboard. It's not easy for me to take a screenshot, find it in its default location, and then upload it while taking running notes. It’s really hard to manage all that.

It would be great if there was an easier way to make this process more user-friendly and accessible. For example, automatically placing uploaded images into Photo mode (/photo gallery) and grouping contiguous images would make things much smoother.

Thanks for letting me know about the /photogallery function!

**Comment by Yuvaraaj2004** [comment]
> Have you tried the Photo Gallery block? It supports Browser and Grid view.
> 
> You can write `/photo` to locate it 🙏

I just tried it, but it seems that it doesn't allow images from the clipboard. It's not easy for me to take a screenshot, find it in its default location, and then upload it while taking running notes. It’s really hard to manage all that.

It would be great if there was an easier way to make this process more user-friendly and accessible. For example, automatically placing uploaded images into Photo mode (/photo gallery) and grouping contiguous images would make things much smoother.

Thanks for letting me know about the /photogallery function!
