### ISSUE TITLE
[Bug] AI responses are truncated

### ISSUE THREAD

**Issue by nbuckley** [AppFlowy-IO/AppFlowy#6295]
### Bug Description

The AI responses in AI chat are frequently truncated (frequently as in 90% or more).

### How to Reproduce

- Create an Ai chat
- Ask questions
- Responses will generally be truncated if the response is more than a paragraph or two

### Expected Behavior

Responses that are not truncated

### Operating System

Win 10 Home 22H2

### AppFlowy Version(s)

0.6.9

### Screenshots

![cut off](https://github.com/user-attachments/assets/10d02293-9501-44a5-bb8b-93cf5088fa60)

### Additional Context

Appears to happen with any of the models I choose in settings.

**Comment by nbuckley** [comment]
![image](https://github.com/user-attachments/assets/8153026b-e1d8-4b87-8d0d-2714131dacd1)
![image](https://github.com/user-attachments/assets/b9b3ed69-bcfc-4799-92aa-b2e9d178ef71)
Just some more examples. Can't seem to find any particular pattern with it -- sometimes it's truncated after a few paragraphs and sometimes after just a few sentences. 🤷‍♂️

**Comment by annieappflowy** [comment]
@nbuckley , I haven't encountered this issue lately after a server upgrade. Closing it for now, and please feel free to reopen if the issue persists
