### ISSUE TITLE
[Bug] Filter and sort not applied in grid view

### ISSUE THREAD

**Issue by iimog** [AppFlowy-IO/AppFlowy#6297]
### Bug Description

When I add a Grid to a new Document and add a Filter for it, this filter is applied in the Grid view within the document, but it is not applied when I view only the grid.

### How to Reproduce

- create new page
- in the page type /grid to create a new grid
- in the default grid add some items and check some of the "Done" boxes
- add a filter to only include entries where "Done" is "Unchecked" 
- change to the grid directly in the left navigation bar

### Expected Behavior

The filter should be applied and the checked entries should be hidden

### Operating System

Linux (Ubuntu 22.04)

### AppFlowy Version(s)

0.6.9

### Screenshots

It works as expected in the document view
![Screenshot from 2024-09-13 09-20-36](https://github.com/user-attachments/assets/ea72f796-6178-4e35-8c0d-00a51150cab4)

The filter is not applied in the grid view
![Screenshot from 2024-09-13 09-21-16](https://github.com/user-attachments/assets/bd108d85-7ccf-4a03-852c-ce9d2f75b2c7)

### Additional Context

Deactivating and activating the filter in the grid view applies it. But switching to another view and coming back, the filter is again not applied. Sorting is also not applied.
I need to switch to the grid view directly, as in the document view the grids are not fully visible (#6287).

**Comment by iimog** [comment]
Here are Screenshots to show, that sorting is also not applied. Sorting should be on Type (second column, ascending).
Again works in the document view
![Screenshot from 2024-09-13 09-28-21](https://github.com/user-attachments/assets/61439eb7-ad9b-4652-adbf-f7c5a2d74d58)

But does not work in the grid view
![Screenshot from 2024-09-13 09-28-53](https://github.com/user-attachments/assets/1f1369ac-5d1a-43c1-b721-473fe4881b71)

**Comment by kylecreate** [comment]
This was fixed by @appflowy on Tuesday

**Comment by iimog** [comment]
I can confirm, that this is fixed in v0.7.0. Thank you :tada:
