### ISSUE TITLE
[FR] Scroll controller adds new functionality

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/AppFlowy#6299]
### Description

1. Obtain the total height of the editor
2. Get the position of each block in the editor

### Impact

It can conveniently implement the functions of line comment and block comment similar to notion

### Additional Context

@LucasXu0 Are there any good ways to do this quickly

**Comment by annieappflowy** [comment]
@q200892907 , it would be nice to request appflowy editor requests in https://github.com/AppFlowy-IO/appflowy-editor
