### ISSUE TITLE
[FR]  Hyperlinks to pages

### ISSUE THREAD

**Issue by AntonKoshuba** [AppFlowy-IO/AppFlowy#6301]
### Description

Hello, team!

My name is Anton, and I’m an active user of your project AppFlowy. I really appreciate the tool and find it very useful in my work.

While using it, I noticed that it would be incredibly helpful to have the ability to link pages to each other using hyperlinks. This would include links to other pages, as well as to specific headings or arbitrary places within the text. Such a feature would significantly improve navigation and information organization within the project.

Here’s my idea:

Hyperlinks to pages — the ability to create links that navigate to other pages within the project.
Hyperlinks to headings — the ability to link to specific headings on other pages or within the same document.
Hyperlinks to arbitrary places in the text — the ability to link to specific fragments or marked sections of text.
This feature would enhance the user experience, especially in large projects with many interconnected pages.

Thank you in advance for considering my request. If any additional information is needed, I’d be happy to provide it.

Thank you for your work and for continuously improving the project!

Best regards,
Anton

### Impact

The proposed hyperlink feature can be useful to the following types of users:

1. **Software Developers**:
   - Developers working on large projects with multiple modules and documentation pages can easily link different sections and create quick navigation between them.

2. **Documentation Authors**:
   - Those who create technical or project documentation can link various sections, topics, or chapters, making the documentation more structured and easier to navigate.

3. **Researchers and Analysts**:
   - Researchers dealing with large volumes of data or texts can link related documents, sections, or places within the text, simplifying work with research and reports.

4. **Educational Platforms and Instructors**:
   - Educational platforms and online course creators can organize content so that students can quickly navigate to related materials or tasks, enhancing the learning process.

5. **Content Managers and Editors**:
   - Professionals responsible for maintaining web content can organize interconnected pages or sections, making it easier to manage large volumes of information and creating a more interactive website.

6. **Project Management Teams**:
   - In project management systems, hyperlinks to specific tasks or sections can ease navigation and manage complex projects with many interconnected elements.

7. **Teams Working with Wiki Platforms**:
   - Wiki platforms, where content often overlaps, will be easier to use if links to other pages, subsections, or important text points can be created.

8. **Journalists and Article Authors**:
   - For creating and maintaining cross-links between different articles, sections, and sources within a single project, enhancing reader usability.

This feature is versatile and can significantly improve navigation and data organization across various fields.

**Comment by emmggi** [comment]
Linking other pages already exists. Use `+` to get a prompt.

Linking and embedding blocks has already been requested: https://github.com/AppFlowy-IO/AppFlowy/issues/4587

**Comment by Xazin** [comment]
Closing this as some of the FR is already completed, and other parts of it is duplicate :+1:
