### ISSUE TITLE
[Bug] Unable to Zoom Out with Keyboard Shortcut on AZERTY Keyboard in Ubuntu Budgie

### ISSUE THREAD

**Issue by unknoxx** [AppFlowy-IO/AppFlowy#6311]
### Bug Description

Hi there! 

I'm facing an issue with zooming out using the keyboard shortcut on my French AZERTY keyboard. When I press `Ctrl` + `=`, it zooms in as expected. However, I'm unable to zoom out using `Ctrl` + `6` (which contains the "-" symbol on AZERTY) or the "-" key on the number pad (right-hand side of the keyboard).

I’m using Ubuntu Budgie. Any assistance would be greatly appreciated!

### How to Reproduce

1. Use a French AZERTY keyboard on Ubuntu Budgie.
2. Press `Ctrl` + `=` to zoom in.
3. Attempt to zoom out using:
   - `Ctrl` + `6` (which contains the `-` symbol).
   - `Ctrl` + `-` on the number pad (right-hand side of the keyboard).

### Expected Behavior

Pressing `Ctrl` + `6` (with the `-` symbol) or `Ctrl` + `-` on the number pad should zoom out after zooming in with `Ctrl` + `=`.

### Operating System

Ubuntu Budgie 22.04.4 LTS x86_64

### AppFlowy Version(s)

0.6.9

### Screenshots

A similar visual representation of my laptop keyboard and the strokes mentioned above:
![similay$r kb layout](https://github.com/user-attachments/assets/7c5d77f7-835a-4b44-8f0c-dc13903c14c1)

**Comment by LucasXu0** [comment]
@unknoxx Is it expected to use Ctrl+Digital 6 with a French keyboard to zoom out in other applications on your PC? I tested these keybinds, but they don't work on any application I'm using.

**Comment by unknoxx** [comment]
@LucasXu0 Not at all, but a test when after noticing the `-` on my numpad isn't  zooming out with AppFlowy or `ctrl` `0` not resetting it
