### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mihaisavchuk** [AppFlowy-IO/AppFlowy#6326]
### Bug Description

In other words, the issue  is that when  navigating to a page by  clicking on  a link from  another page, the destination  page loads  as expected, but the title  of the page is  cleared or reset , instead of ret aining the custom  title that was previously  set.
This behavior is likely un intended and could be considere d a bug,  as the  page title shoul d typically persist  across navigation unless explicitly change d or reset by the application  logic. The  expected behavior woul d be for the custom page  title to remain  visible and unchanged when  navigating to that  page via  a link. 

### How to Reproduce

1. Create a table view of database
2. Add link property
3. Set a link to another page to the link property
4. Open page via link property

### Expected Behavior

- name of the page is declared 

### Operating System

mac os 

### AppFlowy Version(s)

Version 0.6.8 (0.6.8)

**Comment by annieappflowy** [comment]
Should be fixed in v0.7.0. Please feel free to reopen if the issue persists.
