### ISSUE TITLE
[Bug] When I add / delete a column in a database, all titles of document disappear

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#6336]
### Bug Description

When I add / delete a column in database, title of all documents are reseted to 0.

### How to Reproduce

- Create a database
- Add a column ( or delete )
- The title of your pages was deleted.

### Expected Behavior

The title should not disappear ?

### Operating System

MacOS

### AppFlowy Version(s)

0.6.9

### Screenshots

https://github.com/user-attachments/assets/5e84c6dd-d9e7-4b44-b662-cb32dff23115

**Comment by annieappflowy** [comment]
This bug was fixed in the upcoming release (v0.7.0)
