### ISSUE TITLE
[FR] When create a new page the focus must be on page edit input

### ISSUE THREAD

**Issue by henri9813** [AppFlowy-IO/AppFlowy#6341]
### Description

When I create a page, I want to have my focus automatically to change the page name.

### Impact

I will be more efficient in creating new pages and avoid to forget changing page name.

### Additional Context

Before: 
<img width="380" alt="image" src="https://github.com/user-attachments/assets/8429c197-a488-493f-8bdd-6bb0536c1140">

After ( wanted )

<img width="551" alt="image" src="https://github.com/user-attachments/assets/18e5d249-689e-4917-977e-9849152d6baf">

**Comment by emmggi** [comment]
There used to be a preference to prompt a dialog for the title. I don't know why it was removed.

**Comment by Xazin** [comment]
Once we have completed #3191 we will most likely auto-focus the title for easy editing on creation, whether that will solve this, I'm not entirely sure.

**Comment by LucasXu0** [comment]
I'm currently working on the document title feature. Once completed, we won't need to show a dialog or popup for editing the title anymore. Users will be able to edit the title directly in the document.

preview 
<img width="1491" alt="Screenshot 2024-09-18 at 20 12 08" src="https://github.com/user-attachments/assets/11eac65b-fda4-4e94-b0b5-b75720f4598e">
