### ISSUE TITLE
[Bug]  windows 11 Unable to log in to AppFlowy through deployed website

### ISSUE THREAD

**Issue by liubq** [AppFlowy-IO/AppFlowy#6359]
### Bug Description

I was using AppFlowy on the Chinese version of Windows 11 operating system, and when I tried to log in through the "Open Appflowy" button on my own deployed website, an error occurred.
error message:
error sending request for url(https://******.***.work:88/gotrue/token?grant_type=refresh_token):error trying to connect:接收到的消息异常，或格式不正确。（os error -2146893018）

### How to Reproduce

https://mydomain:88/web/home
menu:Navigate
button:Open 
![111111111](https://github.com/user-attachments/assets/22e5b266-8a95-4344-bb1c-5f9341e2fd58)
AppFlowy
![222222](https://github.com/user-attachments/assets/a096107c-b7f0-43ed-8590-9c4d3f091f01)

### Expected Behavior

希望能够登录成功

### Operating System

window 10

### AppFlowy Version(s)

0.6.9

**Comment by khorshuheng** [comment]
From the error message, it seems like you have provided the wrong URL. It should start with https, but you have accidentally input ttps instead.

**Comment by liubq** [comment]
不是这样的，是因为我在抄写图片内容，少打了一个字符，实际地址是：https的

**Comment by liubq** [comment]
The address I configured is like this
![aaaaa](https://github.com/user-attachments/assets/e410ae3a-190a-48fc-ae33-07307d6aba19)

**Comment by khorshuheng** [comment]
I see. In that case, can you use either the browser, or any tools that you prefer to send http request (such as postman), and check the result of GET http://(your domain):88/gotrue/settings? This is to check if your gotrue service is up and running, and also reachable from the client machine. For example, if your VM's firewall configuration doesn't allow port 88, the service might not be reachable.

**Comment by liubq** [comment]
This is the log file I found:

{"msg":"prepare upload task: 0","time":"09-20 11:20:53","target":"flowy_storage::manager"}
{"msg":"[Flutter]: onDeepLink: appflowy-flutter://login-callback/#access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzc0OGFlMy1lMDg4LTQwNDgtODY0Mi1jZmEwZjA1OWEzNzYiLCJhdWQiOiIiLCJleHAiOjE3MjY4MDk2MjIsImlhdCI6MTcyNjgwMjQyMiwiZW1haWwiOiJsX2JxQDE2My5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoibF9icUAxNjMuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6IjY3NzQ4YWUzLWUwODgtNDA0OC04NjQyLWNmYTBmMDU5YTM3NiJ9LCJyb2xlIjoiIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MjY4MDI0MjJ9XSwic2Vzc2lvbl9pZCI6IjRjYTY0YjhjLWE3YmQtNDM2Yy05MjBiLTQxNDM5MTcxNjQ4NSIsImlzX2Fub255bW91cyI6ZmFsc2V9.drzLGHThujGG13oCrxl_HlJsEFR5rpDZQQxJDSB-_-o&expires_at=1726809622&expires_in=7200&refresh_token=cMFPFcy9tbz5spaLIQFQYg&token_type=bearer","time":"09-20 11:21:01","target":"dart_ffi"}
{"msg":"[🟢 SIGN_UP - START]","time":"09-20 11:21:01","target":"flowy_user::user_manager::manager","authenticator":"AppFlowyCloud"}
{"msg":"[🟢 GET_MIGRATION_USER - START]","time":"09-20 11:21:01","target":"flowy_user::user_manager::manager_history_user","authenticator":"AppFlowyCloud"}
{"msg":"[GET_MIGRATION_USER - END]","time":"09-20 11:21:01","target":"flowy_user::user_manager::manager_history_user","elapsed_milliseconds":0,"authenticator":"AppFlowyCloud"}
{"msg":"[SIGN_UP - EVENT] client_api::http","time":"09-20 11:21:01","target":"client_api::http","error":"code:NetworkError msg: error sending request for url (https://a.dts.us.kg:88/gotrue/token?grant_type=refresh_token): error trying to connect: 接收到的消息异常，或格式不正确。 (os error -2146893018)","authenticator":"AppFlowyCloud"}
{"msg":"[SIGN_UP - END]","time":"09-20 11:21:01","target":"flowy_user::user_manager::manager","elapsed_milliseconds":109,"authenticator":"AppFlowyCloud"}
{"msg":"flowy_user::event_handler","time":"09-20 11:21:01","target":"flowy_user::event_handler","error":"HttpError: error sending request for url (https://a.dts.us.kg:88/gotrue/token?grant_type=refresh_token): error trying to connect: 接收到的消息异常，或格式不正确。 (os error -2146893018)"}
{"msg":"[Flutter]: code: HttpError\nmsg: error sending request for url (https://a.dts.us.kg:88/gotrue/token?grant_type=refresh_token): error trying to connect: 接收到的消息异常，或格式不正确。 (os error -2146893018)\n","time":"09-20 11:21:01","target":"dart_ffi"}

**Comment by khorshuheng** [comment]
And another thing to check: for your Https setup, are you using self signed certificate, or from a CA provider like LetsEncrypt?

**Comment by liubq** [comment]
I'll try your method first

**Comment by liubq** [comment]
> And another thing to check: for your Https setup, are you using self signed certificate, or from a CA provider like LetsEncrypt?

I am using LetsEncrypt certificate
![zhengshu](https://github.com/user-attachments/assets/53046df2-8daa-4133-b0c5-e275741e5daf)

**Comment by liubq** [comment]
> http://(your domain):88/gotrue/settings

{
    "external": {
        "anonymous_users": false,
        "apple": false,
        "azure": false,
        "bitbucket": false,
        "discord": false,
        "facebook": false,
        "figma": false,
        "fly": false,
        "github": false,
        "gitlab": false,
        "google": false,
        "keycloak": false,
        "kakao": false,
        "linkedin": false,
        "linkedin_oidc": false,
        "notion": false,
        "spotify": false,
        "slack": false,
        "slack_oidc": false,
        "workos": false,
        "twitch": false,
        "twitter": false,
        "email": true,
        "phone": false,
        "zoom": false
    },
    "disable_signup": false,
    "mailer_autoconfirm": true,
    "phone_autoconfirm": false,
    "sms_provider": "",
    "mfa_enabled": false,
    "saml_enabled": false
}

**Comment by liubq** [comment]
Thank you for your patient assistance.
I would like to ask if it is related to the fact that I am not using the default 80/443 ports here, as I have consulted some information that advises against changing port numbers. However, in China, home networks do not provide ports 80 and 443, so only port numbers can be changed
PS: Because my English proficiency is weak, these messages were translated through translation software, which may have a slight impact on your reading experience

原文：感谢您的耐心帮助。
我想问一下，我这里使用的不是默认的：80/443端口，是否与这有关系，因为在查阅了一些资料，都在说明，不要更改端口号，但是在中国，家用网络是不给提供80和443端口的，所以只能更改端口号
ps：因为我英文能力较弱，所以这些消息都是通过翻译软件翻译的，可能会对您的阅读造成一点点影响

**Comment by khorshuheng** [comment]
It is fine not to use port 80 or 443, as long as the nginx configuration and cloud settings are modified accordingly.  By the way, you should probably edit your comments to hide your actual domain name and the tokens, to prevent unauthorized access.

Meanwhile, i will check what could have caused the error message which you see above.

**Comment by khorshuheng** [comment]
Can you also try if the alternative login method works? Eg. via magic link, assuming that you have set up SMTP service. Then in the login page, provide your email, and click the link in the email to sign in.

**Comment by liubq** [comment]
This domain name was temporarily set up by me and will be blocked later. It is not a personal domain name I am using, but a free domain name provided by the internet and will not be used again in the future

I used magic connections and other connections, but they all showed errors. After sending the email, my mailbox couldn't receive it at all, and I'm not sure what the reason is
![image](https://github.com/user-attachments/assets/3548df98-c517-472e-b203-9c9392666698)

**Comment by liubq** [comment]
> Can you try using http instead, to verify if the issue is not due to incorrect setup of ssl?

ok, I will test it now and get back to you after the test is completed.

**Comment by liubq** [comment]
> Can you try using http instead, to verify if the issue is not due to incorrect setup of ssl?
Big boss Ox force, actually succeeded, changed to http protocol actually really succeeded, thank you for your help, you really solved my painful problem, thank you very much.

**Comment by liubq** [comment]
Thank you, through the modification to the HTTP protocol, indeed successful, thank you!
It really solved a big problem for me

**Comment by khorshuheng** [comment]
Glad to help. Closing the issue now

**Comment by liubq** [comment]
> Glad to help. Closing the issue now

Copy that. Thanks again.
收到，再次感谢。
