### ISSUE TITLE
[Bug] I opened AppFlowy and it deleted my entire todo list table

### ISSUE THREAD

**Issue by ChrisIsEditing** [AppFlowy-IO/AppFlowy#6362]
### Bug Description

Hello! I opened AppFlowy this morning and it did something that I can't describe in words.
So here's a screenshot:

![Screenshot](https://github.com/user-attachments/assets/bcb0dd5d-9711-41fb-baec-82a7c48ec62d)

### How to Reproduce

No clue, I wish I could tell you. I woke up, turned my Pc on and opened AppFlowy, and saw this. It didn't look like it glitched on start, it looked like it was already like this. But I remember looking at the todo last night before I went to bed and it was all fine?

I did not do any updates or try poking in the files or something stupid.

### Expected Behavior

It should look something like this:

![Screenshot 2](https://github.com/user-attachments/assets/fab6763e-6e36-489b-b1c5-67bdbdd4ecee)

### Operating System

Linux (Pop_OS 22.04 LTS)

### AppFlowy Version(s)

0.6.9

### Screenshots

**Trying to edit the blocks brings this up:**

![ss 3](https://github.com/user-attachments/assets/b684cae8-512f-4bff-9a8a-c83ad0270187)

**Comment by ChrisIsEditing** [comment]
Update! 

I decided to try and make a new board next to the original one and all the items just showed up there. 
_Spooooky_


![image34](https://github.com/user-attachments/assets/bc72b268-8c1b-44ea-a99f-068422176d27)

**Comment by annieappflowy** [comment]
Let us know if you run into that issue again. Closing it for now.
