### ISSUE TITLE
[Bug] Can't update with Obtainium: Cannot install an older version of an App

### ISSUE THREAD

**Issue by DWolf-19** [AppFlowy-IO/AppFlowy#6416]
### Bug Description

I can't update app with Obtainium.

### How to Reproduce

1. Open Obtainium.
2. Click `Update`.
3. See the error.

### Expected Behavior

1. Open Obtainium.
2. Click `Update`.
3. AppFlowy successfuly updated.

### Operating System

GrapheneOS (Android) 14

### AppFlowy Version(s)

0.6.8

### Screenshots

<img src="https://github.com/user-attachments/assets/aba6461e-c5ed-4184-a148-44b6c5005164" height="500">
<img src="https://github.com/user-attachments/assets/f211e26f-8827-4555-bb89-98c4df7459da" height="500">

**Comment by annieappflowy** [comment]
Should be fixed already

**Comment by DWolf-19** [comment]
Unfortunately, there is no. 🤔

**Comment by DWolf-19** [comment]
I've reinstalled the app and next update was successful.
