### ISSUE TITLE
[Bug] Cursor Highlight in Left Direction Skips Space

### ISSUE THREAD

**Issue by StreamlinedStartup** [AppFlowy-IO/AppFlowy#6433]
**Describe the bug**
Highlighting empty space skips a space when moving left. 

**To Reproduce**

1. Start a new line
2. Introduce a few spaces, then write a word
3. Select just before the first letter and attempt to remove the empty space

**Expected behavior**
Highlight should start where clicked. 

**Screenshots**

https://github.com/user-attachments/assets/92812412-d336-4056-8331-480153444b67

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5 (23F79), Apple Silicon
 - Browser - n/a
 - Version - AppFlowy App 0.6.9 (0.6.9)

**Additional context**
- Docker selfhosted: latest (9/27/24)

**Comment by khorshuheng** [comment]
@StreamlinedStartup I have transferred this issue to AppFlowy repo for better visibility, as this issue is related to the frontend as opposed to AppFlowy Cloud.
