### ISSUE TITLE
[Bug] Kanban board cover images not showing on published site

### ISSUE THREAD

**Issue by Ahad-patel** [AppFlowy-IO/AppFlowy#6443]
### Bug Description

All the images I uploaded in the cards are not visible in published site, but when we use the template all the images are visible inside desktop app.

### How to Reproduce

1. Create a kanban board
2. add cover images in some cards 
3. click on share and publish 
4. All the cover images that you have added will not be visible on published site

### Expected Behavior

The cover images should be visible on published site

### Operating System

macos 

### AppFlowy Version(s)

0.7.0

### Screenshots

https://github.com/user-attachments/assets/780d3f9e-fa76-4cff-9cfe-d22c8077be51

**Comment by annieappflowy** [comment]
@Ahad-patel , please check. This bug was fixed.
