### ISSUE TITLE
[Bug] Workspace owner cannot delete spaces created by other users

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#6444]
### Description

As the workspace owner, I should have the power to manage all spaces, even if they weren't created by me.

Use-cases:
- Old space unused or irrelevant where the relevant pages has been moved to more up-to-date and relevant space. Thus leaving a hanging space with old pages. When deleting the views in the space, there'll be an empty space that I cannot delete.
- If a former team member created a space, the team member isn't in the space anymore and cannot delete it, there is no way to delete that space even as the workspace owner.

---

![image](https://github.com/user-attachments/assets/598a79ab-fc61-4bd2-a6f3-2c9d77e20eb0)

### Impact

Workspace management before we have role permissions.

**Comment by annieappflowy** [comment]
Not work as intended
