### ISSUE TITLE
[FR] h1, h2 too similar

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6466]
### Description

it's a personal opinion, but i found that H1, H2 size are too similar
could it be possible to have more contrast between them ?
![image](https://github.com/user-attachments/assets/f125bb10-ea73-4f86-a202-e3d295a53926)

### Impact

Editor users

**Comment by emmggi** [comment]
Having a subtle indicator in front of the heading is also an option.

**Comment by Charlie17Li** [comment]
BTW, Is there a plan for customizing editor theme， just like [typora](https://theme.typora.io/)?

**Comment by annieappflowy** [comment]
<img width="192" alt="image" src="https://github.com/user-attachments/assets/575ec06b-c7cc-4dfb-bff4-b4dd1c07fe75">

@emmggi , we recently changed the font sizes for headings a little bit. Let us know your feedback.

**Comment by annieappflowy** [comment]
> BTW, Is there a plan for customizing editor theme， just like [typora](https://theme.typora.io/)?
> 
> I find the [this way](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/documentation/customizing.md#customize-a-component) can do it, right?

Yes, we plan to enable customizing themes for AppFlowy
