### ISSUE TITLE
[Bug] msvcp and vcruntime errrors

### ISSUE THREAD

**Issue by srey04** [AppFlowy-IO/AppFlowy#649]
**Describe the bug**
I am getting MSVCP and VCRuntime errors 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by Poly-Pixel** [comment]
@srey04 Can you provide more information please? What exactly do the errors say? What version of AppFlowy are you using?

**Comment by RoccCyborg** [comment]
in start when i open the app after installation then its show system error msvcp , vcruntime not found after that i tried installing Microsoft C++ 2015 redistributable. and dims.exe command to check any error is there but still showing same errror so i downloaded vcruntime140 dll file and put in syswow64 folder after that app opened but when i got to signin it showing same system errror
