### ISSUE TITLE
[Bug] "blank page" on launch

### ISSUE THREAD

**Issue by XuteBox** [AppFlowy-IO/AppFlowy#6490]
### Bug Description

When I launch the AppFlowy App it gives me this blank page (in screenshots).

### How to Reproduce

I don't know how to reproduce it.

### Expected Behavior

It should open the AppFlowy app normally.

### Operating System

Windows

### AppFlowy Version(s)

0.7.0

### Screenshots

![image](https://github.com/user-attachments/assets/796fb82c-2d00-43ce-ba4f-769594ca7bcb)

**Comment by henri9813** [comment]
Hello,

Do you have some logs ?

**Comment by XuteBox** [comment]
Helli,
I use appflowy cloud and I don't know where to get the logs. One guy told me to go to settings and data management or something like that but I can't access settings in the app.

**Comment by LucasXu0** [comment]
Hi, @XuteBox. You can check if there are multiple instances running in the background by using Task Manager. If so, please terminate all the instances and launch AppFlowy again.

**Comment by XuteBox** [comment]
Hello,
Henry told me how to get the logs so here they are. I have also checked Task Manager for AppFlowy instances multiple times but there was always just one.
[logs.zip](https://github.com/user-attachments/files/17288263/logs.zip)

**Comment by LucasXu0** [comment]
```log
{"msg":"[INIT - EVENT] 🔴open collab db error: Error { message: \"IO error: No such file or directory: Failed to open NewSequentialFileC:\\\\Users\\\\tobol\\\\AppData\\\\Roaming\\\\io.appflowy\\\\AppFlowy\\\\data_aHR0cHM6Ly9iZXRhLmFwcGZsb3d5LmNsb3Vk/365740999168757760\\\\collab_db/MANIFEST-000064: The system cannot find the file specified.\\r\\n\" }","time":"10-08 07:20:22","target":"collab_plugins::local_storage::rocksdb::kv_impl"}
```

@XuteBox Did you change the folder path or delete any files in the `io.appflowy\appflowy\data` directory?

**Comment by XuteBox** [comment]
No I didn't even know about that folder in AppData until Henri told me about it so I could get the logs.

**Comment by XuteBox** [comment]
Well, I have fixed the issue by just deleting the data_something file.
