### ISSUE TITLE
502 Bad Gateway Error When Loading Data from Appflowy Cloud

### ISSUE THREAD

**Issue by ReeeoooN** [AppFlowy-IO/AppFlowy#6497]
### Bug Description

I am experiencing a persistent 502 Bad Gateway error while trying to load data from Appflowy Cloud. This issue occurs across multiple platforms, including Windows, Android, and the web interface.
msg: got error code: 502 Bad Gateway, body: error code: 502

### How to Reproduce

1. Open Appflowy on Windows/Android/Web.
2. Attempt to load data from Appflowy Cloud.
3. Observe the error message.

### Expected Behavior

Data should load successfully without any errors.

### Operating System

Windows, Android, Web (chrome)

### AppFlowy Version(s)

0.6.8 (Win) 0.7.0 (android)

### Screenshots

![image](https://github.com/user-attachments/assets/f0f6c198-3af0-4259-8668-a2867b128415)
![image](https://github.com/user-attachments/assets/b24e6a92-c3f3-4896-834c-c2bb818f2d92)

**Comment by khorshuheng** [comment]
We were experiencing some server issue and fixed it a few minutes ago. Is this still happening?

**Comment by ReeeoooN** [comment]
> We were experiencing some server issue and fixed it a few minutes ago. Is this still happening?

Thank you! Now everything is working^^
