### ISSUE TITLE
The Font in your screen shot is not the same on my Computer

### ISSUE THREAD

**Issue by wharjack** [AppFlowy-IO/AppFlowy#653]
**Describe the bug**
Hi, I don't know what happened but the font is so thin and it makes my eyes hurt. I wanted the font that you used in your screen shot or at least I can change the font

**Expected behavior**
Make font more clear, clearer or bolder.

**Screenshots**
![image](https://user-images.githubusercontent.com/52787179/179920760-073e240f-beff-4d51-8c50-6daafd6aca9e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by notstyle** [comment]
Agree, with Light Mode is to thin. Dark mode is ok.

**Comment by wharjack** [comment]
> Agree, with Light Mode is to thin. Dark mode is ok.

Hi! I tried dark mode. A little bit thin but still not manageable to read. It will hurt our eyes in few minutes

**Comment by annieappflowy** [comment]
@notstyle @wharjack thanks a lot. I'll make it a top priority to improve this experience.

**Comment by sunny7dusk** [comment]
I'm thinking I can try implementing ways for people to change font family and size in the settings. Can I work on this?

**Comment by wharjack** [comment]
> I'm thinking I can try implementing ways for people to change font family and size in the settings. Can I work on this?

Just work on it, they will approve it if they wanted to but I guess they will

**Comment by wharjack** [comment]
> @notstyle @wharjack thanks a lot. I'll make it a top priority to improve this experience.

Anyway, you may also add change font size for better readability which Notion lacks.

**Comment by annieappflowy** [comment]
> > @notstyle @wharjack thanks a lot. I'll make it a top priority to improve this experience.
> 
> Anyway, you may also add change font size for better readability which Notion lacks.

Agreed. More flexibility is what we aim for :D

**Comment by vincentdchan** [comment]
@wharjack Sorry for the bad font rendering on Windows. Improving the font rendering on Windows should be taken into consideration ASAP.

Actually, we are developing a new editor to replace flutter-quill. You can track the progress in the project tracker. Custom themes will be implemented through our plugin systems.

If you are interested in this section of the new editor, welcome to participate. cc @sunny7dusk

**Comment by sunny7dusk** [comment]
@vincentdchan I would love to!

**Comment by vincentdchan** [comment]
You can join the discord channel: https://discord.gg/sYzMkG6P.

**Comment by sunny7dusk** [comment]
Am already in jt

**Comment by wharjack** [comment]
Hi, I just downloaded the V5, and it's still the same. The font render is still blurry.

**Comment by Xazin** [comment]
@annieappflowy Can we close this? I believe we have resolved it in the meantime.

**Comment by annieappflowy** [comment]
Thanks @wharjack . Look forward to getting more feedback from you.
