### ISSUE TITLE
[Bug] Toggling end date and include time closes popover unintentionally

### ISSUE THREAD

**Issue by richardshiue** [AppFlowy-IO/AppFlowy#6574]
### Bug Description

Title says all

### How to Reproduce

See screen recording

### Expected Behavior

Shouldn't close

### Operating System

All

### AppFlowy Version(s)

0.7.1

### Screenshots

https://github.com/user-attachments/assets/6ba2c916-27cc-4a66-93b6-be61ae3cc369

**Comment by Ahad-patel** [comment]
Hey @richardshiue I cannot reproduce this issue on version 0.7.2, Am I missing any steps?

https://github.com/user-attachments/assets/a6997b19-697c-43da-a5db-fb4de5ee740a

**Comment by Xazin** [comment]
This should have been resolved already, cannot reproduce on latest.
