### ISSUE TITLE
[Bug] Building from surce: error: the argument '--profile <PROFILE-NAME>' cannot be used with '--release'

### ISSUE THREAD

**Issue by casainho** [AppFlowy-IO/AppFlowy#6603]
### Bug Description

On Linux Ubuntu 24.04 x86, following the instructions: https://docs.appflowy.io/docs/documentation/appflowy/from-source/environment-setup/building-on-linux

When executing this command:
```cargo make --profile production-linux-x86_64 appflowy```

I am getting this error:
```
BUILD_VERSION:
/home/cas/.pub-cache/bin/protoc-gen-dart
[cargo-make][1] INFO - Skipping Task: install_flutter_protobuf 
[cargo-make][1] INFO - Running Task: setup-crate-type
[cargo-make][1] INFO - Running Task: set-app-version
APP_VERSION: 0.7.2 
[cargo-make][1] INFO - Running Task: sdk-release-build
error: the argument '--profile <PROFILE-NAME>' cannot be used with '--release'

Usage: cargo build --profile <PROFILE-NAME> --package [<SPEC>] --target [<TRIPLE>] --features <FEATURES>

For more information, try '--help'.
Error while executing command, exit code: 1
[cargo-make] INFO - Running Task: restore-crate-type
[cargo-make] ERROR - Task error detected, exit code: 105
[cargo-make] WARN - Build Failed.
```

### How to Reproduce

On Linux Ubuntu 24.04 x86, follow the instructions: https://docs.appflowy.io/docs/documentation/appflowy/from-source/environment-setup/building-on-linux

### Expected Behavior

Correct build the app.

### Operating System

Linux Ubuntu 24.04 x86

### AppFlowy Version(s)

0.7.2

### Screenshots

![image](https://github.com/user-attachments/assets/2f469d1c-4bb5-46a6-bb51-1a0c2780d3a3)

**Comment by righere** [comment]
![image](https://github.com/user-attachments/assets/079f1b47-1dcc-4301-931f-18ac1919e8f1)

**Comment by casainho** [comment]
@righere Thanks!! built as expected.
