### ISSUE TITLE
[FR] Icon in side panel

### ISSUE THREAD

**Issue by Danonino1978** [AppFlowy-IO/AppFlowy#661]
Hello,
I will appreciate if I can use icons in directory side panel to better user experience. I think I,ve seen it in some image in Google search but i´m not sure.
Many thanks !!
Regards,

**Comment by ChiragKr04** [comment]
> Hello, I will appreciate if I can use icons in directory side panel to better user experience. I think I,ve seen it in some image in Google search but i´m not sure. Many thanks !! Regards,

What is `directory side panel` ? Possible to show any screenshots?

**Comment by annieappflowy** [comment]
Hi @ChiragKr04 , I believe it's the left panel where you see a list of pages. To @Danonino1978 's request, I guess it's related to adding an emoji to a page title but I'm not sure. @Danonino1978 can you please elaborate on your request?

**Comment by annieappflowy** [comment]
<img width="1860" alt="Group 26" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/62c74aa2-2cad-41e6-ab05-f6dee17bc009">
