### ISSUE TITLE
[FR] Drag-and-Drop Functionality for Swapping Table Rows and Columns

### ISSUE THREAD

**Issue by ming2k** [AppFlowy-IO/AppFlowy#6631]
### Description

I discovered that I cannot manipulate the table by dragging and dropping rows or columns. 

### Impact

I hope to add this feature, as it would be beneficial for easier manipulation.

**Comment by Glydric** [comment]
Hello, I also think this is a needed functionality.
The problem (I think) is that currently appflowy uses the first "tab" as a baseline for the others, this also means that renaming it leads to rename the file. 
I think those are two "issues" to fix together

**Comment by henri9813** [comment]
Good idea !!!! I also have the same need.

**Comment by annieappflowy** [comment]
Supported in the upcoming release (v0.7.8)
