### ISSUE TITLE
[FR] Documents in Database Entries

### ISSUE THREAD

**Issue by candideu** [AppFlowy-IO/AppFlowy#664]
# **1~3 main use cases of the proposed feature**
Hello! Thanks for making this app.

My suggestion is to have a document attached to each database entry. This way, users can attach rich text information when they expand the entry, and have the option to open it as a document.

# **What types of users can benefit from using your proposed feature**
- People who want to keep track of recipes
- People who plan videos
- People who plan social media content
- People who plan courses

# **Additional context**
## Example from Notion:
![image](https://user-images.githubusercontent.com/55474996/180076428-e42f08ce-60cc-4eb3-8227-c69d7cb75640.png)

## Example from Focalboard
![image](https://user-images.githubusercontent.com/55474996/180080962-21ead65b-17ec-432e-bb65-868effd5816b.png)

**Comment by annieappflowy** [comment]
Thanks @candideu for sharing your use cases. We currently support open a record as a page where you can see where we are going - open as a document. This feature is planned and will keep you posted when it's online.

**Comment by annieappflowy** [comment]
@candideu, we've completed your feature request. You can give it a try with the[ latest release](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.2.5).

**Comment by candideu** [comment]
Amazing, thank you!
