### ISSUE TITLE
[Bug] 国内用不了呀

### ISSUE THREAD

**Issue by Myfanily123456** [AppFlowy-IO/AppFlowy#6682]
### Bug Description

国内电脑无法登陆

### How to Reproduce

国内用不了

### Expected Behavior

国内能用

### Operating System

windows 10

### AppFlowy Version(s)

最新版

**Comment by annieappflowy** [comment]
AppFlowy Cloud is not available in China, as we don't have the bandwidth to comply with local regulations. However, you can still use the local mode we offer.
<img width="584" alt="image" src="https://github.com/user-attachments/assets/8505bb73-c821-42b1-ab50-bc00bd41481f">
