### ISSUE TITLE
[Bug][Mobile] editor bullet list enter 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6688]
### Bug Description

Has anyone encountered this issue before? When pressing enter in a list, it would sometimes create a new line rather than a new list item?

https://github.com/user-attachments/assets/f463ff6f-c186-4469-985b-3b9b0693ceb0

### How to Reproduce

https://discord.com/channels/903549834160635914/1189250440219590719/1301744336467394580

### Expected Behavior

Enter -> Create a new list item 

### Operating System

Android

### AppFlowy Version(s)

v0.7.2

**Comment by LucasXu0** [comment]
Similar to [this issue](https://github.com/AppFlowy-IO/AppFlowy/issues/7105), in some cases, the insertion contains a whitespace before `\n`, which is considered a soft break. This issue will be resolved in version 0.8.0.

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/0f082706-4089-4d71-a510-54708e48691a" />
