### ISSUE TITLE
[FR] Document where data is stored, and please reconsider ~/flowy

### ISSUE THREAD

**Issue by tv42** [AppFlowy-IO/AppFlowy#669]
**1~3 main use cases of the proposed feature**

The website claims "100% control of your data Download and install AppFlowy on your local machine. You own and control your personal data.". I wanted to evaluate these claims for myself, and looked for where AppFlowy stores the data and how. This was never mentioned in the documentation or in the app.

Also, please consider moving the default location to e.g. ~/.local/share/AppFlowy, ~/flowy is both unwanted litter in the home directory *and* not the name of the app!

**Comment by annieappflowy** [comment]
> **1~3 main use cases of the proposed feature**
> 
> The website claims "100% control of your data Download and install AppFlowy on your local machine. You own and control your personal data.". I wanted to evaluate these claims for myself, and looked for where AppFlowy stores the data and how. This was never mentioned in the documentation or in the app.
> 
> Also, please consider moving the default location to e.g. ~/.local/share/AppFlowy, ~/flowy is both unwanted litter in the home directory _and_ not the name of the app!

Hi @tv42 , thanks a lot for your feedback. Documenting the path and renaming the folder path totally make sense to me. We'll incorporate your suggestions.

**Comment by martinfiers** [comment]
Hello! Thanks for this nice project! I was wondering, are you also planning to allow customization of where the data is stored? That way you could store it on a shared folder (and use it e.g. in combination with syncthing/... to share notes across different computers). But I'm not sure if AppFlowy was intended to be used this way?

**Comment by annieappflowy** [comment]
Hi @martinfiers , thanks a lot for the encouraging words. Customizable data storage path is planned to include in v0.0.9: https://github.com/AppFlowy-IO/AppFlowy/milestone/6, and we will iterate on it as more feedback / requests from our users become available.

**Comment by Wood-Xia** [comment]
@annieappflowy 
May I follow the status of this proposal? Is already supported and any document for that?

**Comment by annieappflowy** [comment]
@Wood-Xia , thanks for asking. It's planned but not started yet.  You can stay an eye out for the status of this issue or follow our [release page](https://github.com/AppFlowy-IO/AppFlowy/releases)

**Comment by annieappflowy** [comment]
Documentation on how to find where the data is stored: https://appflowy.gitbook.io/docs/essential-documentation/data-storage
@martinfiers , you can customize where the data is stored by going to Settings -> Files
<img width="584" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/fb9f2784-0042-4ca4-b67e-e7d4a022ce3b">
