### ISSUE TITLE
[FR] Flux integration  

### ISSUE THREAD

**Issue by JJger148** [AppFlowy-IO/appflowy#67]
**1~3 main use cases of the proposed feature**
integrate [flux](https://www.fluxsocial.io/) for datasecurity and decentralized p2p data access 

**what types of users can benefit from using your proposed feature**
everyone who want to share data with others
everyone who cares about privacy and data security

**Comment by annieappflowy** [comment]
Hmm, ok, I'm signing up coz I'm curious about it and would like to see what value it can create for us. If it's not relevant to AppFlowy, this will be considered as a self-promoted post; therefore, I'll have to close it.
