### ISSUE TITLE
[FR] Support Markdown

### ISSUE THREAD

**Issue by ItsAleph** [AppFlowy-IO/AppFlowy#671]
**1~3 main use cases of the proposed feature**
Having to point and click on each button to just toggle a single style is very cumbersome. Support for markdown syntax would be an QoL feature and unbelievably increase the speed of writing content

**What types of users can benefit from using your proposed feature**
Everyone.

**Additional context**
I see the implementation of this like that: you type "\*hello world\*", and when you're typing the last "\*", AF automatically converts your "\*hello world\*" into "*hello world*"

**Comment by annieappflowy** [comment]
Thanks @ItsAleph for submitting a FR to us. I searched through the issue list, and there seems to be a markdown FR that's already submitted: https://github.com/AppFlowy-IO/AppFlowy/issues/25

**Comment by ItsAleph** [comment]
Oh, sorry! I searched for "Markdown", but github did not given any results :C
