### ISSUE TITLE
[Bug] Self-hosted user billing interface 404

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#6750]
### Bug Description

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/6c02a107-1f3d-4e71-9940-9b96b0fdb0f8">

### How to Reproduce

Users of self-hosted appflowy should encounter

### Expected Behavior

The billing interface can work normally

### Operating System

mac

### AppFlowy Version(s)

0.7.3

**Comment by khorshuheng** [comment]
The billing interface is what we used to distinguished between different payment plan for a user, and is actually unnecessary for self hosting at all. The 404 doesn't affect normal operation of the server, though we probably shouldn't show this as an error on the log.

**Comment by smartyhero** [comment]
I cannot use the latest version of the namespace modification feature. Is it related to the billing interface?
![image](https://github.com/user-attachments/assets/11e747a3-36c3-4c71-a139-6f08f9da840d)

**Comment by appflowy** [comment]
@smartyhero yes. it's relate to billing feature.
