### ISSUE TITLE
[Bug] Incorrect price shown in the pricing plan tab

### ISSUE THREAD

**Issue by SOSeriously** [AppFlowy-IO/AppFlowy#6757]
### Bug Description

The price plan for the AI Max add-on show 8USD in appflowy and 10USD on the website upon checkout.

### How to Reproduce

Settings > Plan > Add-Ons > Add button

### Expected Behavior

The correct/same price should display in appflowy and on the checkout page.

### Operating System

Windows 11

### AppFlowy Version(s)

0.7.2

### Screenshots

![Screenshot 2024-11-10 222320](https://github.com/user-attachments/assets/e2f628e1-2fa2-4ea3-b7c4-1818f47b2d9a)
![Screenshot 2024-11-10 222257](https://github.com/user-attachments/assets/2ec1715c-0130-4773-b3a4-10dc6df5dcc6)

**Comment by annieappflowy** [comment]
One is the yearly plan, and the other is monthly.
If you toggle on "annual savings" in the checkout page, it will be changed to $8 * 12
