### ISSUE TITLE
[Bug] Fonts menu is very slow

### ISSUE THREAD

**Issue by oppZ** [AppFlowy-IO/AppFlowy#6765]
### Bug Description

When we want to change the font of the text, the font menu is very slow to respond. After a while, it is responsive. Looks like it tries to load all of the fonts. Appflowy uses 100 % of a cpu core during this time

### How to Reproduce

- Highlight any text
- Click on font menu

[Screencast from 2024-11-11 13-24-17.webm](https://github.com/user-attachments/assets/a03df8f9-55cd-4ce9-96fe-c6736a0cb248)

### Expected Behavior

not that slow

### Operating System

ubuntu 24.04

### AppFlowy Version(s)

0.7.3

**Comment by LucasXu0** [comment]
Hi, @oppZ. The font menu performance issue has been fixed and will be included in the upcoming version.
