### ISSUE TITLE
[FR] Renaming Spaces on Mobile

### ISSUE THREAD

**Issue by phiiter2** [AppFlowy-IO/AppFlowy#6771]
### Description

User might want to rename spaces on mobile. The option to change space name could be provided when long pressing the space name.
![Screenshot_2024-11-13-00-25-05-717_io appflowy appflowy](https://github.com/user-attachments/assets/1f45d0af-eda0-4d68-a167-39ad8b355e65)

### Impact

All users

### Additional Context

I would be happy to implement this feature.

**Comment by LucasXu0** [comment]
Hi, @phiiter2. The feature for managing space on mobile has been completed and will be included in the upcoming version.

https://github.com/AppFlowy-IO/AppFlowy/pull/6764
