### ISSUE TITLE
[Bug] Issue with dark theme hightlight colors

### ISSUE THREAD

**Issue by LaBaude32** [AppFlowy-IO/AppFlowy#679]
**Describe the bug**
In dark theme configuration, the text is automatically turning white color. But with the highlight it become unreadable as we can se below : 

**To Reproduce**
1. Go to parameters 
2. Click on appearance
3. switch to dark mode '

**Expected behavior**
Maybe you need to update highlight colors for dark theme

**Screenshots**
![image](https://user-images.githubusercontent.com/42806696/180434823-cabcdd6d-2c2e-4d69-8393-f299162dfcdf.png)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Version 0.0.4

**Comment by fangykai** [comment]
Duplicate of #433

**Comment by MikeWallaceDev** [comment]
Duplicate of #433
