### ISSUE TITLE
[FR] AppFlowy logo in the "blog" page is not linked to home page

### ISSUE THREAD

**Issue by RohitYandigeri** [AppFlowy-IO/AppFlowy#681]
When we access the blog page from the home page , the AppFlowy logo in the blog page should be linked to the home page.
User feels more comfortable to switch and access both pages without creating multiple tabs in the browser.

![Screenshot 2022-07-22 211827](https://user-images.githubusercontent.com/91059418/180476565-a20e4537-4798-4239-9a29-8012369fb6be.png)

**Comment by annieappflowy** [comment]
@RohitYandigeri thank you! We accept your suggestions

**Comment by RohitYandigeri** [comment]
Thank you for your response , please appreciate it with providing some free
swags or tshirt , that would motivate me to contribute to open source
