### ISSUE TITLE
[Bug] Android all notifications blocked

### ISSUE THREAD

**Issue by casainho** [AppFlowy-IO/AppFlowy#6814]
### Bug Description

I was expecting to get a notification from a Date or Reminder block of the app. I didn't and I think is because all the app notifications are blocked and I simple can't enable them (Allow notifications button is disabled). For what I could test, this issue is because something on the app and not configurations of my Android:

![image](https://github.com/user-attachments/assets/7f6bf8a7-246e-44f1-9fd9-23e576d8a5fa)

### How to Reproduce

Install app version 0.7.3 on Android 14 and check the app permissions - you should see the same as the previous screenshot.

### Expected Behavior

Notifications are not blocked and work.

### Operating System

Android 14

### AppFlowy Version(s)

0.7.3

**Comment by LucasXu0** [comment]
Hi, @casainho. We don't support system notifications yet. The system notification feature is on the roadmap.

**Comment by casainho** [comment]
@LucasXu0 thanks for the feedback.

Date and Reminders are must features for a person as me with ADHD!!

So I guess I should close this issue.
