### ISSUE TITLE
[Bug] Free storage errors contradict information in the settings

### ISSUE THREAD

**Issue by genseirin** [AppFlowy-IO/AppFlowy#6815]
### Bug Description

When trying to add more images, I repeatedly receive error messages that free storage was used up. Deleting old content and removing them from the trash doesn't help, even after restarting the app and clearing the cache I can add at most one more image and the problem reappears.
According to the information in "Plan" in my settings, however, I am well below the storage limit and never used any AI.

### How to Reproduce

I don't know if it is a reproducible issue, but I might have crossed a certain threshold in data size or the number of elements.

### Expected Behavior

Either the information about storage usage should show that I hit the limit, or it should be possible to add more images.

### Operating System

macOS 14.7.1

### AppFlowy Version(s)

0.7.3

### Screenshots

![image](https://github.com/user-attachments/assets/1c3b0fa8-8444-4d32-aa10-0070fdc8f095)

![image](https://github.com/user-attachments/assets/b89ca1d9-8a74-4805-bac5-56a2422daa8d)

### Additional Context

I'm using the AppFlowy Cloud.

**Comment by appflowy** [comment]
Hi @genseirin,
Are you using AppFlowy Cloud? I need a bit more information to help locate the issue. Could you upload your log file? Alternatively, feel free to send me a direct message on Discord.

**Comment by appflowy** [comment]
@genseirin What is the size of the file you tried to upload?

**Comment by genseirin** [comment]
Thanks!
File sizes are between 3 and 4 MB, all are photos (jpg, file names are a date + time). The page now contains 8 images, an external link and text. There are some (I think 6) further pages.

**Comment by appflowy** [comment]
Hi @genseirin . Can you try 0.7.4? I've updated the error message.

**Comment by genseirin** [comment]
With 0.7.4 I see:
![image](https://github.com/user-attachments/assets/5bb9d214-c7a8-4c4e-860c-6d494a926192)

The last image had 5.7 MB, the one before below 4 MB. In the plans overview I see that file uploads can take up to 7 MB. So that's not per file? Or could there be a flaw in determining the sizes?

I remember that I before added a file of 17.8 MB (i.e. a video, but added as a file), but later removed it. Maybe this has triggered the alert and the app isn't aware of the fact that is has been removed already.

**Comment by appflowy** [comment]
@genseirin Noted. The alarm might be triggered by your 17.8 MB image. Could you please send me your log file? (Discord or Email)

**Comment by appflowy** [comment]
@genseirin I've fixed this bug. A new version will be released next week

**Comment by genseirin** [comment]
Thank you!

**Comment by genseirin** [comment]
Confirmed, fixed with v0.7.5
