### ISSUE TITLE
[Bug] Broke AppFlowy Boards by changing Status to Date

### ISSUE THREAD

**Issue by Oshirowanen** [AppFlowy-IO/AppFlowy#6816]
### Bug Description

I somehow was able to chose "date" in a board, and now I can no longer get into the board.  

### How to Reproduce

Open any board
click Settings > Properties > Status
Select Date
Click out of the board and then try to get back in.

### Expected Behaviour

If this is going to break the board, I shouldn't be able to make such a change.
I should at least be able to check the status back to a default value to bring the board contents back.

### Operating System

Ubuntu 24.04
Windows 11

### AppFlowy Version(s)

0.7.3

### Video recording

https://github.com/user-attachments/assets/440ffa98-3aa3-4834-a7f7-aa8ad32725d5

### Additional Context

1. appflowy snap package from the snap repository
2. How do I fix this without reinstalling?

**Comment by Oshirowanen** [comment]
Hi @richardshiue 

Sorry about the badly worded post, it was done in a rush.  I have now updated the post and have included a video to show the steps more clearly.

I hope the updated post clarifies the issue.  I can confirm that I get the same issue on Windows 11 and Ubuntu 24.04.

**Comment by richardshiue** [comment]
Hi @Oshirowanen, thanks for the update. Yes I can reproduce it now, I will see to fixing this issue as soon as possible.
