### ISSUE TITLE
[Bug] Search/Replace toolbar input text barely visible on desktop

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/AppFlowy#6832]
### Bug Description

The box for search & replace does not clearly show the text you would have typed in the input field

### How to Reproduce

1. Have a document open  
2. Using the shortcut `ctrl + f` to trigger the search popup.
3. Type into the searchbox the text within the input field should be displaying incorrectly.

### Expected Behavior

Clearly show the text inside the input field when doing search in document or find and replace.

### Operating System

Linux

### AppFlowy Version(s)

0.7.3

### Screenshots

https://github.com/user-attachments/assets/d4b78a75-c844-4f6d-a7d9-ad304c763da4

### Additional Context

Had checked with AppFlowy-Editor demo app the input field there is visible and does not cut off the text.

**Comment by richardshiue** [comment]
Can you check on 0.7.4?

**Comment by LucasXu0** [comment]
![Screenshot from 2024-11-20 09-09-12](https://github.com/user-attachments/assets/350c678f-7df7-4b98-8673-029b124c6a32)

Hi, @rileyhawk1417, I can't reproduce the issue with v0.7.4 on Ubuntu. You can try upgrading to the latest version and check again.

**Comment by rileyhawk1417** [comment]
@LucasXu0 issue seems to be gone on 0.7.4 will close this issue.

![image](https://github.com/user-attachments/assets/df5255cd-b548-4c0a-97a1-4bf152a1c461)
