### ISSUE TITLE
[FR] Tooltip for grid's row action

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#686]
Tooltip for row action. 

1. add a new row
<img width="472" alt="image" src="https://user-images.githubusercontent.com/86001920/180591501-22f58147-d29d-4c77-87f4-624b0aa04c54.png">

2. click to open menu
<img width="535" alt="image" src="https://user-images.githubusercontent.com/86001920/180591529-2485d07b-0d72-41c5-befa-88ad15b6aede.png">

**Comment by aarhusgregersen** [comment]
I'm assuming this is on hover? 

I'll take a look at it :)

**Comment by dhruvmaindola227** [comment]
> I'm assuming this is on hover?

yes it is

**Comment by aarhusgregersen** [comment]
Cool! I'll take a jab at it, see if I can't figure this one out 😄

**Comment by annieappflowy** [comment]
@aarhusgregersen thanks for claiming this issue. I've assigned @appflowy as your mentor on this task. If you need help, please feel free to ask him on Discord.

**Comment by aarhusgregersen** [comment]
I haven't been able to figure this one out and finding the time to sit down and study Flutter has not been as generous as I was hoping 🥴 
If necessary please feel free to re-assign this task to someone else :)

**Comment by annieappflowy** [comment]
Hi @aarhusgregersen , no worries. We've all been there. I was thinking maybe you just needed a little bit help or guidance. Have you reached out Nathan on Discord?

**Comment by ChiragKr04** [comment]
@aarhusgregersen I can help you with this. We can reach out on discord

**Comment by ChiragKr04** [comment]
Can I take this issue if its okay!? @annieappflowy @aarhusgregersen

**Comment by aarhusgregersen** [comment]
Thank you for the overwhelmingly positive feedback @annieappflowy and @ChiragKr04 !! 😄 

I have still not had the opportunity to sit down and focus on learning a bit of flutter, so I would be totally fine by me if @ChiragKr04 takes over on this, as I haven't even started yet 😄

**Comment by annieappflowy** [comment]
@aarhusgregersen thanks, I reassigned it to @ChiragKr04
