### ISSUE TITLE
[FR] Tooltip for open row as page

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#688]
Add a tooltip for opening row as a page.

https://user-images.githubusercontent.com/86001920/180592152-a3981436-de5c-484f-967e-3e57161487a8.mov

**Comment by ChiragKr04** [comment]
Can I work on this issue !?

**Comment by ChiragKr04** [comment]
And what to write on the tooltip!?

**Comment by appflowy** [comment]
> Can I work on this issue !?

Sure. I think `open as a page` would be fine.

**Comment by ChiragKr04** [comment]
> > Can I work on this issue !?
> 
> Sure. I think `open as a page` would be fine.

Created pull request https://github.com/AppFlowy-IO/AppFlowy/pull/781

**Comment by richardshiue** [comment]
Closing as complete since #781 has been merged
