### ISSUE TITLE
[FR] Icon color for light/dark mode

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#689]
The icon seems weird on light mode, but it works on dart mode. The icon color should be pure dark in light mode and light gray in dark mode.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/86001920/180592552-624865b4-8a40-40b6-932e-d62a86ce255c.png">

The color should not be const, it should read from the theme color.
![image](https://user-images.githubusercontent.com/86001920/180592602-f29eac75-d25a-4cf2-ac25-242d23ff8bca.png)

Not only the ViewDisclosureAction but also AppDisclosureAction has the same problem.

**Comment by MikeWallaceDev** [comment]
Wouldn't it be better to have this in the theme instead?  All icons need to be adjusted according to the current theme.

**Comment by IMPranshu** [comment]
I want to take up this issue. Please assign it to me.

**Comment by appflowy** [comment]
> I want to take up this issue. Please assign it to me.

Alright! You could DM me if you have any questions.

**Comment by richardshiue** [comment]
@annieappflowy I believe this has been implemented, should be good to close
