### ISSUE TITLE
[FR] Untitled Feature Request

### ISSUE THREAD

**Issue by dtat1991** [AppFlowy-IO/appflowy#69]
**1~3 main use cases of the proposed feature**
- develop a faucet mining app to introduce a new coin.
- develop it on the eth blockchain
- a simple app that will implement swap dapps and coin made available on all major crypto sites.

**what types of users can benefit from using your proposed feature**
- a free investment until everything is fully developed and reached enough users to develop revenue, the incentive is marketing peer to peer to reach goals quickly.

**Additional context**
I have the faucet app ready need help developing more features.

**Comment by annieappflowy** [comment]
Please only post FR for AppFlowy. Closing this issue.
