### ISSUE TITLE
[FR] Save left side width setting to disk

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#690]
The width of the left sidebar is not saved to disk, so it will get reset on the next launch. 
https://user-images.githubusercontent.com/86001920/180593248-5707c634-7f99-41cd-ae92-b71107d5b4fb.mov

1. Extend the UserSettingsService to save the width. 
2. Restore the width on the next launch.

**Comment by Nike682631** [comment]
@appflowy is this issue available to work on?

**Comment by annieappflowy** [comment]
I've assigned it to you. Thanks, @Nike682631 , for offering the help! If you need help, please feel free to contact @appflowy on Discord.

**Comment by annieappflowy** [comment]
Hi @Nike682631 , can you update the status on this issue? Thanks

**Comment by abichinger** [comment]
@annieappflowy I would like to work on this

**Comment by annieappflowy** [comment]
@abichinger , assigned. thanks!
