### ISSUE TITLE
[FR] Self-hosted users can modify the publishing page domain name

### ISSUE THREAD

**Issue by smartyhero** [AppFlowy-IO/AppFlowy#6902]
### Description

I'm not sure if this is a feature or a bug
Users can modify the site domain name on the site settings page
The site domain name must be at least the domain name of the appflowy server, not all of them are appflowy.com

### Impact

All users who like to play around with appflowy
All users who want to build their own site with appflowy

**Comment by LucasXu0** [comment]
@speed2exe Do you support customizing the namespace and pathname for the self-hosted server?

**Comment by speed2exe** [comment]
@LucasXu0 This is supported in the self-host server. However Appflowy Web is not included in the self-host appflowy-cloud, see https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/873.

**Comment by LucasXu0** [comment]
Closed as a duplicate. Please follow this issue at the [link](https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/873).
