### ISSUE TITLE
[Bug] unable to use keyboards to select a programming language in the code blcok

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6905]
### Bug Description

code block: unable to use the down arrow to select a language in the menu
![Xnip2024-12-02_15-22-30](https://github.com/user-attachments/assets/b26aad80-2f44-406c-bac6-945f2ee20ad1)

### How to Reproduce

as seen in the description

### Expected Behavior

I can use the nav keys to select an item in the menu

### Operating System

macOS

### AppFlowy Version(s)

v0.7.4

**Comment by asjqkkkk** [comment]
Waiting for it
