### ISSUE TITLE
[FR] Shortcut for collapse the left sidebar

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#692]
We enable the collapse of the left sidebar by clicking the collapsed button.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/86001920/180593644-55e22e12-93f4-4a15-b100-549341cf6f4c.png">

We can add a shortcut and tooltip for collapsing the left sidebar. 
<img width="195" alt="image" src="https://user-images.githubusercontent.com/86001920/180593674-db29d954-d694-42ae-b0c9-58e4a41e2f27.png">

**Comment by richardshiue** [comment]
With #789 merged, this feature has been implemented! Closing as completed
