### ISSUE TITLE
[FR] Improve the grid number unit test in the backend

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#693]
The existing tests for the grid number field are in [here](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/number_type_option/number_tests.rs) out.

Expected:
Add more unit tests to cover more corner cases.

**Comment by Nike682631** [comment]
@appflowy is this issue available to work on?

**Comment by annieappflowy** [comment]
Hi @Nike682631 , thanks for offering the help. I've assigned the issue to you. If you have any questions, please reach out to @appflowy on Discord.

**Comment by annieappflowy** [comment]
@Nike682631 , can you please update your progress on this issue? Do you need any help from me? Thanks!
