### ISSUE TITLE
[FR] Improve the grid URL unit test in the backend

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#694]
The existing tests for the grid URL field are in [here](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/url_type_option/url_tests.rs) out.

Expected:
Add more unit tests to cover more corner cases.

**Comment by Nike682631** [comment]
@appflowy is this issue available to work on?

**Comment by Cavalletta98** [comment]
@appflowy is this issue available to work on?

**Comment by ayushanand308** [comment]
@appflowy Can I work on this issue for github octernship?

**Comment by Heccubernny** [comment]
@appflow is this issue still available, and can I be assigned to it?

**Comment by annieappflowy** [comment]
@ayushanand308 , to clarify, this is not an Octernship project

**Comment by annieappflowy** [comment]
This issue was completed 
@ayushanand308 , @Heccubernny  thanks for offering the help though.
There are other newcomer friendly issues: https://github.com/orgs/AppFlowy-IO/projects/5/views/4

**Comment by Heccubernny** [comment]
@ayushanand308 okay I will check it out. Thanks for the response
