### ISSUE TITLE
[FR] Improve the grid date unit test in the backend

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#695]
The existing tests for the grid date field are in [here](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/rust-lib/flowy-grid/src/services/field/type_options/date_type_option/date_tests.rs) out.

Expected:
Add more unit tests to cover more corner cases.

**Comment by Nike682631** [comment]
@appflowy is this issue available to work on?

**Comment by annieappflowy** [comment]
Hi @Nike682631 , I've assigned this issue to you. Thank you for contributing to AppFlowy.

**Comment by annieappflowy** [comment]
@Nike682631 , can you update your progress on this issue?

**Comment by richardshiue** [comment]
Hey @annieappflowy! May I work on this?

**Comment by annieappflowy** [comment]
@richardshiue sure, thanks for offering the help! Just assigned to you
We are not able to reach you, @Nike682631. If you are interested in working on similar topics, let me know. We can find other interesting stuff for you to do.
