### ISSUE TITLE
[Bug] Esc should close the Find/Replace pop-up

### ISSUE THREAD

**Issue by dandv** [AppFlowy-IO/AppFlowy#6955]
### Bug Description

In a document, the Ctrl+F dialog can't be closed by pressing Esc.

### How to Reproduce

1. Ctrl+F
2. Type something
3. Press <kbd>Esc</kbd>

### Expected Behavior

Pretty much any editor will close the Find dialog when the user presses Esc.

### Operating System

Fedora 38

### AppFlowy Version(s)

0.7.6

**Comment by asjqkkkk** [comment]
I'll solve it
