### ISSUE TITLE
[Bug] No way to escape inline code in the end of inline code text

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#6957]
### Bug Description

<img width="220" alt="image" src="https://github.com/user-attachments/assets/7f5d942b-c993-405d-bd05-b5967fd3ac8b">

### How to Reproduce

format text as inline code using the float toolbar
try to escape the syntax using keyboard

### Expected Behavior

I can escape the inline code text

### Operating System

macOS

### AppFlowy Version(s)

v0.7.7

**Comment by LucasXu0** [comment]
Resolved in https://github.com/AppFlowy-IO/AppFlowy/pull/6978
