### ISSUE TITLE
[FR] Implement AppFlowy style toggle

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#697]
The toggle in the setting page fits the AppFlowy style. 
<img width="906" alt="image" src="https://user-images.githubusercontent.com/86001920/180598979-d26d1fc9-e2b7-469d-a9f6-d486193a9d77.png">

You can get the AppFlowy design spec in this [link](https://www.figma.com/file/X1R9i5HAFtJSNIKOPPW7yK/AppFlowy-%5BUI%5D%5BMaster%5D?node-id=15%3A4285
) 

![image](https://user-images.githubusercontent.com/86001920/180599180-b69c44ed-5710-4647-b75e-dde9730833c5.png)

**Comment by tilucasoli** [comment]
Can I do this task?

**Comment by appflowy** [comment]
No problem, I will assign this task to you. You DM me if you have any questions.

**Comment by MikeWallaceDev** [comment]
Fixed with PR #720 
Thank you @tilucasoli !
