### ISSUE TITLE
[Bug] Korean Input Bug Issue

### ISSUE THREAD

**Issue by EC-Sol** [AppFlowy-IO/AppFlowy#6977]
**Describe the bug**
When input korean character they become weired.

**To Reproduce**
Just Input Korean.

**Expected behavior**
Normal korean character type.
```
한국어
입력
```

**Screenshots**

https://github.com/AppFlowy-IO/AppFlowy/assets/12044563/3536521c-0f05-421f-9f4f-42d60b11526f

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: Appflowy App
 - Version 0.5.5

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by annieappflowy** [comment]
@EC-Sol , this was fixed. Let us know if the issue persists.
