### ISSUE TITLE
[FR] Display the number of rows in the grid

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#698]
For the moment, the grid doesn't display the number of rows.  We can implement it according to the design [spec](https://www.figma.com/file/X1R9i5HAFtJSNIKOPPW7yK/AppFlowy-%5BUI%5D%5BMaster%5D?node-id=354%3A2794).

![image](https://user-images.githubusercontent.com/86001920/180599429-990f9fbf-3010-4bab-aa75-c7c42b0481c9.png)

**Comment by thisisamank** [comment]
Hey! can i work on this issue?

**Comment by annieappflowy** [comment]
> Hey! can i work on this issue?

Thanks for offering the help. I've assigned the issue to you, and @appflowy is your mentor on this issue. Please feel free to reach out to him on Discord for help. Look forward to seeing your contributions.

**Comment by annieappflowy** [comment]
https://github.com/AppFlowy-IO/AppFlowy/commit/d955b6ef7ee9e30d32839b3fa5b55e95840fa9a2
Thanks @thisisamank for working on this. 
This feature is released under v0.0.5
