### ISSUE TITLE
[Bug] AppFlowy cannot preview images pasted from screenshot software.

### ISSUE THREAD

**Issue by qingmoming** [AppFlowy-IO/AppFlowy#6996]
### Bug Description

Unable to double-click preview, images pasted by screenshot software, the key point is that the screenshot software directly pastes the image into AppFlowy, and the image displays normally by default, but double-clicking the image does not work. After double-clicking, only an "open image" button appears, and clicking the button shows "application cannot open -50".

### How to Reproduce

Take a screenshot using the screenshot software and paste it directly into the AppFlowy document. Double-click the image to reproduce it.

### Expected Behavior

Hope to be able to correctly double-click preview images pasted from screenshots.

### Operating System

macOS 14.5 macOS 15.2 iOS 18.2

### AppFlowy Version(s)

0.7.7

### Screenshots

![image](https://github.com/user-attachments/assets/6300cf04-df5e-401f-8173-4cf34f7c5e1d)
![image](https://github.com/user-attachments/assets/040b97b9-88db-4a1c-bad5-f99ca9f1382f)

**Comment by LucasXu0** [comment]
Hi, @qingmoming. This issue will be resolved in the next release.
