### ISSUE TITLE
[Bug] Language selector does not save language when reopening

### ISSUE THREAD

**Issue by sunny7dusk** [AppFlowy-IO/AppFlowy#700]
**Describe the bug**
When using the language selector to use a language, UI changes to reflect it. However, if you close the app and reopen it, the language selector remains at  the previously chosen language but the language of the UI returns to English.

**To Reproduce**
1. Go to settings through the settings icon on the top left, then pick the language option on the sidebar
2. Pick any non-English language. You should see the UI updating the locale.
3. Close and reopen the app.
4. When the app reopens, you should see that the language has returned to English.
5. Navigate to settings -> language again, you should see the language selector is at the language previously selected.

**Expected behavior**
When choosing a new language, it should have saved the locale even after closing and opening a new session.

**Screenshots**
This is when I reopen Flowly after changing language.
![image](https://user-images.githubusercontent.com/71191616/180616808-6432896f-24f4-45a9-bbdc-80a7ebdcf7fc.png)

**Desktop (please complete the following information):**
 - OS -> Windows 10 with WSL2

**Comment by annieappflowy** [comment]
@sunny7dusk would you like to work on this?

**Comment by sunny7dusk** [comment]
I can take a look at this @annieappflowy

**Comment by annieappflowy** [comment]
@sunny7dusk , any update on this? If you no longer work on this issue, please let me know so I can release it to other contributors.

**Comment by sunny7dusk** [comment]
Sorry about that, can look into this soon

**Comment by sunny7dusk** [comment]
I have a PR up for this issue @annieappflowy

**Comment by annieappflowy** [comment]
@sunny7dusk , thank you. It is merged? Can you share the link?

**Comment by annieappflowy** [comment]
Great work. Closing this issue.
