### ISSUE TITLE
[Bug]  Simple Table 2.0: can't add blocks like lists, images and code blocks

### ISSUE THREAD

**Issue by casainho** [AppFlowy-IO/AppFlowy#7010]
### Bug Description

On PC Linux app, can't use the '/' to add new blocks like lists (bullet, numbered, toggle, todo). Exceptionally, I can write some small text and select it, to have access to the menu that will let me change the text to a list, but not to an image of code block:

![image](https://github.com/user-attachments/assets/30a4e9a8-4c68-49a3-b32c-57ed601bd735)

### How to Reproduce

Write the '/' inside a cell.

### Expected Behavior

Should be able to select some possible blocks like lists.

### Operating System

Linux Ubuntu 24.04 x86

### AppFlowy Version(s)

0.7.8

**Comment by LucasXu0** [comment]
@casainho The slash menu support is in progress. Currently, you can use the floating toolbar or markdown syntax. For example:

- Use '- ' to insert a bulleted list
- Use '1. ' to insert a numbered list
- Use '```' to insert a code block
