### ISSUE TITLE
[FR] Copy Pasting Raw Mark Down text

### ISSUE THREAD

**Issue by renjithsamuel** [AppFlowy-IO/AppFlowy#7023]
### Impact

- Everyone will be benefiting from this change, for instance the application itself encourages using markdown text, by when typing markdown automatically recognizing and converting into stylized text, we should extend going in the direction of markdown text usage.

**Comment by LucasXu0** [comment]
Aside from 'ctrl+shift+v,' we should provide an option to paste plain text in the context menu for users who may not know this shortcut.

<img width="254" alt="Screenshot 2024-12-23 at 10 16 43" src="https://github.com/user-attachments/assets/2eddbc52-4e18-40bb-9ac8-cfaf49b4d0c9" />
