### ISSUE TITLE
[Bug] Left and right arrows are flipped

### ISSUE THREAD

**Issue by davystrong** [AppFlowy-IO/AppFlowy#7027]
### Bug Description

I feel I may have done something to cause this as it hasn't been reported by anyone else, and it's quite obvious. My left and right arrows are flipped, i.e., pressing the left arrow moves to the right. Up and down work correctly.

### How to Reproduce

* Write text
* Press right arrow
* Watch cursor go to the left

### Expected Behavior

* Write text
* Press right arrow
* Watch cursor go to the right

### Operating System

macOS 14.6.1

### AppFlowy Version(s)

0.7.7

**Comment by Xazin** [comment]
Can you go to Settings -> Shortcuts and press "Reset default", then try again?

See screenshot:
![image](https://github.com/user-attachments/assets/295ff500-0ddf-4ee8-9c75-cc08bd052bbe)

**Comment by davystrong** [comment]
Excellent, thank you! Didn't know that was an option!
