### ISSUE TITLE
[Bug] Duplicating a document with a linked kanban board does not change links

### ISSUE THREAD

**Issue by SOSeriously** [AppFlowy-IO/AppFlowy#7065]
### Bug Description

When duplicating a document with a linked kanban board the document does not update the link to the kanban board that was duplicated with the document. Editing the duplicated kanban board through the document actually edits the original kanban board.

### How to Reproduce

- Create a document
- Add kanban board as an child object to the document
- Link the kanban board in the document
- Duplicate the document (The kanban board should be automatically duplicated as well)
- Edit the duplicated kanban board through the duplicated document

### Expected Behavior

The document should update the links of the linked objects when duplicating the document.

### Operating System

Fedora 41 KDE with Wayland

### AppFlowy Version(s)

0.7.8 Flatpack

**Comment by LucasXu0** [comment]
Closed as duplicated. Follow this issue at this [link](https://github.com/AppFlowy-IO/AppFlowy/issues/5866).
