### ISSUE TITLE
[Bug] New tab in window duplicates data

### ISSUE THREAD

**Issue by VVVAD** [AppFlowy-IO/AppFlowy#7082]
### Bug Description

I don't know if it's a bug, but when I add new tab of sorts, ex. Grid, it duplicates the data from the other grid in the same window.
I feel like adding a new tab of something in the same window will add a clean tab.
If it's not a bug, close the report 😅
https://github.com/user-attachments/assets/087cff9c-89a7-40f1-931e-d85011f54f1c

### How to Reproduce

Just open a page, add a grid, change something in it, add a new grid on the same page.

### Expected Behavior

Clean tab and not a duplicated from the other tab by the same type.

### Operating System

Windows 10

### AppFlowy Version(s)

v0.7.8

**Comment by appflowy** [comment]
@VVVAD It’s not a bug. When you create a new database view, it may appear as a duplicate, but both views share the same underlying database.
