### ISSUE TITLE
[Question] WebSocketException: Connection to 'http://127.0.0.1:50489/D9voQYkoTug=/ws#' was not upgraded to websocket

### ISSUE THREAD

**Issue by xurenda** [AppFlowy-IO/appflowy#71]
When I run front-end and back-end projects.
In the front-end project console output:
```
Exception attempting to connect to the VM Service: WebSocketException: Connection to 'http://127.0.0.1:50489/D9voQYkoTug=/ws#' was not upgraded to websocket
This was attempt #1200. Will retry in 0:00:01.600000.
```
Back-end project listening to port 8000, to start a front-end project, you need to specify the server port:
```
flutter run --host-vmservice-port 8000
```
But it seems that there is a problem with the WebSocket port.
What can I do to make WebSocket work properly? Adding configuration or forgetting to start some services? Thank you for your help!

**Comment by appflowy** [comment]
The frontend with the backend is not ready yet. I'll make a docker image for later use.
