### ISSUE TITLE
[FR] Collaboration Server

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#714]

**Comment by heyakyra** [comment]
Looks like this was delayed from [Q4 last year](https://github.com/AppFlowy-IO/AppFlowy/discussions/565#discussioncomment-4697576) and will instead kick off in around April: 
https://github.com/AppFlowy-IO/AppFlowy/discussions/1715

Presumably this ties into https://github.com/AppFlowy-IO/AppFlowy/issues/246 also

**Comment by c-jw-Medic** [comment]
@annieappflowy I'm just going to leave a big +1 on this issue.  A server-client model to allow collaboration would change AppFlowy from the software I am tinkering with for my own use to the software that I push my whole team to use.

Thanks for your great work on this project.

**Comment by KalynDavis** [comment]
@annieappflowy +1 here. I'm evaluating collaboration software for my startup and this would be the defining feature that would put us on AppFlowy.

**Comment by annieappflowy** [comment]
Team collaboration is live! Add members to your workspace to edit and collaborate on pages together. Please give it a try!

**Comment by Evengard** [comment]
Any guides on how to setup it as a self-hosted solution?
