### ISSUE TITLE
[Bug] Unable to delete content after typing Chinese characters

### ISSUE THREAD

**Issue by Fnll** [AppFlowy-IO/AppFlowy#735]
**Describe the bug**
As the title described, content can not be deleted after typing Chinese characters.

**To Reproduce**
1. create a new doc
2. type a Chinese character
3. delete any character

**Expected behavior**
should be possible to delete content.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser -
 - Version 0.0.4.1

**Comment by ziyziyziy888** [comment]
Please fix this bug, it is very hard to use in Chinese

**Comment by annieappflowy** [comment]
<img width="268" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/3b3e9677-3249-45d0-865e-c2ef9a003afc">
Fixed. Please give it a try with the latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases)
