### ISSUE TITLE
[FR] Unobtrusive and unified renaming

### ISSUE THREAD

**Issue by polypixeldev** [AppFlowy-IO/AppFlowy#737]
**1~3 main use cases of the proposed feature**
When renaming a page from the sidebar a big popup that blurs the rest of the app comes up with the prompt to rename. I would prefer if instead of the popup, the page name itself in the sidebar became a text input to change the name there. In addition, when renaming a root page, I have to right click on the name to get the context menu, but when renaming a nested page, I have to use the double dots on the right. I would prefer if I had the option to right click on the name of the nested page to get the context menu as well as the double dots.

**What types of users can benefit from using your proposed feature**
Users that prefer a simple and unified experience without having to guess how to rename something.

**Comment by annieappflowy** [comment]
Now you can configure it in the settings:
<img width="550" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/2ded1fe3-7b70-46e9-9702-8764dad895d9">
