### ISSUE TITLE
[Bug] Change the year in the copyright of website footer  

### ISSUE THREAD

**Issue by yeganathan18** [AppFlowy-IO/AppFlowy#740]
**Describe the bug**
The copyright year mentioned in the footer seems to be outdated.

**To Reproduce**
1. Go to [appflowy website](https://www.appflowy.io/)
2. Scroll down footer area at the bottom
4. See copyright area and the year mentioned

**Expected behavior**
We could either update the current year in the copyright, or maybe something like this would also work `2021 - present`

**Screenshots**
<img width="1792" alt="Screenshot 2022-07-30 at 11 58 15 AM" src="https://user-images.githubusercontent.com/63534555/181878031-c7924317-2f35-49ba-b75a-588b91c54a2d.png">

**Comment by annieappflowy** [comment]
Done. Thank you!
