### ISSUE TITLE
[Bug] App d'o nt run in Fedora 36

### ISSUE THREAD

**Issue by yodatak** [AppFlowy-IO/AppFlowy#742]
**Describe the bug**

**To Reproduce**
Fedora 36
./app_flowy
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdart_ffi.so': libssl.so.1.1: No file 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      _open (package:flowy_sdk/ffi.dart:23)
#3      _dl (package:flowy_sdk/ffi.dart:10)
#4      _set_stream_port (package:flowy_sdk/ffi.dart)
#5      set_stream_port (package:flowy_sdk/ffi.dart)
#6      FlowySDK.init (package:flowy_sdk/flowy_sdk.dart:32)
#7      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:13)
#8      InitRustSDKTask.initialize.<anonymous closure> (package:app_flowy/startup/tasks/rust_sdk.dart:12)
#9      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#10     InitRustSDKTask.initialize (package:app_flowy/startup/tasks/rust_sdk.dart:12)
<asynchronous suspension>
#11     AppLauncher.launch (package:app_flowy/startup/startup.dart:99)
<asynchronous suspension>

**Comment by thuLink** [comment]
You can fix this by installing openssl1.1
`sudo dnf install openssl1.1`

**Comment by apomalyn** [comment]
@yodatak were you able to test the solution proposed by LinkTTT?
If that resolved your issue, would you mind closing this issue? 😄

**Comment by yodatak** [comment]
It work now thanks but i think we have to documentation this or remove this old dependency or flatpak it ;)

**Comment by MindSetFPS** [comment]
Didn´t work for me, fodora 37.

**Comment by Anvith00** [comment]
@MindSetFPS You'll require installing the `openssl-devel` package in Fedora.
```bash
sudo dnf install openssl-devel
```

If you are however building from source, these are the packages you'll need to install:
```bash
sudo dnf install sqlite-devel keybinder3-devel clang cmake ninja-build openssl-devel
```

**Comment by yodatak** [comment]
In the flatapk version if don't fix anything because it had to be bundle with flatpak but why we need a so old library bytheway

**Comment by yodatak** [comment]
and the packages is deprecated in Fedora  
https://fedoraproject.org/wiki/Changes/DeprecateOpensslCompat

**Comment by Anvith00** [comment]
@yodatak If you're trying to run the tarball release, make sure you have `openssl` or `openssl-devel` and `keybinder-3` installed.
