### ISSUE TITLE
[FR] Ctrl + Backspace in Editor

### ISSUE THREAD

**Issue by Yongbeom-Kim** [AppFlowy-IO/AppFlowy#75]
**Describe the bug**
Pressing Ctrl + Backspace does nothing, when it should delete a word.

**To Reproduce**
1. Go and create a page
2. Type a couple words inside, delimited by spaces
3. Press Ctrl + Backspace
4. Nothing happens

**Expected behavior**
A word to be deleted, Ctrl + Right/LeftArrow navigates 'by word' as well, so I suppose this is a bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/63487502/142853024-be1918df-b4e9-4fae-9346-b0210fb9b8af.png)
For example, Ctrl + Backspace here should delete a "sdf", but does nothing

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 10.0.22000 Build 22000
 - Browser: Vivaldi 4.3.2439.65 / Chrome 94.0.4606.114
 - Version: 0.0.2

**Comment by annieappflowy** [comment]
We have not supported **keyboard shortcut**, which is in development, so this could be the cause

**Comment by gianpaj** [comment]
Is this something that can be easily enabled by configuring `flutter-quill` editor?

https://pub.dev/documentation/flutter_quill/latest/widgets_keyboard_listener/widgets_keyboard_listener-library.html

I can look into if it's not too complicated – I haven't used rust or flutter aside of hello world

**Comment by annieappflowy** [comment]
> Is this something that can be easily enabled by configuring `flutter-quill` editor?
> 
> https://pub.dev/documentation/flutter_quill/latest/widgets_keyboard_listener/widgets_keyboard_listener-library.html
> 
> I can look into if it's not too complicated – I haven't used rust or flutter aside of hello world

@gianpaj Given our evaluation of the work, this isn't a challenging issue. We think it's suitable for devs with some experience. If you would like to give it a try, that would be awesome.

**Comment by ZibingZhang** [comment]
On a similar vein, the `home` and `end` keys don't work on Windows.

Using `Ctrl-Backspace` and navigation with `home` and `end`, especially for selection and deletion, is a fairly commonly used keyboard shortcut, the addition of which would result in a nice QOL change.

**Comment by tqwewe** [comment]
In addition, I am on mac, and option backspace should delete a single word, and command backspace should delete to the start of the line.
