### ISSUE TITLE
[Issue] https://www.appflowy.io/ site "expired"

### ISSUE THREAD

**Issue by ffos** [AppFlowy-IO/AppFlowy#756]
Site expired https://www.appflowy.io/
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7200978/182322256-3b76792f-fda3-439a-b4da-2709dddb6b49.png">

**Comment by annieappflowy** [comment]
Thanks a lot for reporting it. I've fixed it. Could you please try it again?

**Comment by crydotsnake** [comment]
Its working! :)
