### ISSUE TITLE
[Bug] App doesn't open fully / cant be resized when using fractional scaling on linux

### ISSUE THREAD

**Issue by aryaman31** [AppFlowy-IO/AppFlowy#762]
**Describe the bug**
Running the app (```./app_flowy```), opens the app but it cannot be resized or maximized. The side bars are missing as well. I have added pictures for the same (screenshot 1). I managed to fix the issue by using either 100% or 200% scaling. Everytime I used 125% or 150% i would get the same issue as shown in the image. 

**To Reproduce**
1. Set fractional scaling to 125 or 150. 
2. Run the app by running ```./app_flowy```. 

**Expected behavior**
I would expect the app to look the way it does on the website with the side bars and the full page shown. I've added an image to show the expected behavior on my machine (screenshot 2). 

**Screenshots**
screenshot 1:
![image](https://user-images.githubusercontent.com/47158071/182619169-f5529bea-59d6-4d68-87ff-b9ba7058788c.png)
screenshot 2:
![image](https://user-images.githubusercontent.com/47158071/182620020-f9f4117f-dc03-4169-8223-83807401d761.png)

**Desktop**
 - OS: Pop!_OS 22.04 LTS
 - Browser: Chrome
 - Graphics: radeon graphics
 - Hardware model: Lenovo Legion 5 Pro 16ACH6H
 - Gnome version: 42.2

**Additional context**
 - Screen resolution: 2560 x 1600 (16:10)
 - Refresh rate: 60Hz

**Comment by annieappflowy** [comment]
related to https://github.com/AppFlowy-IO/AppFlowy/issues/363

**Comment by KindHeartedTraveler** [comment]
same problem with Ubuntu 22.04.1 LTS.  I have a 2K and a 4K  monitor. The flowy's UI is too small and can't be resized or maximized when I set displays scaling to over 100%.But it works well under the default 100% scaling.

**Desktop:**
 - OS: Ubuntu 22.04.1 LTS
 - Browser: Chrome
 - Version:  GNOME  42.4

**Additional context**
 - 2K(2560 x 1040) and 4K (3840x2160) monitor.

**Comment by evdcush** [comment]
Same issue with necessary 150% fractional scaling on a 4k display.

Deets:

```
                          ./+o+-       
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-47-generic
           .++ .:/++++++/-.+sss/`      Uptime: 3h 39m
         .:++o:  /++++++++/:--:/-      Packages: 2763
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8.1
       .:+o:+o/.          `+sssoo+/    Resolution: 5120x2880
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 41.7
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: 
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Yaru
        \+.++o+o``-````.:ohdhhhhh+     Font: Inter 14
         `:o+++ `ohhhhhhhhyo++os:      Disk: 358G / 916G (42%)
           .o:`.syhhhhhhh/.oo++o`      CPU: AMD Ryzen 5 5600 6-Core @ 12x 3.5GHz
               /osyyyyyyo++ooo+++/     GPU: NVIDIA GeForce GTX 1070
                   ````` +oo+++o\:     RAM: 8654MiB / 32003MiB
                          `oo++.  
```

![20221919-140101_screenshot](https://user-images.githubusercontent.com/28853935/190952735-a0ec7aab-bf3d-444f-99f8-211eeb77905a.png)

**Comment by annieappflowy** [comment]
Hi guys,

This should be fixed in https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.1.0
Please give it a try.

Thanks
