### ISSUE TITLE
[FR] Right click for context menu in sidebar tree

### ISSUE THREAD

**Issue by vincentdchan** [AppFlowy-IO/AppFlowy#767]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/2352832/182989550-0fc0922a-9f3f-47d3-97a1-b914c2170576.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/2352832/182989405-e1c416ac-f6a6-46ae-95ca-43dcf2c624ad.png">

**Current:**
When the "more button" is clicked, the dropdown menu is shown. But when the user right clicks on the button, nothing happens.

**Expected:**
When the user right clicks on the button, the dropdown menu shows at the position of the cursor.

**Comment by aryaman31** [comment]
Hey, can I work on this? I have worked on small flutter apps before.

**Comment by vincentdchan** [comment]
Absolutely

**Comment by vincentdchan** [comment]
If you need help. Join our discord group and DM me.
