### ISSUE TITLE
[Bug] Collapsing button is disappearing on smallest screen. 

### ISSUE THREAD

**Issue by ChiragKr04** [AppFlowy-IO/AppFlowy#796]
**Describe the bug**
On the smallest window width collapse icon is showing and after clicking on that it is disappearing after clicking and does not doing anything. Wierd behavior.

**To Reproduce**
1. On home page and window width as max.
2. Click on `collapse button (Right side of appflowy icon)`
3. Side menu will hide after that.
4. Now resize the window to lowest possible width size.
5. Now click on `collapse button icon`.
6. See error: Now `collapse button icon` will disappear and `side menu wont open`. 

**Expected behavior**
It should open `side menu` on smallest width of window. Or open as `Drawer` in smallest width window.

**Screenshots**
1. Click on the `icon`
![image](https://user-images.githubusercontent.com/62651867/183571958-9423331f-d9ac-4e11-9f99-cd928e7a777f.png)
2. `Side menu` will collapse
![image](https://user-images.githubusercontent.com/62651867/183572240-eef86d40-405e-4bf9-924d-9b7e7c0a30e4.png)
3. Now resize to smallest screen and again click on the icon. It wont open side menu and the icon will disappear.
![image](https://user-images.githubusercontent.com/62651867/183572358-cbd22239-3c71-4c56-a433-196284db5427.png)
![image](https://user-images.githubusercontent.com/62651867/183572440-e1993351-9994-4dc8-99b0-3979acc6267d.png)

Now the icon is disappeared.

**Desktop (please complete the following information):**
- OS: Windows 11, MacOS 12.5, Linux 
- version: 0.0.4.1

**Comment by apomalyn** [comment]
I was able to reproduce the bug on MacOS. So this is confirmed for at least Windows and MacOS.

@ChiragKr04 would you mind adding the following at the end of the issue description:

```
- OS: Windows 11, MacOS 12.5
- version: 0.0.4.1
```

Thank you for the issue!! 😄

**Comment by ChiragKr04** [comment]
> I was able to reproduce the bug on MacOS. So this is confirmed for at least Windows and MacOS.
> 
> @ChiragKr04 would you mind adding the following at the end of the issue description:
> 
> ```
> - OS: Windows 11, MacOS 12.5
> - version: 0.0.4.1
> ```
> 
> Thank you for the issue!! 😄

So what should be the possible fix? Just removing an icon or major UI/UX changes?

**Comment by Poly-Pixel** [comment]
I am able to reproduce on Linux as well. I can look into this tomorrow.

**Comment by annieappflowy** [comment]
Thanks @Poly-Pixel for offering the help. Please feel free to reach out if you need any help from me.
