### ISSUE TITLE
[FR] Handle `Esc` key in rename dialog

### ISSUE THREAD

**Issue by vincentdchan** [AppFlowy-IO/AppFlowy#809]
1. Right click on the sidebar item.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/2352832/183892998-752e7632-3469-4738-a6cf-7e95464dbddb.png">

2. Click on "rename" button.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/2352832/183893055-a850983c-a1d2-47ce-8d82-4291254c11cc.png">

**Expect:**
After the dialog appears, press the "Esc" key, and the dialog should close.

**Comment by ChiragKr04** [comment]
Can I work on this?

**Comment by vincentdchan** [comment]
Sure
