### ISSUE TITLE
[Bug] The position of cursor is wrong.

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#816]
<img width="101" alt="" src="https://user-images.githubusercontent.com/11863087/184064872-f6c8f088-821e-4bde-b154-9848c12f3a50.png">

**Comment by LucasXu0** [comment]
too lower. need to be aligned in the center.

**Comment by ChiragKr04** [comment]
How to reproduce this bug? On which page exactly?

**Comment by annieappflowy** [comment]
Is this resolved? @LucasXu0

**Comment by LucasXu0** [comment]
This bug has been resolved.
