### ISSUE TITLE
[Bug] Fail "cargo make flowy_dev" script if pub global target isn't added to Path

### ISSUE THREAD

**Issue by Hari-07** [AppFlowy-IO/appflowy#83]
**Describe the bug**
dart pub global installs to /.pub-cache/bin and throws a warning if it isn't added to Path. Build continues uninterrupted. If user doesn't add it to path, generate protobuf fails

**Expected behavior**
Script execution should get interrupted if this warning is thrown

**Comment by pdckxd** [comment]
Thanks @Hari-07 . I will take up this issue. @annieappflowy to be aware

**Comment by pdckxd** [comment]
Commit 1ee5a9402b22f686fbfdb950badbf0031f7cfb67 remove sub task "install_protobuf" from flowy_dev task. This issue can be closed.
