### ISSUE TITLE
[FR] Instant search

### ISSUE THREAD

**Issue by rolltidehero** [AppFlowy-IO/AppFlowy#830]
**1~3 main use cases of the proposed feature**

Algolia has a free one but it's capped to a certain amount of requests per month.

I think it's still worth integrating if you don't want to code a unique one.

Thoughts?

![image](https://user-images.githubusercontent.com/11590510/184272545-041901b4-92d0-4e29-9750-be76c15cd07b.png)

![image](https://user-images.githubusercontent.com/11590510/184278940-78b562e9-9f08-4873-a4ec-49fecd219576.png)

**what types of users can benefit from using your proposed feature**
All users who search and the web server for not having to load a new page.

**Comment by annieappflowy** [comment]
Thanks for sharing this search tool. We'll consider it when start developing the search function.

**Comment by annieappflowy** [comment]
#2232

**Comment by Xazin** [comment]
Closed as duplicate
