### ISSUE TITLE
[FR] Add hover and selected state of Trash

### ISSUE THREAD

**Issue by vincentdchan** [AppFlowy-IO/AppFlowy#834]
When the Trash tab is selected, there is no hover state.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/2352832/184302822-2aa1b648-3d63-458e-80a8-f29bd36152a3.png">

**Expect:**

Add hover and selected background of Trash corresponding to the item of the panel:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/2352832/184303025-8b5359ba-cdc6-4221-ae08-730e236625a1.png">

**Comment by IMPranshu** [comment]
Please assign this to me.

**Comment by rasyidmi** [comment]
I am interested in solving this issue. Can you assign me?

**Comment by richardshiue** [comment]
Hello @IMPranshu, have you made any progress on this? If not, @rasyidmi would like to take a crack at it

**Comment by rasyidmi** [comment]
Hello @richardshiue I had write my code and the video of the result is [here](https://drive.google.com/file/d/1qDIW75iBAvYm42zlHyRYxr7m-LSKSS1G/view?usp=share_link)

Can you assign me so you review it?

Thank you.

**Comment by rasyidmi** [comment]
This is the link for my commit

[](https://github.com/rasyidmi/AppFlowy/commit/dd40db0a9c05c513cd2b6a9b9b0dfd17f0ab7c72)

**Comment by richardshiue** [comment]
Got it, thanks for working on this! I've assigned the issue to you

**Comment by rasyidmi** [comment]
> Got it, thanks for working on this! I've assigned the issue to you

Thank you @richardshiue can't wait for the review😄

**Comment by richardshiue** [comment]
With #1513 merged, this task is complete!
