### ISSUE TITLE
[Bug] Resizing `Trash` window is changing screens.

### ISSUE THREAD

**Issue by ChiragKr04** [AppFlowy-IO/AppFlowy#856]
**Describe the bug**
When the `Trash` page is opened resizing the window changes the main screen.

**To Reproduce**
1. Go to the `Trash` page.
2. Now resize the window
3. It will change the screen.

**Expected behavior**
It should not change the screen when resizing the window,

**Desktop (please complete the following information):**
 - OS: `Windows 11`
 - `Version 0.04`

**Comment by richardshiue** [comment]
Also reproducible on Linux

**Comment by Poly-Pixel** [comment]
I'm looking into this right now

**Comment by annieappflowy** [comment]
@Poly-Pixel , big thanks! Just assigned it to you.
