### ISSUE TITLE
[Bug] chrome build failed

### ISSUE THREAD

**Issue by Malenconiaprincep** [AppFlowy-IO/appflowy#86]
**Describe the bug**

**To Reproduce**
1. Follow your step 1,2,3,4
2. Go to the Run and Debug tab and then click the run button.
3. Device choose Chrome

**Screenshots**

![image](https://user-images.githubusercontent.com/6262739/142996834-ab58d1a2-bd2c-420a-b148-1552997fec3f.png)

**Desktop (please complete the following information):**
 - OS: MacOs BigSur 11.5.2
 - Browser chrome
 - Version [[e.g. 22]](https://github.com/AppFlowy-IO/appflowy/commit/6c9fa781cfce7dad3e2e4c4825fd45270b8742f0)

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by irfanbacker** [comment]
AppFlowy supports only macOS, Windows and Linux as of now.

**Comment by Malenconiaprincep** [comment]
okey
