### ISSUE TITLE
[Bug] Outdated documentation

### ISSUE THREAD

**Issue by Leuug** [AppFlowy-IO/AppFlowy#864]
On the section "Building for Linux" in the documentation, on step 2, it says to run an script, but this script doesn't exists:
![image](https://user-images.githubusercontent.com/58122451/184976892-0ebc4e49-1c00-43d7-bb15-32ecc29d7808.png)

**Comment by appflowy** [comment]
Hi, @Leuug , please check out whether your current path is frontend or not. 

![image](https://user-images.githubusercontent.com/86001920/185007105-0784df76-3bee-4217-b6bd-a872101dcdbb.png)

**Comment by Leuug** [comment]
I had downloaded the source code from de 0.0.4 release, for some reason this script is not present there. Thank you.
