### ISSUE TITLE
[Bug] Grid Type color in black theme does not have a good constrat

### ISSUE THREAD

**Issue by yodatak** [AppFlowy-IO/AppFlowy#875]
**Describe the bug**
In the black theme the text in color are not visible because of bad contrast we should have a better contrast 

![image](https://user-images.githubusercontent.com/704477/185429171-716652f5-8f0b-4f36-ab91-ff1c2afc283c.png)

**Comment by ChiragKr04** [comment]
Will changing just text to `black` is a possible fix? Or require a new UI design? @annieappflowy

**Comment by annieappflowy** [comment]
@ChiragKr04 , it requires a design. I'm sourcing a designer to get it fixed.

**Comment by yodatak** [comment]
Any news on this one ? ^

**Comment by richardshiue** [comment]
Hey @yodatak! There is a new dark-mode design coming soon, see the technical roadmap here: https://github.com/AppFlowy-IO/AppFlowy/discussions/565. @annieappflowy I think this can be moved to the parent dark mode issue #1671

**Comment by annieappflowy** [comment]
Upcoming v0.1.3 fixed this
![image](https://user-images.githubusercontent.com/12026239/233056858-8a270ffb-7421-420b-a9af-44d35261e4d6.png)
