### ISSUE TITLE
click add create document failed

### ISSUE THREAD

**Issue by rooct** [AppFlowy-IO/AppFlowy#883]
click create document failed, nothing to do

**Comment by annieappflowy** [comment]
@rooct please provide more details. For example, what steps you've made to get to this point? If you can follow our bug issue template, that would help us a lot to better understand your question.

**Comment by rooct** [comment]
> @rooct please provide more details. For example, what steps you've made to get to this point? If you can follow our bug issue template, that would help us a lot to better understand your question.

build from main branch and start client , create document failed

**Comment by annieappflowy** [comment]
Should be fixed

**Comment by rooct** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，系统正在加紧处理中，不需额外提交，只需信息栏和反馈就行，请联系推荐人进行协助。
