### ISSUE TITLE
error : FolderEditor should be initialized after user login in

### ISSUE THREAD

**Issue by rooct** [AppFlowy-IO/AppFlowy#884]
change client , show error : FolderEditor should be initialized after user login in
what can i do this?

**Comment by annieappflowy** [comment]
@rooct please provide a little bit more details on this error you got. What commands did you run? And what outputs did you receive? Thanks

**Comment by appflowy** [comment]
> change client , show error : FolderEditor should be initialized after user login in what can i do this?

Hello, I have a few questions. 
1. What change client means
2. Do you run on the release version or build from the main branch?

**Comment by rooct** [comment]
> > change client , show error : FolderEditor should be initialized after user login in what can i do this?
> 
> Hello, I have a few questions.
> 
> 1. What change client means
> 2. Do you run on the release version or build from the main branch?

nothing change,  but  i had build main branch and failed, then reinstall release version again

**Comment by rooct** [comment]
> @rooct please provide a little bit more details on this error you got. What commands did you run? And what outputs did you receive? Thanks

nothing ,just a client

**Comment by Erik0806** [comment]
I have the same issue. Yesterday I worked normally with AppFlowy and wanted to start it now. Nothing changed on my system (Linux) in that time. When I delete the old data folder I can start with AppFlowy again, but my data is all gone. Tried to open the folder instead of creating a new workspace but that didn't work either. The button on the screenshot also doesn't work. Do you have any ideas?
@annieappflowy 
![Screenshot_20230111_085022](https://user-images.githubusercontent.com/89295098/211748223-69934014-ec1e-4bd7-9a68-b030f26c9609.png)

**Comment by rooct** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，系统正在加紧处理中，不需额外提交，只需信息栏和反馈就行，请联系推荐人进行协助。

**Comment by Erik0806** [comment]
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"Initialize folder manager failed: 0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"Initialize folder manager failed: 0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"Initialize folder manager failed: 0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"Initialize folder manager failed: 0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"Initialize folder manager failed: 0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_revision::rev_manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::manager","error":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"0: \"OTError { code: IncompatibleLength, msg: \\\"Expected: 1134, but received: 0\\\" }\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}
{"msg":"flowy_folder::services::workspace::event_handler","error":"0: \"FolderEditor should be initialized after user login in.\""}


This is the log for today

**Comment by appflowy** [comment]
This [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/1699) is going to fix this problem. It uses a snapshot to restore data when the deserializing error happens. 

Please send me the **flowy** folder, I can help you to store the data. You can find the **flowy** folder by click the debug info button.
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/86001920/212084853-0abb7e34-a1e4-4b2e-93e0-49971394dbcd.png">

**Comment by maanimis** [comment]
> Should be fixed

hi this bug didn't fix i have the same problem
i use docker and got exactly these error:


> {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"Initialize folder manager failed: 0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"Initialize folder manager failed: 0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"Initialize folder manager failed: 0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"Initialize folder manager failed: 0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"Initialize folder manager failed: 0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_revision::rev_manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::manager","error":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"0: "OTError { code: IncompatibleLength, msg: \"Expected: 1134, but received: 0\" }""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""} {"msg":"flowy_folder::services::workspace::event_handler","error":"0: "FolderEditor should be initialized after user login in.""}
> 
> This is the log for today

and i can't do anything the program freeze:
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/106465992/8d71298b-cf75-4919-9fba-c69aa51fee09)
