### ISSUE TITLE
[Bug] Doc is not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by IMPranshu** [AppFlowy-IO/AppFlowy#889]
When I am making a new page and trying to build a new doc it is not working. 

Whenever I click `Doc` nothing happens but when I click `Grid` a new page appears with an empty grid.

![image](https://user-images.githubusercontent.com/43396684/185918265-2274f027-6508-42a8-adc2-179c62b6649a.png)

**Comment by appflowy** [comment]
fix #891
