### ISSUE TITLE
[FR] Implement embed code 

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#911]
**Feature Scope**
- [ ] Implement embed code
  - [ ] [Figma UI](https://www.figma.com/file/X1R9i5HAFtJSNIKOPPW7yK/AppFlowy-%5BUI%5D%5BMaster%5D?node-id=862%3A411799)
  - [ ] change raw text into embed code by
    - [ ] clicking the icon in the toolbar menu
    - [ ] pressing the command or control + E
 - [ ] Optional: convert text surrounded by \`\` to code, like \`abc\` to `abc`

**Test cases**
- [ ] add test cases

**Comment by rileyhawk1417** [comment]
Hi can I try and take this issue?

**Comment by LucasXu0** [comment]
#985
