### ISSUE TITLE
[Doc] Remove unused blocks 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#923]
https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/requirements

reported by Kai on Discord

**Comment by IMPranshu** [comment]
So what I understood is that the contents of the page have to be removed as they are incomplete.
![image](https://user-images.githubusercontent.com/43396684/187239393-0bb08183-6827-40a9-b7d1-bff83deaff68.png)
