### ISSUE TITLE
[FR] appflowy_editor supports more highlighting colors

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#941]
**1~3 main use cases of the proposed feature**
As a user who loves to use formatting options to highlight different things, I would like to use a variety of highlight colors to highlight text to convey different meanings. Atm, only one highlight color is available.
<img width="816" alt="image" src="https://user-images.githubusercontent.com/12026239/187413365-cf633fc4-6a6d-4b48-bff7-d9ed0a681566.png">
Better to support people to add their customized color themes / palettes.

**Comment by annieappflowy** [comment]
@ChiragKr04 similar to the Color option (right next to the Highlight option)

**Comment by dejvizelo** [comment]
I would like to work on this issue

**Comment by dejvizelo** [comment]
Can you elaborate a bit more on the color palette plugin? Also, how can I reach @LucasXu0 on the Discord server?

**Comment by annieappflowy** [comment]
> Can you elaborate a bit more on the color palette plugin? Also, how can I reach @LucasXu0 on the Discord server?

You can reach him via direct messaging on Discord.

**Comment by Xazin** [comment]
According to discussion on Discord (#appflowy-editor) this can be closed I believe, as done.

**Comment by rileyhawk1417** [comment]
PR has been merged in the [editor repo](https://github.com/AppFlowy-IO/appflowy-editor/pull/270)
