### ISSUE TITLE
[FR]Support inserting pictures

### ISSUE THREAD

**Issue by anbeibei** [AppFlowy-IO/AppFlowy#971]
Support inserting pictures，thanks

**Comment by annieappflowy** [comment]
@anbeibei can you elaborate on your request a little bit more?
For example, where do you want to insert pictures? eg: Grid, Doc, or Board?
And what kind of benefits would you receive by being able to insert pictures?

**Comment by MayurSMahajan** [comment]
@annieappflowy can we close this?
