### ISSUE TITLE
[FR] Windows builds for each release

### ISSUE THREAD

**Issue by djibe** [AppFlowy-IO/AppFlowy#975]
Offer systematic builds for Windows platforms.

Windows is the main OS worldwide.

Thanks a lot.
I'll try to compile myself meanwhile.

**Comment by djibe** [comment]
Did it, 0.0.5 beta 2

[Appflowy-windows-x86_64.zip](https://github.com/AppFlowy-IO/AppFlowy/files/9483128/Appflowy-windows-x86_64.zip)

**Comment by annieappflowy** [comment]
Thanks a lot @djibe . @LucasXu0 is currently working on this

**Comment by djibe** [comment]
Thanks @annieappflowy 
I did a PR on the docs to make sure any newcomer like me can build on Windows (11 for my part)

**Comment by annieappflowy** [comment]
Thank you! Can you share me the link to your PR? I'll take a look

**Comment by djibe** [comment]
Here it is: https://github.com/AppFlowy-IO/AppFlowy-Docs/pull/25/commits/99fe6765cf4780190eb611e298a89db1121b21e5

**Comment by annieappflowy** [comment]
@djibe, it looks very well-written! Will give it a run and approve. Thanks for contributing.

**Comment by djibe** [comment]
Glad you like it :D 
I like to share knowledge.

**Comment by wharjack** [comment]
Thank you for building it for us. The text render is still bad in windows

**Comment by annieappflowy** [comment]
Hi @wharjack , the application has been improved (a lot). Please have a try ([link ](https://github.com/AppFlowy-IO/AppFlowy/releases)to the latest release) and let us know if the text is still not good. We'll keep improving.
